### ISSUE TITLE
Captagent: Can't use () in filters

### ISSUE THREAD

**Issue by loxybjorn** [sipcapture/homer#100]
I can't seem to get parentheses in capture filters to work.

I'm using captagent v4.2.0.

```xml
<param name="filter" value="and (net 10.234.34.0/24 or net 10.233.33.0/24)"/>
```
makes captagent log this:
```
[DEBUG] proto_uni.c:483 FILTER: [ port 5060  and udp  and (net 10.234.34.0/24 or net 10.233.33.0/24)]
[ERR] proto_uni.c:487 Failed to compile filter " port 5060  and udp  and (net 10.234.34.0/24 or net 10.233.33.0/24)": syntax error
```

and
```xml
<param name="filter" value="and \(net 10.234.34.0/24 or net 10.233.33.0/24\)"/>
```
makes captagent log this:

```
[DEBUG] proto_uni.c:483 FILTER: [ port 5060  and udp  and \(net 10.234.34.0/24 or net 10.233.33.0/24\)]
[ERR] proto_uni.c:487 Failed to compile filter " port 5060  and udp  and \(net 10.234.34.0/24 or net 10.233.33.0/24\)": illegal token: \
```

Should it be possible, if so, how?

**Comment by adubovikov** [comment]
man 7 pcap-filter

<param name="filter" value="and (net 10.234.34.0 or net 10.233.33.0)"/>

or

<param name="filter" value="and (net 10.234.34 or net 10.233.33)"/>

or clasic schema:

<param name="filter" value="and (net 10.234.34.0 mask 255.255.255.0 or net 10.233.33.0 mask 255.255.255.0)"/>

**Comment by loxybjorn** [comment]
Hmm, ok, thank you. My libpcap version (0.8) supports using "/" however. tcpdump handles it fine and it's documented in the pcap-filter man page -> I thought captagent would allow it.

**Comment by adubovikov** [comment]
Please check if the captagent was compiled with right libpcap version.

With mobile regards,
Alexandr Dubovikov

**Comment by loxybjorn** [comment]
# ldd /usr/local/bin/captagent
        linux-vdso.so.1 =>  (0x00007ffde63f2000)
        libpcap.so.0.8 => /usr/lib/x86_64-linux-gnu/libpcap.so.0.8 (0x00007f6a88132000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f6a87f08000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6a87d03000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6a87ae7000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6a8775c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6a88179000)

Looks like 0.8 to me...

Regards,
/Björn Bylander

**Comment by adubovikov** [comment]
maybe i have wrong manual, but it says:
```
dst net net
True if the IPv4/v6 destination address of the packet has a network number of net. Net may be either a name from the networks database (/etc/networks, etc.) or a network number. An IPv4 network number can be written as a dotted quad (e.g., 192.168.1.0), dotted triple (e.g., 192.168.1), dotted pair (e.g, 172.16), or single number (e.g., 10); the netmask is 255.255.255.255 for a dotted quad (which means that it's really a host match), 255.255.255.0 for a dotted triple, 255.255.0.0 for a dotted pair, or 255.0.0.0 for a single number. An IPv6 network number must be written out fully; the netmask is ff:ff:ff:ff:ff:ff:ff:ff, so IPv6 "network" matches are really always host matches, and a network match requires a netmask length.
src net net
True if the IPv4/v6 source address of the packet has a network number of net.
net net
True if either the IPv4/v6 source or destination address of the packet has a network number of net.
net net mask netmask
True if the IPv4 address matches net with the specific netmask. May be qualified with src or dst. Note that this syntax is not valid for IPv6 net.
net net/len
True if the IPv4/v6 address matches net with a netmask len bits wide. May be qualified with src or dst.
```

if you have different or an additional information, please provide.

**Comment by loxybjorn** [comment]
Hmm, well, "and (net 10.234.34.0/24 or net 10.233.33.0/24)" seems, to me, to be the last variant from your manual (which matches with mine), no? What do you find incorrect with that syntax?

**Comment by adubovikov** [comment]
heh, you are right, i will check deep next week why captagent doesnt accept with syntax.

thanks for the bug report.

**Comment by loxybjorn** [comment]
Good, I'm glad to be able to contribute :)

**Comment by lmangani** [comment]
Thanks for the report! Next time if possible, kindly use the Captagent repository to file the issue: https://github.com/sipcapture/captagent

**Comment by loxybjorn** [comment]
Oh, sorry, for some reason I didn't realize I was in the wrong project :confused:

**Comment by lmangani** [comment]
@loxybjorn Bjorn, apologies but in an effort to provide followup, could you kindly close this issue and re-open it on the captagent tracker?
