### ISSUE TITLE
With sipcapture() method for > 4.3, time zone offset breaks search

### ISSUE THREAD

**Issue by joshelson** [sipcapture/homer#105]
When switching from this syntax:

$var(a) = $var(table) + "_" + $timef(%Y%m%d);

to this:

$var(a) = $var(table) + "_%Y%m%d";

in the STORE route, when the system (either side) is in non-UTC time, Kamailio starts writing the packets to the _date database table at the wrong time.  So for a UTC-6 Asterisk box and a UTC-6 Homer node, at 18:00, packets move into the next day.

Reverting to the 4.3 or older Kamailio behavior resolves this.

**Comment by joshelson** [comment]
Stay tuned, not 100% sure on this yet, but it looks like explicitly setting the mysql time zone may resolve this.  My mysql instance was running in UTC, but the server was in UTC-6.

You can check that with: 

SELECT TIMEDIFF(NOW(), UTC_TIMESTAMP);

Might be worth documenting that all this needs to be in sync, or you won't get data where you expect it.

**Comment by lmangani** [comment]
Good catch Joshua,

The mysql timezone should indeed be correctly set for things to work as
intended - Thanks for sharing this and let us know if you can confirm this
is the case.

Kind Regards,

Lorenzo Mangani
*Managing Director and Core Dev*

QXIP BV - Capture Engineering
Amsterdam, The Netherlands

Desk: +31 20 8080468 / +1 202-632-7227
Mobile: +31 6 4603-2730
Email: info@qxip.net

Find our more about HOMER, PCAPTURE, CAPTAGENT and all our Services and
Solutions at http://qxip.net

CONFIDENTIALITY NOTICE: This e-mail message, including any attachments, is
for the sole use of the intended recipient(s) and may contain confidential or
legally privileged information. Any unauthorized review, use, disclosure or
distribution is prohibited. If you are not the intended recipient,
please contact
the sender by reply e-mail and destroy all copies of this original message.

**Comment by adubovikov** [comment]
the last version of sipcapture (kamailio) should convert the "_%Y%m%d" to UTC TZ.


	tvsec_ = (time_t) (sco->tmstamp/1000000);        		
	if(gmtime_r( &tvsec_, &capt_ts) == NULL)
		{
			LM_ERR("unable to set time to attributes\n");
			return -1;
		}

	ntab.len = strftime(strftime_buf, sizeof(strftime_buf), table->s,  &capt_ts);
	ntab.s = strftime_buf;


The gmtime() function converts the calendar time timep to broken-down time representation, expressed in Coordinated Universal Time (UTC). It may return NULL when the year does not fit into an integer. The return value points to a statically allocated struct which might be overwritten by subsequent calls to any of the date and time functions. The gmtime_r() function does the same, but stores the data in a user-supplied struct.

can you please run tcpdump on port 3306 and check if the tablename has correct timestamp ?

**Comment by joshelson** [comment]
So there's still something weird here.  With all the zones (server and database) sync'd to UTC-6, I am still getting the following behavior.

For database sip_capture_call_20151025 I get normal entries until 17:59:59.

At 18:00, the entries start to populate to sip_capture_call_20151026.  The date column for the first sip_capture_call_20151026 is 2015-10-25 18:00:00 and it continues until the day actually rolls over.

It looks like Kamailio is properly converting it to UTC, but not adjusting for the fact that we're still in UTC-6.

**Comment by adubovikov** [comment]
thats correct, as I wrote in the last reply, the table name will be in UTC+0 timezone, not in your local TZ

**Comment by miha-** [comment]
Hi,

i have exactly the same problem. So, what is the solution for this?

tnx
miha

**Comment by adubovikov** [comment]
miha,
the timestamp of sip_capture table is also in UTC timezone, not in your local. This needs to store and retrieve all messages in correct way.
sorry, but here is no issue at all.
