### ISSUE TITLE
Rest api questions. 

### ISSUE THREAD

**Issue by soulofmischief87** [sipcapture/homer#106]
Where can I get information about the rest api?

I tried doing a get on /api/ 

and I get 
{
  "sid": "mmjf4vus9j0rc4i7ts9099qr15",
  "auth": "false",
  "status": "wrong-session"
}

when  using authenticated session via the browser I get 

{"server":"apiserver","language":"en","status":"not good","message":"Unknown get call: []","data":[],"totalrecords":0}

Thanks

**Comment by lmangani** [comment]
Hi, 

The HOMER-API package includes an apidoc folder, it should provide you all you need.
We will soon release full documentation to make this more obvious.

Thanks!
