### ISSUE TITLE
Aliases are not shown in Call flow.

### ISSUE THREAD

**Issue by olincho** [sipcapture/homer#107]
Hello,

I'm having problem with the Aliases on the Homer Node. Aliases already configured on the admin page.

define('CFLOW_HPORT', 2); on preferences.php

but still the aliases are not showing on the call flow.

![cflow](https://cloud.githubusercontent.com/assets/15692370/11002344/9ff961ee-8482-11e5-8849-c5da7b949724.JPG)

![addalias](https://cloud.githubusercontent.com/assets/15692370/11002348/a4f8b8e8-8482-11e5-9325-c0db17c9fd6d.JPG)

Everything else is working prefectly.
 
Im running on a port mirroring scenario with 2 NICs on the Capture Node.

**Comment by adubovikov** [comment]
Hi,

Will be very nice if you can tell us how you fix it or where was the problem 

Thank you.

**Comment by olincho** [comment]
Sorry,

a moment after submitted the issue, i realized that the capture_id is the capture node id "homer01" in my case, after update that field with the correct info, the call flow looks good. Thank you for bring this product up, and sorry for waste your time! :) i would check the Mailing-List  first, before summit any issues here in the future.
