### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by scristopher** [sipcapture/homer#109]
Hello, 
I've been trying to follow the instructions as close as possible but there seem to be some issues with the data and the instructions matching up, sorry if this has been brought up already. 

First, when setting up the databases
>create database homer_data ( < $GIT/homer-api/sql/schema_capture.sql) 

This file does not exist, I'm assuming it is supposed to be homer-api/sql/schema_data.sql

So I've followed up to the end instructions, tried using apache and nginx, and cannot login using the admin/test123. It seems I it is trying to post to a non-existent directory, however I'm unsure if this is by design or not

...
[11/Nov/2015:11:55:58 -0500] "POST /api/v1/session HTTP/1.1" 500 161 "http://phoenix.mydomain.tld/"
...

nginx config looks good:

    server {

	listen 80 default_server;

	root /var/www/sipcapture;
	index index.html index.htm;

	# Make site accessible from http://localhost/
	server_name phoenix.mydomain.tld;

	location / {
	    try_files $uri $uri/ /index.html;
	}

	location /api {
	    include fastcgi_params;
	    fastcgi_intercept_errors on;
	    fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
	    fastcgi_param  SCRIPT_FILENAME $document_root/api/index.php;
        }
    }

Any suggestions?

**Comment by lmangani** [comment]
Hi @scristopher and welcome to the early birds Homer5 club. Did you install php5-fpm? 
You might also need the following in php.ini:
<pre>
"cgi.fix_pathinfo = 0;" 
</pre>

**Comment by scristopher** [comment]
Thanks for the reply,
Yes php-fpm is installed, I have enabled "cgi.fix_pathinfo = 0;"  in php.ini but to no avail. The only error I am seeing is the 500 error mention in my first post. Tripled checked my database settings again, but I'm not sure its making it to query my authentication info.

**Comment by scristopher** [comment]
Oh my, I'm awful sorry to bother you, seems to be on my end. I should have quadurpal checked my sql connection. Thanks for the patience, found it while thinking the error was larger than it really was.

http://pastebin.com/HzpSETjS

**Comment by lmangani** [comment]
our pleasure!
