### ISSUE TITLE
Homer5 User Menu Options Appear Unresponsive

### ISSUE THREAD

**Issue by kismetgerald** [sipcapture/homer#110]
So, I'm still struggling to get capture packets working from my Freeswitch server to Homer5.  However, while I'm waiting to fix that I decided to give the Web Interface a try and I noticed something immediately with the interface.  So I thought I'd share it with you, in case it's something that needs fixing in code.

I noticed that the user menu (top-right corner icon) has some sub-menu items that simply do nothing when clicked on.  Nothing seems to happen when I click on Profile, Settings, Notifications, or Messages.  However, if I should click on Reset Profile or Logout, I immediately get logged out of the web interface.

I'm not sure if this is specific to my system, but I thought I'd report it.  See the attached screenshot.

### PS.  I'm running Debian 8 (Jessie)
```
Linux freeswitch2 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
```
```
root@freeswitch2:~# lsb_release -da
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.2 (jessie)
Release:        8.2
Codename:       jessie
```
![snap 2015-11-13 at 13 33 07](https://cloud.githubusercontent.com/assets/14914151/11154482/9acdddb8-8a0d-11e5-82a1-a5794901e231.png)

**Comment by lmangani** [comment]
I understand this might be confusing - those options are in development, i commented them out until finished to avoid misleading users.

**Comment by kismetgerald** [comment]
oh okay, thanks for the response.  I won't lose sleep over them then.
