### ISSUE TITLE
Delete Buttons Not Working

### ISSUE THREAD

**Issue by kismetgerald** [sipcapture/homer#111]
On a fresh install of Homer5 on Debian 8.1 x64, I just realized that all the delete buttons in the web interface (Delete User, Delete Alias, and Delete Node) don't actually do anything.  Any idea what could be wrong?

**Comment by kismetgerald** [comment]
Guys, I'm not sure what happened but the buttons are now working all of a sudden.  Hmmm, maybe a cache problem, I don't know but they are working now.

**Comment by lmangani** [comment]
Weird indeed - if you run into this again, please reopen the ticket and post console logs, thanks!
