### ISSUE TITLE
Debian 8.2 problem by making homer.deb file

### ISSUE THREAD

**Issue by ciscospirit** [sipcapture/homer#113]
Hello,

i tried to do the "Build Custom Packages (advanced)" how-to descripted in this thread: 
https://github.com/sipcapture/homer/wiki/Quick-Install

But at the end, as I did "make debian-jessie-x86_64.homer.deb" i got an error "Makefile:389: recipe for target 'distdir' failed"

How can I fix this problem?

Thank You

root@homer:/usr/src/homer/build# make debian-jessie-x86_64.homer.deb
make homer.deb DISTRO=debian-jessie-x86_64
make[1]: Entering directory '/usr/src/homer/build'
Dummy target repo-update
checking for changes in homer-api...make[2]: Entering directory '/usr/src/homer/build'
make[3]: Entering directory '/usr/src/homer/build'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
make distdir for homer-api...
make[4]: Entering directory '/usr/src/homer/build/homer-api'
cp: ‘./api’ and ‘./api’ are the same file
Makefile:389: recipe for target 'distdir' failed
make[4]: *** [distdir] Error 1
make[4]: Leaving directory '/usr/src/homer/build/homer-api'
mak/10-deb.mk:49: recipe for target 'homer-api.distdir' failed
make[3]: *** [homer-api.distdir] Error 2
make[3]: Leaving directory '/usr/src/homer/build'
mak/10-deb.mk:27: recipe for target 'debian-jessie-x86_64.homer-api.deb' failed
make[2]: *** [debian-jessie-x86_64.homer-api.deb] Error 2
make[2]: Leaving directory '/usr/src/homer/build'
mak/10-deb.mk:44: recipe for target 'homer-api.deb.if-changed' failed
make[1]: *** [homer-api.deb.if-changed] Error 2
make[1]: Leaving directory '/usr/src/homer/build'
mak/10-deb.mk:27: recipe for target 'debian-jessie-x86_64.homer.deb' failed
make: *** [debian-jessie-x86_64.homer.deb] Error 2

**Comment by kvishnivetsky** [comment]
It is a known issue. To solve this "quick", please clean build and reinit build directory.
We will fix this in future.
Thanks for your report.

**Comment by ciscospirit** [comment]
so... after deleting the whole "homer" directory and running all comands again, the make process works now.

**Comment by lmangani** [comment]
Closing - reopen if needed.
