### ISSUE TITLE
Homer 5.0 RC1 - Problems with the Dashboard view

### ISSUE THREAD

**Issue by ciscospirit** [sipcapture/homer#114]
Hey,

if you open a trace detail the popup is everytime too far on the right side in chrome browser.
it is always cutted in the middle.
you must take it everytime with the mouse and move it to the middle of the screen to see full informations.

also the date value is in american style in the overview:  there is 2015-20-11 instead of 2015-11-20 but in the details popup there is right date format.

also the time in detail is in UTC time but, in overview is utc+1.

**Comment by ciscospirit** [comment]
SIP search results just showing 100 total items and not more.

**Comment by lmangani** [comment]
There is a "Limit Query" parameter which rules the number of results. Enable/Activate on your SIP search panel in order to show in the form and use limit.
