### ISSUE TITLE
Tables in MySQL are not created automatically

### ISSUE THREAD

**Issue by samael33** [sipcapture/homer#115]
Hi!
I've installed Homer-httpd via rpm package manager.
Issue:
Tables sip_capture_<type>_<date> in homer_data database are not created automatically(at least, only 3 of them was there, on 4th day I have to create it by hand)
mysql> show tables;
+-----------------------------------+
| Tables_in_homer_data              |
+-----------------------------------+
| logs_capture                      |
| report_capture                    |
| rtcp_capture                      |
| sip_capture_call_20151119         |
| sip_capture_call_20151120         |
| sip_capture_call_20151121         |
| sip_capture_call_20151123         |
| sip_capture_registration_20151119 |
| sip_capture_registration_20151120 |
| sip_capture_registration_20151121 |
| sip_capture_registration_20151123 |
| sip_capture_rest_20151119         |
| sip_capture_rest_20151120         |
| sip_capture_rest_20151121         |
| sip_capture_rest_20151123         |
Tables with 20151123 are created by hand with CREATE TABLE ... LIKE ...
I think it's cause of 

Nov 23 12:22:56 localhost /sbin/kamailio[2418]: WARNING: <core> [timer.c:429]: adjust_ticks(): our timer runs faster then real-time (343007000 ms / 5488112 ticks our time .-> 342989457 ms / 5487831 ticks real time)
Nov 23 12:29:36 localhost /sbin/kamailio[2411]: ERROR: db_mysql [km_dbase.c:121]: db_mysql_submit_query(): driver error on query: Table 'homer_data.sip_capture_rest_20151123' doesn't exist

So, may be not really issue of homer, but time sync.

**Comment by kvishnivetsky** [comment]
Thank you for the participation. :-)
What tables are created just after installation?
May you paste installation log, please?
Are there any errors or warnings with a cron job /usr/bin/homer_rotate in system log?

**Comment by samael33** [comment]
1. Installation log - where can I find it?
2. Cron.
Found in /etc/cron.d/sipcapture
30 3 * * * root /usr/bin/homer_rotate > /dev/null 2>&1
changed it to 
0 0 * * * /usr/bin/homer_rotate > /dev/null 2>&1
3. OS:  CentOS7 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
4. homer-api
Name        : homer-api
Arch        : x86_64
Version     : 5.0.1
Release     : 20151118054522

**Comment by kvishnivetsky** [comment]
1. Installation log located @ /var/log/yum.log
2. I think run time 03:30 AM for cron job is not an issue. ;-)
3-4. Thanks!

**Comment by samael33** [comment]
No, main thing about 2 was get rid of 'root' word before command. As I know, you don't need to specify user before command in crontab.

**Comment by kvishnivetsky** [comment]
2. cat /etc/crontab
# /etc/crontab: system-wide crontab
# Unlike any other crontab you don't have to run the `crontab'
# command to install the new version when you edit this file
# and files in /etc/cron.d. These files also have username fields,
# that none of the other crontabs do.

**Comment by samael33** [comment]
Anyway, this helps )

**Comment by kvishnivetsky** [comment]
It can't help, I'm sure, because we have productve installation with the same cron settings and it works just fine.

**Comment by lmangani** [comment]
Thanks @samael33 for the input, much appreciated and I hope the solution was clear. Re-Open if necessary.
