### ISSUE TITLE
Cannot login after install

### ISSUE THREAD

**Issue by mbodbg** [sipcapture/homer#116]
I've installed homer according to the instructions on a fresh debian jessy vm. I can call the login dialog, but when I try to login with admin/test123 I can see the following error in the browser. 

TypeError: Cannot read property 'grp' of undefined
    at authentication.js:41
    at I (angular.min.js:11446)
    at angular.min.js:11532
    at k.$eval (angular.min.js:12556)
    at k.$digest (angular.min.js:12368)
    at k.$apply (angular.min.js:12660)
    at h (angular.min.js:8272)
    at x (angular.min.js:8477)
    at XMLHttpRequest.z.onreadystatechange (angular.min.js:8416)

On the server side, the error log (sipcapture-error.log) is empty. Is there anything also I can check?

**Comment by lmangani** [comment]
Your API is not serving content. Check your Apache2 config and make sure rewrite mod is enabled

**Comment by mbodbg** [comment]
mod_rewrite is enabled. I'm using the apache config from here:
https://github.com/sipcapture/homer-api/blob/master/examples/web/homer5.apache, is this still up to date?

Here a screenshot with some more info. Is there anything else what I can check?

<img width="1433" alt="homer type error" src="https://cloud.githubusercontent.com/assets/360757/11350174/87cedb88-9230-11e5-9b3b-932a56ae91d3.png">

**Comment by lmangani** [comment]
the screenshot suggests the server returning php as plain files, check if php5 and apache2 modules for it were correctly installed or feel free to tell us what you installed and we'll try to point at what might be missing.

**Comment by mbodbg** [comment]
The package php5 wasn't correctly installed. After reinstall it works now. Thanks for your support.

**Comment by lmangani** [comment]
Our pleasure!
