### ISSUE TITLE
homer installation doesn't work

### ISSUE THREAD

**Issue by mveerdon** [sipcapture/homer#117]
Hello,
when using the install script I receive some errors at the end. Little bit a newbie to Homer so can someone help/advise what to do next?

Thanks!

########
sudo yum install -y git epel-release @Development
cd /usr/src/
git clone -b homer5 https://github.com/sipcapture/homer.git
cd homer
git submodule init
git submodule update
autoreconf -if
mkdir -p build
cd build
../configure --enable-rpm
make setup.sh
export PATH=/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/root/bin
sudo ./setup.sh

make centos-7-x86_64.homer.rpm
######

INFO: Finish: rpmbuild captagent-6.0.1-8.ce7b0.el7.centos.src.rpm
INFO: Finish: build phase for captagent-6.0.1-8.ce7b0.el7.centos.src.rpm
INFO: Done(repo/centos/7/source/captagent-6.0.1-8.ce7b0.el7.centos.src.rpm) Config(centos-7-x86_64) 0 minutes 46 seconds
INFO: Results and/or logs in: repo/centos/7/x86_64
INFO: Finish: run
Spawning worker 0 with 12 pkgs
Spawning worker 1 with 12 pkgs
Workers Finished
Saving Primary metadata
Saving file lists metadata
Saving other metadata
Generating sqlite DBs
Sqlite DBs complete
make[3]: Leaving directory `/usr/src/homer/build'
make[2]: Leaving directory `/usr/src/homer/build'
checking for changes in kamailio...make[2]: Entering directory `/usr/src/homer/build'

make[3]: Entering directory `/usr/src/homer/build'
make[4]: Entering directory `/usr/src/homer/build/kamailio'
Makefile:107: config.mak: No such file or directory
target architecture <x86_64>, host architecture <x86_64>
making config...
make[4]: Leaving directory `/usr/src/homer/build/kamailio'
make[4]: Entering directory `/usr/src/homer/build/kamailio'
generating autover.h ...
make[4]: Leaving directory `/usr/src/homer/build/kamailio'
tar (child): kamailio/kamailio-5.0.1.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
fatal: No names found, cannot describe anything.
Could not find tag v4.3.3
fatal: No names found, cannot describe anything.
Could not find tag 4.3.3
fatal: No names found, cannot describe anything.
Could not find tag v4.3.3
fatal: No names found, cannot describe anything.
Could not find tag v4.3.3
fatal: No names found, cannot describe anything.
Could not find tag 4.3.3
fatal: No names found, cannot describe anything.
Could not find tag v4.3.3
error: File kamailio/kamailio-4.3.3_src.tar.gz: No such file or directory
/usr/bin/cat: kamailio/kamailio-4.3.3_src.tar.gz: No such file or directory
error: File kamailio/kamailio-4.3.3_src.tar.gz: No such file or directory
/usr/bin/cat: kamailio/kamailio-4.3.3_src.tar.gz: No such file or directory
error: Failed to read spec file from kamailio/kamailio-4.3.3_src.tar.gz
make[3]: *** [kamailio.srpm] Error 1
make[3]: Leaving directory `/usr/src/homer/build'
make[2]: *** [centos-7-x86_64.kamailio.rpm] Error 2
make[2]: Leaving directory `/usr/src/homer/build'
make[1]: *** [kamailio.rpm.if-changed] Error 2
make[1]: Leaving directory `/usr/src/homer/build'
make: *** [centos-7-x86_64.homer.rpm] Error 2
[root@localhost build]#

**Comment by lmangani** [comment]
@mveerdon we will check - meanwhile, have you tried using our pre-built packages?

Add our repository:
```curl https://bintray.com/sipcapture/homer-yum/rpm -o /etc/yum.repos.d/sipcapture.repo```

Enable EPEL + MySQL Community:
```sudo yum install -y epel-release https://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm```

Install HOMER + nginx:
```sudo yum install homer-nginx```

**Comment by kvishnivetsky** [comment]
I confirm the issue. Fixing.
@mveerdon, thank you for feedback!

**Comment by kvishnivetsky** [comment]
Fixed: https://github.com/sipcapture/homer/commit/cdcac33dee1d2dc4cb38a092632da1df04ed8198
Check it, please. Kamailio version changed from 4.3.3 to 4.3.4.

**Comment by lmangani** [comment]
Thanks @kvishnivetsky ;)

**Comment by mveerdon** [comment]
@lmangani thanks for your reply.

what to do after sudo yum install homer-nginx?
./configure

and then? How do I start Homer service?

**Comment by lmangani** [comment]
@mveerdon services (kamailio+sipcapture, mysql and nginx/php) should be automatically started if installation succeeds - please let us know if this is not the case and we'll assist

**Comment by mveerdon** [comment]
@lmangani 

I don't see any services active on my CentOS7 vm

[root@localhost homer]# ls -ltr
total 248
-rw-r--r--.  1 root root   5530 Nov 28 14:03 README.md
-rw-r--r--.  1 root root   2205 Nov 28 14:03 Makefile.in
-rw-r--r--.  1 root root  34501 Nov 28 14:03 LICENSE
-rw-r--r--.  1 root root     90 Nov 28 14:03 INSTALL.md
-rw-r--r--.  1 root root   1158 Nov 28 14:03 configure.ac
drwxr-xr-x.  4 root root   4096 Nov 28 14:03 distr
drwxr-xr-x.  2 root root   4096 Nov 28 14:03 tools
drwxr-xr-x. 20 root root  12288 Nov 28 14:04 kamailio
drwxr-xr-x.  2 root root   4096 Nov 28 14:04 autom4te.cache
-rwxr-xr-x.  1 root root 101287 Nov 28 14:04 configure
drwxr-xr-x.  9 root root   4096 Nov 28 14:05 homer-api
drwxr-xr-x.  2 root root   4096 Nov 28 14:11 config
drwxr-xr-x. 14 root root   4096 Nov 28 14:11 homer-ui
drwxr-xr-x.  8 root root   4096 Nov 28 14:12 captagent
drwxr-xr-x. 11 root root   4096 Nov 28 14:13 build
-rwxr-xr-x.  1 root root  28814 Nov 30 13:23 config.status
-rw-r--r--.  1 root root   2117 Nov 30 13:24 Makefile
-rw-r--r--.  1 root root   7371 Nov 30 13:24 config.log
drwxr-xr-x.  4 root root   4096 Nov 30 13:24 mak
[root@localhost homer]# 
[root@localhost homer]# service --status-all
netconsole module not loaded
Configured devices:
lo eth0
Currently active devices:
lo eth0 virbr0
=> This script starts/stops Parallels guest tools' service
Usage: /etc/init.d/prltoolsd <start | stop | restart>
Usage: /etc/init.d/prl-x11 {start}
[root@localhost homer]# 
[root@localhost homer]#

**Comment by mveerdon** [comment]
Hello @lmangani, do you have any idea why 0 services are running with my configuration?

regards, Marty

**Comment by kvishnivetsky** [comment]
Hello @mveerdon, please post an output of:
ps ax | grep -E 'kamailio|php|nginx|mysql'

**Comment by mveerdon** [comment]
[root@localhost homer]# ps ax | grep -E 'kamailio|php|nginx|mysql'
 2267 ?        Sl     3:32 /usr/sbin/mysqld --daemonize --explicit_defaults_for_timestamp
 3074 ?        S      0:00 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 3075 ?        S      0:00 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 3076 ?        S      0:00 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 3077 ?        S      0:00 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 3078 ?        S      0:00 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 3079 ?        S      0:00 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 3080 ?        S      0:01 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 3081 ?        S      2:49 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 3082 ?        S      0:04 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 5330 pts/0    S+     0:00 grep --color=auto -E kamailio|php|nginx|mysql
[root@localhost homer]#

**Comment by adubovikov** [comment]
please start nginx and php-fpm, it should helps.

**Comment by lmangani** [comment]
@mveerdon any logs from your system related to service startup failures would help if available

**Comment by kvishnivetsky** [comment]
@mveerdon for full clearence: did you install from RPMs or from Sources?

**Comment by mveerdon** [comment]
I used the RPM from https://github.com/sipcapture/homer/wiki/Quick-Install

**Comment by mveerdon** [comment]
After installing nginx and php-fpm this is the result
'''
[root@localhost log]# 
[root@localhost log]# ps ax | grep -E 'kamailio|php|nginx|mysql'
  913 pts/0    S+     0:00 grep --color=auto -E kamailio|php|nginx|mysql
 2267 ?        Sl     3:39 /usr/sbin/mysqld --daemonize --explicit_defaults_for_timestamp
 3074 ?        S      0:00 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 3075 ?        S      0:00 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 3076 ?        S      0:00 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 3077 ?        S      0:00 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 3078 ?        S      0:00 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 3079 ?        S      0:00 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 3080 ?        S      0:01 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 3081 ?        S      2:54 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
 3082 ?        S      0:04 /sbin/kamailio -f /etc/kamailio/kamailio-sipcapture.cfg -P /var/run/sipcapture/sipcapture.pid -m 32 -M 4 -u kamailio -g kamailio
31125 ?        Ss     0:00 nginx: master process /usr/sbin/nginx
31126 ?        S      0:00 nginx: worker process
31127 ?        S      0:00 nginx: worker process
[root@localhost log]# 
'''

**Comment by adubovikov** [comment]
nginx is up, but please check why php-fpm is still down.

**Comment by kvishnivetsky** [comment]
Please, grep php /var/log/messages

**Comment by mveerdon** [comment]
[root@localhost log]# grep php /var/log/messages
Dec  4 14:38:49 localhost yum[32056]: Installed: php-fpm-5.4.16-36.el7_1.x86_64
Dec  4 14:39:43 localhost yum[32336]: Installed: php-pecl-zip-1.13.1-1.el7.remi.5.5.x86_64
Dec  4 14:39:43 localhost yum[32336]: Installed: php-pecl-jsonc-1.3.9-1.el7.remi.5.5.x86_64
Dec  4 14:39:44 localhost yum[32336]: Updated: php-common-5.5.30-1.el7.remi.x86_64
Dec  4 14:39:44 localhost yum[32336]: Updated: php-pdo-5.5.30-1.el7.remi.x86_64
Dec  4 14:39:45 localhost yum[32336]: Updated: php-cli-5.5.30-1.el7.remi.x86_64
Dec  4 14:39:46 localhost yum[32336]: Updated: php-5.5.30-1.el7.remi.x86_64
Dec  4 14:39:46 localhost yum[32336]: Installed: php-mysqlnd-5.5.30-1.el7.remi.x86_64
Dec  4 14:39:46 localhost yum[32336]: Updated: php-fpm-5.5.30-1.el7.remi.x86_64
Dec  4 14:39:48 localhost yum[32336]: Erased: php-mysql-5.4.16-36.el7_1.x86_64

**Comment by kvishnivetsky** [comment]
Hi, @mveerdon.
About CentOS7 packages build. Here is a BUG: https://bugzilla.redhat.com/show_bug.cgi?id=636616
Did you meet the same issue trying to build RPMs on C7?

**Comment by kvishnivetsky** [comment]
No feedback from an issuer for a long time.
Please, Re-open if needed.
Closing.
