### ISSUE TITLE
App Doesn't Run

### ISSUE THREAD

**Issue by peconi** [sipcapture/homer#119]
Finally installed it by building my own RPM for CentOS 6, alas, when I install the RPM's and run it, all I see is a blank page and the favicon loaded.

Looking into developer tools in chrome I get:
- SweetAlert-base.min.js:1 Uncaught SyntaxError: Unexpected token <
--> That's at the very top @ <!DOCTYPE declaration

Second error:
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.2.18/$injector/modulerr?p0=homerApp&p1=Error%…0e%20(http%3A%2F%2Fhomer.local%2Flib%2Fangular%2Fangular.min.js%3A33%3A139)(anonymous function) @ angular.min.js:36(anonymous function) @ angular.min.js:3845q @ angular.min.js:320e @ angular.min.js:3811ec @ angular.min.js:3751c @ angular.min.js:1410dc @ angular.min.js:1425Wc @ angular.min.js:1338(anonymous function) @ angular.min.js:21713l @ jquery.min.js:4c.fireWith @ jquery.min.js:4x.extend.ready @ jquery.min.js:4S @ jquery.min.js:4

Hope someone can assist me with this :)

Thank you!

**Comment by adubovikov** [comment]
Please check if you have the last git or if SweetAlert-base.min.js exists
in your installation.

Thank you!


Wbr,
Alexandr
<https://www.avast.com/?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Это
сообщение было отправлено с неинфицированного компьютера, защищенного
программой Avast.
www.avast.com
<https://www.avast.com/?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by peconi** [comment]
Alexandr,

I tried with homer5 branch and master. Latest git is pulled when building RPM's.

I do also have the SweetAlert-base.min.js, however, instead of being a js file, it's HTML and the first error is complaining about <!DOCTYPE declaration in it as it is unexpected.

view-source:http://homer.local/lib/sweetalert/SweetAlert-base.min.js

Tnx.

**Comment by cgarciaarano** [comment]
Looks like you used `wget` to download and it gets the HTML from GitHub.

Use this link: https://raw.githubusercontent.com/sipcapture/homer-ui/master/lib/sweetalert/SweetAlert-base.min.js

**Comment by lmangani** [comment]
Thanks @cgarciaarano same diagnosis from our side
closing, @peconi please reopen if useful

**Comment by peconi** [comment]
Thanks! That was it!
