### ISSUE TITLE
Email and password combination not recognised

### ISSUE THREAD

**Issue by thomasquintana** [sipcapture/homer#120]
After installing using the provided instructions I can't login with admin/test123.

**Comment by thomasquintana** [comment]
I also see the following in the developer console on Chrome:

HOMER INIT: 5.0.0beta1
http://162.243.11.166/api/v1/session Failed to load resource: the server responded with a status of 404 (Not Found)
module.auth.run.js:43 Unknown Username / Password combination
module.auth.run.js:44 bad result

**Comment by lmangani** [comment]
Hi @thomasquintana 
The error points at a faulty API configuration - possibly AllowOverride All missing from your Apache (if you used apache)

**Comment by lmangani** [comment]
Try reaching /api/v1/test to validate the API status with certainty

**Comment by thomasquintana** [comment]
I'm currently using nginx. When I try reaching `/api/v1/test` I get a 404.

**Comment by lmangani** [comment]
You should check your fpm-settings or nginx logs for errors when accessing the API - is your configuration in line with the example at:
https://github.com/sipcapture/homer-api/blob/master/examples/web/homer5.nginx

If so, try swapping the following two parameters:
```
# fastcgi_pass 127.0.0.1:9001;
fastcgi_pass unix:/var/run/php5-fpm.sock;
```

**Comment by thomasquintana** [comment]
That did it! Thanks a bunch!

**Comment by lmangani** [comment]
You're very welcome!
