### ISSUE TITLE
Docker-Homer: No Calls Showing Up in Search?

### ISSUE THREAD

**Issue by lylepratt** [sipcapture/homer#121]
Howdy Guys,

We've been working with your new docker container (awesome!) while we finish helping with the Postgres support. However, we're running into an issue with no calls showing up for search results. I'm not sure why this is. It just returns no data for calls. We are, however showing lots of registration events.

Any tips? Thanks!

**Comment by thomasquintana** [comment]
+1

**Comment by thomasquintana** [comment]
I keep trying to save nodes and aliases from the UI with no success. I fill out the information for a new node and hit save at which point I get back a 200 OK but the new node I added is not part of the response.

**Comment by lmangani** [comment]
Thanks for the reports;
@lylepratt will try to replicate locally and check
@thomasquintana is this also for the Docker container?

**Comment by lylepratt** [comment]
Yep, for the docker container.

**Comment by thomasquintana** [comment]
So we are working on a pgsql container https://github.com/BetterVoice/homer5-container but it should affect https://github.com/QXIP/homer-docker as well.

**Comment by thomasquintana** [comment]
I would also like to add that we modified our container to use MySQL (very just change the sql init scripts) and we get the same results.

**Comment by thomasquintana** [comment]
Request to `http://x.x.x.x/api/v1/admin/node/new`:
```javascript
{
    "param":  {
        "host":"127.0.0.1",
        "dbname":"homer_data",
        "dbport":"3306",
        "dbusername":"homer_user",
        "dbpassword":"mysql_password",
        "dbtables":"sip_capture",
        "name":"Homer",
        "status":"1"
    }
}
```

Response from `http://x.x.x.x/api/v1/admin/node/new`:
```javascript
{
    "status": 200,
    "sid": "99fqcdn2pd1frm4n0gvl6fbc30",
    "auth": "true",
    "message": "ok",
    "data": [
        {
            "id": "21",
            "host": "10.1.0.7",
            "dbname": "homer_data",
            "dbport": "3306",
            "dbusername": "homer_user",
            "dbpassword": "mysql_password",
            "dbtables": "sip_capture",
            "name": "external",
            "status": "1"
        },
        {
            "id": "1",
            "host": "127.0.0.1",
            "dbname": "homer_data",
            "dbport": "3306",
            "dbusername": "homer_user",
            "dbpassword": "mysql_password",
            "dbtables": "sip_capture",
            "name": "homer01",
            "status": "1"
        }
    ],
    "count": 2
}
```

**Comment by lmangani** [comment]
@thomasquintana can you delete an existing one or you get the same results? Is anything else working at all in terms of saving aliases or users?

**Comment by lmangani** [comment]
@lylepratt I have added a dummy call scenario to [hepgen](https://github.com/sipcapture/hepgen.js) would you mind trying it against your docker Homer HEP port (edit in config.js) and report results?

**Comment by thomasquintana** [comment]
So deleting and updating nodes works as expected and adding aliases works as well. 

Also, I think I have the problem reported by @lylepratt nailed down but need a little bit longer to test. Just so you are aware the scripts located https://github.com/sipcapture/homer-api/blob/master/sql/schema_data.sql create tables with the wrong date as the suffix so if these scripts are used then the kamailio script located https://github.com/sipcapture/homer-api/blob/master/examples/sipcapture/sipcapture.kamailio will not work properly because it requires the current date for the system it's running on. I will update the ticket in a few min with my findings.

**Comment by lmangani** [comment]
Looking forward your findings @thomasquintana 

A stock setup (non-Docker) seems not to be affected by either issue above. Our Docker container setup uses its own config snippet so maybe the issue is to be hunted down [there](https://github.com/QXIP/homer-docker/blob/master/data/kamailio.cfg)

**Comment by lmangani** [comment]
@lylepratt please see if this change in https://github.com/QXIP/homer-docker/commit/2d3a3cf124b5941cb10bb5fb2859bb539000b1f8 helps

**Comment by thomasquintana** [comment]
Okay so it was exactly what I was referring to. To fix just had to run homer_rotate which creates the necessary tables. I'm thinking what if the cron job hasn't run during downtime and new data comes in? I just started working on the project so figured it would be easier to ask :)

**Comment by thomasquintana** [comment]
Also adding nodes is still not working but that should probably go into it's own ticket. :)

**Comment by lmangani** [comment]
@thomasquintana yes please, open a new issue and let's get that sorted too
