### ISSUE TITLE
Searching by FreeSWITCH Call UUID

### ISSUE THREAD

**Issue by lylepratt** [sipcapture/homer#122]
Is there any way for Homer to capture additional fields that we can search on, such as FreeSwitch call UUIDS? Maybe we can add the UUIDs as a header and search by them that way?

Reason I ask: We store call UUIDs in our database, and would like to link to Homer PCAPs from our UI via the Call UUID.

**Comment by lmangani** [comment]
If you don't use the X-CID correlation mechanism you can try leverage the call_aleg_header and map it to an arbitrary SIP header: 

modparam("sipcapture", "callid_aleg_header ", "X-CID")

**Comment by lmangani** [comment]
Closing. re-open if needed/useful

PS=2016 roadmap includes FS HEP3 updates and likely add space to set this and more at the core
