### ISSUE TITLE
SIP Search should work with partitial matching strings and not just exact match

### ISSUE THREAD

**Issue by ciscospirit** [sipcapture/homer#129]
hi,

under "SIP Search" there should be the possibility to search also for partitial matching strings.

so if for an example the user is 431234567890 it should also be possible to search for 123456789 to get the results of the 431234567890 user.

this should work for every search field, to have maximum comfort by searching for strings.

**Comment by recourse** [comment]
You can use a wildcard character of % in any part of the search.   Having
it match on partial automatically would slow down searches greatly.

**Comment by lmangani** [comment]
Closing - Mind trailing %wildcards and dangerous and expensive, reopen if needed.
