### ISSUE TITLE
SIP Search result: the call detail popup is everytime to far on the right side

### ISSUE THREAD

**Issue by ciscospirit** [sipcapture/homer#130]
hi,

if I open a call detail window, the window is everytime shifted to right and down, so i must take the mouse courser and move the popup in the middle of the screen to have the full information visible.

i use windows 10 and latest chrome browser.

![detail](https://cloud.githubusercontent.com/assets/15861549/11874951/7a499e0c-a4e2-11e5-9bed-40bd7f82a9e0.png)

**Comment by lmangani** [comment]
Please update to the latest and try the window should be centered towards the click point now.

**Comment by ciscospirit** [comment]
I updated right now but still the same problem.

**Comment by lmangani** [comment]
This works in all of our test setups, closing issue - reopen if still experiencing issue after a full update of UI/API to 5.0.1
