### ISSUE TITLE
Docker qxip/homer-docker first ./run.sh failed

### ISSUE THREAD

**Issue by altzone** [sipcapture/homer#132]
hello, I have a problem when launching the image qxip/homer-docker :

<pre>
root@homer: ~ # docker logs 4512fbb1ac6e
/run.sh: 87: [: 127.0.0.1: unexpected operator
/run.sh: 131: /run.sh: 2: not found
loading modules under config path: //usr/lib/x86_64-linux-gnu/kamailio/modules/
 0(21) WARNING: <core> [socket_info.c:1371]: fix_hostname(): could not rev. resolve 0.0.0.0
Listening on
             udp: 0.0.0.0:9060
Aliases:

config file ok, exiting...
Module php5 already enabled
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
loading modules under config path: //usr/lib/x86_64-linux-gnu/kamailio/modules/
 0(39) WARNING: <core> [socket_info.c:1371]: fix_hostname(): could not rev. resolve 0.0.0.0
Listening on
             udp: 0.0.0.0:9060
Aliases:

 1(45) ERROR: db_mysql [km_my_con.c:124]: db_mysql_new_connection(): driver error: Can't connect to MySQL server on '127.0.0.1' (111)
 1(45) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 1(45) ERROR: sipcapture [sipcapture.c:971]: child_init(): unable to connect to database [mysql://homer_user:homer_password@127.0.0.1/homer_data] from capture_mode param.
 1(45) ERROR: <core> [sr_module.c:917]: init_mod_child(): Error while initializing module sipcapture (//usr/lib/x86_64-linux-gnu/kamailio/modules/sipcapture.so)
 1(45) ERROR: <core> [pt.c:329]: fork_process(): init_child failed for process 1, pid 45, "udp receiver child=0 sock=0.0.0.0:9060"
 1(45) CRITICAL: <core> [main.c:1569]: main_loop(): Cannot fork
 2(46) ERROR: db_mysql [km_my_con.c:124]: db_mysql_new_connection(): driver error: Can't connect to MySQL server on '127.0.0.1' (111)
 2(46) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 2(46) ERROR: sipcapture [sipcapture.c:971]: child_init(): unable to connect to database [mysql://homer_user:homer_password@127.0.0.1/homer_data] from capture_mode param.
 0(39) ALERT: <core> [main.c:725]: handle_sigs(): child process 45 exited normally, status=255
 7(51) ERROR: db_mysql [km_my_con.c:124]: db_mysql_new_connection(): driver error: Can't connect to MySQL server on '127.0.0.1' (111)
 7(51) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 7(51) ERROR: sipcapture [sipcapture.c:971]: child_init(): unable to connect to database [mysql://homer_user:homer_password@127.0.0.1/homer_data] from capture_mode param.
 7(51) ERROR: <core> [sr_module.c:917]: init_mod_child(): Error while initializing module sipcapture (//usr/lib/x86_64-linux-gnu/kamailio/modules/sipcapture.so)
 7(51) ERROR: <core> [pt.c:329]: fork_process(): init_child failed for process 7, pid 51, "timer"
 7(51) CRITICAL: <core> [main.c:1641]: main_loop(): cannot fork timer process
 4(48) ERROR: db_mysql [km_my_con.c:124]: db_mysql_new_connection(): driver error: Can't connect to MySQL server on '127.0.0.1' (111)
 4(48) ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool 4(48) ERROR: sipcapture [sipcapture.c:971]: child_init(): unable to connect to database [mysql://homer_user:homer_password@127.0.0.1/homer_data] from capture_mode param.
 4(48) ERROR: <core> [sr_module.c:917]: init_mod_child(): Error while initializing module sipcapture (//usr/lib/x86_64-linux-gnu/kamailio/modules/sipcapture.so)
 4(48) ERROR: <core> [pt.c:329]: fork_process(): init_child failed for process 4, pid 48, "udp receiver child=3 sock=0.0.0.0:9060"
 4(48) CRITICAL: <core> [main.c:1569]: main_loop(): Cannot fork
</pre>
Do you have any solution? 
How can I check / help you to find solution?

Thanks!!

**Comment by adubovikov** [comment]
Check your kamailio.conf, there you have wrong ip for MySQL connection,
must be 127.0.0.1 and not 127001

Regards,
Alexandr

**Comment by altzone** [comment]
kamailio.conf located in docker image ?

**Comment by lmangani** [comment]
Please post this in the proper repository to get support. Thanks!
https://github.com/qxip/homer-docker
