### ISSUE TITLE
Quick Install on CentOS release 6.7 (Final) RPM

### ISSUE THREAD

**Issue by migu30** [sipcapture/homer#133]
Hi all,

I'm following the steps described on the Quick Install how to to install it on a CentOS release 6.7 (Final) system.
Unfortunately with sudo yum install -y homer-nginx I get the message that the package homer-nginx is not available.

What I did :

yum clean all

Loaded plugins: fastestmirror

Cleaning repos: base bintray--sipcapture-homer-yum epel extras home_kamailio_v4.3.x-rpms

              : mysql-connectors-community mysql-tools-community mysql57-community updates

Cleaning up Everything

Cleaning up list of fastest mirrors

[root@merlin ~]# sudo yum install -y homer-nginx

Loaded plugins: fastestmirror

Setting up Install Process

Determining fastest mirrors

epel/metalink                                                                        |  23 kB     00:00     

 * base: ftp.plusline.de

 * epel: mirror.proserve.nl

 * extras: ftp.halifax.rwth-aachen.de

 * updates: ftp-stud.fht-esslingen.de

base                                                                                 | 3.7 kB     00:00     

base/primary_db                                                                      | 3.6 MB     00:01     

bintray--sipcapture-homer-yum                                                        | 1.3 kB     00:00     

bintray--sipcapture-homer-yum/primary                                                | 7.2 kB     00:00     

bintray--sipcapture-homer-yum                                                                         48/48

epel                                                                                 | 4.3 kB     00:00     

epel/primary_db                                                                      | 4.9 MB     00:04     

extras                                                                               | 3.4 kB     00:00     

extras/primary_db                                                                    |  30 kB     00:00     

home_kamailio_v4.3.x-rpms                                                            | 1.2 kB     00:00     

home_kamailio_v4.3.x-rpms/primary                                                    |  11 kB     00:00     

home_kamailio_v4.3.x-rpms                                                                             49/49

mysql-connectors-community                                                           | 2.5 kB     00:00     

mysql-connectors-community/primary_db                                                | 8.8 kB     00:00     

mysql-tools-community                                                                | 2.5 kB     00:00     

mysql-tools-community/primary_db                                                     |  17 kB     00:00     

mysql57-community                                                                    | 2.5 kB     00:00     

mysql57-community/primary_db                                                         |  28 kB     00:00     

updates                                                                              | 3.4 kB     00:00     

updates/primary_db                                                                   | 3.1 MB     00:01     

No package homer-nginx available.

Error: Nothing to do

Any help/suggestion is very appreciate.

Regards,

- Miguel

**Comment by kvishnivetsky** [comment]
Hi, Miguel.
There are CentOS7 x86_64 pacages in this repo.
We are working on CentOS6 x86_64 repo.
You may build C6 packages.

**Comment by ishmaelen** [comment]
What's the update schedule for the repo's? I see the current version is 5.0.1.

# yum info homer-nginx
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.uninett.no
 * epel: ftp.uninett.no
 * extras: ftp.uninett.no
 * updates: ftp.uninett.no
Available Packages
Name        : homer-nginx
Arch        : x86_64
Version     : 5.0.1
Release     : 20160104162610.el7.centos
Size        : 2.1 k

**Comment by lmangani** [comment]
Hi @ishmaelen the schedule is not yet set, we are working on automated builds on a slower track
