### ISSUE TITLE
HTTP Error 404 - Not Found at bintray.com

### ISSUE THREAD

**Issue by byoungdale** [sipcapture/homer#134]
I am following the Automated Installation steps for a Centos 7 machine and when I get to step 3 **Enable EPEL + MySQL Community**:

   I run this command: 
 `sudo yum install -y epel-release https://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm`

And I get this error:
    `Loaded plugins: fastestmirror`
    `File contains no section headers.`
    `file: file:///etc/yum.repos.d/sipcapture.repo, line: 2`
    `'<!doctype html>\n'`

I actually get this error running any yum command. I tried seeing if there were any noticeable syntax errors, but I could not find any. Deleting the leading space in the file did not change the error either. 

I thought it could be an issue on my machine, but it seems that this `sipcapture.repo` file is causing the issue. 

Any ideas on how I can fix this?

**Comment by lmangani** [comment]
hi @brandonyoungdale 
It seems the file /etc/yum.repos.d/sipcapture.repo has been downloaded and is in HTML format. I suggest to re-seat the file (or check its contents) and you should be able to proceed.

**Comment by byoungdale** [comment]
Thank you for catching that! I don't know why I didn't see it. Must have fat fingered something when I first ran `curl https://bintray.com/sipcapture/homer-yum/rpm -o /etc/yum.repos.d/sipcapture.repo`.

Now when I run `yum install -y epel-release https://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm` 

I get this error:
`http://dl.bintray.com/sipcapture/homer-yum/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found`

And at **https://bintray.com/sipcapture/homer-yum** I see that there aren't any packages available. Is there another mirror available?

**Comment by byoungdale** [comment]
I was able to resolve my issues by following the **RPM Build** steps:
`sudo yum install -y git epel-release @Development`
`cd /usr/local/src/`
`sudo git clone https://github.com/sipcapture/homer.git`
`sudo chown $USER:$GROUP -R homer`
`cd homer`
`git submodule init`
`git submodule update --init --recursive`
`git submodule foreach git pull origin master`
`autoreconf -if`
`mkdir -p build`
`cd build`
`../configure --enable-rpm`
`make setup.sh`
`export PATH=/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/root/bin`
`sudo ./setup.sh`

And then following the last three steps of the **Automated Install**

Install Kamailio v.4.3.x repo:
`curl http://download.opensuse.org/repositories/home:/kamailio:/v4.3.x-rpms/CentOS_<YOUR_CENTOS_VERSION>/home:kamailio:v4.3.x-rpms.repo -o /etc/yum.repos.d/kamailio.repo`

Enable EPEL + MySQL Community:
`sudo yum install -y epel-release https://dev.mysql.com/get/mysql57-community-release-el<YOUR_CENTOS_VERSION>-7.noarch.rpm`

Choose your flavour:

HOMER + nginx:
`sudo yum install -y homer-nginx`

**Comment by lmangani** [comment]
Thanks for the update, much appreciated. We will restore downloadable packages soon.
