### ISSUE TITLE
404 on latest rpm in yum repo

### ISSUE THREAD

**Issue by radius314** [sipcapture/homer#135]
I'm getting a 404 on the latest rpm when doing an update.

```shell
$ sudo yum update homer-httpd
Loaded plugins: fastestmirror
http://dl.bintray.com/sipcapture/homer-yum/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
Loading mirror speeds from cached hostfile
 * elrepo: elrepo.org
 * epel: linux.mirrors.es.net
 * rpmforge: mirror.hmc.edu
Resolving Dependencies
--> Running transaction check
---> Package homer-httpd.x86_64 0:5.0.1-20151125131702.el7.centos will be updated
---> Package homer-httpd.x86_64 0:5.0.1-20151222123940.el7.centos will be an update
--> Finished Dependency Resolution

Dependencies Resolved

======================================================================================================================================================
 Package                    Arch                  Version                                          Repository                                    Size
======================================================================================================================================================
Updating:
 homer-httpd                x86_64                5.0.1-20151222123940.el7.centos                  bintray--sipcapture-homer-yum                2.1 k

Transaction Summary
======================================================================================================================================================
Upgrade  1 Package

Total download size: 2.1 k
Is this ok [y/d/N]: y
Downloading packages:
No Presto metadata available for bintray--sipcapture-homer-yum
homer-httpd-5.0.1-201512221239 FAILED
http://dl.bintray.com/sipcapture/homer-yum/homer-httpd-5.0.1-20151222123940.el7.centos.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found --:--:-- ETA
Trying other mirror.


Error downloading packages:
  homer-httpd-5.0.1-20151222123940.el7.centos.x86_64: [Errno 256] No more mirrors to try.
```

**Comment by lmangani** [comment]
Hi @radius314 
The repositories are being reformatted to host multiple archs, please update the repo to ```sipcapture/homer-yum/homer-el7``` and try again.

**Comment by kcarsey** [comment]
I've got a similar issue while trying to do a new install.   I added the repo via the installation instructions then did yum update on CentOS 7 and I get the following message: 

[root@localhost yum.repos.d]# curl https://bintray.com/sipcapture/homer-yum/rpm -o /etc/yum.repos.d/sipcapture.repo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   198    0   198    0     0    810      0 --:--:-- --:--:-- --:--:--   811
[root@localhost yum.repos.d]# yum update
Loaded plugins: fastestmirror, langpacks
base                                                                                         | 3.6 kB  00:00:00
http://dl.bintray.com/sipcapture/homer-yum/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/



 One of the configured repositories failed (bintray--sipcapture-homer-yum),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable bintray--sipcapture-homer-yum

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=bintray--sipcapture-homer-yum.skip_if_unavailable=true

failure: repodata/repomd.xml from bintray--sipcapture-homer-yum: [Errno 256] No more mirrors to try.
http://dl.bintray.com/sipcapture/homer-yum/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
[root@localhost yum.repos.d]#

**Comment by lmangani** [comment]
Apologies folks, we had some breaking changes for sake of improvement.
Could you try using the following in your ```/etc/yum.repos.d/sipcapture.repo``` ?

```
#bintray-sipcapture-homer-yum - packages by  from Bintray
[bintray-sipcapture-homer-yum]
name=bintray--sipcapture-homer-yum
baseurl=http://dl.bintray.com/sipcapture/homer-yum/$releasever/$basearch
gpgcheck=0
enabled=1
```

**Comment by kcarsey** [comment]
Changed my sipcapture.repo to this, and followed the automated installation instructions and it worked perfect.   Thank you!!

**Comment by lmangani** [comment]
Glad it worked and thanks to @kvishnivetsky for the quick fix of the repo - Wiki updated with the above for others to use.
