### ISSUE TITLE
Cannot create debian package for jessie

### ISSUE THREAD

**Issue by mbodbg** [sipcapture/homer#136]
I just followed the instructions on https://github.com/sipcapture/homer/wiki/Quick-Install on a fresh installed debian jessie VM, but it failed:

make debian-jessie-x86_64.homer.deb
make: rpm: Command not found
make homer.deb DISTRO=debian-jessie-x86_64
make[1]: Entering directory '/usr/src/homer/build'
make[1]: rpm: Command not found
Dummy target repo-update
checking for changes in homer-api...make[2]: Entering directory '/usr/src/homer/build'
make[2]: rpm: Command not found

make[3]: Entering directory '/usr/src/homer/build'
make[3]: rpm: Command not found
configure.ac:4: installing 'config/install-sh'
configure.ac:4: installing 'config/missing'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
make distdir for homer-api...
make[4]: Entering directory '/usr/src/homer/build/homer-api'
make[5]: Entering directory '/usr/src/homer/build/homer-api'
make[5]: Leaving directory '/usr/src/homer/build/homer-api'
make[4]: Leaving directory '/usr/src/homer/build/homer-api'
Building DEB for homer-api...
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: source package homer-api
dpkg-buildpackage: source version 5.0.1~dev
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Konstantin S. Vishnivetsky <kvishnivetsky@sipcapture.org>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build homer-api
dpkg-checkbuilddeps: Unmet build dependencies: dh-autoreconf
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
mak/10-deb.mk:53: recipe for target 'homer-api.deb' failed
make[3]: *** [homer-api.deb] Error 3
make[3]: Leaving directory '/usr/src/homer/build'
mak/10-deb.mk:27: recipe for target 'debian-jessie-x86_64.homer-api.deb' failed
make[2]: *** [debian-jessie-x86_64.homer-api.deb] Error 2
make[2]: Leaving directory '/usr/src/homer/build'
mak/10-deb.mk:44: recipe for target 'homer-api.deb.if-changed' failed
make[1]: *** [homer-api.deb.if-changed] Error 2
make[1]: Leaving directory '/usr/src/homer/build'
mak/10-deb.mk:27: recipe for target 'debian-jessie-x86_64.homer.deb' failed
make: *** [debian-jessie-x86_64.homer.deb] Error 2

**Comment by linuxmaniac** [comment]
WIP See #126
