### ISSUE TITLE
Bad File Mode in cron logs

### ISSUE THREAD

**Issue by jvb187** [sipcapture/homer#137]
Hello,

On a fresh install of CentOS 7 using the prebuilt packages, I was receiving the following error in my cron logs and the homer_rotate cron job never ran:

Jan 12 15:42:42 homerTest103 crond[602]: (root) BAD FILE MODE (/etc/cron.d/sipcapture)

I was able to correct this by running chmod 0644 on /etc/cron.d/sipcapture, it was set to 0664 initially. I am not sure if this was a typo or if it was supposed to be set to 0664 and something else may be wrong.

Thank you,
Jeremy

**Comment by lmangani** [comment]
Thanks for the report - we will address this in packages
