### ISSUE TITLE
Cron log rotate not working correctly

### ISSUE THREAD

**Issue by Caesar305** [sipcapture/homer#138]
Hello,

I followed the instructions on how to install using CentOS yum repo. Everything went smoothly, however, it seems the cron is not roating the sip_capture table correctly.

select count(*) from sip_capture_call_20160118 show 0. I ran the cron manually and it seems to take some time (About 30 seconds) and I can see the tables being created however there is no date inside of them. I filtered the results in the main sip_capture table and I can see that the events are in there. For whatever reason, it is not copying the data from the main table to the rotated tables. Running the cron manually does not display any errors.

**Comment by Caesar305** [comment]
I also noticed it created a few tables in the future. I just run the cron and it has the 19th and 20th. I am wondering if somehow it has the incorrect date which is why it is unable to filter properly. The date command shows the correct time and date.

**Comment by lmangani** [comment]
@Caesar305 the script is meant to create future tables for homer to use and write to, based on its settings. Check out the rotate scripts contents and parameters they should help you understand how they are created and how to manage them.

**Comment by Caesar305** [comment]
Yeah, I've been reviewing the code, trying to get an understanding of things lol.
This script(s) is what is supposed to bring the date from the main sip_capture table to the new tables, correct? I can't seem to find the reason why it is not grabbing the date even though it certainly is in the sip_capture table.

**Comment by lmangani** [comment]
@Caesar305 have you sorted this out or you still need clarifications?

**Comment by Caesar305** [comment]
No, still having the issue unfortunately. I haven't looked into the code enough it seems. I don't understand which part actually puts the data into the tables.

**Comment by lmangani** [comment]
rotation has nothing to do with inserting the data - that's done by Kamailio - the script just manages new tables and rotates old ones.

**Comment by Caesar305** [comment]
Correct that is what I was implying. The main table has data inserted by kamailaio. The issue is the new tables created from the cron are empty even though the data exists in the new table.

**Comment by lmangani** [comment]
Tables created by cron are meant to be empty and ready to utilize by kamailio when their turns arrives.
