### ISSUE TITLE
Homer and Asterisk native agent.

### ISSUE THREAD

**Issue by theoc1** [sipcapture/homer#139]
Hello. Does res_hep works only with PJSIP channels?
I have insalled Homer and setup asterisk's hep.conf on it. But Homer recieves only RTCP info. No SIP. Is that because i'm using chan_sip insead new chan_pjsip on Asterisk?

**Comment by lmangani** [comment]
Hi @theoc1 that is correct, SIP is currently only available in chan_pjsip, although there are some [patches](https://groups.google.com/forum/#!topic/homer-discuss/hJF15HM4ywE) being tested unofficially. If you wish to try them out and help debug them, let us know.

**Comment by theoc1** [comment]
Thank you. I think it's convincing argument for migrating to pjsip. Homer is awsome.
I'll try a patch of course, but bringing it to production isn't best idea, imho.

**Comment by lmangani** [comment]
Thanks for choosing and endorsing Homer and looking forward having you onboard
