### ISSUE TITLE
'Logic OR' and 'Unique' not working in search

### ISSUE THREAD

**Issue by adriangarbacea** [sipcapture/homer#140]
I would like to do a logic OR between search parameters. I can add 'Logic OR' field, by embedded widget menu, but it is not taken into consideration, or maybe i don't know ow to use it, for Homer5
similar behavior for 'unique'.
it would be good that these fields are of checkbox type.

**Comment by adubovikov** [comment]
please check this commit.
https://github.com/sipcapture/homer-ui/commit/df6752b6b2a179e7bf792e2855cb83f81dca60c7

thank you.

**Comment by adubovikov** [comment]
please also update the api part

**Comment by adriangarbacea** [comment]
testing results
unique:
- it removes the double messages, but i have on top of the search results several blank pink lines equal with the number of removed messages
![image](https://cloud.githubusercontent.com/assets/11270840/12645692/6d5e742a-c5d4-11e5-8726-f5d588bf12c1.png)
- callflow from which it has been removed some messages displays just heading and parallel lines, no message

Logic OR: it still does "AND" between search parameters. no difference in OR enabled/disabled

**Comment by adubovikov** [comment]
please get last api git and recheck uniq again.

the or logic will be checked

**Comment by adriangarbacea** [comment]
**unique:  **both "search results" and callflow are ok after last api fc46b27

**Comment by adubovikov** [comment]
please check now OR:

https://github.com/sipcapture/homer-api/commit/8965a28fe40e380e5bca6dd81654a941a640b417

**Comment by adriangarbacea** [comment]
OR works perfectly. thank you

**Comment by adubovikov** [comment]
ok. thanks for testing and bug report.
