### ISSUE TITLE
deeplink into homer search with version 5?

### ISSUE THREAD

**Issue by rbott** [sipcapture/homer#141]
We are currently transitioning from homer 3.5 to homer 5. One of our main benefits was the possibility to "deep-link" into the search form from a third-party application on our end. Basically we sent a POST to /index.php, providing some parameters that pre-filled the search form's fields.

Looking at the new UI/API design in homer 5, we are wondering if that scenario is still possible. Using the API seems to be the closest option. However, we would like to leverage homer's power of displaying information, rather than re-inventing that wheel with data retrieved from the API. Is it possible to generate some sort of deep link that
* shows the search form pre-filled with data or...
* shows the search results or...
* directly shows a given call (e.g. identified by an ID retrieved from a search using the API)?

**Comment by lmangani** [comment]
@rbott try the share functionality under the export tab, i think it might fit the requirements

**Comment by SipSeb** [comment]
As far as we can see, the share functionality is only for previously executed searches which are then saved using a transaction identifier. What we need is to execute a completely new search by providing our own parameters (collected from different sources). Is there any way to submit those values (time range, from, to etc.) from external and end up in the results overwiev table?

**Comment by lmangani** [comment]
@SipSeb just perform an API call with any parameters and use the resulting IDs and time range to assemble an export/share request to ```api/v1/search/sharelink``` ie:
```
{"timestamp":{"from":1454238752233,"to":1454240400000},"param":{"search":{"id":6429,"callid":["35a99bba-4ee2-4203-837f-8c8bc151df71"],"uniq":false},"location":{},"transaction":{"call":true,"registration":false,"rest":false}}}
```

**Comment by rbott** [comment]
@lmangani Thanks for the hint, we have tried it and it directs us to the call-flow view of the search results.
Is it possible to generate a sharelink that points to the results view? Or is it possible to store the search within the user's profile via API and open it with a sharelink?

**Comment by adubovikov** [comment]
you can do similar to this:

#result?query=(trancall:'true',start:'1450529267',end:'1450538873',search_ruri_user:'1234')


https://github.com/sipcapture/homer-ui/blob/master/js/modules/pages/controllers/resultCtrl.js#L94

but this method is limited only for few parameters.

//search_callid
if(sObj.hasOwnProperty("search_callid")) searchValue["callid"] = sObj["
search_callid"];
if(sObj.hasOwnProperty("search_ruri_user")) searchValue["ruri_user"] = sObj[
"search_ruri_user"];
if(sObj.hasOwnProperty("search_from_user")) searchValue["from_user"] = sObj[
"search_from_user"];
if(sObj.hasOwnProperty("search_to_user")) searchValue["to_user"] = sObj["
search_to_user"]

**Comment by rbott** [comment]
Is it possible to extend this to also support the "orand" parameter?

**Comment by adubovikov** [comment]
sure, just make fork, do changes (there are same params as for API calls)
and push it back and we will merge it.... or you can always contact support@
and ask for consulting.

**Comment by rbott** [comment]
Thanks for integrating the pull request, this is exactly what we needed :-)
This issue can be closed from our end.
