### ISSUE TITLE
MSG ID window is blank

### ISSUE THREAD

**Issue by millsu2** [sipcapture/homer#142]
When clicking on a packet the MSG ID window that pops up has Message and Details tab, but is otherwise empty.
The browser shows this javascript error:
```
TypeError: Cannot read property 'id' of undefined
    at dialogCtrl.js:73
    at angular.js:14792
    at r.$eval (angular.js:16052)
    at r.$digest (angular.js:15870)
    at r.$apply (angular.js:16160)
    at g (angular.js:10589)
    at T (angular.js:10787)
    at XMLHttpRequest.w.onload (angular.js:10728)
```

PCAP exports have complete packet information. The kamailio version is 4.3.4 and homer is running the latest git as of this morning. The homer server and capture server have both been setup to use the same ntp server. The OS timezone is "America/Phoenix" and the homer config's timezone is "US/Eastern".

kamailio.cfg has this configuration:
```
        #For old models. Not accurate insert time. System vs capture time.
        $var(a) = $var(table) + "_" + $timef(%Y%m%d);
        #for Kamailio >4.3 please uncomment this parameters:
        #$var(a) = $var(table) + "_%Y%m%d";
```
When the second line is commented and the fourth line is un-commented, it appears that no packets are captured.

**Comment by millsu2** [comment]
Here is the full kamailio.cfg: [kamailio.cfg.txt](https://github.com/sipcapture/homer/files/114312/kamailio.cfg.txt)

**Comment by lmangani** [comment]
Could you also confirm if the *same* session showing up empty can be exported in full as referred in your original request?

**Comment by millsu2** [comment]
If I click on a CallID, I can see the full call flow, but when i click on a specific packet it brings up a blank MSG ID window. If click export on that same call id, I can successfully export and the data appears to be complete.

**Comment by adubovikov** [comment]
Do u use the captagent or freeswitch/kamailio to duplicate SIP?

**Comment by millsu2** [comment]
I am using captagent.

**Comment by adubovikov** [comment]
can you please do follow:
1. open webconsole (F12)
2. click on a message and provide us the parameter of the API call.
3. go to your DB, find this message and show us all fields of the message. mysql-cli

thank you.

**Comment by millsu2** [comment]
Here is the data from mysql:
```
|6|2016-02-02 00:00:01|1454396397783211|100|Trying||||4802467228||as421d9a1f|40460||||40460||07ad4e652ca5a1b1654c2dd234a98a39@192.168.0.20:5060|| SIP/2.0/UDP 192.168.0.20:5060;branch=z9hG4bK4636f1ec;rport|z9hG4bK4636f1ec|102 INVITE||||||192.168.0.183|5060|192.168.0.20|5060|192.168.0.183|5060||0|07ad4e652ca5a1b1654c2dd234a98a39@192.168.0.20:5060||||1|2||2|homer01:4004|SIP/2.0 100 Trying
Via: SIP/2.0/UDP 192.168.0.20:5060;branch=z9hG4bK4636f1ec;rport
From: "Sales-5551237228" <sip:5551237228@192.168.0.20>;tag=as421d9a1f
To: <sip:40460@192.168.0.183:5060;user=phone;transport=udp>
Call-ID: 07ad4e652ca5a1b1654c2dd234a98a39@192.168.0.20:5060
Date: Tue, 02 Feb 2016 07:01:35 GMT
CSeq: 102 INVITE
Server: Cisco-CP7940G/8.0
Contact: <sip:40460@192.168.0.183:5060;user=phone;transport=udp>
Allow: ACK,BYE,CANCEL,INVITE,NOTIFY,OPTIONS,REFER,REGISTER,UPDATE
Content-Length: 0
```

Can you give me a little more help on how to get the parameter of the API call?

**Comment by adubovikov** [comment]
in browser -> F12 -> Network bar.
make a click and you will see in the console api reques. Click on it and you will see params. Please copy and paster.

**Comment by adubovikov** [comment]
can you please upgrade kamailio to 4.4 ? (master git)

**Comment by millsu2** [comment]
Here is everything from the console after clicking the message:
```
HOMER INIT: 5.0.2 Release
resultCtrl.js:38 AUTH TRUE
resultCtrl.js:233 modal1 message opened from url message1636754631
resultCtrl.js:233 modal1 message opened from url message1636754631
angular.js:12520 TypeError: Cannot read property 'id' of undefined
    at dialogCtrl.js:73
    at angular.js:14792
    at r.$eval (angular.js:16052)
    at r.$digest (angular.js:15870)
    at r.$apply (angular.js:16160)
    at g (angular.js:10589)
    at T (angular.js:10787)
    at XMLHttpRequest.w.onload (angular.js:10728)
```

I'm not sure if I will be able to update kamailio because it is a production server, but I will look into it.

**Comment by adubovikov** [comment]
is it kamailio 4.3 ?

**Comment by millsu2** [comment]
Yes, it is Kamailio 4.3.4.

**Comment by adubovikov** [comment]
try this as workaround. Later, please update to 4.4
https://github.com/sipcapture/homer-api/commit/cc94b7df3bd32d3cda875f38363c6f1ceddba274

**Comment by millsu2** [comment]
That does fix the problem, so I assume the issue due to the time difference between the date and micro_ts columns in the database. It looks like the micro_ts is the accurate time. Where do these times come from?

**Comment by adubovikov** [comment]
this is because the timestamp of HEP was not used as MYSQL timestamp. The issue was fixed in 4.4 (master) git.

**Comment by millsu2** [comment]
Thanks for all of your help!

**Comment by adubovikov** [comment]
I hope it works with 4.4 ?

**Comment by serdaronderoglu** [comment]
Pulled latest homer-docker today and It has same problem

**Comment by lmangani** [comment]
Hi @serdaronderoglu this is likely only related to the Docker container and not a general issue with homer - just make sure your agent and capture server are ntp syncronized. You are welcome to raise this on the homer-docker tracker for assistance - I am using the latest build of the image and cannot reproduce the problem so we need to look into the fine details.
