### ISSUE TITLE
Custom Range Not working

### ISSUE THREAD

**Issue by bazemoreb** [sipcapture/homer#143]
Hi there, hope it is OK if I add an issue in!  After the latest update to 5.0.1, custom range does not seem to work.  Clicking the "custom range" option or clicking the date does not bring up the date picker.  Clicking any of the presets works just fine.  

Have replicated in Chrome, Firefox as well as IE.  No errors show in the console logs.
![image](https://cloud.githubusercontent.com/assets/5182535/12757535/4dbec25c-c98d-11e5-84e1-89f09ba8cf11.png)

**Comment by adubovikov** [comment]
Hi,

Please update to the latest git. It was fixed already.

Wbr,
Alexandr

**Comment by bazemoreb** [comment]
Oops!  I guess we were using the most recent RPM.  I'm closing this and we will switch to master - thanks!
