### ISSUE TITLE
404 repodata again

### ISSUE THREAD

**Issue by ishmaelen** [sipcapture/homer#144]
Running Oracle Linux 6 but unable to use yum-repo for Homer.

`[root@hostname src]# yum --enablerepo=bintray-sipcapture-homer-yum search homer
Loaded plugins: security
http://dl.bintray.com/sipcapture/homer-yum/6Server/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: bintray-sipcapture-homer-yum. Please verify its path and try again`

`[root@hostname src]# cat  #/etc/yum.repos.d/sipcapture.repo
#bintray-sipcapture-homer-yum - packages by  from Bintray
[bintray-sipcapture-homer-yum]
name=bintray--sipcapture-homer-yum
baseurl=http://dl.bintray.com/sipcapture/homer-yum/$releasever/$basearch
gpgcheck=0
enabled=0`

Also tried baseurl=http://dl.bintray.com/sipcapture/homer-yum

Please see previously closed issue on the same https://github.com/sipcapture/homer/issues/13

**Comment by lmangani** [comment]
Hi,

No experience with Oracle Linux - The repository currently do not ship builds for "6Server" (is that even correct?) and only have images for EL7 (http://dl.bintray.com/sipcapture/homer-yum/7/x86_64/) - I suggest to try build the packages manually on your system and let us know if you run into issues.

**Comment by ishmaelen** [comment]
OK - thanks!
