### ISSUE TITLE
Kamailo not parsing HEP from Captagent v4.1.3

### ISSUE THREAD

**Issue by drrighteous** [sipcapture/homer#145]
Unfortunately I am unable to compile Captagent v6 (as posted in a different Bug), however after getting the UI, API and captagent 4.1.3 installed, Kamailo is not striking records to mysql. /var/log/syslog is showing errors, e.g.:

Feb 14 01:05:27 ip-10-32-0-39 /usr/local/sbin/kamailio[21447]: ERROR: pv [pv_core.c:1646]: pv_get_hdr(): error parsing headers
Feb 14 01:05:27 ip-10-32-0-39 /usr/local/sbin/kamailio[21447]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Record-Route: <>(10)
Feb 14 01:05:27 ip-10-32-0-39 /usr/local/sbin/kamailio[21447]: message repeated 2 times: [ ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Record-Route: <>(10)]
Feb 14 01:05:27 ip-10-32-0-39 /usr/local/sbin/kamailio[21447]: ERROR: sipcapture [sipcapture.c:1209]: sip_capture_prepare(): cannot parse headers
Feb 14 01:05:27 ip-10-32-0-39 /usr/local/sbin/kamailio[21447]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Record-Route: <>(10)
Feb 14 01:05:27 ip-10-32-0-39 /usr/local/sbin/kamailio[21447]: ERROR: <core> [parser/parse_ppi_pai.c:150]: parse_pai_header(): Error looking for subsequent PAI header
Feb 14 01:05:27 ip-10-32-0-39 /usr/local/sbin/kamailio[21447]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Record-Route: <>(10)
Feb 14 01:05:27 ip-10-32-0-39 /usr/local/sbin/kamailio[21447]: ERROR: <core> [parser/parse_ppi_pai.c:171]: parse_ppi_header(): Error parsing PPI header
Feb 14 01:05:27 ip-10-32-0-39 /usr/local/sbin/kamailio[21445]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Contact: <sip:19999218663048515@209.165.2.198:5060;user=phone>(7)
Feb 14 01:05:27 ip-10-32-0-39 /usr/local/sbin/kamailio[21445]: ERROR: sipcapture [sipcapture.c:1209]: sip_capture_prepare(): cannot parse headers
Feb 14 01:05:27 ip-10-32-0-39 /usr/local/sbin/kamailio[21445]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Contact: <sip:19999218663048515@209.165.2.198:5060;user=phone>(7)
Feb 14 01:05:27 ip-10-32-0-39 /usr/local/sbin/kamailio[21445]: ERROR: <core> [parser/parse_ppi_pai.c:124]: parse_pai_header(): Error parsing PAI header
Feb 14 01:05:27 ip-10-32-0-39 /usr/local/sbin/kamailio[21445]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Contact: <sip:19999218663048515@209.165.2.198:5060;user=phone>(7)
Feb 14 01:05:27 ip-10-32-0-39 /usr/local/sbin/kamailio[21445]: ERROR: <core> [parser/parse_ppi_pai.c:171]: parse_ppi_header(): Error parsing PPI header
Feb 14 01:05:29 ip-10-32-0-39 /usr/local/sbin/kamailio[21445]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Record-Route: <sip:>(10)
Feb 14 01:05:29 ip-10-32-0-39 /usr/local/sbin/kamailio[21445]: message repeated 3 times: [ ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Record-Route: <sip:>(10)]
Feb 14 01:05:29 ip-10-32-0-39 /usr/local/sbin/kamailio[21445]: ERROR: pv [pv_core.c:1646]: pv_get_hdr(): error parsing headers
Feb 14 01:05:29 ip-10-32-0-39 /usr/local/sbin/kamailio[21445]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Record-Route: <sip:>(10)
Feb 14 01:05:29 ip-10-32-0-39 /usr/local/sbin/kamailio[21445]: message repeated 2 times: [ ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Record-Route: <sip:>(10)]
Feb 14 01:05:29 ip-10-32-0-39 /usr/local/sbin/kamailio[21445]: ERROR: sipcapture [sipcapture.c:1209]: sip_capture_prepare(): cannot parse headers
Feb 14 01:05:29 ip-10-32-0-39 /usr/local/sbin/kamailio[21445]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Record-Route: <sip:>(10)
Feb 14 01:05:29 ip-10-32-0-39 /usr/local/sbin/kamailio[21445]: ERROR: <core> [parser/parse_ppi_pai.c:150]: parse_pai_header(): Error looking for subsequent PAI header
Feb 14 01:05:29 ip-10-32-0-39 /usr/local/sbin/kamailio[21445]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Record-Route: <sip:>(10)
Feb 14 01:05:29 ip-10-32-0-39 /usr/local/sbin/kamailio[21445]: ERROR: <core> [parser/parse_ppi_pai.c:171]: parse_ppi_header(): Error parsing PPI header
Feb 14 01:05:33 ip-10-32-0-39 /usr/local/sbin/kamailio[21450]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Contact: <sip:19999218888479159@209.165.2.198:5060;user=phone>(7)
Feb 14 01:05:33 ip-10-32-0-39 /usr/local/sbin/kamailio[21450]: ERROR: sipcapture [sipcapture.c:1209]: sip_capture_prepare(): cannot parse headers
Feb 14 01:05:33 ip-10-32-0-39 /usr/local/sbin/kamailio[21450]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Contact: <sip:19999218888479159@209.165.2.198:5060;user=phone>(7)
Feb 14 01:05:33 ip-10-32-0-39 /usr/local/sbin/kamailio[21450]: ERROR: <core> [parser/parse_ppi_pai.c:124]: parse_pai_header(): Error parsing PAI header
Feb 14 01:05:33 ip-10-32-0-39 /usr/local/sbin/kamailio[21450]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Contact: <sip:19999218888479159@209.165.2.198:5060;user=phone>(7)
Feb 14 01:05:33 ip-10-32-0-39 /usr/local/sbin/kamailio[21450]: ERROR: <core> [parser/parse_ppi_pai.c:171]: parse_ppi_header(): Error parsing PPI header
Feb 14 01:05:33 ip-10-32-0-39 /usr/local/sbin/kamailio[21446]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Contact: <sip:19999218888479159@209.165.2.198:5060;user=phone>(7)
Feb 14 01:05:33 ip-10-32-0-39 /usr/local/sbin/kamailio[21446]: ERROR: sipcapture [sipcapture.c:1209]: sip_capture_prepare(): cannot parse headers
Feb 14 01:05:33 ip-10-32-0-39 /usr/local/sbin/kamailio[21446]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Contact: <sip:19999218888479159@209.165.2.198:5060;user=phone>(7)
Feb 14 01:05:33 ip-10-32-0-39 /usr/local/sbin/kamailio[21446]: ERROR: <core> [parser/parse_ppi_pai.c:124]: parse_pai_header(): Error parsing PAI header
Feb 14 01:05:33 ip-10-32-0-39 /usr/local/sbin/kamailio[21446]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Contact: <sip:19999218888479159@209.165.2.198:5060;user=phone>(7)
Feb 14 01:05:33 ip-10-32-0-39 /usr/local/sbin/kamailio[21446]: ERROR: <core> [parser/parse_ppi_pai.c:171]: parse_ppi_header(): Error parsing PPI header
Feb 14 01:05:35 ip-10-32-0-39 /usr/local/sbin/kamailio[21447]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Record-Route: <sip:AQEAELiVlQgUZ4ItSYnBpu0RszgDAARtQMF2@74.120.136.84>(10)
Feb 14 01:05:35 ip-10-32-0-39 /usr/local/sbin/kamailio[21447]: ERROR: sipcapture [sipcapture.c:1209]: sip_capture_prepare(): cannot parse headers
Feb 14 01:05:35 ip-10-32-0-39 /usr/local/sbin/kamailio[21447]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Record-Route: <sip:AQEAELiVlQgUZ4ItSYnBpu0RszgDAARtQMF2@74.120.136.84>(10)
Feb 14 01:05:35 ip-10-32-0-39 /usr/local/sbin/kamailio[21447]: ERROR: <core> [parser/parse_ppi_pai.c:150]: parse_pai_header(): Error looking for subsequent PAI header
Feb 14 01:05:35 ip-10-32-0-39 /usr/local/sbin/kamailio[21447]: ERROR: <core> [parser/msg_parser.c:260]: get_hdr_field(): ERROR: get_hdr_field: bad body for <Record-Route: <sip:AQEAELiVlQgUZ4ItSYnBpu0RszgDAARtQMF2@74.120.136.84>(10)
Feb 14 01:05:35 ip-10-32-0-39 /usr/local/sbin/kamailio[21447]: ERROR: <core> [parser/parse_ppi_pai.c:171]: parse_ppi_header(): Error parsing PPI header
Feb 14 01:05:37 ip-10-32-0-39 /usr/local/sbin/kamailio[21450]: ERROR: <core> [parser/msg_parser.c:96]: get_hdr_field(): ERROR: get_hdr_field: bad header
Feb 14 01:05:37 ip-10-32-0-39 /usr/local/sbin/kamailio[21450]: ERROR: sipcapture [sipcapture.c:1209]: sip_capture_prepare(): cannot parse headers
Feb 14 01:05:37 ip-10-32-0-39 /usr/local/sbin/kamailio[21450]: ERROR: <core> [parser/msg_parser.c:96]: get_hdr_field(): ERROR: get_hdr_field: bad header
Feb 14 01:05:37 ip-10-32-0-39 /usr/local/sbin/kamailio[21450]: ERROR: <core> [parser/parse_ppi_pai.c:150]: parse_pai_header(): Error looking for subsequent PAI header
Feb 14 01:05:37 ip-10-32-0-39 /usr/local/sbin/kamailio[21450]: ERROR: <core> [parser/msg_parser.c:96]: get_hdr_field(): ERROR: get_hdr_field: bad header

I'm using the stock kamailo.cfg from the homer-api GIT examples file (modified for my port/db) and captagent.xml is also stock except for host changes.

Any assistance would be greatly appreciated.

--David

**Comment by lmangani** [comment]
David,

I doubt you are sending HEP traffic to this socket and whatever is being sent seems very seriously malformed. Could you capture and show what's being sent/received by the Kamailio/Sipcapture socket?

**Comment by lmangani** [comment]
I guess this was solved? Please reopen if needed.

**Comment by gabyfulchic** [comment]
@lmangani it seems to be the same error that i sent to you from the google groups 

link : https://groups.google.com/forum/#!topic/homer-discuss/Up-PPyp0ZBw

I'm always getting this error :/

**Comment by lmangani** [comment]
@gabyfulchic the error is from the Kamailio parser, which definitely can be trusted as valid - the agents will just encapsulate the messages so they are likely innocent. You can try capturing the raw messages with tcpdump and most likely, they will results malformed also when opened in wireshark with bad termination or what-not. Hope this helps.

**Comment by gabyfulchic** [comment]
Thank you fr your fast reply :o 
So i don't have to change anything, i just need to let it throw this error and it will works normally ? :)
