### ISSUE TITLE
Captagent v6 fails to compile on Deb Squeeze (x64 kernel, x86 os)

### ISSUE THREAD

**Issue by drrighteous** [sipcapture/homer#146]
Unfortunately my SBCs run a 64bit kernel with a 32bit OS, which I believe is causing a failure to compile the latest Captagent GIT. An example output from the make:

oot@sip03:/usr/src/captagent# make
Making all in src
make[1]: Entering directory `/usr/src/captagent/src'
make  all-recursive
make[2]: Entering directory `/usr/src/captagent/src'
Making all in .
make[3]: Entering directory `/usr/src/captagent/src'
gcc -m32 -DHAVE_CONFIG_H -I.  -DSYSCONFDIR='"/usr/local/etc"' -I../include  -g -fPIC -rdynamic -I../include -g -O2 -MT captagent.o -MD -MP -MF .deps/captagent.Tpo -c -o captagent.o captagent.c
captagent.c: In function ‘print_hw’:
captagent.h:48: error: can't find a register in class ‘BREG’ while reloading ‘asm’
captagent.h:48: error: ‘asm’ operand has impossible constraints
make[3]: *** [captagent.o] Error 1
make[3]: Leaving directory `/usr/src/captagent/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/usr/src/captagent/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/src/captagent/src'
make: *** [all-recursive] Error 1

Unfortunately, I am by no means a GCC guy; I have tried passing ./configure various flags to compile 32bit, but honestly its just supposition on my part that this might be causing the issue.

--David

**Comment by adubovikov** [comment]
you can comment code in the function out or add -fno-pic as options to compiler

**Comment by lmangani** [comment]
Please kindly re-open in https://github.com/sipcapture/captagent project
