### ISSUE TITLE
PHP Notice: Undefined index: RestApi/Dashboard.php on line 143

### ISSUE THREAD

**Issue by byoungdale** [sipcapture/homer#147]
I have a Freeswitch sending HEP packets to my Homer machine. I see the packets coming in the correct interface on the Homer box, but nothing in populating on the WebUI and I don't see any data in the database. In the **sipcapture-error.log** file I see this error:

> PHP Notice:  Undefined index: _1450278390101 in /var/www/sipcapture/htdocs/api/RestApi/Dashboard.php on line 143

And at line 143 is this:
>if($skipDashboards[$boardid] == 1) continue;

Here is the whole block that line is associated with. I am not knowledgable enough in PHP to know what is going wrong. Is this error being thrown because of something misconfigured on my end? Or is this a bug in the code?

```
/* store */
        if ($handle = opendir(DASHBOARD_PARAM)) {
           while (false !== ($file = readdir($handle))) {
                if ($file[0] == "_") {

                    $boardid = str_replace(".json", "", $file);

                    if($skipDashboards[$boardid] == 1) continue;

                    $dar = DASHBOARD_PARAM."/".$file;
                    $myfile = fopen($dar, "r") or die("Unable to open file!");

                    $text =  fread($myfile, filesize($dar));
                    $json = json_decode($text, true);

                    $parent = new \stdClass;
                    $parent->boardid = $boardid;

                    $parent->name = $json['title'];
                    $parent->class = "fa fa-angle-double-right";
                    $boards[] = $parent;
                    fclose($myfile);
                }
            }
            closedir($handle);
        }
```

**Comment by lmangani** [comment]
Hi @byoungdale 
The data inser part and visualization are not that closely related. The UI issue is not an indicator of inser issues, for this you should check the kamailio logs for error messages, etc. Once you have data in the database we can look at any remaining UI issue.

**Comment by lmangani** [comment]
Re-Open if still needed

**Comment by daniel-lucio** [comment]
Undefined index: _1411848944046 in /var/www/sipcapture/htdocs/api/RestApi/Dashboard.php on line 143

I do have this issue as well. I can confirm my db is being populated.
