### ISSUE TITLE
MSG ID window sometimes is blank 

### ISSUE THREAD

**Issue by pgwiazda** [sipcapture/homer#148]
Hi,
I found a similar problem to that which has already been closed. 
I checked everything as was shown at this closed issue, but I still have a problem

MSG ID window that pops up sometimes is blank, and sometimes has information

![logs](https://cloud.githubusercontent.com/assets/17449639/13396000/6cce01e2-def2-11e5-89d8-28765872cd5f.JPG)

I used docker version qxip/homer-docker and docker qxip/captagent6.
kamailio 4.3.4 

The browser shows this javascript error:
![log2](https://cloud.githubusercontent.com/assets/17449639/13396225/b91a9a5a-def3-11e5-87a7-31469222bd51.JPG)

any helps?

**Comment by adubovikov** [comment]
did you sync date/time between your captagent and server ?

**Comment by pgwiazda** [comment]
Hi,
sorry for late answer. 

Yes, both are sync.
I think that problem with sync should appear at random.
In my case problem refer only for BYE and 180/181 responses. 
One remarks we use SIP-I so these messages are with ISUP BODY
![pic1](https://cloud.githubusercontent.com/assets/17449639/13636081/1c701dce-e600-11e5-85b7-91cac2f3987b.PNG)

![pic2](https://cloud.githubusercontent.com/assets/17449639/13636086/26c95cd6-e600-11e5-94eb-9f9e674207c0.PNG)
Is there any limitation  of using SIP-I or using messages with Message Body? 
 or there is needed changing in configuration?

**Comment by adubovikov** [comment]
ISUP is only SDP part in this case. Can you please check the API call for this message.

You can open webconsole in your browser and check the API call there...

**Comment by pgwiazda** [comment]
if I understand well;

![pic3](https://cloud.githubusercontent.com/assets/17449639/13636366/e145a316-e601-11e5-8e89-c08e7fe2f3df.PNG)

**Comment by adubovikov** [comment]
not javascript's console, but network API calls...

**Comment by pgwiazda** [comment]
![pic4](https://cloud.githubusercontent.com/assets/17449639/13636970/09a0eb24-e605-11e5-90a1-f94a8eb5e637.PNG)
![pic5](https://cloud.githubusercontent.com/assets/17449639/13636974/0af29f72-e605-11e5-8b79-a80153d6d7df.PNG)

**Comment by adubovikov** [comment]
can you please post the response body ?

**Comment by pgwiazda** [comment]
sip reponse body or http response ?

**Comment by adubovikov** [comment]
http

**Comment by pgwiazda** [comment]
![pic6](https://cloud.githubusercontent.com/assets/17449639/13637423/85e743f2-e607-11e5-91e8-caf67457d856.PNG)


and 
POST message
![pic7](https://cloud.githubusercontent.com/assets/17449639/13637497/f55c5f7e-e607-11e5-80be-c25693bd967e.PNG)

**Comment by adubovikov** [comment]
sorry, but I don't need wireshark's screenshot.

you can see the http body resposne in the same WebConsole.

i.e.
![screenshot from 2016-03-09 15 05 20](https://cloud.githubusercontent.com/assets/4513061/13637588/6fc861b8-e608-11e5-91c0-f0ee291556b9.png)

**Comment by pgwiazda** [comment]
For this POST I received somethin like that
![pic8](https://cloud.githubusercontent.com/assets/17449639/13637818/a7065fb2-e609-11e5-8839-3335571a316b.PNG)

maybe we can establish a Webex session to better checking?

**Comment by pgwiazda** [comment]
columns in english
Header, Cookies, Parameters, Responses, (at blue), Timing

**Comment by adubovikov** [comment]
sorry, but establish a webex and work on remote server is out of our "community support"

you should check, why you didn't get data for this API request. Please check the RestAPI/Search.php from API package and add some debug output/logging.

**Comment by adubovikov** [comment]
please also check apache's log. There should be some information about this error

**Comment by pgwiazda** [comment]
I'll check ....

One more issue (if needed I'll opened as new one) - during configuration tables for captured date there is limitation to length 1500. Is it limitation eg due to captagent?
When we used SIP-I messages (especially INVITE) which have length more then 1500 there are  for this moment  cutted to 1500. 
Databases modification should be enough are there should be more reconfiguration?

**Comment by adubovikov** [comment]
should be enough.

**Comment by ishmaelen** [comment]
@pgwiazda : Can you please try to select the same record straight from your database using the callid and "timestamp from/to" values passed when opening MSG window?

Something along the lines of 
`select * from sip_capture_call_yyyymmdd where callid = 'somecallid' and micro_ts >= 'from_ts' and micro_ts <= 'to_ts'`

Did that return any records?
That should at least tell you if this problem is time-related or not. My guess is that it is..

**Comment by ishmaelen** [comment]
@adubovikov Is there any need to include from_ts/to_ts parameters when pressing some Method to display MSG?

After all the call is displayed with exact information such as id and callid based on a previous from_to/to_ts seach - and in any case it would be more sane to use the exact same values that was posted previously to gain further information for stuff found in that seach.

**Comment by adubovikov** [comment]
from/to ts are mandatory  because the sip_capture_* tables based on the time partitions if you don't provide these parameters, you have to do scan indexes on all partitions. 

as a "optimization" we can use only the timestamp of message, but was easy way just reuse the existing search object from prevision search.

**Comment by adubovikov** [comment]
additional information to the my last message. We do already this way but decrements/increment from/to ts 300 seconds just to avoid bug with non synced time between a capture node and a capture server.

@pgwiazda  can you please take the last version of the API and check again ?

thank you

**Comment by pgwiazda** [comment]
sorry, but after update API there is no change. Still not showing BYE msg

**Comment by adubovikov** [comment]
bad, please add error_log in the Search.php at line 560 and print the sql to the log and check the query manual.

https://github.com/sipcapture/homer-api/blob/master/api/RestApi/Search.php#L591

**Comment by pgwiazda** [comment]
is it some progress? :)
Manual query wokrs and show BYE message.
But I see some  difference SQL from error log 
SELECT t.*, 'call' as trans FROM sip_capture_call_20160310 as t WHERE (t.date BETWEEN FROM_UNIXTIME(1457610403) AND FROM_UNIXTIME(1457611004)) AND ( t.id = '1179898')

and log from wwwconsole 
{"timestamp":{"from":1457610703644,"to":1457610703844},"param":{"search":{"id":1179898,"callid":"SDkbur401-7af2ff9aaeea1563a79e976642cc41df-v300g00"},"location":{"node":"single"},"transaction":{"call":true,"registration":false,"rest":false}}}

there is diference between timestamps

**Comment by pgwiazda** [comment]
I come back to the begining, because I think it could be additional trail:
MSG ID window is blank for messages with ISUP Body....  
If it will be a problem with sync it should touch different SIP messages not only this with ISUP.
Do you agree?

**Comment by adubovikov** [comment]
yes, can be some special tags inside and the body couldn't be parsed to html angular view.

can you please make a sql dump and share with us? We will try to reproduce the issue locally.

**Comment by pgwiazda** [comment]
Send to  support@sipcapture.org email
