### ISSUE TITLE
Date range selection doesn't display

### ISSUE THREAD

**Issue by alexanderjp** [sipcapture/homer#150]
I have just installed sip capture and kamailio using the package installation on CentOS. As far as I can tell everything works except selecting custom date range. When it is clicked there is nothing that happens.

**Comment by adubovikov** [comment]
please take the last git of UI and API.

this was fixed in 5.0.3

**Comment by alexanderjp** [comment]
I have updated to 5.0.4 and it shows on the quick search panel however when I try from the home page or the results page if I try and select a different range it does not display.

**Comment by lmangani** [comment]
Are you clicking the SEARCH button again after changing the range? Only widget updates are automatic, not search results

**Comment by alexanderjp** [comment]
Let me explain what is happening.

1. Log into homer
2. On the HOME screen I click on the upper right date icon and the dropdown shows time options and at the bottom CUSTOM RANGE
3. I click on CUSTOM RANGE and nothing happens

I was only able to see the CUSTOM RANGE pop screen once and now I can't see it again.

**Comment by alexanderjp** [comment]
Here are some screenshots using to separate browsers.

I see the date fields are different.  Not sure why
![screen shot 2016-03-04 at 1 30 54 pm](https://cloud.githubusercontent.com/assets/8550150/13536370/89c2b32e-e20d-11e5-9a18-74a5b1ab27ba.png)
![screen shot 2016-03-04 at 1 30 46 pm](https://cloud.githubusercontent.com/assets/8550150/13536371/89d6f1cc-e20d-11e5-9af9-944d1fd6d20c.png)
![screen shot 2016-03-04 at 1 30 32 pm](https://cloud.githubusercontent.com/assets/8550150/13536374/89d8e27a-e20d-11e5-840e-128c98f1518f.png)
![screen shot 2016-03-04 at 1 30 19 pm](https://cloud.githubusercontent.com/assets/8550150/13536375/89d9a732-e20d-11e5-8d89-e3d5cb167f68.png)
![screen shot 2016-03-02 at 1 58 59 pm](https://cloud.githubusercontent.com/assets/8550150/13536372/89d779da-e20d-11e5-91d3-fe14abbadba1.png)
![screen shot 2016-03-02 at 10 30 36 am](https://cloud.githubusercontent.com/assets/8550150/13536373/89d8bdae-e20d-11e5-9c50-6b51260c5b28.png)

**Comment by adubovikov** [comment]
Please clean up your browser cache or disable JavaScript buffering.

**Comment by alexanderjp** [comment]
that worked
