### ISSUE TITLE
Homer Database - MSG length more then 1500

### ISSUE THREAD

**Issue by pgwiazda** [sipcapture/homer#152]
I open as a new issue discussion from other topic
During configuration tables for captured date there is limitation to length 1500. Is it limitation eg due to captagent?
When we used SIP-I messages (especially INVITE) which have length more then 1500 there are for this moment cutted to 1500.
Databases modification should be enough are there should be more reconfiguration?
@adubovikov said that modification should be enough

unfortunatelly is not...

**Comment by adubovikov** [comment]
Is it UDP or TCP packet ?

sorry, but you have to enable the defrag param for UDP or the tcpreasm for TCP in your captagent.

do you use capt6 or capt4 ?

Wbr,
Alexandr

**Comment by pgwiazda** [comment]
we have udp packet
capt6

**Comment by adubovikov** [comment]
so, please enable defrag param

**Comment by pgwiazda** [comment]
in which file ? I can't find such param

**Comment by adubovikov** [comment]
sorry,
reasm = true

https://github.com/sipcapture/captagent/blob/master/conf/socket_pcap.xml#L8

**Comment by pgwiazda** [comment]
i changed and ... 
at sql table msg is still <1500
but (in plus) 
after export to pcap all informations are correct (ISUP/ISDN...) 

but (in minus) 
-  these messages are not shown at msg window as BYE masseges
- at sql query there is no ISUP/ISDN part? 
we can see only encapsulation headers but at ISDN USER PART we can see only signs with any sense
 
--4E17F10BBABB8CF5501B08632AB6ED4F1BF16A45
Content-Type:application/ISUP;base=itu-t92+;version=itu-t92+
Content-Disposition:signal;handling=required
Content-Transfer-Encoding:binary

`
 !X1ő
"FSQ1  91Ŕ
--4E17F10BBABB8CF5501B08632AB6ED4F1BF16A45--

**Comment by lmangani** [comment]
```Content-Transfer-Encoding:binary```

**Comment by adubovikov** [comment]
you have binary payload in this case please change the 'msg' type from 'varchar' to 'binary'

**Comment by pgwiazda** [comment]
after changing 
export to pcap not recognized sip messages
![pic10](https://cloud.githubusercontent.com/assets/17449639/13673762/d553227a-e6da-11e5-9e9d-a3a55318c27b.PNG)

and msq window shows something like that
![pic9](https://cloud.githubusercontent.com/assets/17449639/13673776/e4c5c49c-e6da-11e5-8a09-cbe4ed893c97.PNG)

and msg field contains only "[msg] => B\n  "

**Comment by adubovikov** [comment]
ok, as I said last time please send us a sql dump (varchar) and one original PCAP with ISUP
we will try check it as soon we found time for it

**Comment by pgwiazda** [comment]
can I directly send it to your gmail ?

**Comment by adubovikov** [comment]
you can send it to support@sipcapture.org

**Comment by pgwiazda** [comment]
Send,
I hope it will be enough

**Comment by pgwiazda** [comment]
any news?

**Comment by adubovikov** [comment]
@pgwiazda sorry, but not yet. For now it's not a critical bug, but just a feature request and in this case we will work on it as soon we find a free time.

**Comment by pgwiazda** [comment]
@adubovikov , I made some additional checking, and it seem that is still problem with defrag and big packet.
I found that  packet with content-length >700 are not putted to the SQL base. So it could be something more then feature ;)
Is it any limitations at captagent sip parser for sdp length?

**Comment by adubovikov** [comment]
no, there should be no problem, the captagent by default don't do parsing but only sends the SIP messages to kamailio/sipcapture. Can you please run ngrep and see if you have complete messages in HEP including defragment packets ?

**Comment by pgwiazda** [comment]
I've ckecked with ngrep
and I didn't see complete messages in HEP. Defragmented INVITE is not transmitted by HEP :(

**Comment by adubovikov** [comment]
how you check it ?

**Comment by pgwiazda** [comment]
I established two monitoring at CapAgent Machine  - one at sip interface (tcpdump), second at HEP interface (ngrep)  
At ngrep I put filter for my sip phone number.
I established a call. And at tcpdump I saw defragmented INVITE
At HEP the first msg is 100 Trying and no INVITE...

**Comment by adubovikov** [comment]
do you see also all fragments of your original INVITE ? If not, this can be
a problem, because we are waiting for all fragments and after send complete
INVITE

**Comment by pgwiazda** [comment]
at tcpdump I see ( SDP length is 1298) 
at HEP no, I don't see any fragmented INVITE

One more information:
when I change at socket_pcap.xml  param name="reasm" to value ="false" 
at HEP I see one part of fragmented INVITE (SDP is  cutted)  
Length of this HEP packet is 1624 and his payload hs len=1582

**Comment by adubovikov** [comment]
ok, I expect that INVITE is UDP transport. Can you please send your
socket_pcap.xml ?

**Comment by pgwiazda** [comment]
YES we use UDP

file I sent as previously, to the support email

**Comment by adubovikov** [comment]
please change it:

<param name="filter">
<value>portrange 5060-5091 or (ip[6:2] & 0x3fff != 0)</value>
</param>

**Comment by pgwiazda** [comment]
with this filter nothing is coming at HEP interfaces
but if I use in this way
<value>portrange 5060-5091 or ip[6:2] </value>
its WORKS !!
What means such filter ?

**Comment by pgwiazda** [comment]
is it the some meaning as tcpdump filter?

**Comment by adubovikov** [comment]
get also fragmented packets.

**Comment by adubovikov** [comment]
sorry, fragments of defragmented packets.

**Comment by pgwiazda** [comment]
Thanks, 
I think we can closed this issue, its works :)

**Comment by adubovikov** [comment]
you are welcome

**Comment by rs03** [comment]
I am facing same issue .. I am not getting enitre INVITE MIME and if I set realsm=true as mentioned in above comments , I don't get INVITE in homer . Can somebody please help me here? I have raised another issue regarding same but no reply .this is really urgent for me .
