### ISSUE TITLE
Problems with the position of the detail popup windows

### ISSUE THREAD

**Issue by ciscospirit** [sipcapture/homer#153]
Hello,

in the Call Details > Call Flow if you open the details of a SIP message, the window open with the left upper corner where the mouse pointer was pressed. thats okay for sip messages on the Left side, but if you do the same for a sip message on the right down side, then everytime i must move the popup window on the left upper side, otherwise i cant see the full informations and also can't close the window, cause the "x" for closing is not visible.

is there any other way to positionate this windows? Best would be to open it everytime centralisized in the main screen.

Homer 5.0.5

**Comment by ciscospirit** [comment]
Also another problem:

if you open a second or third detail popup then you cant bring the first on in the front of the screen.

so latest open detail window gets everytime on the frontest layer of the screen, so you must move it somewhere or close this to see the windows in the back again.

it would be good, if you can move a window in the front if you click on it.

**Comment by lmangani** [comment]
Please check & confirm using latest GIT version

**Comment by lmangani** [comment]
Positioning workaround implemented, re-open if needed.
