### ISSUE TITLE
QoS Report in Homer 5.0.5 - Request for some improvements

### ISSUE THREAD

**Issue by ciscospirit** [sipcapture/homer#154]
Hello,

i checked the new feature with QoS Reports and found something, which would be nice to get included:

If you open the CallID without b2b you can see just the QoS from the Peering to the Server and vica versa. If you open the CallID with b2b then you see the QoS Report from Server to Device and vv.

It would be a please to see all this informations in every detail view of a CallID. So it would be easier to debug call problems if you have all informations about jitter, paketloss etc on one screen.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/26b1bd08e88b14128506d899fe0725f06d6f1d76

please check

**Comment by lmangani** [comment]
Fixed, closing :+1:
