### ISSUE TITLE
Call Logs not in right timing...

### ISSUE THREAD

**Issue by ciscospirit** [sipcapture/homer#155]
Normally the log should begin with a invite:
Mar 28 15:28:04 spce (local7.notice) proxy[26180]: NOTICE <script>: New request on proxy - M=INVITE .....

but as you can see in the screenshot, it begins with a log entry which appears later in the server log files. so it is not possible to see the right timings of the log messages in homer. if i do a grep on the server, i see the right timings of the messages.

i believe the problem is, that there are no "milliseconds" and so they just sorted by seconds and so logs are shown in first row which should be somewhere in the middle...

Both the SPCE and the Homer Server have the same NTP Time Settings.

**Comment by lmangani** [comment]
Thanks for the report - This is not due to Homer and needs to be addressed at the sender side - Are you running the latest version of hepipe.js?

**Comment by lmangani** [comment]
Confirmed client issue - Please open this in the hepipe.js issue tracker, Thanks!
