### ISSUE TITLE
Call Logs not visible in a "b2b-1" CallID search result

### ISSUE THREAD

**Issue by ciscospirit** [sipcapture/homer#156]
If i open a trace of a b2b-1 CallID then i can see there any Call Log messages.
If i open the same trace by clicking a search result message with out "b2b-1" in the CallID then i also see the Call Log messages from the SPCE Server.

Is it possible to enable the Call Log messages also there?
it would be better for debugging, to have all informations in one view.

thanks

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/26b1bd08e88b14128506d899fe0725f06d6f1d76

please check.

**Comment by lmangani** [comment]
Fixed, closing :+1:
