### ISSUE TITLE
Example: RTCPXR few fixes

### ISSUE THREAD

**Issue by pinchasMT** [sipcapture/homer#157]
Few suggestions for easier integration

1. specify where to add the modifications:
kamailio.cfg line 260 -> ```else if(is_method("PUBLISH"))``` ...

2. CallID should allow @ _ characters
```$var(callid) = $(rb{re.subst,/.*CallID:([0-9A-Za-z@-_\.]{5,120}).*$/\1/s});```

3. Optional, LocalAddr regex fix (greedy)
```$var(localaddress) = $(rb{re.subst,/.*LocalAddr:IP=([^\S]+).*$/\1/s});```

4.  Optional, comment out all ``statsd_set``

5. Once complete with testing, comment out all ``xlog`` before going to production

**Comment by adubovikov** [comment]
thank you. Can you please do pull request ?

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/04d72862de09d14d4cd32e92cc6e3d898f9a5b92

thank you
