### ISSUE TITLE
install on Debian 8 failed

### ISSUE THREAD

**Issue by jyue16** [sipcapture/homer#158]
when final command 'make debian-jessie-x86_64.homer.deb' is issuded, got following error messages:
Building DEB for homer-api...
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: source package homer-api
dpkg-buildpackage: source version 5.0.1~dev
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: source changed by Konstantin S. Vishnivetsky <kvishnivetsky@sipcapture.org>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build homer-api
dpkg-checkbuilddeps: Unmet build dependencies: dh-autoreconf
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
mak/10-deb.mk:53: recipe for target 'homer-api.deb' failed
make[3]: *** [homer-api.deb] Error 3
make[3]: Leaving directory '/usr/src/homer/build'
mak/10-deb.mk:27: recipe for target 'debian-jessie-x86_64.homer-api.deb' failed
make[2]: *** [debian-jessie-x86_64.homer-api.deb] Error 2
make[2]: Leaving directory '/usr/src/homer/build'
mak/10-deb.mk:44: recipe for target 'homer-api.deb.if-changed' failed
make[1]: *** [homer-api.deb.if-changed] Error 2
make[1]: Leaving directory '/usr/src/homer/build'
mak/10-deb.mk:27: recipe for target 'debian-jessie-x86_64.homer.deb' failed
make: *** [debian-jessie-x86_64.homer.deb] Error 2

**Comment by lmangani** [comment]
Premission: debs are incomplete

```dpkg-checkbuilddeps: Unmet build dependencies: dh-autoreconf``` 

Is dh-autoreconf available on your system?

**Comment by jyue16** [comment]
Thanks Lorenzo. I just installed dh-autoreconf and issued command again.now the errors are different.here are all the outputs
sudo make debian-jessie-x86_64.homer.deb
make homer.deb DISTRO=debian-jessie-x86_64
make[1]: Entering directory '/usr/src/homer/build'
Dummy target repo-update
checking for changes in homer-api...make[2]: Entering directory '/usr/src/homer/build'

make[3]: Entering directory '/usr/src/homer/build'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
make distdir for homer-api...
make[4]: Entering directory '/usr/src/homer/build/homer-api'
cp: ‘./api’ and ‘./api’ are the same file
Makefile:390: recipe for target 'distdir' failed
make[4]: *** [distdir] Error 1
make[4]: Leaving directory '/usr/src/homer/build/homer-api'
mak/10-deb.mk:49: recipe for target 'homer-api.distdir' failed
make[3]: *** [homer-api.distdir] Error 2
make[3]: Leaving directory '/usr/src/homer/build'
mak/10-deb.mk:27: recipe for target 'debian-jessie-x86_64.homer-api.deb' failed
make[2]: *** [debian-jessie-x86_64.homer-api.deb] Error 2
make[2]: Leaving directory '/usr/src/homer/build'
mak/10-deb.mk:44: recipe for target 'homer-api.deb.if-changed' failed
make[1]: *** [homer-api.deb.if-changed] Error 2
make[1]: Leaving directory '/usr/src/homer/build'
mak/10-deb.mk:27: recipe for target 'debian-jessie-x86_64.homer.deb' failed
make: *** [debian-jessie-x86_64.homer.deb] Error 2

**Comment by paolovisintin** [comment]
delete /usr/src/homer and restart
everything will go!

Paolo

**Comment by jyue16** [comment]
thanks Paolo. I find the install isn't easy for a non-developer like me. not sure if the install is complete now, but web gui isn't accessible. 

the last a few outputs of install are:
make[5]: Leaving directory '/usr/src/homer/build/captagent'
 dpkg-source --after-build captagent
dpkg-source: info: using options from captagent/debian/source/options: --compression=gzip
dpkg-buildpackage: full upload; Debian-native package (full source is included)
make[4]: Leaving directory '/usr/src/homer/build/captagent'
dpkg-scanpackages: warning: Packages in archive but missing from override file:
dpkg-scanpackages: warning:   captagent homer-api homer-ui
dpkg-scanpackages: info: Wrote 3 entries to output Packages file.
make[3]: Leaving directory '/usr/src/homer/build'
make[2]: Leaving directory '/usr/src/homer/build'
make[1]: Leaving directory '/usr/src/homer/build'

**Comment by lmangani** [comment]
@jyue16 It's actually harder to build the package than install its few components and understand the elements behind in the process at this time indeed. For the non-technical the Docker container is the simplest and most self-contained option. We're focused developing the application at this time, packaging improvement efforts are ongoing and results will follow once complete. This being said, did you install the package you created?

**Comment by jyue16** [comment]
I followed the steps from this page: https://github.com/sipcapture/homer/wiki/Package-Install#-build-custom-packages-advanced. 
I'll try the docker install. can't wait to try Homer, I've heard it's very useful to troubleshoot SIP.
thanks for you guys' hard work.

**Comment by lmangani** [comment]
If you want a quick & dirty setup you can start with the single container setup:
https://github.com/sipcapture/homer/wiki/Docker-Install

For a fully hosted version and zero effort:
https://github.com/sipcapture/homer/wiki/Example:-Docker-Carina

**Comment by jyue16** [comment]
docker install works. thanks Lorenzo
