### ISSUE TITLE
QOS reports not shown

### ISSUE THREAD

**Issue by nlalexandrov** [sipcapture/homer#160]
Hello.

When I analyse a call in Homer, I can see the sip messages and their contents, however clicking on QoS Reports, I can only see "Avg. Packet Loss", "Tot Packets Lost", etc. but nothing is actually calculated (no values shown). Please check the attached screenshot.
However I can see the rtcp_capture table populated and if I try to export the data via "share link", when I open the link I see data populated in QoS Reports - that's the second screenshot. 

Please could you guide me in the right direction, what could be the issue here ?

Best regards
Nikolai

![qos1](https://cloud.githubusercontent.com/assets/8723029/14466099/118d75a2-00de-11e6-8a52-59ef43c5be55.png)
![qos2](https://cloud.githubusercontent.com/assets/8723029/14466100/11aa099c-00de-11e6-9049-f14397507327.png)

**Comment by lmangani** [comment]
Hi

You must update to the latest UI + API version to see the reports and statistics (currently 5.0.5)

**Comment by nlalexandrov** [comment]
Wow, that was fast :)
Many thanks, will do first thing tomorrow and let you know!

Thanks a lot !

**Comment by lmangani** [comment]
No Problem! Feel free to re-open this issue if you need help
