### ISSUE TITLE
Some timestamp management issues

### ISSUE THREAD

**Issue by nlalexandrov** [sipcapture/homer#161]
Hello,

I will try to describe some strange behaviour that I saw today (I'm on version 5.0.5 since this morning).

If I set my time interval to 
From 2016-04-13 02:00:00 to 2016-04-13 02:30:00, TZ GMT+3 MSK 
I can find no calls (please check screenshot half-hour.png)

If I set it to   From 2016-04-13 02:00:00 to 2016-04-13 03:00:00, TZ GMT+3 MSK    and refresh - suddenly there are calls available (screenshot is one-hour.png)

The calls that I see are within the timerange in both cases.

Now the next  thing - i think it's another issue, and I suspect the time set on my server could be the issue - I'm set to GMT + 3 ... 
If i try to open the signalling itself, I don't see the SIP message contents. Please check no-data.png. The post request is as follows : 
Host: 192.168.15.65
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json;charset=utf-8
Referer: http://192.168.15.65/
Content-Length: 236
Cookie: HOMERSESSID=60ifcdvpk3eua4k90fn7u6qaj7
Connection: keep-alive

request body : 
{"timestamp":{"from":1460502005589,"to":1460502005789},"param":{"search":{"id":1494,"callid":"4b02b27e010211e68da9080027ca4300@217.28.243.231"},"location":{"node":"single"},"transaction":{"call":true,"registration":false,"rest":false}}}

As you can see in the screenshot, the reply is empty.
However if I increase the second timestamp with about 3 hours (my local time is GMT+3) and re-post ... now I have the response - check response-is-there.png.
My second request body : 
{"timestamp":{"from":1460502005589,"to":1460513105789},"param":{"search":{"id":1494,"callid":"4b02b27e010211e68da9080027ca4300@217.28.243.231"},"location":{"node":"single"},"transaction":{"call":true,"registration":false,"rest":false}}}

Thank you in advance for your help !
Best regards
Nikolai
![one-hour](https://cloud.githubusercontent.com/assets/8723029/14492111/cd5588a4-0185-11e6-846a-ca063056a104.png)
![half-hour](https://cloud.githubusercontent.com/assets/8723029/14492112/d215b3b4-0185-11e6-8328-ef7d12440d4c.png)
![no-data](https://cloud.githubusercontent.com/assets/8723029/14492126/ed8a8ff2-0185-11e6-9d1a-3880a4e2ebd6.png)
![response-is-there](https://cloud.githubusercontent.com/assets/8723029/14492130/f1422fec-0185-11e6-8ced-c6b185e5e96c.png)

**Comment by adubovikov** [comment]
Do you use kamailio 4.4 ?

and this variable should be active:

https://github.com/sipcapture/homer-api/blob/master/examples/sipcapture/sipcapture.kamailio#L849

please check

**Comment by nlalexandrov** [comment]
I'm on kamailio 4.3, but the data I wrote about was gathered last night with homer 5.0.2 and old kamailio.cfg ... so let me gather some new data now, and I will keep you posted :)

Just to clarify, do I have to upgrade kamailio to 4.4 ?

Thank you Mr. Dubovikov !

**Comment by adubovikov** [comment]
yes, please

upgrade kamailio to 4.4 and install new kamailio's config that I pointed in
the last reply. Also don't forget update UI and API to the last one.


Wbr,
Alexandr

**Comment by nlalexandrov** [comment]
Hello Alexander and devs@Homer :)

with kamailio 4.4, updatdet kamailio.cfg (as Alexander wrote) and Homer 5.0.5 - works ok.

Many thanks for your help !

Best regards
Nikolai
