### ISSUE TITLE
Puppet support

### ISSUE THREAD

**Issue by giavac** [sipcapture/homer#162]
I've been working on a Puppet module for Homer. The simplest (and perhaps most requested) distributions to cover were Ubuntu and Debian, and this is where I focussed.

In the pipeline I have CentOS support but also managing the Docker containers from Puppet itself. There are cases where this is desirable and anyway I'm making it conditional: who wants an installation directly on the host can "switch off" the Docker part. In a similar fashion, one can decide to install and configure mysql with the Puppet module, or just use an existing mysql server.

The work done so far is in https://github.com/giavac/giavac-homer (and I've also followed Puppet Forge practices in order to have it published there: https://forge.puppet.com/giavac/homer)

I'm raising this issue so that you can comment and give me instructions on how to best integrate this work in your project. It could be perhaps a new sipcapture repo, like `puppet-homer`, or a `puppet/` folder in the `homer` repo, or some other strategy (including of course holding on).

Regardless of this integration feel free to submit feedback and suggest improvements (e.g. I based the UI part on nginx but could optionally add apache, etc). Thanks.

**Comment by lmangani** [comment]
Giacomo,

First and foremost, thanks on behalf of the sipcapture bunch for your efforts and for supporting the project and taking care of this long-overdue aspect - we welcome and appreciate it a ton, and I'm sure all the community will even more. I created [homer-puppet](https://github.com/sipcapture/homer-puppet) where you have full push rights as part of the sipcapture pkg team to push the project (please confirm) 

Make yourself Home(r) and let us know how to best support You - Grazie!

**Comment by giavac** [comment]
Grazie Lorenzo,
this is much appreciated, and I can confirm permissions are working. Cheers.

**Comment by lmangani** [comment]
Closing as this is now live
