### ISSUE TITLE
QOS Reports - report_capture entries missing

### ISSUE THREAD

**Issue by t1mb0** [sipcapture/homer#163]
Latest 5.0.5 (updated UI / API / kamailio.cfg) have found published QOS reports in report_capture table are not displaying within the homer interface.
Have confirmed batch of entries exist in report_capture table with correct correlation_id but i'm only seeing RTCP stats.

Can I confirm the "RTP Agent Stats" is the location where vq-rtcpxr events sent via publish are displayed?

Secondly, I note that X-RTP (end of call) reports are showing blank data in the UI.  Confirmed phone sent X-RTP, UI shows the X-RTP Stats block, all data missing.

**Comment by lmangani** [comment]
Hi @t1mb0 
Could you paste the ```qos``` api JSON console output for a session you believe should have statistics?

**Comment by t1mb0** [comment]
Hi,

This example has 4 x published reports in the database, all of which have blank info when displayed in the UI.
[qos-api.txt](https://github.com/sipcapture/homer/files/223438/qos-api.txt)

Cheers,

Tim

**Comment by adubovikov** [comment]
Timbo,

can you please provide the sql dump of report_capture table ?
2-3 lines will be ok!

thank you.

Wbr,
Alexandr

**Comment by lmangani** [comment]
@t1mb0  You can also send this to support@sipcapture.org in privacy mode if easier

**Comment by adubovikov** [comment]
unfortunately we didn't receive any dumps, therefore please check this commits:

https://github.com/sipcapture/homer-api/commit/cefaa7cebb2bd9631dbbe3284b99b98b75a231e3

**Comment by pinchasMT** [comment]
+1 https://github.com/sipcapture/homer-ui/issues/69

**Comment by adubovikov** [comment]
did you check the last commit ?

**Comment by pinchasMT** [comment]
-1, it does show
![image](https://cloud.githubusercontent.com/assets/17321963/14652588/f166857e-0642-11e6-9faf-fe8d0aa59d70.png)

my apologies

**Comment by t1mb0** [comment]
Hi All,

Apologies for the delay, have been off work sick past day or two.

Confirmed RTCP-XR stats sent via PUBLISH are now showing on the QOS Metrics Chart, but the summary statistics block on the left is missing:

[cid:image001.png@01D19AE5.0D6CFDD0]
Here’s an example from a Cisco SPA setup to add statistics to BYE.  The single entry is shown in the graph, but information is not placed in the X-RTP Stats summary block.

[cid:image002.png@01D19AE5.AC556180]
Cheers,

Tim

**Comment by camiloortiz** [comment]
After installation HOMER, the only table information  running is Homer_data , and do not enter information to webhomer .
someone has or fix this problem?

**Comment by lmangani** [comment]
@camiloortiz seems unrelated to this case, please provide more details or open a new issue

**Comment by lmangani** [comment]
Feel free to reopen if needed
