### ISSUE TITLE
data not showing in homer

### ISSUE THREAD

**Issue by mfremont1** [sipcapture/homer#166]
I hope this is a simple issue.

I installed homer and am able to login to the web interface.

I installed sngrep and using it as a capture agent for now anyway.   

I ran the following sngrep port 5060 -H udp:10.10.10.10:9060 replacing  10.10.x.x with the homer IP.  

logged in with a sip phone and placed a call.   I see it in the sngrep interface (also ran wireshark) saw the registration and the actual call.    

I can not find this data in Homer5.    Is there a place to check to make sure sngrep is sending it correctly to homer and is there a  way to check or see what may be blocking it.

Any advice would be great.    

Have not used captagent6 as the wiki is not complete to understand the configs.

thanks for any help.

**Comment by adubovikov** [comment]
do you see any HEP packets on the interface ?

**Comment by mfremont1** [comment]
I know I saw sip packets but didn’t look for HEP packets specially?   Being new to HEP what should I be looking for those?

M

**Comment by adubovikov** [comment]
capture port 9060 and check if you see any packets started from HEP3 
(ascii) and SIP as body ....

**Comment by mfremont1** [comment]
So I just did another test to get a clean sample.   I ran sngrep port 5060  -H 10.x.x.x:9060

I saw the register and the phone call.  I did not see any HEP packets.  Attached is the pcap from sngrep.

Shouldn’t I have seen the registration in Homer5 since it was captured in the sngrep even with no HEP packets?

Thanks
M

**Comment by adubovikov** [comment]
no packets - no charts ;-)

**Comment by mfremont1** [comment]
So we are using Genesys Sip server.

Is there a way to force HEP packets as I thought the tool only needed the sip traffic to at least get some data.

**Comment by lmangani** [comment]
@mfremont1 Homer leverages capture agents sending encapsulated data, not raw SIP.
Could you confirm you have ran the following on the HOMER server while running sngrep and performing a test call?
```
ngrep -W byline port 9060
```

**Comment by mfremont1** [comment]
I have not run that command.

But I think you just nailed it why it doesn’t work.  I thought Homer5 could leverage raw SIP.     Not sure in our environment I am able to encapsulate or even have the HEP packages as we are using a Genesys Sip server and it does not have HEP natively.  (or that I am aware of)

**Comment by lmangani** [comment]
@mfremont1 Homer / Kamailio can also capture bare SIP from a raw socket, if needed, but in your case the best option would probably be to install and configure an instance of captagent on each system being monitored. We have rpm/deb packages available on the repository, you just need to configure your HEP server in ```transport_hep.xml``` and capture filter in ```socket_pcap.xml``` for the basics.

**Comment by mfremont1** [comment]
So does the captagent act as the HEP server then?   Also our sip server runs on windows and I did not see a install for windows but may have missed it.

**Comment by lmangani** [comment]
Not really. In Homer-land a Capture Agent is really the client, and Capture Server.. the server.
So a Captagent instance running on your SIP softswitch would basically sniff, encapsulate and mirror your traffic according to the network filters and ship it to a Capture Server using the HEP protocol.

**Comment by lmangani** [comment]
Closing - feel free to reopen if useful
