### ISSUE TITLE
Where in the web interface I can view data stored in the logs_capture table ?

### ISSUE THREAD

**Issue by nlalexandrov** [sipcapture/homer#168]
Dear Homer team,

I'm on Homer 5.0.5. By reading here and there in our beloved Internet, I was able to populate my logs_capture db table with some data (just for testing) via hepipe  : 
mysql> select * from logs_capture;
+----+---------------------+------------------+----------------+-----------+-------------+----------------+------------------+-------+--------+------+--------------+---------+
| id | date                | micro_ts         | correlation_id | source_ip | source_port | destination_ip | destination_port | proto | family | type | node         | msg     |
+----+---------------------+------------------+----------------+-----------+-------------+----------------+------------------+-------+--------+------+--------------+---------+
|  1 | 2016-04-27 14:42:59 | 1461758840757379 | 99999999       | 1.2.3.4   |         123 | 1.2.3.4        |            31488 |     1 |      2 |    1 | homer01:1234 | blabla
 |
|  2 | 2016-04-27 14:42:59 | 1461758847498483 | 99999999       | 1.2.3.4   |         123 | 1.2.3.4        |            31488 |     1 |      2 |    1 | homer01:1234 | blabla

Please could you point me in the right direction, how can I view this data in the Homer web. Sounds like a very dull issue to have, but so far I'm unable to find this anywhere in the web ... or maybe I've messed up the data in the table somehow?

Many thanks in advance for your help.
Best regards
Nikolai

**Comment by lmangani** [comment]
Hi @nlalexandrov 

The data will only be available in correlation with a session (ie: SIP session) which the logs will be associated with.

**Comment by nlalexandrov** [comment]
Hello Lorenzo,

thank you for your prompt answer.
Ok, so obviously I messed up the data. Great, by inserting a log with a correct correlation ID, i can check the corresponding call and there in Logs tab i can see my log :)

Just one more question - what table should be populated so the info will be shown in the "Alarm List" view ? 
I'm trying to store some error logs in the database and be able to view them from the web ....

Thank you again for your time and help!

**Comment by adubovikov** [comment]
Hi @nlalexandrov 

https://github.com/sipcapture/homer-api/blob/master/sql/schema_statistic.sql#L14-L48

this tables are related to Alarms.

Wbr,
Alexandr

**Comment by nlalexandrov** [comment]
Hi Alexandr,

many thanks, I had forgotten there are 2 more databases here :D 
I will close this question,

Thank You again for the great stuff you guys provide for the open source community!
