### ISSUE TITLE
Only 100 items can be searched in Sip Search

### ISSUE THREAD

**Issue by xihh401** [sipcapture/homer#171]
Hi,

I installed homer 5.0.5 in a CentOS 6 virtual machine.
The sip search result only show 100 items,

![20160527160321](https://cloud.githubusercontent.com/assets/12489785/15601842/59c11a9a-2424-11e6-97bf-74c818202773.png)

however, there more than 300 items in database, here the database search:

**mysql> select count(*) from sip_capture_call_20160527 where date between ('2016-05-27 00:25:00') and ('2016-05-27 23:25:00');
+----------+
| count(*) |
+----------+
|      312 |
+----------+
1 row in set (0.00 sec)**

Is there any settings ???

Thanks for any help...

**Comment by lmangani** [comment]
This is expected unless you change value using the ```query limit``` form parameter.

https://github.com/sipcapture/homer/wiki/Using-Homer-5#sip-search-customization

**Comment by xihh401** [comment]
Thanks a lot
