### ISSUE TITLE
Webinterface Bug in Homer 5.0.5

### ISSUE THREAD

**Issue by ciscospirit** [sipcapture/homer#175]
Hello,

i found out since the last update you changed something in your "export" section, and so there are 2 things i want to notice:

1.) If you press "Share Link" the link url is now not visible any more after pressing the button "Share Link" button. So you must rightclick on the hyperlink to copy out the url or open the hyperlink and copy out the url from the browser. Thats not really workflow friendy. Last version, that the url was directly put under the menubar was better in my opinion. Or you copy/paste the link directly in the Clipboard? would also be nice feature.

2.) the view of a shared link has also a bug... if you open such a link a new browser window will be opened with the "call Flow" analysis. but if you press on a leg detail the detail window is anywhere on the screen.. so you cant also not touch it our move it or whatever... So you also can't close the detail window so you must refresh the site to scroll up and down or whatever again.

![image](https://cloud.githubusercontent.com/assets/15861549/15964696/0f616102-2f1a-11e6-9d27-17412da08972.png)

**Comment by lmangani** [comment]
Thanks for the report! Will check and update

**Comment by lmangani** [comment]
Updates on this one:

1) not sure what the difference would be between right-click copying the previous link and the current link in the popup? Could you extend on how it affects the workflow negatively?

2) please pull the latest UI code and retest to see if resolved (popup should behave as in main UI)

**Comment by lmangani** [comment]
Fixed in latest GIT of UI, for issue 1) feel free to open a dedicated feature change/request

Thanks!
