### ISSUE TITLE
Problem data in WebHomer

### ISSUE THREAD

**Issue by camiloortiz** [sipcapture/homer#176]
After installation HOMER the only table information  running is Homer_data , and do not enter information to webhomer .
someone has or fix this problem?

**Comment by lmangani** [comment]
Please provide details about your setup it's impossible to help you otherwise - thanks

**Comment by camiloortiz** [comment]
Thanks Imangani. The specs are 
Debian 8.4
kamailio 5.0.0-dev4
Apache/2.4.10 (Debian)
homer-ui,5.0.2 ( git )

we're only monitoring a single instance of asterisk 13.7.2 via res_hep. we can see that there is data only in rtcp_capture table in homer_data and stats_data in homer_statistic. No data in the web interface. 

Thanks in advance

**Comment by lmangani** [comment]
Hi @camiloortiz 
The description would suggest you are not using ```chan_pjsip ``` which is a requirement for the built in mirroring of SIP packets. The quickest solution is to deploy captagent 6.x on the Asterisk box and configure it to mirror all packets of interest to your HOMER instance.

**Comment by lmangani** [comment]
@camiloortiz any updates here? Feel free to reopen if useful anytime
