### ISSUE TITLE
Docker compose install problem with homer-kamailio

### ISSUE THREAD

**Issue by bathizte** [sipcapture/homer#177]
Hello,

According to [the docker install page in the wiki](https://github.com/sipcapture/homer/wiki/Docker-Install), docker-compose pull should download preexisting docker images for the environnement.

However it seems the homer-kamailio images has moved :
    [/usr/src/homer-docker] (master ✔)# docker-compose pull
    Pulling mysql (mysql:5.6)...
    5.6: Pulling from library/mysql
    [...]
    Digest: sha256:03646869dfecf96f443640f8b9040fbde78a96269aaf47bbfbb505a4c1adcad9
    Pulling kamailio (qxip/homer-kamailio:latest)...
    Pulling repository docker.io/qxip/homer-kamailio
    ERROR: Error: image qxip/homer-kamailio not found

What is your advice ? building myself the homer-kamailio image ? Or do you have an other repo available for me to fix the docker-compose.yml file ?

Thanks !
Baptiste

**Comment by bathizte** [comment]
OK I just found that issue which is actually the same : 
https://github.com/sipcapture/homer-docker/issues/14

So it seems that the wiki has to be updated :).

**Comment by lmangani** [comment]
Wiki Fixed! Thanks for the reminder ;)
