### ISSUE TITLE
Dashboard changes not saved

### ISSUE THREAD

**Issue by mkowalski** [sipcapture/homer#178]
Hi,

My changes made to any of the dashboards are not visible after logging off. Even if I save panel and then save a grid, the changes are lost. Also when creating a new dashboard it's not visible anywhere (even searching by name does not show it). Where may be the problem?

DB access and rest of the things works correctly, default dashboards work like a charm, but I cannot make any changes.

Homer installed on CentOS 7 from sources.

Thanks for help,
Mateusz

**Comment by lmangani** [comment]
Hi @mkowalski 

Please make sure the ```api/store/dashboard``` folder features write permissions for the webserver

**Comment by mkowalski** [comment]
I have no such a directory in my filesystem

```
[root@tone-0513z-mon api]# pwd
/var/www/sipcapture/htdocs/api
[root@tone-0513z-mon api]# ls -l
total 88
drwxr-xr-x. 2 root root  4096 Jul  1 18:03 Authentication
-rw-r--r--. 1 root root  7338 Jul  1 18:03 autoload.php
-rw-r--r--. 1 root root   793 Jul  1 18:03 configuration_example.php
-rw-r--r--. 1 root root   795 Jul  1 18:03 configuration.php
-rw-r--r--. 1 root root 34520 Jul  1 18:03 COPYING
drwxr-xr-x. 3 root root    85 Jul  1 18:03 Database
-rw-r--r--. 1 root root  9636 Jul  1 18:03 index.php
-rw-r--r--. 1 root root  4604 Jul  1 18:03 preferences_example.php
-rw-r--r--. 1 root root  4604 Jul  1 18:03 preferences.php
drwxr-xr-x. 2 root root  4096 Jul  1 18:03 RestApi
drwxr-xr-x. 2 root root    82 Jul  1 18:03 RestService
drwxr-xr-x. 2 root root    42 Jul  1 18:03 Statistic
[root@tone-0513z-mon api]#
```

**Comment by lmangani** [comment]
The directory is in the main root folder ```/store/dashboard```
https://github.com/sipcapture/homer-ui/tree/master/store

**Comment by mkowalski** [comment]
Great, works like a charm now. Thanks for super fast help!

**Comment by lmangani** [comment]
You're most welcome!

**Comment by ryeager315** [comment]
Having the same issue.  I validated /home-ui/store/dashboard permissions include write access and ownership is apache.  

# ls -Flta
total 4
drwxr-xr-x. 15 apache apache 4096 Jul 25 13:31 ../
drwxr-xr-x.  4 apache apache   56 Jul 21 15:28 ./
drwxrwxrwx.  2 apache apache  240 Jul 21 15:28 dashboard/
-rwxrwxrwx.  1 apache apache    0 Jul 21 15:28 index.html*
drwxrwxrwx.  2 apache apache   24 Jul 21 15:28 profile/

All files in dashboard also have write permissions and apache as owner:
]# ls -Flta
total 764
drwxrwxrwx. 2 apache apache    240 Jul 21 15:28 ./
drwxr-xr-x. 4 apache apache     56 Jul 21 15:28 ../
-rwxrwxrwx. 1 apache apache 288794 Jul 21 15:28 _1411848944046.json*
-rwxrwxrwx. 1 apache apache   1350 Jul 21 15:28 _1426001444630.json*
-rwxrwxrwx. 1 apache apache 203764 Jul 21 15:28 _1427728371642.json*
-rwxrwxrwx. 1 apache apache 265772 Jul 21 15:28 _1428431423814.json*
-rwxrwxrwx. 1 apache apache    751 Jul 21 15:28 _1430318378410.json*
-rwxrwxrwx. 1 apache apache   2125 Jul 21 15:28 _1431721484444.json*
-rwxrwxrwx. 1 apache apache   2813 Jul 21 15:28 _1450278390101.json*
-rwxrwxrwx. 1 apache apache   3316 Jul 21 15:28 _1452069187383.json*
-rwxrwxrwx. 1 apache apache      0 Jul 21 15:28 index.html*

from /var/log/httpd/error-log:
[:error] [pid xxxx] [client xxx.xxx.xxx.xxx:xxxxxx] PHP Warning:  fopen(/var/www/html/homer/store/dashboard/_1427728371642.json): failed to open stream: Permission denied in /var/www/html/homer/api/RestApi/Dashboard.php on line 298, referer: http://xxx.xxx.xxx.xxx/

**Comment by adubovikov** [comment]
nothing new: "Permission denied", you have to fix it

**Comment by ryeager315** [comment]
As you see, permissions were set to 777, but still permission denied.  So where is the permission issue?  It is not in homer-ui.  PID is owned by apache.  If I knew what permissions to fix I would.  Do you have any other ideas?

**Comment by ryeager315** [comment]
Ahh....got it.  SELinux permissions, not file permissions.
