### ISSUE TITLE
 Error opening Kamailio's FIFO

### ISSUE THREAD

**Issue by fagnersilva** [sipcapture/homer#179]
I'm running the kamailio version 4.4 along with Homer 5, is generating the error below

[root@sipserver ~]# kamctl ul show
ERROR: Error opening Kamailio's FIFO /tmp/kamailio_fifo
ERROR: Make sure you have the line 'modparam("mi_fifo", "fifo_name", "/tmp/kamailio_fifo")' in your config
ERROR: and also have loaded the mi_fifo module.

configuration example kamailio.cfg
[root@sipserver ~]# vim /etc/kamailio/kamailio.cfg
####### Routing Logic ########
modparam("sipcapture", "db_url", "mysql://HOMER_DB_USER:HOMER_DB_PASSWORD@127.0.0.1/homer_data")
modparam("sipcapture", "capture_on", 1)
modparam("sipcapture", "hep_capture_on", 1)
modparam("sipcapture", "insert_retries", 5)
modparam("sipcapture", "insert_retry_timeout", 10)
#modparam("sipcapture", "capture_node", "homer01")
modparam("mi_fifo", "fifo_name", "/tmp/kamailio_fifo")

configuration example kamctlrc
[root@sipserver ~]# vim /etc/kamailio/kamctlrc
#######  FIFOPATH="/var/run/kamailio/kamailio_fifo"
FIFOPATH="/tmp/kamailio_fifo"

**Comment by lmangani** [comment]
Hi @fagnersilva 

Homer is not meant to handle user registration or any role other than capture server.
Consequently general purpose commands will not work (or make sense)

I hope this helps!

**Comment by fagnersilva** [comment]
@lmangani which option best to implement HOMER , maintain application in each separate server?

**Comment by lmangani** [comment]
Hi @fagnersilva 
Homer/Kamailio should be on a dedicated server, the agents can co-exist with the application they monitor or leverage HEP integrations where available.
