### ISSUE TITLE
When CFLOW POPUP = 2 , the 'RTCP INFO' and 'CDR INFO' buttons do nothing.

### ISSUE THREAD

**Issue by marrold** [sipcapture/homer#18]
When CFLOW POPUP = 2  the 'RTCP INFO' and 'CDR INFO' buttons do nothing-

define('CFLOW_POPUP',2); /* Modal type: 1, Browser popup: 2 */

Error-

'TypeError: $.toJSON is not a function' in Firefox Console
 'Object doesn't support property or method 'toJSON'' in IE Console 

This works fine when CFLOW POPUP = 1

**Comment by adubovikov** [comment]
fixed

https://github.com/sipcapture/homer/commit/41387e71c34b41987f6297671080aa2cb6bb1275
