### ISSUE TITLE
Allowed characters for Call ID field at RTCP-XR Publish packet 

### ISSUE THREAD

**Issue by N1ck3l** [sipcapture/homer#180]
Hi. I was having issues at the homer5 setup, I found that the call ID was not being properly stored at the homer_data database, at report_capture table. It was being truncated 

I had to modify this line at kamailio.conf:

$var(callid) = $(rb{re.subst,/(.*)CallID:([0-9A-Za-z@-]{5,120})(.*)$/\2/s});

to this:

$var(callid) = $(rb{re.subst,/(.*)CallID:([0-9A-Za-z\_\-\.@-]{5,120})(.*)$/\2/s});

Only added the escaped "_", "-" and "." because some of carriers we use include those chars as part of their caller ID. IE: "0_4883729492002@127.0.0.1" 

I'm testing it now, but seems to work.

**Comment by lmangani** [comment]
Let us know if your tests validate the above and we'll merge the new rule in - thanks!

**Comment by N1ck3l** [comment]
Yes. it seems to be working. I have not tried removing the escaping (backslashes) before the "_" and "."

I will test again tomorrow and will update this. But at least no more errors at the log since that change.  

BTW I think I duplicated some chars. tomorrow I will try instead:

`$var(callid) = $(rb{re.subst,/(.)CallID:([0-9A-Za-z\_\.@-]{5,120})(.)$/\2/s});`

**Comment by N1ck3l** [comment]
Ok, I am confirming that this is the proper config: (no backslash needed)

`$var(callid) = $(rb{re.subst,/(.*)CallID:([0-9A-Za-z_.@-]{5,120})(.*)$/\2/s});`

Only need to add "-" and "." to the character list.

**Comment by adubovikov** [comment]
@N1ck3l can you please do push request ? this way is easy for us to track all changes

**Comment by adubovikov** [comment]
it was fixed
