### ISSUE TITLE
Problem when displaying rtcp graphs. Data captured and stored but graph empty.

### ISSUE THREAD

**Issue by N1ck3l** [sipcapture/homer#181]
Hi. I was having another problem with the RTCP graphs at homer5

At the error.log I had this line:

` PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/html/api/RestApi/Report.php on line 514,`

as a result, I was not able to see the the rtcp graphs. (See attached file, rtcp error)

![rtcp error](https://cloud.githubusercontent.com/assets/18313853/16933993/54ceb8ec-4d20-11e6-8521-ccc2aad401c4.png)

I look at the code and the database and found that the msg field from rtcp_capture had the proper json string, but it was including a NULL character at the end, causing an error when using the json_decode.

I did a quick fix at the file '/api/RestApi/Report.php', line 480:

Changed  from this:

`$d = json_decode($data[$key]["msg"], true);`

to 

`$d = json_decode(substr($data[$key]["msg"],0,-1), true);` 

Finally I got the rtcp graphs.  ( See attached file, rtcp working). 

![rtcp working](https://cloud.githubusercontent.com/assets/18313853/16933999/61181328-4d20-11e6-8874-dd30196d63b1.png)

This can be improved, with validation to see if there is a null at the end of the string and remove only if necessary. I will try to do it tomorrow.

BTW: I am impressed with Homer5. I really appreciate what you are creating here, guys. Keep up the good work!

**Comment by adubovikov** [comment]
@N1ck3l can you please provide this JSON string ?

**Comment by adubovikov** [comment]
can you please check this patch ?
https://github.com/sipcapture/homer-api/commit/c1e78da3316f1639fee9171c1fd81dbf9891fc65

**Comment by N1ck3l** [comment]
Ok: Json Strings:

`{ "sender_information":{"ntp_timestamp_sec":215287040,"ntp_timestamp_usec":1355192665,"octets":1201440,"rtp_timestamp":4084438441, "packets":7509},"ssrc":3996133049,"type":200, "report_blocks":[{"source_ssrc":3863654907,"highest_seq_no":7835,"fraction_lost":0,"ia_jitter":6,"packets_lost":0,"lsr":0,"dlsr":0}],"report_count":1,"sdes_ssrc":3996133049,"sdes_chunk_ssrc":17717605,"sdes_information": [ {"type":1,"text":"Yealink Co.Ltd"},{"type":3,"text":"sales@yealink.com"}],"sdes_report_count":2} **NUL**`

[json string.txt](https://github.com/sipcapture/homer/files/371622/json.string.txt)
[json string 2.txt](https://github.com/sipcapture/homer/files/371624/json.string.2.txt)
[json string 3.txt](https://github.com/sipcapture/homer/files/371625/json.string.3.txt)

I will test the patch and update you in a moment.

**Comment by N1ck3l** [comment]
Yes, I confirm the patch works. Great Work!

**Comment by adubovikov** [comment]
ok, I am closing the ticket
