### ISSUE TITLE
Question - disabling authentication

### ISSUE THREAD

**Issue by mkowalski** [sipcapture/homer#182]
Hi,

Is it possible to completely disable authentication on Homer side. I have build my own SSO on top of it, so if user reaches Homer itself it is guaranteed he's authenticated.

As I don't need multiple accounts on Homer, everyone could be pre-authenticated as an Admin.

It scenario like this possible?

Cheers,
Mateusz

**Comment by adubovikov** [comment]
Hi,

yes, please check to External.php auth

https://github.com/sipcapture/homer-api/blob/master/api/Authentication/External.php

Wbr,
Alexandr

**Comment by adubovikov** [comment]
please open if you still have any questions

**Comment by manujha** [comment]
Hey,
I have installed the homer webapp and heplify server via docker-compose.
It there a way to disable the authentication when using these?

TIA

**Comment by lmangani** [comment]
@manujha you can remove the caddy proxy. You will still have to authenticate to the homer webapp in order to use it.
