### ISSUE TITLE
Cumulative number of packets lost in RTCP should be a signed 3-byte number. 

### ISSUE THREAD

**Issue by N1ck3l** [sipcapture/homer#183]
Hi. I was getting odd numbers at MOS at the QoS Reports.

After digging a bit, I found that our original rtcp packets had extremely high values; 16 millions packets lost at some calls. 

---

![rtcp error high packet loss](https://cloud.githubusercontent.com/assets/18313853/17302362/dcbb514c-57e9-11e6-8897-505abc01636c.png)

---

After the capture,  using wireshark at the SSRC contents, I found that the 'Cumulative number of packets lost' was -2, and the value was FF:FF:FE. 

---
## ![rtcp lost packets](https://cloud.githubusercontent.com/assets/18313853/17302371/e633a062-57e9-11e6-96a2-9c197c9796ed.png)

That means that the captagent that I am using needs to proper decode the 3-bytes as a signed int and not as a unsigned int, likely the same bug that wireshark had a bit of time ago at this link: https://www.wireshark.org/lists/wireshark-bugs/200907/msg00630.html

As a quick workaround, I added a quick validation at the RTCP report API:

`/api/RestApi/Report.php`

and had to add a couple of lines to validate if the number exceeds the high limit:

`        foreach($blocks as $r => $block)
                        {
                                //new lines
                                if($block["packets_lost"] > 8388607) //quick fix for packet loss negative unsigned
                                {
                                $block["packets_lost"] = 0;
                                }
                                //end of new lines
                                $tmpMos = round($this->calculateJitterMos($block["dlsr"] < 1000 ? $block["dlsr"] : 0 ,$block["ia_jitter"],$block["packets_lost"]),2);
                                $statsData[$ipkey]["mos_counter"] += 1;
                                $statsData[$ipkey]["mos_average"] += $tmpMos;

`

Now it shows better (and hopefully expected) behavior:

---
## ![rtcp error high packet loss - patched](https://cloud.githubusercontent.com/assets/18313853/17302389/02788b98-57ea-11e6-9f85-f8df950ee2a5.png)

I believe this would need a fix at the captagent, here or both places.

**Comment by adubovikov** [comment]
Thank you for the bug report and also for the workaround. Can you please do a pull request ?

**Comment by adubovikov** [comment]
https://github.com/sipcapture/captagent/commit/45d3e72bc53e6b9863137f89f689a9f998b291dc

can you please check ?

**Comment by N1ck3l** [comment]
Sorry for not doing the "pull" but honestly I am still reading about how to use git. I will test and update you.

**Comment by adubovikov** [comment]
it's easy, just make a fork, do changes in your local repository and press
the push request button.
