### ISSUE TITLE
No Stats Presented in Search

### ISSUE THREAD

**Issue by jackstevens100** [sipcapture/homer#184]
Hi Guys,

I have performed a clean install of Homer on Debian 8 using the packages. We have also got our kamailio box's pushing data over to the homer box now we can see data such as IP Invites. But when we try and use the search function it does not show any records. I have browsed to the following http://x.x.x.x:80/api and it displays without an error. Has anyone else come across this issue. I have also attached a couple of screenshots to help

![sipcap1](https://cloud.githubusercontent.com/assets/20946458/17550075/21b1533e-5eeb-11e6-84a1-b986ad0d8957.PNG)
![sipcap2](https://cloud.githubusercontent.com/assets/20946458/17550076/21c91f5a-5eeb-11e6-9b20-4f8e50389ffb.PNG)
![sipcap3](https://cloud.githubusercontent.com/assets/20946458/17550077/21d8f786-5eeb-11e6-9503-72867ff3cca4.PNG)

 this problem before

**Comment by lmangani** [comment]
Hi Jack,

Please doublecheck to make sure the systems times are syncronized. Homer internally logs using UTC so a timezone should be selected too. If you are sure settings are correct, please check the Kamailio logs for insert errors of any kind, and/or provide the API request/response for no data.

_note: This is hardly a bug rather a configuration/usage issue you might want to use the mailing list for._

**Comment by jackstevens100** [comment]
Hi Imangani,

Thanks for the quick response I wasn't expecting that. i have checked the time and date on all of the boxes I can see in the kamailio logs the following I am rather new so a bit of a push in the right direction would be a great help

 Table 'homer_data.sip_capture_call_20160810' doesn't exist (1146)

**Comment by lmangani** [comment]
Hi @jackstevens100 this would suggest your rotation scripts are not running from Cron (or at all)
How did you install HOMER? Could you try manually execute the homer_rotate script and check for any output errors? My guess is bad authentication details in the script itself but this depends how you installed - best method is currently our installer script.

**Comment by jackstevens100** [comment]
hi @lmangani I followed the below for installation
https://github.com/sipcapture/homer-installer#package-packages

can you please let me know how to execute this script on debian

**Comment by lmangani** [comment]
@jackstevens100 the installer can be executed by running:
```
bash <( curl -s https://cdn.rawgit.com/sipcapture/homer-installer/master/homer_installer.sh )
```

Your root crontab should include:
```
30 3 * * * /opt/homer_rotate >> /var/log/cron.log 2>&1
```

Try to execute ```/opt/homer_rotate``` manually and report its output, and check if the tables were created in MySQL

**Comment by jackstevens100** [comment]
okay I have ran the rotate script and I get the following output

DBI connect('homer_data:localhost:3306','homer_user',...) failed: Access denied for user 'homer_user'@'localhost' to database 'homer_data' at /opt/homer_mysql_rotate.pl line 211.
Can't call method "prepare" on an undefined value at /opt/homer_mysql_rotate.pl line 300.

so you were right its an authentication issue with the DB so how do i get the credentials to modify the job



________________________________

**Comment by lmangani** [comment]
The script normally patches the configuration [itself](https://github.com/sipcapture/homer-installer/blob/master/homer_installer.sh#L291)

Please manually port the same database configuration details utilized in HOMER's ```configuration.php``` (or any other valid credentials with write permissions) in the rotation script to address the issue

**Comment by jackstevens100** [comment]
hi @lmangani  the problem that i get when running that script is the following and it does not seem to progress 
Starting mysqld
/dev/fd/63: line 213: /etc/init.d/mysql: No such file or directo

**Comment by lmangani** [comment]
Please provide the full installation log for suggestions. 
You can mail it to support@sipcapture.org if privacy is a concern
