### ISSUE TITLE
Debian Installation Error

### ISSUE THREAD

**Issue by mshoaib67** [sipcapture/homer#186]
Hi,
Getting **Starting mysqld
/dev/fd/63: line 213: /etc/init.d/mysql: No such file or directory
** error

> bash <( curl -s https://cdn.rawgit.com/sipcapture/homer-installer/master/homer_installer.sh )

& its not working either if installation is done on Cent OS 7

**Comment by lmangani** [comment]
Hi @mshoaib67 
Line 213 shouldn't be executed on CentOS as its part of the Debian setup.
Please open an issue on https://github.com/sipcapture/homer-installer with the full OS details nad installation logs.
