### ISSUE TITLE
homer submodule for captagent fails to checkout

### ISSUE THREAD

**Issue by quentusrex** [sipcapture/homer#187]
root@outpost01:/usr/src# git clone https://github.com/sipcapture/homer.git
Cloning into 'homer'...
remote: Counting objects: 6407, done.
remote: Total 6407 (delta 0), reused 0 (delta 0), pack-reused 6407
Receiving objects: 100% (6407/6407), 5.09 MiB | 2.43 MiB/s, done.
Resolving deltas: 100% (3639/3639), done.
Checking connectivity... done.
root@outpost01:/usr/src# cd homer/
root@outpost01:/usr/src/homer# git submodule init
Submodule 'captagent' (https://github.com/sipcapture/captagent.git) registered for path 'captagent'
Submodule 'homer-api' (https://github.com/sipcapture/homer-api.git) registered for path 'homer-api'
Submodule 'homer-ui' (https://github.com/sipcapture/homer-ui.git) registered for path 'homer-ui'
root@outpost01:/usr/src/homer# git submodule update --init --recursive
Cloning into 'captagent'...
remote: Counting objects: 3723, done.
remote: Total 3723 (delta 0), reused 0 (delta 0), pack-reused 3723
Receiving objects: 100% (3723/3723), 4.79 MiB | 1.81 MiB/s, done.
Resolving deltas: 100% (2241/2241), done.
Checking connectivity... done.
fatal: reference is not a tree: a897f70f86e7f8d3da9dfc7ed1f8336660ea14e0
Cloning into 'homer-api'...
remote: Counting objects: 2196, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 2196 (delta 22), reused 0 (delta 0), pack-reused 2152
Receiving objects: 100% (2196/2196), 814.26 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1366/1366), done.
Checking connectivity... done.
Submodule path 'homer-api': checked out '91af432e40bc28ecb9d6ba8119190a11b9ec824d'
Cloning into 'homer-ui'...
remote: Counting objects: 2600, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 2600 (delta 1), reused 0 (delta 0), pack-reused 2590
Receiving objects: 100% (2600/2600), 4.55 MiB | 2.01 MiB/s, done.
Resolving deltas: 100% (1625/1625), done.
Checking connectivity... done.
Submodule path 'homer-ui': checked out 'f47fbf842643a62de5b209ee2c4441d89334b0aa'
Unable to checkout 'a897f70f86e7f8d3da9dfc7ed1f8336660ea14e0' in submodule path 'captagent'

**Comment by adubovikov** [comment]
Hi @quentusrex ,

fixed. Please re-check.

Wbr,
Alexandr
