### ISSUE TITLE
GUi filter not working correctly

### ISSUE THREAD

**Issue by andycol** [sipcapture/homer#188]
When i change the date search for the past 24 hours for example it only shows an hours worth of calls
and if you set a date range bigger then an hour it also only shows 1 hours worth of calls
but there are all calls for the past 24 hours as we are writing around 300+ concurrent calls throughout the day

**Comment by lmangani** [comment]
Did you set the Query Limit parameter to a high value?

**Comment by ljubo2015** [comment]
Hey andycol default value in query limit is 100 you just need to change that value to higher ex:1000 or 2000.
