### ISSUE TITLE
Geo Chart: Incompatible data table: Error: Table contains more columns than expected (Expecting 2 columns)

### ISSUE THREAD

**Issue by stiw47** [sipcapture/homer#189]
Hello all.
First of all, sorry cause I posting this issue, I know it is already posted as issue 151 and closed, but I didn't solved my (same) problem. Probably, I don't understanding good as I'm not so advanced as you.

Ok - scenario:
-Fresh installed Debian Jessie amd64 KDE in Virtual Box
-Fresh installed Homer 5.0.5 via your official homer_installer.sh script from here:
[https://github.com/sipcapture/homer/wiki/Quick-Install](url)
-Everything is default, Homer is working, I receiving SIP data from FreeSWITCH on other machine.
-Kamailio is installed from homer_installer.sh
-MySQL is installed via apt-get before homer_installer.sh was started because homer_installer.sh stuck on step when should to install MySQL
-Databases and tables in MySQL are created with homer_installer.sh
-I have next data bases:
+---------------------+
| Database                   |
+---------------------+
| information_schema  |
| homer_configuration |
| homer_data               |
| homer_statistic           |
| mysql                        |
| performance_schema  |
+---------------------+

Also have next tables:
+-----------------------------------+
| Tables_in_homer_data              |
+-----------------------------------+
| logs_capture                      |
| report_capture                    |
| rtcp_capture                      |
| sip_capture_call_20160913         |
| sip_capture_call_20160914         |
| sip_capture_call_20160915         |
| sip_capture_registration_20160913 |
| sip_capture_registration_20160914 |
| sip_capture_registration_20160915 |
| sip_capture_rest_20160913         |
| sip_capture_rest_20160914         |
| sip_capture_rest_20160915         |
| webrtc_capture                    |
+-----------------------------------+

+---------------------------+
| Tables_in_homer_statistic |
+---------------------------+
| alarm_config              |
| alarm_data                |
| alarm_data_mem            |
| stats_data                |
| stats_dest_mem            |
| stats_dest_reply          |
| stats_generic             |
| stats_geo                 |
| stats_geo_mem             |
| stats_ip                  |
| stats_ip_mem              |
| stats_method              |
| stats_method_mem          |
| stats_useragent           |
| stats_useragent_mem       |
+---------------------------+

Please note: In kamailio.cfg, I changed a:

`##!define WITH_HOMER_GEO

to

#!define WITH_HOMER_GEO`

and

`modparam("geoip", "path", "/usr/share/GeoIP/GeoIP.dat")

to

modparam("geoip", "path", "/usr/share/GeoIP/GeoIPCity.dat")`

than, restarted Kamailio several times.

I cannot get World Map, and always have a message: Incompatible data table: Error: Table contains more columns than expected (Expecting 2 columns)

Tell me please: Can you help me to configure this, and if you can, what config files you need to paste here.

Thanks in advance.

**Comment by adubovikov** [comment]
do you have any data in the geo table ?

**Comment by stiw47** [comment]
No.
stats_geo and stats_geo_mem are emtpty both.

**Comment by adubovikov** [comment]
so, maybe because you defined WITH_HOMER_GEO wrong ?

#!define WITH_HOMER_GEO**`**

and must be

#!define WITH_HOMER_GEO

**Comment by stiw47** [comment]
Sorry, but mark ` is my typing mistake. It is from 'Insert code' tool, here on GIT hub.
In my kamailio.cfg standing just as you said:

#!define WITH_HOMER_GEO

**Comment by adubovikov** [comment]
anyway, please add xlog to this block and check if there are any inserts....

**Comment by stiw47** [comment]
Sorry because of delay. This is a log which I catch with **kamailio -ddddddddd** during one call (cca 30sec). I hope that posting right thing.


[kamailio.txt](https://github.com/sipcapture/homer/files/472146/kamailio.txt)

**Comment by adubovikov** [comment]
this doesn't help, you have to add xlog in the geo block and check syslog later


https://github.com/sipcapture/homer-api/blob/master/examples/sipcapture/sipcapture.kamailio#L147

something like this:
xlog("Data  source IP: $si");

**Comment by stiw47** [comment]
I already have geo block from link you mentioned and don't know what to do with

xlog("Data source IP: $si");

**Comment by adubovikov** [comment]
just add this before line 147 and restart kamailio

**Comment by stiw47** [comment]
Ok, I added  xlog("Data source IP: $si"); in geo block, this is a part of syslog during a call:

[kamailio2.txt](https://github.com/sipcapture/homer/files/472322/kamailio2.txt)

**Comment by adubovikov** [comment]
<script>: Data source IP: 10.28.73.11

this is private IP and of course it doesn't have any "country"

**Comment by stiw47** [comment]
Ok. Can we put my private IP in "second place" just for moment? (I planing to migrate all this stuffs to public IP)

If I understand right, web Homer GUI just reading data from databases and show them on display, am I right?

I entered one entry manually into **stats_geo_mem** form terminal:

mysql>INSERT INTO stats_geo_mem ( method, country, lat, lon, total) VALUES('INVITE','Somalia',10.0000,49.0000,1);

Than I log out from Homer web, log in and Geo charts again display same error as in thread title, without world map. After that, I restarted a Homer machine. I notice entry from **stats_geo_mem** is now in **stats_geo** (and stats_geo_mem is empty):

mysql> select * from stats_geo;
+----+---------------------+---------------------+--------+---------+-----+-----+-------+
| id | from_date           | to_date             | method | country | lat | lon | total |
+----+---------------------+---------------------+--------+---------+-----+-----+-------+
|  1 | 2016-09-15 11:10:00 | 2016-09-15 11:15:00 | INVITE | Somalia |  10 |  49 |     1 |
+----+---------------------+---------------------+--------+---------+-----+-----+-------+


But in Homer web, again have nothing in Geo chart, only error.
Can you tell me where to looking for issue?

**Comment by adubovikov** [comment]
sorry, I didn't get you about "second place". If you want add private IP to geo DB, please contact Maxmind, maybe they can help you.

I close the ticket, because there is no issue related to homer-api.

**Comment by lmangani** [comment]
Reopening, issue is about ```Error: Table contains more columns than expected```

**Comment by lmangani** [comment]
Added to ```https://github.com/sipcapture/homer/wiki/FAQ```
