### ISSUE TITLE
GeoIP no sum for stats

### ISSUE THREAD

**Issue by ljubo2015** [sipcapture/homer#190]
Hello guys,
I am having issues with GeoMap not showing sum of values based on search.
(Please don't take this for granted as this is based on my current research)
1.Picture should represent min and max value from map and based on those values change colors on map
![image](https://cloud.githubusercontent.com/assets/15197215/18552466/da049a3a-7b5c-11e6-9c86-8c4540512932.png)
2.It should display sum for this country not only first row for defined time frame for example last 12h only showing first value.
![image](https://cloud.githubusercontent.com/assets/15197215/18552526/0f765334-7b5d-11e6-9112-1f2778c06bdd.png)

Please let me know if any additional information are needed. Data is there and i see stats are made each 5min but i am not sure if js source for geochart needs to be changed ?

**Comment by adubovikov** [comment]
check that you have in the API reply, paste please the data object

**Comment by ljubo2015** [comment]
Okay so based on reguest(if i am right):
1.I tried to use geo widget which it seems has some bug* screenshot below i am not able to go to expert mode:
![image](https://cloud.githubusercontent.com/assets/15197215/18552821/703788ae-7b5e-11e6-8239-843b2496e733.png)
2.I used normal widget:
curl -v --cookie 'HOMERSESSID=undefined' -X POST \
-d '{"timestamp":{"from":1473904975799,"to":1473948175799},"param":{"filter":[{"country":"ALL"}],"total":false}}' \
 "http://10.16.40.142/api/v1/statistic/country"
Output:{"status":200,"sid":"i7cc05bnd7vqld5enfic2tm050","auth":"true","message":"ok","data":[{"id":"61","from_ts":"1473947400","to_ts":"1473947700","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"60","from_ts":"1473947100","to_ts":"1473947400","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"1"},{"id":"59","from_ts":"1473947100","to_ts":"1473947400","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"58","from_ts":"1473946800","to_ts":"1473947100","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"57","from_ts":"1473946500","to_ts":"1473946800","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"56","from_ts":"1473946200","to_ts":"1473946500","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"55","from_ts":"1473946200","to_ts":"1473946500","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"3"},{"id":"54","from_ts":"1473945900","to_ts":"1473946200","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"53","from_ts":"1473945600","to_ts":"1473945900","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"10"},{"id":"52","from_ts":"1473945600","to_ts":"1473945900","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"51","from_ts":"1473945300","to_ts":"1473945600","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"8"},{"id":"50","from_ts":"1473945300","to_ts":"1473945600","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"13"},{"id":"49","from_ts":"1473945000","to_ts":"1473945300","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"10"},{"id":"48","from_ts":"1473944700","to_ts":"1473945000","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"10"},{"id":"47","from_ts":"1473944400","to_ts":"1473944700","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"12"},{"id":"46","from_ts":"1473944100","to_ts":"1473944400","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"12"},{"id":"45","from_ts":"1473943800","to_ts":"1473944100","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"12"},{"id":"44","from_ts":"1473943500","to_ts":"1473943800","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"12"},{"id":"43","from_ts":"1473943200","to_ts":"1473943500","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"12"},{"id":"42","from_ts":"1473942900","to_ts":"1473943200","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"11"},{"id":"41","from_ts":"1473942600","to_ts":"1473942900","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"12"},{"id":"40","from_ts":"1473942300","to_ts":"1473942600","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"12"},{"id":"39","from_ts":"1473942000","to_ts":"1473942300","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"14"},{"id":"38","from_ts":"1473942000","to_ts":"1473942300","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"7"},{"id":"37","from_ts":"1473941700","to_ts":"1473942000","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"36","from_ts":"1473941700","to_ts":"1473942000","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"13"},{"id":"35","from_ts":"1473941400","to_ts":"1473941700","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"12"},{"id":"34","from_ts":"1473941400","to_ts":"1473941700","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"33","from_ts":"1473941100","to_ts":"1473941400","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"21"},{"id":"32","from_ts":"1473941100","to_ts":"1473941400","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"31","from_ts":"1473940800","to_ts":"1473941100","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"22"},{"id":"30","from_ts":"1473940800","to_ts":"1473941100","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"29","from_ts":"1473940500","to_ts":"1473940800","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"28"},{"id":"28","from_ts":"1473940500","to_ts":"1473940800","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"27","from_ts":"1473940200","to_ts":"1473940500","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"27"},{"id":"26","from_ts":"1473940200","to_ts":"1473940500","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"13"},{"id":"25","from_ts":"1473939900","to_ts":"1473940200","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"25"},{"id":"24","from_ts":"1473939900","to_ts":"1473940200","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"23","from_ts":"1473939600","to_ts":"1473939900","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"24"},{"id":"22","from_ts":"1473939600","to_ts":"1473939900","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"21","from_ts":"1473939300","to_ts":"1473939600","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"24"},{"id":"20","from_ts":"1473939300","to_ts":"1473939600","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"19","from_ts":"1473939000","to_ts":"1473939300","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"24"},{"id":"18","from_ts":"1473939000","to_ts":"1473939300","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"17","from_ts":"1473938700","to_ts":"1473939000","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"16","from_ts":"1473938700","to_ts":"1473939000","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"27"},{"id":"15","from_ts":"1473938400","to_ts":"1473938700","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"24"},{"id":"14","from_ts":"1473938400","to_ts":"1473938700","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"13","from_ts":"1473938100","to_ts":"1473938400","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"26"},{"id":"12","from_ts":"1473938100","to_ts":"1473938400","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"11","from_ts":"1473937800","to_ts":"1473938100","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"26"},{"id":"10","from_ts":"1473937800","to_ts":"1473938100","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"9","from_ts":"1473937500","to_ts":"1473937800","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"26"},{"id":"8","from_ts":"1473937500","to_ts":"1473937800","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"7","from_ts":"1473937200","to_ts":"1473937500","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"26"},{"id":"6","from_ts":"1473937200","to_ts":"1473937500","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"13"},{"id":"5","from_ts":"1473936900","to_ts":"1473937200","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"26"},{"id":"4","from_ts":"1473936900","to_ts":"1473937200","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"13"},{"id":"3","from_ts":"1473936600","to_ts":"1473936900","country":"BE","lat":"50.85","lon":"4.35","method":"INVITE","total":"26"},{"id":"2","from_ts":"1473936600","to_ts":"1473936900","country":"US","lat":"39.7525","lon":"-104.999","method":"INVITE","total":"14"},{"id":"1","from_ts":"1473936000","to_ts":"1473936300","country":"Somalia","lat":"10","lon":"49","method":"INVITE","total":"38"}],"count":61}

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/commit/941bbc6fbaa273bdc02f60ae91ffbdc461ef9cc7

check this patch

**Comment by ljubo2015** [comment]
Hello, 
This fix solved issue with sum but what is unsolved is bar for min and max values at bottom left:
![image](https://cloud.githubusercontent.com/assets/15197215/18581142/85dd96b6-7bff-11e6-9169-da71cc52724b.png)
Min should be: 38
Max should be: 1228
