### ISSUE TITLE
Kamilio crashing when receiving hep packets

### ISSUE THREAD

**Issue by iamninjabob** [sipcapture/homer#191]
I have installed the homer packages from the curl script on a Debian server and everything seems to be running with the exception of a full crash when kamailio receives any packets.

Below i have listed the SYSLOG. I currently have kamailio running in debug mode so there should be quite a bit of information.

A common message I keep seeing is 

> INFO: <core> [sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized

	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [parser/msg_parser.c:595]: parse_msg(): SIP Request:
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [parser/msg_parser.c:597]: parse_msg():  method:  <PUBLISH>
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [parser/msg_parser.c:599]: parse_msg():  uri:     <sip:Pi@192.168.55.6:9060>
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [parser/msg_parser.c:601]: parse_msg():  version: <SIP/2.0>
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [parser/parse_via.c:1254]: parse_via_param(): Found param type 232, <branch> = <z9hG4bK1717674992>; state=16
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [parser/parse_via.c:2642]: parse_via(): end of header reached, state=5
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [parser/msg_parser.c:486]: parse_headers(): Via found, flags=2
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [parser/msg_parser.c:488]: parse_headers(): this is the first via
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [receive.c:178]: receive_msg(): After parse_msg...
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [receive.c:221]: receive_msg(): preparing to run routing scripts...
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: htable [ht_var.c:90]: pv_set_ht_cell(): set value for $sht(a=>method::total)
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: htable [ht_var.c:90]: pv_set_ht_cell(): set value for $sht(a=>method::total)
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: htable [ht_var.c:90]: pv_set_ht_cell(): set value for $sht(a=>packet::count)
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: htable [ht_var.c:90]: pv_set_ht_cell(): set value for $sht(a=>packet::size)
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: htable [ht_var.c:90]: pv_set_ht_cell(): set value for $sht(a=>packet::count)
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: htable [ht_var.c:90]: pv_set_ht_cell(): set value for $sht(a=>packet::size)
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [parser/parse_addr_spec.c:894]: parse_addr_spec(): end of header reached, state=10
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [parser/msg_parser.c:171]: get_hdr_field(): <To> [28]; uri=[sip:Pi@192.168.55.6:9060]
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [parser/msg_parser.c:172]: get_hdr_field(): to body [<sip:Pi@192.168.55.6:9060>#015#012]
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/msg_parser.c:605]: parse_msg(): SIP Reply  (status):
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [parser/msg_parser.c:152]: get_hdr_field(): cseq <CSeq>: <1> <PUBLISH>
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/msg_parser.c:607]: parse_msg():  version: <SIP/2.0>
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/msg_parser.c:609]: parse_msg():  status:  <200>
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/msg_parser.c:611]: parse_msg():  reason:  <OK>
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/parse_hname2.c:192]: parse_hname2(): beginning of SIP-If-Match: yet=0x2d706973
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/parse_via.c:1254]: parse_via_param(): Found param type 234, <received> = <12.217.238.3>; state=6
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/parse_via.c:1254]: parse_via_param(): Found param type 232, <branch> = <z9hG4bK1717674992>; state=16
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/parse_via.c:2642]: parse_via(): end of header reached, state=5
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/msg_parser.c:486]: parse_headers(): Via found, flags=2
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/msg_parser.c:488]: parse_headers(): this is the first via
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [receive.c:178]: receive_msg(): After parse_msg...
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: htable [ht_var.c:90]: pv_set_ht_cell(): set value for $sht(a=>method::total)
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/parse_addr_spec.c:172]: parse_to_param(): DEBUG: add_param: tag=3683474597-43548
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/parse_addr_spec.c:894]: parse_addr_spec(): end of header reached, state=29
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/msg_parser.c:171]: get_hdr_field(): <To> [49]; uri=[sip:Pi@192.168.55.6:9060]
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/msg_parser.c:172]: get_hdr_field(): to body [<sip:Pi@192.168.55.6:9060>]
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/msg_parser.c:152]: get_hdr_field(): cseq <CSeq>: <1> <PUBLISH>
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: htable [ht_var.c:90]: pv_set_ht_cell(): set value for $sht(b=>200::1::PUBLISH::4114455551@172.30.76.20)
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: htable [ht_var.c:90]: pv_set_ht_cell(): set value for $sht(a=>method::all)
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: htable [ht_var.c:90]: pv_set_ht_cell(): set value for $sht(a=>method::all)
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: sipcapture [sipcapture.c:1562]: sip_capture(): CAPTURE DEBUG...
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/msg_parser.c:183]: get_hdr_field(): content_length=0
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/msg_parser.c:89]: get_hdr_field(): found end of header
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/parse_addr_spec.c:172]: parse_to_param(): DEBUG: add_param: tag=1382816950
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: <core> [parser/parse_addr_spec.c:894]: parse_addr_spec(): end of header reached, state=29
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: sipcapture [sipcapture.c:1859]: sip_capture(): src_ip: [198.17.84.55]
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: sipcapture [sipcapture.c:1860]: sip_capture(): dst_ip: [172.30.76.20]
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: sipcapture [sipcapture.c:1862]: sip_capture(): dst_port: [5062]
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: sipcapture [sipcapture.c:1863]: sip_capture(): src_port: [5060]
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: sipcapture [sipcapture.c:1507]: sip_capture_store(): insert into homer table [1]: [sip_capture_rest_20160914]
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: DEBUG: sipcapture [sipcapture.c:1510]: sip_capture_store(): storing info...
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: htable [ht_var.c:90]: pv_set_ht_cell(): set value for $sht(b=>PUBLISH::1::4114455551@172.30.76.20)
	Sep 14 11:29:08 HomerQA kernel: [ 4297.489091] kamailio[25350]: segfault at 22 ip 0000000000518494 sp 00007ffc72342d50 error 4 in kamailio[400000+3ad000]
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: htable [ht_var.c:90]: pv_set_ht_cell(): set value for $sht(a=>method::all)
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [parser/msg_parser.c:183]: get_hdr_field(): content_length=659
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: textops [textops.c:2630]: has_body_f(): content type is 196863
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [parser/msg_parser.c:89]: get_hdr_field(): found end of header
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: pv [pv_trans.c:549]: tr_eval_string(): i=0 j=1
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [re.c:436]: subst_run(): running. r=0
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25350]: DEBUG: <core> [re.c:457]: subst_run(): matched (0, 659): [VQIntervalReport: CallTerm#015#012LocalMetrics:#015#012Timestamps:START=2016-09-21T19:21:05Z STOP=2016-09-21T19:21:25Z#015#012SessionDesc:PT=0 PPS=50 PLC=3 SSUP=off#015#012CallID:39832428-3683474568-654603@S3S04.PROVIDER.com#015#012LocalAddr:IP=FAKE_IP_ADDRESS PORT=11796 SSRC=0x0e20033e#015#012RemoteAddr:IP=FAKE_IP_ADDRESS  PORT=49308 SSRC=0xbaa88379#015#012JitterBuffer:JBA=2 JBR=15 JBN=40 JBM=40 JBX=240#015#012PacketLoss:NLR=0.0 JDR=0.0#015#012BurstGapLoss:BLD=0.0 BD=0 GLD=0.0 GD=20090 GMIN=16#015#012Delay:RTD=0 ESD=97 SOWD=48 IAJ=0 MAJ=0#015#012Signal:SL=127 NL=-62 RERL=127#015#012QualityEst:RCQ=92 EXTRI=127 MOSLQ=4.1 MOSCQ=4.1#015#012DialogID:39832428-3683474568-654603@S3S04.PROVIDER.com;to-tag=2037376232;from-tag=3683474568-654608#015#012]
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25349]: ALERT: <core> [main.c:740]: handle_sigs(): child process 25350 exited by a signal 11
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25349]: ALERT: <core> [main.c:743]: handle_sigs(): core was not generated
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25349]: INFO: <core> [main.c:755]: handle_sigs(): terminating due to SIGCHLD
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25349]: DEBUG: <core> [main.c:757]: handle_sigs(): terminating due to SIGCHLD
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25355]: INFO: <core> [main.c:810]: sig_usr(): signal 15 received
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25362]: INFO: <core> [main.c:810]: sig_usr(): signal 15 received
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25353]: INFO: <core> [main.c:810]: sig_usr(): signal 15 received
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25365]: INFO: <core> [main.c:810]: sig_usr(): signal 15 received
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25356]: INFO: <core> [main.c:810]: sig_usr(): signal 15 received
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25361]: INFO: <core> [main.c:810]: sig_usr(): signal 15 received
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25358]: INFO: <core> [main.c:810]: sig_usr(): signal 15 received
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25351]: INFO: <core> [main.c:810]: sig_usr(): signal 15 received
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25349]: DEBUG: tm [t_funcs.c:86]: tm_shutdown(): DEBUG: tm_shutdown : start
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25349]: DEBUG: tm [t_funcs.c:89]: tm_shutdown(): DEBUG: tm_shutdown : emptying hash table
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25349]: DEBUG: tm [t_funcs.c:91]: tm_shutdown(): DEBUG: tm_shutdown : removing semaphores
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25349]: DEBUG: tm [t_funcs.c:93]: tm_shutdown(): DEBUG: tm_shutdown : destroying tmcb lists
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25349]: DEBUG: tm [t_funcs.c:96]: tm_shutdown(): DEBUG: tm_shutdown : done
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25349]: INFO: <core> [sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25349]: DEBUG: <core> [mem/shm.c:174]: shm_core_lock_destroy(): destroying the shared memory lock
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25349]: DEBUG: <core> [mem/shm.c:266]: shm_destroy_manager(): destroying memory manager: f_malloc
	Sep 14 11:29:08 HomerQA /usr/sbin/kamailio[25349]: DEBUG: <core> [mem/pkg.c:89]: pkg_destroy_manager(): destroying memory manager: f_malloc
	Sep 14 11:29:08 HomerQA systemd[1]: kamailio.service: main process exited, code=exited,             status=1/FAILURE
	Sep 14 11:29:08 HomerQA systemd[1]: Unit kamailio.service entered failed state.

**Comment by adubovikov** [comment]
please use this config:

https://github.com/sipcapture/homer-api/blob/master/examples/sipcapture/sipcapture.kamailio

**Comment by iamninjabob** [comment]
I have done as recomdened but kamailio fails to start stating that there are 24 errors in the config file.

 Sep 22 09:57:59 HomerQA kamailio: ERROR: <core> [modparam.c:152]: set_mod_param_regex(): No module matching <sipcapture> found
 Sep 22 09:57:59 HomerQA kamailio: : <core> [cfg.y:3371]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 100, column 50: Can't set module par$
 Sep 22 09:57:59 HomerQA kamailio: ERROR: <core> [pvapi.c:828]: pv_parse_spec2(): error searching pvar "sht"
 Sep 22 09:57:59 HomerQA kamailio: ERROR: <core> [pvapi.c:1032]: pv_parse_spec2(): wrong char [a/97] in [$sht(a=>method::total)] at [5 (5)]
 Sep 22 09:57:59 HomerQA kamailio: : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 115, column 5-26: Can't get from cac$
 Sep 22 09:57:59 HomerQA kamailio: INFO: <core> [sctp_core.c:53]: sctp_core_destroy(): SCTP API not initialized
 Sep 22 09:57:59 HomerQA systemd[1]: kamailio.service: control process exited, code=exited status=255
 Sep 22 09:57:59 HomerQA systemd[1]: Failed to start Kamailio (OpenSER) - the Open Source SIP Server.
 Sep 22 09:57:59 HomerQA systemd[1]: Unit kamailio.service entered failed state.
 Sep 22 09:57:59 HomerQA kamailio[28254]: ERROR: bad config file (24 errors)

**Comment by adubovikov** [comment]
can u please provide output:

kamailio -c

did you adapt the config  or just replaced ?

**Comment by iamninjabob** [comment]
I replaced the file totally from a fresh git clone of the homer-api file tree.

root@HomerQA:/# kamailio -c
 0(28397) ERROR: <core> [sr_module.c:571]: load_module(): could not find module <pv> in </usr/lib64/kamailio/modules>
 0(28397) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 54, column 12-18: failed to load module
 0(28397) ERROR: <core> [sr_module.c:571]: load_module(): could not find module <db_mysql> in </usr/lib64/kamailio/modules>
 0(28397) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 55, column 12-24: failed to load module
 0(28397) ERROR: <core> [sr_module.c:571]: load_module(): could not find module <sipcapture> in </usr/lib64/kamailio/modules>
 0(28397) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 56, column 12-26: failed to load module
 0(28397) ERROR: <core> [sr_module.c:571]: load_module(): could not find module <textops> in </usr/lib64/kamailio/modules>
 0(28397) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 57, column 12-23: failed to load module
 0(28397) ERROR: <core> [sr_module.c:571]: load_module(): could not find module <rtimer> in </usr/lib64/kamailio/modules>
 0(28397) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 58, column 12-22: failed to load module
 0(28397) ERROR: <core> [sr_module.c:571]: load_module(): could not find module <xlog> in </usr/lib64/kamailio/modules>
 0(28397) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 59, column 12-20: failed to load module
 0(28397) ERROR: <core> [sr_module.c:571]: load_module(): could not find module <sqlops> in </usr/lib64/kamailio/modules>
 0(28397) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 60, column 12-22: failed to load module
 0(28397) ERROR: <core> [sr_module.c:571]: load_module(): could not find module <htable> in </usr/lib64/kamailio/modules>
 0(28397) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 61, column 12-22: failed to load module
 0(28397) ERROR: <core> [sr_module.c:571]: load_module(): could not find module <tm> in </usr/lib64/kamailio/modules>
 0(28397) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 62, column 12-18: failed to load module
 0(28397) ERROR: <core> [sr_module.c:571]: load_module(): could not find module <sl> in </usr/lib64/kamailio/modules>
 0(28397) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 63, column 12-18: failed to load module
 0(28397) ERROR: <core> [sr_module.c:571]: load_module(): could not find module <siputils> in </usr/lib64/kamailio/modules>
 0(28397) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 64, column 12-24: failed to load module
 0(28397) ERROR: <core> [sr_module.c:571]: load_module(): could not find module <exec> in </usr/lib64/kamailio/modules>
 0(28397) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 65, column 12-20: failed to load module
 0(28397) ERROR: <core> [modparam.c:152]: set_mod_param_regex(): No module matching <htable> found
 0(28397) : <core> [cfg.y:3371]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 78, column 56: Can't set module parameter
 0(28397) ERROR: <core> [modparam.c:152]: set_mod_param_regex(): No module matching <htable> found
 0(28397) : <core> [cfg.y:3371]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 79, column 55: Can't set module parameter
 0(28397) ERROR: <core> [modparam.c:152]: set_mod_param_regex(): No module matching <htable> found
 0(28397) : <core> [cfg.y:3371]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 81, column 55: Can't set module parameter
 0(28397) ERROR: <core> [modparam.c:152]: set_mod_param_regex(): No module matching <rtimer> found
 0(28397) : <core> [cfg.y:3371]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 88, column 58: Can't set module parameter
 0(28397) ERROR: <core> [modparam.c:152]: set_mod_param_regex(): No module matching <rtimer> found
 0(28397) : <core> [cfg.y:3371]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 89, column 56: Can't set module parameter
 0(28397) ERROR: <core> [modparam.c:152]: set_mod_param_regex(): No module matching <sqlops> found
 0(28397) : <core> [cfg.y:3371]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 91, column 99: Can't set module parameter
 0(28397) ERROR: <core> [modparam.c:152]: set_mod_param_regex(): No module matching <sipcapture> found
 0(28397) : <core> [cfg.y:3371]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 96, column 96: Can't set module parameter
 0(28397) ERROR: <core> [modparam.c:152]: set_mod_param_regex(): No module matching <sipcapture> found
 0(28397) : <core> [cfg.y:3371]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 97, column 39: Can't set module parameter
 0(28397) ERROR: <core> [modparam.c:152]: set_mod_param_regex(): No module matching <sipcapture> found
 0(28397) : <core> [cfg.y:3371]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 98, column 43: Can't set module parameter
 0(28397) ERROR: <core> [modparam.c:152]: set_mod_param_regex(): No module matching <sipcapture> found
 0(28397) : <core> [cfg.y:3371]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 99, column 43: Can't set module parameter
 0(28397) ERROR: <core> [modparam.c:152]: set_mod_param_regex(): No module matching <sipcapture> found
 0(28397) : <core> [cfg.y:3371]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 100, column 50: Can't set module parameter
 0(28397) ERROR: <core> [pvapi.c:828]: pv_parse_spec2(): error searching pvar "sht"
 0(28397) ERROR: <core> [pvapi.c:1032]: pv_parse_spec2(): wrong char [a/97] in [$sht(a=>method::total)] at [5 (5)]
 0(28397) : <core> [cfg.y:3368]: yyerror_at(): parse error in config file /etc/kamailio/kamailio.cfg, line 115, column 5-26: Can't get from cache: $sht(a=>method::total)
ERROR: bad config file (24 errors)

**Comment by adubovikov** [comment]
Kamailio couldn't find modules, please set the mpath param in your config before loadmodule

i.e.
mpath="/usr/local/lib64/kamailio/modules/"

**Comment by iamninjabob** [comment]
That did it. 

Thanks so much!
