### ISSUE TITLE
Login Issues - New Install

### ISSUE THREAD

**Issue by kris1351** [sipcapture/homer#193]
Having issues with the interface allowing the default logins to install. I have verified in the database that the admin/test1234 exists like that, but anytime you attempt to login you get:

**Email and password combination not recognised**

I am not seeing any failures in logs is the frustrating part. I can see sipcaptures in the database through phpMyAdmin so the database and Homer system are working properly in that aspect. Any ideas?

**Comment by kris1351** [comment]
The users exist here, tried with and without the test.com like old revisions required.

![screen shot 2016-09-28 at 12 08 09 pm](https://cloud.githubusercontent.com/assets/22503877/18924032/41fe9c96-8574-11e6-8639-6655aa17f0ec.png)

**Comment by giavac** [comment]
I would `ngrep` what happens over ports 80 and 3306 (which is most probably the one in use for mysql). Often the error message from mysql helps.

Also try opening the Developer Tools in your browser and watch the Console output.

**Comment by kris1351** [comment]
No errors in the mysql log.

2016-09-28T16:57:48.396413Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
2016-09-28T16:57:48.396740Z 0 [Warning] CA certificate ca.pem is self signed.
2016-09-28T16:57:48.399383Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
2016-09-28T16:57:48.399429Z 0 [Note] IPv6 is available.
2016-09-28T16:57:48.399463Z 0 [Note]   - '::' resolves to '::';
2016-09-28T16:57:48.399490Z 0 [Note] Server socket created on IP: '::'.
2016-09-28T16:57:48.403906Z 0 [Note] InnoDB: Buffer pool(s) load completed at 160928 16:57:48
2016-09-28T16:57:48.412922Z 0 [Note] Event Scheduler: Loaded 0 events
2016-09-28T16:57:48.413337Z 0 [Note] /usr/sbin/mysqld: ready for connections.
Version: '5.7.15'  socket: '/var/lib/mysql/mysql.sock'  port: 3306  MySQL Community Server (GPL)

**Comment by kris1351** [comment]
It is a CentOS 7 install that is default with everything from the homer_installer.

**Comment by kris1351** [comment]
This is a default CentOS 7 install with your installer script, no 
changes. The port 80/443/3306 is running, but nothing shows in the ngrep 
when I check for 3306.

-bash: !nc: event not found
[root@newhomer homer]# !ng
ngrep -i 'select' port 3306
interface: eth0 (67.209.158.0/255.255.255.0)
filter: ( port 3306 ) and (ip or ip6)
match: select

**Comment by giavac** [comment]
Try looking on the local interface too, e.g. with:

```ngrep -d any -lqtW byline port 3306```

and also

```ngrep -d any -lqtW byline port 3306 or port 80```

**Comment by kris1351** [comment]
[root@newhomer homer]# ngrep -d any -lqtW byline port 3306 or port 80 or 
port 443
interface: any
filter: ( port 3306 or port 80 or port 443 ) and (ip or ip6)

T 2016/09/28 18:10:42.644069 xxx.xxx.xxx.93:58059 -> xxx.xxx.xxx.200:443 [S]
................

T 2016/09/28 18:10:42.644118 xxx.xxx.xxx.200:443 -> xxx.xxx.xxx.93:58059 
[AS]
................

T 2016/09/28 18:10:42.654062 xxx.xxx.xxx.93:58059 -> xxx.xxx.xxx.200:443 [A]
................

T 2016/09/28 18:10:42.654460 xxx.xxx.xxx.93:58059 -> xxx.xxx.xxx.200:443 
[AP]
...........*....L.h0.,...~;...)b.}......Nd. 
)..b#..'....W.......ra.g..*..\vg.".+./.,.0.............
......./.5.
..............#..xi..a..I....%.U..UP.I..4..mu. ...5|.!'7....
s
.....}..~..Ulm4....p.._....0..o.1......f`..XS~....'(.,f.ps.";..(..8..;....@M'9....km..\.?r=..Z`h.@.x...,s.J;..x#..k#...&.P....K..s..........t....8..........................................h2.http/1.1uP.........
.............u.....................................................................................................................................

T 2016/09/28 18:10:42.654491 xxx.xxx.xxx.200:443 -> xxx.xxx.xxx.93:58059 [A]
................

T 2016/09/28 18:10:42.661421 xxx.xxx.xxx.200:443 -> xxx.xxx.xxx.93:58059 
[AP]
....=...9..W...&........
..#........e......../.................#.................0...0..........P#0...*.H........0..1.0...U....--1.0...U....SomeState1.0...U....SomeCity1.0...U.
..SomeOrganization1.0...U....SomeOrganizationalUnit1.0...U....newhomer1.0...*.H........root@newhomer0...160928164335Z..170928164335Z0..1.0...U....--1.0...U....SomeState1.0...U....SomeCity1.0...U.
..SomeOrganization1.0...U....SomeOrganizationalUnit1.0...U....newhomer1.0...*.H........root@newhomer0.."0...*.H.............0..
.......v...e.&....n.....[..N..{......!z..
.....#%..?.3.^..=.'.>k..3lq..t.....p..X.6..w......ti..
d..k......Jqi..&....".._.'...{k.y..".GAm}...X0...]....W...t..vF..ik.d..M|......~.69r#..6{..<...5.ie..K%....J`.^......X.!..4.6..l..(0.1.....>...`{..x@....+.0...l.{LE.......0.0...U....0.0...U........0...*.H..............eG./.....\.b`......2.....I-...bR.L%...<=b.ps.....<.<..0z.[..IO..[
....,.pM=
g=s...$..k.xz...7.....Ej?".T2m..D~..Rf..h....-. 
...Q..DL8...*\....E4......z....#cK.*X-..k..
....g.r.u.'.+.........e.......q9......6...Y
.o_.c..0
.$..V.WK..PuU...PFx.,o[.'..'.'$,......M...I...A."....D..;r&^..a...uU9..Z.)^#....p..=....7....'&....i.C..#.s...Rw....r.-..1............;Qx|nj...`...)...@..,...U..].......@X..bTkV...n...a.Th.|...WR.b}..|./......0n+....'B.3.$...G..+...,r.../C.....p..j'..N...+{..`;..........(.{.6.....,..H.RZ.z....t....@@.9.....?m.H.bY.......KHz...w6P.....=.o.7<uP0.#....7.d...a..m..3}..p.............................

T 2016/09/28 18:10:42.671678 xxx.xxx.xxx.93:58059 -> xxx.xxx.xxx.200:443 [A]
................

T 2016/09/28 18:10:42.674196 xxx.xxx.xxx.93:58059 -> xxx.xxx.xxx.200:443 
[AP]
....F...BA..s"..&...{7.e.u=.\....
......=....Lqf7...8...,..CwJ=..\...#Ye-............(.........:..7#.0..I.0>....v.i......,^N.r................

T 2016/09/28 18:10:42.675333 xxx.xxx.xxx.200:443 -> xxx.xxx.xxx.93:58059 
[AP]
............,..xi..a..I....%.U.[.\..-V ..f..4o...mf?........%W. 
-...J....Pt;...l.@.9.3.....1X.h.c......F:J........c..8......p"]..1/..u..&m.......w.. 
..V..S.*..u............x+.9.....G.....ph.........c,I94.^............(..nrfJ.x..P...!......../y..f!;_.x....#&.................

T 2016/09/28 18:10:42.686646 xxx.xxx.xxx.93:58059 -> xxx.xxx.xxx.200:443 [A]
................

T 2016/09/28 18:10:42.689034 xxx.xxx.xxx.93:58060 -> xxx.xxx.xxx.200:443 [S]
................

T 2016/09/28 18:10:42.689048 xxx.xxx.xxx.200:443 -> xxx.xxx.xxx.93:58060 
[AS]
................

T 2016/09/28 18:10:42.689080 xxx.xxx.xxx.93:58059 -> xxx.xxx.xxx.200:443 
[AF]
................

T 2016/09/28 18:10:42.689197 xxx.xxx.xxx.200:443 -> xxx.xxx.xxx.93:58059 
[AF]
................

T 2016/09/28 18:10:42.698973 xxx.xxx.xxx.93:58060 -> xxx.xxx.xxx.200:443 [A]
................

T 2016/09/28 18:10:42.699396 xxx.xxx.xxx.93:58060 -> xxx.xxx.xxx.200:443 
[AP]
............pg.;..x..3.....\51..cfe../..m.. 
)..b#..'....W.......ra.g..*..\vg.".+./.,.0.............
......./.5.
..............#..xi..a..I....%.U..UP.I..4..mu. ...5|.!'7....
s
.....}..~..Ulm4....p.._....0..o.1......f`..XS~....'(.,f.ps.";..(..8..;....@M'9....km..\.?r=..Z`h.@.x...,s.J;..x#..k#...&.P....K..s..........t....8..........................................h2.http/1.1uP.........
.............u.....................................................................................................................................

T 2016/09/28 18:10:42.699415 xxx.xxx.xxx.200:443 -> xxx.xxx.xxx.93:58060 [A]
................

T 2016/09/28 18:10:42.701749 xxx.xxx.xxx.93:58059 -> xxx.xxx.xxx.200:443 [A]
................

T 2016/09/28 18:10:42.708262 xxx.xxx.xxx.200:443 -> xxx.xxx.xxx.93:58060 
[AP]
....=...9..W.......+d.ZO.a...9.\.&..rm.3...../.................#.................0...0..........P#0...*.H........0..1.0...U....--1.0...U....SomeState1.0...U....SomeCity1.0...U.
..SomeOrganization1.0...U....SomeOrganizationalUnit1.0...U....newhomer1.0...*.H........root@newhomer0...160928164335Z..170928164335Z0..1.0...U....--1.0...U....SomeState1.0...U....SomeCity1.0...U.
..SomeOrganization1.0...U....SomeOrganizationalUnit1.0...U....newhomer1.0...*.H........root@newhomer0.."0...*.H.............0..
.......v...e.&....n.....[..N..{......!z..
.....#%..?.3.^..=.'.>k..3lq..t.....p..X.6..w......ti..
d..k......Jqi..&....".._.'...{k.y..".GAm}...X0...]....W...t..vF..ik.d..M|......~.69r#..6{..<...5.ie..K%....J`.^......X.!..4.6..l..(0.1.....>...`{..x@....+.0...l.{LE.......0.0...U....0.0...U........0...*.H..............eG./.....\.b`......2.....I-...bR.L%...<=b.ps.....<.<..0z.[..IO..[
....,.pM=
g=s...$..k.xz...7.....Ej?".T2m..D~..Rf..h....-. 
...Q..DL8...*\....E4......z....#cK.*X-..k..
....g.r.u.'.+.........e.......q9......6...Y
.o_.c..0
.$..V.WK..PuU...PFx.,o[.'..'.'$,......M...I...A.....V=3.yR...}M.6*.....a.K.b{.(E...
...b...........=..a.;.....BE....w@z.....8.D.t).e......;....xh..M.b%.d. 
.'.m!...P.# ......
..L...e..H..6i.o.......F8....^....u~6.>E....}Olv......PP.>.x.....N..vT../F.6.i;
HZ....4~....sp.y6...,L...-..l|~.e.i......f.Z..or6o.#@....%..N.]G...A..Y!......c.!E.6.^...NSlml..Y..... 
'..#..M..*....b.........................

T 2016/09/28 18:10:42.716534 xxx.xxx.xxx.93:58060 -> xxx.xxx.xxx.200:443 [A]
................

T 2016/09/28 18:10:42.716600 xxx.xxx.xxx.93:58060 -> xxx.xxx.xxx.200:443 
[AP]
....F...BA......zi.D........&.g......N.f..P...}.Sn....<..|j$...*N...O^...............(.........a...!s..,..Y?...*.KXW....Y.....................

T 2016/09/28 18:10:42.718002 xxx.xxx.xxx.200:443 -> xxx.xxx.xxx.93:58060 
[AP]
............,..xi..a..I....%.U.\..Nf.(
.)*....|.......|%..a5_.zHr...9....[...........[...._.....?..Dm..~~.;...]P....gh...&1\........dk..F.a...Q...L.".-\.&-.......9..iJg..h].#.... 
KK.Ax].r@[.fi@.......%..K7t...........(...MT.K..`.|PE.....T..r..8......~+N.Vo..................

T 2016/09/28 18:10:42.728932 xxx.xxx.xxx.93:58060 -> xxx.xxx.xxx.200:443 [A]
................

T 2016/09/28 18:10:42.729480 xxx.xxx.xxx.93:58060 -> xxx.xxx.xxx.200:443 
[AP]
....<........`0Q.N.$$..K.&.N....|..P.....i./............JF..!.r....6..Uw...g.3\.........(.h+.....RX..K....q..?c.\lN..sf..}.....t.< 
..J...I..JBc?`tg.L...z..f>_...O...._..c....X.5..zY6..).....5l..UN 
.'.K.z8..2.."P!y....z8.....d...e....y.....P...8t0"....`.6...1.z$~...s..F..H....l5.\..;.}B(@...y....P.. 

..{..<"...\....N.l...%.B..qu_.......u......z\.......Ka...5..h.......I..sR....@....p.`D..h.c..}A...(q..n..Z"4.....k4'3"........%....:&.s.m.B.+).L.Te.1 
'.O.....Y..x...,x.v..uHf.|....2.f.^b1....7,.3#.W.'..k.^......?......Oj....m......>....8.....;.=.#.."<..........".H..G"27.d.$..................

T 2016/09/28 18:10:42.730109 xxx.xxx.xxx.200:443 -> xxx.xxx.xxx.93:58060 
[AP]
........MT.K.?)=.]z...`mD..@..6y......G.s..6..n..$TR%(
...).M....5Y.....-.s.....E.].-Z.^z.8.......k.d/.;}J..=5du......0^...u~... 
..#\.!)...a..jgo.EY..u....+.+(,......h...C..T0.L$.*j:....
.C.....%...2..3..y.[.#/[..h......&\..c#....bq..F.I].zu...L....F...e...A..!X......_..Z............MT.K.......z~.4.....G...*.^]6.N.p.../...._.3..;mh....%.k....?&...@W.U..9........z..
)....j'..M..mn...\.A......BJm..[..p.L....PcP..b...Zh.,......../..Wp8KbL.t.D.m.V.K.IG.9.~.......5-....oh..Du..?....GG.74...'.IV#.{.=.M.[N...Ka....v.{I................

T 2016/09/28 18:10:42.741423 xxx.xxx.xxx.93:58060 -> xxx.xxx.xxx.200:443 [A]
................
^C[root@newhomer homer]#

**Comment by giavac** [comment]
Please look at the Console output.
Also check PHP logs for errors.

**Comment by Joonake** [comment]
Check that you have php5-mysql installed and enabled. I remember having this issue when it was missing.

**Comment by adubovikov** [comment]
can you please check if your api works ?

/api/v1/test

second, please use: admin/test123 - not test1234

**Comment by kris1351** [comment]
That file does not exist in the latest install versions, do you have a 
copy I can download? Also, the password is test1234 I decrypted the hash 
to verify. I have tried the admin and noc users with their specified 
passwords with no luck

otal 112
-rw-r--r--  1 root root  4935 Sep 28 16:43 preferences_example.php
-rw-r--r--  1 root root  9857 Sep 28 16:43 index.php
-rw-r--r--  1 root root   142 Sep 28 16:43 .htaccess
drwxr-xr-x  3 root root  4096 Sep 28 16:43 Database
-rw-r--r--  1 root root  7338 Sep 28 16:43 autoload.php
drwxr-xr-x 14 root root  4096 Sep 28 16:43 ..
drwxr-xr-x  2 root root  4096 Sep 28 16:43 Statistic
drwxr-xr-x  2 root root  4096 Sep 28 16:43 RestService
-rw-r--r--  1 root root 34520 Sep 28 16:43 COPYING
-rw-r--r--  1 root root   967 Sep 28 16:43 configuration_example.php
drwxr-xr-x  2 root root  4096 Sep 28 16:43 Authentication
drwxr-xr-x  2 root root  4096 Sep 28 16:43 RestApi
drwxrwxrwx  2 root root  4096 Sep 28 16:44 tmp
-rw-r--r--  1 root root  3225 Sep 28 16:57 preferences.php
-rwxrwxr-x  1 root root   774 Sep 28 16:57 configuration.php
drwxr-xr-x  8 root root  4096 Sep 28 16:57 .
[root@newhomer api]# pwd
/var/www/html/api

**Comment by kris1351** [comment]
angular.js:10765 POST https://xxx.xxx.xxx.200/api/v1/session 404 (Not 
Found)(anonymous function) @ angular.js:10765r @ angular.js:10558g @ 
angular.js:10268(anonymous function) @ angular.js:14792$eval @ 
angular.js:16052$digest @ angular.js:15870$apply @ 
angular.js:16160(anonymous function) @ angular.js:23618dispatch @ 
jquery.min.js:5y.handle @ jquery.min.js:5
authentication.js:52 Object {data: "<!DOCTYPE HTML PUBLIC "-//IETF//DTD 
HTML 2.0//EN">…was not found on this server.</p>↵</body></html>↵", 
status: 404, config: Object, statusText: "Not Found"}

**Comment by adubovikov** [comment]
you didn't configure mod_rewrite. Please follow our wiki

**Comment by kris1351** [comment]
I added the AllowOveride All as it states and checked it in apache that 
the module is there. Apache owns the /var/www since thats what it is 
running with.


angular.js:10765 GET https://xxx.xxx.xxx.200/api/v1/session 403 
(Forbidden)(anonymous function) @ angular.js:10765r @ angular.js:10558g 
@ angular.js:10268(anonymous function) @ angular.js:14792$eval @ 
angular.js:16052$digest @ angular.js:15870$apply @ 
angular.js:16160(anonymous function) @ angular.js:1679e @ 
angular.js:4523c @ angular.js:1677yc @ angular.js:1697Zd @ 
angular.js:1591(anonymous function) @ angular.js:29013l @ 
jquery.min.js:4fireWith @ jquery.min.js:4ready @ jquery.min.js:4S @ 
jquery.min.js:4
module.auth.run.js:43 Unknown Username / Password combination
module.auth.run.js:44 bad result

**Comment by kris1351** [comment]
This part is working now:


  Your api call works! Well done!

**Comment by kris1351** [comment]
admin/test123

admin/test1234

noc/123test

noc/1234test

All fail still, the MD5 hash shown in phpMyAdmin shows it is 
admin/test1234 and noc/1234test.


angular.js:10765 POST https://xxx.xxx.xxx.200/api/v1/session 404 (Not 
Found)(anonymous function) @ angular.js:10765r @ angular.js:10558g @ 
angular.js:10268(anonymous function) @ angular.js:14792$eval @ 
angular.js:16052$digest @ angular.js:15870$apply @ 
angular.js:16160(anonymous function) @ angular.js:23618dispatch @ 
jquery.min.js:5y.handle @ jquery.min.js:5
authentication.js:52 Object {data: Object, status: 404, config: Object, 
statusText: "Not Found"}config: Objectdata: Objectheaders: Objectmethod: 
"POST"paramSerializer: (a)transformRequest: Array[1]transformResponse: 
Array[1]url: "api/v1/session"__proto__: Objectdata: Objectauth: 
"false"data: Array[0]message: "bad password or username"sid: 
"nbf5aqb8v7cbsfih339inaqkf4"status: 404__proto__: Objectheaders: 
(d)arguments: (...)caller: (...)length: 1name: ""prototype: 
Object__proto__: ()<function scope>status: 404statusText: "Not 
Found"__proto__: Object__defineGetter__: 
__defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: 
__lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: 
Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: 
isPrototypeOf()propertyIsEnumerable: 
propertyIsEnumerable()toLocaleString: toLocaleString()toString: 
toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: 
__proto__()
loginCtrl.js:27 Submiting user info.

**Comment by adubovikov** [comment]
why MD5 ? it should be PASSWORD function

**Comment by kris1351** [comment]
Sorry typed that wrong. The hash decrypter shows it as a MySQL4.1+

**Comment by kris1351** [comment]
angular.js:10765 POST https://xxx.xxx.xxx.200/api/v1/session 404 (Not 
Found)(anonymous function) @ angular.js:10765r @ angular.js:10558g @ 
angular.js:10268(anonymous function) @ angular.js:14792$eval @ 
angular.js:16052$digest @ angular.js:15870$apply @ 
angular.js:16160(anonymous function) @ angular.js:23618dispatch @ 
jquery.min.js:5y.handle @ jquery.min.js:5
authentication.js:52 Object {data: Object, status: 404, config: Object, 
statusText: "Not Found"}config: Objectdata: Objectheaders: Objectmethod: 
"POST"paramSerializer: (a)transformRequest: Array[1]transformResponse: 
Array[1]url: "api/v1/session"__proto__: Objectdata: Objectauth: 
"false"data: Array[0]message: "bad password or username"sid: 
"nbf5aqb8v7cbsfih339inaqkf4"status: 404__proto__: Objectheaders: 
(d)arguments: (...)caller: (...)length: 1name: ""prototype: 
Object__proto__: ()<function scope>status: 404statusText: "Not 
Found"__proto__: Object__defineGetter__: 
__defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: 
__lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: 
Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: 
isPrototypeOf()propertyIsEnumerable: 
propertyIsEnumerable()toLocaleString: toLocaleString()toString: 
toString()valueOf: valueOf()get __proto__: __proto__()set __proto__: 
__proto__()

**Comment by kris1351** [comment]
This is still appearing as forbidden.


https://xxx.xx.xxx.200/api/v1/session 403 (Forbidden)

**Comment by kris1351** [comment]
/api/v1/session returns this, what is it calling that it would be forbidden?

{
     "sid": "nbf5aqb8v7cbsfih339inaqkf4",
     "auth": "false",
     "status": 403,
     "message": "wrong session",
     "data": [
         
     ]
}

**Comment by kris1351** [comment]
Ok ran your curl to check the password and both admin/test123 and 
admin/test1234 say bad passwords.


[root@newhomer html]# curl -v --cookie 
"HOMERSESSID=tcuass65ejl2lifoopuuurpmq7; path=/" -X POST -H 
"Content-Type: application/json" -d 
'{"username":"admin","password":"test1234”}’ \
http://localhost/api/v1/session^C

[root@newhomer html]# curl -v --cookie 
"HOMERSESSID=tcuass65ejl2lifoopuuurpmq7; path=/" -X POST -H 
"Content-Type: application/json" \
 > -d '{"username":"admin","password":"test1234"}' \
 > http://localhost/api/v1/session
* About to connect() to localhost port 80 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 80 (#0)
 > POST /api/v1/session HTTP/1.1
 > User-Agent: curl/7.29.0
 > Host: localhost
 > Accept: */*
 > Cookie: HOMERSESSID=tcuass65ejl2lifoopuuurpmq7; path=/
 > Content-Type: application/json
 > Content-Length: 42
 >
* upload completely sent off: 42 out of 42 bytes
* HTTP 1.0, assume close after body
< HTTP/1.0 404 Not Found
< Date: Wed, 28 Sep 2016 21:37:14 GMT
< Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.4.16
< X-Powered-By: PHP/5.4.16
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, 
pre-check=0
< Pragma: no-cache
< Content-Length: 156
< Connection: close
< Content-Type: application/json; charset=utf-8
<
{
     "sid": "tcuass65ejl2lifoopuuurpmq7",
     "auth": "false",
     "status": 404,
     "message": "bad password or username",
     "data": [

     ]
* Closing connection 0
}[root@newhomer html]#

**Comment by kris1351** [comment]
Well, I didn't think I was going crazy.....It appears the issue is only 
present in Chrome which is what I use mostly. Firefox and Safari are 
working as they should so we will just use those. Is this a known issue?

**Comment by adubovikov** [comment]
No, this is not known issue,
Please update homer-ui and homer-api to the last version and check again

**Comment by kris1351** [comment]
This is a brand new install so it is the very latest version.

**Comment by itrstar** [comment]
Hi, I had same probem. Authorization became broken when I changed ip address, rollback setup ip address fixed the problem.

**Comment by adubovikov** [comment]
If you changed the IP address, maybe you have to change also mysql listening port, apache etc... ?

**Comment by itrstar** [comment]
Nothing more was changed. Reboot machine comeback the problem. More precisely after reboot mysql. Here what I got:
`
[root@homer ~]# curl -X POST -d '{"username":"admin","password":"test1234"}' http://localhost/api/v1/session --header "Content-Type:application/json"
{
    "status": 200,
    "sid": "ooovanau8nt9jsfld0dfvia9s5",
    "auth": "true",
    "message": "ok",
    "data": {
        "uid": "1",
        "username": "admin",
        "gid": "10",
        "grp": "users,admins",
        "firstname": "Admin",
        "lastname": "Admin",
        "email": "admin@test.com",
        "lastvisit": "2016-10-04 11:41:28"
    }
}

[root@homer ~]# service mysqld stop
Redirecting to /bin/systemctl stop  mysqld.service

[root@homer ~]# curl -X POST -d '{"username":"admin","password":"test1234"}' http://localhost/api/v1/session --header "Content-Type:application/json"
{
    "status": 500,
    "error": "PDOException",
    "message": "SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '\/var\/lib\/mysql\/mysql.sock' (2)"
}

[root@homer ~]#service mysqld start
Redirecting to /bin/systemctl start  mysqld.service

[root@homer ~]# curl -X POST -d '{"username":"admin","password":"test1234"}' http://localhost/api/v1/session --header "Content-Type:application/json"
{
    "sid": "c9i7n9ojgjnhrcr4bnmkotiqr4",
    "auth": "false",
    "status": 404,
    "message": "bad password or username",
    "data": [
        
    ]
}
`

Installation on clear centos (CentOS Linux release 7.2.1511 (Core)) with epel repository, homer from autoinstall script.

**Comment by adubovikov** [comment]
maybe because password should be "test123" ?

https://github.com/sipcapture/homer-api/blob/master/sql/schema_configuration.sql#L159

**Comment by itrstar** [comment]
Here is password hash from database and it is 'test1234' (checked with online decriptor):
3d3b92f242033365ae5bc6a8e6fc3e1679f4140a MySQL4.1/MySQL5 : test1234
Besides first time, before mysqld restart, I have correct response

**Comment by adubovikov** [comment]
so,  one more time:
1. all works good.
2. you do mysql restart and nothing doesn't work ?
3. you reboot the system and after all works as expected ?

**Comment by itrstar** [comment]
Sorry for my bad explaining.
1. all works good.
2. I do mysql restart and authorization broke. that's it.
And that I found:
After reboot mysql, mysql config validate_password_policy=LOW became 'MEDIUM' again. Аnd query 'SELECT PASSWORD("test1234")' dropping . If I set it again to LOW or set more strong password, all works fine. So solution is add to my.cnf config  validate_password_policy=LOW or set more strong password while install Homer. THX.

**Comment by gedia** [comment]
To anyone else having login issues, especially with manual install, it's worth checking the following:

a) You might have stumbled into this: http://stackoverflow.com/questions/1412339/cannot-log-in-with-created-user-in-mysql

b) You're using the mysqli driver for php. In my case, I have had to enable legacy mysql

**Comment by gedia** [comment]
UPDATE: When using homer-api from master instead of homer-api-5.0.6, I also had to disable PHP notices. Otherwise, login would fail with no obvious reason when checking mysql logs...

**Comment by lmangani** [comment]
Thanks for the update @kris1351 

Password complexity enforcement is something we'd rather leave to the user - we should probably switch to a proper generator of strong passwords for the installer and leave default passwords behind.

The PHP Notices condition is documented in our FAQ but I will doublecheck to make sure its in the installers too.
