### ISSUE TITLE
No QoS stats displayed on homer 5.0.5

### ISSUE THREAD

**Issue by iamninjabob** [sipcapture/homer#194]
I have a homer 5.0.5 server up and running, but I see no information for QoS from RTCP-XR.

When doing a select \* from report_capture it shows that captagent is sending the PUBLISH, RTCP-XR, and that Kamailio is receiving it and putting it into MYSQL. Am I missing a step on how to get the Homer dashboard to show these call stats?

**Comment by iamninjabob** [comment]
dump from MYSQL in report_capture


VQIntervalReport: CallTerm
LocalMetrics:
Timestamps:START=2016-09-23T14:49:51Z STOP=2016-09-23T15:31:51Z
SessionDesc:PT=0 PPS=50 PLC=3 SSUP=off
CallID:43483408-3683631093-416116@S3S04.genband.com
LocalAddr:IP=172.16.0.4 PORT=11790 SSRC=0x24271b8b
RemoteAddr:IP=198.17.84.54 PORT=45748 SSRC=0x00000000
JitterBuffer:JBA=2 JBR=15 JBN=40 JBM=40 JBX=240
PacketLoss:NLR=0.0 JDR=0.0
BurstGapLoss:BLD=0.0 BD=0 GLD=0.0 GD=65535 GMIN=16
Delay:RTD=0 ESD=97 SOWD=48 IAJ=0 MAJ=0
Signal:SL=127 NL=-84 RERL=127
QualityEst:RCQ=92 EXTRI=127 MOSLQ=4.1 MOSCQ=4.1
DialogID:43483408-3683631093-416116@S3S04.genband.com;to-tag=744749146;from-tag=3683631093-416121
 |
| 1678 | 2016-09-23 11:31:53 | 1474644713822810 | 43483197                  | 172.16.0.7   |        5060 | 198.17.84.55   |             5060 |     1 |      2 |    1 | homer01:1234 | PUBLISH sip:Pi@192.168.55.6:6090 SIP/2.0
Via: SIP/2.0/UDP 172.16.0.7:5060;branch=z9hG4bK3394838440
From: "user 1" <sip:user1@domain.com:5060>;tag=553342434
To: <sip:Pi@192.168.55.6:6090>
Call-ID: 0_3529546721@172.16.0.7
CSeq: 1 PUBLISH
Contact: <sip:user1@172.16.0.7:5060>
Content-Type: application/vq-rtcpxr
Allow: INVITE, INFO, PRACK, ACK, BYE, CANCEL, OPTIONS, NOTIFY, REGISTER, SUBSCRIBE, REFER, PUBLISH, UPDATE, MESSAGE
Max-Forwards: 70
User-Agent: Yealink SIP-T41P 36.80.0.95
Event: vq-rtcpxr
Expires: 300
Content-Length:   772

VQAlertReport: Type=moslq Severity=Critical Dir=local
LocalMetrics:
TimeStamps:START=2016-09-23T14:49:41Z STOP=2016-09-23T15:31:53Z
SessionDesc:PT=0 SR=0 FD=0 FO=0 FPP=0 PPS=50 PLC=0 SSUP=off
CallID:43483197-3683631086-54004@S3S04.genband.com
FromID:<sip:user1@172.16.0.7:5060>
ToID:"User 2" <sip:1231231234@domain.com>
LocalAddr:IP=172.16.0.7 PORT=40010 SSRC=0xfd50f80a
RemoteAddr:IP=198.17.84.54 PORT=45714 SSRC=0x29de016b
JitterBuffer:JBA=0 JBR=0 JBN=0 JBM=0 JBX=0
PacketLoss:NLR=0.0 JDR=0.0
BurstGapLoss:BLD=0.0 BD=0 GLD=0.0 GD=0 GMIN=0
Delay:RTD=0 ESD=0 SOWD=0 IAJ=0 MAJ=0
Signal:SL=0 NL=0 RERL=0
QualityEst:RCQ=0 RLQ=0 MOSLQ=0.0 MOSCQ=0.0
DialogID:43483197-3683631086-54004@S3S04.genband.com;to-tag=544845525;from-tag=3683631086-54017
 |
| 1679 | 2016-09-23 11:31:55 | 1474644715147556 | 0_3931855627@172.16.0.6   | 172.16.0.6   |        5060 | 198.17.84.55   |             5060 |     1 |      2 |    1 | homer01:1234 | PUBLISH sip:Pi@192.168.55.6:6090 SIP/2.0
Via: SIP/2.0/UDP 172.16.0.6:5060;branch=z9hG4bK662650190
From: "user 2" <sip:user2@domain.com:5060>;tag=37588204
To: <sip:Pi@192.168.55.6:6090>
Call-ID: 0_3456585388@172.16.0.6
CSeq: 1 PUBLISH
Content-Type: application/vq-rtcpxr
Max-Forwards: 70
User-Agent: Yealink SIP-T46G 28.80.0.60
Event: vq-rtcpxr
Content-Length:   721

VQAlertReport: Type=moslq Severity=Critical Dir=local
LocalMetrics:
Timestamps:START=2016-9-23 10:49:41 STOP=2016-9-23 11:31:55
SessionDesc:PT=0 SR=0 FD=0 FO=0 FPP=0 PPS=50 PLC=0 SSUP=off
CallID:0_3931855627@172.16.0.6
ToID:<sip:Pi@192.168.55.6:6090>
FromID:"user2"<sip:user2@domain.com>
LocalAddr:IP=172.16.0.6 PORT=11790 SSRC=0x29de016b
RemoteAddr:IP=198.17.84.54 PORT=45708 SSRC=0xfd50f80a
JitterBuffer:JBA=0 JBR=0 JBN=0 JBM=0 JBX=0
PacketLoss:NLR=0.0 JDR=0.0
BurstGapLoss:BLD=0.0 BD=0 GLD=0.0 GD=0 GMIN=0
Delay:RTD=0 ESD=0 SOWD=0 IAJ=0 MAJ=0
Signal:SL=0 NL=0 RERL=0
QualityEst:RCQ=0 EXTRI=0 MOSLQ=0.0 MOSCQ=0.0
DialogID:0_3931855627@172.16.0.6;to-tag=3683631086-151521;from-tag=4044788304 |
| 1680 | 2016-09-23 11:31:58 | 1474644718822563 | 43483197                  | 172.16.0.7   |        5060 | 198.17.84.55   |             5060 |     1 |      2 |    1 | homer01:1234 | PUBLISH sip:Pi@192.168.55.6:6090 SIP/2.0
Via: SIP/2.0/UDP 172.16.0.7:5060;branch=z9hG4bK4193791419
From: "user 1" <sip:user1@domain.com:5060>;tag=1775151520
To: <sip:Pi@192.168.55.6:6090>
Call-ID: 0_427120999@172.16.0.7
CSeq: 1 PUBLISH
Contact: <sip:user1@172.16.0.7:5060>
Content-Type: application/vq-rtcpxr
Allow: INVITE, INFO, PRACK, ACK, BYE, CANCEL, OPTIONS, NOTIFY, REGISTER, SUBSCRIBE, REFER, PUBLISH, UPDATE, MESSAGE
Max-Forwards: 70
User-Agent: Yealink SIP-T41P 36.80.0.95
Event: vq-rtcpxr
Expires: 300
Content-Length:   772

VQAlertReport: Type=moslq Severity=Critical Dir=local
LocalMetrics:
TimeStamps:START=2016-09-23T14:49:41Z STOP=2016-09-23T15:31:58Z
SessionDesc:PT=0 SR=0 FD=0 FO=0 FPP=0 PPS=50 PLC=0 SSUP=off
CallID:43483197-3683631086-54004@S3S04.genband.com
FromID:<sip:user1@172.16.0.7:5060>
ToID:"user 2" <sip:1231231234@domain.com>
LocalAddr:IP=172.16.0.7 PORT=40010 SSRC=0xfd50f80a
RemoteAddr:IP=198.17.84.54 PORT=45714 SSRC=0x29de016b
JitterBuffer:JBA=0 JBR=0 JBN=0 JBM=0 JBX=0
PacketLoss:NLR=0.0 JDR=0.0
BurstGapLoss:BLD=0.0 BD=0 GLD=0.0 GD=0 GMIN=0
Delay:RTD=0 ESD=0 SOWD=0 IAJ=0 MAJ=0
Signal:SL=0 NL=0 RERL=0
QualityEst:RCQ=0 RLQ=0 MOSLQ=0.0 MOSCQ=0.0
DialogID:43483197-3683631086-54004@S3S04.genband.com;to-tag=544845525;from-tag=3683631086-54017
 |
| 1681 | 2016-09-23 11:31:59 | 1474644719336974 | 43483792                  | 172.16.0.3   |        5062 | 198.17.84.55   |             5060 |     1 |      2 |    1 | homer01:1234 | PUBLISH sip:Pi@192.168.55.6:6090 SIP/2.0
Via: SIP/2.0/UDP 172.16.0.3:5062;branch=z9hG4bK577745648
From: "user 1" <sip:user1@domain.com>;tag=3428936918
To: <sip:Pi@192.168.55.6:6090>
Call-ID: 1175034081@172.16.0.3
CSeq: 1 PUBLISH
Content-Type: application/vq-rtcpxr
Max-Forwards: 70
User-Agent: Yealink SIP-T22P 7.73.0.50
Expires: 3600
Event: vq-rtcpxr
Content-Length: 656

VQIntervalReport: CallTerm
LocalMetrics:
Timestamps:START=2016-09-23T14:49:59Z STOP=2016-09-23T15:31:54Z
SessionDesc:PT=0 PPS=50 PLC=3 SSUP=off
CallID:43483792-3683631103-829053@S3S04.genband.com
LocalAddr:IP=172.16.0.3 PORT=11784 SSRC=0x0325e875
RemoteAddr:IP=198.17.84.54 PORT=45792 SSRC=0x7a049379
JitterBuffer:JBA=2 JBR=15 JBN=40 JBM=40 JBX=240
PacketLoss:NLR=0.0 JDR=0.0
BurstGapLoss:BLD=0.0 BD=0 GLD=0.0 GD=65535 GMIN=16
Delay:RTD=0 ESD=97 SOWD=48 IAJ=0 MAJ=0
Signal:SL=-20 NL=-44 RERL=127
QualityEst:RCQ=92 EXTRI=127 MOSLQ=4.1 MOSCQ=4.1
DialogID:43483792-3683631103-829053@S3S04.genband.com;to-tag=135026517;from-tag=3683631103-829057
 |
| 1682 | 2016-09-23 11:31:59 | 1474644719640883 | 1388643225@172.16.0.8     | 172.16.0.8   |        5062 | 198.17.84.55   |             5060 |     1 |      2 |    1 | homer01:1234 | PUBLISH sip:Pi@192.168.55.6:6090 SIP/2.0
Via: SIP/2.0/UDP 172.16.0.8:5062;branch=z9hG4bK319322039
From: "user 2" <sip:user2@domain.com>;tag=3230182098
To: <sip:Pi@192.168.55.6:6090>
Call-ID: 1434573583@172.16.0.8
CSeq: 1 PUBLISH
Content-Type: application/vq-rtcpxr
Max-Forwards: 70
User-Agent: Yealink SIP-T22P 7.73.0.50
Expires: 3600
Event: vq-rtcpxr
Content-Length: 611

**Comment by lmangani** [comment]
Hi @iamninjabob could you check if the timestamps match those of the call?

**Comment by iamninjabob** [comment]
@lmangani Yes the time stamps on the Publish messages in mysql match the time on the calls shown in the search field on homer.

**Comment by adubovikov** [comment]
Can you please activate syslog in the preferences.php and check queries by
hand.

Wbr,
Alexandr

**Comment by iamninjabob** [comment]
Oct  6 16:00:36 HomerQA homer[25554]: ERROR: <core> [db_query.c:181]: db_do_raw_query(): error while submitting query
Oct  6 16:00:36 HomerQA homer[25554]: ERROR: sqlops [sql_api.c:265]: sql_do_query(): cannot do the query [INSERT INTO stats_ip (from_date,]
Oct  6 16:05:36 HomerQA homer[25554]: ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Duplicate entry '2016-10-06 16:00:00-2016-10-06 16:05:00-REGISTER-Yealink SIP-T23' for key 'datemethodua' (1062)
Oct  6 16:05:36 HomerQA homer[25554]: ERROR: <core> [db_query.c:181]: db_do_raw_query(): error while submitting query
Oct  6 16:05:36 HomerQA homer[25554]: ERROR: sqlops [sql_api.c:265]: sql_do_query(): cannot do the query [INSERT INTO stats_useragent (fro]
Oct  6 16:05:36 HomerQA homer[25554]: ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Duplicate entry '2016-10-06 16:00:00-2016-10-06 16:05:00-REGISTER-172.30.76.10' for key 'datemethod' (1062)
Oct  6 16:05:36 HomerQA homer[25554]: ERROR: <core> [db_query.c:181]: db_do_raw_query(): error while submitting query
Oct  6 16:05:36 HomerQA homer[25554]: ERROR: sqlops [sql_api.c:265]: sql_do_query(): cannot do the query [INSERT INTO stats_ip (from_date,]
Oct  6 16:09:01 HomerQA CRON[26360]: (root) CMD (  [ -x /usr/lib/php5/sessionclean ] && /usr/lib/php5/sessionclean)
Oct  6 16:17:01 HomerQA CRON[26405]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Oct  6 16:19:59 HomerQA systemd-timesyncd[306]: interval/delta/delay/jitter/drift 2048s/+0.001s/0.072s/0.002s/+16ppm
Oct  6 16:29:53 HomerQA gnome-session[22243]: (gnome-settings-daemon:22307): GLib-CRITICAL **: Source ID 1406 was not found when attempting to remove it
Oct  6 16:30:36 HomerQA homer[25554]: ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Duplicate entry '2016-10-06 16:25:00-2016-10-06 16:30:00-REGISTER-Yealink SIP-T23' for key 'datemethodua' (1062)
Oct  6 16:30:36 HomerQA homer[25554]: ERROR: <core> [db_query.c:181]: db_do_raw_query(): error while submitting query
Oct  6 16:30:36 HomerQA homer[25554]: ERROR: sqlops [sql_api.c:265]: sql_do_query(): cannot do the query [INSERT INTO stats_useragent (fro]
Oct  6 16:30:36 HomerQA homer[25554]: ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Duplicate entry '2016-10-06 16:25:00-2016-10-06 16:30:00-REGISTER-172.30.76.10' for key 'datemethod' (1062)
Oct  6 16:30:36 HomerQA homer[25554]: ERROR: <core> [db_query.c:181]: db_do_raw_query(): error while submitting query
Oct  6 16:30:36 HomerQA homer[25554]: ERROR: sqlops [sql_api.c:265]: sql_do_query(): cannot do the query [INSERT INTO stats_ip (from_date,]
Oct  6 16:35:36 HomerQA homer[25554]: ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Duplicate entry '2016-10-06 16:30:00-2016-10-06 16:35:00-REGISTER-Yealink SIP-T23' for key 'datemethodua' (1062)
Oct  6 16:35:36 HomerQA homer[25554]: ERROR: <core> [db_query.c:181]: db_do_raw_query(): error while submitting query
Oct  6 16:35:36 HomerQA homer[25554]: ERROR: sqlops [sql_api.c:265]: sql_do_query(): cannot do the query [INSERT INTO stats_useragent (fro]
Oct  6 16:35:36 HomerQA homer[25554]: ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Duplicate entry '2016-10-06 16:30:00-2016-10-06 16:35:00-REGISTER-172.30.76.10' for key 'datemethod' (1062)
Oct  6 16:35:36 HomerQA homer[25554]: ERROR: <core> [db_query.c:181]: db_do_raw_query(): error while submitting query
Oct  6 16:35:36 HomerQA homer[25554]: ERROR: sqlops [sql_api.c:265]: sql_do_query(): cannot do the query [INSERT INTO stats_ip (from_date,]
Oct  6 16:39:01 HomerQA CRON[26448]: (root) CMD (  [ -x /usr/lib/php5/sessionclean ] && /usr/lib/php5/sessionclean)


Looks like I must be mistaken as it is giving guery errors on date.
I will have to do some more digging then. Thanks

**Comment by lmangani** [comment]
This sounds like a potential rotation issue. Check if your tables are being created, at any given time you should see tables for the current + coming days in database

**Comment by iamninjabob** [comment]
Okay, this is my QA version before going live. So I'll need to do this anyways, but while I have you I'd like to ask one question. With the current install I have I see no QoS panel from the default layout. (such as can bee seen on https://github.com/sipcapture/homer/wiki/Using-Homer-5-QoS-Reports) Will this panel automaticly be built or will we need to find a json file to build it?

Please feel free to close this case.

**Comment by iamninjabob** [comment]
homer_mysql_remove_partitions.pl  homer_partremove  rotation.ini
homer_mysql_rotate.pl             homer_rotate      sipcapture.crontab

Which of these rotation scripts need to be running. I already have homer_rotate running daily at 3AM.

**Comment by lmangani** [comment]
```homer_rotate sipcapture.crontab``` contains all the details to run the other files. That's the only one you should schedule for rotation to take place, assuming all paths are correct.
