### ISSUE TITLE
Vanilla Debian installation script errors

### ISSUE THREAD

**Issue by lexxua** [sipcapture/homer#195]
Hi I tried to install homer using deb files from wiki, but install script generates few errors:
mysql: [Warning] Using a password on the command line interface can be insecure.
Creating Databases...
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1044 (42000) at line 2: Access denied for user 'homer'@'%' to database 'homer_configuration'
Creating Tables...
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1062 (23000) at line 1: Duplicate entry '1' for key 'PRIMARY'
Patching Homer configuration...
Can't open /opt/homer_mysql_new_table.pl: No such file or directory.
Can't open /opt/homer_mysql_new_table.pl: No such file or directory.

Or this is expected ?

Thank you in advance!

**Comment by lmangani** [comment]
Hi @lexxua please provide details for your OS/version to receive assistance

**Comment by lexxua** [comment]
Hi @lmangani ,
Basically I took netinstall image from debian and install it in virtualbox.
userid@homer:~$ uname -a
Linux homer 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
userid@homer:~$ cat /etc/debian_version 
8.6
userid@homer:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.6 (jessie)
Release:	8.6
Codename:	jessie
userid@homer:~$

**Comment by lmangani** [comment]
Just clean the vbox and run:
```bash <( curl -s https://cdn.rawgit.com/sipcapture/homer-installer/master/homer_installer.sh )```

**Comment by lexxua** [comment]
Hi script do magic.
Only one error was reported, but everything else works fine.
Creating Tables...
ERROR 1062 (23000) at line 1: Duplicate entry '1' for key 'PRIMARY'
Setting root password....
Thank you.
