### ISSUE TITLE
Kamailio Table doesn't exist

### ISSUE THREAD

**Issue by tslytsly** [sipcapture/homer#199]
I installed homer onto Centos 7 using the installer script.
No errors on the install that I can see.

Correct mysql user and password in the kamailio.cfg file. (I checked I can login manually with this user)

Journelctl is showing thousands of these errors:
`Nov 18 12:55:37 homer.ntvd.local /usr/sbin/kamailio[14778]: ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Table 'homer_data.sip_capture_registration_20161118' doesn't exist (1146)`

`Nov 18 12:55:37 homer.ntvd.local /usr/sbin/kamailio[14778]: ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query`

`Nov 18 12:55:37 homer.ntvd.local /usr/sbin/kamailio[14778]: ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Table 'homer_data.sip_capture_registration_20161118' doesn't exist (1146)`

`Nov 18 12:55:37 homer.ntvd.local /usr/sbin/kamailio[14778]: ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query`

`Nov 18 12:55:37 homer.ntvd.local /usr/sbin/kamailio[14778]: ERROR: sipcapture [sipcapture.c:1531]: sip_capture_store(): failed to insert into database(second attempt)`

I have checked mysql tables and it doesn't seem to exist:

`mysql> show tables;`
`+-----------------------------------+`
`| Tables_in_homer_data              |`
`+-----------------------------------+`
`| logs_capture                      |`
`| report_capture                    |`
`| rtcp_capture                      |`
`| sip_capture_call_20150407         |`
`| sip_capture_registration_20150407 |`
`| sip_capture_rest_20150407         |`
`| webrtc_capture                    |`
`+-----------------------------------+`
`7 rows in set (0.00 sec)`

Have I missed something?

Thanks

**Comment by lmangani** [comment]
Hi @tslytsly 
The rotation scripts are probably not running. Check your crontab to see if they are scheduled and try executing it manually to validate auth and any eventual errors.

**Comment by tslytsly** [comment]
Hi @lmangani 
Thanks for the quick reply.
I can see this in the root crontab:
`30 3 * * * /opt/homer_rotate >> /var/log/cron.log 2>&1`

and if I try to run this manually I get this error:
`[ntvd@homer ~]$  /opt/homer_rotate`
`DBI connect('database=homer_data;mysql_socket=/var/run/mysqld/mysqld.sock','homer',...) failed: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) at opt/homer_mysql_rotate.pl line 216.
Can't call method "do" on an undefined value at /opt/homer_mysql_rotate.pl line 275.`

Sorry if I'm missing something obvious.

**Comment by lmangani** [comment]
@tslytsly is mysql running?

**Comment by tslytsly** [comment]
@lmangani yep:
`[ntvd@homer ~]$ mysqladmin -u root -p status`
`Uptime: 4417  Threads: 19  Questions: 16896  Slow queries: 0  Opens: 370  Flush tables: 1  Open tables: 172  Queries per second avg: 3.825`

**Comment by lmangani** [comment]
Check if there's a socket up for mysql, ie:
```sudo find / -type s```

**Comment by tslytsly** [comment]
looks like it: 
`/var/lib/mysql/mysql.sock`

**Comment by lmangani** [comment]
There - your socket is at ```/var/lib/mysql/mysql.sock``` while rotation looks for ```/var/run/mysqld/mysqld.sock```

Please update your ```rotation.ini``` with the right path and run again.

**Comment by lmangani** [comment]
@sipcapture/contributors can anyone confirm if this is the default location for CentOS mysql socket?

**Comment by giavac** [comment]
It is for CentOS 7 - I can see it in a few cases (e.g. mariadb 5.5, mysql 5.6).

**Comment by tslytsly** [comment]
@lmangani I can confirm that after changing the path manually running the script doesn't throw any errors.

**Comment by lmangani** [comment]
Alright, will add a condition to the installer(s) to reflect this - keeping this issue open to track

**Comment by tslytsly** [comment]
@lmangani 
Thanks for the help.
I may need to open another issue for this:
The table is now being written, however there is no data in the Homer UI.
tcpdump shows that my capture agent is sending the data to correct port, but nothing is showing up.

**Comment by lmangani** [comment]
If the tables exist and there are no errors from Kamailio, just select "Last 10 Minutes" from HOMER UI and set the proper timezone settings if needed to see results.

**Comment by lmangani** [comment]
Patch for CentOS varieties in: https://github.com/sipcapture/homer-installer/commit/58ab8bfdbbfe068a97de1a0d2de67d23aaedaf1e

**Comment by tslytsly** [comment]
@lmangani 
> If the tables exist and there are no errors from Kamailio, just select "Last 10 Minutes" from HOMER UI and set the proper timezone settings if needed to see results.

yep that's working.
Thanks for the speedy replies and help.

**Comment by lmangani** [comment]
@tslytsly our pleasure, enjoy Homer! ;)

**Comment by strongman221** [comment]
salut 
je viens d'installer homer-sipcapture mais je vois plus de donnéés sur sur le sip-search alors que je vois les trafic VoIP 
i need help.

**Comment by strongman221** [comment]
greeting
I just installed homer-sipcapture but I don't see more data on the sip-search while I see VoIP traffic
i need help.
