### ISSUE TITLE
Timezones - not all timezones are shown

### ISSUE THREAD

**Issue by dancapper** [sipcapture/homer#200]
in the Homer SIP Capture web interface, only a particular range of timezones are selectable in the Time Range window.

While the default is our local timezone (Pacific/Auckland - GMT+12 and in DST GMT+13) we cannot select another timezone and then later return to our local timezone.  Nor can a user choose it from the list explicitly.

Along with the above, the "default" time span selected does not seem to correlate with the current local time.

Can all valid timezones be provided for in this list?

**Comment by lmangani** [comment]
Hi @dancapper 
The current list of supported timezones is here: https://github.com/sipcapture/homer-ui/blob/fb980710495651d2a86aa570e00a90c40ebae033/js/controller.js#L208

Could you produce the exact stepping to replicate your issue?

**Comment by dancapper** [comment]
Hi,

A quick glance at that list demonstrates that our timezone at least is
missing :)

Login to homer-ui
Click on the "time span" ui element near upper right hand corner
Select time zone drop down
Observe there are no timezones for GMT+12 or GMT+13

As you've shown me where they are defined, I can test and create a pull
request if you like, I'll have a look tomorrow.  Does the front end do all
the timezone translation to GMT?

Thanks and regards

Dan


On Nov 30, 2016 19:54, "Lorenzo Mangani" <notifications@github.com> wrote:

Hi @dancapper <https://github.com/dancapper>
The current list of supported timezones is here:
https://github.com/sipcapture/homer-ui/blob/fb980710495651d2a86aa570e00a90
c40ebae033/js/controller.js#L208

Could you produce the exact stepping to replicate your issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sipcapture/homer/issues/200#issuecomment-263797956>,
or mute
the thread

**Comment by dancapper** [comment]
I added the timezones in that file and it works.  So I have created a pull request in homer-ui.  Thanks.
