### ISSUE TITLE
Using JSON for deeplink into homer

### ISSUE THREAD

**Issue by davidtek** [sipcapture/homer#201]
Relating to this message : https://github.com/sipcapture/homer/issues/141

There are multiple issues.

1. For we can't pass unix time stamps because the code only handles strings. Which means we always have to pass formatted dates.
2. The split is incorrect, and it is causing a quote to be included in the last string that is passed in the object
3. The examples at the given link are incorrect and DO NOT WORK (end instead of enddate, start instead of startdate )
4. Example left out / between # and r

The code uses primitive split to decode a complex string. Instead I propose we use JSON.

The attached patch modifies the behaviour of the function so that it accepts a JSON string ( which is properly decoded and supports integers ).

So using the old code you would use : 

#/result?query=(trancall:'true',startdate:"2016-12-05 12:00:00",enddate:"2016-12-05 13:00,search_callid:'7216880062184e3c745256a5335101da@192.168.2.2:5060)

After my patch, it would be like this ( purposely left out last quote because of bad parsing :

#/result?query=(trancall:'true',startdate:'2016-12-05 12:00:00',enddate:'2016-12-05 13:00',search_callid:'7216880062184e3c745256a5335101da@192.168.2.2:5060)

#/result?query={"trancall":1,"startdate":"2016-12-05 12:00:00","enddate":"2016-12-05 13:00","search_callid":"7216880062184e3c745256a5335101da@192.168.2.2:5060"}

or properly encoded : 
#/result?query=%7B%22trancall%22%3A1%2C%22startdate%22%3A%222016-12-05+12%3A00%3A00%22%2C%22enddate%22%3A%222016-12-05+13%3A00%22%2C%22search_callid%22%3A%227216880062184e3c745256a5335101da%40192.168.2.2%3A5060%22%7D

Why is this better ?

1. It uses standard and well known json
2. It allows the user to pass timestamps in milliseconds as an integer OR a fully formatted time
3. It fixes problems with the parser
4. JSON is cool.

The original code is great because it allows linking directly to searching, I have simply reworked it to make it slightly better.

I WROTE THIS PATCH AND GIVE PERMISSION TO THE SIPCAPTURE PROJECT TO INCLUDE IT IN THEIR PROJECT AND APPLY THE SAME LICENSE TO THE CODE AS THE SIPCAPTURE PROJECT USES.

**Comment by davidtek** [comment]
https://github.com/davidtek/homer-ui

https://github.com/davidtek/homer-ui/commit/7abe716d9ee98fc08d78a4658a946b26d57b8904

**Comment by adubovikov** [comment]
Please make a pull request
Thank you.

**Comment by lmangani** [comment]
HI @davidtek 

Thanks for your contribution and effort! You can find a guide with the few steps required to submit a Pull Request here: https://help.github.com/articles/creating-a-pull-request/

This will allow us to review the code before its merged and/or suggest or apply any adaptions, if needed. 
If you have any questions, feel free to ask :)
