### ISSUE TITLE
Capagent 6 issue installs in different folders and does not work

### ISSUE THREAD

**Issue by 3bugi** [sipcapture/homer#202]
Had Captagent 4 running with Homer 5 installed and deleted the folders for Captagent 4 on our sip server, so I could install V6 even though now still when I do 
captagent -v gives me the output of version 4.2.0

Anyway installing V6 Issue - 
Following the instructions exactly as per wiki
cd /usr/src
  git clone https://github.com/sipcapture/captagent.git captagent
  cd captagent
  ./build.sh
  ./configure
  make && make install

It installs in usr/local/captagent
Then it adds more folders and the config files directory becomes usr/local/captagent/etc/captagent
Checked version and output still 4.2.0
After configuring the files captagent to send to homer
Then do a /etc/init.d/captagent start
It gives nothing found

So it does not work.
Deleted the folders and tied an other method - 
So then I went to the PDF http://www.kamailio.org/events/2015-KamailioWorld/Day1/07-Alexandr.Dubovikov-Sipcapture-Introducing-Homer-5-Captagent-6.pdf

and followed the instruction to install Captagent
Setup of a CAPTAGENT is just as easy using the provided installer:
# wget https://raw.githubusercontent.com/sipcapture/homer/master/scripts/extra/captagent_installer.sh
# chmod 775 captagent_installer.sh
# ./captagent_installer.sh

And it is broken too
[root@cloud2 captagent]# wget https://raw.githubusercontent.com/sipcapture/homer/master/scripts/extra/captagent_installer.sh
--2016-12-27 08:35:13--  https://raw.githubusercontent.com/sipcapture/homer/master/scripts/extra/captagent_installer.sh
Resolving raw.githubusercontent.com... 151.101.192.133, 151.101.128.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-27 08:35:13 ERROR 404: Not Found.

Any help as now I finished with no monitoring.

**Comment by gabyfulchic** [comment]
could someone help him ?
