### ISSUE TITLE
QoS from VQM

### ISSUE THREAD

**Issue by ishmaelen** [sipcapture/homer#203]
Hello!

I have a lot of QoS information stored in an external database (VQM-stats sent from clients over HTTPS).

Is there any way for me to insert this data to Homers DB and have Homer show QoS-information per call? What is the required format for report_capture to show all those nice graphics? Is there som required/pre-defined format for the message in "msg" column?

As observed from the HTTP request:

`<![CDATA[VQSessionReport
CallID: 0198510sakldfjj091309las
LocalID: 
RemoteID: 
OrigID: 
LocalAddr: IP=1.1.1.1 PORT=62420 SSRC=0x637687cd
RemoteAddr: IP=2.2.2.2 PORT=16462 SSRC=0xc46b47e3
LocalGroup: 
RemoteGroup: 
LocalMetrics:
Timestamps: START=2016-12-28T22:34:15Z STOP=2016-12-28T22:35:16Z
SessionDesc: PD=audio/opus SR=32000 FD=20 FO=0 FPP=2 PPS=25 PLC=0
JitterBuffer: JBA=3 JBN=40 JBM=40 JBX=80
PacketLoss: NLR=0.00 JDR=0.00
BurstGapLoss: BLD=0.00 BD=0 GLD=0.00 GD=93600 GMIN=16
Delay: RTD=44 OWD=92
QualityEst: RLQ=176 RCQ=173 MOSLQ=4.19 MOSCQ=4.15 QoEEstAlg="VQmon"
RemoteMetrics:
Timestamps: START=2016-12-28T22:34:15Z STOP=2016-12-28T22:35:16Z
SessionDesc: PLC=3
JitterBuffer: JBA=3 JBR=0 JBN=40 JBM=40 JBX=80
PacketLoss: NLR=0.00 JDR=0.00
BurstGapLoss: BLD=0.00 BD=0 GLD=0.00 GD=40040 GMIN=16
Delay: RTD=44 ESD=0
QualityEst: RCQ=173 MOSLQ=4.09 MOSCQ=4.09
]]>`

I also have all data stored in a database on the receiever of these HTTP requests so I could copy them to Homers DB on insert etc. as well if it simplifies things.

Thanks!

//Andy

**Comment by lmangani** [comment]
Hi @ishmaelen 
This looks like the VQ body of an RTCP-XR PUBLISH message at first sight.
HOMER can parse those our of SIP messages so its adaptable, could you specify the devices sending such reports, the format the use, etc. We might want to just try receive them in HOMER rather than import them from an external source.

**Comment by ishmaelen** [comment]
Hello @lmangani 

These reports are coming in from Counterpath Bria clients, sent to Stretto platform using HTTP(s).

I can e-mail you a full example but as it includes a lot of sensitive data I don't want to upload it here.
The VQM data is just a small part of the entire HTTP(s) request under a <vqm_report> header.

//Andy

**Comment by lmangani** [comment]
My guess is the [CUSTOM STATS](https://github.com/sipcapture/homer-config/blob/master/sipcapture/sipcapture.kamailio#L870) could be cloned and used to handle the posted XML, extract the VQ body and do the parsing, etc. Surely takes a bit of time but seems an interesting case - We'll look into this with the team, thanks for providing some background and examples :+1:

**Comment by oza4h07** [comment]
@ishmaelen : 1. For curiousity sake, which database are you currently using to store VQM-Stats ?
2. I'm evaluating the interest to add VQM-Stats in my setup. Have you dealt with situations in which VQM-Stats helped with Voice Quality issues ?
Best regards

**Comment by ishmaelen** [comment]
I am using MySQL to store the data (and MyDBR to view it as it has drill functions etc.) and yes I have experienced that the stats has helped indicate where the issue for voice quality has been located. 
As these stats come from the UEs and not "pseudo-calculated" they seem to be quite reliable, at least in my experience.
