### ISSUE TITLE
Use 'ip addr' in homer_installer.sh instead of ifconfig

### ISSUE THREAD

**Issue by oza4h07** [sipcapture/homer#205]
Hello,

Looking at homer_installer.sh from [1], I can see the following line:
LOCAL_IP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')

I wonder if using 'ip addr' would improve this script portability as:
1. ifconfig output is localized (see [2])
2. ifconfig is not installed on all systems but ip addr is present (at least on my CentOS 7.3.1611).

So, both commands produce the same output (please, note I had to use adr instead of addr) on my systems (tested on both CentOS 7.3.1611 and Debian 8.6) :
LOCAL_IP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (adr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
LOCAL_IP=$(ip addr | grep -Po 'inet \K[\d.]+' | grep -v '127.0.0.1')

Best regards

[1] https://cdn.rawgit.com/sipcapture/homer-installer/master/homer_installer.sh
[2] http://inai.de/2008/02/19
[3] http://unix.stackexchange.com/questions/87468/is-there-an-easy-way-to-programmatically-extract-ip-address

**Comment by giavac** [comment]
Thanks @oza4h07,
I have to agree that `iconfig` may present some issues (even if it's just used to suggest what URL will Homer be listening to).

I've tried your suggested improvement but it may have issues when more than one IP address is associated to the main interface, e.g. `eth0`.

Example with anonymised output:

```
2: eth0: [...]
[...]
    inet 111.111.111.111/18 brd 111.111.111.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.16.0.6/16 brd 10.16.255.255 scope global eth0
       valid_lft forever preferred_lft forever
[...]
```

```
[root@ahost ~]# LOCAL_IP=$(ip addr | grep -Po 'inet \K[\d.]+' | grep -v '127.0.0.1')
[root@ahost ~]# echo $LOCAL_IP
111.111.111.1111 10.16.0.6
```

Perhaps a compromise (easier to read/remember) (from [0]) could be:

```
[root@ahost ~]# LOCAL_IP=$(ip route get 1 | awk '{ print $NF; exit}')
[root@ahost ~]# echo $LOCAL_IP
111.111.111.111
```

This works on both `CentOS 7.3.1611 x64` and `Debian 8.6 x64`.

Cheers.

[0] http://stackoverflow.com/a/25851186/620140
