### ISSUE TITLE
Geo chart not working after script install

### ISSUE THREAD

**Issue by coboni01** [sipcapture/homer#206]
Hi,

Setup: vanilla Debian 8 + Homer installed using the install script.
All seems to work fine except the Geo stats, printing:

"We don't have any chart data. Please enable GEO STATS in the config of your capture server."

Root seems to be the mysql error when Geo stats is called:

"T 127.0.0.1:3306 -> 127.0.0.1:35026 [AP]
.......#42000Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'homer_statistic.stats_geo.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"

After digging into this, seems to be related to:

 https://groups.google.com/forum/#!topic/homer-discuss/H5FH6SeNnv4

just that the fix described there is not available anymore.

Changing line 709 in based on the description form above
/var/www/html/api/RestApi/Statistic.php

from

$layerHelper['group']['by'] = "country,method";

to

$layerHelper['group']['by'] = "id,from_ts,to_ts,country,lat,lon,method";

seems to make it work, although not sure if the change has any impact or not.

Cosmin

**Comment by adubovikov** [comment]
Thank you, but unfortunately grouping by all fields will return wrong data, because we have to group it by country and method. Please deactivate only_full_group_by as you see in the response.

**Comment by lmangani** [comment]
What should be best changed in the installer for this to work smoothly? An option to enable geo?

**Comment by adubovikov** [comment]
the param should be enabled:
https://github.com/sipcapture/homer-config/blob/master/sipcapture/sipcapture.kamailio#L33

geomodules should be installed 

and "only_full_group_by" should be deactivated in my.cnf

**Comment by adubovikov** [comment]
Here is more information about this. I think we have to fix it propertly in the php code.
http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by

let me think about the best way.

**Comment by lmangani** [comment]
Wiki updated with suggested settings: 
https://github.com/sipcapture/homer/wiki/Example:-GeoIP

For the installer, the only way is to patch the my.cnf as part of the script - will check internally.

**Comment by adubovikov** [comment]
only way to use this feature is disable only_full_group_by in my.cnf

**Comment by bayforza** [comment]
Hi

**Comment by bayforza** [comment]
Hi, 

My Debian 8 Jessie setup is working except Geo Chart.

I've implemented exactly the same configuration update from the following wiki link on my installation but still have "We don't have any chart data. Please enable GEO STATS in the config of your capture server. " notification on web panel.

https://github.com/sipcapture/homer/wiki/Example:-GeoIP

**Comment by saydulk** [comment]
broken link - https://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz

please update wiki @lmangani 

![Screenshot from 2019-05-14 07-29-21](https://user-images.githubusercontent.com/1058663/57664444-082e7380-761a-11e9-8cbc-88eca246a2fb.png)

**Comment by lmangani** [comment]
@saydulk please consider upgrading to H7 we no longer maintain H5 and legacy documentation. Thanks!

**Comment by saydulk** [comment]
@lmangani I think updating to Homer7 may require some DB schema changes - I couldn't find good documentation on that
