### ISSUE TITLE
SIP call timezone issue?

### ISSUE THREAD

**Issue by zecke** [sipcapture/homer#207]
Hi,

we are using Kamailio to receive HEP3 and store the SIP capture in the database. The symptoms is that when clicking on any SIP message doesn't show any details.. either from the primary listing or the transaction listing. It seems some sort of timezone conversion happens on insert and then doSearchMessage (by id) is using a non matching time interval in the where clause. Is this known? What to do about it?

On the kamailio system we have:

```
$ date
Thu Jan 26 20:22:43 CET 2017
```

It seems that inserting the DATE is subject to timezone conversion but the doSearchMessage works on a time interval as timestamp. E.g. notice the difference between micro_ts/milli_ts and unix_timestamp(date)?

```
 (date BETWEEN FROM_UNIXTIME(1484896289) AND FROM_UNIXTIME(1484896890))
```

```
SELECT id, date, unix_timestamp(date), (micro_ts DIV 1000) as milli_ts, micro_ts,method FROM sip_capture_call_20170120  WHERE ( id = '3059') LIMIT 1
    -> ;
+------+---------------------+----------------------+---------------+------------------+--------+
| id   | date                | unix_timestamp(date) | milli_ts      | micro_ts         | method |
+------+---------------------+----------------------+---------------+------------------+--------+
| 3059 | 2017-01-20 08:16:30 |           1484900190 | 1484896590400 | 1484896590400037 | INVITE |
+------+---------------------+----------------------+---------------+------------------+--------+
```

```
select 1484896590 - 1484900190;
+-------------------------+
| 1484896590 - 1484900190 |
+-------------------------+
|                   -3600 |
+-------------------------+
1 row in set (0.00 sec)
```

So one hour difference.. same as CET?

**Comment by zecke** [comment]
@lmangani @adubovikov @mmonka

**Comment by adubovikov** [comment]
you get "unix_timestamp(date)" in CET, but the time is in UTC

before execute the query please set TZ to UTC and you will see no different.

**Comment by adubovikov** [comment]
also please check the capture system. Have been time synced ?

**Comment by zecke** [comment]
Okay but is this missing somewhere in homer-api? Because right now ISUP details find message details and SIP details find nothing and the message originate from the same system (so the time is right and the time is taken out of the message). Is it intended that kamailio runs on a machine with UTC?

```
        $time['from'] = getVar('from', round((microtime(true) - 300) * 1000), $timestamp, 'long');
        $time['to'] = getVar('to', round(microtime(true) * 1000), $timestamp, 'long');
        $time['from_ts'] = floor($time['from']/1000);
        $time['to_ts'] = round($time['to']/1000);
...
        $layerHelper['time'] = $time;
```

```
...
                if(isset($layerHelper['time']))
                {
                        $time = $layerHelper['time'];
                        $datafield = "date";
                        if(isset($layerHelper['fields']['time'])) $datafield = $layerHelper['fields']['time'];

                        $query .= " WHERE (".$datafield." BETWEEN FROM_UNIXTIME(".$time['from_ts'].") AND FROM_UNIXTIME(".$time['to_ts']."))";
                        if(count($callwhere)) $query .= " AND ( " .implode(" ".$layerHelper['where']['type']." ", $callwhere). ")";
                }
```

so maybe it would be better to make this work on 'from' and 'to' here to avoid having to deal with different timezones? I am not sure how it is intended to work, I just see that it has some issues. What kind of data would help you to understand more about this issue?

**Comment by adubovikov** [comment]
so, just to be clear that we are same page.

How it works:
1. captagent sends HEP packets with timestamp  (sec + usec). Here we don't have any time zones.
2.  kamailio receive it and do insert into mysql using timestamp from the HEP packet. 

https://github.com/kamailio/kamailio/blob/master/src/modules/sipcapture/sipcapture.c#L1300
https://github.com/kamailio/kamailio/blob/master/src/modules/sipcapture/sipcapture.c#L1305

3. during search we use FROM_UNIXTIME to convert unixtime to MYSQL DATE (here come timezone)
to avoid inconsistency, we use "SET timezone +00:00" and all results have to be in UTC timezone.

 https://github.com/sipcapture/homer-api/blob/master/api/Database/PDOConnector.php#L69

4. now is very good question, why you have different time in 'date' and 'microts'. There should be same, as you see in the code. Do you use actual version of the sipcapture module ?

**Comment by zecke** [comment]
1. / 2. should be like that.

3.

doSearchTransaction
```
        "calldata": [
            {
                "id": "75564",
                "protocol": "sip",
                "method": "INVITE",
                "src_port": "5060",
                "dst_port": "5060",
                "trans": "call",
                "callid": "1569355735@XXXX",
                "node": "homer01:0",
                "dbnode": "homer01",
                "micro_ts": "1484670746124863",
                "ruri_user": "4917621050247",
                "source_alias": "XXXX",
                "destination_alias": "YYYY",
                "source_ip": "YYYY",
                "destination_ip": "XXXXX",
                "src_id": "XXX:5060",
                "dst_id": "XXX:5060",
                "milli_ts": 1484670746124,
                "method_text": "INVITE  (SDP) ",
                "msg_color": "blue",
                "destination": 1
            },
```

Clicking on that INVITE in the transaction view

```
The query made. So id 75564 as in the transaction view..
{"timestamp":{"from":1484670746124,"to":1484670746124},"param":{"search":{"id":75564,"callid":"1569355735@XXXXX"},"location":{"node":"homer01"},"transaction":{"call":true,"registration":false,"rest":false,"isup":false}}}
```


```
Actual SQL query not giving a result
SELECT id, date, (micro_ts DIV 1000) as milli_ts, micro_ts,method,reply_reason,ruri,ruri_user,ruri_domain,from_user,from_domain,from_tag,\nto_user,to_domain,to_tag,pid_user,contact_user,auth_user,callid,callid_aleg,via_1,via_1_branch,cseq,diversion,reason,content_type,auth,\nuser_agent,source_ip,source_port,destination_ip,destination_port,contact_ip,contact_port,originator_ip,originator_port,correlation_id,proto,family,rtp_stat,type,node,'call' as trans,'homer01' as dbnode,msg FROM sip_capture_call_20170117  WHERE (date BETWEEN FROM_UNIXTIME(1484670446) AND FROM_UNIXTIME(1484671046)) AND ( id = '75564') LIMIT 1
```

BUT:

```
It is there:
| 75564 | 2017-01-17 17:32:26 | 1484670746124 | 1484670746124863 | INVITE
```

I know too little about both mysql and the rest of the stack. So either things go wrong when inserting it or when retrieving it. It looks a bit like "wrong" on insert as the ISUP transactions don't have this problem and go through a different path for insert (insert through the kamailio.cfg).

**Comment by adubovikov** [comment]
please show how you insert it. The full sql query.

**Comment by zecke** [comment]
```
ISUP:

	$var(table) = "isup_capture_all_" + $var(utc);
	sql_query("is", "INSERT INTO $var(table)
				(correlation_id, method, opc, dpc, cic, called_inn, called_ton,
				 called_npi, called_number, calling_ni, calling_restrict,
				 calling_screened, calling_ton, calling_npi, calling_number,
				 calling_category, cause_standard, cause_location, cause_itu_class,
				 cause_itu_cause, event_num, hop_counter, nci_satellite,
				 nci_continuity_check, nci_echo_device, fwc_nic, fwc_etem,
				 fwc_iw, fwc_etei, fwc_isup, fwc_isup_pref, fwc_ia, fwc_sccpm,
				 transmission_medium, user_coding_standard,
				 user_transfer_cap, user_transfer_mode,
				 user_transfer_rate, user_layer1_ident, user_layer1_proto,
				 source_ip, source_port, destination_ip, destination_port,
				 proto, date, micro_ts, msg)
                                VALUES($(var(corr_id){sql.val}), $var(method), $(var(opc){sql.val}),
					$(var(dpc){sql.val}), $(var(cic){sql.val}), $var(called_inn),
					$var(called_ton), $var(called_npi), $var(called_num),
					$var(calling_ni), $var(calling_res), $var(calling_scr),
					$var(calling_ton), $var(calling_npi), $var(calling_num),
					$var(calling_cat), $var(cause_std), $var(cause_loc),
					$var(cause_cls), $var(cause_num), $var(event_num),
					$var(hop_counter), $var(nci_sat), $var(nci_con),
					$var(nci_ech), $var(fwd_nic), $var(fwd_eemeth),
					$var(fwd_interw), $var(fwd_eeinf), $var(fwd_isup),
					$var(fwd_isupp), $var(fwd_isdn), $var(fwd_sccp),
					$var(trans_med), $var(ui_coding), $var(ui_tracap),
					$var(ui_tramde), $var(ui_trarte), $var(ui_l1idnt),
					$var(ui_l1prot), $var(src_ip), $var(src_port),
					$var(dst_ip), $var(dst_port), $var(proto),
					from_unixtime($var(time_sec)), $var(time_sec) * 1000000 + $var(time_usec),
					$var(json));");
```

Let me try to get the INSERT done by kamailio from the mysql log.

**Comment by adubovikov** [comment]
@zecke no it looks ok. Can you please tell me, what do you have in the timezone of the search ?

click please on "select time" in the UI and check TZ. Now should be CET+2

**Comment by zecke** [comment]
It was GMT+1 (CET), I have tried +0/+2 but the result is the same. ISUP message details work and SIP can not be found... :(

**Comment by adubovikov** [comment]
so, please set again "CET" (+2) select time last hour and do search.

please check the from/to range. You can post it also here. 

please also post the sql search query.

**Comment by zecke** [comment]
```
{"timestamp":{"from":1484670746124,"to":1484670746124},"param":{"search":{"id":75564,"callid":"1569355735@XXXXX"},"location":{"node":"homer01"},"transaction":{"call":true,"registration":false,"rest":false,"isup":false}}}
```

so the timestamp is unchanged and is the one from the transaction.calldata result. I have seen other queries that do transmit a timezone offset but /api/v1/search/method doesn't seem to be one of them.

**Comment by zecke** [comment]
Markus just commented this:

```
mysql> show global variables like '%zone%';
+------------------+-------+
| Variable_name | Value |
+------------------+-------+
| system_time_zone | CET |
| time_zone | UTC |
+------------------+-------+
```

and I followed the path in kamailio to (not sure if it is called):

```
db_time2str_ex
        /* Convert time_t structure to format accepted by the database */
        t = localtime(&_v);
        l = strftime(_s, *_l -1, "%Y-%m-%d %H:%M:%S", t);
```

So localtime should be CET but DB time is UTC. I assume this creates a mismatch. Would you recommend changing the DB time to CET too or the system time to UTC?

**Comment by adubovikov** [comment]
please check your query:

{"timestamp":{"from":1484670746124,"to":1484670746124},"param":{"search":{"id":75564,"callid":"1569355735@XXXXX"},"location":{"node":"homer01"},"transaction":{"call":true,"registration":false,"rest":false,"isup":false}}}

as I see, from and to are same.

**Comment by adubovikov** [comment]
they should do some range: +/- 60 seconds

**Comment by zecke** [comment]
```
                $scope.showMessage = function(data, event) {

                    var search_data = {

                        timestamp: {
                            from: parseInt(data.micro_ts / 1000),
                            to: parseInt(data.micro_ts / 1000)
                        },
```

I think the timestamp being the same is intended here. It is to show the details of a known message (id is known, timestamp is known, partition would be known too)

**Comment by adubovikov** [comment]
also here:


| 75564 | 2017-01-17 17:32:26 | **1484670746124** | 1484670746124863 | INVITE

but the query is:

WHERE (date BETWEEN FROM_UNIXTIME(**1484670446**) AND FROM_UNIXTIME(**1484671046**)) AND ( id = '75564') 

looks like something wrong in the API, can you please debug and see thats value you have received and why it was converted to the wrong timestamp.

{"timestamp":{"from":**1484670746124**,"to":1484670746124},"param":{"search":{"id":75564,"callid":"1569355735@XXXXX"},"location":{"node":"homer01"},"transaction":{"call":true,"registration":false,"rest":false,"isup":false}}}

so, this is definitely something wrong in the api php.

**Comment by adubovikov** [comment]
oops, it's ok. 1484671046 > 1484670746.

nevermind!

**Comment by adubovikov** [comment]
can you please do two queries:

SELECT id, date, unix_timestamp(date), (micro_ts DIV 1000) as milli_ts, micro_ts,method FROM sip_capture_call_20170117  WHERE ( id = '75564') LIMIT 1;

and:

SET time_zone = "+00:00";
SELECT id, date, unix_timestamp(date), (micro_ts DIV 1000) as milli_ts, micro_ts,method FROM sip_capture_call_20170117  WHERE ( id = '75564') LIMIT 1;

**Comment by zecke** [comment]
But I think Markus has pointed us to the right direction:

* kamailio formats a timestring using localtime
* mysql is treating the database as UTC

That explains the 1h difference and why the ISUP insert works (we let mysql convert the timestamp to a datetime). Now the question is.. what is recommended..

a.) Run the db with CET
b.) Run the system as UTC?

```
mysql> SELECT id, date, unix_timestamp(date), (micro_ts DIV 1000) as milli_ts, micro_ts,method FROM sip_capture_call_20170117 WHERE ( id = '75564') LIMIT 1;
+-------+---------------------+----------------------+---------------+------------------+--------+
| id    | date                | unix_timestamp(date) | milli_ts      | micro_ts         | method |
+-------+---------------------+----------------------+---------------+------------------+--------+
| 75564 | 2017-01-17 17:32:26 |           1484674346 | 1484670746124 | 1484670746124863 | INVITE |
+-------+---------------------+----------------------+---------------+------------------+--------+
1 row in set (0.00 sec)

mysql> SET time_zone = "+00:00";
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT id, date, unix_timestamp(date), (micro_ts DIV 1000) as milli_ts, micro_ts,method FROM sip_capture_call_20170117 WHERE ( id = '75564') LIMIT 1;
+-------+---------------------+----------------------+---------------+------------------+--------+
| id    | date                | unix_timestamp(date) | milli_ts      | micro_ts         | method |
+-------+---------------------+----------------------+---------------+------------------+--------+
| 75564 | 2017-01-17 17:32:26 |           1484674346 | 1484670746124 | 1484670746124863 | INVITE |
+-------+---------------------+----------------------+---------------+------------------+--------+
1 row in set (0.00 sec)

mysql> SET time_zone = "+01:00";
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT id, date, unix_timestamp(date), (micro_ts DIV 1000) as milli_ts, micro_ts,method FROM sip_capture_call_20170117 WHERE ( id = '75564') LIMIT 1;
+-------+---------------------+----------------------+---------------+------------------+--------+
| id    | date                | unix_timestamp(date) | milli_ts      | micro_ts         | method |
+-------+---------------------+----------------------+---------------+------------------+--------+
| 75564 | 2017-01-17 18:32:26 |           1484674346 | 1484670746124 | 1484670746124863 | INVITE |
+-------+---------------------+----------------------+---------------+------------------+--------+
1 row in set (0.00 sec)
```

no effect :)

**Comment by mmonka** [comment]
Hi,

any chance to adapt the sip logic to have

a) system in CET

and

b) db in UTC

That's what all our systems look like today.

**Comment by adubovikov** [comment]
yep, looks like this is the issue.

the only way is change "db_vals[0].type" to DB1_STR

https://github.com/kamailio/kamailio/blob/master/src/modules/sipcapture/sipcapture.c#L1298

//Pseudo code
db_vals[0].type = DB1_STR;
db_vals[0].nul = 0;
db_vals[0].val.str_val = sprintf("FROM_UNIXTIME(%d)",(sco->tmstamp/1000000));

this will solve the issue, because mysql will do internal DB TIME conversion. 

not sure about PgSQL in this case, the solution will work only for MySQL.

**Comment by zecke** [comment]
From what I see there are two/three ways.. but both are likely to be met with some resistance upstream:

a.) Change time2str_ex in kamailio to use gmtime instead of localtime
b.) Try to have db_mysql do the date conversion instead of the generic way to convert to string
c.) Change to what alexandr just proposed :)

**Comment by adubovikov** [comment]
or set DB internal time to CET and use  'SET time_zone = "+01:00"' there is needed.

anyway Homer's API do this.

**Comment by adubovikov** [comment]
@zecke 
a) will not solve the issue, but will create another on the system with TZ != UTC.

so, here only 2:
1) use FROM_UNIXTIME
2. use same zone on kamailio and mysql. (z.b. switch kamailio to UTC)

**Comment by zecke** [comment]
Would you accept a change to sipcapture.c to format the string already (tuned by a settable parameter?)?

**Comment by adubovikov** [comment]
sure, but lets do it this way:

modpraram("sipcapture", "enable_sql_timefunction", 1);
modpraram("sipcapture", "custom_sql_timefunction", "FROM_UNIXTIME(%d)");

so, if the enable_sql_timefunction == true , we change the field to STR and use custom_sql_timefunction. If not, we use old way. Just to be compatible with old setups...

agree ?

**Comment by adubovikov** [comment]
so, just another 5 cents.

IMHO better fix it in the db_mysql. If the field is DB1_DATETIME, better use "FROM_UNIXTIME" vs local conversion. This make more consistence way and avoid any issues in the future.

**Comment by zecke** [comment]
```
diff --git a/src/modules/db_mysql/km_val.c b/src/modules/db_mysql/km_val.c
index fd93d9b..39acfc4 100644
--- a/src/modules/db_mysql/km_val.c
+++ b/src/modules/db_mysql/km_val.c
@@ -46,6 +46,22 @@ int db_mysql_val2str(const db1_con_t* _c, const db_val_t* _v, char* _s, int* _le
        int l, tmp;
        char* old_s;

+       switch(VAL_TYPE(_v)) {
+       case DB1_DATETIME:
+               /* Let MySQL handle timestamp to internal time representation */
+               if (!_s || !_l || !*_l) {
+                       LM_ERR("Invalid parameter value\n");
+                       return -1;
+               }
+               l = snprintf(_s, *_l, "UNIX_TIMESTAMP(%d)", VAL_INT(_v));
+               if (l < 0 || ret >= *_l) {
+                       LM_ERR("Error in snprintf\n");
+                       return -1;
+               };
+               *_l  = l;
+               return 0;
+       };
+
        tmp = db_val2str(_c, _v, _s, _len);
        if (tmp < 1)
                return tmp;
```

untested.. but something like this?

**Comment by adubovikov** [comment]
perfect, exactly this  :+1:

**Comment by zecke** [comment]
Great s/ret/l/ and _l to _len and it compiles but the date is stored as 00-00-0000 00:00:00 in the database. I am on my way :)

**Comment by zecke** [comment]
https://github.com/zecke/kamailio/commit/d5f20adf1dab24860f99df8683433db26c074504 with the fixed code. We will hopefully check soon if this is fixing the problem and then I will rebase and create a pull request at kamailio.

**Comment by adubovikov** [comment]
super! Thank you!

**Comment by dig12345** [comment]
Has this been fixed? I see MYSQL module added modparam("db_mysql", "server_timezone", 1) but doesn't seem to affect sipcapture inserts. Is there a way to resolve homer box in local time while db is in UTC?

**Comment by adubovikov** [comment]
The time in the mysql is always UTC (timestamp field) , therefore doesn't
matter that server's timezone you have. Only one suggestion from my side:
click on the timeselector on UI and check that the timezone has been
selected.

**Comment by dig12345** [comment]
The inserts are made in local time but MYSQL assumes they're in UTC so
homer UI can't find them. I've been struggling with this for a week since
we are trying to use a separate database machine. If they're on the same
box it doesn't matter but if DB is in UTC (usually is) and homer box is in
local time its broken. I've changed every time zone setting in
preferences.php, mysql.php, time selector etc. The problem comes from
sipcapture module inserting in local time not UTC.  Only solution we found
is to change homer box to UTC.

**Comment by adubovikov** [comment]
sorry, but i really don't understand the problem. Insertion we always do in
Unix TS (no TZ) and search we do ALSO using unixTS (No TZ), doesn't matter
that TZ you have, the result SHOULD be always same.

Can you please give a bit more input ? also some examples of INSERT/SELECT
will be great welcome!

Wbr,
Alexandr

**Comment by dig12345** [comment]
The inserts happen in Unix TS but the time is not converted to UTC before
converting to Unix TS so its a Unix TS of local time. This is not correct
but works so long as homer box is in same local TZ as DB box. Issue happens
when Homer box is in local but DB is in UTC. Is there an easy way to
capture those Inserts so I can show you?

**Comment by adubovikov** [comment]
ah, now I understand the issue, let me find the description and a
workaround.

**Comment by dig12345** [comment]
Looks like they fixed it in MYSQL module maybe can integrate this?
https://kamailio.org/docs/modules/5.1.x/modules/db_mysql.html#idp41216076

**Comment by adubovikov** [comment]
yes, please set the param - it should solve the issue.

3.2. server_timezone (integer)

Control if kamailio convers a time to string using the local timezone or if
MySQL will convert it using FROM_UNIXTIME. This option is useful if
kamailio and the database are configured for different timezones.

*Default value is 0 (use local conversion)*

*Example 1.2. Set server_timezone parameter*

...
modparam("db_mysql", "server_timezone", 1)

**Comment by dig12345** [comment]
When I tried it it did not affect the sipcapture inserts.

**Comment by adubovikov** [comment]
can you ngrep the inserts to DB ? port 3306

Wbr,
Alexandr
