### ISSUE TITLE
How to change the incoming port setting on Homer? After changing it, it doesn't work anymore.

### ISSUE THREAD

**Issue by ciscospirit** [sipcapture/homer#208]
Hello,

i run into a problem with my Homer 5.0.5 configuration.
As I installed Homer many months ago, I define port 5060 as port for recieving data from Captagent, HEP and RTP:Engine.

Now i wanted to change the port to 9060 for better traffic splitting on my agents and changed the port in the agent configs as well in the kamailio config file on homer (/usr/local/etc/kamailio/kamailio.cfg).

In Kamailio.cfg i switch port=5060 to port=9060 and after that I did a reboot of the homer server.
BTW: On Homer there is version: kamailio 4.4.0-dev6 (x86_64/linux) 4d122e installed.

to check if homer is recieving data from the agents i execute ngrep on port 9060 and define also my primary agent ip adress on my homer server.

`ngrep -W byline port 9060 and host 1x.1x.1x.10`

after executing this comand, i see a lot of sip & hep traffic coming to my homer server, so the captagent, hep and rtp:engine settings are valid and sending data to my homer server, but if i look into the homer webinterface, i can't see any data there...

i also checked the log files and found just this ERROR message inside:

```
# cat /var/log/kamailio.log
Feb  8 09:08:53 homer /usr/local/sbin/kamailio[834]: ERROR: sipcapture [hep.c:86]: hep_msg_received(): ERROR: sipcapture:hep_msg_received: not supported version or bad length: v:[79] l:[80]
```

but i didn't change any other setting like the port, so I have no idea why this message appears and also no idea, why it is not working.

it would be nice if anybody can help me out of this problem.
Thank you!

**Comment by adubovikov** [comment]
please check the listening param in the kamailio.cfg

**Comment by ciscospirit** [comment]
Hello,

i have done this, cause there i changed the port valua from 5060 to 9060...

this are the options, but first one is commented out.

```
/* uncomment and configure the following line if you want Kamailio to
   bind on a specific interface/port/proto (default bind on all available) */
#listen=udp:10.0.0.10:5060

/* port to listen to
 * - can be specified more than once if needed to listen on many ports */
port=9060
```

i can't see there any other values with port 5060 to change to 9060

**Comment by adubovikov** [comment]
does it kamailio listen on 9060 ?
please check it with lsof

**Comment by ciscospirit** [comment]
`kamailio    740     kamailio    4u  IPv4   12306      0t0  UDP *:sip
kamailio    834     kamailio    4u  IPv4   12306      0t0  UDP *:sip
kamailio    837     kamailio    4u  IPv4   12306      0t0  UDP *:sip
kamailio    838     kamailio    4u  IPv4   12306      0t0  UDP *:sip
kamailio    839     kamailio    4u  IPv4   12306      0t0  UDP *:sip
kamailio    840     kamailio    4u  IPv4   12306      0t0  UDP *:sip
kamailio    841     kamailio    4u  IPv4   12306      0t0  UDP *:sip
kamailio    842     kamailio    4u  IPv4   12306      0t0  UDP *:sip
kamailio    843     kamailio    4u  IPv4   12306      0t0  UDP *:sip
kamailio    843     kamailio    9u  IPv4   12325      0t0  TCP localhost:54636->localhost:mysql (ESTABLISHED)`

**Comment by ciscospirit** [comment]
it looks like that kamailio is still listening on port 5060 and NOT at port 9060.
where can i change this?

**Comment by adubovikov** [comment]
please use listen vs port

**Comment by ciscospirit** [comment]
what u mean?

**Comment by adubovikov** [comment]
in your case:

listen=udp:10.0.0.10:9060 <http://10.0.0.10:5060/>
#port=9060

**Comment by ciscospirit** [comment]
i also tried this and restart kamailio... but not change...

listen=udp:homerIP:9060

**Comment by adubovikov** [comment]
please check if you real stop kamailio and restart it

this you can do by ptree or ps aux

**Comment by ciscospirit** [comment]
i also did a reboot of the homer server now and same behavior... maybe this setting is somewhere else defined?

**Comment by ciscospirit** [comment]
found the problem!

there is another kamailio-sipcapture.cfg file installed... i always edited the normal kamailio config file and not the special one... 

/usr/local/etc/kamailio/kamailio-sipcapture.cfg

**Comment by ciscospirit** [comment]
aaah i found the problem:

```
root@homer:~# ps aux | grep kamailio
kamailio  1002  0.0  0.1 157644 11292 ?        S    22:01   0:00 /usr/local/sbin/kamailio -f /usr/local/etc/kamailio/kamailio-sipcapture.cfg -P /var/run/kamailio/kamailio.pid -m 64 -M 8 -u kamailio -g kamailio
```

there is a custom kamailio-sipcapture.cfg file in which the port is defined:

```
#!substdef "!HOMER_LISTEN_PROTO!udp!g"
#!substdef "!HOMER_LISTEN_IF!0.0.0.0!g"
#!substdef "!HOMER_LISTEN_PORT!9060!g"
```

i changed the port there and now kamailio listen to 9060

**Comment by lmangani** [comment]
If you are using Kamailio with the templated config, its at the beginning of the file declared.
Grep your file for "5060" and find where precisely.
