### ISSUE TITLE
Homer-Docker with external MySQL doesn't work.

### ISSUE THREAD

**Issue by shaunbro** [sipcapture/homer#212]
Document says to do something like this 

--Quote--
docker run -tid --name homer5 -p 80:80 -p 9060:9060/udp sipcapture/homer-docker --dbhost 10.0.0.1 --dbuser homer_user -dbpass homer_password
--

files like 

- configuration.php

- rotation.ini

 do not get passed these values, although the run script seems to attempt this for at least the rotation file.  Additionally the "run.sh" script attempts to use root to create and initialise the db tables (this is not passed either using the above example)

**Comment by lmangani** [comment]
@shaunbro please open this in homer-docker
You need to look into the multi-container setup to achieve your purpose elegantly IMHO
