### ISSUE TITLE
Fresh install error with homer-config.git

### ISSUE THREAD

**Issue by oirtel** [sipcapture/homer#215]
I've tried to install Homer but here seems to be an error in line 183 of homer_installer.sh

"git clone --depth 1 https://github.com/QXIP/homer-config.git homer-config"

When the install script tries to execute that line, it doesn't find the homer-config.git
I've checked that it no longer exists at https://github.com/QXIP/

**Comment by lmangani** [comment]
@oirtel this was already patched. please resync the repo
