### ISSUE TITLE
sipgrep is not showing RTCP stats

### ISSUE THREAD

**Issue by kisienya** [sipcapture/homer#218]
Much appreciate this tool.

I have configured my Asterisk according to
https://github.com/sipcapture/homer/wiki/Examples%3A-Asterisk

SIP Signaling works correctly but there are no RTCP STATS when I run sipgrep.

In essence I am not getting quality of service stats.

Kindly assist.

Regards

**Comment by lmangani** [comment]
Not sure what sipgrep has to do with this.... Are you using ```chan_pjsip``` in Asterisk, as required to perform RTCP correlation?

**Comment by kisienya** [comment]
Thanks for the reply 
Yes I am using pjsip.
I need to use sipgrep as HEP3 capture agent and forward packets (especially QOS stats) to a pcap file for analysis.

**Comment by lmangani** [comment]
You should use the built-in functionality in Asterisk to send both SIP and RTCP. There is no need for sipgrep. If you cannot use Asterisk's built in HEP agent, then you need to use Captagent, which features RTCP capture in a similar fashion.

**Comment by kisienya** [comment]
Thanks I will be working on it
