### ISSUE TITLE
not rotating rtcp_capture

### ISSUE THREAD

**Issue by andycol** [sipcapture/homer#219]
Hi Guys

So daily when the rotation script runs it only rotates sip_capture_call_$date
it doesnt do the same for rtcp_capture_$date

**Comment by adubovikov** [comment]
drop the old rtcp_capture and change the param
https://github.com/sipcapture/homer-api/blob/master/scripts/rotation.ini#L33
to rtcp_capture

**Comment by andycol** [comment]
mine is set that way already
http://pasteboard.co/RbCm3v7OQ.png

**Comment by adubovikov** [comment]
sorry, does it work for you or not ?

**Comment by andycol** [comment]
no it does not work :(

**Comment by adubovikov** [comment]
I hope you have changed in the DATA_ROTATION as well

https://github.com/sipcapture/homer-api/blob/master/scripts/rotation.ini#L22

**Comment by andycol** [comment]
yes i have

![image](https://cloud.githubusercontent.com/assets/13945173/24604800/9e0b644e-1866-11e7-9861-6b3f66383d43.png)

**Comment by adubovikov** [comment]
then it should works, I don't see any reason why it should not

https://github.com/sipcapture/homer-api/blob/master/scripts/homer_mysql_rotate.pl#L248-L277

**Comment by andycol** [comment]
no still doesnt
see my tables below

+-----------------------------------+
| Tables_in_homer_data              |
+-----------------------------------+
| isup_capture_all_20170329         |
| isup_capture_all_20170330         |
| isup_capture_all_20170331         |
| isup_capture_all_20170401         |
| isup_capture_all_20170402         |
| isup_capture_all_20170403         |
| isup_capture_all_20170404         |
| isup_capture_all_20170405         |
| logs_capture                      |
| report_capture                    |
| rtcp_capture                      |
| rtcp_capture_all_20170216         |
| rtcp_capture_all_20170329         |
| sip_capture_call_20170329         |
| sip_capture_call_20170330         |
| sip_capture_call_20170331         |
| sip_capture_call_20170401         |
| sip_capture_call_20170402         |
| sip_capture_call_20170403         |
| sip_capture_call_20170404         |
| sip_capture_call_20170405         |
| sip_capture_registration_20170329 |
| sip_capture_registration_20170330 |
| sip_capture_registration_20170331 |
| sip_capture_registration_20170401 |
| sip_capture_registration_20170402 |
| sip_capture_registration_20170403 |
| sip_capture_registration_20170404 |
| sip_capture_registration_20170405 |
| sip_capture_rest_20170329         |
| sip_capture_rest_20170330         |
| sip_capture_rest_20170331         |
| sip_capture_rest_20170401         |
| sip_capture_rest_20170402         |
| sip_capture_rest_20170403         |
| sip_capture_rest_20170404         |
| sip_capture_rest_20170405         |
| webrtc_capture                    |
| webrtc_capture_all_20170329       |
| webrtc_capture_all_20170330       |
| webrtc_capture_all_20170331       |
| webrtc_capture_all_20170401       |
| webrtc_capture_all_20170402       |
| webrtc_capture_all_20170403       |
| webrtc_capture_all_20170404       |
| webrtc_capture_all_20170405       |
+-----------------------------------+

**Comment by adubovikov** [comment]
so, as I said, the tables has been created ;-)

but, immediately after they has been deleted :-/ 

the fix is here:

https://github.com/sipcapture/homer-api/commit/86115c889135c5fa2397ac9801ce1cfd15fd03e7

please check and confirm.

Thank you!

Wbr,
Alexandr

**Comment by andycol** [comment]
thanks all is working now :)

**Comment by Rico29** [comment]
Hello,
Got exactly the same problem on a fresh (manual) install.
fix sipcapture/homer-api@86115c8 is in my release.
rtcp_capture table does not rotate
any tip please ?

**Comment by adubovikov** [comment]
Please show your rotation.ini

**Comment by Rico29** [comment]
```
root@sipcapture:/opt/homer# cat rotation.ini
#Rotation parameters

[MYSQL]
    user = homer_user
    password = rmLWYs2AIJjFdL5V
    host = localhost
    port = 3306
    usesocket = 0
    socket = /var/run/mysqld/mysqld.sock
    db_data = homer_data
    db_stats = homer_statistic
    # Extra param
    newtables = 2 # Create new tables or partitions for next 2 days
    engine = InnoDB #MyISAM or InnoDB
    compress=ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8

[DATA_TABLE_ROTATION]
    #how long data keeps
    sip_capture_call = 10 #days
    sip_capture_registration = 10 # 10 days
    sip_capture_rest = 10 # 10 days
    rtcp_capture = 10 # days
    logs_capture = 10 # days
    report_capture = 10 # days
    webrtc_capture_all = 10 # days
    isup_capture_all = 10

[DATA_TABLE_STEP]
    # 0 - Day, 1 - Hour, 2 - 30 Minutes, 3 - 15 Minutes
    sip_capture_call = 0
    sip_capture_registration = 0
    sip_capture_rest = 0
    rtcp_capture = 0
    logs_capture = 0
    report_capture = 0
    webrtc_capture_all = 0
    isup_capture_all = 0

[DROP_OLD_PARTITIONS]
    # Remove partitions older than $seconds
    # Ignored if zero
    sip_capture_call = 0
    sip_capture_registration = 0
    sip_capture_rest = 0
    rtcp_capture = 0
    logs_capture = 0
    report_capture = 0
    isup_capture_all = 0
    webrtc_capture_all = 0

[STATS_TABLE_ROTATION]
    stats_ip = 20 # days
    stats_geo = 20 # days
    alarm_data = 10 # days
    stats_method = 10 #  days
    stats_useragent = 20 # days

[STATS_TABLE_STEP]
    #0 - Day, 1 - Hour, 2 - 30 Minutes, 3 - 15 Minutes
    stats_ip = 0
    stats_geo = 0
    alarm_data = 0
    stats_method = 0
    stats_useragent = 0

[SYSTEM]
    debug = 1
    exec =  1

[MSG_TABLE_SIZE]
    #characters
    sip_capture_call = 1500
    isup_capture_all = 3000
    webrtc_capture_all = 3000

```

Just found in homer_mysql_rotate.pl line 216 : 
-    my $is_rtcp = $table=~/^rtcp_capture_all/;
+    my $is_rtcp = $table=~/^rtcp_capture/;

**Comment by adubovikov** [comment]
look, I have added new block to the rotation.ini. Please download the last version of the script and config and try again. Thank you!

https://github.com/sipcapture/homer-api/commit/86dd2bb3233a3e42677dfd96d17293406c9fe7bc

**Comment by Rico29** [comment]
Part of the problem is resolved :  new rtpc_capture_<date> are created every day. But they're still empty, because all records are written in "rtcp_capture" table instead of "rtcp_capture_<date of the day>".

Any idea why ?

**Comment by adubovikov** [comment]
Because for this you have to upgrade kamailio to version 5 and use event
capture socket scenario.

Wbr,
Alexandr

On 7 Jun 2017 09:11, "Rico29" <notifications@github.com> wrote:

Part of the problem is resolved : new rtpc_capture_ are created every day.
But they're still empty, because all records are written in "rtcp_capture"
table instead of "rtcp_capture_".

Any idea why ?

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/sipcapture/homer/issues/219#issuecomment-306707343>,
or mute
the thread

**Comment by Rico29** [comment]
thanks Alexandr, I upgraded kamailio to 5.0.1
Any doc about "event capture socket scenario" ?

**Comment by adubovikov** [comment]
sure
take this config:
https://github.com/sipcapture/homer-config/blob/master/sipcapture/sipcapture.kamailio5

at line 906 is the event_route for capture, but just change the mysql user and password and it should be fine!

**Comment by Rico29** [comment]
OK, now I understand !

I've enabled some xlog debug in kamailio and: 
everything seems to work fine when using HEP CHUNK Type: 5
when using HEP CHUNK Type: 1, I get errors like this : 

```
Jun  7 12:40:04 sipcapture homer[8190]: ERROR: <script>: HEP Request!
Jun  7 12:40:04 sipcapture homer[8190]: ERROR: <script>: HEP CHUNK Type: 1
Jun  7 12:40:04 sipcapture homer[8190]: ERROR: <core> [core/parser/parse_fline.c:257]: parse_first_line(): parse_first_line: bad message (offset: 0)
Jun  7 12:40:04 sipcapture homer[8190]: ERROR: <core> [core/parser/msg_parser.c:671]: parse_msg(): ERROR: parse_msg: message=<HEP3#002u>
```

Trying to fix it

**Comment by adubovikov** [comment]
try to set HEP type 100, this is for logs and I will add the block for xlog as well...

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-config/commit/84af4e849f2346122c1ae3e63556f99d16b2ff02

**Comment by Rico29** [comment]
still have the same errors with your patch :(

**Comment by adubovikov** [comment]
how you send xlog to homer ?

**Comment by Rico29** [comment]
I don't understand your question. error log is kamailio's one, so I guess there's nothing related to homer at this point...?

**Comment by adubovikov** [comment]
sorry, I though you try send xlog to homer. 
Do you have SIP messages in the sip_capture tables ?

try to disable corelog just to avoid HEP parsing.

https://www.kamailio.org/wiki/cookbooks/5.0.x/core#corelog

**Comment by Rico29** [comment]
no problem !
Messages in sip_capture_* tables are OK. I've made a test call, and I can find the rows related to my call (with 'correlation_id field) in rtcp_capture_20170607 table.

So this part seems to work as expected, but two problem remains : 
- setting corelog / debug to -5 still display errors in logfile
- qos reports in homer is empty (I think it tries to look in rtcp_capture table instead of rtcp_capture_<%Y%m%d>)

**Comment by Rico29** [comment]
got it, I have to get rtcp_capture_all_* tables

**Comment by Rico29** [comment]
Hi Alexandr,
Rotation seems to be working as expected now, do you want me to open an issue for kamailio error logs ?

**Comment by adubovikov** [comment]
@Rico29 normally this is issue for @kamailio project, but I strongly recommend before play a bit with corelog parameter and see i it will help, because base on this information it should not write anything into log:

https://github.com/kamailio/kamailio/blob/master/src/core/parser/parse_fline.c#L257

so, debug = 1, corelog = 4;
