### ISSUE TITLE
Problem to use homer 5 

### ISSUE THREAD

**Issue by barto95100** [sipcapture/homer#221]
HI,

I have Serveur Debian 8 fresh install and homer5 is installed by script

and 

I have an other serveur with 2 NIC (ETH0 and ETH1) the ETH1 is received the mirroring port of my cisco 2960

bI start de kamailio on 1st server and Captagent on 2nd Server

But nothing to do ...

do you have a complete how to to install and test your solution ? 

I work for an ISP VOIP in French and I test your Solution for work in production ASAP :)

Excuse my bad english :D

**Comment by lmangani** [comment]
The issue could be anywhere in the configuration, we can't tell with the provided details alone.
If you need professional assistance for a production setup ASAP please email support@sipcapture.org

**Comment by adubovikov** [comment]
anyway, please use wiki as well:
https://github.com/sipcapture/homer/wiki

**Comment by barto95100** [comment]
Ok I send you a email to explain ma network 

Thank you for your help guys :)
