### ISSUE TITLE
Kubernetes / GKE deployments?

### ISSUE THREAD

**Issue by allandrick** [sipcapture/homer#222]
Hi,

I am wondering if anyone has successfully deployed sipcapture/homer-docker in Google Cloud Platform Container Engine (GKE) (Kubernetes)?

I am a novice and had a crack at it, failed dismally :-)

I do have it running nicely on my Mac using the docker-compose instructions so it shouldn't be a huge leap to get it running in GKE - but clearly I am lacking some certain skills ;-)

Cheers

Leigh

**Comment by lmangani** [comment]
Yessir! I've been running the all-in-one container in Kubernetes for some time without issues, in terms of bigger and better plans our local docker hero @dougbtv is working on a branch here: https://github.com/dougbtv/homer-docker/tree/k8s

**Comment by dougbtv** [comment]
Haha -- thanks for the kind words Lorenzo! Leigh, I do have a Kubernetes
deployment of Homer under work. I'm looking to integrate it into another
project, and it's a keystone for that project. I have a couple more things
to complete there until I can focus more effort on the Homer side of it,
but, it won't be too long.

Feel free to track that project / branch of my homer-docker fork -- and if
you'd like to contribute at all, I'd happily collab and happy to take some
input, too.

-Doug

**Comment by allandrick** [comment]
That's awesome!  I'm playing with it locally on my laptop's docker for now - will keep an eye out and see how I can help.

**Comment by dougbtv** [comment]
Hey @allandrick -- I've got a working deploy of Homer on Kubernetes. It's still in need of getting some more usage cycles before it's totally ready for prime time, but, it has all the gears turning.

I documented it up @ http://dougbtv.com/nfvpe/2017/04/20/homer-kubernetes/

**Comment by allandrick** [comment]
Thank you @dougbtv!
