### ISSUE TITLE
QOS stats blank

### ISSUE THREAD

**Issue by mase2hot** [sipcapture/homer#223]
Hello

I have Homer 5.05 and the below screenshot when I go to QOS stats. Data is in the table and calls that dont have data say stats unavailable which is correct. But for ones with data I get the below. I'm also missing the RTCP stats section totally.

Thanks

![capture](https://cloud.githubusercontent.com/assets/3533442/24903100/55e05faa-1ea4-11e7-8c30-36586932b0d5.PNG)

**Comment by lmangani** [comment]
What happens when you select ```packets``` from the list of metrics? Is anything displayed?

**Comment by mase2hot** [comment]
Nothing is displayed , well I get the legend colour of it but not data. This is same for jitter and packetloss

**Comment by mase2hot** [comment]
![capture2](https://cloud.githubusercontent.com/assets/3533442/24904898/ecc65adc-1ea9-11e7-8d7a-75f72db1bf49.PNG)

**Comment by mase2hot** [comment]
OK I have gone into developer mode in chrome and when I click on the call it says "no rtcp stats", but it must be finding something. As previously it said top right not statistics available and now thats gone.

**Comment by lmangani** [comment]
You should rather look at the Network/API response for the QoS data which might be at fault here.
I'm not sure I understand the second part of the comment about "top right not statistics" could you clarify?

**Comment by mase2hot** [comment]
Where it says QOS metrics chart. On calls with no QOS it says stats unavailable. I'm think that possible may for some reason the json is not saving correctly and the chart can not read it. Also not sure why the rctp statics box is missing.

msg: { "sender_information":{"ntp_timestamp_sec":1818138844,"ntp_timestamp_usec":2292540800,"octets":380000,"rtp_timestamp":951031049, "packets":2375},"ssrc":317831168,"type":200, "report_blocks":[{"source_ssrc":1426819901,"highest_seq_no":58371,"fraction_lost":0,"ia_jitter":0,"packets_lost":0,"lsr":0,"dlsr":0}],"report_count":1,"sdes_ssrc":317831168,"sdes_chunk_ssrc":17254213,"sdes_information": [ {"type":0,"text":"ñ¸"}],"sdes_report_count":1}

**Comment by lmangani** [comment]
We need to see the statistics response rather than the single messages to understand.
Please outline your full setup/pipeline and how you're capturing RTCP.

**Comment by mase2hot** [comment]
![capture3](https://cloud.githubusercontent.com/assets/3533442/24949544/e7105ca2-1f65-11e7-9433-95e86f98cfae.PNG)

**Comment by mase2hot** [comment]
Seems to be some data in there.

OK so current setup / call flow. I have:

Provider > SBC (Kamailio) > Freeswitch > Provider

I have a separate Kamailio server running homer and currently I only have captagent on Freeswitch. I'm using the standalone version and not the Freeswitch built in version.

**Comment by mase2hot** [comment]
Do you know why I'm missing the RCTP Stats box? I'm not sure what files handle this for me to check with the github version. Although this is a new install of Homer, less than a week old.

**Comment by mase2hot** [comment]
any ideas?

**Comment by adubovikov** [comment]
Can you please show us the raw data of rtcp packets?

**Comment by mase2hot** [comment]
sorry were do I get this from?

**Comment by adubovikov** [comment]
In the rtcp_capture table.

18 апр. 2017 г. 12:39 пользователь "mase2hot" <notifications@github.com>
написал:

**Comment by mase2hot** [comment]
Here is example:

msg: { "sender_information":{"ntp_timestamp_sec":521246428,"ntp_timestamp_usec":1520369921,"octets":120000,"rtp_timestamp":805676737, "packets":750},"ssrc":322548736,"type":200, "report_blocks":[{"source_ssrc":1022354911,"highest_seq_no":49277,"fraction_lost":0,"ia_jitter":0,"packets_lost":0,"lsr":0,"dlsr":0}],"report_count":1,"sdes_ssrc":322548736,"sdes_chunk_ssrc":17254213,"sdes_information": [ {"type":0,"text":"9´"}],"sdes_report_count":1}

**Comment by adubovikov** [comment]
Do u have only one report per call or multiple ?

**Comment by mase2hot** [comment]
multiple see latest example:

 msg: { "sender_information":{"ntp_timestamp_sec":2056888540,"ntp_timestamp_usec":3440051715,"octets":40000,"rtp_timestamp":807258890, "packets":250},"ssrc":307495936,"type":200, "report_blocks":[{"source_ssrc":1319462005,"highest_seq_no":59586,"fraction_lost":0,"ia_jitter":0,"packets_lost":0,"lsr":0,"dlsr":0}],"report_count":1,"sdes_ssrc":307495936,"sdes_chunk_ssrc":17254213,"sdes_information": [ {"type":0,"text":"T"}],"sdes_report_count":1}


 msg: { "sender_information":{"ntp_timestamp_sec":2123997404,"ntp_timestamp_usec":3440051843,"octets":76000,"rtp_timestamp":3500788490, "packets":475},"ssrc":307495936,"type":200, "report_blocks":[{"source_ssrc":1319462005,"highest_seq_no":59811,"fraction_lost":0,"ia_jitter":0,"packets_lost":0,"lsr":0,"dlsr":0}],"report_count":1,"sdes_ssrc":307495936,"sdes_chunk_ssrc":17254213,"sdes_information": [ {"type":0,"text":"T"}],"sdes_report_count":1}
2 rows in set (0.00 sec)

**Comment by mase2hot** [comment]
does this look normal?

**Comment by adubovikov** [comment]
i looks normal, but it will be very nice if you can dump all rtcp record for a one call and send the sql dump to us. Please use support at sipcapture.org for this. We will check if anything wrong...

**Comment by mase2hot** [comment]
ok thanks

**Comment by vtzan** [comment]
Dear Team,

I have installed yesterday latest homer and for some reason qos stats now shows blank. This was working fine for 1 day but suddenly this stopped working.

The RTCP data exists correctly on DB. And I can see the data using mysql select:

select * from rtcp_capture WHERE correlation_id like 'callid' ORDER BY id desc;

chrome console while selecting called shows "no rtcp stats"

I can email you any dump or debug data you request.
![no-rtcp-stats](https://user-images.githubusercontent.com/1777931/28241770-9858b932-69a3-11e7-8b2a-99e38de85d63.png)

thank you in advance

**Comment by adubovikov** [comment]
be sure that your rotation script works correct!

**Comment by vtzan** [comment]
Hi!,

/opt/homer/homer_mysql_rotate runs without issues.

what I have found is that rotation_kamailio5.ini had 
[MYSQL]
    user = homer_user
    password = homer_password

and I changed them to the correct ones.

All the RTCP data are in the table rtcp_capture and the system creates the rotation table every day. For example rtcp_capture_all_20170216 table is created from cron but is has not data in it.

althought on web UI QoS Metrics Chart is still empty for each callid... and chrome dev console say no rtcp data. All other Homer web UI functions and mysql rotations seems to work correctly. For example table sip_capture_call_20170713 includes all proper data for this date.

thank you in advance

**Comment by negbie** [comment]
Please show us your  homer-api/api/preference.php
Could you change this inside the preference.php

define('RTCP_TABLE_PARTITION', 0);
to
define('RTCP_TABLE_PARTITION', 1);

**Comment by vtzan** [comment]
preference.php has define('RTCP_TABLE_PARTITION', 0); as per default installtion.

I have tried also with 1 but without any luck on the web UI chart. 
The rtcp data is on the base table (rtcp_capture) anyway and not on the rotated one.

**Comment by vtzan** [comment]
here is the preference.php file --> https://pastebin.com/4TfN8SXn

**Comment by negbie** [comment]
Hmm ok could you try one more thing:

Inside your kamailio.cfg
Under event_route[sipcapture:request] {

if($hep(0x00b) == 5){
    $var(utc) = $utimef(%Y%m%d); 
    $var(table) = "rtcp_capture_all_" + $var(utc);
    report_capture("$var(table)", "$hep(0x011)", "$hep(0x00f)");
}

**Comment by adubovikov** [comment]
if you want store data to rtcp_capture_YYYYMMDD, you have to use kamailio 5 and different config for this
if you still use kamailio 4, please change rotation of rtcp_capture to the partition mode and not daily mode

kamailio4 and old way of rtcp_capture ->
https://github.com/sipcapture/homer-api/blob/master/scripts/mysql/rotation.ini#L43

kamailio5 ->
https://github.com/sipcapture/homer-api/blob/master/scripts/mysql/rotation_kamailio5.ini

**Comment by negbie** [comment]
I asumed you already using the config for kamailio 5. If not take a look here inside the event_route[sipcapture:request] and you should get the idea:

https://github.com/sipcapture/homer-config/blob/master/sipcapture/sipcapture.kamailio5

**Comment by vtzan** [comment]
Sorry for not mentioning that the installation was made using the automated script.
Here is the kamailio config I am using --> https://pastebin.com/Gxcwiqhc version 4.3

**Comment by negbie** [comment]
I would suggest you to upgrade kamailio. Since v5 is in the repos its not a big deal.

**Comment by vtzan** [comment]
Well, thank you for your replies.

1)I have upgraded to kamailio 5
kamailio -v
version: kamailio 5.1.0-dev4 (x86_64/linux) 
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown 
compiled on 13:19:03 Jul 16 2017 with gcc 4.9.2

2)used the kamailio v5 config
https://github.com/sipcapture/homer-config/blob/master/sipcapture/sipcapture.kamailio5

3)used the v5 rotation.ini
https://github.com/sipcapture/homer-api/blob/master/scripts/mysql/rotation_kamailio5.ini

4) run the homer_rotate script first. (with some warnings but it seems to worked (?) btw)
root@homer:/opt/homer# ./homer_rotate 
Use of uninitialized value $partstep in array element at ./homer_mysql_rotate.pl line 255.
Use of uninitialized value $partstep in array element at ./homer_mysql_rotate.pl line 256.
Use of uninitialized value $partstep in numeric gt (>) at ./homer_mysql_rotate.pl line 509.
Use of uninitialized value $partstep in numeric gt (>) at ./homer_mysql_rotate.pl line 509.

5) sip traces on UI are working fine just like before

6)
kamailio saves RTCP data correctly to DB which i verified with 
mysql> select * from rtcp_capture_all_20170716
also kamailio doesn't report anything wrong on syslog which means upgrade went fine.

changed the partition variable of /var/www/html/homer/api/preferences.php from  define('RTCP_TABLE_PARTITION', 0);  to ----->
define('RTCP_TABLE_PARTITION', 1);

**Result:** QoS Metrics Chart are still BLANK with chrome dev console still saying "no rtcp stats"

thank you in advance

**Comment by adubovikov** [comment]
please activate syslog in the preferences.php and check the sql query that you generate to get information from rtcp tables.

**Comment by vtzan** [comment]
the syslog showed all the queries.
the rtcp one:

SELECT *,'single' as dbnode FROM rtcp_capture_all_20170716  WHERE (date BETWEEN FROM_UNIXTIME(1500215596) AND FROM_UNIXTIME(1500216319)) AND ( ( correlation_id = 'isbc9d9mcfm98mdgmpde8abapg8hme7hhg5f@*******************' OR correlation_id = 'isbc9d9mcfm98mdgmpde8abapg8hme7hhg5f@*******************_b2b-1' OR correlation_id = 'isbc9d9mcfm98mdgmpde8abapg8hme7hhg5f@*******************_b2b-' OR correlation_id = 'isbc9d9mcfm98mdgmpde8abapg8hme7hhg5f@*******************' )) LIMIT 100

whole syslog result is here: https://pastebin.com/XJRhr5Rd

in the logs there are some "from_tag,#012to_user," fields. Are those correct?

thank you

**Comment by adubovikov** [comment]
now check if the query give you any results

**Comment by vtzan** [comment]
they give me the correct results sorry for not mention it.

**Comment by adubovikov** [comment]
and any errors in php during parsing/working on this result ?

**Comment by vtzan** [comment]
mysql result:

![mysql-rtcp-results](https://user-images.githubusercontent.com/1777931/28248746-739afd62-6a52-11e7-91b9-b3a1f7926fed.png)

And yes I see some php errors though ...

php errors ---> https://pastebin.com/JJZ6ymGJ

thank you

**Comment by adubovikov** [comment]
can you please make print_r or similar before the function return array, to be sure that the array is not empty:

https://github.com/sipcapture/homer-api/blob/master/api/RestApi/Report.php#L202

need check if this is error in json decoding because you have wrong characters or wrong extraction.

**Comment by negbie** [comment]
Could you paste this inside Report.php around line 507?

 if(SYSLOG_ENABLE == 1) syslog(LOG_WARNING,print_r($data, TRUE));

Output in log should be something like this:
https://pastebin.com/kE6ViEW0

**Comment by vtzan** [comment]
thank you for your reply.

Here is the output --> https://pastebin.com/fKMhFJfP

**Comment by negbie** [comment]
I'm a litle bit confused about your table structure it should be

  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `micro_ts` bigint(18) NOT NULL DEFAULT '0',
  `correlation_id` varchar(256) NOT NULL DEFAULT '',
  `source_ip` varchar(60) NOT NULL DEFAULT '',
  `source_port` int(10) NOT NULL DEFAULT 0,
  `destination_ip` varchar(60) NOT NULL DEFAULT '',
  `destination_port` int(10) NOT NULL DEFAULT 0,
  `proto` int(5) NOT NULL DEFAULT 0,
  `family` int(1) DEFAULT NULL,
  `type` int(5) NOT NULL DEFAULT 0,
  `node` varchar(125) NOT NULL DEFAULT '',
  `msg` varchar(1500) NOT NULL DEFAULT '',

but yours is

  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `micro_ts` bigint(18) NOT NULL DEFAULT '0',
  `correlation_id` varchar(256) NOT NULL DEFAULT '',
  `source_ip` varchar(60) NOT NULL DEFAULT '',
  `source_port` int(10) NOT NULL DEFAULT 0,
  `destination_ip` varchar(60) NOT NULL DEFAULT '',
  `destination_port` int(10) NOT NULL DEFAULT 0,
  `proto` int(5) NOT NULL DEFAULT 0,
  `family` int(1) DEFAULT NULL,
  `type` int(5) NOT NULL DEFAULT 0,
  `node` varchar(125) NOT NULL DEFAULT '',
  `msg` varchar(1500) NOT NULL DEFAULT '',
  `dbnode` varchar(125) NOT NULL DEFAULT '',

**Comment by vtzan** [comment]
I used the installation script for installing homer stuff....

the schema located on my server (and on database) on /usr/src/homer-api/sql/mysql/schema_data.sql is the same with the one on git clone https://github.com/sipcapture/homer-api.git

So the question is where is the correct schema located?

thank you

**Comment by negbie** [comment]
Thats the right location but i was wondering why my table looks like this:

homer_user@homer_data> select * from rtcp_capture_all_20170717 ORDER BY id DESC limit 1;
+---------+---------------------+------------------+-------------------+---------------+-------------+----------------+------------------+-------+--------+------+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id      | date                | micro_ts         | correlation_id    | source_ip     | source_port | destination_ip | destination_port | proto | family | type | node  | msg                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+---------+---------------------+------------------+-------------------+---------------+-------------+----------------+------------------+-------+--------+------+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 1614225 | 2017-07-17 14:34:13 | 1500295230642000 | 22AF5611@21bc334df | 192.168.1.1 |        6701 | 192.168.1.2  |            38065 |    17 |      3 |    5 | 24755 | { "sender_information":{"ntp_timestamp_sec":497,"ntp_timestamp_usec":4196183048,"octets":3983680,"rtp_timestamp":1848508679, "packets":24898},"ssrc":2112204491,"type":200,"report_count":1,"report_blocks":[{"source_ssrc":92474822,"highest_seq_no":26230,"fraction_lost":0,"ia_jitter":1,"packets_lost":0,"lsr":287468512,"dlsr":193462}],"sdes_ssrc":2112204491,"sdes_report_count":1,"sdes_information": [ {"sdes_chunk_ssrc":2484404491,"type":1,"text":"notset@nowhere.com"}] } |

**Comment by vtzan** [comment]
I just found that the QoS Table is working for outbound calls. The problem is with incoming calls only!!!! any idea? here is the output with QoS Table working ---> https://pastebin.com/eW0XWnwS

**Comment by negbie** [comment]
Could you give an example of both side by side?

**Comment by negbie** [comment]
It seems you have more than one b2bua (...-b2b_1_b2b-1) so mby you could check the output for those callid's

**Comment by vtzan** [comment]
on the incoming call i don't have b2b prefix at all. the call id is like this on the incoming call isbc91adoc19r9fq9eqfdc9e1radp09rbr8p@B.11.314.hostname.tld

on the outbound call the call id is: 7461cdef3aff3c7f767a2fca3d641a84@ipaddress:65060-b2b_1

preferences.php are default:
/* BLEG DETECTION */
define('BLEGDETECT', 1); /* always detect BLEG leg in CFLOW/PCAP*/
define('BLEGCID', "b2b"); /* options: x-cid, b2b */
define('BLEGTAIL', "_b2b-1"); /* session-ID correlation suffix, required for b2b mode */

should i change them for incoming call to show up the QoS Stats?

thank you

**Comment by negbie** [comment]
No don't change it. What do you get if you search for outbound calls without the _b2b-1 suffix?

**Comment by negbie** [comment]
Homer will apend itself the blegtail if you have defined BLEGCID as b2b. Take a look here:
https://github.com/sipcapture/homer-api/blob/master/api/RestApi/Report.php#L241

**Comment by negbie** [comment]
If you search for 5123123@1.1.1.1 homer will also look up 5123123@1.1.1.1 _b2b-1 for you.

**Comment by negbie** [comment]
Could you provide a sql query for both?

**Comment by vtzan** [comment]
working sql  --> https://pastebin.com/fzq2UhJr

non working sql --> https://pastebin.com/a5UV4A3m

**Comment by negbie** [comment]
Tried to reproduce your behaviour but no matter how i search as long as i have valid json data i see the rtcp stats

**Comment by vtzan** [comment]
Can I sent you mysqldump in private somehow?

**Comment by negbie** [comment]
Yes. How big is that dump. Mby its too big for email.

**Comment by negbie** [comment]
If its < 50mb you can send it to negbieme@posteo.de
Just some rtcp and matching sip data

**Comment by vtzan** [comment]
~500kb bz2 I have just emailed it to you. thank you in advance

**Comment by negbie** [comment]
Ok thank you. Since Lorenzo made it so easy to spin up a docker container and test things the solution is really simple and on the rtcp producer side.

Please have a look at the ntp_timestamp_sec json keys. Most of the time you have no valid unix timestamps here. I don't know why you have sometimes valid ones for outgoing calls but often they aren't valid even for outgoing calls. For example you have something like this:
"ntp_timestamp_sec":3
"ntp_timestamp_sec":5
"ntp_timestamp_sec":8

instead of valid one like this:
"ntp_timestamp_sec":1500290860
"ntp_timestamp_sec":1500290862
"ntp_timestamp_sec":1500290864

Test it by yourself and update some rows like
UPDATE rtcp_capture_all_20170717
SET msg = '{ "sender_information":{"ntp_timestamp_sec":1500290864 ....... PUT THE REST HERE"}] }'
WHERE id = 15;

**Comment by negbie** [comment]
With valid ntp timestamps everything looks normal. Here one example for a incoming call with updates ntp timestamps
![wrong_ntp](https://user-images.githubusercontent.com/20154956/28290735-e1ffdc96-6b47-11e7-9a85-7c5e68e47fc5.jpeg)

**Comment by vtzan** [comment]
The node that generates the data has ntp service running and time is correct. what should I do to fix this behavior? 

thank you

**Comment by negbie** [comment]
First use ngrep or tcpdump at the producer host to verify that i sends invalid unix timestamps. Look into the producer code and how it gets the time or open a issue/bug report for this program.

**Comment by negbie** [comment]
First use ngrep or tcpdump at the producer host to verify that i sends invalid unix timestamps. Look into the producer code and how it gets the time or open a issue/bug report for this program.

**Comment by vtzan** [comment]
Here is the ngrep from producer side --- > https://pastebin.com/TNTctVxD

I have verified that the same data are received from homer server using ngrep and also that kamailio receives those messages correctly and sends it to DB.

Finally I have verified that mysql has the same data too ----> https://pastebin.com/TpyGXKLq

Is there any possibility that there is a php compatibility issue? 
installed php packages ----> https://pastebin.com/0qG4wGv1

lsb_release -a
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.8 (jessie)
Release:	8.8
Codename:	jessie

Also Chrome Version is 58.0.3029.96 (64-bit)

what distro do you use for testing?

**Comment by vtzan** [comment]
the wrong timestamps that you saw on the DB dump maybe was before adding ntp few days ago... check timestamps for example on table rtcp_capture_all_20170717 I don't see any wrong ones there.

**Comment by negbie** [comment]
Hi, you can clearly see, that the timestamps are already broken at the producer side
{"ntp_timestamp_sec":2,
{"ntp_timestamp_sec":7
{"ntp_timestamp_sec":12,

Obviously you will find the same broken once in the DB. So this has nothing to do with homer, the distro or the php version.

Its simply your rtcp producer which is broken.

**Comment by vtzan** [comment]
ok understood now.
Just for the records I am using rtpengine 5.4.0.0+0~mr5.4.0.0. I will investigate further. 

thank you for your support so far.

**Comment by negbie** [comment]
Than the rtpengine repo would be the right place to open a isse or look into the code
https://github.com/sipwise/rtpengine/blob/mr5.4/daemon/homer.c

I use rtpengine 4.5.5 and the timestamps are correct.

**Comment by negbie** [comment]
Your welcome. Feel free to post your findings here. Mby it could help others with the same problem.

**Comment by vtzan** [comment]
thank you for the extra info on the version that works for you. I have replied on rtpengine case just now -> https://github.com/sipwise/rtpengine/issues/281 

I will try to see the diff of this file on you version.

**Comment by vtzan** [comment]
Finally I have verified with wireshark that the Vendor sends RTCP packets with **wrong** timestamp. This is the reason why in first time the problem was only on incoming calls. 

![rtcp](https://user-images.githubusercontent.com/1777931/28388747-608e90a8-6cdc-11e7-803d-58f7cc2c5918.png)

So the reason of this inconsistency was not homer or rtpengine. 
thank you all for your support on this case.

**Comment by negbie** [comment]
Nice to see that you went down the whole rabbit hole and finally found the root cause. Can you tell us the vendor?

**Comment by vtzan** [comment]
HUAWEI SBC

**Comment by adubovikov** [comment]
Eudaemon 2200 ?

**Comment by vtzan** [comment]
I am pretty sure its SE2900

**Comment by adubovikov** [comment]
good to know that nothing changed

**Comment by vtzan** [comment]
also good to know that you have seen similar behavior too with the same vendor.

**Comment by adubovikov** [comment]
Ok. thank you guys who helped to solve the issue!

**Comment by lpradovera** [comment]
Hey everybody! Sorry to necro this but I have no other ideas. If I have values like "ntp_timestamp_sec":2342954974 in the database (some time in 2044), it means they are getting sent wrong or parsed wrong, correct? As far as I can see they are ok in the Wireshark capture, however.
