### ISSUE TITLE
MySQL Query issue inserting data

### ISSUE THREAD

**Issue by goharahmed** [sipcapture/homer#224]
```
ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Data too long for column 'via_1_branch' at row 1 (1406)
ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query
```

Hi,
I'm just starting with Homer and I have almost all my grpahs showing up. I'm seeing the above mentioned error in my syslog since the start. 

I've couple of other questions/issues as well which I'll post later one (need mailing-list address, couldnt find it in main pages)

Thanks,
Gohar

**Comment by zapata010** [comment]
This indicates that data couldn't be inserted into sip_capture_call_YYYMMDD table due to exceeding length for column "via_1_branch". The default length for this column is 80.
- To check the schema for this table: 
> desc sip_capture_call_YYYMMDD (change YYYMMDD)
- To alter the length: 
> alter table sip_capture_call_YYYYMMDD modify msg via_1_branch(100);

If you're still getting such error after the above adjustments, you might need to try higher values with the alter statement.

**Comment by lmangani** [comment]
The column configuration is part the rotation and gets applied daily. The alter function is only ok for same-day modifications, for a permanent change file `homer_mysql_rotate.pl` needs to be adapted.

**Comment by aleczmw** [comment]
@lmangani 
add rotate.ini
[MSG_TABLE_SIZE]
    #characters
    sip_capture_call = 2500
    isup_capture_all = 3000
    webrtc_capture_all = 3000
    rtcp_capture_all = 1500

**Comment by aleczmw** [comment]
| node             | varchar(125)        | NO   |     |                   |                |
| msg              | varchar(2500)       | NO   |     |                   |                |
+------------------+---------------------+------+-----+-------------------+----------------+
46 rows in set (0.00 sec)

mysql> describe sip_capture_call_20180712;
