### ISSUE TITLE
B2BUA leg correlation

### ISSUE THREAD

**Issue by azigelman** [sipcapture/homer#225]
Hello, I work in communication, and we would like to start using sipcapture for our servers. 
Problem is that we are using B2BUA, and I can't manage to achieve leg correlation within the 2 call legs.
I have read and tried the options that you suggest for achieving this, but apparently, our sip messages are a bit different. 
Our only link between the two calls is an inserted header, (called X-HDAP-TraceId), which appears on one of the first messages of both legs.
For example:

> 
> U 
> INVITE sip:
> Record-Route: 
> Call-ID: 969b0be77d2c94b2a9f1667878a4f6ee@10.62.235.108.
> CSeq: 47 INVITE.
> From: 
> To: 
> Via: 
> Via: 
> Max-Forwards: 
> Contact:
> Content-Type: 
> Allow: 
> X-HDAP-AccountId:
> Remote-Party-ID: 
> X-HDAP-TraceId: 12216766131493206427110.
> User-Agent:
> Content-Length: 
> 
> 
> U 
> SIP/2.0 200 OK.
> Record-Route: 
> Via: SIP/2.0/UDP 
> From: "sipp" 
> To: 
> Call-ID: 10830-6136@10.71.18.232.
> CSeq: 4 INVITE.
> Max-Forwards: 98.
> Content-Type: application/sdp.
> Contact: 
> X-HDAP-TraceId: 12216766131493206427110.
> Server: 
> Content-Length: 
> 

Within the following restrictions, (we have been working this way for past years so changing the sip messages can get a bit problematic), is it possible to achieve leg correlation?

Thanks a lot!

**Comment by lmangani** [comment]
Hi Amit,
You can use any header for correlation as long as its consistently presented. 
Check our the wiki examples and try replace X-CID with your header: https://github.com/sipcapture/homer/wiki/Using-Homer-5#session-correlation

**Comment by azigelman** [comment]
Many thanks!
Just to clear a small misunderstanding for me,
when you say "consistently presented", do you mean that the header has to appear in all of the messages (of both call legs) that I want to be correlated?
So if it appears only on some 2 messages on the 2 different legs homer won't be able to make the link?

**Comment by lmangani** [comment]
It will - I meant at least once per session.

**Comment by lmangani** [comment]
Not sure about the second header, unless its used as well just do:
```
modparam("sipcapture", "callid_aleg_header", "X-HDAP-TraceId")
```

Don't forget to tell HOMER to use X-correlation in its settings:
```
define('BLEGCID', "x-cid");
```
