### ISSUE TITLE
Found Issue With CenOS 7 Quick Install Script

### ISSUE THREAD

**Issue by jvb187** [sipcapture/homer#226]
Hello,

I have found an issue with the latest install script on CentOS7 that was preventing me from logging into the web gui.  

In the schema_configuration.sql file that is loaded, you have the following code:

INSERT INTO `node` (`id`, `host`, `dbname`, `dbport`, `dbusername`, `dbpassword`, `dbtables`, `name`, `status`) VALUES
(1, '127.0.0.1', 'homer_data', '3306', 'homer_user', 'mysql_password', 'sip_capture', 'homer01', 1),
(21, '10.1.0.7', 'homer_data', '3306', 'homer_user', 'mysql_password', 'sip_capture', 'external', 1);

And then later on in the homer_install.sh file, you try to insert the node 1 again, but there is a primary key conflict because key 1 already exists.

This code:

mysql -u "$DB_USER" -p"$DB_PASS" homer_configuration -e "INSERT INTO node VALUES(1,'mysql','homer_data','3306','"$DB_USER"','"$DB_PASS"','sip_capture','node1', 1);"

gives this error in the script logs:

Creating Tables...
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1062 (23000) at line 1: Duplicate entry '1' for key 'PRIMARY'  <------------ HERE
Patching Homer configuration...

This was blocking me from logging into the web gui with the default credentials. Once I manually removed the first row that was inserted by the schema_configuration.sql, and then manually entered the row again using the proper user and password generated by the script, I was able to login without issue.

Thank you,
Jeremy

**Comment by jvb187** [comment]
Actually, once I restarted MySql I was no longer able to login.  It looks like per  SHOW VARIABLES LIKE 'validate_password%';  the validation rules are not compatible with the password that is set via the install script for CentOS 7:

mysql>  SHOW VARIABLES LIKE 'validate_password%';
+--------------------------------------+--------+
| Variable_name                        | Value  |
+--------------------------------------+--------+
| validate_password_check_user_name    | OFF    |
| validate_password_dictionary_file    |        |
| validate_password_length             | 8      |
| validate_password_mixed_case_count   | 1      |
| validate_password_number_count       | 1      |
| validate_password_policy             | MEDIUM |
| validate_password_special_char_count | 1      |
+--------------------------------------+--------+
7 rows in set (0.00 sec)

And therefore I see the following in the Apache error logs when I attempt to login:

[Wed Apr 26 17:27:15.431931 2017] [:error] [pid 2338] [client 192.168.247.14:51690] Array\n(\n    [0] => HY000\n    [1] => 1819\n    [2] => Your password does not satisfy the current policy requirements\n)\n, referer: http://192.168.247.20/

Once I manually created a user with a more complex password, I was able to login without issue.

Thanks,
Jeremy

**Comment by yumminova** [comment]
How do u manually create that user?
