### ISSUE TITLE
Blind SQL injection

### ISSUE THREAD

**Issue by barf** [sipcapture/homer#227]
Hello

There is a blind, time-based SQL injection vulnerability in the login form.

Sending the following JSON body in a POST request to /api/v1/session should be sufficient to reproduce:
`{"username":"admin","password":"foo'+(select*from(select(sleep(20)))a)+'"}`

**Comment by adubovikov** [comment]
IMHO it should be fixed here:
https://github.com/sipcapture/homer-api/commit/ed55fd27c1f3a41c161aef6cb19d0ef621344771

thank you for the report!!

**Comment by adubovikov** [comment]
looks like the bug has been fixed. If any additional input, please reopen!
