### ISSUE TITLE
B2BUA with prefix instead of suffix

### ISSUE THREAD

**Issue by rsanting** [sipcapture/homer#228]
We would like to use leg correlation in Call-Flow with a B2BUA prefix instead of a suffix. Is there a way to do this?

**Comment by negbie** [comment]
Have a look into my "Improve cleg handling" commit for homer-api. With that you should be able to introduce a prefix.

**Comment by lmangani** [comment]
@rsanting hey Rene' this this solve your scenario?

**Comment by lmangani** [comment]
@rsanting feel free to reopen if useful
