### ISSUE TITLE
Architecture questions about Captagent/Kamailo

### ISSUE THREAD

**Issue by Gourou85** [sipcapture/homer#230]
Hi folks,

I have some IP Phones and I would like to collect their RTCP-XR data. I configured it correctly as I see the data via tcpdump.

I setup a homer via the script provided on the wiki. Web UI access is ok. 
I configured and launch the captagent and it respond to rtcp-xr with a "200 OK".

But no data in the mysql nor anywhere by the way.

I wonder the requirement of Kamailo. As I understand what I found on the net Kamailo like Capagent listen to sip packets and rewrite them as HEP for pushing it in a database .

So do I really need it or just captagent will be sufficient ?

Thanks for the answer
G

**Comment by adubovikov** [comment]
in any scenarios you have to install kamailio as HEP collector.
