### ISSUE TITLE
Couple Questions

### ISSUE THREAD

**Issue by unridaz** [sipcapture/homer#232]
Hello,

Using Centos 7, and install script

I noted that my kamailio.cfg file was not populated with proper database username and password, I set this myself copying settings from configuration.php, is this expected?

Now that homer is installed, and have begun duplicating packets from my switch (using freeswitch), I noted that I am receiving a few errors from Kamailio. Not sure how to track down, or if its serious. I still notice packets being logged in the DB. My questions are, how to track down, and is this something which I should be concerned about?

Also, I have enabled HEPIPE on my switch, and am also receiving MOS scores etc!! Its great to have this feature, but I have noticed that a seemingly perfect call is reporting large packet loss. What is strange is that the longer the call goes, the less loss(%) is reported. I'm wondering if this has something to do with aforementioned Kamailio/DB issues. I was also reading somewhere that freeswitch also duplicates empty ping messages to Homer which can have problems being parsed by Kamailio. 

Thanks for your efforts!

**Comment by lmangani** [comment]
Hi @unridaz 

I think you're right, just patched the installer to hopefully correct this:
https://github.com/sipcapture/homer-installer/commit/3c44dad46828883c5efb0916a6a089870fb20864

Could you take it for a spin?

As of the parsing errors, its impossible to help without the exact log and possibly the packet causing it. More a Kamailio issue than a HOMER one.

As of HEPIPE, we just relay what Freeswtich sends. Mind where announcements are played, very often the sequence numbers change causing a false positive for packet loss. As per above, hard to tell without seeing the data behind this detection.

Hope this helps!

**Comment by lmangani** [comment]
Please comment to reopen if needed. Thanks for your report!
