### ISSUE TITLE
No SIP content in shared link

### ISSUE THREAD

**Issue by ciscospirit** [sipcapture/homer#233]
Hello,

if i share a homer capture link and open this link the sip message content is missing in the "shared" version.
if i open the trace directly in homer i see the content but if i open it over the "share" link i have no content there. just the time...

2017-06-09 19:16:58 +0200 : 176.123.55.22:5060 -> 176.123.55.10:5060

any idea?

**Comment by lmangani** [comment]
Indeed, we need to resync the shared view with fixes applied to the main view

**Comment by ciscospirit** [comment]
Hello,

is this already done?

**Comment by lmangani** [comment]
Sorry, All hands are on HOMER 7 so not unless someone wants to do a PR for 5. This won't be an issue there surely.
