### ISSUE TITLE
Homer Stopped working ,NO data in mysql and WEB homer ref#234

### ISSUE THREAD

**Issue by bharathg65** [sipcapture/homer#236]
HI ,
I have checked in Kamailio.log and getting below error , any one pls help me ;
Jun 16 11:14:51 localhost homer[1340]: ERROR: rtimer [rtimer_mod.c:164]: child_init(): failed to start timer routine as process
Jun 16 11:14:51 localhost homer[1340]: ERROR: <core> [sr_module.c:923]: init_mod_child(): Error while initializing module rtimer (//usr/lib/x86_64-linux-gnu/kamailio/modules/rtimer.so)
Jun 16 11:14:51 localhost homer[1340]: ERROR: <core> [main.c:1697]: main_loop(): error in init_child
Jun 16 11:14:51 localhost homer[1339]: ERROR: db_mysql [km_my_con.c:124]: db_mysql_new_connection(): driver error: Can't connect to MySQL server on '127.0.0.1' (111)
Jun 16 11:14:51 localhost homer[1339]: ERROR: <core> [db.c:318]: db_do_init2(): could not add connection to the pool
Jun 16 11:14:51 localhost homer[1339]: ERROR: sipcapture [sipcapture.c:1104]: child_init(): unable to connect to database [mysql://root:Bharath@123@127.0.0.1/homer_data] from capture_mode param.
Jun 16 11:14:51 localhost homer[1339]: ERROR: <core> [sr_module.c:923]: init_mod_child(): Error while initializing module sipcapture (//usr/lib/x86_64-linux-gnu/kamailio/modules/sipcapture.so)
Jun 16 11:14:51 localhost homer[1339]: ERROR: <core> [pt.c:329]: fork_process(): init_child failed for process 8, pid 1339, "secondary timer"
Jun 16 11:14:51 localhost homer[1339]: ERROR: <core> [timer_proc.c:418]: sr_wtimer_start(): wtimer starting failed
Jun 16 11:14:51 localhost homer[1339]: CRITICAL: <core> [main.c:1689]: main_loop(): Cannot start wtimer

Regards
Bharath.G

**Comment by lmangani** [comment]
Mysql is down, check your services

```Jun 16 11:14:51 localhost homer[1339]: ERROR: db_mysql [km_my_con.c:124]: db_mysql_new_connection(): driver error: Can't connect to MySQL server on '127.0.0.1' (111)
```
