### ISSUE TITLE
When scrolling down in Chrome, it always scrolls all the way down. Scrolling up works as expected.

### ISSUE THREAD

**Issue by SipSeb** [sipcapture/homer#237]
Our support guys have an annoying problem. When scrolling in the search result list, it immediately scrolls all the way down to the bottom of the list after starting to scroll. Then you have to scroll up to the wanted position again. 

This does not happen in Firefox or Safari, but always in Chrome.

Is this something that can be fixed within Homer? Or is it a pure Chrome bug?

**Comment by adubovikov** [comment]
looks like a css problem. If you can, please update ui-grid component. 

btw, why you use scroll ? the pagination works well :-)

**Comment by lmangani** [comment]
@SipSeb do you have any infinite scrolling plugins such as RES?

**Comment by SipSeb** [comment]
No, my Chrome is almost plugin-free. And I hate pagination. ;)

It kinda looks like these bugs: 
https://github.com/angular-ui/ui-scroll/issues/138
https://github.com/noraesae/perfect-scrollbar/issues/612

From those comments, it helps adding a css attribute "overflow-anchor: none" to the container. I just did that directly in the developer console in my Chrome, and this indeed fixes the scrolling. 

Now the question would be: Where to add it in the source? Honestly, I don't see any chance for me finding the correct point in the source code.

**Comment by adubovikov** [comment]
just open the ui result template and add this class as inline style

**Comment by SipSeb** [comment]
I just installed the newest ui-grid library (4.0.6) into my Homer project folder, and the problem is gone. It was tackled already in February. See https://github.com/angular-ui/ui-grid/issues/6017

I've created a PR for this. https://github.com/sipcapture/homer-ui/pull/98

**Comment by adubovikov** [comment]
merged! Thank you!
