### ISSUE TITLE
Sliding timewindow when autoupdate is enabled

### ISSUE THREAD

**Issue by astrakid** [sipcapture/homer#239]
When you select "last x hours" as timeframe and enable auto update, then the time frame is not updated. it makes no sense to have an auto update with a static timeframe in the past.

**Comment by lmangani** [comment]
Please pull the latest HOMER-UI and retest: https://github.com/sipcapture/homer-ui/commit/71cc316756232b2737e1fbe4901ffe40ea24b17f

**Comment by astrakid** [comment]
hi,
fix is working!!! thanks a lot.
the only "cosmetic thing" is that the timeframe itself is not changing, 
but i am nost sure if this is an issue.

thanks a lot again!

regards,
andre



Von:    Lorenzo Mangani <notifications@github.com>
An:     sipcapture/homer <homer@noreply.github.com>
Kopie:  Andre G <andre.gronwald@gfi.ihk.de>, Author 
<author@noreply.github.com>
Datum:  27.06.2017 20:37
Betreff:        Re: [sipcapture/homer] Sliding timewindow when autoupdate 
is enabled (#239)



Please pull the latest HOMER-UI and retest: sipcapture/homer-ui@71cc316

**Comment by lmangani** [comment]
@astrakid doesn't the range display "Last XX" or is it a manual selection?

**Comment by astrakid** [comment]
as you see: the time range is not updated afterwards, but the charts are 
updated in the right manner (see in the background -> stats available for 
a later timestamp (11:30). -> auto update is working, timerange is not 
updated.

**Comment by lmangani** [comment]
Now I understand. Timerange is not supposed to be updated really as that's a selector.... we might do that too if others think this is useful in any way, but the "real" representation driving the refresh is "Last 1 Hour"

**Comment by astrakid** [comment]
I totally agree. Issue can be closed! ;-)
thanks a lot!
