### ISSUE TITLE
couple error with homer docker

### ISSUE THREAD

**Issue by mveerdon** [sipcapture/homer#241]
I get an error during the installation of homer w/ docker.

Any tips?

`HypriotOS/armv6: pirate@black-pearl in ~/homer-docker on master

$ git clone https://github.com/sipcapture/homer-docker.git
Cloning into 'homer-docker'...
remote: Counting objects: 515, done.
remote: Total 515 (delta 0), reused 0 (delta 0), pack-reused 515
Receiving objects: 100% (515/515), 105.21 KiB | 0 bytes/s, done.
Resolving deltas: 100% (284/284), done.
Checking connectivity... done.

HypriotOS/armv6: pirate@black-pearl in ~/homer-docker on master
$ cd homer-docker

HypriotOS/armv6: pirate@black-pearl in ~/homer-docker/homer-docker on master
$ docker-compose build
mysql uses an image, skipping
Building kamailio
Step 1/15 : FROM debian:jessie
 ---> 62a932a5c143
Step 2/15 : MAINTAINER L. Mangani <lorenzo.mangani@gmail.com>
 ---> Using cache
 ---> 01c530023e4a
Step 3/15 : ENV HOME /root
 ---> Using cache
 ---> f827a6284d7c
Step 4/15 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 92f548bc44c8
Step 5/15 : RUN apt-get update -qq
 ---> Running in cc45c981c184
standard_init_linux.go:178: exec user process caused "exec format error"
ERROR: Service 'kamailio' failed to build: The command '/bin/sh -c apt-get update -qq' returned a non-zero code: 1
HypriotOS/armv6: pirate@black-pearl in ~/homer-docker/homer-docker on master

$ docker-compose up
Building kamailio
Step 1/15 : FROM debian:jessie
 ---> 62a932a5c143
Step 2/15 : MAINTAINER L. Mangani <lorenzo.mangani@gmail.com>
 ---> Using cache
 ---> 01c530023e4a
Step 3/15 : ENV HOME /root
 ---> Using cache
 ---> f827a6284d7c
Step 4/15 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 92f548bc44c8
Step 5/15 : RUN apt-get update -qq
 ---> Running in 7a8ee4230c19
standard_init_linux.go:178: exec user process caused "exec format error"
ERROR: Service 'kamailio' failed to build: The command '/bin/sh -c apt-get update -qq' returned a non-zero code: 1
HypriotOS/armv6: pirate@black-pearl in ~/homer-docker/homer-docker on master

$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
HypriotOS/armv6: pirate@black-pearl in ~/homer-docker/homer-docker on master
$ [](url)`

**Comment by lmangani** [comment]
Are you actually trying to build this on an armv6 or is it just a hostname?

**Comment by mveerdon** [comment]
I'm trying to install it on a raspberry pi2 with hypriot docker

**Comment by dougbtv** [comment]
@mveerdon -- sounds like a cool project, but, might take some elbow grease to get all the deps to compile for ARM. If you need to make some changes to the dockerfiles etc, happy to help you fold that in to collaborate in getting both an x86 & arm set of dockerfiles working in the homer-docker project.

**Comment by lmangani** [comment]
Please comment to reopen if needed. Thanks for your report!
