### ISSUE TITLE
Documentation X-CID Correlation

### ISSUE THREAD

**Issue by lchabert** [sipcapture/homer#244]
Hi,

I have just installed homer, and real good work ... thanks.
Infortunaly, my voice plateform has some asterisk acting has SBC. I have noticed correlation feature using X-CID header.

How can i implement it on asterisk, diaplan part using PJSIP ? Some diaplan test below, not working.

I have try:
```
[routing]
exten => _+X.,1,NoOp()
 same =>n,Set(PJSIP_HEADER(add,X-CID)=${BRIDGEPVTCALLID})
 same =>n,Dial(PJSIP/${EXTEN}@kamailio)
```
Output: 
```
-- Executing [+33XXXXXXXX@routing:2] Set("PJSIP/transit-0000d4b2", "PJSIP_HEADER(add,X-CID)=") in new stack
```

Thanks,
Regards.

**Comment by negbie** [comment]
Please be so kind and provide the records from mysql.

**Comment by lchabert** [comment]
Sorry for this output, but please find two invites with asterisk as B2B:

```
id	date	micro_ts	method	reply_reason	ruri	ruri_user	ruri_domain	from_user	from_domain	from_tag	to_user	to_domain	to_tag	pid_user	contact_user	auth_user	callid	callid_aleg	via_1	via_1_branch	cseq	diversion	reason	content_type	auth	user_agent	source_ip	source_port	destination_ip	destination_port	contact_ip	contact_port	originator_ip	originator_port	expires	correlation_id	custom_field1	custom_field2	custom_field3	proto	familyrtp_stat	type	node	msg
2	2017-07-18 17:19:11	1500391151083000	INVITE		sip:+40214074532@dc4-virt-sbc-01.adm.voxity.fr	+40214074532	dc4-virt-sbc-01.adm.voxity.fr	+33481680110	10.0.247.14	as68e0370e	+40214074532	kamailiocore.adm.voxity.fr			+33481680110		1856f97c190569d255f2834c401493be@10.0.247.14:5060		SIP/2.0/UDP 10.0.244.1;branch=z9hG4bK759.d2e5e4ba33527271d216f70fa358ab44.0	z9hG4bK759.d2e5e4ba33527271d216f70fa358ab44.0	102 INVITE			application/sdp		vgw1-voxity	10.0.244.1	5060	10.0.245.4	5060	10.0.247.14	5060		0	-1	1856f97c190569d255f2834c401493be@10.0.247.14:5060				1	2		1\na=sendrecv 0-16lephone-event/8000 10.0.247.14ER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
3	2017-07-18 17:19:11	1500391151089947	INVITE		sip:40214074532@sip.flowroute.com:5060	40214074532	sip.flowroute.com	33481680110	91.229.172.4	577313a7-2fb7-4597-b5d1-8483cc081294	40214074532	sip.flowroute.com			asterisk		3325a48c-226e-469c-b665-471676d049ac		SIP/2.0/UDP 91.229.172.4:5060;rport;branch=z9hG4bKPjbdb8887e-4e44-4f25-9f2a-69d21863a458	z9hG4bKPjbdb8887e-4e44-4f25-9f2a-69d21863a458	32765 INVITE			application/sdp		Asterisk PBX 13.11.2	91.229.172.4	5060	216.115.69.144	5060	91.229.172.4	5060		0	-1	3325a48c-226e-469c-b665-471676d049ac				1	2		1	h\na=sendrecv:1506lephone-event/800091.229.172.4bVITE, ACK, BYE, CANCEL, UPDATE, PRACK, REGISTER, REFER, MESSAGE
```

**Comment by negbie** [comment]
And have a look at 
https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+Configuration_res_hep

I did not test this but you could try to read the callid like
exten => s,n,Set(SIPCALLID=${PJSIP_HEADER(read,Call-ID)}

Add your bleg string and tell the
hep module to use your custom SIPCALLID variable AS uuid_type

**Comment by negbie** [comment]
Hm reading this
https://github.com/asterisk/asterisk/blob/master/configs/samples/hep.conf.sample

You cannot pass your own variables. Only  
 'call-id' for the PJSIP or chan_sip SIP Call-ID

**Comment by negbie** [comment]
Mby you should mask the sensitive data (if any) from your output. Try to read the callid as suggested and add it with PJSIP_HEADER(add,X-CID)=$SIPCALLID

**Comment by lchabert** [comment]
But some configuration is needed on homer side no ?

**Comment by lmangani** [comment]
@lchabert you can find generics for the HOMER side settings on the wiki: https://github.com/sipcapture/homer/wiki/Using-Homer-5#session-correlation

**Comment by lmangani** [comment]
This info is available on the wiki. Please comment to reopen if needed. Thanks for your report!

**Comment by Happyman1974** [comment]
Hi,

just want to notice there is not complite info on the wiki 👍 
[https://github.com/sipcapture/homer/wiki/Examples%3A-Asterisk#pjsip-x-cid-correlation-for-bleg](url)

here are my code rows:
`Set(SIPCALLID=${PJSIP_HEADER(read,Call-ID)});
PJSIP_HEADER(add,X-CID)=${SIPCALLID};`

**Comment by davidcsi** [comment]
the wiki doesn't have any info as to how to configure the x-cid on the homer7 version docker-compose.

**Comment by lmangani** [comment]
@davidcsi there's nothing special about the docker version. the same heplify-server settings apply. If you need help, please open a new issue 👍
