### ISSUE TITLE
Problem with logrotate script "duplicate partition name"

### ISSUE THREAD

**Issue by ciscospirit** [sipcapture/homer#245]
Hello,

since few days we have a problem with the logrotate script, that it doesn't function anymore.
there is a "duplicate partition name" problem... so the disk get full after some days...

see screenshot below:

![logrotate](https://user-images.githubusercontent.com/15861549/29171238-198e8eae-7ddc-11e7-9e4a-b70912d5effe.PNG)

can you help us with this problem?

**Comment by adubovikov** [comment]
This is not a problem, because you have enabled step rotation bigger than 1
day.

Just check if you have enough partitions to store the data.

Wbr,
Alexandr

10 авг. 2017 г. 14:57 пользователь "ciscospirit" <notifications@github.com>
написал:
