### ISSUE TITLE
default varchar(1500) for msg in various tables is to small

### ISSUE THREAD

**Issue by Doranku** [sipcapture/homer#246]
After testing Homer with the docker install, I noticed that the message body in the database is to small for INVITEs from out upstream provider. It is the default varchar(1500) for the kamailio sipcapture module. There appears to be no reason not to change this to a higher value. There is no negative impact to setting it to for example 9000 (a random chosen value (mtu of jumbo frames)), the storage requirements for varchar>255 is the string length +2 bytes. The pro is that we can see the actual INVITE body and not some truncated string.

**Comment by lmangani** [comment]
Hi @Doranku thanks for your note. This parameter can already be defined in the rotation preferences as you probably noticed - have you tried that approach already? 

This being said, the upcoming version does indeed raise the default to a higher value and there's no problem doing the same here if we have a quorum - If your question is more specific to the Docker setup, we can add it as a parameter at startup time - just file an issue on the homer-docker repo if so.

**Comment by Doranku** [comment]
Good to hear that it is fixed in new versions. That closes this issue. Thanks for the feedback.

I just started looking into this project and just altered the tables in mysql for testing. I'm off to find out how make this permanent (unrelated to this issue).

**Comment by lmangani** [comment]
The rotation scripts do define the table size, once you change it there, its applied daily when the cron script runs. Hope this helps!

**Comment by Doranku** [comment]
Thanks for the pointer found it ( /homer-api/scripts/rotation.ini in homer-cron container)
