### ISSUE TITLE
QOS information from ACME SBC with Horaclifix

### ISSUE THREAD

**Issue by MosinAnton** [sipcapture/homer#248]
When I enabled qos in comm-monitor on ACME SBC, I have a lot of error messages in kamailio log.

```
/usr/sbin/kamailio[130983]: ERROR: <core> [core/parser/msg_parser.c:330]: parse_headers(): bad header field [(null)]

/usr/sbin/kamailio[130994]: ERROR: <core> [core/parser/parse_fline.c:257]: parse_first_line(): parse_first_line: bad message (offset: 0)

/usr/sbin/kamailio[130994]: ERROR: <core> [core/parser/msg_parser.c:671]: parse_msg(): ERROR: parse_msg: message=<{"CALLEE_DST_IP":"ХХ.ХХ.ХХ.ХХ","CALLEE_DST_PORT":13604,"CALLEE_SRC_IP":"ХХ.ХХ.ХХ.ХХ","CALLEE_SRC_PORT":13000,"CALLEE_VLAN":ХХХ,"CALLER_DST_IP":"ХХ.ХХ.ХХ.ХХ","CALLER_DST_PORT":17366,"CALLER_SRC_IP":"XX.XX.XX.XX","CALLER_SRC_PORT":19280,"CALLER_VLAN":XXX,"INC_ID":"F7383F2-8D5011E7-ACE7C82E-F6EC6D48@XX.XX.XX.XX","INC_MOS":438,"INC_REALM":"peering1","INC_RTCP_AVG_JITTER":453,"INC_RTCP_AVG_LAT":57,"INC_RTCP_BYTE":1602,"INC_RTCP_MAX_JITTER":600,"INC_RTCP_MAX_LAT":59,"INC_RTCP_PK":9,"INC_RTCP_PK_LOSS":0,"INC_RTP_AVG_JITTER":2,"INC_RTP_BYTE":516224,"INC_RTP_MAX_JITTER":15,"INC_RTP_PK":2368,"INC_RTP_PK_LOSS":0,"INC_RVAL":9204,"MEDIA_TYPE":1,"OUT_ID":"F7383F2-8D5011E7-ACE7C82E-F6EC6D48@XX.XX.XX.XX","OUT_MOS":440,"OUT_REALM":"core","OUT_RTCP_AVG_JITTER":17,"OUT_RTCP_AVG_LAT":1,"OUT_RTCP_BYTE":990,"OUT_RTCP_MAX_JITTER":26,"OUT_RTCP_MAX_LAT":2,"OUT_RTCP_PK":9,"OUT_RTCP_PK_LOSS":0,"OUT_RTP_AVG_JITTER":0,"OUT_RTP_BYTE":482652,"OUT_RTP_MAX_JITTER":33,"OUT_RTP_PK":2214,"OUT_RTP_PK_LOSS":0,"OUT_RVAL":9284}>
```

How I can save QOS information?

**Comment by lmangani** [comment]
Are you using horaclifix, the GO version of the client?

**Comment by MosinAnton** [comment]
yes, from https://github.com/negbie/horaclifix/releases/download/0.80/horaclifix

**Comment by negbie** [comment]
Hi, on mobile right now. So without going into Details this rctp type is atm not fully(you need some stuff in kamailio and a some PHP tweaks) integrated into the opensource tree of Homer. Inside horaclifix i created a custom rtcp type but did not have the time to do a pull request. I can upload my www folder later if you want.

**Comment by MosinAnton** [comment]
It wil be great. I can change some files and test.

**Comment by lmangani** [comment]
@negbie best to do this properly in a UI branch rather than creating uncontrolled "snapshots" I'll take charge of the task if needed

**Comment by negbie** [comment]
@MosinAnton I pushed for you some new files into the horaclifix branch inside homer-ui.
https://github.com/sipcapture/homer-ui/tree/horaclifix

Still not the best choise as i created some new files which does not belong here. So this branch will be delete in the near future. But for you following is important:

Move the etc/kamailio and opt folder out. The config files inside the etc/kamailio folder should give you the idea what you need. Especially this is needed on kamailio side:
.......
	 #####################HORACLIFIX###############################
else if($hep(0x00b) == 38)
.......

The rotation.ini and homer_mysql_rotate.pl files inside the opt folder are needed because i store those data inside the report_capture_all table which i rotate.

**Comment by negbie** [comment]
If you setup it right you should see following.
![Imgur](http://i.imgur.com/xhEQuSv.jpg)

(The top part is from rtpengine)

**Comment by negbie** [comment]
Since I am a litle bit busy the last week I did not find the time to integrate it fluent into the master branch. If the next homer release comes out I will do it.

**Comment by negbie** [comment]
PS: I just saw that all the files you need are also in the source code zip under the homer folder:
https://github.com/negbie/horaclifix/releases

I removed it some time ago because I dont want a high % number of php code in my repo ;D But its still in the zip

**Comment by MosinAnton** [comment]
I have replaced files from zip. All works great!
