### ISSUE TITLE
Can't install Homer

### ISSUE THREAD

**Issue by DPanzer101** [sipcapture/homer#249]
Hi,

I'm having an issue installing Homer on Debian 8.6 Jesse.  I tried to install the package I'm receiving errors

It says Unable to locate package php-services-jason
Unable to locate package pwgen
unable to loacte package libclass-dbi-mysql-perl

I'm new to using Linux so I'm sure it's something on my end.  Thanks.

**Comment by lmangani** [comment]
Please comment to reopen if needed. Thanks for your report!
