### ISSUE TITLE
not getting all CDRS at sip signaling

### ISSUE THREAD

**Issue by prashantvidja** [sipcapture/homer#251]
Hello

I am not getting all CDRS from database also I check by changing time period but only I get 20-25 cdrs How I get all live CDRS..
And also live cdrs are not showing when I did calling...
I  use Homer 5.0.5 version and kamailio 5.0 and also I used captagent 3 in VOIP server...

Thanks

**Comment by lmangani** [comment]
Hi, apologies but unfortunately it is extremely hard to make any suggestion with such scarce information.
I would assume (maybe being wrong) this is not an issue with our software, but rather an installation or usage question which might sit best on our mailing-list. Thanks!
