### ISSUE TITLE
QoS : time shift

### ISSUE THREAD

**Issue by Rico29** [sipcapture/homer#252]
I'm facing an issue with QoS graphs and I don't know where it can come from.
My call flow starts at 10:33:42 : 
![selection_052](https://user-images.githubusercontent.com/12935571/31377876-d2df18fe-ada9-11e7-8adf-547a79fb5a00.png)
and ends at 10:37:23
![selection_053](https://user-images.githubusercontent.com/12935571/31377894-e0125446-ada9-11e7-9d66-5c4e8cdaf5bb.png)

Qos Chart starts at 10:38:33 and ends at 10:46:02. -> why ?
![selection_051](https://user-images.githubusercontent.com/12935571/31378131-9261b5e2-adaa-11e7-8239-99784847d09d.png)

Analyses shows two rtp streams, but there's no reinvite or port change during the communication.
Why are the streams shifted in time like this ? Can it come from a phone which is not NTP synchronized ? SIP proxy (asterisk) and capture node are NTP sync.

Regards,
Cédric

**Comment by adubovikov** [comment]
please check the time you have in the DB for these RTCP records

**Comment by Rico29** [comment]
which fields do I have to check ?
I have : 
{ "sender_information":{"ntp_timestamp_sec":1873231872,"ntp_timestamp_usec":272422755,"octets":1260,"rtp_timestamp":2963715898, "packets":63},"ssrc":1891677661,"type":200, "report_blocks":[{"source_ssrc":1712128753,"highest_seq_no":12699,"fraction_lost":0,"ia_jitter":0,"packets_lost":0,"lsr":0,"dlsr":0}],"report_count":1,"sdes_ssrc":1891677661,"sdes_chunk_ssrc":17258853,"sdes_information": [ {"type":0,"text":"pÀµÝYea"},{"type":108,"text":"nksales@yealink.com"}],"sdes_report_count":2}                    |

One other thing I don't understand : in my RTCP records for this call_id, I only have ports 12183 and 18195. Why do I see ports 12182 and 18194 in "SDP session 1" tab ?

**Comment by Rico29** [comment]
Do you want me to provide a sqldump for this call_id ?

**Comment by adubovikov** [comment]
this is report payload, I am asking about the DB fields:

https://github.com/sipcapture/homer-api/blob/master/sql/mysql/schema_data.sql#L41-L54

**Comment by adubovikov** [comment]
yes, it will be the best way also please provide your TZ

**Comment by Rico29** [comment]
Here is the sqldump for this call_id
[sqldump.txt](https://github.com/sipcapture/homer/files/1371375/sqldump.txt)

**Comment by adubovikov** [comment]
and TZ?

**Comment by Rico29** [comment]
Timezone is GMT +2

**Comment by Rico29** [comment]
mysql> select * from setting where param_name LIKE "time%"\G
*************************** 1. row ***************************
              id: 141
             uid: 1
      param_name: timerange
     param_value: {"from":"2017-10-10T08:25:38.678Z","to":"2017-10-10T09:25:38.678Z","custom":"","customFrom":"2017-10-10T08:25:38.678Z","customTo":"2017-10-10T09:25:38.678Z"}
valid_param_from: 2012-01-01 00:00:00
  valid_param_to: 2032-12-01 00:00:00
      param_prio: 10
          active: 1
*************************** 2. row ***************************
              id: 142
             uid: 1
      param_name: timezone
     param_value: {"value":-120,"name":"GMT+2 EET","offset":"+0200"}
valid_param_from: 2012-01-01 00:00:00
  valid_param_to: 2032-12-01 00:00:00
      param_prio: 10
          active: 1
2 rows in set (0.00 sec)

**Comment by adubovikov** [comment]
so, yes, the chart shows UTC time, but anyway you have time desync between your MYSQL DB and rtpagents who sent the report:

MYSQL insert time: 2017-10-10 10:33:58
captagent time: 1507624960759000 = 10/10/2017 @ 8:42am (UTC)

so, please fix it on your side. Here is no issue.

**Comment by Rico29** [comment]
captagent and mysql server are both NTP synced... don't understand

**Comment by adubovikov** [comment]
if it has been synced, why the time of captagent is 9 minutes above ?

**Comment by adubovikov** [comment]
here it shows: we use captagent HEP time
https://github.com/kamailio/kamailio/blob/master/src/modules/sipcapture/sipcapture.c#L2321

**Comment by Rico29** [comment]
that is exactly the same question I'm asking to myself :)
both servers are correctly synced, time is the same on both  : 

root@adm-tph-asterisk1:~# date +%s && \ssh root@172.27.0.10 date +%s
1507633532
1507633532

**Comment by adubovikov** [comment]
do you use captagent or asterisk to send HEP data ?

**Comment by Rico29** [comment]
I use captagent 6.2

**Comment by Rico29** [comment]
any specifig config to do on captagent ?

**Comment by adubovikov** [comment]
there is not specific configs... 

do you have high load on the mysql server ? 

and please try to capture HEP packet and make analyze in Wireshark using HEP-LUA plugin (check our projects)

**Comment by Rico29** [comment]
load is low on mysql server.
I'm trying to analyze hep packets

**Comment by Rico29** [comment]
still trying to install wireshark with LUA support but I have a QT lib problem and I can not compile it...

**Comment by adubovikov** [comment]
sorry ? why just not install it from repository ? what do you use ?

**Comment by Rico29** [comment]
using centos 7, LUA was not recognized by wireshark ( 1.10.14 in centos repos...)
it works just fine with 2.4.2

**Comment by Rico29** [comment]
Strange....
![image](https://user-images.githubusercontent.com/12935571/31431456-183b0046-ae74-11e7-9e96-cb305c3ee2a9.png)

**Comment by adubovikov** [comment]
i told you: you have desync

**Comment by Rico29** [comment]
how can I find where this desync comes from ? because both servers are NTP synced...

**Comment by adubovikov** [comment]
first check HEP packets using HEP-LUA and wireshark

**Comment by Rico29** [comment]
HEP packets are fine.
ex : call-id Call-ID: 06f0116957e30aa1387a1c39728994d2@172.17.190.10:5060 
in HEP pcap : invite received at 10 Oct 2017 14:14:17 GMT 
in homer : displayed date in call-flow is 2017-10-10 16:14:17 +0200
in pcap : first RTCP report for this call is received BEFORE the 200 OK.

Attached : 
capture_hep.pcap.txt : export of tcpdump on kamailio port on capture node, with filter : "sip.Call-ID contains 06f0116957e30aa1387a1c39728994d2|| hep3.correlation_id contains 06f0116957e30aa1387a1c39728994d2"
[capture_homer.pcap.txt](https://github.com/sipcapture/homer/files/1375120/capture_homer.pcap.txt)

capture_homer.pcap.txt : pcap export from homer frontend for this call-id
[capture_hep.pcap.txt](https://github.com/sipcapture/homer/files/1375122/capture_hep.pcap.txt)

capture_homer_web.png : screenshot of QoS report
![capture_homer_web](https://user-images.githubusercontent.com/12935571/31434033-8637cb86-ae7b-11e7-8835-12d68ac0ce37.png)

**Comment by adubovikov** [comment]
Can you please share your kamailio.cfg (sipcapture) and full SQL dump of this call:
06f0116957e30aa1387a1c39728994d2@172.17.190.10:5060

**Comment by Rico29** [comment]
Here is the kamailio.cfg : 
[kamailio.cfg.txt](https://github.com/sipcapture/homer/files/1375163/kamailio.cfg.txt)

the dump of  "sip_capture_call" table : 
[sip_capture_export.sql.txt](https://github.com/sipcapture/homer/files/1375178/sip_capture_export.sql.txt)
the dump of "rtcp_capture" table : 
[rctp_capture_export.sql.txt](https://github.com/sipcapture/homer/files/1375180/rctp_capture_export.sql.txt)

Regards

**Comment by adubovikov** [comment]
Can you please change line 1003 to:

 $var(millisec) = "("+$var(timesec)+"*1000000+"+$var(timeusec)+")";

and re-test it ?

**Comment by Rico29** [comment]
Still have the same behavior after changing this line & restart kamailio :(

**Comment by adubovikov** [comment]
Can you add after such line:
xlog("HEP XLOG JSON PAYLOAD [$var(json)]. Id: $var(correlation_id): MS: $var(millisec) NOW: $TS \r\n");

and please compare the time in MS and NOW

**Comment by Rico29** [comment]
I'm waiting for xlog lines to appear.
I see a lot of errors in syslog like this one : 
Oct 11 14:34:00 homer homer[7734]: ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'S7/DS1"},{"type":45,"text":"0/18@mgtou270.francetelecom.net"}],"sdes_report_coun' at line 1 (1064)
Oct 11 14:34:00 homer homer[7734]: ERROR: <core> [db_query.c:181]: db_do_raw_query(): error while submitting query
Oct 11 14:34:00 homer homer[7734]: ERROR: sqlops [sql_api.c:265]: sql_do_query(): cannot do the query [INSERT INTO rtcp_capture_all_201]

when I say "a lot", it's about 20 per minute...

**Comment by Rico29** [comment]
I guess it's related to special chars, like : 
Oct 11 14:35:06 homer homer[7735]: ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '��#001#007Ye"},{"type":97,"text":"ink#004#01786-592-570-2000"}],"sdes_report_count":2}' at line 1 (1064)

**Comment by adubovikov** [comment]
you have to escape it. looks like your UAC sends some utf8 or non ascii in RTCP "text" field
but this is different issue, please show me the xlog that I sent to you

**Comment by Rico29** [comment]
I had to put your changes at line 970, as I HEP packets match if($hep(0x00b) == 5) condition

Here's a few lines of output : 

Oct 11 14:45:48 homer homer[9775]: ERROR: <script>: HEP XLOG JSON PAYLOAD [{ "sender_information":{"ntp_timestamp_sec":2926084352,"ntp_timestamp_usec":2852790,"octets":17032480,"rtp_timestamp":3357389126, "packets":106453},"ssrc":1821080245,"type":200, "report_blocks":[{"source_ssrc":1598410392,"highest_seq_no":143174,"fraction_lost":0,"ia_jitter":0,"packets_lost":1,"lsr":2432350965,"dlsr":128450}],"report_count":1,"sdes_ssrc":1821080245,"sdes_chunk_ssrc":19354423,"sdes_information": [ {"type":0,"text":"l�z�#001'S7/DS1"},{"type":45,"text":"0/18@mgtou270.francetelecom.net"}],"sdes_report_count":2}
Oct 11 14:45:49 homer homer[9776]: ERROR: <script>: HEP XLOG JSON PAYLOAD [{ "sender_information":{"ntp_timestamp_sec":0,"ntp_timestamp_usec":0,"octets":1149600,"rtp_timestamp":11669760, "packets":7185},"ssrc":3247473667,"type":200, "report_blocks":[{"source_ssrc":1148224492,"highest_seq_no":1157,"fraction_lost":0,"ia_jitter":6,"packets_lost":0,"lsr":0,"dlsr":289013}],"report_count":1,"sdes_ssrc":3247473667,"sdes_chunk_ssrc":18113126,"sdes_information": [ {"type":0,"text":"���#003#001#024b"},{"type":102,"text":"9@100.127.216.213"}],"sdes_report_count":2}
Oct 11 14:45:49 homer homer[9775]: ERROR: <script>: HEP XLOG JSON PAYLOAD [{ "sender_information":{"ntp_timestamp_sec":4254107869,"ntp_timestamp_usec":3518747092,"octets":1068960,"rtp_timestamp":4042659984, "packets":6681},"ssrc":1148224492,"type":200, "report_blocks":[{"source_ssrc":849604,"highest_seq_no":7210,"fraction_lost":0,"ia_jitter":2,"packets_lost":0,"lsr":0,"dlsr":33947}],"report_count":1,"sdes_ssrc":1148224492,"sdes_chunk_ssrc":16777216,"sdes_information": [],"sdes_report_count":0}
Oct 11 14:45:49 homer homer[9776]: ERROR: <script>: HEP XLOG JSON PAYLOAD [{ "sender_information":{"ntp_timestamp_sec":3369959168,"ntp_timestamp_usec":1829929888,"octets":692160,"rtp_timestamp":3620590683, "packets":4326},"ssrc":1547001671,"type":200, "report_blocks":[{"source_ssrc":1947279799,"highest_seq_no":18423,"fraction_lost":0,"ia_jitter":3,"packets_lost":0,"lsr":2432455482,"dlsr":96992}],"report_count":1,"sdes_ssrc":1547001671,"sdes_chunk_ssrc":19419953,"sdes_information": [ {"type":0,"text":"\5_G#001(S12/DS"},{"type":49,"text":"49/17@mgtou170.francetelecom.net"}],"sdes_report_count":2}

**Comment by adubovikov** [comment]
sorry, but this is not that I gave you
where is MS and ID ?

keep it without JSON body

xlog("HEP XLOG Id: $var(correlation_id): MS: $var(millisec) NOW: $TS \r\n");

**Comment by Rico29** [comment]
other lines without payload display : 
Oct 11 14:49:36 homer homer[9871]: ERROR: <script>: HEP XLOG JSON PAYLOAD . Id: 0_2966351477@172.27.1.85: MS: (1507726176*1000000+388228) NOW: 1507726176
Oct 11 14:49:36 homer homer[9870]: ERROR: <script>: HEP XLOG JSON PAYLOAD . Id: 011d702b3c7008737715daae2597c639@172.27.0.20:5060: MS: (1507726176*1000000+388425) NOW: 1507726176
Oct 11 14:49:36 homer homer[9871]: ERROR: <script>: HEP XLOG JSON PAYLOAD . Id: 011d702b3c7008737715daae2597c639@172.27.0.20:5060: MS: (1507726176*1000000+451008) NOW: 1507726176
Oct 11 14:49:36 homer homer[9874]: ERROR: <script>: HEP XLOG JSON PAYLOAD . Id: 5c03b60e45c8bb2f7dd64c1619696251@172.17.190.10:5060: MS: (1507726176*1000000+729687) NOW: 1507726176
Oct 11 14:49:36 homer homer[9872]: ERROR: <script>: HEP XLOG JSON PAYLOAD . Id: 0_3781233487@172.27.1.105: MS: (1507726176*1000000+749948) NOW: 1507726176
Oct 11 14:49:37 homer homer[9873]: ERROR: <script>: HEP XLOG JSON PAYLOAD . Id: 0_2766426917@172.27.1.125: MS: (1507726176*1000000+978302) NOW: 1507726177

**Comment by Rico29** [comment]
looks correct, isn't it ? 15077261761000000+978302 / 1000000 = 1507726176.19

**Comment by adubovikov** [comment]
sorry, should be one null more: 10000000

**Comment by Rico29** [comment]
Looks better ! will check tomorrow.
I also changed line 977 : 
`sql_query("wc", "INSERT INTO $var(table) (date, micro_ts, correlation_id, source_ip, source_port, destination_ip, destination_port, proto, family, type, node, msg) VALUES($var(t_date), $var(millisec), '$var(correlation_id)','$var(srcip)',$var(srcport),'$var(dstip)',$var(dstport),$var(proto),$var(family),$var(type),'$var(node)','$var(json)')");`
to
`sql_query("wc", "INSERT INTO $var(table) (date, micro_ts, correlation_id, source_ip, source_port, destination_ip, destination_port, proto, family, type, node, msg) VALUES($var(t_date), $var(millisec), '$var(correlation_id)','$var(srcip)',$var(srcport),'$var(dstip)',$var(dstport),$var(proto),$var(family),$var(type),'$var(node)','$(var(json){s.escape.common})')");`

I'll do a pull requesto tomorrow

**Comment by adubovikov** [comment]
super!

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-config/commit/433a32c85abdabc89922880b7561b3eb5040245f

for s.escape, please do pull request.

Thank you

**Comment by Rico29** [comment]
here is the pull request.
many thanks for your debugging support !
Cédric
