### ISSUE TITLE
Associating more than 2 Call-IDs

### ISSUE THREAD

**Issue by nward** [sipcapture/homer#253]
Hi,

I have a network where a call will typically go through at least two SBCs, so there are 3 different Call-IDs. We can look at 2 calls joined together at a time (i.e. SBC-A inside+outside) but we can't correlate all 3 and look at a signalling trace across the whole lot.

Perhaps we can generate an internal "Homer Call-ID" which ties all the calls together in an association table, or something, rather than the 1:1 association that's currently possible?

Happy to do some work on this, but, figured I'd open discussion as I'm sure it's not something unique to me.

**Comment by SipSeb** [comment]
If you inject the Call-ID of Call A not only into Call B but also into Call C via the appropriate header, Homer will combine all three call legs in its output. 

Does that help already?

**Comment by games130** [comment]
i have something similar which i solved using post-processing.

UE to SBC call id = 12345
SBC to IMS/Application Server(AS) call id = sbc12345

search and remove "sbc"

SBC to AS call id = 12345 and icid = abc1234
AS to new INVITE call id = AS98766 and icid = abc1234

here i notice that the icid which is use for charging is the same throughout the call within IMS, so i use icid to identify the call within the IMS flow

search sip message with ICID = abc1234 and u get call id 12345 and AS98766. Replace all callid AS98766 with 12345

So now i have end to end call from UE -- SBC -- IMS --- until termination with the same call-id

**Comment by lmangani** [comment]
Please comment to reopen if needed. Thanks for your report!
