### ISSUE TITLE
No VoIP-Traffic stats after switching to SINGLE_NODE=0

### ISSUE THREAD

**Issue by mihovilkolaric** [sipcapture/homer#254]
I installed homer using the manual https://github.com/sipcapture/homer/wiki/Quick-Install#-manual-setup-from-source-advanced - everything worked fine, including VoIP-Stats.
Then I extended my setup to a Multi-Node Setup as according to https://github.com/sipcapture/homer/wiki/Using-DB-Nodes , that means:
Two nodes using captureagent + kamailio (with sipcapture) and an own mysql-database.
A third node with apache, homer-api, homer-web (and mysql-database for homer_configuration.

Since that, "SIP Search" in homer works fine (and finds results from both DB nodes), but the VoIP Traffic stats are empty.
Is there any special configuration for the statistics tables (in Admin-Panel-> Local Nodes)?

**Comment by kevin-olbrich** [comment]
I am planning a similar setup. Did you solve this problem?

**Comment by adubovikov** [comment]
can you please activate syslog and check if the sql queries has been generated correct and sent to the correct DB node.

**Comment by mihovilkolaric** [comment]
Unfortunately I could not solve the issue ... I figured out that the queries for the "Stats: VoIP Traffic" are sent to the DB on localhost (which is the configuration-Database of the homer-API only, and thus returns nothing), and not to the DB-Nodes configured in Admin-Panel.

The DB-config from configuration.php is:

/*********************************************************************************/
/* AUTH DB homer. User and Configuration */
define('DB_HOSTNAME', "localhost");
define('DB_PORT', 3306);
define('DB_USERNAME', "homer_user");
define('DB_PASSWORD', "XYXYXYXY");
define('DB_CONFIGURATION', "homer_configuration");
define('DB_STATISTIC', "homer_statistic");
define('DB_HOMER', "homer_data");
define('SINGLE_NODE', 0);
define('DATABASE_DRIVER',"mysql");

And the DB-Nodes in Admin-Panel are:
ID | Name    | host    | DB Name    | DB Port | DB User    | DB Password | DB Tables   | status
---+---------+---------+------------+---------+------------+-------------+-------------+-------
23 | server2 | server2 | homer_data |  3306   | homer_user |    ******   | sip_capture | 1
22 | server1 | server1 | homer_data |  3306   | homer_user |    ******   | sip_capture | 1

btw: I also verified that for the "SIP search", the SQL-queries are sent to both configured DB-Nodes.
Do you have any hints for configuring DB-nodes also for statistics?

**Comment by adubovikov** [comment]
Sorry guys, currently statistics couldn't be aggregated across multiple nodes, therefore just send all stats to one DB and use this DB for global stats.

**Comment by kevin-olbrich** [comment]
What is the best solution to independently capture at two locations but join the results?
Currently we were planning with two locations, both hosting homer-api and one hosting the UI.
There are a lot of re-routings between these locations, so we need to have aggregated stats.
As far as I understand, this (currently) can only be accomplished by using a single all-on-one installation?

**Comment by adubovikov** [comment]
you can capture on two or many locations and store data in each datacenter, but the stats should be centralized. This is a point of our talk.

**Comment by kevin-olbrich** [comment]
What exactly is the definition of stats in your case?

**Comment by adubovikov** [comment]
the homer_statistics database

**Comment by kevin-olbrich** [comment]
Ok, so no blocker. Thanks.
