### ISSUE TITLE
Correlating A and B Leg where there is no X-CID. How to use Call-ID and ICID(under P-Charging-Vector)

### ISSUE THREAD

**Issue by games130** [sipcapture/homer#255]
From the homer wiki, i see the correlation that is available is when 
X-CID in B leg is the Call-ID of the A Leg.
or, in b2b mode there is some suffix.

On my system, i am not able to add the X-CID and b2b does not work as well.
The flow i have is as follow:-

SBC ---- CSCF A1 --- ATS ------ CSCF A2

SBC to ATS have Call-ID A. 
CSCF A1 to ATS have **Call-ID A** and **ICID A** (ICID is found in P-Charging-Vector). Note: ICID does not equal Call-ID. It is another unique number used for charging identification
ATS to CSCF A2 have **Call-ID B** and **ICID A**

As you can see above, ATS to CSCF A2, the Call-ID have already change but the ICID is the same throughout the call. However the ICID only appears in SIP Request message, so if just using ICID itself we wont be able to correlate the SIP respond message.

Any suggestion on how i can do this correlation?

Thank You

**Comment by adubovikov** [comment]
Please don't open an issue. For such question we have the mail-list. Thank you!

**Comment by games130** [comment]
may i know where i can access the mail-list?

thank you
