### ISSUE TITLE
/api/v1/session - 500

### ISSUE THREAD

**Issue by davidcsi** [sipcapture/homer#256]
Hello,

I tried installing as per your instructions on https://github.com/sipcapture/homer/wiki/Quick-Install (Manual install, as i want the db separated from the UI), everything seems ok, but when trying to login the browser always gets 500.

My config:

php5-fpm is installed and running: 

> root@sgl-homer-dev-kam-18-220-174-3:/home/admin# netstat -l
> Active UNIX domain sockets (only servers)
> Proto RefCnt Flags       Type       State         I-Node   Path
> unix  2      [ ACC ]     STREAM     LISTENING     2563287  /var/run/php5-fpm.sock

fpm config is set to connect via sockets:

> grep "^listen" /etc/php5/fpm/pool.d/www.conf
> listen = /var/run/php5-fpm.sock
> listen.owner = www-data
> listen.group = www-data
> listen.mode = 0666

The only error coming up on apache's log is:

> FastCGI: comm with server "/usr/lib/cgi-bin/php5-fcgi" aborted: error parsing headers: malformed header '2', referer: http://18.220.174.3/

Any help is greatly appreciated!

Thanks
David

**Comment by davidcsi** [comment]
I tried redoing the whole installation again...
Your instructions don't including installing php5-fpm, but then you do a request to /api/v1/session...
I don't know what else do do to make this work.

**Comment by davidcsi** [comment]
I decided to go with 'nginx' installation, that worked properly.
I shouldn't close this ticket, because as far as I'm concerned, this is an open bug. The installation instructions never talk about installing php5-fpm and configuring it.

**Comment by lmangani** [comment]
Thanks for the update @davidcsi could you help with a "patch" for the procedure so we can update it accordingly?

**Comment by davidcsi** [comment]
Sure, I'll do it during the weekend.
