### ISSUE TITLE
Homer, asterisk, webrtc, hep.conf

### ISSUE THREAD

**Issue by roginvs** [sipcapture/homer#257]
Hi! I am using Homer with asterisk via "hep.conf", and I am getting distorted Call-Flow charts on webrtc calls
![homer-webrtc](https://user-images.githubusercontent.com/6670512/31814573-c2737208-b592-11e7-99d1-8b377578ca84.png)
As we can see on the picture, source ip:port and destination ip:port are the same. I suppose that this is because of asterisk http server, which serves websocket clients. Can we do something with this, even with ugly workaround?

**Comment by lmangani** [comment]
Hi @roginvs This is simply because the message is sent/received by the very same IP:PORT

**Comment by lmangani** [comment]
Oops, did not mean to close the ticket ;) but confirm the last response as the root cause.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-api/blob/master/api/preferences_example.php#L8

**Comment by roginvs** [comment]
@adubovikov : tried CFLOW_HPORT=0 or CFLOW_HPORT=1 , did not notice any changes
@lmangani and @adubovikov : Homer and asterisk hep.conf works perfect for SIP-TLS calls. The problem appears only with webrtc calls. I admit that this is not even a Homer bug, it is an asterisk bug (or, probably, `res_hep.c`)

**Comment by adubovikov** [comment]
ah yes, the IP are also same.... will not work at all :-(

why  are you getting same destination/source pair   ?

**Comment by roginvs** [comment]
@adubovikov I am calling from Chrome with sipjs, so PJSIP channel with WSS transport (which goes via asterisk http server) causes this.
Also, asterisk's own security logs had same bug (LocalAddress is equal to RemoteAddress). Same again, it appears only with wss transport

**Comment by adubovikov** [comment]
so, this is unfortunately the logical issue on the asterisk's site. I recommend open a ticket there. 
sorry about this.

**Comment by roginvs** [comment]
Ok, I agree
