### ISSUE TITLE
Time-Range selector Issue

### ISSUE THREAD

**Issue by iliesh** [sipcapture/homer#259]
Hi,
I have some troubles with using Time Selector feature. It is now showing actually date - but only old data, for ex. if I'm selecting Last 10 min. - I can see all messages until 10 min ago but not the last 10 min. messages, and generally it is not showing properly selected range. Also, doesn't matter how many messages I have - it's showing only 4 pages by 25 items/page and a lot of messages are missing.
Web-Server log file - are filled with errors like:
"A non-numeric value encountered in $WEBPATH/api/RestService/Client.php on line 339"

The Project is great - but still a lot of bugs. Waiting for fixes.
Thank You.

_Homer Version: 5.0.5 (Installed from Instruction: https://github.com/sipcapture/homer/wiki/Quick-Install#-manual-setup-from-source-advanced)
OS: CentOS 7
Kamailio: 5.0.4
Web-Server: Nginx/PHP-FPM_

**Comment by lmangani** [comment]
Known issue. Homer 5 is about to go to pension, this is addressed in the SEVEN release.

**Comment by iliesh** [comment]
@lmangani, where can I download the seven release?

**Comment by lmangani** [comment]
You'll have to wait still several weeks and follow our annoucements, It's not yet released as the API replacement component is in progress - this is just to confirm this issue is already addressed there.

**Comment by iliesh** [comment]
@lmangani, that's great.
Waiting for the release.
Thank You.
