### ISSUE TITLE
message parse problem with rtpengine

### ISSUE THREAD

**Issue by futsystems** [sipcapture/homer#261]
i have setup rtpengine 5.5 and Homer5
rtpengine send report to homer,
i get fail log as these 

Jan  8 10:53:49 iZbp1ddnvf7uhweomat9dbZ sipcapture[10546]: ERROR:core:parse_method: invalid character {
Jan  8 10:53:49 iZbp1ddnvf7uhweomat9dbZ sipcapture[10546]: ERROR:core:parse_msg: message=<{ "ssrc":570629018,"type":201,"report_count":1,"report_blocks":[{"source_ssrc":0,"highest_seq_no":0,"fraction_lost":0,"ia_jitter":0,"packets_lost":0,"lsr":0,"dlsr":0}],"sdes_report_count":1,"sdes_information": [ {"sdes_chunk_ssrc":570629018,"type":1,"text":"343cb@pjbd5fef.org"}] }>

Jan  8 10:53:49 iZbp1ddnvf7uhweomat9dbZ sipcapture[10546]: ERROR:core:parse_method: invalid character {
Jan  8 10:53:49 iZbp1ddnvf7uhweomat9dbZ sipcapture[10546]: ERROR:core:parse_msg: message=<{ "sender_information":{"ntp_timestamp_sec":3724397631,"ntp_timestamp_usec":1028869266,"octets":396,"rtp_timestamp":1912, "packets":12},"ssrc":570629018,"type":200,"report_count":1,"report_blocks":[{"source_ssrc":180320981,"highest_seq_no":4644,"fraction_lost":0,"ia_jitter":0,"packets_lost":0,"lsr":0,"dlsr":0}],"sdes_report_count":1,"sdes_information": [ {"sdes_chunk_ssrc":570629018,"type":1,"text":"343cb@pjbd5fef.org"}] }>

**Comment by lmangani** [comment]
If you're using a Kamailio 4 based server you're going to have to upgrade your HOMER stack. Could you confirm if this is the case?
