### ISSUE TITLE
sip_capture_call field msg length

### ISSUE THREAD

**Issue by futsystems** [sipcapture/homer#262]
Network topology:
UA1-->Proxy-->Registrar
UA1-->Proxy-->SBC-->SIP Trunk

so if sip message have many record-route,via header and so on ,message maybe bigger.

i got this error,in homer5
CRITICAL:db_mysql:wrapper_single_mysql_stmt_execute: driver error (1406): Data too long for column 'msg' at row 1

when i change the field size in table sip_capture_call_20180108 manually, it is working without error.
but the table is created day by day,so how to change this field length or which file need to change to make it work.

so maybe it is an issue when sip message is some bigger than normal.
it is better we can config the msg field length in Homer.

**Comment by sfrique** [comment]
@futsystems you can edit the table size at the script that rotates the tables. 
it's a perl script, depending on your version, it does have a conf file for it. 
Hope that helps

**Comment by futsystems** [comment]
thanks , i will look for that script to try .
