### ISSUE TITLE
captagent SIP TLS capture - <parse_tls> not found

### ISSUE THREAD

**Issue by vazir** [sipcapture/homer#264]
Hi!
I set up the captagent for SIP TLS as per documentation (--enable-tls --enable-ssl). But SIP TLS capturing does not work. protocol_tcp.so module has been built and exists in the modules dir.

Log show this line, what is suspicious:
(I use port 443, not 5061, but tested with 5061 too, regardles)

```
 [NOTICE] Using filter: (tcp port 443)
 [DEBUG] conf_function.c:453 find_export_record: found <msg_check> in module protocol_sip [/usr/local/captagent/lib/captagent/modules]
 [ERR] conf_function.c:458 find_export_record: <parse_tls> not found 
 
 parse error (7,22-23): unknown command, missing loadmodule?
 
 [DEBUG] conf_function.c:453 find_export_record: found <parse_sip> in module protocol_sip [/usr/local/captagent/lib/captagent/modules]
 ```

configuration used:
captagent.xml:
(deleted standard lines, so only modules listed)
              
```
                 <load module="transport_hep" register="local"/>
                 <load module="protocol_sip" register="local"/>
                 <load module="database_hash" register="local"/>
                 <load module="protocol_rtcp" register="local"/>
                 <load module="socket_pcap" register="local"/>
                 <load module="protocol_tcp" register="local"/>
 ```
protocol_tcp.xml
```
<?xml version="1.0"?>
<document type="captagent_module/xml">
  <module name="protocol_tcp" description="TCP Protocol" serial="2014010402">
    <profile name="proto_tcp" description="TCP PROTO" enable="true" serial="2014010402">
      <settings>
        <param name="flow-timeout" value="180"/>
        <!-- the value of private key refers to the absolute path of the key (used for decription) -->
        <param name="private-key-path" value="/usr/local/freeswitch/certs/agent.key"/>
      </settings>
    </profile>
  </module>
</document>
```

**Comment by lmangani** [comment]
Hi @vazir could you try load the ``` <load module="protocol_tcp" register="local"/>``` before the  ```<load module="socket_pcap" register="local"/>``` module and see if the error changes or disappears?

**Comment by lmangani** [comment]
@vazir could please open this issue on the [captagent repository](https://github.com/sipcapture/captagent) to chase this further and help you troubleshoot. Thanks for your report, we appreciate it!

**Comment by vazir** [comment]
@lmangani thank you. Opening an issue in the captagent repo.

**Comment by vazir** [comment]
not sure how it does influence on the TLS excahnge in meaning of using the DH, but here is the my FS (standard) ciphers setting.
```
<X-PRE-PROCESS cmd="set" data="sip_tls_ciphers=ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH"/>
```

**Comment by sangeeth-ytel** [comment]
I have a kamilio installed for registerations and for signaling . and i  have installed captagent on the same kamailio server which points to a different homer IP . But i cant see registar method capturing into the homer ip .

but when i run the command sngrep port 9000 -H udp:XXX.XX.XX.XXX:9060 i see data inserting into sip_capture_registration_20180514 tables but cant see them on the homer GUI.

please help me out if am missing anything .

**Comment by kYroL01** [comment]
@sangeeth-ytel I think your question is not correlated to this one and maybe to captagent neither.
Please open a new issue in the correct repository (it seems your problem is with the homer GUI, so open in homer repo).
Thanks
