### ISSUE TITLE
No QoS Stats - rtcp_capture blank

### ISSUE THREAD

**Issue by kierandavies** [sipcapture/homer#265]
Hi, 

I recently installed Homer 5.0.5 (Debian) with version: kamailio 4.4.6 from the install script.

Everything is working fine except for the QoS stats, I have read over the other posts but none of the steps have fixed my issue.

The database tables are being created but do not contain any data.

Would appreciate some help with this 👍 

> mysql> show tables like "rtcp_capture%";
> +--------------------------------------+
> | Tables_in_homer_data (rtcp_capture%) |
> +--------------------------------------+
> | rtcp_capture                         |
> | rtcp_capture_all_20180126            |
> | rtcp_capture_all_20180127            |
> | rtcp_capture_all_20180128            |
> | rtcp_capture_all_20180129            |
> | rtcp_capture_all_20180130            |
> | rtcp_capture_all_20180131            |
> | rtcp_capture_all_20180201            |
> | rtcp_capture_all_20180202            |
> | rtcp_capture_all_20180203            |
> | rtcp_capture_all_20180204            |
> | rtcp_capture_all_20180205            |
> +--------------------------------------+

**Comment by kierandavies** [comment]
I have enabled syslog and can see this...

> Feb  3 14:07:18 homer homerlog[6589]: RTCP Query: SELECT *,'single' as dbnode FROM rtcp_capture_all_20180203  WHERE (date BETWEEN FROM_UNIXTIME(1517662083) AND FROM_UNIXTIME(1517664574)) AND ( ( correlation_id = '4db2851b70a846c25a82c8362ff85975 @XXX.XXX.XXX.XXX:5060' OR correlation_id = '4db2851b70a846c25a82c8362ff85975 @XXX.XXX.XXX.XXX:5060_b2b-1' OR correlation_id = '4db2851b70a846c25a82c8362ff85975 @XXX.XXX.XXX.XXX:5060_b2b-' OR correlation_id = '4db2851b70a846c25a82c8362ff85975 @XXX.XXX.XXX.XXX:5060' )) LIMIT 100

Checking in MySQL I get nothing....

> mysql> select * from rtcp_capture_all_20180203;
> Empty set (0.00 sec)

**Comment by adubovikov** [comment]
Can you please check if you have been enabled non_sip_hook in the
kamailio.cfg?

**Comment by kierandavies** [comment]
Hi Alexandr, 

I am unable to locate non_sip_hook in the config... I have only found the below similar info but commenting that out and restarting Kamailio fails.

> ####### Routing Logic ########
> modparam("sipcapture", "db_url", "mysql://HOMER_DB_USER:HOMER_DB_PASSWORD@localhost/homer_data")
> modparam("sipcapture", "capture_on", 1)
> modparam("sipcapture", "hep_capture_on", 1)
> modparam("sipcapture", "insert_retries", 5)
> modparam("sipcapture", "insert_retry_timeout", 10)
> #modparam("sipcapture", "capture_node", "homer01")
> #modparam("sipcapture", "nonsip_hook", 1)

**Comment by kierandavies** [comment]
Hi Lorenzo,

I have tried both options as per the FAQ but still see nothing in the DB.

I have a feeling it isn't providing QoS as it's not seeing any traffic.

If I run this on the server I see results:
ngrep -W byline port 9060 | grep -i HEP

But if I run: 
ngrep -W byline port 9060 | grep -i jitter

I do not see anything.

**Comment by kierandavies** [comment]
Ok, I've configured a separate asterisk box and can see data in the database now, but I am still unable to see any QoS stats on the GUI.

**Comment by lmangani** [comment]
@kierandavies have you followed the wiki settings?

**Comment by kierandavies** [comment]
@lmangani - Sure, everything I try shows "no rtcp stats" in chrome console. 

I will set up a new server this evening and hopefully get better results :)

**Comment by kierandavies** [comment]
Hi, I set up a new server... same results unfortunately.

**Comment by lmangani** [comment]
So to recap - you have a setup using Kamailio 5.x, you see traffic in the database, your rtcp tables have a time suffix, and the settings for RTCP_TABLE_PARTITION are indeed correct, it probably means there is no set correlation between SIP and RTCP/RTP streams. Grab a query, and check it against the data you actually have - Could be NAT or a number of things at play.

**Comment by kierandavies** [comment]
Hi @lmangani I am currently running Kamailio 4.4.6.

I am yet to see any RTCP data on now, I only managed to capture 327778 rows until it stopped collecting for some reason.

---
version: kamailio 4.4.6 (x86_64/linux)
flags: STATS: Off, USE_TCP, USE_TLS, USE_SCTP, TLS_HOOKS, DISABLE_NAGLE, USE_MCAST, DNS_IP_HACK, SHM_MEM, SHM_MMAP, PKG_MALLOC, Q_MALLOC, F_MALLOC, TLSF_MALLOC, DBG_SR_MEMORY, USE_FUTEX, FAST_LOCK-ADAPTIVE_WAIT, USE_DNS_CACHE, USE_DNS_FAILOVER, USE_NAPTR, USE_DST_BLACKLIST, HAVE_RESOLV_RES
ADAPTIVE_WAIT_LOOPS=1024, MAX_RECV_BUFFER_SIZE 262144, MAX_LISTEN 16, MAX_URI_SIZE 1024, BUF_SIZE 65535, DEFAULT PKG_SIZE 8MB
poll method support: poll, epoll_lt, epoll_et, sigio_rt, select.
id: unknown
compiled with gcc 4.9.2
---

**Comment by lmangani** [comment]
I would honestly suggest switching to either K 5.x or OpenSIPS 2.x - there are branches in the installer repository for each, including the new homer-metrics which includes the ability to stream out statistics, to be able to use all the features. We'll drop support for K 4.x version in the next release.

**Comment by kierandavies** [comment]
Hi @lmangani - Thank you for your suggestion.

I have reinstalled using Opensips instead of Kamailio. 

ngrep port 9060 |grep -i jitter (Shows me results)

However:

mysql> select * from rtcp_capture;
Empty set (0.00 sec)

mysql> select * from rtcp_capture_all_20180208;
Empty set (0.00 sec)

**Comment by lmangani** [comment]
I'm afraid this means no RTCP packets are being sent. The issue might be on the sending part.
```ngrep -W byline port 9060 | grep -i jitter``` (or any other rtcp field) show any packets?

**Comment by kierandavies** [comment]
Yes, I see data when I ngrep on both the VoIP server and on the Homer server... 

eg)

> .........'SIP/xxx.xxxxx000c02ae.....T{"type":200,"ssrc":617759400,"report_count":1,"sender_information":{"rtp_timestamp":359696,"ntp_timestamp_sec":"1518113797","ntp_timestamp_usec":"237801","packets":2102,"octets":336320},"report_blocks":[{"source_ssrc":2089027805,"fraction_lost":0,"lsr":"312833890","packets_lost":0,"highest_seq_no":24867,"ia_jitter":3,"dlsr":19988}]}

**Comment by kierandavies** [comment]
I have noticed this when I run service opensips status:

> Feb 08 18:24:28 homer2 sipcapture[788]: ERROR:core:parse_msg: message=<{"type":200,"ssrc":1914772207,"report_count":1,"sender_information":{"rtp_timestamp":1199136,"ntp_timestamp_sec":"1518114267","ntp_timestamp_usec":"860897","packets":7342,"octets":1174720},"report_blocks":[{"source_ssrc":250044237,"fract...
> Feb 08 18:24:28 homer2 sipcapture[788]: ERROR:core:receive_msg: Unable to parse msg received from [XXX.XXX.XXX.39:13521]
> Feb 08 18:24:28 homer2 sipcapture[785]: ERROR:core:parse_msg: message=<{"type":200,"ssrc":410536354,"report_count":1,"sender_information":{"rtp_timestamp":0,"ntp_timestamp_sec":"1518114268","ntp_timestamp_usec":"249032","packets":7579,"octets":1208108},"report_blocks":[{"source_ssrc":1295356650,"fraction_lo...
> Feb 08 18:24:28 homer2 sipcapture[785]: ERROR:core:receive_msg: Unable to parse msg received from [XXX.XXX.XXX.162:23983]
> Feb 08 18:24:28 homer2 sipcapture[788]: ERROR:core:parse_msg: message=<{"type":201,"ssrc":105204402,"report_count":0,"sender_information":null,"report_blocks":[]}>
> Feb 08 18:24:28 homer2 sipcapture[788]: ERROR:core:receive_msg: Unable to parse msg received from [XXX.XXX.XXX.178:20271]
> Feb 08 18:24:28 homer2 sipcapture[788]: ERROR:core:parse_msg: message=<{"type":200,"ssrc":1327323758,"report_count":1,"sender_information":{"rtp_timestamp":20313984,"ntp_timestamp_sec":"1518114301","ntp_timestamp_usec":"294801","packets":126487,"octets":20237920},"report_blocks":[{"source_ssrc":227690915,"f...
> Feb 08 18:24:28 homer2 sipcapture[788]: ERROR:core:receive_msg: Unable to parse msg received from [XXX.XXX.XXX.7:14959]
> Feb 08 18:24:29 homer2 sipcapture[788]: ERROR:core:parse_msg: message=<{"type":200,"ssrc":1516948844,"report_count":1,"sender_information":{"rtp_timestamp":513502576,"ntp_timestamp_sec":"1518114301","ntp_timestamp_usec":"400094","packets":126981,"octets":20316180},"report_blocks":[{"source_ssrc":1175776747,...
> Feb 08 18:24:29 homer2 sipcapture[788]: ERROR:core:receive_msg: Unable to parse msg received from [XXX.XXX.XXX.7:11993]

**Comment by lmangani** [comment]
Is the RTCP profile configured and enable on your agent or are those coming from Asterisk? Definitely there is an issue, please confirm the configuration file in use.
