### ISSUE TITLE
Outdated wiki / can't manually install 

### ISSUE THREAD

**Issue by lgg** [sipcapture/homer#266]
I think wiki is really outdated

e.g: https://github.com/sipcapture/homer/wiki/Quick-Install#mysql
>Configure & Install rotation script:
But there is no `homer_rotate` script in newest release

So i can't install it further

**Comment by lmangani** [comment]
Indeed the manual process needs some love but the differences should be minimal - You need to pick either mysql or postgres options - they now have each its own [folder](https://github.com/sipcapture/homer-api/tree/master/scripts/mysql) as you can see by browsing the tree.  We're currently working on the next release so much of this will be updated once seven is ready. In the meantime, you can check out the installer scripts or Docker builders which outline the full procedure in pure bash no less.

_PS: Feel free to correct the wiki - its open for edits!_

**Comment by lmangani** [comment]
Wiki updated - please let me know if you find other blockers - Thanks!

**Comment by lgg** [comment]
@lmangani i'm not sure, but what `scripts/mysql` directory you mean?

https://github.com/sipcapture/homer/tree/master/utils/scripts

also searching for this file `homer_rotate` failed
`root@server:/usr/src/homer/homer# find . -name 'homer_rotat*'`

dir `/usr/src/homer/homer` was created after:
```
$ git clone https://github.com/sipcapture/homer.git
$ cd homer
$ git submodule init
$ git submodule update --init --recursive
$ git submodule foreach git pull origin master
```
