### ISSUE TITLE
Can't login after fresh install

### ISSUE THREAD

**Issue by lgg** [sipcapture/homer#267]
Server info:
* Ubuntu 16.04.3 LTS
* kamailio
* mysql-server
* nginx

nginx-conf:
```
server {

    listen 18080;

    #root /var/www/sipcapture/htdocs;
    root /usr/src/homer/homer/vhost;
    index index.html index.htm;

    # Make site accessible from http://localhost/
    server_name myserver.com;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api {
        include fastcgi_params;
        # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
            include fastcgi_params;
        # fastcgi_pass 127.0.0.1:9001;
        # by default there is unix socket
        fastcgi_pass unix:/var/run/php/php5.6-fpm.sock;
        fastcgi_intercept_errors on;
        fastcgi_param  SCRIPT_FILENAME $document_root/api/index.php;
        }
}
```

"cgi.fix_pathinfo = 0;" in php.ini

the owner of `/usr/src/homer/homer/vhost` and sub-dir/files is `www-data:www-data`

`http://myserver.com:18080/api/v1/test`: `Your api call works! Well done!`

file `/var/log/mysql/error.log` have no errors 
file `/var/log/php5.6-fpm.log` have no errors

Clear install from sources following https://github.com/sipcapture/homer/wiki/Quick-Install

## Steps to reproduce
Trying to log in to homer-ui
`http://myserver.com:18080/#/login`

used:
admin/test123
admin@test.com/test123

checked `schema_configuration.sql` which i used while installing:
`(1, 10, 'users,admins', 'admin', PASSWORD('test123'), 'Admin', 'Admin', 'admin@test.com', `

I also checked https://github.com/sipcapture/homer/issues/214 and https://github.com/sipcapture/homer/issues/193 but nothing from these issues seems to be helpful

also tried to disabling PHP notices(`error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE` in php.ini) as mentioned here https://github.com/sipcapture/homer/issues/193#issuecomment-255591599
it didn't help

**Comment by lgg** [comment]
ngrep -d any port 18080
```
root@server:/# ngrep -d any port 18080
interface: any
filter: (ip or ip6) and ( port 18080 )
###
T myip.xx.xxx.xx:8710 -> serv.xx.xxx.xx:18080 [A]
  ......
#
T myip.xx.xxx.xx:8710 -> serv.xx.xxx.xx:18080 [AP]
  POST /api/v1/session HTTP/1.1..Host: server.com:18080..Connection: keep-alive..Content-Length: 41..Pragma: no-cache..Cache-Control: no-cache..Accept: application/json
  , text/plain, */*..Origin: http://server.com:18080..User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 S
  afari/537.36..Content-Type: application/json;charset=UTF-8..DNT: 1..Referer: http://server.com:18080/..Accept-Encoding: gzip, deflate..Accept-Language: ru,en;q=0.9,en
  -US;q=0.8..Cookie: name=00; pass=Matrix1337Creator!; HOMERSESSID=sotip341sog4k0lg83imdtf444....
##
T myip.xx.xxx.xx:8710 -> serv.xx.xxx.xx:18080 [AP]
  {"username":"admin","password":"test123"}
##
T serv.xx.xxx.xx:18080 -> myip.xx.xxx.xx:8710 [AP]
  HTTP/1.1 404 Not Found..Server: nginx..Date: Tue, 06 Feb 2018 13:28:46 GMT..Content-Type: application/json; charset=utf-8..Transfer-Encoding: chunked..Connection:
  keep-alive..Expires: Thu, 19 Nov 1981 08:52:00 GMT..Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0..Pragma: no-cache..2: ....9c..{.
     "sid": "sotip341sog4k0lg83imdtf444",.    "auth": "false",.    "status": 404,.    "message": "bad password or username",.    "data": [.        .    ].}..0....
#
T myip.xx.xxx.xx:8710 -> serv.xx.xxx.xx:18080 [A]
  ......
```

**Comment by lmangani** [comment]
Hey @lgg the 404 message basically means the API is not correctly mapped to the homer API folder and/or its missing permissions to execute fpm php - either one. Here's a valid [vhost example](https://raw.githubusercontent.com/sipcapture/homer-config/master/docker/vhost.conf) to check against.

**Comment by lgg** [comment]
@lmangani i'm using nginx

also tried this conf:
```

```

Nginx and php-fpm is running under `www-data` user

```
root@server:/usr/src/homer/homer/vhost/api# ll
total 112
drwxr-xr-x  7 www-data www-data  4096 Feb  6 16:17 ./
drwxr-xr-x 14 www-data www-data  4096 Feb  6 14:58 ../
drwxr-xr-x  2 www-data www-data  4096 Feb  6 14:58 Authentication/
-rw-r--r--  1 www-data www-data  7338 Feb  6 14:58 autoload.php
-rw-r--r--  1 www-data www-data   967 Feb  6 14:58 configuration_example.php
-rw-r--r--  1 www-data www-data   985 Feb  6 15:08 configuration.php
-rw-r--r--  1 www-data www-data 34520 Feb  6 14:58 COPYING
drwxr-xr-x  3 www-data www-data  4096 Feb  6 14:58 Database/
-rw-r--r--  1 www-data www-data   142 Feb  6 14:58 .htaccess
-rw-r--r--  1 www-data www-data  9994 Feb  6 14:58 index.php
-rw-r--r--  1 www-data www-data  6171 Feb  6 14:58 preferences_example.php
-rw-r--r--  1 www-data www-data  6171 Feb  6 15:07 preferences.php
drwxr-xr-x  2 www-data www-data  4096 Feb  6 14:58 RestApi/
drwxr-xr-x  2 www-data www-data  4096 Feb  6 14:58 RestService/
drwxr-xr-x  2 www-data www-data  4096 Feb  6 14:58 Statistic/
```

**Comment by lmangani** [comment]
I just provided a working example to check against, if you'd like to use ```nginx``` you need to debug this problem - it is 100% php-fpm related tho. Try check the nginx logs for errors. Also make sure the ```.htaccess``` contains a compatible path.

**Comment by lgg** [comment]
@lmangani thank you so much! I forgot that i need to check `/var/log/nginx/error.log` not `/var/log/php5.6-fpm.log` !

For some reason table  homer_configuration was broken, rerunning `mysql -u root homer_configuration < $GIT/homer-api/sql/schema_configuration.sql` helped!

**Comment by lmangani** [comment]
@lgg awesome! glad you got this figured and welcome to the HOMER family!
