### ISSUE TITLE
possible to reset gui to default state?

### ISSUE THREAD

**Issue by davehorton** [sipcapture/homer#269]
I've inherited a homer installation where the webapp has some attempted customizations that seem not to be working.  I'd like to simply reset the webapp back to the default state -- without impacting preferences like the database url etc -- just reset the GUI look/feel/widgets to the default state.  Is that possible?  What would be the best way to do that?  (I am running homer-complete in Docker (/k8s) if that makes a difference)

**Comment by lmangani** [comment]
Hi @davehorton have you already attempted to start a vanilla homer-everything container, mounting the same mysql volumes of the previous one? Alternatively you could consider migrating to the multi-container version, using the same approach perhaps?

**Comment by davehorton** [comment]
No, not yet I wanted to make sure in doing so I wasn't going to somehow blow away some aspect of the data.  I'll try this now -- I am running in Kubernetes so I will just recreate my deployment (which does not include the mysql database, so that should preserve the data)
