### ISSUE TITLE
Not capturing SIP traffic to HOMER

### ISSUE THREAD

**Issue by waynemillskidals** [sipcapture/homer#272]
Hi

I am not sure where the issue lies (HOMER or CAPTAGENT) but myself and others have rebuilt our HOMER server several times and have been unable to get it working reliabley.

Server Setup
==========
Centos 7 on VMWARE
2 x NIC cards assigned (1 is the LAN, the other is promiscuous card that has port mirrored data being sent to it)

Steps Taken
===========
We have done fresh install of centos7 (minimal) and followed the following steps
  1  yum update
    2  systemctl disable firewalld
    3  systemctl stop firewalld
    4  yum install redhat-lsb-core
    5  cd /usr/src
    6  wget https://cdn.rawgit.com/sipcapture/homer-installer/master/homer_installer.sh
    7  yum install wget
    8  chmod +x homer_installer.sh
    9  wget https://cdn.rawgit.com/sipcapture/homer-installer/master/homer_installer.sh
   10  chmod +x homer_installer.sh
   11  ./homer_installer.sh
   12  yum -y install json-c-devel expat-devel libpcap-devel flex-devel automake libtool bison libuv-devel flex
   13  rpm -i https://downloads.datastax.com/cpp-driver/centos/7/dependencies/libuv/v1.8.0/libuv-1.8.0-1.el7.centos.x86_64.rpm
   14  rpm -i https://downloads.datastax.com/cpp-driver/centos/7/dependencies/libuv/v1.8.0/libuv-devel-1.8.0-1.el7.centos.x86_64.rpm
   15  yum -y install json-c-devel expat-devel libpcap-devel flex-devel automake libtool bison libuv-devel flex
   16    cd /usr/src
   17    git clone https://github.com/sipcapture/captagent.git captagent
   18    cd captagent
   19    ./build.sh
   20    ./configure
   21    make && make install
   22  cp /usr/src/captagent/init/el/captagent.sysconfig /etc/sysconfig/captagent
   23  cp /usr/src/captagent/init/el/7/captagent.service /usr/lib/systemd/system
   24  cat /usr/lib/systemd/system/captagent.service
   25  vi /usr/lib/systemd/system/captagent.service
   26  reboot
   27  systemctl status captagent
   28  systemctl start captagent
   29  systemctl status captagent
   30  yum install wireshark

When we run wireshark we on the 2nd nic with following we can see SIP Data

`[root@homer5 captagent]# tshark -i ens33
Running as user "root" and group "root". This could be dangerous.
Capturing on 'ens33'
  1 0.000000000 87.238.73.136 -> 185.109.105.6 SIP/SDP 928 Status: 200 OK | 
  2 0.000178699 14.142.34.90 -> 185.109.105.4 SIP 505 Request: ACK sip:447785266613@185.109.105.4:5060 | 
  3 0.000776040 185.109.105.4 -> 14.142.34.90 SIP/SDP 958 Status: 200 OK | 
  4 0.001026994 185.109.105.6 -> 79.99.199.211 SIP 488 Request: ACK sip:447785266613@79.99.199.211:5060 | 
  5 0.024006734 14.142.34.90 -> 185.109.105.4 SIP 521 Request: BYE sip:447784906456@185.109.105.4:5060 | 
  6 0.024599906 185.109.105.6 -> 79.99.199.211 SIP 537 Request: BYE sip:447784906456@79.99.199.211:5060 | 
  7 0.034596298 79.99.199.211 -> 185.109.105.6 SIP 547 Status: 200 OK | 
  8 0.035115021 185.109.105.4 -> 14.142.34.90 SIP 488 Status: 200 OK | 
  9 0.114423403 79.99.199.211 -> 185.109.105.6 SIP/SDP 872 Status: 180 Ringing | 
 10 0.115885047 185.109.105.5 -> 14.140.220.179 SIP/SDP 815 Status: 180 Ringing | 
 11 0.162810423 185.65.84.240 -> 185.109.105.5 SIP/SDP 973 Request: INVITE sip:01430879310@185.109.105.5:5060 | 
 12 0.163315209 185.109.105.5 -> 185.65.84.240 SIP 337 Status: 100 Trying | 
 13 0.164879584 185.109.105.6 -> 91.146.114.10 SIP/SDP 958 Request: INVITE sip:+441430879310@91.146.114.10 | 
 14 0.176531201 91.146.114.10 -> 185.109.105.6 SIP 438 Status: 100 trying -- your call is important to us | 
 15 0.186108329 87.238.72.130 -> 185.109.105.10 SIP 584 Request: BYE sip:442081613220@185.109.105.10:5060 | 
 16 0.186736132 185.109.105.5 -> 185.65.84.240 SIP 587 Request: BYE sip:02081613220@185.65.84.240:5060 | 
 17 0.187788043 14.142.34.90 -> 185.109.105.4 SIP 504 Request: ACK sip:447785734393@185.109.105.4:5060 | 
 18 0.188704571 185.109.105.6 -> 87.238.73.136 SIP 498 Request: ACK sip:87.238.73.176 | 
 19 0.203026327 185.65.84.240 -> 185.109.105.5 SIP 367 Status: 200 OK | 
`

I can see Kamailio is working 

` systemctl status kamailio
● kamailio.service - Kamailio (OpenSER) - the Open Source SIP Server
   Loaded: loaded (/usr/lib/systemd/system/kamailio.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kamailio.service.d
           └─require_mysql.conf
   Active: active (running) since Tue 2018-02-27 18:31:47 GMT; 15h ago
  Process: 1635 ExecStart=/usr/sbin/kamailio -P /var/run/kamailio/kamailio.pid -f $CFGFILE -m $SHM_MEMORY -M $PKG_MEMORY -u $USER -g $GROUP (code=exited, status=0/SUCCESS)
 Main PID: 1637 (kamailio)
   CGroup: /system.slice/kamailio.service
           ├─1637 /usr/sbin/kamailio -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 8 -u kamailio -g kamailio
           ├─1638 /usr/sbin/kamailio -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 8 -u kamailio -g kamailio
           ├─1639 /usr/sbin/kamailio -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 8 -u kamailio -g kamailio
           ├─1640 /usr/sbin/kamailio -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 8 -u kamailio -g kamailio
           ├─1641 /usr/sbin/kamailio -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 8 -u kamailio -g kamailio
           ├─1642 /usr/sbin/kamailio -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 8 -u kamailio -g kamailio
           ├─1643 /usr/sbin/kamailio -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 8 -u kamailio -g kamailio
           ├─1644 /usr/sbin/kamailio -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 8 -u kamailio -g kamailio
           ├─1645 /usr/sbin/kamailio -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 8 -u kamailio -g kamailio
           └─1646 /usr/sbin/kamailio -P /var/run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 8 -u kamailio -g kamailio

Feb 27 18:31:47 homer5.fuse2.net systemd[1]: Starting Kamailio (OpenSER) - the Open Source SIP Server...
Feb 27 18:31:47 homer5.fuse2.net kamailio[1635]: Listening on
Feb 27 18:31:47 homer5.fuse2.net kamailio[1635]: udp: 127.0.0.1:9060
Feb 27 18:31:47 homer5.fuse2.net kamailio[1635]: Aliases:
Feb 27 18:31:47 homer5.fuse2.net kamailio[1635]: udp: localhost4.localdomain4:9060
Feb 27 18:31:47 homer5.fuse2.net kamailio[1635]: udp: localhost4:9060
Feb 27 18:31:47 homer5.fuse2.net kamailio[1635]: udp: localhost.localdomain:9060
Feb 27 18:31:47 homer5.fuse2.net kamailio[1635]: udp: localhost:9060
Feb 27 18:31:47 homer5.fuse2.net systemd[1]: Started Kamailio (OpenSER) - the Open Source SIP Server.
`

AS we can observe Kamailio is listening on 9060 so we have updated the default port setting on captagent hep protocol (transport_hep.xml)
/usr/local/captagent/etc/captagent

`at transport_hep.xml
<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="transport_hep" description="HEP Protocol" serial="2014010402">
	<profile name="hepsocket" description="Transport HEP" enable="true" serial="2014010402">
	    <settings>
		<param name="version" value="3"/>
		<param name="capture-host" value="127.0.0.1"/>
		<param name="capture-port" value="9060"/>
		<param name="capture-proto" value="udp"/>
		<param name="capture-id" value="2001"/>
		<param name="capture-password" value="myhep"/>
		<param name="payload-compression" value="false"/>
	    </settings>
	</profile>
    </module>
</document>
`

Lastly we defined the 2nd NIC in the socket_pcap.xml file **<param name="dev" value="ens33"/>**

`cat socket_pcap.xml
<?xml version="1.0"?>
<document type="captagent_module/xml">
    <module name="socket_pcap" description="HEP Socket" serial="2014010402">
	<profile name="socketspcap_sip" description="HEP Socket" enable="true" serial="2014010402">
	    <settings>
		<param name="dev" value="ens33"/>
		<param name="reasm" value="false"/>
		<param name="tcpdefrag" value="false"/>
		<param name="capture-plan" value="sip_capture_plan.cfg"/>
		<param name="filter">
		    <value>port 5060</value>
		</param>
	    </settings>
	</profile>
	<profile name="socketspcap_tls" description="TLS Socket" enable="false" serial="2014010402">
	    <settings>
		<param name="dev" value="any"/>
		<param name="promisc" value="true"/>
		<param name="reasm" value="false"/>
		<param name="tcpdefrag" value="true"/>
		<param name="capture-plan" value="tcp_capture_plan.cfg"/>
		<param name="filter">
		    <value>tcp port 5061</value>
		</param>
	    </settings>
	</profile>
	<profile name="socketspcap_rtcp" description="RTCP Socket" enable="true" serial="2014010402">
	    <settings>
		<param name="dev" value="any"/>
		<param name="promisc" value="true"/>
		<param name="reasm" value="false"/>
		
		<param name="ring-buffer" value="20"/>
		
		<param name="snap-len" value="256"/>
		<param name="capture-filter" value="rtcp"/>
		<param name="capture-plan" value="rtcp_capture_plan.cfg"/>
		<param name="filter">
		    <value>portrange 10000-30000 and len >=50 </value>
		</param>
	    </settings>
	</profile>
    </module>
</document>
`

Captagent appears to be running without any issues

` systemctl status captagent
● captagent.service - SIP capture agent server daemon
   Loaded: loaded (/usr/lib/systemd/system/captagent.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2018-02-28 08:24:47 GMT; 1h 28min ago
  Process: 25021 ExecStart=/usr/local/captagent/sbin/captagent -f $CFG_FILE -d (code=exited, status=0/SUCCESS)
 Main PID: 25022 (captagent)
   CGroup: /system.slice/captagent.service
           └─25022 /usr/local/captagent/sbin/captagent -f /usr/local/captagent/etc/captagent/captagent.xml -d

Feb 28 08:24:47 homer5.fuse2.net systemd[1]: Starting SIP capture agent server daemon...
Feb 28 08:24:47 homer5.fuse2.net captagent[25021]: [NOTICE] Loaded core config
Feb 28 08:24:47 homer5.fuse2.net systemd[1]: Started SIP capture agent server daemon.
`

What is strange, when we defined the NIC (ens33) on the  socket_pcap.xml file, restarted captagent we managed to get data to show in HOMER GUI , but it stopped after 5 mins, no reason why and unable to get it running despite SIP traffic being sent to the server

**Comment by lmangani** [comment]
@waynemillskidals its not extremely clear to me what the actual problem is at the bottom line. Since there is not such thing as HOMER UI in terms of components, the element crashing might be either the webserver, database, kamailio, etc? Please clarify

**Comment by waynemillskidals** [comment]
Sorry, I meant there is no data in the DB

How can i verify which element is not working? All services are running webserver/db/kamaillio & captagent

**Comment by lmangani** [comment]
In this specific setup, Kamailio will be writing the packets to DB. So that's the point to start from. Are you positive Kamailio is NOT emitting logs/syslog errors? Seems very unlikely....

**Comment by waynemillskidals** [comment]
no errors i can see from Kamaillio - i enabled debug and see nothing that indicates any issues with Kamaillio.


My gut feel is Captagent isnt listening correctly or passing it through to Kamaillio - is there anyway to verify this?

Kam debug attached if its any use..

[kamdebug.txt](https://github.com/sipcapture/homer/files/1766808/kamdebug.txt)

**Comment by lmangani** [comment]
DO you see HEP Packets going to Kamailio on port 9060? Could there be a firewall rule dropping them?

**Comment by waynemillskidals** [comment]
i have used tshark to verify this by -i any and -i lo (loopback) is there a better way to check? either way i didn't see any 9060 packets 

`
tshark -i any port 9060
Running as user "root" and group "root". This could be dangerous.
Capturing on 'any'
^C0 packets captured
[root@homer5 log]# tshark -i lo port 9060
Running as user "root" and group "root". This could be dangerous.
Capturing on 'Loopback'
^C0 packets captured

`

**Comment by waynemillskidals** [comment]
I have used our old server that was running v4 of captagent and pointed the traffic to our new server and this is working - so it definitely appears the issues is with the new captagent v6

**Comment by lmangani** [comment]
Have you sorted this out? Please make sure you're using the latest GIT version, some patches were applied today.

**Comment by waynemillskidals** [comment]
No i haven't fixed the catpagent v6 that sits on the same server as homer... My feeling is it has issues dealing with multiple NICS... 

Currently we have it working by configuring a v4 captagent on a different server to send to the new HOMER ..  This isnt a long term solution for us as we need catagent on the new server.

I will re-try again with the latest GIT and see if the patches have helped.

IF not, i will increase debug and let you know

**Comment by robcornes** [comment]
I also have this issue and read the comments above and installed the latest version of CaptAgent. When I stream from CaptAgent on another box to kamailio it works without issue but when using CaptAgent & kamailio on a 1 box solution with 2 nics it doesn't work. Services run without issue however nothing is being captured on 9060. 

Thanks

Rob

**Comment by tandelDipak** [comment]
@waynemillskidals, I am also facing the same issue. Does anyone know how to fix it?
