### ISSUE TITLE
homer_installer.sh silent on error

### ISSUE THREAD

**Issue by udf2457** [sipcapture/homer#273]
Hi,

Am trying the `https://cdn.rawgit.com/sipcapture/homer-installer/master/homer_installer.sh` script  (Single-Node Auto-Installer (beta 5.0.1)) on CentOS 7 (3.10.0-693.17.1.el7.x86_64 #1 SMP Thu Jan 25 20:13:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux  - CentOS Linux release 7.4.1708 (Core) )

Running the script yields nothing but the pretty header and an exit code of "1".  No messages, nothing in the logs ?   Not particularly troubleshooting friendly !

**Comment by lmangani** [comment]
Thanks for the report! I ran the Kamailio 5 based installer on CentOS 7 just yesterday and had no issues - the basics are covered but the script is not designed to handle any exception in the world, so we'll need you to look into your system logs for hints. The script is just as open as the project, if you feel you can improve anything, feel absolutely welcome to!

**Comment by lmangani** [comment]
Could you kindly re-open this issue on the homer-installer repository so we can check and fix there?
