### ISSUE TITLE
CloudShark

### ISSUE THREAD

**Issue by waynemillskidals** [sipcapture/homer#274]
Hi

Is there anything else to do on cloudshark settings than adding this to preferences.api

define('CLOUD_STORAGE', 1);
define('CLOUD_STORAGE_API', "xxxxxxx44d6f049660d20c760");
define('CLOUD_STORAGE_URI', "https://www.cloudshark.org");

![screen shot 2018-03-05 at 11 13 13](https://user-images.githubusercontent.com/29538924/36972227-4763c790-2066-11e8-8943-266fff2e8569.png)

Thanks

**Comment by waynemillskidals** [comment]
im not sure if this is relevant, but we installed 5.0.5 using the install script - the preferences had no data in the preferences for CLOUD_STORAGE - i have had to insert these myself

**Comment by zachad** [comment]
(CloudShark developer here)

These preferences were originally called `CSHARK`, `CSHARK_URI` and `CSHARK_API` I'm not sure if that has changed in the last several years or not. Is this integration still supported in the latest 5.x series?

**Comment by lmangani** [comment]
@zachad yes, and thanks for joining in! I've used the integration some months ago and it was working fine, I'll take a further look see if anything needs tweaking.

**Comment by zachad** [comment]
Thanks Lorenzo! I'm happy to help debug anything on our side if you run into any problems.

**Comment by waynemillskidals** [comment]
if it helps these are the httpd logs when i press 'send to cloud'

[Mon Mar 05 14:12:21.960746 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Undefined index: node in /var/www/html/homer/api/RestApi/Search.php on line 1209, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.960930 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant BLEGTAIL - assumed 'BLEGTAIL' in /var/www/html/homer/api/RestApi/Search.php on line 1247, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.960957 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant CLEGTAIL - assumed 'CLEGTAIL' in /var/www/html/homer/api/RestApi/Search.php on line 1247, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.960979 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant BLEGTAIL - assumed 'BLEGTAIL' in /var/www/html/homer/api/RestApi/Search.php on line 1253, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.960994 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant CLEGTAIL - assumed 'CLEGTAIL' in /var/www/html/homer/api/RestApi/Search.php on line 1254, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.961010 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant BLEGTAIL - assumed 'BLEGTAIL' in /var/www/html/homer/api/RestApi/Search.php on line 1256, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.961040 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant BLEGTAIL - assumed 'BLEGTAIL' in /var/www/html/homer/api/RestApi/Search.php on line 1267, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.961057 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant CLEGTAIL - assumed 'CLEGTAIL' in /var/www/html/homer/api/RestApi/Search.php on line 1270, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.961073 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant CLEGTAIL - assumed 'CLEGTAIL' in /var/www/html/homer/api/RestApi/Search.php on line 1273, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.961089 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant BLEGTAIL - assumed 'BLEGTAIL' in /var/www/html/homer/api/RestApi/Search.php on line 1277, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.961102 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant CLEGTAIL - assumed 'CLEGTAIL' in /var/www/html/homer/api/RestApi/Search.php on line 1277, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970466 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant ethernet - assumed 'ethernet' in /var/www/html/homer/api/RestApi/Search.php on line 2349, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970543 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant ip - assumed 'ip' in /var/www/html/homer/api/RestApi/Search.php on line 2350, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970593 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant ip6 - assumed 'ip6' in /var/www/html/homer/api/RestApi/Search.php on line 2351, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970613 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant udp - assumed 'udp' in /var/www/html/homer/api/RestApi/Search.php on line 2352, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970640 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant tcp - assumed 'tcp' in /var/www/html/homer/api/RestApi/Search.php on line 2353, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970656 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant data - assumed 'data' in /var/www/html/homer/api/RestApi/Search.php on line 2354, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970674 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant total - assumed 'total' in /var/www/html/homer/api/RestApi/Search.php on line 2355, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970689 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant magic - assumed 'magic' in /var/www/html/homer/api/RestApi/Search.php on line 2360, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970704 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant version_major - assumed 'version_major' in /var/www/html/homer/api/RestApi/Search.php on line 2361, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970721 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant version_minor - assumed 'version_minor' in /var/www/html/homer/api/RestApi/Search.php on line 2362, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970736 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant thiszone - assumed 'thiszone' in /var/www/html/homer/api/RestApi/Search.php on line 2363, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970750 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant sigfigs - assumed 'sigfigs' in /var/www/html/homer/api/RestApi/Search.php on line 2364, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970765 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant snaplen - assumed 'snaplen' in /var/www/html/homer/api/RestApi/Search.php on line 2365, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970782 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant network - assumed 'network' in /var/www/html/homer/api/RestApi/Search.php on line 2366, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970927 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant dest_mac - assumed 'dest_mac' in /var/www/html/homer/api/RestApi/Search.php on line 2372, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970957 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant src_mac - assumed 'src_mac' in /var/www/html/homer/api/RestApi/Search.php on line 2372, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.970973 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Notice:  Use of undefined constant type - assumed 'type' in /var/www/html/homer/api/RestApi/Search.php on line 2372, referer: http://10.2.0.52/
[Mon Mar 05 14:12:21.972546 2018] [:error] [pid 3664] [client 10.252.0.6:54623] PHP Warning:  fopen(/var/www/html/homer/tmp//HOMER5_sip_6107592-3729247253-698216052@Q10-MANTCW-1.fuse2.net.pcap): failed to open stream: No such file or directory in /var/www/html/homer/api/RestApi/Search.php on line 2263, referer: http://10.2.0.52/

**Comment by waynemillskidals** [comment]
hi guys, just wondering if you had any chance to look at this one?

**Comment by lmangani** [comment]
@waynemillskidals could you confirm you disabled `display_errors` in your php settings?

**Comment by waynemillskidals** [comment]
Hi @lmangani I haven't made any changes as wasn't aware i needed to?
I checked this file

[root@homer5 ~]# cat /etc/php.ini |grep display_errors
; display_errors
display_errors = Off
; separately from display_errors. PHP's default behavior is to suppress those

Do i need to make a change to it? if so what ? and what output would you need from me when retesting?

Thanks
