### ISSUE TITLE
table RTCP capture

### ISSUE THREAD

**Issue by DiogoTeixeira96** [sipcapture/homer#275]
Hello,

In this moment I have the homer (version 5.0.5), kamailio (version4.4) and captagent (version6) installed on a machine, and I can capture my calls and analyse them. 
However, my data of rtcp capture, are save in the table rtcp_capture and not in the table rtcp_capture_YYYYMMDD. What I need do to resolve this? I have the next configuration:
[DATA_TABLE_TYPE_TIMESTAMP]
    #type: sip, isup, webrtc, rtcp
    sip_capture_call = sip
    sip_capture_registration = sip
    sip_capture_rest = sip
    isup_capture_all = isup
    webrtc_capture_all = webrtc
 
[DATA_TABLE_STEP]
    # 0 - Day, 1 - Hour, 2 - 30 Minutes, 3 - 15 Minutes
    sip_capture_call = 0
    sip_capture_registration = 0
    sip_capture_rest = 0
    rtcp_capture = 0
    logs_capture = 0
    report_capture = 0
    webrtc_capture_all = 0
    isup_capture_all = 0

Thanks.

**Comment by levageneral** [comment]
Hello. 
I have installed homer via docker. after last update I have same issue with RTP Qos. I'm installed new homer but have same issue.  Data saving only to table rtcp_capture but not to rtcp_capture_YYYYMMDD. Please help me how I can fix it. Thank you,

**Comment by fasa-modulis** [comment]
Same issue

**Comment by lmangani** [comment]
The difference and settings are explained in the wiki: https://github.com/sipcapture/homer/wiki/FAQ#q-i-see-no-qos-media-statistics-in-the-ui
