### ISSUE TITLE
Data table

### ISSUE THREAD

**Issue by DiogoTeixeira96** [sipcapture/homer#276]
Hello,
 
In this moment I have the homer (version 5.0.5), kamailio (version4.4) and captagent (version6) installed on a machine, and I can capture my calls and analyse them. 
Currently, my table of report_capture and logs_capture don't have any information. Why? And which are the config I need do?

Thanks

**Comment by lmangani** [comment]
I would suggest reviewing one of our past presentations to understand how to use logs and rtcp capture, those are delicate, parallel functions you can implement in a variety of ways depending on your targets, and require a good understanding of the underlying architecture and its details to make suggestions about. If you open issues on the tracker, make sure you include details such as your attempts, configurations, logs, etc or we won't be able to help.

If you need dedicated help you can contact sales@qxip.net for assistance and get your problems solved while helping sponsor the project.
