### ISSUE TITLE
Acme SBC capture agent just outputting to cent os console, not importing to Homer

### ISSUE THREAD

**Issue by osgoodr** [sipcapture/homer#279]
[root@local horaclifix-1.1.0]# ########################################################################
Headerversion: 10, Headerlength: 41, SetID: 256
Header in raw: [0 10 0 41 90 160 13 9 0 0 0 0 0 0 0 0 1 0 0 25]
n########################################################################
Headerversion: 10, Headerlength: 421, SetID: 258
Header in raw: [0 10 1 165 90 160 13 10 0 0 93 223 0 0 0 0 1 2 1 149]
########################################################################

2018/03/05 11:32:22 New IPFIX connection from sbc at 172.31.100.59:38361
2018/03/05 11:32:22 Send handshake message [0 10 0 41 90 -99 42 -58 0 0 0 0 0 0 0 0 1 1 0 25 0 1 0 0 0 124 0 0 0 0 0 0 0 0 0 0 67 90 7 2 0] to sbc at 172.31.100.59:38361
2018/03/05 11:32:25 [WARN] <sbc> write udp 172.30.8.250:42592->172.30.8.250:9090: write: connection refused
2018/03/05 11:32:25 [WARN] <sbc> write udp 172.30.8.250:42592->172.30.8.250:9090: write: connection refused

**Comment by negbie** [comment]
What is the kamailio listen ip+port? Really 172.30.8.250:9090 because horaclifix tries to send the hep traffic there.

**Comment by osgoodr** [comment]
yeah i fixed it, kamailio conf was wrong.
