### ISSUE TITLE
RTCP Qos data

### ISSUE THREAD

**Issue by levageneral** [sipcapture/homer#281]
Hello.
I have installed homer v5 via docker. after last updat I have issue with RTP Qos. I'm installed new homer but have same issue. Data saving only to table rtcp_capture but not to rtcp_capture_YYYYMMDD. Please help me how I can fix it. Thank you.
![image12121212121](https://user-images.githubusercontent.com/1182899/37604123-ea5a70e2-2b98-11e8-8fb3-99bc1578239a.png)

**Comment by gudge25** [comment]
have the same issue

**Comment by lmangani** [comment]
Wiki: https://github.com/sipcapture/homer/wiki/FAQ#q-i-see-no-qos-media-statistics-in-the-ui

**Comment by lmangani** [comment]
Please open this issue on the `homer-docker` repository in case of need - thanks for your report!
