### ISSUE TITLE
Homer5 Receive packets but no Packets on Search

### ISSUE THREAD

**Issue by xandre11** [sipcapture/homer#282]
Hi,

I have deployed HOMER 5 with Asterisk 13 with captagent6.

I can see HEP Packets sent from Asterisk towards Homer and can see charts with it.
But when i search for a call in it the search always return empty.

Do you know if this is a known bug or how can i solve it?

Thanks in advance for your help.

Alex

**Comment by lmangani** [comment]
Did you select a range from the top-right? Ie: last hour

**Comment by xandre11** [comment]
Yes, it is last 6 hours 
<img width="1391" alt="screen shot 2018-03-22 at 16 30 21" src="https://user-images.githubusercontent.com/37667349/37783879-73ad105a-2dee-11e8-8fa6-87c832823bbe.png">
<img width="1376" alt="screen shot 2018-03-22 at 16 30 09" src="https://user-images.githubusercontent.com/37667349/37783888-75de571c-2dee-11e8-8274-f6a378bb0d29.png">

**Comment by xandre11** [comment]
I've reinstalled the Homer and packets are already shown on GUI.

But now I have another problem that is:

I change the layout and adapt for my needs and after 20 seconds the change is reverted. do you know how I can overcome this?

Thanks
Alex

**Comment by lmangani** [comment]
I'm afraid I don't understand the case - I suggest to open a new ticket for this with detailes steps to reproduce. Thanks!
