### ISSUE TITLE
Error on daily rotation script

### ISSUE THREAD

**Issue by bshiers** [sipcapture/homer#283]
I've had homer deployed for about 3 months.  Now my rotate script is failing all of a sudden and I'm getting the following error when running the script (but it does seem to run manually ok): 

DBD::mysql::st execute failed: Got error 1 "Operation not permitted" from storage engine partition at ./homer_mysql_rotate.pl line 294.

Well it does purge, but my cronjob appears to have quit working.  I've made no changes to the system at all.  Here is my crontab entry: 
root /opt/sipcapture/homer_mysql_rotate > /dev/null 2>&1

Any ideas what changed all of a sudden?  I've done no updates.  Running on Debian 9.

**Comment by lmangani** [comment]
Hi @bshiers the issue seems with a `drop` based on the line but we'll need more details - what version of mysql are you running? any errors logged from mysql when this happens?

**Comment by bshiers** [comment]
I'm running Mariadb actually:
Server version: 10.1.26-MariaDB-0+deb9u1 Debian 9.1

No errors that I can find. I went in and dropped the table mysql and it worked just fine.

There are no errors in the mysql log at all.

**Comment by lmangani** [comment]
Oh.. MariaDB != Mysql tho and the stack is intended for an actual Mysql 5.7 so I'm not sure what to advice. Perhaps others will have ideas.
