### ISSUE TITLE
RFC7989 - Session-ID header support

### ISSUE THREAD

**Issue by sergey-safarov** [sipcapture/homer#284]
For correlation calls between legs is wanted [RFC7989](https://tools.ietf.org/html/rfc7989) implementation.

**Comment by lmangani** [comment]
This is already possible since a long time using the `xcid` method in HOMER which allows you to extract one (or multiple) SIP Header of your choice carrying the desired correlation ID. This shoud be well compatible with your needs: https://github.com/sipcapture/homer/wiki/Using-Homer-5#x-cid

**Comment by sergey-safarov** [comment]
@lmangani , think you not looked RFC SIP messages examples.
[10.1.  Basic Call with Two UUID](https://tools.ietf.org/html/rfc7989#section-10.1)
```
Message F1 - Session-ID: ab30317f1a784dc48ff824d0d3715d86;remote=00000000000000000000000000000000
Message F2 - Session-ID: ab30317f1a784dc48ff824d0d3715d86;remote=00000000000000000000000000000000
Message F3 - Session-ID: 47755a9de7794ba387653f2099600ef2;remote=ab30317f1a784dc48ff824d0d3715d86
Message F4 - Session-ID: 47755a9de7794ba387653f2099600ef2;remote=ab30317f1a784dc48ff824d0d3715d86
Message F5 - Session-ID: ab30317f1a784dc48ff824d0d3715d86;remote=47755a9de7794ba387653f2099600ef2
Message F6 - Session-ID: ab30317f1a784dc48ff824d0d3715d86;remote=47755a9de7794ba387653f2099600ef2
```
For basic call (without transfer, conference and etc) you have 3 different correlation values.

1. ab30317f1a784dc48ff824d0d3715d86;remote=00000000000000000000000000000000
2. 47755a9de7794ba387653f2099600ef2;remote=ab30317f1a784dc48ff824d0d3715d86
3. ab30317f1a784dc48ff824d0d3715d86;remote=47755a9de7794ba387653f2099600ef2

According docs homer can correlate message between legs when correlation header is not changed during a call.
If this possible, can you add this to documentation.

**Comment by lmangani** [comment]
I have the same feeling from this side - unless you can show us what you attempted and failed so far.

Homer performs a leg-to-leg correlation - So as long as A points to B, and B points to C, correlation is possible (with some edge limitations). You can inject any type of "correlation header" in each session leg, and use it for correlation to the previous as described in the documentation - you can even specify multiple headers. If you need something more advanced, you are more than welcome to submit a PR or a request for commercial support or custom development. Thanks!

**Comment by sergey-safarov** [comment]
FreeSwitch have added RFC7989sussport.
https://github.com/signalwire/freeswitch/commit/a9e634b6640478ccf4a6c50e0e951730acf7ce60

**Comment by zombiedk** [comment]
Question if I have a call that passes through several asterisk servers, what should the X-CID refer to
the [first,last,all] call ?

setup
all servers is running asterisk, 
for several call from and to is changing between server depenging on customer setup (E164/national/local/queue numers)
GW -> core -> PBX -> VMserver

exsample 1
call1: Call-ID=111
call2: Call-ID=222, X-CID=111
call3: Call-ID=333, X-CID=222
call4: Call-ID=444, X-CID=333
 
exsample 2
call1: Call-ID=111
call2: Call-ID=222, X-CID=111
call3: Call-ID=333, X-CID=111
call4: Call-ID=444, X-CID=111

exsample 1 (several X-CID as they relate to several calls)
call1: Call-ID=111
call2: Call-ID=222, X-CID=111
call3: Call-ID=333, X-CID=111, X-CID=222
call4: Call-ID=444, X-CID=111, X-CID=222, X-CID=333

**Comment by sergey-safarov** [comment]
I think here applicable
```
exsample 1
call1: Call-ID=111
call2: Call-ID=222, X-CID=111
call3: Call-ID=333, X-CID=222
call4: Call-ID=444, X-CID=333
```
