### ISSUE TITLE
New homer install. Can't login

### ISSUE THREAD

**Issue by mdu113** [sipcapture/homer#293]
Hello,

I've installed homer following instruction at https://github.com/sipcapture/homer/wiki/Quick-Install#-manual-setup-from-source-advanced and I cannot login.
Using default credentials (admin:test123) gives me "Email and password combination not recognized" error.
Here's what I get in the web console:

loginCtrl.js:27:22
Object { data: "", status: 500, headers: bd/<(), config: {…}, statusText: "Internal Server Error" }
authentication.js:52:13

I made sure mod_rewrite is enabled. Do you have any idea what might be wrong?

Thanks,
Michael

**Comment by mdu113** [comment]
I figured it out. Somehow I forgot to rename preferences.php. It works now. Sorry for the noise

**Comment by sergani** [comment]
Hello @mdu113 - I kinda have the same problem.
I've reloaded the DB twice to make sure all entries are there, and the preferences.php is named as it should be under api/ 

Looking at the logs in Chrome it keeps complaining about api/v1/session not found.

Any thoughts?

**Comment by mdu113** [comment]
hi,

make sure that preferences.php has correct content.
in my case i somehow managed to copy configuration.php into preferences.php, so that file existed, but had incorrect content and that was my problem.

Michael
