### ISSUE TITLE
Duplicate key violations when using postgres lead to wrong statistics

### ISSUE THREAD

**Issue by mihovilkolaric** [sipcapture/homer#294]
When using sipcapture with postgres as DBMS (using the configuration file https://github.com/sipcapture/homer-config/blob/master/db/pgsql/kamailio.cfg ), several insert statements fail, and the kamailio log is full with errors such as:

```
INFO: INSERT INTO stats_useragent_mem (useragent, method, total) VALUES('MyUserAgent', 'REGISTER', 1)
WARNING: db_postgres [km_dbase.c:254]: db_postgres_submit_query(): postgres result check failed with code 7 (PGRES_FATAL_ERROR)
WARNING: db_postgres [km_dbase.c:259]: db_postgres_submit_query(): postgres query command failed, connection status 0, error [ERROR:  duplicate key value violates unique constraint "stats_useragent_mem_useragent"
ERROR: db_postgres [km_dbase.c:267]: db_postgres_submit_query(): 0x7f8b07ba9960 PQsendQuery Error: ERROR:  duplicate key value violates unique constraint "stats_useragent_mem_useragent"
ERROR: <core> [db_query.c:181]: db_do_raw_query(): error while submitting query
ERROR: sqlops [sql_api.c:265]: sql_do_query(): cannot do the query [INSERT INTO stats_useragent_mem ]
WARNING: db_postgres [km_dbase.c:254]: db_postgres_submit_query(): postgres result check failed with code 7 (PGRES_FATAL_ERROR)
WARNING: db_postgres [km_dbase.c:259]: db_postgres_submit_query(): postgres query command failed, connection status 0, error [ERROR:  duplicate key value violates unique constraint "stats_useragent_mem_useragent"
WARNING: db_postgres [km_dbase.c:254]: db_postgres_submit_query(): postgres result check failed with code 7 (PGRES_FATAL_ERROR)
WARNING: db_postgres [km_dbase.c:259]: db_postgres_submit_query(): postgres query command failed, connection status 0, error [ERROR:  duplicate key value violates unique constraint "stats_useragent_mem_useragent"
WARNING: db_postgres [km_dbase.c:254]: db_postgres_submit_query(): postgres result check failed with code 7 (PGRES_FATAL_ERROR)
WARNING: db_postgres [km_dbase.c:259]: db_postgres_submit_query(): postgres query command failed, connection status 0, error [ERROR:  duplicate key value violates unique constraint "stats_useragent_mem_useragent"
ERROR: db_postgres [km_dbase.c:267]: db_postgres_submit_query(): 0x7f8b07ba9960 PQsendQuery Error: ERROR:  duplicate key value violates unique constraint "stats_useragent_mem_useragent"
ERROR: <core> [db_query.c:181]: db_do_raw_query(): error while submitting query
ERROR: sqlops [sql_api.c:265]: sql_do_query(): cannot do the query [INSERT INTO stats_useragent_mem ]
```

... which also results in a inaccurate statistic, as the message now is not counted.

The root cause seems to be following:
While the config for MySQL ( https://github.com/sipcapture/homer-config/blob/master/sipcapture/sipcapture.kamailio )
uses statements such as:
`sql_query("cb", "INSERT INTO stats_useragent_mem (useragent, method, total) VALUES($(ua{sql.val}), 'REGISTER', 1) ON DUPLICATE KEY UPDATE total=total+1");`
and increases the value, if already exists, the postgres-config-file does not provide such handling:
`sql_query("cb", "INSERT INTO stats_useragent_mem (useragent, method, total) VALUES($(ua{sql.val}), 'INVITE', 1) ");`
and thus only the first insertion succeeds, and all consecutive for the same UA fail.

**Comment by mihovilkolaric** [comment]
Since postgres also supports UPSERT, I´m trying to fix the issue - however, I´m not familiar with UPSERT and the table model of homer.
Is 
`sql_query("cb", "INSERT INTO stats_useragent_mem as stats (useragent, method, total) VALUES('$ua', 'INVITE', 1) ON CONFLICT (useragent, method) DO UPDATE SET total = stats.total+1 where stats.useragent = '$ua' AND stats.method = 'INVITE' ");`
the correct replacement for:
`sql_query("cb", "INSERT INTO stats_useragent_mem (useragent, method, total) VALUES($(ua{sql.val}), 'INVITE', 1) ");`
?

**Comment by morfair** [comment]
Is problem solve? Has same error with PostgreSQL and Homer 5 kamailio:
`2019-02-26 17:58:19 MSK DETAIL:  Key (useragent, method)=(Oktell 2.14.1 HCS 2.16.70.225 Mar 27 2018, INVITE) already exists.
2019-02-26 17:58:19 MSK STATEMENT:  INSERT INTO stats_useragent_mem (useragent, method, total) VALUES('Oktell 2.14.1 HCS 2.16.70.225 Mar 27 2018', 'INVITE', 1) 
2019-02-26 17:58:19 MSK ERROR:  duplicate key value violates unique constraint "stats_useragent_mem_useragent"
2019-02-26 17:58:19 MSK DETAIL:  Key (useragent, method)=(Oktell 2.14.1 HCS 2.16.70.225 Mar 27 2018, INVITE) already exists.
2019-02-26 17:58:19 MSK STATEMENT:  INSERT INTO stats_useragent_mem (useragent, method, total) VALUES('Oktell 2.14.1 HCS 2.16.70.225 Mar 27 2018', 'INVITE', 1) 
2019-02-26 17:58:19 MSK ERROR:  duplicate key value violates unique constraint "stats_useragent_mem_useragent"
2019-02-26 17:58:19 MSK DETAIL:  Key (useragent, method)=(Oktell 2.14.1 HCS 2.16.70.225 Mar 27 2018, INVITE) already exists.
2019-02-26 17:58:19 MSK STATEMENT:  INSERT INTO stats_useragent_mem (useragent, method, total) VALUES('Oktell 2.14.1 HCS 2.16.70.225 Mar 27 2018', 'INVITE', 1) 
`
