### ISSUE TITLE
HEP3 parsing errors, Kamailio 5.1.3 as sipcapture server

### ISSUE THREAD

**Issue by mishehu** [sipcapture/homer#295]
Greetings,

We recently upgraded our systems to homer 5, and are  using kamailio 5.1.3 on debian jessie as the sipcapture backend.  We're using OpenSIPS 2.4.1 also on debian jessie with proto_hep and siptrace to send the HEP3 packet over tcp to the kamailio server.  Half of the data never makes it into the database, and I see this in the kamilio logs:

Jun  1 22:20:30 dtla-homer41 homer[9214]: ERROR: <script>: HEP VERSION 3 request from 52.X.X.X:50985
Jun  1 22:20:30 dtla-homer41 homer[9214]: ERROR: <script>: HEP CHUNK Source IP 52.X.X.X request from 52.X.X.X:50985
Jun  1 22:20:30 dtla-homer41 homer[9214]: DEBUG: <core> [core/mem/q_malloc.c:363]: qm_malloc(): qm_malloc(0x7f7bcbdb8010, 136) called from sipcapture: hep.c: hepv3_get_chunk(914)
Jun  1 22:20:30 dtla-homer41 homer[9214]: DEBUG: <core> [core/mem/q_malloc.c:408]: qm_malloc(): qm_malloc(0x7f7bcbdb8010, 136) returns address 0x7f7bcbedf418 frag. 0x7f7bcbedf3e0 (size=136) on 1 -th hit
Jun  1 22:20:30 dtla-homer41 homer[9214]: DEBUG: <core> [core/mem/q_malloc.c:471]: qm_free(): qm_free(0x7f7bcbdb8010, 0x7f7bcbedf418), called from sipcapture: hep.c: hepv3_get_chunk(1069)
Jun  1 22:20:30 dtla-homer41 homer[9214]: DEBUG: <core> [core/mem/q_malloc.c:506]: qm_free(): freeing frag. 0x7f7bcbedf3e0 alloc'ed from sipcapture: hep.c: hepv3_get_chunk(914)
Jun  1 22:20:30 dtla-homer41 homer[9214]: DEBUG: <core> [core/mem/q_malloc.c:363]: qm_malloc(): qm_malloc(0x7f7bcbdb8010, 136) called from sipcapture: hep.c: hepv3_message_parse(548)
Jun  1 22:20:30 dtla-homer41 homer[9214]: DEBUG: <core> [core/mem/q_malloc.c:408]: qm_malloc(): qm_malloc(0x7f7bcbdb8010, 136) returns address 0x7f7bcbedf418 frag. 0x7f7bcbedf3e0 (size=136) on 1 -th hit
Jun  1 22:20:30 dtla-homer41 homer[9214]: DEBUG: <core> [core/mem/q_malloc.c:471]: qm_free(): qm_free(0x7f7bcbdb8010, 0x7f7bcbedf418), called from sipcapture: hep.c: hepv3_message_parse(749)
Jun  1 22:20:30 dtla-homer41 homer[9214]: DEBUG: <core> [core/mem/q_malloc.c:506]: qm_free(): freeing frag. 0x7f7bcbedf3e0 alloc'ed from sipcapture: hep.c: hepv3_message_parse(548)
Jun  1 22:20:30 dtla-homer41 homer[9214]: INFO: <core> [core/parser/parse_fline.c:144]: parse_first_line(): ERROR:parse_first_line: method not followed by SP
Jun  1 22:20:30 dtla-homer41 homer[9214]: ERROR: <core> [core/parser/parse_fline.c:257]: parse_first_line(): parse_first_line: bad message (offset: 0)
Jun  1 22:20:30 dtla-homer41 homer[9214]: DEBUG: <core> [core/parser/msg_parser.c:600]: parse_msg(): invalid message
Jun  1 22:20:30 dtla-homer41 homer[9214]: ERROR: <core> [core/parser/msg_parser.c:675]: parse_msg(): ERROR: parse_msg: message=<0#015#012Via: SIP/2.0/UDP 205.207.0.124;rport;branch=z9hG4bKcB2e5SU2rr2rc#015#012Max-Forwards: 68#015#012From: "TFFtest" <sip:123456@205.X.X.X>;tag=S3H6Bj8HScBNe#015#012To: <sip:3269@52.X.X.X:5060>;tag=5QB6rQ5X84rQr#015#012Call-ID: d54535c4-e08c-1236-65b1-525400a8231a#015#012CSeq: 123609750 ACK#015#012Content-Length: 0#015#012#015#012>
Jun  1 22:20:30 dtla-homer41 homer[9214]: ERROR: sipcapture [sipcapture.c:2975]: nosip_hep_msg(): couldn't parse sip message
Jun  1 22:20:30 dtla-homer41 homer[9214]: DEBUG: <core> [core/tcp_read.c:1328]: hep3_process_msg(): running hep3 handling event returned -1
Jun  1 22:20:30 dtla-homer41 homer[9214]: ERROR: <core> [core/tcp_read.c:1334]: hep3_process_msg(): error running hep3 handling event: -1
Jun  1 22:20:30 dtla-homer41 homer[9214]: DEBUG: <core> [core/tcp_read.c:1664]: release_tcpconn(): releasing con 0x7f7bc44780e8, state -2, fd=8, id=6 ([52.X.X.X]:50985 -> [52.X.X.X]:9061)
Jun  1 22:20:30 dtla-homer41 homer[9214]: DEBUG: <core> [core/tcp_read.c:1665]: release_tcpconn(): extra_data (nil)

The kamailio.cfg is pretty much identical to the default one for sipcapture, with the exception of changes for the tcp listener and database url.  The other differences are:

#disable_tcp=yes
tcp_accept_hep3=1
tcp_accept_no_cl=yes

On the OpenSIPS 2.4.1 that is feed data, these are the pertinent snippets:

#### HEP encapsulation protocol
loadmodule "proto_hep.so"
modparam("proto_hep", "hep_id", "[homer41] 10.X.X.41:9061; transport=tcp; version=3")
modparam("proto_hep", "homer5_on", 1)

#### siptrace module:  So that we can replicate the SIP messages to another server or to a database
loadmodule "siptrace.so"
modparam("siptrace", "trace_id", "[homer41-st]uri=hep:homer41")

sip_trace("homer41-st", "d"); gets called up in the main routing block upon an initial INVITE request.

The pcaps I captures on the wire have the data segment of the packet start with the value "HEP3" .

Please advise.  Thanks!

**Comment by adubovikov** [comment]
you have to activate nonsip hook in your kamailio.cfg

**Comment by mishehu** [comment]
That was done.  As I said, this is virtually identical to the config in kamailio 5.1.3 under src/modules/sipcapture/example

modparam("sipcapture", "db_url", "mysql://HOMER_DB_USER:HOMER_DB_PASSWORD@[client]/homer_5_data")
modparam("sipcapture", "capture_on", 1)
modparam("sipcapture", "hep_capture_on", 1)
modparam("sipcapture", "db_insert_mode", 1)
modparam("sipcapture", "insert_retries", 5)
modparam("sipcapture", "insert_retry_timeout", 60)
modparam("sipcapture", "capture_node", "homer41")
modparam("sipcapture", "nonsip_hook", 1)

And this is the event_route:

event_route[sipcapture:request] {
        xlog("received sipcapture request from $si:$sp\n");
        xlog("HEP VERSION $hep(version) request from $si:$sp\n");
        xlog("HEP CHUNK Source IP $hep(0x002) request from $si:$sp\n");

        if($hep(0x00b) == 1) {
                # Parsing is done internally
                return 1;
        } else {
                xlog("HEP CHUNK PAYLOAD $hep(0x00f) request from $si:$sp\n");
                return 0;
        }
}

If you'll note, the xlog lines are in the very beginning of that log snippet I provided in the original report.

**Comment by mishehu** [comment]
Here's an additional thought.  I even tried downgrading to kamailio 4.2.8 and using the old config we had for homer 3 (I think that was the version).  We still had the same problems with missing data in the database.  This is on debian 8.  The only Centos6 vm running kamailio 4.2.4 records the data no problem.  Have you encountered any issues with debian 8 sipcapture servers like this before?

**Comment by lmangani** [comment]
Hi @mishehu we're migrating off to our own capture servers - perhaps this is a good excuse to test a setup with `heplify-server` and see if the results change. You can find docker examples [here](https://github.com/sipcapture/homer-docker/tree/master/heplify-server)
