### ISSUE TITLE
Data too long for column 'via_1_branch'.   Failed to insert into database

### ISSUE THREAD

**Issue by JonConnor** [sipcapture/homer#296]
New install of Homer5.  Used heplify to send a PCAP into Homer.  For some sip messages received the error:
Jun  2 17:54:55 homer homer[25972]: ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query
Jun  2 17:54:55 homer homer[25972]: ERROR: sipcapture [sipcapture.c:1593]: sip_capture_store(): failed to insert into database(second attempt)
Jun  2 17:54:55 homer homer[25970]: ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Data too long for column 'via_1_branch' at row 1 (1406)

Hence the SIP flow is incomplete within the HOMER GUI.  

Same of a VIA header (I replaced the IP addresses with letter X):

Via:SIP/2.0/UDP XX.XXX.XX.X;branch=z9hG4bKBroadWorks.-1qifk68-XX.XXX.XXX.XXXV5060-0-629286764-663839900-1510939578070-

**Comment by negbie** [comment]
The quickest way would be to go into the db, alter the table and allow longer via's or even better use the text type instead varchar. The best solution at all would be to use heplify-server instead of kamailio because it will handle this for you. Before it will drop those messages it will strip them so you don't need to alter your table because of one or two messages which are to long.

**Comment by lmangani** [comment]
Hi @JonConnor 
The size of the column is defined by the [table schema](https://github.com/sipcapture/homer-api/blob/master/scripts/mysql/homer_mysql_rotate.pl#L82) and can be adjusted as you see fit for your setup

**Comment by JonConnor** [comment]
Thanks both, makes sense.  Will adjust the table schema; that should do the trick.  Thanks for tip.

**Comment by JonConnor** [comment]
Looks like that's not the problem.  'alter table' for via_1 and via_1_branch to varchar(512), which is more than enough, and still getting the same error.  

Tables that were modified:
 | sip_capture_call_20180601         |
| sip_capture_call_20180602         |
| sip_capture_call_20180603         |
| sip_capture_call_20180604         |
| sip_capture_registration_20180601 |
| sip_capture_registration_20180602 |
| sip_capture_registration_20180603 |
| sip_capture_registration_20180604 

tried sending the pcap file to Homer using capAgent instead of heplify;  Same results.

**Comment by JonConnor** [comment]
my bad, missed the following tables:

| sip_capture_rest_20180601         |
| sip_capture_rest_20180602         |
| sip_capture_rest_20180603         |
| sip_capture_rest_20180604         |

altered the columns here and the insert error went away.  Now have parsing errors (bad header fields .. seems capAgent cannot handle the P-headers, eg. P-Charging-Vector).  

different issue though, will close this one out.
