### ISSUE TITLE
webhomer: Unable to change dates in stats & dashboard

### ISSUE THREAD

**Issue by dougbtv** [sipcapture/homer#3]
### Error experienced 
In the front end, I'm getting a 

    Uncaught TypeError: Cannot read property '2' of null

On `homer.js` [line 100](https://github.com/sipcapture/homer/blob/master/webhomer/js/homer.js#L100)

Which is: 

    to_date = dateToArray[2] + '/' +dateToArray[1] + '/' +dateToArray[3];

### Steps to reproduce 

I get it when:
* In "statistics" window, changing date in panel labeled "statistic range"
* In "dashboard" when changing date in panel labeled "quick search"

No need to change the range.

Click the button to search in those contexts, and you'll see the error in your console.

...I had it in both FF & Chrome.

----

I have data showing up otherwise inside the default time range / other things appear to be generally functioning. (backend looks good, stats winding up the database)

**Comment by lmangani** [comment]
Thanks, indeed reproducible. This is caused by the default date format of the unchanged field - queued for a fix.

**Comment by dougbtv** [comment]
Awesome, thanks Lorenzo!

**Comment by lmangani** [comment]
Temporarily patched, please check latest webHomer
Note: date formats will be subject of major review in our next release and become more configurable for local preferences.

**Comment by lmangani** [comment]
Please re-open if needed.
