### ISSUE TITLE
form not working to create database information

### ISSUE THREAD

**Issue by gabyfulchic** [sipcapture/homer#301]
Hi everyone,

When i execute the ./homer_installer.sh on my fresh install centOS_7 vm at the end a form appear. that's normal but the form is looping and it asks me infinity times my host/user/passwd so what am i supposed to do ?
![homer](https://user-images.githubusercontent.com/22600727/41727514-d2733c54-7574-11e8-9280-60949b6907d0.png)

**Comment by lmangani** [comment]
Hi @gabyfulchic and welcome to the club. As the scripts very clearly states, only vanilla systems are supported. This means having an existing mysql, apache, etc will cause the procedure to fail. Could you confirm if this was your case?

**Comment by gabyfulchic** [comment]
Ok i'll try to --version every dependancies and i'll show you if ithey are running ;) but i think that's the problem ;)

**Comment by gabyfulchic** [comment]
I've got php5.4.16-45, I've got mysqld running, and httpd running but it still not working.. i'm a newbie sorry.. i'm just a trainee employee (intern) 
Do you know what should i do ?

**Comment by lmangani** [comment]
The best way is to use a net-install image and let it install all dependencies minus wget ;)

**Comment by lmangani** [comment]
If you want to make it awesome, install docker and then do:
```
git clone https://github.com/sipcapture/homer-docker
cd heplify-server/hom5-hep-prom-graf
docker-compose up
```

Boom. Full stack + Prometheus. If you prefer InfluxDB instead:
```
git clone https://github.com/sipcapture/homer-docker
cd heplify-server/hom5-hep-influx
docker-compose up
```

**Comment by gabyfulchic** [comment]
I tried installing docker but it dosen't work too.. with a vanilla systems download at https://www.centos.org/download/ with the minimal iso it doesn't work too.. 
When i'm trying with docker, i well install docker-ce via the yum repo add but when i'm starting it with : 
systemctl start docker it fails.

I'm not very lucky this days

**Comment by lmangani** [comment]
Don't give up :)
You can install docker with this script: https://github.com/rancher/install-docker/blob/master/17.03.2.sh

**Comment by gabyfulchic** [comment]
ty man ! i saw your message too late.. i've changed of OS and taken the Debian stretch ! I finally well installed docker with that tuto : https://docs.docker.com/v17.09/engine/installation/linux/docker-ce/debian/#upgrade-docker-ce

Now i'm trying to install homer ! but i'm not having the docker-compose command after every docker installs i did.. :3 
So i'm searching how to get it !

**Comment by gabyfulchic** [comment]
I got it from : https://docs.docker.com/compose/install/#install-compose
now docker-compose up is working tyy

**Comment by lmangani** [comment]
what stack/recipe have you picked?

**Comment by gabyfulchic** [comment]
#git clone https://github.com/sipcapture/homer-docker
#cd heplify-server/hom5-hep-influx

(the http variable is because sometimes my pings to google come back with 2300ms, so i want to be sure)
And i did #COMPOSE_HTTP_TIMEOUT=3000 docker-compose --verbose up
