### ISSUE TITLE
malformed header

### ISSUE THREAD

**Issue by yumminova** [sipcapture/homer#302]
hi,

i get a malformed header when trying to login:

[Sun Jun 24 08:43:22.358753 2018] [core:error] [pid 24059:tid 140530860128000] [client 109.41.64.122:14606] malformed header from script 'index.php': Bad header: 2

**Comment by lmangani** [comment]
Details are key. What version are you running, on what OS/version and how did you install it?

**Comment by yumminova** [comment]
sorry,that was not very clear indeed ))

I installed via these instructions
http://blog.ones-app.com/how-to-install-homer-sipcapture-server-in-centos-7/

The login page shows version 5.05

but the config shows

define('CONFIG_VERSION', "2.1.2"); /* Please ALWAYS include CONFIGVERSION */
define('WEBHOMER_VERSION', "5.1.3"); /* WEBHOMER VERSION */

Running Centos 7

**Comment by yumminova** [comment]
this is my apache config for the account

# vhost_start homer.removed
<VirtualHost removed0:80>
	ServerName homer.removed
	ServerAlias www.homer.removed
	ServerAdmin webmaster@homer.removed
	DocumentRoot /home/removed/public_html
	UseCanonicalName Off
	ScriptAlias /cgi-bin/ /home/removed/public_html/cgi-bin/

	# Custom settings are loaded below this line (if any exist)
	# Include "/usr/local/apache/conf/userdata/removed/homer.removed/*.conf

      <IfModule !mod_rewrite.c>
       LoadModule rewrite_module modules/mod_rewrite.so
      </IfModule>
	<IfModule mod_userdir.c>
		UserDir disabled
		UserDir enabled removed
	</IfModule>

	<IfModule mod_suexec.c>
		SuexecUserGroup xx xx
	</IfModule>

	<IfModule mod_suphp.c>
		suPHP_UserGroup xx xx
		suPHP_ConfigPath /home/xx
	</IfModule>

	<Directory "/home/xx/public_html">
		Options Indexes FollowSymLinks MultiViews
   AllowOverride All
   Order allow,deny
   allow from all
	</Directory>

</VirtualHost>
# vhost_end homer.removed

**Comment by lmangani** [comment]
Could you try disable PHP warnings?

**Comment by yumminova** [comment]
Error reporting is not on if thats what u mean, or.. i dont understand u ))
I tried to disable suphp, but no resolve

**Comment by yumminova** [comment]
it seems to be a server issue and not a homer issue, when disabling suphp the error changes ))
when loading the login screen with suphp disabled:

angular.js:12520 TypeError: Cannot read property 'grp' of undefined
    at authentication.js:73
    at angular.js:14792
    at r.$eval (angular.js:16052)
    at r.$digest (angular.js:15870)
    at r.$apply (angular.js:16160)
    at g (angular.js:10589)
    at T (angular.js:10787)
    at XMLHttpRequest.w.onload (angular.js:10728)

Pressing the signin button just makes the spinner work, but no requests made by browser due to above error

**Comment by lmangani** [comment]
I suggest using one of our guides or installers, perhaps the article you followed hardlinks a resource we moved/changed in the meantime?

**Comment by yumminova** [comment]
It just clones the git repo, im now installing on a other server via the quick install method https://github.com/sipcapture/homer/wiki/Quick-Install

**Comment by yumminova** [comment]
on that lates i could login, after disabling the firewall ))
But my existing box still not
let me check that firewall
