### ISSUE TITLE
Getting error on kamailio service status

### ISSUE THREAD

**Issue by gabyfulchic** [sipcapture/homer#303]
I'm running 2 Vm with virtualbox, One vm using homer with kamailio 5.0.7 on Debian 8 and another one running under debian 9 and being a 3cx server test to train myself. I want to use homer to capture via SIPSearch the sip packets of the 3cx server but before to do this i need my first vm to well work.

Mysql is well running without errors, apache2 too but when i hit : 
# service kamailio status ; i see that ->

![statuskamailio](https://user-images.githubusercontent.com/22600727/42022737-5625596c-7abe-11e8-8b09-fc0391713d6e.png)

I've also tried to see the kamailio log using that following command : 
![syslogkamailio](https://user-images.githubusercontent.com/22600727/42022779-6e1ada38-7abe-11e8-8569-d32e89e9cf40.png)

So, Do someone know what is happening ? i've searched before on the others issues but my error id is different than the others. 

ty :)

**Comment by games130** [comment]
i ask this question before and they told me to just ignore this error. 
Even though i have this error, it does not affect the service.
https://groups.google.com/forum/#!topic/homer-discuss/NzvhH9pcLus
