### ISSUE TITLE
Duplicate info shown on Homer-ui's SIP result html page after click search button on this result page

### ISSUE THREAD

**Issue by lauraliq** [sipcapture/homer#304]
1. No errors when I click the search button on SIP search dashboard. The SIP messages are all shown normally. please refer to picture 1 and 2.
2. However, when I click search button on the result page, lots of duplicate info are shown on the page. please refer to picture 3.
Q: Did you have the same question with me or did this kind of result acceptable?
![1](https://user-images.githubusercontent.com/38939679/42261903-37e62246-7f9c-11e8-9430-c44763ba8adc.png)
![2](https://user-images.githubusercontent.com/38939679/42261911-3ce77e7a-7f9c-11e8-9042-ff86be4a3116.png)
![3](https://user-images.githubusercontent.com/38939679/42261916-3fc3649c-7f9c-11e8-998e-f0d1a24b83bb.png)

**Comment by lmangani** [comment]
HOMER can accept as manu duplicates as its being sent, most likely you are capturing on multiple interfaces or something similar. We can't help unless we know how your're capturing data and what HEP Agents are you using.

**Comment by lauraliq** [comment]
Thanks for your quick reply firstly. Sorry for that i am not sure what the HEP agent is. But the data in our database is not duplicated. so i think the message shown on the page should not be duplicated too. Because of that the data shonw on this page should keep the same with that in database, right? Thanks

**Comment by lauraliq** [comment]
And the most strange is that the result for the first time (search on the dashboard) and the second time (search on the result page) is totally different. the duplicate is just happen on the second time search.
