### ISSUE TITLE
How to config alarm on homer-ui?

### ISSUE THREAD

**Issue by lauraliq** [sipcapture/homer#306]
hello, i have configed alarm name and type in alarm setting(please refer to picture 1
). And i changed the kamailio.cfg as alarm defined in sipcapture.kamailio. But there is nothing  shown on alarm list after i made a sip call which contains "500" error. Could you please tell me what else i should do? Thanks very much!
![1](https://user-images.githubusercontent.com/38939679/42308628-b668a054-8068-11e8-9a49-864ac5f2b67d.png)

**Comment by mantisgirl** [comment]
yeah its kinda glitch rn

**Comment by lmangani** [comment]
Hello there,

Truth is we're moving away from this model which requires plenty of expertise towards fully manageable standards - I would not invest efforts there and rather switch to the HOMER 5.9 containers w/ external timeseries for Alerting (Prometheus, InfluxDB, Elasticsearch) and compatible with the upcoming HOMER 7.x release once out of beta.

You can find HOM5 examples here: https://github.com/sipcapture/homer-docker/tree/master/heplify-server
