### ISSUE TITLE
How do I enable "GEO Stats"

### ISSUE THREAD

**Issue by sergani** [sipcapture/homer#309]
Hi, 

So i've finally got HOMER to work and can see captures on my system successfully.

There are a lot of things I can't get to work, one of which is the GEO Chart.
Whenever I access the dashboard, it gives me this error message, and displays an empty map.
`We don't have any chart data. Please enable GEO STATS in the config of your capture server.`

Any thoughts on what I should configure to enable this feature?

Thanks in advance.

**Comment by HamidrezaRamezani** [comment]
You follow below steps:

1- download "GeoLiteCity.dat.gz" package from sourceforge:
https://sourceforge.net/projects/lempelf/files/packages/GeoLiteCity.dat.gz/download
Then run below commands:
mkdir /usr/share/GeoIP
cd /usr/share/GeoIP/
mv GeoLiteCity.dat.gz GeoIPCity.dat.gz
gunzip GeoIPCity.dat.gz

2- Uncomment below line from kamailio configuration file:
vim /etc/kamailio/kamailio.cfg
##!define WITH_HOMER_GEO -> commented
#!define WITH_HOMER_GEO -> after removing one of hashtags

3- Disable ONLY_FULL_GROUP_BY in sql_mode in MySQL (for version 5.7+)
Edit your my.cnf with the following parameter
sql_mode = NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLE 
-> If it does not work, you can easily search for disabling "ONLY_FULL_GROUP_BY" in Mysql
