### ISSUE TITLE
All query debugs return "no data" even though there is 

### ISSUE THREAD

**Issue by sergani** [sipcapture/homer#310]
Hello, 

All charts are unable to view any data, and debugging them in their own widgets show the server responding with no data, like: 
`{"sid":"2981763981276392187369128","auth":"true","status":200,"message":"no data","data":[],"count":0}`

There is data however in the DB and I'm able to search for SIP calls using different parameters. 

I'm using HOMER 5.0.5 on Centos 6 with MySQL 5.6.17.

Thanks in advance.

**Comment by lmangani** [comment]
@sergani what capture server are you using? If you are on `heplify-server`  there will be no charts in 5.0.5

**Comment by sergani** [comment]
Hi @lmangani, it's heplify-server indeed. 
Can you elaborate a bit more, and if we need to have charts on the system, what options do we have?

**Comment by lmangani** [comment]
You do have charts, they are just displayed in a different (native. more powerful) UI until HOMER 7.x is completed. Take a look at the hybrid containers [here](https://github.com/sipcapture/homer-docker/tree/master/heplify-server) and specifically the [prometheus](https://github.com/sipcapture/homer-docker/tree/master/heplify-server/hom5-hep-prom-graf) one wich comes with powerful presets in Grafana.

The other option is to use the plain old HOMER 5.x w/ Kamailio or OpenSIPS with local stats.
