### ISSUE TITLE
Incorrect Displaying Call Flow

### ISSUE THREAD

**Issue by sve71** [sipcapture/homer#311]
Hi,

Something’s wrong with displaying the call flow. The thing is that not very often, but sometimes 100 Trying answer goes before INVITE request.  The call flow looks like in the picture below:
![image](https://user-images.githubusercontent.com/39119140/42873995-b8fbeeb4-8a88-11e8-8ed5-6292e393319b.png)

My HOMER server is synchronized with an NTP server.
Is it possible to fix this behavior?

Thx

**Comment by lmangani** [comment]
You must be using a capture agent < HEP3 format which lacks timestamps, so the 100 Trying is simply reaching the capture server fast due to its smaller size and appears before it. The only way out is to use HEP3 which timestamps the packets at the source. What agent are you using?

**Comment by grumvalski** [comment]
Hi,
Homer callflows are generated according to the timestamp in the captured
packets. Be sure that the servers where the capture is done are NTP
synchronised.

Best regards,

Federico

**Comment by sve71** [comment]
Thanks for your answers.
I'm using horaclifix agent, becaise the only way to get SIP traffic from our SBCs is using comm-monitor. But I thought that horaclifix work with HEP3... Ok, I'll try to come up with something.
