### ISSUE TITLE
How to re-order the sequence of dashboard on Homer?

### ISSUE THREAD

**Issue by lauraliq** [sipcapture/homer#313]
hello, i added one new dashboard. But it was numbered by a random number and locates at the bottom in the panels. How can I change the place of this new dashboard in the panels? Thanks a lot!

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
