### ISSUE TITLE
Exit delay aways after press ctrl+c

### ISSUE THREAD

**Issue by michael2009** [sipcapture/homer#314]
[DEBUG] socket_pcap.c:905 STARTING STATS....
[NOTICE] No packet drops on interface [eth0], index: [0], received: [2]
[NOTICE] No packet drops on interface [eth0], index: [1], received: [2]
[DEBUG] captagent.c:316 The Captagent is ready
[DEBUG] socket_pcap.c:865 Link offset interface type [1] [1] [14]
^C[DEBUG] captagent.c:87 The agent has been terminated
[NOTICE] unloaded module socket_pcap
^C[DEBUG] captagent.c:87 The agent has been terminated
[NOTICE] unloaded module socket_pcap
^C[DEBUG] captagent.c:87 The agent has been terminated
[NOTICE] unloaded module socket_pcap
^C[DEBUG] captagent.c:87 The agent has been terminated
[NOTICE] unloaded module socket_pcap
^C[DEBUG] captagent.c:87 The agent has been terminated
[NOTICE] unloaded module socket_pcap

**Comment by VeselaHouba** [comment]
In my experience it's not delay, but captagent won't exit at all. I always have to kill the process with sigkill to terminate it.

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
