### ISSUE TITLE
Error on the package install page 

### ISSUE THREAD

**Issue by gabyfulchic** [sipcapture/homer#315]
Hi guys,

On this web page : https://github.com/sipcapture/homer/wiki/Package-Install#-automated-installation-work-in-progress , there is mistake i think. 

When we go to the RPM tab under Automated Installation like here : 
![github_sipcapture_erreur](https://user-images.githubusercontent.com/22600727/43395968-50924266-9400-11e8-9ba1-7e0057c43248.png)

When we reach this link following link : https://cdn.rawgit.com/sipcapture/homer-installer/master/latest/homer-installer-5.0.5-1.x86_64.rpm
We get a 404 error type.

I saw that it was wrote : "work in progress" ;) 
I just say it to you to help you to know what is not working ;)

Warmly FULCHIC Gaby

**Comment by lmangani** [comment]
Thanks for your notification! Much appreciated and indeed valid point.

As discussed in other tickets, we're about to switch to the H7 branch soon and all of the above will become obsolete, so I doubt we'll have time to fix this specific guide before its gone so I think i'll remove it. FYI and anyone else reading, You can still build your own RPM if you wish by following the procedure below.

**Comment by lmangani** [comment]
Commented out the offending part from the guide - thanks @gabyfulchic
