### ISSUE TITLE
Error occur making centos7 rpm

### ISSUE THREAD

**Issue by gabyfulchic** [sipcapture/homer#316]
Hi everyone,

I've tried to install homer on my VirtualBox VM centos7 following this tuto : (build cstm pkg)
https://github.com/sipcapture/homer/wiki/Package-Install

But same using ctrl+c / ctrl+v i've got some errors after the last line.
When i make the homer centos7 rpm some errors appears.

Errors : 
![first_error_rpmbuild_homer](https://user-images.githubusercontent.com/22600727/43512927-aaf6ef0e-957c-11e8-8523-db9e2f5498ac.png)
![second_error_rpmbuild_homer](https://user-images.githubusercontent.com/22600727/43512933-aead35e0-957c-11e8-9f90-8635b2a8c590.png)
![fourth_error_rpmbuild_homer](https://user-images.githubusercontent.com/22600727/43512952-bc7f47b2-957c-11e8-8aa0-f0e0bc68687f.png)

And i'm very confused because the errors seems to concern captagent and not kamailio.
After all this errors i've tried using kamailio service but can't be found and i've tried looking in the db and no homer databases.

If you want i can give you some other informations to help me to debug.
Thanks you very much for all your help and your work.

Warmly FULCHIC Gaby

**Comment by lmangani** [comment]
Thie method is no longer supported. Closing with long delay
