### ISSUE TITLE
Error in console, search doesn't work

### ISSUE THREAD

**Issue by davidcsi** [sipcapture/homer#317]
Hello Guys,

I installed homer5 a while ago, all was looking fine.
I'm trying to query a specific call, but whatever i search nothing comes back and the following error shows up on the console:

`/api/v1/dashboard/store/search:1 Failed to load resource: the server responded with a status of 403 ()`

Anyone seen this before?

David

**Comment by lmangani** [comment]
`Your authentication token has expired. Are you behind a proxy? Does the same work if you re-login?

**Comment by davidcsi** [comment]
Yeah, same thing... See, my problem is data gets inserted properly from a new host ( I can see the packets in:

```
mysql> select count(*) from sip_capture_call_20180815 where callid = 'OGM0NzA5MWUyMDQ1ZDU3M2Q2ZGI1NzVkMmVkMWU1NzA.';
+----------+
| count(*) |
+----------+
|       11 |
+----------+
1 row in set (0.00 sec)
```

But doing the same query on the UI doesn't return anything, but if i just do a query without any params, i do get data back... it's kind of weird...

**Comment by davidcsi** [comment]
Any thoughts on this? I'm stuck :(

**Comment by lmangani** [comment]
Hi @davidcsi please switch to your browser console and grab the POST requests fired as you perform a successful (no params) vs. unsuccessful query and post them here for advice.

**Comment by davidcsi** [comment]
Hello Lorenzo,

I was trying to still figure this out... I can't.
I'm pasting the requests/response save sa HAR from a successful search and from an empty response search.



[homer5-EMPTY-RESPONSE.txt](https://github.com/sipcapture/homer/files/2424053/homer5-EMPTY-RESPONSE.txt)
[homer5-successful-search.txt](https://github.com/sipcapture/homer/files/2424054/homer5-successful-search.txt)

**Comment by davidcsi** [comment]
I'm also seeing in the console:

Failed to load resource: the server responded with a status of 403 ()

But one search works ok, while the other no.
I have to point out, the packets i can't find are all from specific nodes, all are kamailios. The data is in the table, but nothing comes back on searches or on a search with no fields.
