### ISSUE TITLE
"Export to PCAP" results in fake MAC addresses

### ISSUE THREAD

**Issue by sergani** [sipcapture/homer#318]
Hi, 

My deployment uses heplify and heplify-server. 

When i try to export to pcap, I get fake 01:01:01 and 02:02:02 mac addresses.

Is it something wrong with the capture options? 

Thanks.

**Comment by negbie** [comment]
Hi @sergani,

it's a limitation of the h5 api. I guess the ability to send mac's from hep clients to server was introduced later and before that time fixed values were used as you can see here:

https://github.com/sipcapture/homer-api/blob/master/api/RestApi/Search.php#L2384

Most likely it will be addressed in h7 api.
