### ISSUE TITLE
Unable to parse msg received from…

### ISSUE THREAD

**Issue by iamenderst** [sipcapture/homer#319]
Trying to setup Homer with a Sangoma SBC and am getting this in the Home syslog:
ERROR:core:parse_msg: message=<#015#012#015#012>
ERROR:core:receive_msg: Unable to parse msg received from…

Tried with OpenSIPS and Kamailio, same result.

**Comment by danceinrain** [comment]
hi,I have the same problem.Do you have solve the problem?

**Comment by iamenderst** [comment]
No, I just ignore it for now.

**Comment by danceinrain** [comment]
Do you have any other problems about homer?I find that some sip messages are not insert into database.And I don't know where the problem is.I choose oepnsips as my homer. Maybe my asterisk do not send hep messages to opensips.Or maybe opensips do not insert into database.

**Comment by iamenderst** [comment]
I'm using Homer with Kamailio. No other issues that i know of.
