### ISSUE TITLE
Not getting entire MIME data

### ISSUE THREAD

**Issue by rs03** [sipcapture/homer#322]
I am capturing SIP traces using Homer but in homer web interface , I don't see complete SDP offer.As displayed in image ..I am getting data till t and not after that
![image](https://user-images.githubusercontent.com/37635175/46956127-21863600-d0b2-11e8-95f2-404aaf30e4a3.png)
What needs to be changed to get entire SDP data?

**Comment by rs03** [comment]
how can I fragment data and capture fragmented data?

**Comment by lmangani** [comment]
@rs03 you need to configure your capture agent to deal with this, not HOMER which is just receiving. Depending on the agent in use, follow the instructions or open an issue on the relevant repository. Thanks!

**Comment by rs03** [comment]
@lmangani I took tcpdump at homer server and I am getting entire data at homer server . So I guess problem is when kamailio is stroing data in tables. Can you please help me in here?
