### ISSUE TITLE
search older than 10 days doesn't show any content

### ISSUE THREAD

**Issue by xandre11** [sipcapture/homer#324]
Hi Guys,

I needed to check the traces older than 10 days, I can see that stats is updated but no traces are shown.

Also the stats older than 15 days doesn't show.

Is there any limitation on timerange to show data?

we are using Homer 5 no Centos 7 server.

Thanks
Alex

**Comment by lmangani** [comment]
The rotation parameters determine what's kept and for how long. For HOMER 5 see [here](https://github.com/sipcapture/homer-api/blob/master/scripts/mysql/rotation.ini)
