### ISSUE TITLE
search doesn't work

### ISSUE THREAD

**Issue by pasanmdev** [sipcapture/homer#325]
Hi Guys,
Sometimes when I search through homer GUI it doesn't respond at all. The cogwheel keeps spinning when I press the search button.

below is the http requests/response seq I got. It happens randomly and hard to reproduce sometimes.

T 2018/10/25 13:07:31.297967 y.y.y.y:45708 -> x.x.x.x:80 [AP]
POST /api/v1/profile/store/search HTTP/1.1.
Host: voipmonitor.somewhere.com.
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0.
Accept: application/json, text/plain, */*.
Accept-Language: en-US,en;q=0.5.
Accept-Encoding: gzip, deflate.
Referer: http://voipmonitor.somewhere.com/.
Content-Type: application/json;charset=utf-8.
Content-Length: 50.
Cookie: _ga=GA1.3.1091768182.1537345466; _gcl_au=1.1.1645418759.1537423841; __utma=204933572.1091768182.1537345466.1539154038.1539686768.3; __utmc=204933572; __utmz=204933572.1539076486.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); HOMERSESSID=ci5ng5031ocsu4n3936jqjtdm2.
Connection: keep-alive.
.
{"id":"search","param":{"ruri_user":"XXXXXXXXX"}}

T 2018/10/25 13:07:31.298186 y.y.y.y:45706 -> x.x.x.x:80 [AP]
POST /api/v1/profile/store/transaction HTTP/1.1.
Host: voipmonitor.somewhere.com.
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0.
Accept: application/json, text/plain, */*.
Accept-Language: en-US,en;q=0.5.
Accept-Encoding: gzip, deflate.
Referer: http://voipmonitor.somewhere.com/.
Content-Type: application/json;charset=utf-8.
Content-Length: 31.
Cookie: _ga=GA1.3.1091768182.1537345466; _gcl_au=1.1.1645418759.1537423841; __utma=204933572.1091768182.1537345466.1539154038.1539686768.3; __utmc=204933572; __utmz=204933572.1539076486.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); HOMERSESSID=ci5ng5031ocsu4n3936jqjtdm2.
Connection: keep-alive.
.
{"id":"transaction","param":{}}

T 2018/10/25 13:07:31.298750 y.y.y.y:45710 -> x.x.x.x:80 [AP]
POST /api/v1/profile/store/result HTTP/1.1.
Host: voipmonitor.somewhere.com.
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0.
Accept: application/json, text/plain, */*.
Accept-Language: en-US,en;q=0.5.
Accept-Encoding: gzip, deflate.
Referer: http://voipmonitor.somewhere.com/.
Content-Type: application/json;charset=utf-8.
Content-Length: 68.
Cookie: _ga=GA1.3.1091768182.1537345466; _gcl_au=1.1.1645418759.1537423841; __utma=204933572.1091768182.1537345466.1539154038.1539686768.3; __utmc=204933572; __utmz=204933572.1539076486.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); HOMERSESSID=ci5ng5031ocsu4n3936jqjtdm2.
Connection: keep-alive.
.
{"id":"result","param":{"restype":{"name":"table","value":"TABLE"}}}

T 2018/10/25 13:07:31.299273 y.y.y.y:45712 -> x.x.x.x:80 [AP]
POST /api/v1/profile/store/node HTTP/1.1.
Host: voipmonitor.somewhere.com.
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0.
Accept: application/json, text/plain, */*.
Accept-Language: en-US,en;q=0.5.
Accept-Encoding: gzip, deflate.
Referer: http://voipmonitor.somewhere.com/.
Content-Type: application/json;charset=utf-8.
Content-Length: 68.
Cookie: _ga=GA1.3.1091768182.1537345466; _gcl_au=1.1.1645418759.1537423841; __utma=204933572.1091768182.1537345466.1539154038.1539686768.3; __utmc=204933572; __utmz=204933572.1539076486.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); HOMERSESSID=ci5ng5031ocsu4n3936jqjtdm2.
Connection: keep-alive.
.
{"id":"node","param":{"node":{"name":"localhost","id":"localhost"}}}

T 2018/10/25 13:07:31.320081 x.x.x.x:80 -> y.y.y.y:45708 [AP]
HTTP/1.1 200 OK.
Server: nginx/1.10.3.
Date: Thu, 25 Oct 2018 02:07:31 GMT.
Content-Type: application/json; charset=utf-8.
Transfer-Encoding: chunked.
Connection: keep-alive.
Expires: Thu, 19 Nov 1981 08:52:00 GMT.
Cache-Control: no-store, no-cache, must-revalidate.
Pragma: no-cache.
2: .
.
33.
{
    "status": 200,
    "data": [
        
    ]
}.
0.
.

T 2018/10/25 13:07:31.341340 x.x.x.x:80 -> y.y.y.y:45706 [AP]
HTTP/1.1 200 OK.
Server: nginx/1.10.3.
Date: Thu, 25 Oct 2018 02:07:31 GMT.
Content-Type: application/json; charset=utf-8.
Transfer-Encoding: chunked.
Connection: keep-alive.
Expires: Thu, 19 Nov 1981 08:52:00 GMT.
Cache-Control: no-store, no-cache, must-revalidate.
Pragma: no-cache.
2: .
.
33.
{
    "status": 200,
    "data": [
        
    ]
}.
0.
.

T 2018/10/25 13:07:31.362842 x.x.x.x:80 -> y.y.y.y:45712 [AP]
HTTP/1.1 200 OK.
Server: nginx/1.10.3.
Date: Thu, 25 Oct 2018 02:07:31 GMT.
Content-Type: application/json; charset=utf-8.
Transfer-Encoding: chunked.
Connection: keep-alive.
Expires: Thu, 19 Nov 1981 08:52:00 GMT.
Cache-Control: no-store, no-cache, must-revalidate.
Pragma: no-cache.
2: .
.
33.
{
    "status": 200,
    "data": [
        
    ]
}.
0.
.

T 2018/10/25 13:07:31.383719 x.x.x.x:80 -> y.y.y.y:45710 [AP]
HTTP/1.1 200 OK.
Server: nginx/1.10.3.
Date: Thu, 25 Oct 2018 02:07:31 GMT.
Content-Type: application/json; charset=utf-8.
Transfer-Encoding: chunked.
Connection: keep-alive.
Expires: Thu, 19 Nov 1981 08:52:00 GMT.
Cache-Control: no-store, no-cache, must-revalidate.
Pragma: no-cache.
2: .
.
33.
{
    "status": 200,
    "data": [
        
    ]
}.
0.
.

T 2018/10/25 13:07:31.557360 y.y.y.y:45708 -> x.x.x.x:80 [AP]
GET /api/v1/profile/store HTTP/1.1.
Host: voipmonitor.somewhere.com.
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0.
Accept: application/json, text/plain, */*.
Accept-Language: en-US,en;q=0.5.
Accept-Encoding: gzip, deflate.
Referer: http://voipmonitor.somewhere.com/.
Cookie: _ga=GA1.3.1091768182.1537345466; _gcl_au=1.1.1645418759.1537423841; __utma=204933572.1091768182.1537345466.1539154038.1539686768.3; __utmc=204933572; __utmz=204933572.1539076486.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); HOMERSESSID=ci5ng5031ocsu4n3936jqjtdm2.
Connection: keep-alive.
.

T 2018/10/25 13:07:31.570790 x.x.x.x:80 -> y.y.y.y:45708 [AP]
HTTP/1.1 200 OK.
Server: nginx/1.10.3.
Date: Thu, 25 Oct 2018 02:07:31 GMT.
Content-Type: application/json; charset=utf-8.
Transfer-Encoding: chunked.
Connection: keep-alive.
Expires: Thu, 19 Nov 1981 08:52:00 GMT.
Cache-Control: no-store, no-cache, must-revalidate.
Pragma: no-cache.
2: .
.
29e.
{
    "status": 200,
    "data": {
        "search": "{\\\"ruri_user\\\":\\\"XXXXXXXXX\\\"}",
        "transaction": "[]",
        "node": "{\\\"node\\\":{\\\"name\\\":\\\"localhost\\\",\\\"id\\\":\\\"localhost\\\"}}",
        "result": "{\\\"restype\\\":{\\\"name\\\":\\\"table\\\",\\\"value\\\":\\\"TABLE\\\"}}",
        "timerange": "{\\\"from\\\":\\\"2018-10-25T03:08:02.844Z\\\",\\\"to\\\":\\\"2018-10-25T06:23:02.844Z\\\",\\\"customFrom\\\":\\\"2018-10-25T03:08:02.844Z\\\",\\\"customTo\\\":\\\"2018-10-25T06:23:02.844Z\\\",\\\"custom\\\":\\\"\\\"}",
        "timezone": "{\\\"value\\\":-600,\\\"name\\\":\\\"GMT+10 AEST\\\",\\\"offset\\\":\\\"+1000\\\"}"
    }
}.
0.
.

**Comment by pasanmdev** [comment]
PS same search criteria produce output when it functions properly. I believe its not firing the required request towards the API.

**Comment by logock** [comment]
check if your other result types work. Otherwise I'd carefully check the preferences.php & configuration.php if your databases are set correctly.

does this only happen when you query for TABLE results? if so, I have the same issue using a postgres database: https://github.com/sipcapture/homer/issues/321

**Comment by pasanmdev** [comment]
@logock db connections are all good, coz it works fine when it works. I checked the query type and yes it happens to TABLE result type. I'm also using postgres db

**Comment by logock** [comment]
I can confirm from my side that it has nothing to do with resource/capacity.

**Comment by lmangani** [comment]
@logock thanks - but the fact this happens at random and unpredictably is still an indicator of resource gaps outside of HOMER. Is the database local or remote?

**Comment by logock** [comment]
On my setup it is currently remotely located but I encountered the same issues while hosting it locally. It seems to me that it has something to do with the way the homer-ui is built. Is there a way to "reload" the homer-ui or homer-api besides the dashboard refresh icon?

**Comment by pasanmdev** [comment]
@lmangani hey is homer7 out yet ? I'd like to try it out, But when I search through git hub repo I couldn't find installation procedure.
Also problem above happens most of the time, search works only sometimes to me. other result type 'pcap,text' always works fine as @logock indicated, it always break 'table' type result search.

**Comment by pasanmdev** [comment]
@Dinushasilva Thanks
@logock please checkout https://github.com/sipcapture/homer-ui/pull/106

**Comment by logock** [comment]
many thanks @pasanmdev & @Dinushasilva
