### ISSUE TITLE
Wrong date time when reading from pcap file

### ISSUE THREAD

**Issue by josenunesr93** [sipcapture/homer#328]
When reading SIP packets from .pcap files and sending them to HOMER, HOMER lists them with the date they enter the db. Is there a way to list them by the date in the SIP packet ?

**Comment by lmangani** [comment]
Depending on the HEP format the timestamp is the database entry (v1) or the original packet (v2,v3)
Please make sure your HEP client is sending using v2 or higher to your HOMER collector.
