### ISSUE TITLE
[unable to view graph]

### ISSUE THREAD

**Issue by bilalabbasi55** [sipcapture/homer#329]
Hi,
I am able to install homer via install script, everything is working perfectly, all my VoIP/FreeSWITCH servers are sending data to homer and i can see the data in homer_data database as well.
I can see the stats on the UI as well, the listing of calls are working fine, but when i try to click the CallID for callflow it does not show me anything, i can see the following errors on apache error.log

------------------------------------------------------------------------------------------------------
[Mon Dec 17 09:22:59.173535 2018] [:error] [pid 12066] [client 115.186.137.147:50141] PHP Notice:  Undefined index: node in /var/www/html/homer/api/RestApi/Report.php on line 1275, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.176057 2018] [:error] [pid 12068] [client 115.186.137.147:50140] PHP Notice:  Undefined index: node in /var/www/html/homer/api/RestApi/Report.php on line 219, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.178822 2018] [:error] [pid 12068] [client 115.186.137.147:50140] PHP Notice:  Undefined index: node in /var/www/html/homer/api/RestApi/Report.php on line 904, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.181424 2018] [:error] [pid 12068] [client 115.186.137.147:50140] PHP Notice:  Undefined offset: 0 in /var/www/html/homer/api/RestApi/Report.php on line 988, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.181469 2018] [:error] [pid 12068] [client 115.186.137.147:50140] PHP Notice:  Undefined offset: -1 in /var/www/html/homer/api/RestApi/Report.php on line 989, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.181910 2018] [:error] [pid 12068] [client 115.186.137.147:50140] PHP Notice:  Undefined index: node in /var/www/html/homer/api/RestApi/Report.php on line 561, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.183031 2018] [:error] [pid 12068] [client 115.186.137.147:50140] Fail to execute query: [SELECT *,'single' as dbnode FROM report_capture_all_20181216  WHERE (date BETWEEN FROM_UNIXTIME(1545003744) AND FROM_UNIXTIME(1545026487)) AND ( ( correlation_id = '79109dfe-7c30-1237-42a5-468cfaaa73d8' OR correlation_id = '79109dfe-7c30-1237-42a5-468cfaaa73d8_b2b-1' OR correlation_id = '79109dfe-7c30-1237-42a5-468cfaaa73d8_b2b-' OR correlation_id = '79109dfe-7c30-1237-42a5-468cfaaa73d' ) AND (type = 1 OR type = 35)) LIMIT 100], referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.183066 2018] [:error] [pid 12068] [client 115.186.137.147:50140] Array\n(\n    [0] => 42S02\n    [1] => 1146\n    [2] => Table 'homer_data.report_capture_all_20181216' doesn't exist\n)\n, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.183773 2018] [:error] [pid 12068] [client 115.186.137.147:50140] PHP Notice:  Undefined index: node in /var/www/html/homer/api/RestApi/Report.php on line 720, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.191618 2018] [:error] [pid 12068] [client 115.186.137.147:50140] PHP Notice:  Undefined index: node in /var/www/html/homer/api/RestApi/Report.php on line 392, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.197582 2018] [:error] [pid 12067] [client 115.186.137.147:50139] PHP Notice:  Undefined index: node in /var/www/html/homer/api/RestApi/Search.php on line 1403, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.197695 2018] [:error] [pid 12067] [client 115.186.137.147:50139] PHP Notice:  Undefined variable: limit in /var/www/html/homer/api/RestApi/Search.php on line 1473, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.199859 2018] [:error] [pid 12067] [client 115.186.137.147:50139] PHP Notice:  Undefined index: node in /var/www/html/homer/api/RestApi/Search.php on line 1218, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.199979 2018] [:error] [pid 12067] [client 115.186.137.147:50139] PHP Notice:  Use of undefined constant CLEGTAIL - assumed 'CLEGTAIL' in /var/www/html/homer/api/RestApi/Search.php on line 1256, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.200000 2018] [:error] [pid 12067] [client 115.186.137.147:50139] PHP Notice:  Use of undefined constant CLEGTAIL - assumed 'CLEGTAIL' in /var/www/html/homer/api/RestApi/Search.php on line 1263, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.200011 2018] [:error] [pid 12067] [client 115.186.137.147:50139] PHP Notice:  Use of undefined constant CLEGTAIL - assumed 'CLEGTAIL' in /var/www/html/homer/api/RestApi/Search.php on line 1279, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.200018 2018] [:error] [pid 12067] [client 115.186.137.147:50139] PHP Notice:  Use of undefined constant CLEGTAIL - assumed 'CLEGTAIL' in /var/www/html/homer/api/RestApi/Search.php on line 1282, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.200026 2018] [:error] [pid 12067] [client 115.186.137.147:50139] PHP Notice:  Use of undefined constant CLEGTAIL - assumed 'CLEGTAIL' in /var/www/html/homer/api/RestApi/Search.php on line 1286, referer: http://X.X.X.X/
[Mon Dec 17 09:22:59.205034 2018] [:error] [pid 12071] [client 115.186.137.147:50142] PHP Notice:  Undefined index: node in /var/www/html/homer/api/RestApi/Report.php on line 1390, referer: http://X.X.X.X/
------------------------------------------------------------------------------------------------------
I am not the PHP guy, so does not know what exactly is the issue, can somebody please give me a direction.

Thanks
Abbasi

**Comment by aqsyonas** [comment]
@bilalabbasi55 please update to homer7 which has a lot new exciting features and bug fixes.
