### ISSUE TITLE
How to data stored in MySQL 

### ISSUE THREAD

**Issue by so1n** [sipcapture/homer#331]
Hello 

I don't know homer server ip:port  and how to data stored in MySQL( HEP Capture server, Kamailio).

My rtpengine config

homer = 127.0.0.1:9060
homer-protocol = udp
homer-id = 2001

RTPengine log:  
Write error to Homer at 127.0.0.1:9066: Connection refused

**Comment by lmangani** [comment]
As you can see from your own post, HOMER listens on port 9060 but you're sending HEP to port 9066.
Try fixing the configuration as first step

**Comment by so1n** [comment]
> 正如您在自己的帖子中看到的那样，HOMER侦听端口9060但您正在将HEP发送到端口9066. 
> 尝试将配置修复为第一步

Sorry i don,t knows what is homer listen port

Where is the configuration file containing the listening port?

**Comment by lmangani** [comment]
@so1n that's configured in each HEP Server or Agent. I suggest you move to `heplify-server' to keep things simple for the capture server.

**Comment by so1n** [comment]
> 在每个HEP服务器或代理中配置的@ so1n。我建议你转到`heplify-server'来保持捕获服务器的简单性。

Thank you for your reply
