### ISSUE TITLE
Homer UI with PostgreSQL trouble

### ISSUE THREAD

**Issue by morfair** [sipcapture/homer#336]
Homer UI with PostgreSQL backend do not create new items in System Admin page. Update work good.

**Comment by aqsyonas** [comment]
@morfair Homer-UI has been depreciated in the favor of homer-app(Homer7) which contains new exciting features. You can find the installer and docker files for installation in our repository. 

https://github.com/sipcapture/homer-installer
https://github.com/sipcapture/homer7-docker

Please let us know if you have any trouble in homer7 setup.

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
