### ISSUE TITLE
exporting to pcap only messages on the same hour

### ISSUE THREAD

**Issue by descartin** [sipcapture/homer#338]
Hello all

yesterday we saw an issue, when we have a sip trace that has all messages in a same hour but the bye transaction belongs to the next hour, when exporting by clicking on the callid of one of the messages, it exports only the messages belonging to its own hour

![image](https://user-images.githubusercontent.com/7767994/53546600-10076d00-3b2d-11e9-96b7-5e71cdda91cb.png)

this is an example.
We are using homer all 7.0.4 

could you please take a look or maybe this is aknown issue? i didnt see something similar in the opened issues

thanks a lot and regards
david

**Comment by lmangani** [comment]
Please upgrade to the latest `homer-app` and version 7.7 to retest your usecase
