### ISSUE TITLE
Too long data for column 'msg' at row 1

### ISSUE THREAD

**Issue by Dazez** [sipcapture/homer#339]
Hello, I've installed homer with docket, everything works just fine, except of long messages. I am running Kamailio with WebRTC clients, so for example **INVITE** is over "the limit", but everything that is not especially long is displayed as should be.
I've altered these files, so the '**msg**' value is now **15000** everywhere I could (I tried 5000 at first): 
_rotation.ini 
rotation_kamailio4.ini
homer_mysql_rotate.pl_
I've also checked it in database, and it is altered as it should be -> in tables in homer_data database.
I've also tried to alter some tables directly, but nothing changed. 
I would be very thankful for any advice.

**log:**
 _1(346) ERROR: db_mysql [km_dbase.c:128]: db_mysql_submit_query(): driver error on query: Data too long for column 'msg' at row 1 (1406)
 1(346) ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query_

**Comment by lmangani** [comment]
Hi @Dazez you can control this from the `rotation.ini` parameters at the very end of the file you can define the default column size for the various types. I would suggest going H7 at this stage.
