### ISSUE TITLE
QoS failed INVITEs and REGISTER graphs not displayed

### ISSUE THREAD

**Issue by kemathy** [sipcapture/homer#34]
After the commit "7e9186107e0ecbb8b975ecaba56adb2ef43d20a9" (added multinode rtcp/log search) application, we don't have anymore the QoS graphs for failed INVITEs and REGISTERs.
Even if we have values in the database... 

See attached pictures as description.

Thanks, 
Kevin
![capture10](https://cloud.githubusercontent.com/assets/7022659/6263425/b361e824-b817-11e4-9c15-7be98da8b63a.jpeg)
![capture11](https://cloud.githubusercontent.com/assets/7022659/6263427/b6e66d1c-b817-11e4-9b39-6cacf5c3b797.jpeg)

**Comment by adubovikov** [comment]
please check the last git.

**Comment by kemathy** [comment]
Not better :-s ... If you need me to log the values returned by the APIs, feel free to ask, I'll make some console logs and send it to you 

Thanks, 
Kevin

**Comment by adubovikov** [comment]
sorry, but are you sure ? I just checked, with the last git, all looks good.
![image](https://cloud.githubusercontent.com/assets/4513061/6264530/0dc757c4-b825-11e4-90ea-224bf5a4c441.png)

**Comment by adubovikov** [comment]
you have to update api/class/search.php and modules/QoS/index_data.php

**Comment by kemathy** [comment]
I made a git pull, so every modified files have been pulled ;-)

Also, I'm sure values are not displayed... But after having made some debugs, I found that my calls_ko value is negative, and I don't understand why... Your calculation method is calls_ko = INVITE 200 - (INVITE TOTAL - INVITE 407), but on my opinion, I would make something like calls_ko = INVITE TOTAL - INVITE 200 - INVITE 407, no ? 

I don't know why it doesn't work anymore :-s

Kevin

**Comment by kemathy** [comment]
Here are some logged values, for example : 
[Log] call3_qos[subvite]=3027 call2_qos[subvite]=10815 call1_qos[invite]=16242 calls_ok=10815 calls_diff=13215 calls_ko=0 (index.php, line 547)

**Comment by adubovikov** [comment]
do you have any keep alive RE-INVITEs in the network ?

**Comment by kemathy** [comment]
Yep, we have some !

Kevin

**Comment by adubovikov** [comment]
here is a small problem, we can filter INVITE without totag + auth, but we couldn't detect 200 OK only for this INVITE. In your scenario, you receive 200 OK for keep alive RE-INVITES and this 200 OK goes to DB as an answer on a call. As workaround we should reset 200 OK value if it bigger than INVITE without totag. Any another suggestion ?

**Comment by adubovikov** [comment]
for BYE this will not work, because BYE will go in another stats interval if a call is longer than 5 minutes

**Comment by adubovikov** [comment]
ok, forget, we can take all INVITES+REINVITES and do sum.

the fix is comming...

**Comment by kemathy** [comment]
We can try this, maybe it'll work ;-) 

Kevin

**Comment by kemathy** [comment]
Ok, perfect, thanks a lot !

**Comment by adubovikov** [comment]
please check this git. I hope now the values should be correct.
https://github.com/sipcapture/homer/commit/f9778dda54377767917801ab7ce3aad53696a378

**Comment by kemathy** [comment]
Everything is ok ! Many thanks !

Kevin
