### ISSUE TITLE
export pcap with wrong timestamps

### ISSUE THREAD

**Issue by descartin** [sipcapture/homer#341]
Dear Alex, 

i think issue 335 was closed by mistake

i reopen a new one

**Comment by descartin** [comment]
Here you have the capture

![image](https://user-images.githubusercontent.com/7767994/56202628-c4107900-6043-11e9-914c-184af80e21ba.png)

and the text exported attached

best regards
david
[HEPIC-undefined-undefined-4_16_2019 12_30_31.txt](https://github.com/sipcapture/homer/files/3084441/HEPIC-undefined-undefined-4_16_2019.12_30_31.txt)

**Comment by adubovikov** [comment]
dont need to open a new one. Lets continue talking there
