### ISSUE TITLE
The refresh button on homer dashboard (IP Network) widgets keeps turning after click the reload button next to timerange select button

### ISSUE THREAD

**Issue by lauraliq** [sipcapture/homer#342]
I wanted to upload a snapshot about this issue, but failed. Any misunderstanding, please let me know. Thanks in advance!

**Comment by lmangani** [comment]
Hi @lauraliq I'm afraid I do not understand the issue. Could you confirm the version you're using?

**Comment by lauraliq** [comment]
Hello,

The HOMER5 WebUI version I uses is 5.0.5.

Sorry for the mis-understanding. I will clarify this issue in this email.
On Homer5 dashboard – Stats: IP Network, the three charts (HOMER Method Distribution, HOMER Packet Count, SIPCapture Charts) keep refresh and always no chart or some remind words shown on them after I clicked the refresh button on the top of right on this dashboard. You can see the snapshot below.


1.      Select the Stats: IP Network dashboard
[cid:image002.jpg@01D50EF3.29BDBD00]

2.      The snapshot of Stats: IP Network dashboard and you can see that the refresh button keep turning and nothing shown on these three charts.
[cid:image003.jpg@01D50EF3.29BDBD00]
BR,
Laura

**Comment by lmangani** [comment]
Hi,

I'm sorry, we no longer maintain version 5.x with the exception of security patches. I would suggest installing Homer 7.x and opening any issues you might find for that version. Thanks!
