### ISSUE TITLE
migrate traffic from Homer 5 to Homer 7

### ISSUE THREAD

**Issue by saydulk** [sipcapture/homer#345]
I have install H7 using your installer script into a new Linux server but not able to migrate traffic from old H5 to new H7 Linux server. Is their any helpful resource for do it?

**Comment by lmangani** [comment]
Could you be any more specific? What is preventing you from migrating traffic? All you have to do is reconfigure your agents to use the new H7 HEP socket and you should be done.

If you're trying to migrate data over, sorry - you cannot.

**Comment by saydulk** [comment]
that means support@sipcapture.org give us wrong information? we have forwarded an email at lorenzo.mangani@gmail.com please check. we are not interested to disclose this matter in public

**Comment by lmangani** [comment]
You're talking to the same person. Please don't post personal details or email addresses - thanks!
