### ISSUE TITLE
Error: Something went wrong, no JWT token received, probably wrong credentials used to login

### ISSUE THREAD

**Issue by saydulk** [sipcapture/homer#346]

**Comment by saydulk** [comment]
How to change default user name and password for homer 7 app. 
username 'admin' and password 'sipcapture'

![Screenshot from 2019-05-22 06-50-54](https://user-images.githubusercontent.com/1058663/58139741-f6724f00-7c5d-11e9-9515-28db365a643b.png)

**Comment by aqsyonas** [comment]
@saydulk you can change the password in the seeds/01_Users.js file. After changes you need to run below command for the effect. Please let us know if you are still unable to login. 

`knex seed:run`

**Comment by lmangani** [comment]
@saydulk If the authentication does not work, make sure your database is up and running and no errors were reported by `homer-app` while initializing. Once logged in, you can of course also change those from the HOMER User-Interface via the Preferences menu.

**Comment by saydulk** [comment]
Thanks all for reply :)
@lmangani i am using postgresql working fine 

@aqsyonas when i run $ knex seed:run it shows

[homerdev@ip-172-31-50-13 seeds]$ knex seed:run
Working directory changed to ~/homer-app
Using environment: development
Error: Error while executing "/home/homerdev/homer-app/seeds/06_HepSubmapping.js" seed: Error while executing "/home/homerdev/homer-app/seeds/05_AgentLocation.js" seed: Error while executing "/home/homerdev/homer-app/seeds/04_Globalsettings.js" seed: Error while executing "/home/homerdev/homer-app/seeds/03_Dashboard.js" seed: Error while executing "/home/homerdev/homer-app/seeds/02_Mapping.js" seed: Error while executing "/home/homerdev/homer-app/seeds/01_Users.js" seed: Ident authentication failed for user "homer_user"
    at Object.current.then.then.catch.originalError (/home/homerdev/homer-app/node_modules/knex/lib/seed/Seeder.js:138:21)
Error: Error while executing "/home/homerdev/homer-app/seeds/05_AgentLocation.js" seed: Error while executing "/home/homerdev/homer-app/seeds/04_Globalsettings.js" seed: Error while executing "/home/homerdev/homer-app/seeds/03_Dashboard.js" seed: Error while executing "/home/homerdev/homer-app/seeds/02_Mapping.js" seed: Error while executing "/home/homerdev/homer-app/seeds/01_Users.js" seed: Ident authentication failed for user "homer_user"
    at Object.current.then.then.catch.originalError (/home/homerdev/homer-app/node_modules/knex/lib/seed/Seeder.js:138:21)
Error: Error while executing "/home/homerdev/homer-app/seeds/04_Globalsettings.js" seed: Error while executing "/home/homerdev/homer-app/seeds/03_Dashboard.js" seed: Error while executing "/home/homerdev/homer-app/seeds/02_Mapping.js" seed: Error while executing "/home/homerdev/homer-app/seeds/01_Users.js" seed: Ident authentication failed for user "homer_user"
    at Object.current.then.then.catch.originalError (/home/homerdev/homer-app/node_modules/knex/lib/seed/Seeder.js:138:21)
Error: Error while executing "/home/homerdev/homer-app/seeds/03_Dashboard.js" seed: Error while executing "/home/homerdev/homer-app/seeds/02_Mapping.js" seed: Error while executing "/home/homerdev/homer-app/seeds/01_Users.js" seed: Ident authentication failed for user "homer_user"
    at Object.current.then.then.catch.originalError (/home/homerdev/homer-app/node_modules/knex/lib/seed/Seeder.js:138:21)
Error: Error while executing "/home/homerdev/homer-app/seeds/02_Mapping.js" seed: Error while executing "/home/homerdev/homer-app/seeds/01_Users.js" seed: Ident authentication failed for user "homer_user"
    at Object.current.then.then.catch.originalError (/home/homerdev/homer-app/node_modules/knex/lib/seed/Seeder.js:138:21)
Error: Error while executing "/home/homerdev/homer-app/seeds/01_Users.js" seed: Ident authentication failed for user "homer_user"
    at Object.current.then.then.catch.originalError (/home/homerdev/homer-app/node_modules/knex/lib/seed/Seeder.js:138:21)
error: Ident authentication failed for user "homer_user"
    at Connection.parseE (/home/homerdev/homer-app/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/home/homerdev/homer-app/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/home/homerdev/homer-app/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
![Screenshot from 2019-05-22 16-28-55](https://user-images.githubusercontent.com/1058663/58167849-b7201e80-7cae-11e9-81d4-db6749e3b6d7.png)

**Comment by aqsyonas** [comment]
@saydulk could you please check if database connection details are correct in the config.js file. 
 
https://github.com/sipcapture/homer-app/blob/master/server/config.js#L3
https://github.com/sipcapture/homer-app/blob/master/server/config.js#L5

**Comment by saydulk** [comment]
@aqsyonas yes sir. database connection is correct in the config.js file

sudo -u postgres psql
postgres=# create database homer;
postgres=# create user masum with encrypted password '01722gausia';
postgres=# grant all privileges on database homer to masum;
![Screenshot from 2019-05-22 17-45-22](https://user-images.githubusercontent.com/1058663/58172169-a1fcbd00-7cb9-11e9-99c9-d5b5ad115fb5.png)


const pgsql = {
  host: 'localhost',
  user: 'masum',
  port: 5432,
  password: '01722gausia',
  charset: 'utf8',
  timezone: 'utc',
  pool: {
    afterCreate: function(connection, callback) {
      connection.query('SET timezone = "UTC";', function(err) {
        callback(err, connection);
      });
    },
  },
};

**Comment by lmangani** [comment]
I would suggest dropping the homer database, removing the `bootstrapped` file and letting `homer-app` recreate and provision the tables again, watching for errors or failures in the process.

**Comment by saydulk** [comment]
@lmangani  i drop homer database and remove bootstrapped file and run:
$ knex migrate:latest
$ knex seed:run

when i run $ npm start dev i see white screen not homer page now also see this :

[homerdev@ip-172-31-50-13 homer-app]$ npm start dev

> homer-app@1.0.7 start /home/homerdev/homer-app
> node bootstrap.js "dev"

Error was handled!
{ Error: listen EADDRINUSE 0.0.0.0:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at doListen (net.js:1501:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 443 }
Server started
Debug: handler, error 
    {"msec":1.9741970002651215,"error":"Not Found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found","message":"Not Found"},"headers":{}},"message":"Not Found"}}

FYI, their are 5 vulnerabilities required manual review and could not be updated using $ npm audit fix

![Screenshot from 2019-05-24 04-43-55](https://user-images.githubusercontent.com/1058663/58291784-7fb18f00-7de0-11e9-8434-8fd7249eb75b.png)

**Comment by aqsyonas** [comment]
@saydulk did you build the application using below command? Because I see that missing from your above commands. 
`npm run build`
Everything should be working fine if you have followed the instructions in README.

**Comment by aparajey** [comment]
Hi, i was also facing same issue but when i installed it with binary it started working but now heplify is not starting up

**Comment by saydulk** [comment]
@aqsyonas yes i did and get this 

[homerdev@ip-172-31-50-13 homer-app]$ cat /home/homerdev/.npm/_logs/2019-05-26T20_30_21_874Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/homerdev/.nvm/versions/node/v8.9.1/bin/node',
1 verbose cli   '/home/homerdev/.nvm/versions/node/v8.9.1/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.9.1-next.0
3 info using node@v8.9.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle homer-app@1.0.7~prebuild: homer-app@1.0.7
6 info lifecycle homer-app@1.0.7~build: homer-app@1.0.7
7 verbose lifecycle homer-app@1.0.7~build: unsafe-perm in lifecycle true
8 verbose lifecycle homer-app@1.0.7~build: PATH: /home/homerdev/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/homerdev/homer-app/node_modules/.bin:/home/homerdev/.nvm/versions/node/v8.9.1/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/homerdev/.local/bin:/home/homerdev/bin
9 verbose lifecycle homer-app@1.0.7~build: CWD: /home/homerdev/homer-app
10 silly lifecycle homer-app@1.0.7~build: Args: [ '-c',
10 silly lifecycle   'rimraf public/dist && webpack --bail --progress --profile' ]
11 silly lifecycle homer-app@1.0.7~build: Returned: code: 1  signal: null
12 info lifecycle homer-app@1.0.7~build: Failed to exec build script
13 verbose stack Error: homer-app@1.0.7 build: `rimraf public/dist && webpack --bail --progress --profile`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/homerdev/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/homerdev/.nvm/versions/node/v8.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid homer-app@1.0.7
15 verbose cwd /home/homerdev/homer-app
16 verbose Linux 4.14.114-105.126.amzn2.x86_64
17 verbose argv "/home/homerdev/.nvm/versions/node/v8.9.1/bin/node" "/home/homerdev/.nvm/versions/node/v8.9.1/bin/npm" "run" "build"
18 verbose node v8.9.1
19 verbose npm  v6.9.1-next.0
20 error code ELIFECYCLE
21 error errno 1
22 error homer-app@1.0.7 build: `rimraf public/dist && webpack --bail --progress --profile`
22 error Exit status 1
23 error Failed at the homer-app@1.0.7 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by aqsyonas** [comment]
@saydulk I would say start with given installer-script available on the repository on freshly installed Debian 9/Centos7 distro. 

https://github.com/sipcapture/homer-installer

**Comment by saydulk** [comment]
@aqsyonas Homer 7 is running fine on Amazon Linux 2 AMI and i have used this url for setup https://github.com/sipcapture/homer-app/blob/master/docs/dev/README.md

My problem is in step 3: Provision migrations and defaults to database:

knex migrate:latest
knex seed:run  

For this I am not able to use login : admin/sipcapture

Error: Something went wrong, no JWT token received, probably wrong credentials used to login

Thanks 
![Screenshot from 2019-05-28 01-08-44](https://user-images.githubusercontent.com/1058663/58436027-2c438780-80e5-11e9-8a6f-a37ae3de8a38.png)

**Comment by aqsyonas** [comment]
@saydulk looks homer-app is unable to connect to the database. Please double check your database connection settings. Looks like the interface from which homer-app is trying to connect to the database is not allowed. Maybe you need to allow loopback access to Postgres. Something similar to below commands. 

` sed -i 's/\(host  *all  *all  *127.0.0.1\/32  *\)ident/\1md5/' /var/lib/pgsql/10/data/pg_hba.conf
  sed -i 's/\(host  *all  *all  *::1\/128  *\)ident/\1md5/' /var/lib/pgsql/10/data/pg_hba.con`

And then restart of database.

**Comment by saydulk** [comment]
@aqsyonas thanks for your valuable help. its working now

![Screenshot from 2019-05-29 04-40-39](https://user-images.githubusercontent.com/1058663/58517091-00e79800-81cc-11e9-9f11-932276409789.png)

**Comment by aqsyonas** [comment]
Glad to hear that. :)

Br, Aqs.
