### ISSUE TITLE
Error while login.

### ISSUE THREAD

**Issue by aparajey** [sipcapture/homer#348]
i installed homer7 in debian9, everything seems to be working fine but on login screen i get error: Something went wrong, no JWT token received, probably wrong credentials used to login.

i checked and found homer is not creating homer database in postgres 
![Uploading Screenshot 2019-05-26 at 1.34.47 PM.png…]()
![Uploading Screenshot 2019-05-26 at 1.36.28 PM.png…]()

**Comment by negbie** [comment]
Hi @aparajey. Thats strange. Even when knex fails to create the db's + tables heplify-server should do it too. Did you use docker? Could you please post some logs here from docker or heplify-server.

**Comment by aparajey** [comment]
i am doing fresh install not using docker. upon various trial and error i managed to get everything running but now sip packets are not getting captured, i checked firewall it is disabled i checked on server it is working fine but still it is not showing capture.

**Comment by negbie** [comment]
Please change inside heplify-server.toml
LogLvl                = "info"
to
LogLvl                = "debug"

Check if you receive packets.

**Comment by aparajey** [comment]
i changed it to LogLvl= "debug" and restarted it but still no packets showing on dashboard.

**Comment by negbie** [comment]
Good now look into the heplify-server.log and see if you get some packets? Changing log level to debug won't fix anything but give you more details in the log file.

**Comment by aparajey** [comment]
nope still nothing.
![Screenshot 2019-05-27 at 3 15 16 PM](https://user-images.githubusercontent.com/23430485/58411645-5e77c980-8092-11e9-89b5-6c37ef4f2031.png)

it shows 0 HEP

**Comment by negbie** [comment]
This means no packets flows into port 9060. Check you sender side.

**Comment by negbie** [comment]
Which hep clients/sender do you use?

**Comment by aparajey** [comment]
i am using ASTPP for sending HEP packet, as i see it is sending HEP packets and it is correctly pointed.

**Comment by negbie** [comment]
Well you can see that nothing hits port 9060 and the host with heplify-server running. You can confirm this with tcpdump, sngrep or ngrep.

**Comment by aparajey** [comment]
yes it appears to be not receiving any packets from ASTPP, let me check and tweak it

**Comment by negbie** [comment]
Does the sender use UDP, TCP or TLS?

**Comment by aparajey** [comment]
i tweaked in sip profile and now i am seeing packet capture in homer. 

thanks a lot now everything working fine
