### ISSUE TITLE
Issue in "Correlation Mapping"

### ISSUE THREAD

**Issue by leongnaw8** [sipcapture/homer#349]
Hello,

In Correlation Mapping Tab, there are 2 default records such like below:
[
  {
    "source_field": "data_header.callid",
    "lookup_id": 100,
    "lookup_profile": "default",
    "lookup_field": "sid",
    "lookup_range": [
      -300,
      200
    ]
  },
  {
    "source_field": "data_header.callid",
    "lookup_id": 5,
    "lookup_profile": "default",
    "lookup_field": "sid",
    "lookup_range": [
      -300,
      200
    ]
  }
]

If I deleted one of them, then when I tried to add it back, it does not work after I click save...
Pls help check.
Thanks!

**Comment by negbie** [comment]
https://github.com/sipcapture/homer-app/issues/135

**Comment by lmangani** [comment]
Please upgrade to the latest `homer-app` and version 7.7 to retest
