### ISSUE TITLE
The definition of "lookup_range" in the Correlation Mapping?

### ISSUE THREAD

**Issue by TaurusXY** [sipcapture/homer#350]
How to define the lookup_range? I can see the default value is [-300, 200].
Does it mean that when search the table in database, it will check 300 tables backward and 200 tables onward?

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/wiki/Examples:-Correlation-MAPPING

lookup_range = this is time range

**Comment by TaurusXY** [comment]
Thanks!  but I am still a little confused about the definition: "timerange (original) from+=-300, to+=200".  Does it mean 300,200 seconds or 300, 200 record entries or something else?

**Comment by lmangani** [comment]
@TaurusXY lookup range is expressed in seconds and gets [converted to MS](https://github.com/sipcapture/homer-app/blob/a92e126d46caef1d84330634e46338947c31b7e4/server/classes/settings.js#L252) when used in combination with the original timestamp being correlated against, ie:
```
let FromTs = fromts + lookupRange[0]*1000;
let ToTs = tots + lookupRange[1]*1000;
```

I hope this helps!
