### ISSUE TITLE
homer5 quick install script

### ISSUE THREAD

**Issue by aparajey** [sipcapture/homer#351]
Hello,

does anyone have homer5 quick install script. i tried homer7 and it is is really giving hard time homer5 was very easy and it worked like charm in one shot in homer 7 i am stuck with past 5 days and now everything working good but it isn't capturing any SIP packets from my servers.

Thank You

**Comment by negbie** [comment]
You don't need and install script for that. Just follow this steps
https://github.com/sipcapture/heplify-server/tree/master/example/install/homer5

**Comment by negbie** [comment]
Since this is not really an issue, close.
