### ISSUE TITLE
What's the meaning of partid?

### ISSUE THREAD

**Issue by TaurusXY** [sipcapture/homer#352]
Hello,

I noticed there is a field named "partid" in the "mapping settings" , "Advanced settings" and "User settings".

![image](https://user-images.githubusercontent.com/49503708/58543433-0d9ed700-8232-11e9-917a-7561e9979dc7.png)

![image](https://user-images.githubusercontent.com/49503708/58543475-214a3d80-8232-11e9-8f77-f7f5b952916e.png)

![image](https://user-images.githubusercontent.com/49503708/58543527-36bf6780-8232-11e9-8d87-7a6b6fe3f12d.png)

Could you please give more explanation about this field? what is it used for?

Thanks,
TaurusXY

**Comment by adubovikov** [comment]
This is group of settings. Lets say it's a partion id of settings for different group of users

**Comment by lmangani** [comment]
Hi @TaurusXY great question - this is a future feature placeholder. 
Currently not affecting much unless intentionally used in queries.

**Comment by TaurusXY** [comment]
OK, Thanks so much your quick response!
