### ISSUE TITLE
Homer7 Stack Documentation

### ISSUE THREAD

**Issue by gabrielmangieri** [sipcapture/homer#353]
Per Lorenzo Mangani's request, I am opening this issue in order to help develop the documentation for Homer7.  I plan to post on this issue each piece of the documentation as I write them out in an attempt to make it easy to build and collate later.

I look forward to contributing my help and knowledge to this wonderful project.  Thank you!

-Gabriel

**Comment by lmangani** [comment]
Hi @gabrielmangieri I've created this Wiki page as a starting point. Please confirm you can edit with some dummy content, and we can directly work on the public version this way.

https://github.com/sipcapture/homer/wiki/homer-seven-setup

Thanks for your time donation!

**Comment by gabrielmangieri** [comment]
Lorenzo,

Github support unlocked my account and I was able to edit the Wiki page.  I
added the first piece, which is the HEPlify Capture component.

I'd appreciate your feedback before I continue.

Thank you.
-Gabriel

**Comment by bilalabbasi55** [comment]
Hi @gabrielmangieri it is looking great. Thanks for the effort it means a lot to us.
Please continue your good work. 
Thanks.

**Comment by gabrielmangieri** [comment]
Can you please let me know where I can upload images to, in order to add them to the Wiki documentation?

Thank you.

**Comment by lmangani** [comment]
Hi @gabrielmangieri images can be hosted anywhere external (imgur is my preferred) or as part of an [issue thread](https://github.com/sipcapture/homer/issues/271) hosted on github which is my current approach. Feel free to chain on the link above at will, you can simply drag images into issues and github will convert to a markdown link

**Comment by gabrielmangieri** [comment]
Lorenzo,

I appreciate the information and I'll use that in the future.

I believe I'm done with my documentation for now.  I would very much appreciate either yourself, or someone from your team read through it once to make sure it's accurate.  If you have any suggestions or comments please let me know so I can address them.  I want to make sure the documentation is as complete as possible.

On another note, I had some suggestions regarding the way some of the Homer components are working and I'm hoping you're open to those suggestions.  If so, please let me know if you'd like me to open a new issue for that discussion, or should we continue on this one?

Thank you very much for allowing me to help and be a part of this amazing project.  It has helped me tremendously and I'm hoping it will help many other people as well.

-Gabriel

**Comment by gabrielmangieri** [comment]
Hi all,

To follow-up, can we please start a discussion regarding optimizing the Homer web app, along with the SQL database?  I'd very much like to help get this working more efficiently.

Please let me know who I can work with to help with this.

Thank you!
-Gabriel

**Comment by gabrielmangieri** [comment]
Please disregard my previous comment.  I am not a database guru, and therefore didn't understand that the values were being stored in JSON format.

Thank you.

**Comment by lmangani** [comment]
Please upgrade to the latest `homer-app` and version 7.7 to retest - and thanks for helping us documenting the platform!
