### ISSUE TITLE
kamailio.cfg example: correlation_id for RTCP should be escaped

### ISSUE THREAD

**Issue by mtryfoss** [sipcapture/homer#354]
..like this:
$var(correlation_id) = $(hep(0x011){s.escape.common});

SIP call-id might contain single quotes ('), which will cause sql insert failure and open up for sql injection.

**Comment by lmangani** [comment]
Thanks - would you kindly submit a PR on the relevant code?

**Comment by mtryfoss** [comment]
What is the correct path here on github for the kamailio.cfg example, used in the release? There are so many repositories, branches and trees.
