### ISSUE TITLE
Does HOMER7 support MySQL?

### ISSUE THREAD

**Issue by leonwangcn** [sipcapture/homer#355]
Hello,

Here is the HOMER7 code for DB connector:
= = =
    if shema == "homer5" && driver != "mysql" {
        return fmt.Errorf("homer5 has only mysql support")
    }
    if shema == "homer7" && driver != "postgres" {
        return fmt.Errorf("homer7 has only postgres support")
}
= = = =
Does this mean, HOMER7 only supports postgresql? I remember it supports MySQL as well, right?

Thanks,
Leon

**Comment by lmangani** [comment]
@leonwangcn at this time HEPlify-server only supports the above. There are no plans to support MySQL in HOMER7 but it should be quite easy to implement if desirable by contributors.
