### ISSUE TITLE
SIPP with Homer 

### ISSUE THREAD

**Issue by bmfmancini** [sipcapture/homer#357]
Hello Everyone

I have recently installed the HOMER package on a fresh debian image we are using SIPP for testing between sites 

Is it required to use kamielio or can homer its self capture the sip packets as they come in to the server ?

Current the install of Homer works fine I am in the UI but when we test with SIPP the calls come in you can capture the traffic with tshark but there is nothing in the homer ui

I have also installed the captagent on the same server as the homerui and configured it to go to localhost on port 9060 but still the UI shows no captures 

Any help would be appreciated 

Thanks !

**Comment by lmangani** [comment]
Hi @bmfmancini if you're using H7 you don't need any external elements other than a HEP Agent such as HEPlify or CaptAgent. Make sure you have capture rights, no firewall rules/SELINUX, etc which might prevent delivery - this is the case for CentOS for instance. 

If you can see the packets with say, ngrep, our agents shall too.

Hope this helps!

**Comment by bmfmancini** [comment]
Thanks ! 

I still dont know what I am missing here I have now 2 servers both running SIPP - the testing tool not a typo lol 

I have tshark captures on both and I see the SIP call taking place and hear the audio but homer still doesnt pick anything up 

In my capture plans I have the defaults for SIP 

No firewalls
No selinux 

Any help would be appreciated ! 
Thanks !

**Comment by lmangani** [comment]
We can't help without details. Tell us what ports you're using and what config you're running and perhaps we'll spot the difference?

**Comment by bmfmancini** [comment]
Sorry Here is my setup

I used the bash script installation on a vanilla debian 9 server
I have hpelify going to port 9060

root@localhost:/opt/homer-app/server# ss -pn | grep 9060
udp    ESTAB      0      0      127.0.0.1:42240              127.0.0.1:9060                users:(("heplify",pid=15058,fd=6))
root@localhost:/opt/homer-app/server#

Homer main dashboard is not showing clear 

![image](https://user-images.githubusercontent.com/13388748/60916766-408ab080-a25d-11e9-8578-8710628fcfd8.png)

I have SIPP in server mode on this same server  it is handling multiple calls I have captured all of the sip traffic coming into the server via tshark 

Here is my DB info 

classes  config.js  private  routes  server.js
root@localhost:/opt/homer-app/server# cat config.js
const pgsql = {
  host: 'localhost',
  user: 'homer',
  port: 5432,
  password: 'HASH REMOVED',
  charset: 'utf8',
  timezone: 'utc',
  pool: {
    afterCreate: function(connection, callback) {
      connection.query('SET timezone = "UTC";', function(err) {
        callback(err, connection);
      });
    },
  },
};

const mysql = {
  host: 'localhost',
  user: 'homer',
  password: 'HASH REMOVED',
  charset: 'utf8',
  timezone: 'utc',
  pool: {
    afterCreate: function(connection, callback) {
      connection.query('SET time_zone = "+00:00";', function(err) {
        callback(err, connection);
      });
    },
  },
};

const influxdb = {
  host: 'influxdb',
  port: 8086,
  database: 'homer'
}

const prometheus = {
  protocol: 'http',
  host: 'prometheus',
  port: 9090,
  api: '/api/v1/'
}

const ldapauth = {
   url: 'ldap://127.0.0.1:389',
   strictDN: true,
   dn: 'dc=qxip,dc=net',
   userdn: 'uid=%USERNAME%',
   filter: '(uid=%USERNAME%)',
   scope: 'sub',
   uidNumber: 'uidNumber',
   tls: false
}

export default {
  http_host: '0.0.0.0',
  http_port: 80,
  https_host: '0.0.0.0',
  https_port: 443,
  certificate: {
    self_signed: true,
    days: 1,
  },
  auth: {
    internal: true,

The script i used is located here https://github.com/sipcapture/homer-installer

**Comment by lmangani** [comment]
I would suggest a quick `hepgen.js` execution to make sure the data makes it into the db
```
git clone https://github.com/sipcapture/hepgen.js
cd hepgen.js
npm install
npm start -s 127.0.0.1 -p 9060 -c ./config/b2bcall_rtcp.js
```

Once completed, go in Homer and search w/o filters in the last Hour. You should find two legs.

If this works, proceed and check the configuration of your agent. You might have misconfigured the capture device, portrange, or anything in between causing the SIPP traffic not to be captured. 
I assume your SIPP flow is using port 5060? If not, you'll need to reflect this in your HEP agent config.
