### ISSUE TITLE
Homer 7 - No data in UI

### ISSUE THREAD

**Issue by Largehawiian** [sipcapture/homer#358]
I've newly installed Homer 7 and have the capture agent running.
ngrep shows HEP data coming to the Homer server 
I can see data in the postgres database but nothing is displayed in the UI.

Any help is appreciated.
Thanks

**Comment by lmangani** [comment]
Hi,

Have you selected a time-range from the Top-Right menu?

**Comment by sebky94** [comment]
Hello, 

I have kind of the same issue, i don't see any DATA displayed in the UI. 

HOMER 7 server is UP and running, HEPlify agent displays data only using "./heplify -i any -hs "" -e" on screen, but i don't see any data on the UI of the server when i try to send DATA to the server using : "./heplify -i any -hs IPofserver:9060".

Though i don't know how to check if there is data coming to homer server nor data on postgres.  Could you please tell me how to do it? 

@lmangani should i open a seperate issue for this?

Thank you.

**Comment by lmangani** [comment]
Please upgrade to the latest `homer-app` and version 7.7 to retest - your issue should be resolved!
