### ISSUE TITLE
Homer not displaying information

### ISSUE THREAD

**Issue by omarioja** [sipcapture/homer#359]
I am able to do a tcpdump on my homer server and capture incoming data from my pbx, however it is not showing up on the web interface. i can look in stream and see the data but it just will not show up in mu homer interface. 

Any ideas

**Comment by aqsyonas** [comment]
@omarioja did you try to change your time range and see if that worked for you? please check your timezone settings.

**Comment by omarioja** [comment]
@aqsyonas my time zone is set to my local time TZ='America/Jamaica', still nothing.

**Comment by aqsyonas** [comment]
@omarioja could you test your system with hepgen and see if you get any data on UI. 

https://github.com/sipcapture/hepgen.js

**Comment by omarioja** [comment]
@aqsyonas Dont know if i am doing the correct thing. I could not find config.js so i created a file and place the setting withing. I then install npm and did a npm start and go this error. 
 
sh: nodejs: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! hepgen@1.0.5 start: `nodejs hepgen.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the hepgen@1.0.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Also how do i know if Homer is connect to the correct datasource.

**Comment by omarioja** [comment]
@aqsyonas  ok so i just figured out how to send the test data and still nothing. Any ideas?

**Comment by omarioja** [comment]
@aqsyonas I alos loged into postgres and did a SELECT * from hep_proto_100_default; and it show the test data, but not my data that should be coming in.

**Comment by omarioja** [comment]
@aqsyonas ok i did some more digging and was able to find data from my pbx reaching the database. SELECT * from hep_proto_1_call.

**Comment by aqsyonas** [comment]
@omarioja could you please check your browser console, if you get any error. Make sure the firewall(selinux/iptables)is not blocking data.

**Comment by VolhaRS** [comment]
I have the same problem. In database i can see data, in dashboard - nothing. Use heplify-server as agent and dashboard version 5.9.
In  browser console in network i can see reponse with data, but in UI i cannot it see.

![image](https://user-images.githubusercontent.com/52915455/64849141-66488300-d61b-11e9-8545-a42d2eb614f9.png)

**Comment by aqsyonas** [comment]
@VolhaRS homer5 is long obsoleted and no longer supported. I would recommend installing homer7.

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
