### ISSUE TITLE
How to get QOS tab

### ISSUE THREAD

**Issue by bmfmancini** [sipcapture/homer#360]
Hey Guys 

Not a bug

Just wondering If I am missing something I am new to Homer and was able to capture calls but I am not seeing a QOS tab am I missing something ?

**Comment by bmfmancini** [comment]
Oh BTW i am using homer 7.0.4

**Comment by lmangani** [comment]
Hi @bmfmancini this really depends on the agents and what they're feeding HOMER. The data displayed changes and QoS and Log tabs really only show when there's data to be displayed.

What agents are you using and how are they configured?

NOTE: closing Issue as non bug but feel free to continue troubleshooting here!

**Comment by bmfmancini** [comment]
Hey Thanks ! 

I am using the captagent  it is currently sending the SIP info 
I am using SIPP to simulate calls to test network latency

**Comment by lmangani** [comment]
The QoS tab depends on RTP/RTCP information, assuming you are sending actual RTP/RTCP I'm guessing the CaptAgent instance is not able to either capture or correlate any. You could try give HEPlify a shot, as it uses a different approach.

**Comment by bmfmancini** [comment]
ok will try that out ! 
thanks !

**Comment by bmfmancini** [comment]
Ok i am using hpelify but still no QOS the Pcap I am using to make the test call does in deed have a pcap packet in it 

im confused as to where I am going wrong

**Comment by lmangani** [comment]
This is designed for real traffic - there might be a myriad of reasons as of why the SIPP scenario does not work, namely not having RTCP packets perhaps?
