### ISSUE TITLE
unable to gather error="reading text format failed: text format parsing error in line 1: invalid metric name"

### ISSUE THREAD

**Issue by unridaz** [sipcapture/homer#361]
Hello,

I'm using centos 7, I just installed homer using the "kamailio script". I don't know if its worth noting, but while I used the kamailio script, Kamailio is not actually running, looks like I'm using Heplify-Server instead, if that's correct/makes sense?  

I am also using Fusionpbx on Centos 7 and I installed and configured CaptAgent there.

My setup appears to be working as far as sending messages from CaptAgent to Heplify-Server... That is... on the Heplify-Server machine, I'm getting what appears to be logged messages that the server was unable to write data to the database:

lvl=error msg="unable to gather" error="reading text format failed: text format parsing error in line 1: invalid metric name"

Either something wrong with the inital data being sent, or something wrong with the way Heplify-Server is trying to write to influx.

Any suggestions/ next steps for me?

Thanks!

**Comment by lmangani** [comment]
Please upgrade to the latest `homer-app` and version 7.7 to retest - your issue should be resolved!
