### ISSUE TITLE
does possiable Homer join to ldap or active directory server for authenticate user 

### ISSUE THREAD

**Issue by salehhoushangi** [sipcapture/homer#362]
Hi . I'm new in Homer . my question is how to authenticate user in Homer from AD server or any support from ldap protocol available or not?If yes please tell me in detail  how and what requirement need to do it.

**Comment by aqsyonas** [comment]
@salehhoushangi yes homer does provide ldap authentication out of the box. You need to add ldap configurations in config.js file. 
https://github.com/sipcapture/homer-app/blob/master/server/config.js#L45-L53
and then need to put ldap instead of internal at below location. 

https://github.com/sipcapture/homer-app/blob/master/server/config.js#L65

**Comment by salehhoushangi** [comment]
@aqsyonas sorry. could you give me information in detail and step by step to join Homer to active directory. i couldn't found any config.js in my source directory to replace it . if possible please give me a document to do this job . thank you for advise .

**Comment by aqsyonas** [comment]
@salehhoushangi I hope you are using homer7, in that case, it should be at location `/opt/homer-app/server/config.j`

I have already explained to you the process, provided you with lines that you need to change. Please, change them according to your LDAP configurations. if you see any issue you can ask here.

**Comment by salehhoushangi** [comment]
@aqsyonas Unfortunately, I am currently using the older version of 5.0.5. so is there a solution and document to the problem in this version ?

**Comment by aqsyonas** [comment]
@salehhoushangi version 7 is stable and latest and should only be used.

**Comment by salehhoushangi** [comment]
@aqsyonas You mean in previous versions this(LDAP) is not supported?

**Comment by salehhoushangi** [comment]
is any solution to over come this problem in version  5.0.5?

**Comment by salehhoushangi** [comment]
@aqsyonas in fact we have lot of config and data to capture  customers traffic in our server .so please guide me to activate LDAP module in our server without any upgrade process and if not possible best secure way to upgrade server to Homer7 with out any manipulating in our data.

**Comment by aqsyonas** [comment]
@salehhoushangi please check homer google group and old(closed) issues related to homer5 ldap authentication on homer repository.
A quick search gives me this link, 
https://groups.google.com/forum/#!topic/homer-discuss/tXG4fK7E1OQ

**Comment by salehhoushangi** [comment]
@aqsyonas thanks for advise.but  my problem still exist. Should there be any changes other than this file(preferences.php)? Or delete a database  especial table as homer mention in(https://github.com/sipcapture/homer/wiki/webHomer-authentication) . but  i cant found such as this  table name. i mean how can i bypass local authentication and use LDAP instead of it . before all i check my connection with ldapsearch command and i think everything is ok.
thanks

**Comment by salehhoushangi** [comment]
could you tell me  how to track authenticate log for homer?

**Comment by salehhoushangi** [comment]
Hi guys 
i checked my LDAP bind connection with below script
``<?php

// using ldap bind
$ldaprdn = 'uname'; // ldap rdn or dn
$ldappass = 'password'; // associated password

// connect to ldap server
$ldapconn = ldap_connect("ldap.example.com")
or die("Could not connect to LDAP server.");

if ($ldapconn) {

// binding to ldap server
$ldapbind = ldap_bind($ldapconn, $ldaprdn, $ldappass);

// verify binding
if ($ldapbind) {
    echo "LDAP bind successful...";
} else {
    echo "LDAP bind failed...";
}
}`
and everything be ok  and has been reported "LDAP bind successful...`"
but when i try authenticate  to Homer  via LDAP , ngrep result in my server show below error:
 10.x.x.x:389 -> 17x.x.x.x:44506 [AP] #156
  0....h...a...._..1...X80090308: LdapErr: DSID-0C09042A, comment: AcceptSecurityContext error, data 52e, v3839
I know the error Indicates an Active Directory (AD) AcceptSecurityContext error, which is returned when the username is valid but the combination of password and user credential is invalid. This is the AD equivalent of LDAP error code 49.
but i dont  know what  What causes this error?
also my parameter configured in preferences.php are:
define('AUTHENTICATION',"LDAP");
define('LDAP_HOST',"1x.xx.x");
define('LDAP_PORT',389);
define('LDAP_VERSION',3);
define('LDAP_ENCRYPTION',"none");
define('LDAP_BIND_USER',"cn=xx,ou=xx,ou=xx,dc=xx,dc=xx");
define('LDAP_BIND_PASSWORD',"xx");
define('LDAP_BASEDN',"dc=xx,dc=xx");
define('LDAP_USERNAME_ATTRIBUTE_OPEN',"uid=");
define('LDAP_USERNAME_ATTRIBUTE_CLOSE',"");
define('LDAP_USERLEVEL',3);
define('LDAP_UID',"uidnumber");
define('LDAP_USERNAME',"uid");
define('LDAP_GID',"gidnumber");
define('LDAP_FIRSTNAME',"givenname");
define('LDAP_LASTNAME',"sn");
define('LDAP_EMAIL',"mail");
define('LDAP_GROUPDN',true);
define('LDAP_GROUP_USER','uid');
define('LDAP_GROUP_ARRAY',false);
define('LDAP_GROUP_ATTRIBUTE','memberUid');

**Comment by salehhoushangi** [comment]
this issue resolve in "https://github.com/sipcapture/homer/issues/364"
