### ISSUE TITLE
LdapErr: DSID-0C09042A, comment: AcceptSecurityContext error, data 52e, v3839

### ISSUE THREAD

**Issue by salehhoushangi** [sipcapture/homer#364]
Hi guys 
i checked my LDAP bind connection with below script
``<?php

// using ldap bind
$ldaprdn = 'uname'; // ldap rdn or dn
$ldappass = 'password'; // associated password

// connect to ldap server
$ldapconn = ldap_connect("ldap.example.com")
or die("Could not connect to LDAP server.");

if ($ldapconn) {

// binding to ldap server
$ldapbind = ldap_bind($ldapconn, $ldaprdn, $ldappass);

// verify binding
if ($ldapbind) {
    echo "LDAP bind successful...";
} else {
    echo "LDAP bind failed...";
}
}`
`"
and everything be ok  and has been reported "LDAP bind successful...
also check with ldapsearch qurey and everything is ok .
but when i try authenticate  to Homer  via LDAP , ngrep result in my server show below error:
 10.x.x.x:389 -> 17x.x.x.x:44506 [AP] #156
  0....h...a...._..1...X80090308: LdapErr: DSID-0C09042A, comment: AcceptSecurityContext error, data 52e, v3839
I know the error Indicates an Active Directory (AD) AcceptSecurityContext error, which is returned when the username is valid but the combination of password and user credential is invalid. This is the AD equivalent of LDAP error code 49.
but i dont  know what  What causes this error?
also my parameter configured in preferences.php are:
define('AUTHENTICATION',"LDAP");
define('LDAP_HOST',"1x.xx.x");
define('LDAP_PORT',389);
define('LDAP_VERSION',3);
define('LDAP_ENCRYPTION',"none");
define('LDAP_BIND_USER',"cn=xx,ou=xx,ou=xx,dc=xx,dc=xx");
define('LDAP_BIND_PASSWORD',"xx");
define('LDAP_BASEDN',"dc=xx,dc=xx");
define('LDAP_USERNAME_ATTRIBUTE_OPEN',"uid=");
define('LDAP_USERNAME_ATTRIBUTE_CLOSE',"");
define('LDAP_USERLEVEL',3);
define('LDAP_UID',"uidnumber");
define('LDAP_USERNAME',"uid");
define('LDAP_GID',"gidnumber");
define('LDAP_FIRSTNAME',"givenname");
define('LDAP_LASTNAME',"sn");
define('LDAP_EMAIL',"mail");
define('LDAP_GROUPDN',true);
define('LDAP_GROUP_USER','uid');
define('LDAP_GROUP_ARRAY',false);
define('LDAP_GROUP_ATTRIBUTE','memberUid');

**Comment by adubovikov** [comment]
please check your user object, normaly it should start from: uid=youruser
or cn=youruser. If you have different type (i.e. full username) you have to
use double bind

**Comment by salehhoushangi** [comment]
@adubovikov  thanks . but how can i  use double bind . does any change need to do in my configuration Homer or just configure in AD?

**Comment by salehhoushangi** [comment]
when i get dsquery from my AD it give me back ""CN=homer,CN=Users,DC=rXXXX,DC=net"  so i think is a single bind .

**Comment by adubovikov** [comment]
as I see you have user attribute CN=, but you use uid=, please change it and check again that you send to LDAP

**Comment by salehhoushangi** [comment]
you means put uid instead of cn in preferences config . if i guessed correctly i put it and in ngrep tracing showing same error.

**Comment by adubovikov** [comment]
you should check the request that homer-api sends

**Comment by salehhoushangi** [comment]
in the most recent action i setup full DN in both  LDAP_BIND_USER and LDAP_BASEDN as follow:
cn=homer,cn=Users,dc=xxxx,dc=xxxx,. now when i checked with browser editor As before, it will not give error 404 and  method post is 200 but i got error like below:
Error: results.data.data is undefined
login/<@http://172.22.32.53/js/modules/auth/services/authentication.js:41:25
f/<@http://172.22.32.53/lib/angular/angular.min.js:119:129
$eval@http://172.22.32.53/lib/angular/angular.min.js:133:313
$digest@http://172.22.32.53/lib/angular/angular.min.js:130:412
$apply@http://172.22.32.53/lib/angular/angular.min.js:134:78
g@http://172.22.32.53/lib/angular/angular.min.js:87:444
T@http://172.22.32.53/lib/angular/angular.min.js:92:50
Uf/</w.onload@http://172.22.32.53/lib/angular/angular.min.js:93:78
and after this event 
Source map error: request failed with status 404
Resource URL: http://172.22.32.53/js/widgets/markdown/showdown.min.js
Source Map URL: showdown.min.js.map
but there is  no error remain in ngrep tools :
#
T 10.0.5.55:389 -> 172.22.32.53:57826 [AP] #263
  0........a............................
#
T 172.22.32.53:57826 -> 10.0.5.55:389 [A] #264
  -."...qr........
#
T 172.22.32.53:57826 -> 10.0.5.55:389 [AP] #265
  0....B.................
#
T 172.22.32.53:57826 -> 10.0.5.55:389 [AF] #266
  07...`2....#cn=h
#
T 10.0.5.55:389 -> 172.22.32.53:57826 [AR] #267
  ......"...qs0........a
#
T 10.0.5.55:389 -> 172.22.32.53:57826 [R] #268
  ......qw-.".07...`2...

**Comment by adubovikov** [comment]
you dont capture full packets

**Comment by salehhoushangi** [comment]
thanks @adubovikov 
thanks @aqsyonas
thanks @lmangani
finally i can do integration with my AD microsoft .
here my preferences.php file:
define('LDAP_HOST',"x.x.x.x");
define('LDAP_PORT',389);
define('LDAP_BASEDN',"dc=respina,dc=net");
define('LDAP_REALM',"RESPINA");
define('LDAP_USERNAME_ATTRIBUTE_OPEN',"cn=");
define('LDAP_USERNAME_ATTRIBUTE_CLOSE',"");
define('LDAP_USERLEVEL',3);
define('LDAP_BIND_USER','cn=homer,cn=Users,dc=respina,dc=net');
define('LDAP_BIND_PASSWORD','xxxx');
define('LDAP_ENCRYPTION','no');
define('LDAP_VERSION','3');
also one of the weakness of this software is when logging error in php.ini changing to on  Causes many unwanted problems.
also  don't remember  using php 5.6 , one of the problem causes to  have problem in ldap integration  was using php 5.4 so i had problem  for example in(@ldap_escape)  that was undefined in my php log 
after remove  and change it to 
$r=ldap_search( $ds, LDAP_BASEDN, LDAP_USERNAME_ATTRIBUTE_OPEN.($param['username']).LDAP_USERNAME_ATTRIBUTE_CLOSE);
i could pass this section
All these experiences have been the result of debugging for a week.
but This is the last undiscovered puzzle for me to add to the group authorize via LDAP in homer.
i appreciate If anyone helps me so it will save me time.
if any person have problem to integrate homer to ldap  I welcome people who want to expand the open source community.
