### ISSUE TITLE
Homer SIPcapture on AVAYA.

### ISSUE THREAD

**Issue by sebky94** [sipcapture/homer#365]
Hello everyone!

I have an AVAYA AURA 7 plateform and i want to install a homer server with captagents on my AVAYA telephony servers (communication manager, session manager, session border controller ...).

Could anyone please provide the whole process of installation and configuration?

Many thanks in advance.

Kind Regards.

**Comment by changzx** [comment]
> Hello everyone!
> 
> I have an AVAYA AURA 7 plateform and i want to install a homer server with captagents on my AVAYA telephony servers (communication manager, session manager, session border controller ...).
> 
> Could anyone please provide the whole process of installation and configuration?
> 
> Many thanks in advance.
> 
> Kind Regards.

linux plateform?

**Comment by aqsyonas** [comment]
We have installer script available for debian 9 and centos 7.

If you would to have more control you can use below links.

https://github.com/sipcapture/homer/wiki/homer-seven-setup

https://github.com/sipcapture/homer/wiki/Homer-7-Stack-Installation-on-Debian-9-Stretch


Br, Aqs.

**Comment by sebky94** [comment]
@changzx Redhat yes 
@aqsyonas : thank you very much! i will try them and let you know if everything works

**Comment by sebky94** [comment]
Could you guys please tell me if i need to set homer this way on my servers : 

Homer Server/ web interface : separate server (centos 7)
Captagent : on my existing SIP avaya servers (SBC, Session manager, Communication manager ...)

**Comment by aqsyonas** [comment]
@sebky94 that looks good.

**Comment by sebky94** [comment]
Thank you! 

I understand that since i have SIP servers that are already running, i don't need Kamailio or OpenSIP ? 

The only thing i need to do is install Captagent on my AVAYA Redhat servers. Am I right?

**Comment by aqsyonas** [comment]
@sebky94 in homer7 you don't need to install opensips/kamailio. Homer7 has its own powerful capture server, heplify-server that you need to install along with homer-app. 

For the Agent Captagent or heplify on the AVAYA server would be enough.

**Comment by sebky94** [comment]
Hello, 

I have installed a homer 7 server on a centos machine. i have the web interface UP, but i cannot login using the credentials : admin/sipcapture

I captured the traffic on port 80 using this command : ngrep -W byline -q -d any port 80

I got this as a result : 

[root@localhost ~]# ngrep -W byline -q -d any port 80
interface: any
filter: ( port 80 ) and (ip || ip6)

T 172.19.45.92:57902 -> 172.19.47.206:80 [S] #1
................

T 172.19.47.206:80 -> 172.19.45.92:57902 [AS] #2
................

T 172.19.45.92:57902 -> 172.19.47.206:80 [A] #3
......................

T 172.19.45.92:57902 -> 172.19.47.206:80 [AP] #4
POST /api/v3/auth HTTP/1.1.
Host: 172.19.47.206.
Connection: keep-alive.
Content-Length: 44.
Accept: application/json, text/plain, */*.
Origin: http://172.19.47.206.
Authorization: .
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36.
Content-Type: application/json;charset=UTF-8.
Referer: http://172.19.47.206/.
Accept-Encoding: gzip, deflate.
Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7.
.
{"username":"admin","password":"sipcapture"}................

T 172.19.47.206:80 -> 172.19.45.92:57902 [A] #5
................

T 172.19.47.206:80 -> 172.19.45.92:57902 [AP] #6
HTTP/1.1 503 Service Unavailable.
content-type: application/json; charset=utf-8.
cache-control: no-cache.
vary: accept-encoding.
content-encoding: gzip.
Date: Mon, 21 Oct 2019 11:20:19 GMT.
Connection: keep-alive.
Transfer-Encoding: chunked.
.
a.
...........
................

T 172.19.45.92:57902 -> 172.19.47.206:80 [A] #7
......................

T 172.19.47.206:80 -> 172.19.45.92:57902 [AP] #8
75.
..M
.@.@....E...fk.K.....Q.;.ItS.{...x?T#;.O3....@.I..G.s..S....>;c._V.5..d.K....,.B....._....i....{Y.j.....?.&G.r....
0.
.
................

T 172.19.45.92:57902 -> 172.19.47.206:80 [A] #9
......................

T 172.19.45.92:57902 -> 172.19.47.206:80 [AF] #10
......................

T 172.19.47.206:80 -> 172.19.45.92:57902 [AF] #11
................

T 172.19.45.92:57902 -> 172.19.47.206:80 [A] #12
......................


Could you please help me understand this?

**Comment by lmangani** [comment]
Hello @sebky94 

`HTTP/1.1 503 Service Unavailable.`
The API is not responding or configured. How did you install Homer?

**Comment by sebky94** [comment]
Hello @lmangani 

I followed this guide : https://github.com/sipcapture/homer/wiki/homer-seven-setup

**Comment by sebky94** [comment]
I can re-configurate the server, if you have a good guide for homer 7 please share it with me.

Many thanks.

**Comment by sebky94** [comment]
I used this one : https://github.com/sipcapture/homer-installer

sorry.

**Comment by sebky94** [comment]
Hello, 

I still have this problem, could you please help me figure out the reason why it doesnt work?

**Comment by lmangani** [comment]
Hard to tell without further troubleshooting. What's the status of the various services installed? Is Postgres up and running? Are ports listening? Is SELINUX disabled? 

`netstat -tulpn`

**Comment by sebky94** [comment]
[root@localhost src]# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      32007/postmaster
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1517/master
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      822/node
tcp        0      0 127.0.0.1:4222          0.0.0.0:*               LISTEN      1087/influxd
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      822/node
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1081/sshd
tcp6       0      0 ::1:5432                :::*                    LISTEN      32007/postmaster
tcp6       0      0 ::1:25                  :::*                    LISTEN      1517/master
tcp6       0      0 :::9060                 :::*                    LISTEN      1085/heplify-server
tcp6       0      0 :::9096                 :::*                    LISTEN      1085/heplify-server
tcp6       0      0 :::9999                 :::*                    LISTEN      1087/influxd
tcp6       0      0 :::22                   :::*                    LISTEN      1081/sshd
udp        0      0 127.0.0.1:323           0.0.0.0:*                           835/chronyd
udp6       0      0 :::9060                 :::*                                1085/heplify-server
udp6       0      0 ::1:323                 :::*                                835/chronyd

**Comment by lmangani** [comment]
What about all the other questions? ;)

**Comment by aqsyonas** [comment]
@sebky94 could you please try with latest installer, I have pushed some fixes for firewall and SELinux.

**Comment by sebky94** [comment]
Hello,

@lmangani I think i'll do the whole installation again, i lost the server.
@aqsyonas Could you please send me a guide with the new installer?

Thank you.

**Comment by sebky94** [comment]
Hello, 

I am creating two virtual machines as HOMER 7 servers, i want to know in which partition the data will be stored, so i can inforce the storage in that precise partition. Where does homer automatically store data ?

Thank you.

**Comment by lmangani** [comment]
Hi @sebky94 the storage of data is handled by Postgres and timeseries either InfluxDB/Prometheus depending on the choice, so the default data locations of their configs apply here. You can refer to the config files on your system or the defauls, which we do not modify in our process.

Hope this helps!
