### ISSUE TITLE
Fresh install, INFLUXDB CHART shows No Data

### ISSUE THREAD

**Issue by SB-JohnK** [sipcapture/homer#369]
I used homer installer, I installed influxdb and grafana.

I configured a scraper in influxdb to point to heplify-server http://192.168.8.18:9096/metrics

I can use influxdb data explorer to see rtcp counters so I believe data collection is working.

I configured my timezone in the world clock.

I get 'No Data' from INFLUXDB CHART' on either the 'Home' or 'RTC' dashboards.

What should these graphs be showing? Do I need to configure them?

I would like graphs showing jitter and packet loss at each of my capture nodes.

If I look at the system journal I see the errors logged for homer-app

Oct 15 09:43:40 homer.simplybits.net homer-app[4377]: Error....
Oct 15 09:43:40 homer.simplybits.net homer-app[4377]: Debug: handler, error
Oct 15 09:43:40 homer.simplybits.net homer-app[4377]: {"msec":3.150979000143707,"error":"stats data has not been found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found","message":"stats data has not been found"},"headers":{}}}}

**Comment by lmangani** [comment]
Hi,

Sounds like a connectivity issue between the UI and the backend potentially. Please try reconfiguring the influxdb widget, and see if you get any dropdown values when selecting the Databases / Series as a first step - please update the ticket with results.

**Comment by SB-JohnK** [comment]
I do see drop downs but only one option in each.

I've checked and selinux is disabled and firwalld is not running, I have tcp ports 80, 9999 and 9096 permitted through my hardware firewall. 

![homer1](https://user-images.githubusercontent.com/22180146/66942812-b93c9e00-effe-11e9-87ab-17b6987a1ae7.PNG)
![homer2](https://user-images.githubusercontent.com/22180146/66942817-bb066180-effe-11e9-915c-edcc2bfe22da.PNG)

**Comment by aqsyonas** [comment]
@SB-JohnK please, make sure you have correct details at 
https://github.com/sipcapture/homer-app/blob/master/server/config.js#L33
I will check the installer and fix it. If not getting properly set.

**Comment by SB-JohnK** [comment]
I modified config.js to change the port number to 9999, I also found a reference to influx in server.js and changed the port there, still seeing the same results.

**Comment by SB-JohnK** [comment]
Is there additional troubleshooting I can do at this point to help? provide configurations or logs?

**Comment by lmangani** [comment]
Hi @SB-JohnK first let's check if there's any data at all. You should have Chronograf installed and running on port 8888 on the same host. Try access it and see if there's any database from homer, and it it contains any of your data. If this works, its a connectivity issue betwen the (now old) UI and InfluxDB, otherwise it's an issue somewhere in the `heplify-server -> telegraf -> influxdb` path

**Comment by SB-JohnK** [comment]
I'm unable to access anything on port 8888.

Netstat doesn't show anything listening on 8888 either:
```

[root@homer ~]# netstat -plnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name                                                     
tcp        0      0 127.0.0.1:4222          0.0.0.0:*               LISTEN      4463/influxd                                                         
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      25733/node                                                           
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      5213/sshd                                                            
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      3973/postmaster                                                      
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      5725/master                                                          
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      25733/node                                                           
tcp6       0      0 :::9060                 :::*                    LISTEN      4562/heplify-ser                                                     ver
tcp6       0      0 :::9096                 :::*                    LISTEN      4562/heplify-ser                                                     ver
tcp6       0      0 :::9999                 :::*                    LISTEN      4463/influxd                                                         
tcp6       0      0 :::22                   :::*                    LISTEN      5213/sshd                                                            
tcp6       0      0 ::1:5432                :::*                    LISTEN      3973/postmaster                                                      
tcp6       0      0 ::1:25                  :::*                    LISTEN      5725/master  
```                                                        

I am able to access the influxdb web interface on port 9999, I can use the data explorer and see the following measurements that appear to be homer related:

heplify_packets_zie
heplify_packets_total
heplify_rtcp_dlsr
heplify_rtcp_fraction_lost
heplify_rtcp_jitter
heplify_rtcp_packets_lost

I've attached a screenshot ![influxdb png](https://user-images.githubusercontent.com/22180146/67414094-417af000-f577-11e9-90d1-ba00020b7ca7.PNG)

**Comment by lmangani** [comment]
Oh - you're using the TICK stack 2.0. I guess it's as simple as changing the Influxdb settings of the HOMER-APP which currently points at 8086 rather than 9999 as I guess it should be. Could you give this a shot?

https://github.com/sipcapture/homer-app/blob/master/server/config.js#L32

**Comment by SB-JohnK** [comment]
I changed config.js and server.js both when @aqsyonas mentioned it last week, please see attached:

I had to rename the files to .txt to upload them.
[server.txt](https://github.com/sipcapture/homer/files/3763458/server.txt)
[config.txt](https://github.com/sipcapture/homer/files/3763459/config.txt)

**Comment by SB-JohnK** [comment]
@lmangani Any more suggestions? Changing the settings and restarting did not make a difference.

**Comment by rossual** [comment]
I have the exact same issue. Have also made the port changes in the files. I also used the installer script.

**Comment by rossual** [comment]
I have tried the installer script on Debian 9 and centos 7, I have updated the ports in the two files mentioned above. Both operating systems have the same issue @SB-JohnK  did you get any further? @lmangani do you have any other suggestions to try? I do see data in InfluxDB. Any help greatly appreciated.

**Comment by lmangani** [comment]
I am travelling and can't test this but I guess we just need to provide the correct endpoint for InfluxQL HTTP queries to the API:
```
const influxdb = {
  host: '127.0.0.1/api/v2/query',
  port: 9999,
  database: 'homer'
}
```
FYI @rossual and all, we're about to release 7.7 and we'll nail this down permanently

**Comment by rossual** [comment]
Thanks @lmangani  I'm also travelling now, I will test on thursday next week. Thanks again for the response. Looking forward to 7.7

**Comment by rossual** [comment]
@lmangani  I tried the suggestion above and /api/v2 but no luck. How long until the 7.7 release? 
Is there anything I can provide/test?

**Comment by lmangani** [comment]
Gents, 7.7 is already out in alpha and i invite you all to switch to it and help us bootstrap it before the end of the month.

We can easily troubleshoot and fix issues (shall any be left) and since the UI is completely changed, and the access method to statistics did too (we now also allow embedding Grafana widgets from dashboards alongside raw from influx and prometheus)

**Comment by sebky94** [comment]
Hello, 

Thank you @lmangani for the update. I'll try to reinstall my server.

Do you guys think it's normal that the service on which the ports the server listens on are 9060 and 9096 is tcp6:

**tcp6**       0      0 :::9060                 :::*                    LISTEN      4562/heplify-ser                                                     ver
**tcp6**       0      0 :::9096                 :::*                    LISTEN      4562/heplify-ser                                                     ver

i have the same on my server.

**Comment by lmangani** [comment]
This is a common misunderstanding, I'm quite certain tcp6 sockets can also listen to tcp4 when operating on all interfaces as per this example. If you can receive packets via ipv4 this is implicit.

**Comment by sebky94** [comment]
Thank you @lmangani .

Is 7.7 available for CentOS7 too?

**Comment by lmangani** [comment]
The 7.7 installer should support both CentOS and Debian just fine. I would although suggest running one of the 7.7 Docker bundles to get the full stack results on a single server and still be able to move things around at a later time as those (particularly the Prometheus bundle) come pre-provisioned for Dashboards, etc.

**Comment by sebky94** [comment]
Is there a dedicated guide to install the 7.7?

Is uploading and executing the install enough ? or should i go through a series of installs seperatly (for example, the DB, HEPlify ...)?

**Comment by lmangani** [comment]
I'm not sure what the confusion is, but there's a `homer-installer` branch `7.7` with the current changes - this should spin up a 7.7 instance you can update/upgrade over time. The best method for those unfamiliar with the process is mimic what our Docker set do. Let me know if you have a more precise question ;)

**Comment by SB-JohnK** [comment]
I had some trouble with the 7.7 homer installer branch, It may be something weird to my environment but there were several places in the script where  Yum should have been prompting 'Is this ok [y/d/n]' or 'Is this ok [y/N]' where the question did not display until I had blindly entered 'Y'.

I chose to install influxdb and chronograph, I'm unable to access the web interface for chronograph on port 8888, I can access the homer UI on port 80.

Homer-app is still logging that it can't get stats data:

Dec 05 12:36:12 homer homer-app[17757]: {"msec":5.2992939949035645,"error":"stats data has not been found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found","message":"stats data has not been found"},"headers":{}}}}
Dec 05 12:38:29 homer homer-app[17757]: Debug: handler, error
Dec 05 12:38:29 homer homer-app[17757]: {"msec":0.35391199588775635,"error":"Not Found","data":{"data":null,"isBoom":true,"isServer":false,"output":{"statusCode":404,"payload":{"statusCode":404,"error":"Not Found","message":"Not Found"},"headers":{}},"message":"Not Found"}}
Dec 05 12:38:30 homer influxd[23692]: ts=2019-12-05T19:38:30.001098Z lvl=info msg="failed to store statistics" log_id=0JXrWzr0000 service=monitor error=timeout
Dec 05 12:38:31 homer homer-app[17757]: AAL { '127.0.0.1:5060': 'localhost' }
Dec 05 12:38:40 homer influxd[23692]: ts=2019-12-05T19:38:40.001694Z lvl=info msg="failed to store statistics" log_id=0JXrWzr0000 service=monitor error=timeout
Dec 05 12:38:41 homer homer-app[17757]: AAL { '127.0.0.1:5060': 'localhost' }

**Comment by Niii** [comment]
Fresh install of Homer7.7 on Centos7.7, still no data.
I can push sip and rtcp and show them with a research, but I can't configure a chart.

When I try to configure an Influxdb chart, got error "db was not found".

**Comment by sebky94** [comment]
Same thing here, except that i have no data at all, I have fresh install homer 7.7 nd still no data.

**Comment by lmangani** [comment]
No data at all, means you also checked directly in InfluxDB if there is data, or just referring to the Homer UI?

**Comment by sebky94** [comment]
I meant only the UI, how can i check directly in InfluxDB?

**Comment by lmangani** [comment]
If you're running InfluxDB 2.0 here's a good pointer: https://v2.docs.influxdata.com/v2.0/get-started/

You might want to configure a scraper for heplify-server:9060/metrics

**Comment by Niii** [comment]
@sebky94 do you have some traffic coming on port 5060 ?
On Centos network card wasn't on promisc mode, so you receive nothing and heplify client can't grab data.

**Comment by sebky94** [comment]
@lmangani Thank you i will do it.

@Niii On the heplify client i have SIP data on port 5060, it's an on production SBC.

**Comment by lmangani** [comment]
Please upgrade to the latest `homer-app` and version 7.7 to retest - your issue should be resolved!
