### ISSUE TITLE
Installer errors on debian7

### ISSUE THREAD

**Issue by nshopik** [sipcapture/homer#37]
```
WARNING: "pear/json" is deprecated in favor of "channel://http://www.php.net/json/json"
downloading json-1.2.1.tgz ...
Starting to download json-1.2.1.tgz (17,780 bytes)
......done: 17,780 bytes
11 source files, building
running: phpize
Cannot find config.m4.
Make sure that you run '/usr/bin/phpize' in the top level source directory of the module

If the command failed with 'phpize: not found' then you need to install php5-dev packageYou can do it by running 'apt-get install php5-dev' as a root userERROR: `phpize' failed
```

**Comment by adubovikov** [comment]
but at line 77 you have this:

 apt-get -y install autoconf automake autotools-dev binutils bison build-essential cpp curl flex g++ gcc git-core libxml2 libxml2-dev lynx m4 make mcrypt ncftp nmap openssl sox ssl-cert ssl-cert unzip zip zlib1g-dev zlib1g-dev libjpeg-dev sox mysql-server mysql-client libmysqlclient15-dev libcurl4-openssl-dev apache2 php5 php5-cli php5-gd php-pear php5-dev php5-mysql php5-json php-services-json sudo

correct ?

**Comment by nshopik** [comment]
You mean line 177, yes exactly. 

I've just found out this is debian issue. `pear install pecl/json` always fails for me, yes php5-dev is installed.

**Comment by lmangani** [comment]
Does "pecl install json" work on your system?

**Comment by nshopik** [comment]
Nope same error.

Apparently in jessie they packaged php5-json with new license, which I assume same thing we trying to build here https://github.com/remicollet/pecl-json-c

**Comment by adubovikov** [comment]
ok, looks like phpize doesn't work correct under Debian7

please disable it and install:

apt-get install php-services-json

if all will be ok, we will change the installation script 

thank you

**Comment by nshopik** [comment]
Yeah looks like it already done that (was clean debian install) , it says php-services-json already installed, I've also checked phpinfo() it confirms 
```
json support	enabled
json version	1.2.1
```
