### ISSUE TITLE
Setting panel to 'Shared' does not appear to share panel.

### ISSUE THREAD

**Issue by SB-JohnK** [sipcapture/homer#370]
I used homer installer, I installed influxdb and grafana.

I used the default 'admin' account, I changed the timzeone on the panel and customized the SIP search.

I clicked the gear icon to edit panel, I clicked the 'Shared' checkbox and clicked Save.

The Icon for the panel changed from a single person to two people.

I logged out as 'admin' and logged in as my 'johnk' user that I created and the 'Home' panel is not shown in the list of panels.

I logged out as 'johnk' and logged back in as 'admin', the icon for the panel has reverted to a single person icon, I edited the panel and the 'Shared' checkbox is still checked.

**Comment by lmangani** [comment]
Sounds like a bug! Thanks for reporting it - we will replicate and fix this.

**Comment by lmangani** [comment]
Closing in preparation for the 7.7 Release. Please re-test your issue using the 7.7. branch or Compose containers and feel free to reopen w/ fresh details if needed. Thanks!
