### ISSUE TITLE
how to set postgress data retention-policies

### ISSUE THREAD

**Issue by wangduanduan** [sipcapture/homer#373]
the postgress data grow very fast, i want to only save tow day sip data,  how to do this?

**Comment by negbie** [comment]
Hi @wangduanduan 
You do this in heplify-server.toml by changing some of these values:

DBDropDays            = 14
DBDropDaysCall        = 0
DBDropDaysRegister    = 0
DBDropDaysDefault     = 0


Default value is 14 days so maybe you want to set this to 2.

**Comment by wangduanduan** [comment]
thank you。

**Comment by negbie** [comment]
Your welcome. Here https://github.com/sipcapture/homer/wiki/HEPLIFY-SERVER-Settings you can find some options a little bit more explained but they still need a better documentation.
