### ISSUE TITLE
Get empty detail view when I click CallerId in my external mariadb

### ISSUE THREAD

**Issue by stevenchiu7311** [sipcapture/homer#374]
Hello,
I tried using docker external mariadb and everything is OK, but when I use pre-installed mariadb in my server, I'll get empty report view after I click callerId.

I've already checked my mysql.user between two case but cannot find any difference.
And I can see completed sip data in homer_data even in incorrect case.

Only difference I can find is two line more errlog in incorrect case

Sun Nov 03 09:50:19.014156 2019] [:error] [pid 29] [client 172.30.0.7:56612] PHP Notice:  Undefined offset: 0 in /var/www/html/api/RestApi/Report.php on line 988, referer: http://172.31.35.67:9080/
[Sun Nov 03 09:50:19.014169 2019] [:error] [pid 29] [client 172.30.0.7:56612] PHP Notice:  Undefined offset: -1 in /var/www/html/api/RestApi/Report.php on line 989, referer: http://172.31.35.67:9080/

But I still have no idea even I get this log, could anyone help us to answer this problem?

Homer version I'm using: homer7-docker/heplify-server/hom5-hep-prom-gra

![螢幕快照 2019-11-03 下午7 27 56](https://user-images.githubusercontent.com/26733525/68084429-3c1f7e80-fe70-11e9-9ec2-e58b41922ab5.png)

**Comment by lmangani** [comment]
Hello,

The homer 5 bundles are no longer supported. Please upgrade to H7.7 and feel free to open new issues in case of problems.
