### ISSUE TITLE
NO DATA CAPTURED ON HOMER 7.

### ISSUE THREAD

**Issue by sebky94** [sipcapture/homer#375]
Hello,

I have newly installed HOMER 7 on a centos 7, and I don't see any DATA displayed in the web interface.

HOMER 7 server is UP and running, HEPlify agent displays data only using "./heplify -i any -hs "" -e" on screen, but i don't see any data on the web interface when i try to send DATA to the server using : "./heplify -i any -hs IPofserver:9060".

Though i don't know how to check if there is data coming to homer server nor data on postgres. How could I check if DATA is being sent or received on the DB? 

Could you please help me and guide me to troubleshoot?

Thank you.

**Comment by bvisonl** [comment]
Experiencing this exact same issue.

**Comment by Niii** [comment]
Same here (also same as ticket #369)

**Comment by lmangani** [comment]
Please upgrade your setup to the latest `homer-app` and version 7.7 - the issue should be resolved
