### ISSUE TITLE
search

### ISSUE THREAD

**Issue by changzx** [sipcapture/homer#377]
Dear:
     Can only search 200?
![image](https://user-images.githubusercontent.com/42836671/70294711-5d80db00-181f-11ea-94fb-8933e2d05944.png)

**Comment by lmangani** [comment]
Yes this is a safety default - Just add/edit the `query limit` parameter to your search widget and off you go ;)

**Comment by changzx** [comment]
where?   query limit parameter

Lorenzo Mangani <notifications@github.com> 于2019年12月6日周五 下午5:59写道：

**Comment by lmangani** [comment]
![image](https://user-images.githubusercontent.com/1423657/70319244-2102ae80-1822-11ea-8904-c10f6cf4854e.png)
