### ISSUE TITLE
jquery.flot.resize.js missing

### ISSUE THREAD

**Issue by nshopik** [sipcapture/homer#38]
When I navigate to search tab, it appears looking for js/jquery.flot.resize.js file which doesn't exist.

Also if I press search it complains `Timeout error. Please take small timeintervall` not sure if this related

**Comment by adubovikov** [comment]
this is two different issues. About Timeout error, please go to our FAQ.

**Comment by lmangani** [comment]
https://github.com/sipcapture/homer/commit/3de1ed04a41adbef741519feacc6b97df12c256d
