### ISSUE TITLE
TODO: Update Documentation

### ISSUE THREAD

**Issue by lmangani** [sipcapture/homer#382]
The current Documentation and Wiki are obsoleted and need to be refreshed.

Up for grabs, among others:

* [API](https://github.com/sipcapture/homer/wiki/Using-Homer-API)
* ~~[Installation](https://github.com/sipcapture/homer/wiki/Quick-Install)~~
* [Usage](https://github.com/sipcapture/homer/wiki)

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.20

**Comment by vkprabha29** [comment]
Hello,
I am testing Homer 7 now. But i am unable to get the correlated callflow from the trace. i can see a single leg. Please advise whether i can do from this existing setup ?
Thanks

**Comment by grinapo** [comment]
Typo: `https://github.com/sipcapture/homer/wiki/Quick-Install#-grafana-integration` at the end tries to link grafana repo but searches "homers" instead of "homer".

**Comment by kYroL01** [comment]
Updated
