### ISSUE TITLE
src.rpms available?

### ISSUE THREAD

**Issue by electroniceel** [sipcapture/homer#384]
On the page https://github.com/sipcapture/homer/wiki/Quick-Install you suggest using a repository on packagecloud to install rpms from for CentOS 7.

Are the src rpms that you use to populate this repo available somewhere?

**Comment by lmangani** [comment]
@electroniceel we don't suggest it, its just an option - the packages are built with `nfpm` from the sources. Each repository we have a package for carries a yml file with the definitions. Let me know if you need further details or links for a specific package source.

**Comment by electroniceel** [comment]
wow, lightning fast response, thanks.

can't find the nfpm yml for heplify-server. There might be an issue with the versioning, the git tag says "1.13", while the rpm on packagecloud is for "1.1.3".

**Comment by lmangani** [comment]
Spot on - they are the same, its a typo. They're in branch `scripts` for now as we test things. `heplify-server` does not return a version number unlike `heplify`, so this is per-build at this time.
