### ISSUE TITLE
Error by updating application tablepq

### ISSUE THREAD

**Issue by akam-it** [sipcapture/homer#385]
Hello, I have fresh centos 7 and installed homer7 packages as described in https://github.com/sipcapture/homer/wiki/Quick-Install

Also I've installed  postgresql-10 and heplify server (all on the same server).

Bit when I try to run homer-app (systemctl start homer-app) I have this message in logs.
{"level":"error","msg":"Error by updating application tablepq: relation \"applications\" does not exist","time":"2020-01-26T12:26:38Z"}

What is wrong?

PS. Are there any complete step-by-step documentation not only to install homer7 from packages, but configure and start it?

**Comment by adubovikov** [comment]
./homer-app -upgrade-table-db-config

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-app/releases/tag/1.1.15
