### ISSUE TITLE
Manual Installation with curl don't work...

### ISSUE THREAD

**Issue by ciscospirit** [sipcapture/homer#387]
hello...

i can't install your homer software with guide here: https://github.com/sipcapture/homer/wiki/Quick-Install

root@2281138-homer:~# curl -s https://packagecloud.io/install/repositories/qxip/sipcapture/script.rpm.sh | sudo bash
Detected operating system as debian/9.
Checking for curl...
Detected curl...
Downloading repository file: https://packagecloud.io/install/repositories/qxip/sipcapture/config_file.repo?os=debian&dist=9&source=script
main: line 161: /etc/yum.repos.d/qxip_sipcapture.repo: No such file or directory

Unable to run:
    curl https://packagecloud.io/install/repositories/qxip/sipcapture/config_file.repo?os=debian&dist=9&source=script

Double check your curl installation and try again.
root@2281138-homer:~#

root@2281138-homer:~# apt-get install curl
Reading package lists... Done
Building dependency tree
Reading state information... Done
curl is already the newest version (7.52.1-5+deb9u9).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

**Comment by ciscospirit** [comment]
https://packagecloud.io/install/repositories/qxip/sipcapture/config_file.repo?os=debian&dist=9&source=script

There is no content.... just "page not exist"

**Comment by adubovikov** [comment]
Detected operating system as debian/9.
but you try use RPM. Please use the correct script
curl -s https://packagecloud.io/install/repositories/qxip/sipcapture/script.deb.sh | sudo bash
