### ISSUE TITLE
configuration_example.php not suitable for debian

### ISSUE THREAD

**Issue by nshopik** [sipcapture/homer#39]
Currently` configuration_example.php` is used for debian w/o changes but there 2 lines require changes for debian, I see there is Centos fixes in installer so I don't know where is better provide fix in `configuration_example.php` or add section in installer for debian.

These two lines should be changed
```
define('WEBPCAPLOC',"/webhomer/tmp/");
define('APILOC',"/webhomer/api/");
```
to
```
define('WEBPCAPLOC',"tmp/");
define('APILOC',"api/");
```

**Comment by lmangani** [comment]
I would say it belongs in the installer as this purely a per-setup preference depending if the user is using a subdomain or just a subdirectory. By default the main domain is used so the the lines in question should work?

**Comment by nshopik** [comment]
Well installer assume to install homer into subdirectory, so these changes are suited for subdirectory
