### ISSUE TITLE
Homer version 7.7.031 - dashboard version

### ISSUE THREAD

**Issue by vkprabha29** [sipcapture/homer#392]
Hello 

I am using docker version of homer. i have attached a screenshot which i am getting now.
Please confirm whether it is correct screenshot.  Homer version 7.7.031

![dashboard](https://user-images.githubusercontent.com/45845584/76143063-bacd3800-606b-11ea-9bf2-9eb0703e8789.jpg)

But i noticed some one have different screenshot with more functinality with Preference menu.

thanks

**Comment by adubovikov** [comment]
sorry, but you can add new widgets and make it looks same :-)

**Comment by vkprabha29** [comment]
Thanks for reply. At the moment i can see these (attched screenshot). I tried but nothing come as preference

![widget](https://user-images.githubusercontent.com/45845584/76143165-02a08f00-606d-11ea-9217-12b2c515dbba.jpg)

thanks

**Comment by adubovikov** [comment]
I don't understand that do you mean in "as preference" These are widgets. You can add them and configure. What else ?
