### ISSUE TITLE
Homer7-Docker: Changing the admin password

### ISSUE THREAD

**Issue by lukeescude** [sipcapture/homer#394]
I'm trying to get into the sipcapture/webapp container and log into SQL to change the admin password, but cannot get into the container.

I've tried docker exec into Bash, MySQL, etc. but nothing is taking.

Any ideas for changing the admin password on homer-webapp via Docker?

**Comment by lmangani** [comment]
The sipcapture/webapp container has no SQL database inside it just connects to one. The user is provisioned in your postgresql container so you should either do this there, or change the provisioning of webapp to use different defaults on creation. Hope this helps.

**Comment by lukeescude** [comment]
Sounds good - So how would one go about changing it in the Postresql container then?

Thanks!
