### ISSUE TITLE
Help - Calculate Packet Loss %

### ISSUE THREAD

**Issue by noahrotheray** [sipcapture/homer#395]
Hi Guys,

I'm at a point where I have majority of the Homer stack installed (prometheus,promtail,grafana,homer-app etc etc) and its working perfectly.

What I'm struggling with is using PromQL (I've never used a time series DB) to calculate packet loss percentages and not the actual amounts of packets lost, as I would like to replace the packet loss dashboard panel in Grafana (QOS RTCP) with a percentage based panel.

Any advice/starting points to achieve this would be appreciated.

**Comment by adubovikov** [comment]
did you check that ? 
https://www.robustperception.io/common-query-patterns-in-promql
```
histogram_quantile(
    0.9, 
    sum without (instance)(rate(my_histogram_latency_seconds_bucket[5m])))
```

**Comment by adubovikov** [comment]
and here
https://prometheus.io/docs/prometheus/latest/querying/operators/#vector-matching

**Comment by noahrotheray** [comment]
Thanks @adubovikov 

Will have a look at these.

**Comment by adubovikov** [comment]
you are welcome
