### ISSUE TITLE
SIP Registration or Default call trace exports empty file

### ISSUE THREAD

**Issue by bmgante** [sipcapture/homer#397]
Did a fresh manual installation this week and didn´t change any mapping schema, so everything is set by default. I am using HEPFIX to convert from Oracle SBC to IPFIX and then use HEPLIFY server to write into postgres for homer.

When on a homer UI session-id correlation window, if trying to export to txt or pcap, it only exports the records if using CALL SIP search. When using REG SIP or DEFAULT SIP search, it creates an empty file when exporting.

**Comment by adubovikov** [comment]
it has been fixed
