### ISSUE TITLE
Truncated Call Flow

### ISSUE THREAD

**Issue by nakchak** [sipcapture/homer#399]
Seem to be hitting a query limit when i try and view a large call flow (> 30 mins call duration) 
Debugging the XHR queries in browser dev tools, can see a limit:200 json property in the request which seems to be ignoring the query limit i pass into the search.

Im using the docker compose script (hom7-prom-all) following the installation instructions, and have pulled latest changes and recreated the service but still no luck, any idea's?

I have read the trouble shooting guide, and suspect a re-init of mappings etc might fix it, but how do i do that with the docker images?

UI Version: 7.7.032

**Comment by nakchak** [comment]
Dug further into problem looking at the XHR requests in dev tools seems that the QOS Query honours the time span set, where as TRANSACTIONS always defaults to a 15min time span

**Comment by im-voiceon** [comment]
We have similar issue: for very long calls INVITE and BYE messages displayed separately as different calls. I suppose this may be done intentionally in order to shorten the search period and thus accelerate it.

**Comment by rwilkinson87** [comment]
We are also experiencing similar issues with calls lasting > 15 minutes.

It seems on the transaction API call, a timestamp[from] and timestamp[to] JSON array is being pushed with timestamps exactly 15 minutes apart.  This is not respecting the specified time range on the homer UI

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer-ui/issues/199

**Comment by adubovikov** [comment]
fixed
