### ISSUE TITLE
ERROR: do_action: bad from dropping packet

### ISSUE THREAD

**Issue by jbartak** [sipcapture/homer#400]
Hello im getting this in `/var/log/messages`:
`Apr  2 07:24:44 localhost homer[5586]: ERROR: sipcapture [sipcapture.c:1687]: sip_capture(): ERROR: do_action: bad from dropping packet`
`Apr  2 07:24:44 localhost homer[5585]: ERROR: <core> [core/parser/parse_from.c:107]: parse_from_uri(): failed to parse From uri`
`Apr  2 07:24:44 localhost homer[5585]: ERROR: pv [pv_core.c:414]: pv_get_xto_attr(): cannot parse From URI`

acording to issue #57 there is no workaround for me and im also running on version `5.0.7`

How to fix this?

**Comment by adubovikov** [comment]
1. install Homer 7.7
2. ignore the parser issue, because the message that you have received doesn't have correct From header and will be dropped
