### ISSUE TITLE
pjsip + wss + homer 7.7.034

### ISSUE THREAD

**Issue by tiagoggsouza** [sipcapture/homer#403]
I configured one server with homer 7.7.034 in centos7 and hep.conf in asterisk(different server) to send the packet but nothing is happening in web page, the page is empty, I need to do some think in specific to begin show the packet in web page? showing throw tcpdump i can see all packet arrives in port 9060 in the Homer server.

**Comment by lmangani** [comment]
Hello @tiagoggsouza This raises more questions so please be as specific as you can.
How did you install? Is heplify-server up and running? Do you see any errors in your console? 
Did you select a time range?

**Comment by tiagoggsouza** [comment]
Hello Imangani thanks for help .

 I Installed using this tutorial to centos7(in manual Install) : https://github.com/sipcapture/homer/wiki/Quick-Install

heplify-server up and running - YES

Did you select a time range - yes, i tried some diferents dates on webrowser...

the console on web page?

I just use default config on asterisk(hep.conf) and homer too.

I'm using pjsip with protocol wss in webrtc.

**Comment by tiagoggsouza** [comment]
I reinstall with Quick Install and now is working normally.. thanks.. it's possible to capture rtp packet's too?

**Comment by lmangani** [comment]
@tiagoggsouza no that's a commercial feature used to sponsor homer
