### ISSUE TITLE
Qos metrics not available

### ISSUE THREAD

**Issue by bmgante** [sipcapture/homer#404]
Hello,

Received a QoS message that was successfully decoded by horaclifix and sent to homer database, ID 35.
From heplify-server debug log we got (see detail of the message in attached log file):

`2020-06-02T17:01:47+01:00 DBG  [sql] COPY hep_proto_35_default(sid,create_date,protocol_header,data_header,raw) FROM STDIN`

[heplify-server.debug.log](https://github.com/sipcapture/homer/files/4718897/heplify-server.debug.log)

On the Homer side, message is accessible using the template i´ve created for ID 35 (exact copy of default RTP template ID 34 only with ID changed):
 
![image](https://user-images.githubusercontent.com/27358817/83554057-1476be80-a504-11ea-8c59-ce616572a6a8.png)

However when checking for QoS on respective SIP messages using the default Call template, we have the metrics there but all of them are set to zero. I´ve only received only single message with QoS counters (very few data being generated from sbc), can it be related to that?

![image](https://user-images.githubusercontent.com/27358817/83554139-353f1400-a504-11ea-89b5-abc23312600c.png)

Finally, what Delta counter stands for?

Thanks

**Comment by bmgante** [comment]
Some more information:
Was able to capture more events from SBC but noticed that we are only processing (do not know why to be honets) the QoS message for the first leg of the call. Can this bue the reason to do not have QoS tab counters populated on call trace QoS tab as shown below?

![image](https://user-images.githubusercontent.com/27358817/83622121-7b898700-a587-11ea-8dee-ec0f555b8fc7.png)

![image](https://user-images.githubusercontent.com/27358817/83622256-9d830980-a587-11ea-975d-8f14b1155472.png)

Thanks

**Comment by lmangani** [comment]
Sorry, not an HOMER issue, please keep this troubleshooting in the repository of interest. Horaclifix is no longer developed or supported as I already explained privately.

**Comment by bmgante** [comment]
> Sorry, not an HOMER issue, please keep this troubleshooting in the repository of interest. Horaclifix is no longer developed or supported as I already explained privately.

Hi @lmangani just to understand why it´s not an HOMER issue if qos data is properly stored into HOMER database but only not being properly presented on call qos tab/graph.

**Comment by adubovikov** [comment]
because you have to deliver the report in the Homer's format and not as Acme SBC. Please take a look on RTPAgent and RTCP JSON reports.
