### ISSUE TITLE
Data not being displayed due to mapping schema issue

### ISSUE THREAD

**Issue by bmgante** [sipcapture/homer#405]
Hello,

I have data stored on homer database and created a a new mapping schema for it (ID 35).
However, these value are not displayed on call trace qos tab/flow. The counters are all set to zero.
This may be probably due to an incorrect mapping on the template i´ve created (copy of default ID 34).
Attached there are csv dumps from the following tables:
- hep_proto_1_call
- hep_proto_35_default
- mapping_schema

[homer_database_exports.zip](https://github.com/sipcapture/homer/files/4722849/homer_database_exports.zip)

Any help is appreciated.

Thanks

**Comment by adubovikov** [comment]
did you figure it out ?

**Comment by bmgante** [comment]
Unfortunately no.

**Comment by adubovikov** [comment]
I hope you read this page:

https://github.com/sipcapture/homer-app/wiki/Examples:-Correlation-MAPPING
