### ISSUE TITLE
Not able to installed Homer on fresh Ubuntu 18.04

### ISSUE THREAD

**Issue by Avdhesh2828** [sipcapture/homer#407]
Hi all,

I am not able to install fresh ubuntu 18.04 on AWS. Please suggest.

############
root@ip-XXXXXXX:~# curl -s https://packagecloud.io/install/repositories/qxip/sipcapture/script.deb.sh | sudo bash
Detected operating system as Ubuntu/bionic.
Checking for curl...
Detected curl...
Checking for gpg...
Detected gpg...
Running apt-get update... done.
Installing apt-transport-https... done.
Installing /etc/apt/sources.list.d/qxip_sipcapture.list...done.
Importing packagecloud gpg key... done.
Running apt-get update... done.

The repository is setup! You can now install packages.
root@ip-XXXXXX:~# apt install heplify
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package heplify
root@ip-XXXXX:~#

############ Second Method #############
      ,;;;;;,       HOMER SIP CAPTURE (http://sipcapture.org)
     ;;;;;;;;;.     Single-Node Auto-Installer (beta 7.7)
   ;;;;;;;;;;;;;
  ;;;;  ;;;  ;;;;   <--------------- INVITE ---------------
  ;;;;  ;;;  ;;;;    --------------- 200 OK --------------->
  ;;;;  ...  ;;;;
  ;;;;       ;;;;   WARNING: This installer is intended for
  ;;;;  ;;;  ;;;;   dedicated/vanilla OS setups without any
  ,;;;  ;;;  ;;;;   customization and with default settings
   ;;;;;;;;;;;;;
    :;;;;;;;;;;     THIS SCRIPT IS PROVIDED AS-IS, USE AT
     ^;;;;;;;^      YOUR *OWN* RISK, REVIEW LICENSE & DOCS

**************************************************************

root@ip-XXXXXXX:/usr/src# ERROR:
Sorry, this Installer does not support your OS yet!
Please follow instructions in the HOW-TO for manual installation & setup
available at http://sipcapture.org

Thanks,

**Comment by adubovikov** [comment]
please use packages!
