### ISSUE TITLE
no acess web

### ISSUE THREAD

**Issue by DavidsonJR90** [sipcapture/homer#409]
Hello, I installed on centos7, but I can't get web access on port 9080. I disabled the firewall to check it, but I still can't access it. How to check if the service is active and operating?

**Comment by DavidsonJR90** [comment]
I use Quick Install.
my homer-app dont start "homer-app.service failed."
consult homer-app.log return {"level":"error","msg":"dial tcp [::1]:5432: connect: connection refused","time":"2020-07-16T13:05:34-03:00"}

**Comment by adubovikov** [comment]
Please check if your postgres is up. Without it homer-app would not work.
Also for more details you can activate debug log in the homer-app.

Regards,
Alexandr

**Comment by DavidsonJR90** [comment]
Hi Alexandr

I checked and it was not installed, it should have been installed when running the script, correct?

which advises me, uninstall everything and install again or install only postgres.

**Comment by aqsyonas** [comment]
Script should install everything and configure homer with default
configurations automatically.

Script also produces logs, please check if you got some error during
installation.

Br, Aqs.

**Comment by DavidsonJR90** [comment]
Well, i completely removed homer, and installed it again, now i got access. However I am not able to see any capture by the homer, if i use TCPDUMP on the server I can see the SIP packets.

**Comment by aqsyonas** [comment]
You need to check a couple of things here,
1. Check if data is in the database.
2. If not, check if you see errors in heplify-server log
3. If data makes to database, check if you have firewall off
4. Try to enable debug logs in homer-app
5. While you perform a search check  make sure you have the correct time
range selected in the UI.
6. Watch data on port 9080 while you make a request.

I hope this helps,

Br, Aqs

**Comment by DavidsonJR90** [comment]
Thanks for the support.
My server has 4 network interface, is there any way to force the homer to capture network interface # 4?
I performed a test with sngrep and it only works when I use the parameter "sngrep -d em4" only using "sngrep" does not capture.

**Comment by lmangani** [comment]
Hi @DavidsonJR90 sure you can specify the interfaces in your `heplify` configuration just like you would with other tools. The command examples will show you how, ie: `./heplify -i eth2`
