### ISSUE TITLE
CentOS7 mysqld

### ISSUE THREAD

**Issue by dmeiser** [sipcapture/homer#41]
Install on CentOS7 halts with the error:
HALT! There is no database. Please install mysqld manually and retry.

This error occurs because package mariadb-server is needed, but is not installed by the script.

In order for it to work, the script needs to install mariadb (mariadb-server package), enable mariadb (systemctl enable mariadb), check the correct file (/etc/systemd/system/multi-user.target.wants/mariadb.service), and then start the service (systemctl start mariadb).

**Comment by adubovikov** [comment]
ah, ok, I see now, Centos 7 has replaced MySQL  and now it comes with MariaDB instead of MySQL.... need make an additional switch/case.

**Comment by dmeiser** [comment]
Yeah, it was a hurculean effort to get it working...  I didn't actually script any of my changes, so I didn't have any changes for you on this one.

**Comment by lmangani** [comment]
Will fix

**Comment by kvishnivetsky** [comment]
Hi, Guys!
BTW: In Oracle Enterprise Linux 7 there is a difference from CentOS with MySQL:
There are packages, named: mysql-community-client and mysql-community-server and so on
They are in additional repositories(disabled by default) and are an altenative to mariadb, which is located in system repositories.

**Comment by kvishnivetsky** [comment]
Hi, Guys!
Here is additional info for RHEL7 and forks and MySQL:
https://dev.mysql.com/downloads/repo/yum/

**Comment by lmangani** [comment]
To use the script (and upcoming packages) just add the MySQL repos to your setup:
https://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
