### ISSUE TITLE
Asterisk 16 (13+) correlation_id prefill

### ISSUE THREAD

**Issue by rberlin01** [sipcapture/homer#410]
This was a drawn out conversation in gitter.im that I am bringing here as an issue to hopefully be resolved. The Asterisk built in HEP module, as of Asterisk 13, has a predefined parameter "UUID_Type" which is not optional and will always default to the active Call-ID. This makes B-Leg correlation not work in Homer 7. It seems that "X-CID" will only be filled into the correlation_id field if the correlation_id field is blank. In this case, Asterisk includes it in the HEP packet so it is already populated. The problem being that the A-Leg correlation_id is set to the A-Leg Call-ID, and the B-Leg correlation_id is set to the B-Leg Call-ID. So leg correlation is not working for Asterisk.

**Comment by adubovikov** [comment]
I have just answered on the channel. Please add an additional block to the correlation mapping same as a first block to fetch all messages one more time.

**Comment by adubovikov** [comment]
also, in the block there you do lookup by data_header->>xcid please add:

```
append_sid = true
```

it will add all "xcid" to the SID array and after you can get all messages

**Comment by adubovikov** [comment]
https://github.com/sipcapture/heplify-server/commit/9f3cc45beeecbc396227158efa4689a83edd684f
as a workaround - in the config: IgnoreCorrHeader = true will force using X-CID even if

**Comment by adubovikov** [comment]
https://github.com/sipcapture/heplify-server/commit/38429186f48c3e55679694bfd2853e5b9e845c86
in the heplify-server.toml:

ForceALegID = true

will override correlation_id by your X-CID

**Comment by rberlin01** [comment]
> append_sid = true

I can confirm that this did fix correlation working for only the initial invite.

**Comment by adubovikov** [comment]
so, can we close the ticket ?

**Comment by rberlin01** [comment]
> 
> 
> so, can we close the ticket ?

I am reinstalling with docker now, and going to apply the ALegIds and ForceALegID before composing, and see if it works out of the box. If you'd like to wait for that confirmation.

**Comment by adubovikov** [comment]
ForceALegID will work only with new release. The binary is not yet in the docker.

**Comment by rberlin01** [comment]
@adubovikov worth noting that I still had to set my correlation_id to data_header->>'X-CID' with append_sid = true. But this is working.

**Comment by adubovikov** [comment]
Also in docker?
