### ISSUE TITLE
Aliases not shown on the main panel

### ISSUE THREAD

**Issue by cyrilconstantin** [sipcapture/homer#411]
Hi Guys,

I have added Aliases to some of my IPs but they are not shown on the main panel as it was for the previous homer versions. The only way to see my Aliases is by clicking on a Correlation ID and there I can see the Aliases. I wonder why I can't see on the main GUI. Also on the Correlation ID screen the Alias is slightly truncated.

![aliases_details](https://user-images.githubusercontent.com/11923641/90792365-000abc80-e2d0-11ea-852d-43c64705d140.png)
![aliases1](https://user-images.githubusercontent.com/11923641/90792367-00a35300-e2d0-11ea-8146-6ac62e96fcf3.png)

**Comment by adubovikov** [comment]
Can you please show the full name of your alias ?  "US Webserver" or it has more characters ?

**Comment by cyrilconstantin** [comment]
Hi,

Thanks for the quick answer, please find below the config. I have tried with shorter name but still the same issue they are not shown on the main panel:


![alias config 2](https://user-images.githubusercontent.com/11923641/90794838-e9199980-e2d2-11ea-89df-75c9d7a96575.png)

**Comment by adubovikov** [comment]
do you see the alias in the API reply ?  F12 -> network

**Comment by cyrilconstantin** [comment]
API result below, let me know if it's the right one that you are looking for ?

![api result](https://user-images.githubusercontent.com/11923641/90795511-be7c1080-e2d3-11ea-9128-2b8eea288c52.png)

**Comment by adubovikov** [comment]
ah, wait. Are you talking that you don't see aliases in the search result ? You have to add field "aliasDst" and "aliasSrc"

here is the example:

```
0: {aliasDst: "135.115.130.166:5060", aliasSrc: "241.138.214.5:5064", callid: "2x6zww@127.0.0.1",…}
aliasDst: "135.115.130.166:5060"
aliasSrc: "241.138.214.5:5064"
callid: "2x6zww@127.0.0.1"
captureId: "2001"
capturePass: "myHep"
correlation_id: "2x6zww@127.0.0.1"
create_date: 1597939074137
dbnode: "localnode"
dstIp: "135.115.130.166"
dstPort: 5060
from_domain: "sipcapture.org"
from_user: "hepgenjs"
id: 55069144
method: "INVITE"
node: "localnode"
payloadType: 1
protocol: 17
protocolFamily: 2
ruri_domain: "sipcapture.org"
ruri_user: "186"
sid: "2x6zww@127.0.0.1"
srcIp: "241.138.214.5"
srcPort: 5064
table: "hep_proto_1_call"
timeSeconds: 1597939074
timeUseconds: 137000
to_user: "186"
user_agent: "HEPGEN.JS@sipcapture.org"
```

**Comment by adubovikov** [comment]
Settings->Mapping 
call - SIP -> Edit

Fields Mapping:
```

{
        "id": "aliasDst",
        "name": "Alias Dest",
        "type": "string",
        "index": "none",
        "form_type": "input",
        "position": 25,
        "skip": false,
        "hide": false
    },

```

**Comment by cyrilconstantin** [comment]
I have added it to Fields Mapping but it doesn't update the Panel with the name:

![alias mapping](https://user-images.githubusercontent.com/11923641/90797483-55e26300-e2d6-11ea-9283-2f5d65361fe3.png)

**Comment by adubovikov** [comment]
if you use widget result - just recreate it or use to default (big page result)

**Comment by cyrilconstantin** [comment]
Indeed it works if I use the Default container. While using the widget "SIP search result" and editing the json file by adding your info and re-importing it, it doesn't display the alias.

[Home (2).txt](https://github.com/sipcapture/homer/files/5104543/Home.2.txt)

**Comment by adubovikov** [comment]
as I wrote above, destroy the existing "result" widget and add a new one.

**Comment by cyrilconstantin** [comment]
I have deleted the result widget and tried to recreate it but it seems to be buggy, I just have a blank vertical bar displayed on the left of my screen without the ability to choose the columns.


![chrome_rS6g0Tsems](https://user-images.githubusercontent.com/11923641/90806496-b7103380-e2e2-11ea-8a37-d0379f442b65.png)
![chrome_6FCh7Sl76h](https://user-images.githubusercontent.com/11923641/90806494-b6779d00-e2e2-11ea-8636-6ac0e78a8156.png)
![chrome_uW5iuUc3p5](https://user-images.githubusercontent.com/11923641/90806498-b7103380-e2e2-11ea-9d4f-3841a6d03676.png)

**Comment by adubovikov** [comment]
looks like you have broken it by editing json file of your dashboard :-(

just try to add a new dashboard, export it and reimport as home

**Comment by adubovikov** [comment]
or just complete remove HOME, after do logout and login - the app should recreate the default dashboard automaticaly

**Comment by adubovikov** [comment]
does it work ?

**Comment by cyrilconstantin** [comment]
It isn't possible to delete the main HOME dashboard, you can empty it but the Trash icon isn't available, I can't add the widget named "display results" because when I click on "column settings" from this widget it give me a blank vertical bar and I observed that before making any of your recommended changes. Even emptying the HOME dashboard login out and in won't recreate automatically anything.

I have created a new dashboard and imported the original json file and I'm seeing the Alias Dst and I have also added the ALIAS Src.

Is it something that could be added to the master branch to be available by default ?

Best Regards

**Comment by adubovikov** [comment]
unfortunately I couldn't reproduce your issue. Let me do some tests and i will come back to you

**Comment by dmsf100** [comment]
Following your instructions @adubovikov i managed to add destAlias to the widget but not to the default

![default](https://user-images.githubusercontent.com/45314626/90929373-828a9d80-e3f0-11ea-8208-306b7b042188.png)
![widget](https://user-images.githubusercontent.com/45314626/90929376-83bbca80-e3f0-11ea-9d80-bd5108e12a22.png)

**Comment by adubovikov** [comment]
please Reset the local storage:

Settings -> Reset

and check again

**Comment by dmsf100** [comment]
Resetting the local storage worked for me! 🙂

**Comment by adubovikov** [comment]
You know what todo here: https://github.com/sipcapture/homer/stargazers 

:-)

**Comment by adubovikov** [comment]
@cyrilconstantin what is about you ? Does it work ? Can we close the ticket?

**Comment by cyrilconstantin** [comment]
Hi,

Indeed after modifying the field mapping and resetting the local storage it worked. Can this be included by default in the next release ?

Thanks

**Comment by adubovikov** [comment]
@cyrilconstantin applogies, can you please make a PR ?
the changes should be done in this structure:

https://github.com/sipcapture/homer-app/blob/master/migration/jsonschema/jsonschema.go#L58

thank you!
