### ISSUE TITLE
INQUIRY Homer

### ISSUE THREAD

**Issue by LinuxSysAdmin** [sipcapture/homer#413]
We have several FreePBX / Grandstream PBXs, hosted and on-premise, We are looking for a monitoring system that can help me with the following:

1. Automate test calls and verify two-way audio
2. Detect packet loss, jitter, or latency issues
3. Monitor SIP and RTP packets
4. Monitor SIP registration for specified extensions / trunks
5. Alerting capabilities
6. Does not overuse pbx cpu/memory

Will Homer fulfill all our requirements?

**Comment by adubovikov** [comment]
1. no - check sipp
2. yes - check captagent/rtcp reports
3. YES/NO - we do SIP and RTCP in Homer
4. Yes
5. Yes - InfluxDB/Prometheus - Grafana/Kapacitor
6. depeneds on ammount of your memory
