### ISSUE TITLE
No DB rotation in homer7-docker

### ISSUE THREAD

**Issue by maximilianhofmann** [sipcapture/homer#414]
Hi,

we use hom7-prom-all with docker.
The rotation does not work. We have still data 6 days after.

Best regards.

**Comment by lmangani** [comment]
Hello @maximilianhofmann 
In order to get help, you'll need to share a little more, such as the exact version you are running, the configuration you are attempting to use, etc.

**Comment by maximilianhofmann** [comment]
Hi lmangani,

i have updated to the latest version, it seems to work after all. I observe.

Thanks

**Comment by adubovikov** [comment]
@maximilianhofmann https://github.com/sipcapture/homer/stargazers - you know that todo there :-)
