### ISSUE TITLE
is there any document about uploading our data?

### ISSUE THREAD

**Issue by zhangywww** [sipcapture/homer#416]
I want to upload the final audio call statistics to heplify-server, and display on the homer-app frontend, but I can't find something helpful. 
Is there any document or tuturial, about the relationship of hep_id proto_type and so on , about how to configure the mapping to make my own search and display the specific data ?

I am using homer 7.7.

**Comment by adubovikov** [comment]
you can use heplify and captagent that read your pcap file and send RTCP stats to Homer
