### ISSUE TITLE
Feature Reuests

### ISSUE THREAD

**Issue by swilkinsmitre** [sipcapture/homer#417]
Hello,

We just started using homing and find in very valuable for our debugging.  One thing we would really like to see is for Homer to be able to maintain RTCP and RTP packet history in the pcaps that Homer exports.

How can we create a feature request to include RTCP and RTP packets in a pcap export?

Thank you,

**Comment by adubovikov** [comment]
we can export only RTCP Json format. To do reconstruction to binary makes no sense
