### ISSUE TITLE
Homer not displaying data

### ISSUE THREAD

**Issue by tjcoding9** [sipcapture/homer#418]
**Setup:**
Host machine (Windows) running asterisk pbx. The res_hep_pjsip.so is loaded and hep.conf is present.
On packet capture I see that hep3 packets are being sent from the asterisk to the homer server port 9060.

Homer server is running on docker inside a linux vm on the above host machine. A tcpdump on this machine shows the packet being received for the port 9060.

**Issue:**
But no data is displayed on the homer home page at http://localhost:9080.

**Comment by adubovikov** [comment]
@tjcoding9 please check if you have any errors in the heplify-server, also please check if your postgress DB is up

**Comment by tjcoding9** [comment]
docker ps -a shows:

postgres:11-alpine                       "docker-entrypoint.s…"   22 hours ago        Up 11 hours (healthy)       5432/tcp                                                                                         db

heplify is also not showing any errors:
sipcapture/heplify-server:master         "./heplify-server"       22 hours ago        Up 11 hours                 0.0.0.0:9060->9060/tcp, 0.0.0.0:9060->9060/udp, 9090/tcp                                         heplify-server

**Comment by adubovikov** [comment]
and do you see any insertion on port 5432  ? This is posgres port. Run ngrep or tcpdump just to be sure that your heplify-server inserts data

Also check if you have any tables/data in the posgress using psql CLI

**Comment by tjcoding9** [comment]
In the tcpdump I do not see any insertion to port 5432.

How do I access the tables in postgress?
I used the following command but it dosent work:
sudo docker exec -tiu postgres db psql

Here is my docker instance:
977d11a13e14        postgres:11-alpine                       "docker-entrypoint.s…"   22 hours ago        Up 11 hours (healthy)       5432/tcp                                                                                         db

**Comment by adubovikov** [comment]
if you don't see any insertion to port 5432, this means heplify-server doesn't send any. Now you have to be sure if you have received the HEP message on the application level and heplify-server can see it and work on it

@lmangani any another suggestion here ?

**Comment by tjcoding9** [comment]
The packet capture sent from asterisk shows hep3 sent using udp when open in wireshark .

**Comment by adubovikov** [comment]
yes, but this is network level, you have to be sure that messages have been delivered to the application (heplify-server)

**Comment by lmangani** [comment]
I would suggest running a hepgen.js scenario on the same host. If it shows, Homer is fine.

**Comment by tjcoding9** [comment]
could you please point me to the steps to do that?

**Comment by lmangani** [comment]
inside the `heplify-server` container install and run ngrep or tcpdump to make sure the packets reach the instance. If they do not, make sure your firewall allows packets being delivered to the container/docker network.

**Comment by adubovikov** [comment]
can we close this ticket ?
