### ISSUE TITLE
Can I use mysql with homer 7?

### ISSUE THREAD

**Issue by tjcoding9** [sipcapture/homer#419]
Hello I have setup the heplify server to use mysql db using teh environment variables as shown below:
environment:
      - "HEPLIFYSERVER_HEPADDR=0.0.0.0:9060"
      - "HEPLIFYSERVER_HEPTLSADDR=0.0.0.0:9060"
      - "HEPLIFYSERVER_HEPTCPADDR="
      - "HEPLIFYSERVER_DBSHEMA=homer7"
      - "HEPLIFYSERVER_DBDRIVER=mysql"
      - "HEPLIFYSERVER_DBADDR=db:3306"
      - "HEPLIFYSERVER_DBUSER=root"
      - "HEPLIFYSERVER_DBPASS=homerSeven"
      - "HEPLIFYSERVER_DBDATATABLE=homer_data"
      - "HEPLIFYSERVER_DBCONFTABLE=homer_config"
      - "HEPLIFYSERVER_DBROTATE=true"
      - "HEPLIFYSERVER_DBDROPDAYS=5"

But the homer-webapp still tries to use postgres and hence the container fails. Is there a way to use mysql here?

**Comment by adubovikov** [comment]
probably heplify-server can write to the mysql DB, but homer-app can work only with PostgreSQL now. Do you have any doubt ?

**Comment by CorrieM** [comment]
> probably heplify-server can write to the mysql DB, but homer-app can work only with PostgreSQL now. Do you have any doubt ?

Hi Adubovikov 
I am trying to get Homer 7 data to MSSQL but I see MSSQL Driver is not supported.
So my next step was to make use of MariaDB instead of Postgres and then link MariaDB(MySQL) to MSSQL, can you tell me if this will work ?

**Comment by lmangani** [comment]
@CorrieM you can't use HOMER7 with MySQL, only Postgres is currently supported by all elements. You can of course dump data into other databases, but do not expect the UI to work with them if you take that route.

**Comment by CorrieM** [comment]
> @CorrieM you can't use HOMER7 with MySQL, only Postgres is currently supported by all elements. You can of course dump data into other databases, but do not expect the UI to work with them if you take that route.

Next Question how should my heplify-server file look like? if I want to truncate the tables to just keep 30days of data ?
I currently have no disk space left , and I see in the pgsql/12/data/base/16385/ there is every hour a 820mb file :(

This is my current settings 

DBDataTable           = "homer_data"
DBConfTable           = "homer_config"
DBBulk                = 100
DBTimer               = 4
DBBuffer              = 400000
DBWorker              = 8
DBRotate              = true
DBPartLog             = "2h"
DBPartSip             = "1h"
DBPartQos             = "6h"
DBDropDays            = 7
DBDropDaysCall        = 0
DBDropDaysRegister    = 0
DBDropDaysDefault     = 0
DBDropOnStart         = true
DBUsageProtection     = true
DBUsageScheme         = "percentage"
DBPercentageUsage     = "80%"
DBMaxSize             = "30MB"
Dedup                 = false


Please assist me with the correct setting to just keep 30days of data.

**Comment by lmangani** [comment]
This issue is closed, please do not pollute it with other topics. Feel free to open a new one with this problem, and before doing so make sure you are using the latest version of our packages and consult the default examples.
