### ISSUE TITLE
Cant connect to postgresql

### ISSUE THREAD

**Issue by v1cdang** [sipcapture/homer#420]
Any reason why I keep getting the error when I run

homer-app -create-config-db -database-root-user=postgres -database-host=localhost -database-root-password=postgres -database-homer-user=homer_user

CONNECT to DB ROOT STRING: [host=localhost user=postgres dbname=postgres sslmode=disable port=5432 password=postgres]

{"level":"error","msg":"pq: Ident authentication failed for user \"postgres\"","time":"2020-09-24T15:00:41Z"}
{"level":"error","msg":"Couldn't establish connection. Please be sure you can have correct passwordpq: Ident authentication failed for user \"postgres\"","time":"2020-09-24T15:00:41Z"}
{"level":"error","msg":"Try run: sudo -u postgres psql -c \"ALTER USER postgres PASSWORD 'postgres';\"","time":"2020-09-24T15:00:41Z"}
panic: pq: Ident authentication failed for user "postgres"

**Comment by lmangani** [comment]
The password for user `postgres` seems to be wrong or not matching what expected. How did you install postgres?
Just change `database-root-password=postgres` to the correct postgres password or `-database-root-user=postgres` to the user you have access to, or just reset it from psql shell to progress.

**Comment by v1cdang** [comment]
I've already made the changes to the postgres user password by doing this

ALTER USER postgres with password 'postgres';

and Im still getting same error thou

**Comment by aqsyonas** [comment]
you need to add  proper setttings in your  pg_hba.conf file.

https://stackoverflow.com/questions/2942485/psql-fatal-ident-authentication-failed-for-user-postgres
https://github.com/sipcapture/homer-installer/blob/master/homer_installer.sh#L442-L443

Br, Aqs

**Comment by adubovikov** [comment]
@v1cdang please star it :-) https://github.com/sipcapture/homer/stargazers

**Comment by v1cdang** [comment]
I was able to get it to work. Seems like the hba.conf didnt update to md5.
Which worked. Now I just need it to collect sip messages and connect it to
opensip
