### ISSUE TITLE
What is Share Cloud?

### ISSUE THREAD

**Issue by noahrotheray** [sipcapture/homer#421]
Hey Guys,

Quick question, what is the Share cloud option under the Session 'Export' tab?

![image](https://user-images.githubusercontent.com/31306657/94599139-4d475a00-0290-11eb-8cb7-277a080ec76c.png)

I'm just curious as its always been greyed out for me?

**Comment by adubovikov** [comment]
this is an option to save your pcap to an external cloud storage, like cloudshark

**Comment by noahrotheray** [comment]
Alright awesome, thanks @adubovikov

**Comment by adubovikov** [comment]
btw, you didn't star us :-( please do https://github.com/sipcapture/homer/stargazers

**Comment by noahrotheray** [comment]
Done!

Sorry I'm terrible at these things 😌
