### ISSUE TITLE
Homer install on Centos 8

### ISSUE THREAD

**Issue by mkezys** [sipcapture/homer#423]
Hi! 

Made a guide: https://blog.kolmisoft.com/homer-install-on-centos-8/
Thought will share.

Thanks for the amazing software!

**Comment by adubovikov** [comment]
Awesome! Thank you so much!!!

**Comment by reqlez** [comment]
Hi.

Have you managed to make the docker install work with CentOS 8 ?  I'm getting bad gateway on ports 9080 and 9090 after the docker images start up.

**Comment by reqlez** [comment]
And yes, I did confirm that doing this modification does not work:

volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

**Comment by lmangani** [comment]
@reqlez if this is related to docker, its best to open a separate issue to get help

**Comment by lmangani** [comment]
Closing for no updates. Please reopen if this is still an issue.
