### ISSUE TITLE
Admin Node

### ISSUE THREAD

**Issue by dmigardos** [sipcapture/homer#424]
Hi Team,

In the past we used Homer 5.0.5 and it had a section to add additional Nodes (databases).  This was located under System -> Admin

In version 7.8.5 I can't seem to locate this option?

Screen shot from version 5.0.5:
https://drive.google.com/file/d/16EovmA2dB0ib9aQgsoOldBKSX8IcJ89K/view?usp=sharing

Basically, we have are looking to have the option to use one GUI but search multiple homer databases.  Is this something that could be added or is task now completed via another method?

Thank you,
Dennis

**Comment by lmangani** [comment]
Hello @dmigardos 

A bit buried and hard to find indeed, but here's the setting you are looking for: https://github.com/sipcapture/homer-app/wiki/Multinode-setup
