### ISSUE TITLE
Session Duration 

### ISSUE THREAD

**Issue by dmigardos** [sipcapture/homer#425]
Hi Team,

Our Homer 5.0.5 installation showed a session duration (screen shot link below) in the ladder diagram section.
https://drive.google.com/file/d/166D0K294PJkweplQyXaUS2COSgWTuKbW/view?usp=sharing

Do you have this option in homer 7.8.5?

**Comment by adubovikov** [comment]
the version 1.3.0 has been released. Please install it and retest it.

**Comment by dmigardos** [comment]
Hi Team, I have installed 1.3.0 and now 1.3.3.  However, the session duration is still not present  

Here is a screen shot of the session duration in the call flow of homer 5
https://drive.google.com/file/d/166D0K294PJkweplQyXaUS2COSgWTuKbW/view?usp=sharing

**Comment by adubovikov** [comment]
Can you show the screenshot of your "transaction view" ? Do you have "Session Info" tab ?

**Comment by dmigardos** [comment]
Hi Alexandr, I see it under the session info.  Thank you feel free to close
the case.

**Comment by adubovikov** [comment]
sure, once you will give us a star here: https://github.com/sipcapture/homer/stargazers

**Comment by dmigardos** [comment]
Star added.  Thank you again.

**Comment by adubovikov** [comment]
Thank you :)
closed!
