### ISSUE TITLE
Row display / Call Flows with more than 100 packet Issue.

### ISSUE THREAD

**Issue by dmigardos** [sipcapture/homer#426]
Hi,

The rows on the homer 7.8.5 display are limited to 100 per page.
Link to screen shot: https://drive.google.com/file/d/1z7IuQpIxGyW_E-mE3rT67L3ehHyOjLJz/view?usp=sharing

On some long duration calls where multiple re-invites are sent we could receive up to 400 packets (400 row displayed)

Homer allows us to go to... 
page 1 of 4 (to view packets 1-100)
page 2 of 4 (to view packets 101 - 200)
page 3 of 4 (to view packets 201 - 300)
page 4 of 4 (to view packets 301 - 400)

However, if you are on one of these pages (ex: page 1 of 4) and you click on the call ID the messages, flows and export tab will only show data for that one page (ex: page 1 of 4) and not include the other packets on pages 2 to 4.

My previous version of homer, 5.0.5 did not seem to do this.  Is this behavior by design on Homer 7?

Is it possible to increase the display row lines to 2,000 as homer 5.0.5 allowed previously?  I can't find this option on the GUI.

**Comment by adubovikov** [comment]
the version 1.3.0 has been released. Please install it and retest it.

**Comment by adubovikov** [comment]
can you also be sure that your time range is cover the call duration of your call, because the last param will be taken exactly from your time range.

**Comment by dmigardos** [comment]
Hi Team,

Thank you for looking into this.

I upgraded the homer-app to 1.3.0 and I don't see a change I'm afraid.

I'm looking at a 4 pages long call (313 packets) and I see the same
behavior as before.   When I click on the call ID I only see the packets
within that page.

apt-cache policy homer-app
homer-app:
  Installed: 1.3.0
  Candidate: 1.3.0
  Version table:
 *** 1.3.0 500


NOTE: I also issued a systemctl stop homer-app and systemctl start
homer-app after the installation.

**Comment by lmangani** [comment]
@dmigardos please provide a screen capture or short video to demonstrate the issue. I cannot reproduce it.

**Comment by dmigardos** [comment]
Hi,

Do you have a gmail email address so I could send you a secure link, I
don't want to make the data public.

**Comment by adubovikov** [comment]
On the left side you have "query limit" put something bigger and make a
search

**Comment by dmigardos** [comment]
Hi,

I set the query limit to 2,000 but it still shows 100 rows and the data
when you select the CallID only shows the content of those 100 packets.

Here is a screenshot.
https://drive.google.com/file/d/1z_rNFFSSQJwUC5FNE4QScFmungmioGcX/view?usp=sharing

**Comment by adubovikov** [comment]
sorry, couldn't get you. What is problem now ? You have 383 records for this call in the period last 24 hours

please click on the callid and show how many records do you have in the call flow / messages

![Screenshot from 2020-11-19 13-42-16](https://user-images.githubusercontent.com/4513061/99668181-abf9aa80-2a6d-11eb-9b0e-6085e3eb1225.png)

**Comment by dmigardos** [comment]
Hi,


   - The call which I searched for had 322 packets.
   - Homer shows these 322 packets in 4 pages
      - Page 1: 1-100
      - Page 2: 101-200
      - Page 3: 201-300
      - Page 4: 301-322
   - If I'm viewing page 1 and I click on the call ID on one of the packets
   on page 1 the ladder diagram only shows me packets on page 1 and does not
   show packets on page 2, 3 and 4
   - If I'm viewing page 2 and I click on the call ID on one of the packets
   on page 2 the ladder diagram only shows me packets on page 2 and does not
   show packets on page 1, 3 and 4
   - If I'm viewing page 3 and I click on the call ID on one of the packets
   on page 3 the ladder diagram only shows me packets on page 3 and does not
   show packets on page 1, 2 and 4
   - If I'm viewing page 4 and I click on the call ID on one of the packets
   on page 4 the ladder diagram only shows me packets on page 4 and does not
   show packets on page 1, 2 and 3

I would like to click on the callID and would like to see all 322 packets
of this call not just the packets on the page I'm currently viewing (this
was available in Homer 5)

**Comment by lmangani** [comment]
@dmigardos could you then attach screenshots for this case, showing us exactly the call-flow resulting from each example? You can just drag images on the github issue editor, it will upload them and display.

**Comment by dmigardos** [comment]
Hi Lorenzo,  I don't want to make the user data (telephone numbers, IPs,
etc...) in the ladder diagram public.  if you have a gmail email address I
could provide a link which only your gmail account has access to view.

**Comment by lmangani** [comment]
our main goal here is understanding - blur out the information you dont want us to see.

**Comment by adubovikov** [comment]
@dmigardos please install 1.3.3 and re-check it

**Comment by dmigardos** [comment]
Alexandr, great job!  I now see the full call flow.

**Comment by adubovikov** [comment]
Perfect! dont' forget to start our Project :-)
