### ISSUE TITLE
Homer 7 No data in DB

### ISSUE THREAD

**Issue by abitrusty** [sipcapture/homer#428]
Hi,

Homer 7.9.7

To begin I am competely new to Homer and defintely not a Linux guru so I'm hoping this is a simple fix or that it jsut isn't going to work like this

I've installed Homer 7 using the Homer_Installer.sh script on a Debian 9 net-install image. The server has 2 x NICs of whih one is in our "SIP" VLAN. 
Everything seems fine with the install - as in can get to Homer GUI, I've checked the DB and all the expected tables are there but are empty

I've done a tcpdump capture on the "SIP" interface and can conform I am seeing all the SIP Signalling and UDP traffic I expect. The heplify-server.toml config is pretty much left at default

Am I right in saying I also need to install heplify client on this server to sniff the SIP interface - after homer_installer.sh script finishes it gives details on how to start stop heplify client service but it actually isn't installed....jsut heplify-server

I guess my question mainly is how can I get traffic sniffed from this SIP interface into the database?

Also to note it is mainly Cisco SIP traffic I want if there are any better parameters for this

Any help or guidance on this si appreciated

Thanks

**Comment by adubovikov** [comment]
Hi abitrusty,

you can easy install heplify using packages:

curl -s https://packagecloud.io/install/repositories/qxip/sipcapture/script.deb.sh | sudo bash
sudo apt-get install heplify

or 
wget --content-disposition https://packagecloud.io/qxip/sipcapture/packages/debian/stretch/heplify_1.61.0_amd64.deb/download.deb


the configuration of heplify is very simple:

https://github.com/sipcapture/heplify#examples

so, runs you will start the heplify with normal settings you will able see your data.

Enjoy!

**Comment by abitrusty** [comment]
Hi,

Many thanks for response. I have tried installing heplify on this server and running it manually but it doesn't appear to be picking up any packets or putting anything in DB. If I run tcpdump on same interface I can se all SIP messages

Below is what I see when running it

![image](https://user-images.githubusercontent.com/54104859/101072643-3ece3500-3596-11eb-8d02-cf46e08088f5.png)

I've managed to install captagent on a test node else where which is spanning the same VLAN and it is ending all the info to Homer perfectly but ideally I'd rather have it all on same server. Am I missing something easy with heplify you think?

**Comment by adubovikov** [comment]
yes, you forgot to activate VLAN flag: -vlan param

**Comment by abitrusty** [comment]
Unfortunately still the same. I've tried puttng interface in/out of promiscuous mode. Tried it with and without an IP but still the same...... I'd think it was an interface issue but tcpdump picks up the packets. Anything else I can try you think?

![image](https://user-images.githubusercontent.com/54104859/101088832-29fc9c00-35ac-11eb-9b19-d70335dc08ed.png)

**Comment by adubovikov** [comment]
if you will take this filter and apply to tcpdump - will you see the packets ? I think you should capture some messages to pcap and see if this BPF filter can be applied to your traffic (maybe you have some another encapsulation or GRE traffic)

**Comment by abitrusty** [comment]
Ah ok think you have picked it - I see lots of GREv0 when i do a tcpdump -i ens160 -vlan

Is there anything I can do here?

![image](https://user-images.githubusercontent.com/54104859/101091486-210dc980-35b0-11eb-9a94-ab3dc0535d35.png)

**Comment by abitrusty** [comment]
![image](https://user-images.githubusercontent.com/54104859/101094236-fcb3ec00-35b3-11eb-8ee4-b358098b4f9d.png)

From readin posts looks like I should be able to get this with -erspan but still not getting any hits - looks like I'm getting drops

![image](https://user-images.githubusercontent.com/54104859/101094348-2d942100-35b4-11eb-83bb-04addd9e9df9.png)

**Comment by adubovikov** [comment]
try to leave only -erspan flag and remove vlan

**Comment by abitrusty** [comment]
Noy joy still I'm afraid. Tried with and without. Jsut doesn't like it for some reason.....looks like might have to run a seperate capture agent else where. Not the end of the world but if this should work I'd love to get it going. Thanks for taking the time

**Comment by adubovikov** [comment]
If u can provide a pcap file with you traffic, we can take a look at it and
give you the correct bpf filter.

**Comment by abitrusty** [comment]
That would be amazing if you could - how can I get a pcap to you?

**Comment by adubovikov** [comment]
you can send it to my email

**Comment by adubovikov** [comment]
so, if you can take the heplify from http://github.com/adubovikov/heplify and compile it, after please run it using -bpf flag:

here is an example that I use to validate on your pcap:

```
./heplify -rf tcpdump_ens160.pcap -l debug -bpf "ip[9]=47 and ((ip[62:2]>=0x13c4 and ip[62:2]<=0x13e2) or (ip[64:2]>=0x13c4 and ip[64:2]<=0x13e2))" -hs 127.0.0.1:9060
```

and it should work

**Comment by abitrusty** [comment]
HI,

I will do it shortly but I am a newb and not a linux admin or dev by any stretch. How do I go about compiling your version of heplify

Also to then run it as a service on Debian would be great too! 

Thanks

**Comment by adubovikov** [comment]
1. install heplify from packages
2. install golang
3. go get github.com/adubovikov/heplify
4 cd go/src/github.com/adubovikov/heplify
5. make
6. copy heplify to the installed directory
7. edit heplify.service to add custom bpf filter
8. run systemctl start heplify.service

if these steps are diffiifcult - you can wait untill the patch will be applied and we will release a new heplify

**Comment by adubovikov** [comment]
https://github.com/sipcapture/heplify/blob/master/example/heplify.service

the service file for it

**Comment by abitrusty** [comment]
Appreciate the time on this. Gave it a bash but will need to wait for the new heplify release :-)

Thanks for all your time on this!

**Comment by adubovikov** [comment]
heplify-1.63-amd64.deb is up

**Comment by abitrusty** [comment]
Looks to be working perfectly now!!! 

Legend!!

**Comment by adubovikov** [comment]
@abitrusty don't forget to star us: https://github.com/sipcapture/homer/stargazers

**Comment by abitrusty** [comment]
Done

**Comment by abitrusty** [comment]
Hi,

Sorry have a follow on question related to this. Will I re-open this thread?

Would that filter need tweaking to accept RTCP packets do you think? I'm not getting any captured from heplify but if I do a tcpdump I see them

**./heplify ii ens160 -bpf "ip[9]=47 and ((ip[62:2]>=0x13c4 and ip[62:2]<=0x13e2) or (ip[64:2]>=0x13c4 and ip[64:2]<=0x13e2))" -hs 127.0.0.1:9060**

2020/12/08 16:10:21.019828 util.go:100: INFO Packets since last minute IPv4: 1482, IPv6: 0, UDP: 625, TCP: 116, SCTP: 0, RTCP: 0, RTCPFail: 0, DNS: 0, duplicate: 0, fragments: 0, unknown: 897

**Comment by kYroL01** [comment]
In your filter `ip[9]=47` means that you're trying to filter pkt with GRE encapsulation.
If you don't have GRE you need to put `ip[9]=17` for UDP or `ip[9]=6` for TCP.
Consider that you're also filtering for portrange `5060-5090` (**0x13c4 - 0x13e2**)

**Comment by abitrusty** [comment]
OK - RTCP Packets are defintely coming in as GRE and I see how that capture works now. Thanks! I've tried changing the port range to 5060 - 50000 and I now see some RTCP packets captured but im also capturing all the RTP packets as well so the files are huge - all my SIP traffic is UDP. Assume there is no way to seperate the RTCP out as my homer server will proably keel over capturing all the RTP as well

.

**Comment by adubovikov** [comment]
you can also isolate and capture ONLY rtcp traffic: 

```
sniffer.bpf = "(tcp or sctp) and greater 42 and portrange " + sniffer.config.PortRange + " or (udp and greater 128 and portrange " + sniffer.config.PortRange + " or ip[6:2] & 0x1fff != 0 or ip6[6]=44) or (ip and ip[6] & 0x2 = 0 and ip[6:2] & 0x1fff = 0 and udp and udp[8] & 0xc0 = 0x80 and udp[9] >= 0xc8 && udp[9] <= 0xcc)"

```

**Comment by adubovikov** [comment]
https://github.com/sipcapture/captagent/blob/master/include/captagent/capture.h#L41

**Comment by abitrusty** [comment]
Cheers guys....that's enough for me to play with for a while :-)

**Comment by abitrusty** [comment]
Hi guys, I'm assuming something is wrong with below as I'm not getting any hits on only RTCP (or anything) - I'm learning though I think

heplify -i ens160 -e -bpf "ip[9]=47 and (ip[6:2] & 0x1fff = 0 and udp and udp[8] & 0xc0 = 0x80 and udp[9] >= 0xc8 && udp[9] <= 0xcc)"

**Comment by kYroL01** [comment]
@abitrusty I think you need to understand properly how BPF works.
In this case, if you have GRE pkts you cannot filter using the `udp`, because that is for a standard pkt with L2->L3->L4 layer.
In this case you have to use only `ip` and play with the byte offset from there.

**Comment by abitrusty** [comment]
For completeness I was able to filter the RTCP packets by using below filter which gets the SIP ports and then also takes any UDP packet between 10000 and 50000 with an odd port number. Maybe not the cleanest but it works

heplify -i ens192 -bpf "ip[9]=47 and ((ip[62:2]>=0x13c4 and ip[62:2]<=0x13e2) or (ip[64:2]>=0x13c4 and ip[64:2]<=0x13e2) or (ip[62:2]>=0x2710 and ip[62:2]<=0xc350 and ip[62:2] & 1 ==1))"

Thanks for all your help on this guys!

**Comment by adubovikov** [comment]
you are welcome! Thanks for sharing your result!
