### ISSUE TITLE
no data captured. 

### ISSUE THREAD

**Issue by johandeclercqdemocon** [sipcapture/homer#429]
Hi, I installed homer 7 on debian 10 using the install script. 
Everything ran smooth (db is created, tables are okay, gui works). 
heplify-server.toml is default

There is however no data in the db. 
[homer.pcap.zip](https://github.com/sipcapture/homer/files/5642186/homer.pcap.zip)

following your troubeshoot document, it told me to check the messages as being hepv3. 
It seems they are. 

Do not that it are OPTIONS and the 200 OK response. 
is there somehting additional that I need to configure to have options in the DB ? 

attached the pcap.

**Comment by lmangani** [comment]
Hi @johandeclercqdemocon 
HOMER partitions messages according to the session type. Calls, Registrations, and everything else sit in different partitions to allow different rotations and faster queries. Try adding the partition type selector to your search form, and switching between them.

**Comment by johandeclercqdemocon** [comment]
thanks for the reply, can you point me to a document on how to add this to a search form ?

**Comment by adubovikov** [comment]
https://www.youtube.com/watch?v=fUu4DpVwWe0&feature=youtu.be

**Comment by johandeclercqdemocon** [comment]
this is what I find strange :

this is syslog :

Dec  4 13:39:42 HOMER-01 /usr/local/bin/heplify-server[553]:
decoder.go:149: [hep]
&HEP{Version:2,Protocol:17,SrcIP:176.241.249.28,DstIP:10.254.100.131,SrcPort:5060,DstPort:5060,Tsec:1607085582,Tmsec:607790,ProtoType:1,NodeID:1,NodePW:,Payload:OPTIONS
sip:10.254.100.131 SIP/2.0#015#012Record-Route:
<sip:176.241.249.28;lr;ftag=as339857eb>#015#012Via: SIP/2.0/UDP
176.241.249.28;branch=z9hG4bKf2f1.e9432f73.0#015#012Via: SIP/2.0/UDP
176.241.249.19:5060;received=176.241.249.19;branch=z9hG4bK69323848;rport=5060#015#012From:
"Anonymous" <sip:Anonymous@176.241.249.19>;tag=as339857eb#015#012To:
<sip:10.254.100.131>#015#012Contact:
<sip:Anonymous@176.241.249.19>#015#012Call-ID:
002c2fc35417af792b4860a50ff7712f@176.241.249.19#015#012CSeq: 102
OPTIONS#015#012User-Agent: SBC01-BRS#015#012Max-Forwards:
69#015#012Date: Fri, 04 Dec 2020 12:39:42 GMT#015#012Allow: INVITE, ACK,
CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY#015#012Supported:
replaces#015#012Content-Length:
0#015#012#015#012,CID:002c2fc35417af792b4860a50ff7712f@176.241.249.19,Vlan:0,}

oddly enough the attached pcap says v3.

**Comment by adubovikov** [comment]
Version:2 - this is not hep version, but IP version (2 = Ipv4)

https://github.com/sipcapture/heplify-server/blob/master/decoder/decoder.go#L47

**Comment by johandeclercqdemocon** [comment]
still no luck.  What else can I check to fix this ?

Op vr 4 dec. 2020 om 14:08 schreef Alexandr Dubovikov <
notifications@github.com>:

**Comment by adubovikov** [comment]
sorry, do you have any data in Postgress ?

you can use or CLI or pgsqladmin to check if your tables have been populated

**Comment by johandeclercqdemocon** [comment]
|when I do below query: SELECT nspname AS schemaname,relname,reltuples
FROM pg_class C LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)
WHERE nspname NOT IN ('pg_catalog', 'information_schema') AND
relkind='r' ORDER BY reltuples DESC; all tables show me reltuples = 0.
So the tables do not get populated. wkr, |

**Comment by johandeclercqdemocon** [comment]
is there somewhere a log file that I can check ?

Thanks, Johan.

Op ma 7 dec. 2020 om 16:55 schreef johan <johan@democon.be>:

**Comment by adubovikov** [comment]
hard to say - you should check heplify-server log and also postgres's logs

**Comment by johandeclercqdemocon** [comment]
I noticed that the debian vanilla is in french.

Could that be the issue ?


Secondly, when looking in the logs of pgsql, I only see that the db is
started.

connecntions are not mentioned.  So it seems to me that homer doesn't
make a connection.

**Comment by johandeclercqdemocon** [comment]
Hi, I found it.

heplify-server starts too fast.

the db is not started yet => timeout.

restart heplify-server fixed the issue.


wkr,

**Comment by adubovikov** [comment]
oki, i think in the heplify-server.service should be wait for pgsql @negbie

**Comment by adubovikov** [comment]
[Unit]
After=postgresql.service

**Comment by adubovikov** [comment]
anyway, this param is optional and valid only in case heplify-server and postgress are on the same box

**Comment by johandeclercqdemocon** [comment]
Hello Alexandr,


I have 2 suggestions :

- as homer 7 was installed in the very simple way (using the .sh
script), I think that the .service file should have the addition included.

- secondly, when the connectoin to the DB fails, I think that it would
be wise that heplify-server tries to reconnect (at least 4 times, before
giving a critical error; it would be handy if that error could be seen
in the web gui (maybe thsi last thing is a bit over the top :-) ))

**Comment by adubovikov** [comment]
@johandeclercqdemocon i think it does reconnect but only if the first connection was succesful. About first suggestion, it will be ok if you have a local postgres, but many users use remote DB server and in this case it will be failed. Specialy in the docker scenario.... So, let me add this as a WIKI and it will solve the issue

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer/wiki/Heplify-server-AND-Postgress-on-same-host

**Comment by adubovikov** [comment]
@lmangani can we add an option to the installer script and add this line on demand ?
