### ISSUE TITLE
Incorrectly Calculated Jitter?

### ISSUE THREAD

**Issue by noahrotheray** [sipcapture/homer#430]
Hi Guys,

We have +-15 FreeSwitch boxes that currently report to our homer server through heplify.

We have a single host, that for some reason, reports huge amounts of jitter in its calls, but only in a single RTCP packet:
![image](https://user-images.githubusercontent.com/31306657/101478429-5b34ed80-3959-11eb-8712-d5f2c5430149.png)

This occurs in 90% of calls on this host. There aren't any issues with the call quality, the quality is clear...and I've checked hundreds of calls, the problem is this throws our jitter alert off, as this host, according to Grafana, constantly has high jitter.

FYI: .218 is my FreeSwitch host, .35 is our provider. 

Scenario:
A party calls in -> we play early media disclaimer -> forward the call to B party

Could this actually just be bad RTP from the provider for that second or 2 during the call, or miscalculated jitter?

Any ideas?

**Comment by lmangani** [comment]
It's most likely due to the early media injection. The sequence of this injected stream differs from the real time, and statistically speaking, its an anomaly. Is this by any chance a playback of RTP w/o transcoding into the stream?

**Comment by lmangani** [comment]
```
seq 00001
seq 00001
seq 00001
seq 00001
seq 00001
```
```
seq 00001
seq 00001
seq 00001
```
```
seq 00001
seq 00001
seq 00001

**Comment by adubovikov** [comment]
As @lmangani said above, it's typical media injection: announce or custom ringing, that doesn't have a rtp mark and jitter in this case will be huge. I think you have to capture a rtp stream and do analysis on it. I close the ticket, because it's not an issue in Homer

**Comment by noahrotheray** [comment]
Thanks guys, 
You were right...that early media injection was causing this, had a look at an actual RTP stream:
![image](https://user-images.githubusercontent.com/31306657/101910892-4742f300-3bc8-11eb-834f-93ef473c9e20.png)
Appreciate the input.

**Comment by adubovikov** [comment]
super! Glad to read it! :-)
