### ISSUE TITLE
heplify-server  .. decoder.go:132: WARN Authorization.parse err: no LWS found

### ISSUE THREAD

**Issue by sido420** [sipcapture/homer#432]
I followed the instructions at https://github.com/sipcapture/homer/wiki/Examples%3A-Kamailio and https://github.com/sipcapture/homer7-docker/tree/master/heplify-server/hom7-prom-all to run Homer and related containers but getting the error in subject

```
heplify-server  .. decoder.go:132: WARN Authorization.parse err: no LWS found
```

Also, the SIP message sent from Kamailio is printed right below this error in homer container logs. But, I only see blank graphs in Homer UI.

So packets are coming from Kamailio but not being accepted by Homer it seems.

```
version: kamailio 5.4.2 (x86_64/linux) f8885c
```

Kamailio settings:
```
modparam("siptrace", "duplicate_uri", "sip:homer_address:9060")
modparam("siptrace", "hep_mode_on", 1)
modparam("siptrace", "hep_version", 3)
modparam("siptrace", "trace_sl_acks", 1)
modparam("siptrace", "trace_to_database", 0)
modparam("siptrace", "trace_flag", 22) // same as in the setflag(22) call 
modparam("siptrace", "trace_on", 1)
```

**Comment by adubovikov** [comment]
the decoder's output it's just a warning - the Auth header doesn't have LWS
about the rest: please check if you have connection to postgress and heplify-server sends something there: you can also check if tables have been populated or use ngrep -W byline -d any port 5432

**Comment by sido420** [comment]
Its a fresh `docker-compose up` install on a fresh cloud VM, so it should technically work as is.

I will investigate and report back.

**Comment by adubovikov** [comment]
just be sure that posgress will start before heplify-server ... this is common issue

**Comment by sido420** [comment]
That is taken care of by `depends_on` in docker compose file for heplify-server. 

Postgres  should be starting before heplify-server.

**Comment by adubovikov** [comment]
in this case just check if u see any data goes to postgres on port 5432

**Comment by sido420** [comment]
I looked inside the `homer_data` database in postgres and found  7 tables there. All of them are empty except `public.hep_proto_100_default`. 
`public.hep_proto_100_default` contains log records from Kamailio that I am sending via `hlog`. 

```
	hlog("[cfg:$cfg(line)] This is a log from kamailio to Homer");
```

Unless I am looking inside the wrong database, data is coming to heplify and is being logged in DB. For some reason, its not logging SIP records and I doubt authorization as per the error message.

**Comment by adubovikov** [comment]
dont think so, because not all your SIP messages have Authorization header and as I wrote above - this is just a WARNING, not an error

**Comment by sido420** [comment]
Looks like Authorization string is there in SIP message.

```
grafana           | t=2020-12-14T14:54:20+0000 lvl=warn msg="Skipping OAuth auto login because multiple OAuth providers are configured"
heplify-server    | 2020/12/14 14:54:21.044359 decoder.go:132: WARN Authorization.parse err: no LWS found
heplify-server    | "REGISTER sip:test.example.com:4753 SIP/2.0\r\nVia: SIP/2.0/TLS 6nir0s33usfe.invalid;branch=z9hG4bK5504772\r\nMax-Forwards: 69\r\nTo: <sip:user1@test.example.com>\r\nFrom: <sip:user1@test.example.com>;tag=5ciq6m2f8p\r\nCall-ID: tnjdbv1onbhogcq65439ll\r\nCSeq: 1 REGISTER\r\nAuthorization: 1234-FGFDS54-53452354F\r\nContact: <sip:v9t6hq3p@6nir0s33usfe.invalid;transport=ws>;+sip.ice;reg-id=1;+sip.instance=\"<urn:uuid:4012ebfe-e79b-1234-1234-033ff82f9417>\";expires=600\r\nExpires: 600\r\nAllow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO,NOTIFY\r\nSupported: path,gruu,outbound\r\nUser-Agent: JSSIP\r\nContent-Length: 0\r\n\r\n"
heplify-server    | nodeID: 1, protoType: 1, version: 2, protocol: 22, length: 624, flow: 162.222.82.9:3398->172.22.0.4:8443
```

So whats the solution for this case?

**Comment by adubovikov** [comment]
you didn't get me, I said that Authorization header is not in EACH SIP messages, therefore if it was the reason, you would see another messages in the tables. For now you dont see ANY messages. So, please check it

**Comment by sido420** [comment]
Sorry, I am new to this VoIP world. I did check other SIP packets like `MESSAGE`. It is also showing Authorization string in logs. 
I'm using JSSIP on the client side with `authorization_jwt` option and that might be adding that.

So, I believe all my SIP packets will contain the authorization header. If theres no solution (yet), do you know how Kamailio config could be modified to redact the Authorization string, execute sip_trace(); (to send SIP packet to Homer), and put the Authorization header back in packet? Is there a Homer setting?

**Comment by sido420** [comment]
Ref: https://jssip.net/documentation/3.6.x/api/ua_configuration_parameters/#parameter_authorization_jwt

**Comment by adubovikov** [comment]
@sido420 i think you send not SIP, but WEBSOCKET messages can you capture the data that kamailio sends to heplify-server (port 9060) to a pcap file (tcpdump/ngrep) and share it to us

**Comment by sido420** [comment]
Yes, JSSIP connects to Kamailio via Websocket.

What I shared earlier was in the heplify-server container logs. 

Here is `ngrep` output from inside the heplify-server container. It was captured when I sent a message via JSSIP+Kamailio.

```
~ # ngrep port 9060
interface: eth0 (172.18.0.0/255.255.0.0)
filter: ( port 9060 ) and ((ip || ip6) || (vlan && (ip || ip6)))
#
U 214.176.29.117:7890 -> 172.18.0.9:9060 #1
  HEP3.................................w........#d.............._..}........Bo......d................9p9u03jmj6c8n0me9tkn.....4[cfg:880] This is a log from kamailio to Homer                                                                               
#
U 214.176.29.117:7890 -> 172.18.0.9:9060 #2
  HEP3.Q......................R......................... ......._..}........B........................MESSAGE sip:sido_423432879@test.example.com SIP/2.0..Via: SIP/2.0/TLS jmqvlg8bcs62.invalid;branch=z9hG4bK85767..Max-Forwards: 69..To: <sip:sido_4234328
  79@test.example.com>..From: <sip:sido_q@test.example.com>;tag=vunq3afjqb..Call-ID: 9p9u03jmj6c8n0me9tkn..CSeq: 709 MESSAGE..Authorization: 5AC5435GFDGSD-GFGSDE767..Content-Type: text/plain..Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPT
  IONS,REFER,INFO,NOTIFY..Supported: outbound..User-Agent: JSSIP..Content-Length: 7....fsdgfd4 
```

**Comment by adubovikov** [comment]
check if you don't drop the messages that not related to "CALL" and "Register"

**Comment by sido420** [comment]
I am not dropping any messages and honestly I dont even know how to drop messages. REGISTER, MESSAGE etc can be captured using `ngrep` inside the heplify container. 

Just to clarify, I dont see any (including REGISTER and CALL) messages in the database. The only ones are the log messages or *only* SIP packets without authorization header.

**Comment by adubovikov** [comment]
as I said, please provide us a pcap with your HEP packets from your
kamailio. We can check and do analyze.

**Comment by lmangani** [comment]
Closing for no updates. Please reopen if this is still an issue.
