### ISSUE TITLE
How to figure out what DTMF RTP events were sent?

### ISSUE THREAD

**Issue by mikebevz** [sipcapture/homer#433]
Hi,

I'm trying to figure out how to see DMTF RTP events. I see some RTP packets in Homer7 UI, but I don't see any DTMF ones.

Should I configure Homer7 additionally to be able to do that? 

Thanks in advance for answer,
Michael

**Comment by adubovikov** [comment]
Hi @mikebevz ,

Homer doesn't have RTP event support from, but you can send a quote for HEPIC or Rtpagent that can add such functionality
http://hepic.tel/

Regards,
Alexandr

**Comment by mikebevz** [comment]
Alright, got it! Thanks a lot for response!
