### ISSUE TITLE
hom7-influx-tick

### ISSUE THREAD

**Issue by jmillican61** [sipcapture/homer#434]
OS Ubuntu 20.04.1 LTS (Focal Fossa)
root@homer:~/homer7-docker-master/heplify-server/hom7-influx-tick# docker version
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Oct 14 19:43:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.12
  Git commit:       77e06fd
  Built:            Mon Jun  8 20:24:59 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

root@homer:~/homer7-docker-master/heplify-server/hom7-influx-tick# docker container list --all 
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                      PORTS                                                                                            NAMES
f5c0166012b6        telegraf:1.5-alpine                "/entrypoint.sh teleâ¦"   11 minutes ago      Up 11 minutes               0.0.0.0:8092->8092/udp, 0.0.0.0:8125->8125/udp, 8094/tcp                                         hom7-influx-tick_telegraf_1
4d4924b19116        sipcapture/hepsub:master           "/entrypoint.sh npm â¦"   11 minutes ago      Exited (1) 11 minutes ago                                                                                                    hepsub
2c90a4b47447        chronograf:1.5-alpine              "/entrypoint.sh chroâ¦"   11 minutes ago      Up 11 minutes               8888/tcp                                                                                         hom7-influx-tick_chronograf_1
79c023fc4e84        sipcapture/webapp                  "/docker-entrypoint.â¦"   11 minutes ago      Up 11 minutes               80/tcp                                                                                           homer-webapp
385abc1d47a4        sipcapture/heplify-server:master   "./heplify-server"       11 minutes ago      Up 11 minutes               0.0.0.0:9060->9060/tcp, 0.0.0.0:9060->9060/udp, 9090/tcp                                         heplify-server
b27abc905e37        kapacitor:1.5-alpine               "/entrypoint.sh kapaâ¦"   11 minutes ago      Up 11 minutes               9092/tcp                                                                                         hom7-influx-tick_kapacitor_1
d70d4a2e4fb3        alpine:latest                      "/bin/sh -c 'apk addâ¦"   11 minutes ago      Exited (0) 11 minutes ago                                                                                                    hom7-influx-tick_provisioning_1
abf45488e650        postgres:11-alpine                 "docker-entrypoint.sâ¦"   12 minutes ago      Up 11 minutes (healthy)     5432/tcp                                                                                         hom7-influx-tick_db_1
d3632e63b23b        stefanprodan/caddy                 "/sbin/tini -- caddyâ¦"   12 minutes ago      Up 11 minutes               0.0.0.0:3000->3000/tcp, 0.0.0.0:9080->9080/tcp, 0.0.0.0:9090->9090/tcp, 0.0.0.0:9093->9093/tcp   caddy
418ff8699115        influxdb:1.5-alpine                "/entrypoint.sh inflâ¦"   12 minutes ago      Up 11 minutes               8086/tcp                                                                                         hom7-influx-tick_influxdb_1

root@homer:~/homer7-docker-master/heplify-server/hom7-influx-tick# docker logs 4d4924b19116

> hep-pubsub-hello@1.0.0 start /app
> nodejs helloworld.js

sh: nodejs: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! hep-pubsub-hello@1.0.0 start: `nodejs helloworld.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the hep-pubsub-hello@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-16T16_51_42_636Z-debug.log
root@homer:~/homer7-docker-master/heplify-server/hom7-influx-tick# cat /var/snap/docker/common/var-lib-docker/overlay2/c6b9a71f2e66a8f87cb0ed8f33cd56cb3bc628bc4e2b58fa7b1c6a6ec101ff6b/diff/root/.npm/_logs/2020-12-16T16_51_42_636Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.4.1
3 info using node@v8.16.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle hep-pubsub-hello@1.0.0~prestart: hep-pubsub-hello@1.0.0
6 info lifecycle hep-pubsub-hello@1.0.0~start: hep-pubsub-hello@1.0.0
7 verbose lifecycle hep-pubsub-hello@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle hep-pubsub-hello@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle hep-pubsub-hello@1.0.0~start: CWD: /app
10 silly lifecycle hep-pubsub-hello@1.0.0~start: Args: [ '-c', 'nodejs helloworld.js' ]
11 info lifecycle hep-pubsub-hello@1.0.0~start: Failed to exec start script
12 verbose stack Error: hep-pubsub-hello@1.0.0 start: `nodejs helloworld.js`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:915:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid hep-pubsub-hello@1.0.0
14 verbose cwd /app
15 verbose Linux 5.4.0-58-generic
16 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
17 verbose node v8.16.0
18 verbose npm  v6.4.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error hep-pubsub-hello@1.0.0 start: `nodejs helloworld.js`
23 error spawn ENOENT
24 error Failed at the hep-pubsub-hello@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

A little out of my league here so hoping someone can point me in the correct direction.  My google foo is failing me.  I have managed to get some of the other docker stacks running and collecting data but this is one that I would like to try out for monitoring several FreePBX installs and a openSips install.
TIA
John

**Comment by lmangani** [comment]
Hi John,

Thanks for sharing this. Indeed the hepsub container needs to be updated - since its non-vital, I removed it from the default stack, so if you pull the docker-compose file and run again, the error should disappear. Once its all up, just point your HEPv3 agents at the container on port 9060/UDP

If you have further issue, feel free to comment here.

**Comment by jmillican61** [comment]
Thank you very much for such a fast response!  
1 minor change I had to make to the docker-compose.yml file:
Where you had several comments that were not indented properly in the curl command under InfluxDB Retention Policy push.  The comments were at the far left and needed to be indented in line with the curl commands.
And now all containers are running. I have no dashboards in chronograf though but looking to see if I can figure that out.

**Comment by lmangani** [comment]
Great! Feel free to submit a PR with the adjustments or post them here if you think they are of general benefit.
FYI: We don't currently have default dashboards for Chronograf as it doesn't allow presets as easily as grafana and we are on 1.8
