### ISSUE TITLE
Docker installation script for homer fails in centos 7 .

### ISSUE THREAD

**Issue by sasmita11** [sipcapture/homer#435]
I am installing homer on centos 7 machine . 

while setting up docker with infulxDB I am facing below issue  . 

 hom7-influx-tick]# docker-compose up -d
ERROR: yaml.parser.ParserError: while parsing a block collection
  in "./docker-compose.yml", line 136, column 7
expected <block end>, but found '<scalar>'
  in "./docker-compose.yml", line 154, column 9

Then I  have installed Homer through docker successfully with prometheus . 
I have attached the output of docker ps command . 

I have allowed 9080/tcp traffic from everywhere for the server  . 

When I am hitting http://public_ip:9080 on my browser the output is 

**This site can't be reachable .** 

[homer-docker-ps-output.txt](https://github.com/sipcapture/homer/files/5713889/homer-docker-ps-output.txt)

What should I do next ? Please help me .

**Comment by sasmita11** [comment]
After some refresh the page was loaded . 

But now I am not able to login through the credentials . 
admin/sipcapture

![homer-login-error](https://user-images.githubusercontent.com/18418391/102592742-e96b5980-4139-11eb-88e4-05f1ad48e7ad.PNG)

Please look into the image and help me how to solve this .

**Comment by adubovikov** [comment]
i can only tell you that homer-app server is not up. Need to check this.

**Comment by lmangani** [comment]
@sasmita11 I cannot reproduce any such issue - could you please pull the latest docker-compose and try restart the service, attaching the new logs.

**Comment by sasmita11** [comment]
How Can I do that ? Can you please share the command with me what to do . I have simply followed the video tutorial for the commands . 

[ hom7-prom-all]# docker-compose --version
docker-compose version 1.27.4, build 40524192
[ hom7-prom-all]# docker --version
Docker version 20.10.1, build 831ebea

This is my docker-compose and docker version . Do you need me to change this .

**Comment by lmangani** [comment]
Start with the following commands: 
```
git pull
docker-compose pull
```

**Comment by sasmita11** [comment]
Now its running with influxdb also . But I did some changes in the yml file . the web-app and caddy both are configure with same port . I changed that .. Then everything works perfectly .
