### ISSUE TITLE
No graph data analysis shown in Homer 7.9.10 (prod)

### ISSUE THREAD

**Issue by yazarlwin** [sipcapture/homer#438]
We installed homer 7.9.10 (prod) successfully. We saw the captured messages when searched. But we can't have graph display of the traffic data. Please help us as we are planning to put this in production soon.

**Comment by adubovikov** [comment]
can you provide a bit more information what are you trying to display and how ?

**Comment by yazarlwin** [comment]
We would like to see like below dashboard. 
![Dashboard](https://user-images.githubusercontent.com/45550549/103209894-8eecad00-4932-11eb-9d33-2068333f1fc1.png)

**Comment by lmangani** [comment]
@yazarlwin this very much depends on your setup. If you chose to use influxDB you can do so but we provide no presets. Our suggestion is to do the charting in Grafana using the HOMER generated data, and then embed widgets in the Homer UI.

**Comment by yazarlwin** [comment]
We configured Grafana as per the credential and data from /usr/local/homer/etc/webapp_config.json, but the problem is that we can't see homer data in influxDB.
