### ISSUE TITLE
Packets Not Showing on GUI 

### ISSUE THREAD

**Issue by imdrpn** [sipcapture/homer#439]
Hello , I am not getting data on  web interface ,here is all the details 
------------------------------------------------------------------------------------------------------------------------------------
homer-app -version
VERSION: 1.3.13                                                              

heplify-server --version
VERSION: heplify-server 1.32
----------------------------------------------------------------------------------------------------------------------------------
Installed applications through installer script 
-----------------------------------------------------------------------------------------------------------------------------------
Sending SIP packets to homer server through Captagent Which is configured with PBX server
------------------------------------------------------------------------------------------------------------------------------------
Here , captagent sending packets already to  server which is inspected by doing ngrep on port 9060 on HOMER server & getting logs in syslog  .

MAINLY I AM GETTING THIS PROBLEM AFTER REBOOTING OF HOMER SERVER .

**Comment by aqsyonas** [comment]
Hey,

could you please check if
1. Data is being saved into database
2.  Try to turn on debug in homer-app inside
/usr/local/homer/etc/webapp_config.json and watch /usr/local/homer/log/
directory for logs.

I hope you find useful hints from the above instructions.

Br, Aqs

**Comment by imdrpn** [comment]
Hi , 
1. No Data is not saved to into database 
2.  tail -f  /usr/local/homer/log/homer-app.log.2021_01_11_00_00
{"level":"error","msg":"couldn't make ping to [Host: localhost]: \ndriver: bad connection","time":"2021-01-11T08:15:46Z"}
{"level":"error","msg":"couldn't make ping to [Host: 127.0.0.1]: \ndriver: bad connection","time":"2021-01-11T08:15:46Z"}
{"level":"error","msg":"couldn't make ping to [Host: localhost]: \ndriver: bad connection","time":"2021-01-11T08:19:46Z"}
{"level":"error","msg":"couldn't make ping to [Host: 127.0.0.1]: \ndriver: bad connection","time":"2021-01-11T08:19:46Z"}
{"level":"error","msg":"dial tcp 127.0.0.1:5432: connect: connection refused","time":"2021-01-11T09:16:08Z"}

**Comment by adubovikov** [comment]
Looks like your postgress is down. Please recheck.

**Comment by imdrpn** [comment]
@adubovikov  Service is running, and i am getting less frequently these type of logs, nothing is printed apart of the same

**Comment by adubovikov** [comment]
please open heplify-server.service:

```
[Unit]
Description=HEP Server & Switch in Go 
#Only if you have postgresql on the same host!
After=network.target postgresql.service

```

you should have After=network.target postgresql.service

save it, do systemd daemon-reload and try again

**Comment by imdrpn** [comment]
I have tried after  Editing  service file as you suggested & restart the service , but still not getting anything

**Comment by adubovikov** [comment]
did you restart all services ? If you did it correct, you shouldn't see any errors like above.

**Comment by adubovikov** [comment]
also, please check if you are sending any traffic to port 9060 there your heplify-server is running.

**Comment by imdrpn** [comment]
Yes I have restarted all services, not getting above errors &  by doing ngrep on port 9060 i can conclude that traffic is coming .

**Comment by adubovikov** [comment]
in this case check if you heplify-server sends something to port 5432

**Comment by imdrpn** [comment]
127.0.0.1:60978 -> 127.0.0.1:5432 [AP]
  d....OWE5YzQ2NGVjZTU3ODRhNGYwMmQ5OGI4Y2RkMDI5ZjE..2021-01-11T12:52:27.233831Z.{"protocolFamily":2,"protocol":6,"srcIp":"xy.xx.yy.zz","dst
  Ip":"1xx.1yy.2z.2y2","srcPort":5060,"dstPort":37922,"timeSeconds":1610369547,"timeUseconds":233831,"payloadType":1,"captureId":"2001","cap
  turePass":"myhep","correlation_id":"OWE5YzQ2NGVjZTU3ODRhNGYwMmQ5OGI4Y2RkMDI5ZjE."}.{"ruri_user":"","ruri_domain":"","from_user":"201","fro
  m_tag":"a3c3690b","to_user":"201","callid":"OWE5YzQ2NGVjZTU3ODRhNGYwMmQ5OGI4Y2RkMDI5ZjE.","cseq":"99 PUBLISH","method":"200","user_agent":
  "FreeSWITCH"}.SIP/2.0 200 OK\r\nVia: SIP/2.0/TCP 192.168.1.208:44901;branch=z9hG4bK-d8754z-05872a052305bfe1-1---d8754z-;received=103.106.2
  0.217;rport=37922\r\nFrom: <sip:201@xy.xx.yy.zz;transport=TCP>;tag=a3c3690b\r\nTo: <sip:201@xy.xx.yy.zz;transport=TCP>;tag=rU0K5m7UBKKma
  \r\nCall-ID: OWE5YzQ2NGVjZTU3ODRhNGYwMmQ5OGI4Y2RkMDI5ZjE.\r\nCSeq: 99 PUBLISH\r\nCont

**_yes its sending data to port 5432_**

**Comment by adubovikov** [comment]
perfect, check now if you have correct time range in the UI

**Comment by imdrpn** [comment]
Yes , time range is correct UTC ,but no data Showing .

**Comment by adubovikov** [comment]
restart homer-app as well and add same lines (After:" to the
homer-app.service and check

**Comment by imdrpn** [comment]
@adubovikov  its works ! Thanks alot , still i will do various testing and close this issue accordingly .

**Comment by adubovikov** [comment]
you are welcome, don't forget to star us:

https://github.com/sipcapture/homer/stargazers

**Comment by imdrpn** [comment]
@adubovikov  ,done :)

**Comment by adubovikov** [comment]
@imdrpn as well: https://github.com/sipcapture/homer-app/commit/375045c7c477c77d1403153f799f3f7c8864dbf0

**Comment by imdrpn** [comment]
@adubovikov  Done :+1:

**Comment by adubovikov** [comment]
ok. I am closing the ticket! Enjoy!
