### ISSUE TITLE
partrotate_unixtimestamp.pl doesn't create first partition?

### ISSUE THREAD

**Issue by apogrebennyk** [sipcapture/homer#44]
I'm using version 0.3.3 partrotate_unixtimestamp.pl on CentOS.
I've noticed that the script doesn't work for the first time (there is partition being created other than pmax).
I've traced it down to the condition if($#partsadd > 0). The value is zero when there's only one element in the array. I've thought that we have an "offset by 1" issue and patched is as follows:

@@ -151,7 +151,8 @@ for(my $i=0; $i<$newparts; $i++) {
     }    
 }
  
-if($#partsadd > 0)
+my $parts_count=scalar @partsadd;
+if($parts_count > 0)
 {
     # Fix MAXVALUE. Thanks Dorn B. <djbinter@gmail.com> for report and fix.
     $query = "ALTER TABLE ".$mysql_table." REORGANIZE PARTITION pmax INTO (".join(',', @partsadd)

 The partition was created after I modified the script in this way.
The difference between $# notation and "scalar" is best illustrated by the following code snippet:
# perl
my @array = (1);
$size = @array;
$max_index = $#array;

print "Size:  $size\n";
print "Max Index: $max_index\n";

Size:  1
Max Index: 0

Please check if the patch is correct and apply it. I noticed there are some other places in the script using the $# notation, don't know if that's an issue though.

**Comment by adubovikov** [comment]
thank you. Can you please do pull request ?

**Comment by adubovikov** [comment]
thank you! Fixed
https://github.com/sipcapture/homer/commit/825a61c1800733b6c27abd3643630b4b1b488fb2
