### ISSUE TITLE
Postgres Database is full

### ISSUE THREAD

**Issue by vishalmpai** [sipcapture/homer#441]
I have homer setup and default DBDropDays = 14 now concern is my disk space is full as i checked it's /var/lib/postgresql. What is the best way to tackle this.

**Comment by lmangani** [comment]
Reduce the rotation days, enable `DBDropOnStart` and restart the service. It should free up the disk space accordingly.

**Comment by vishalmpai** [comment]
DBDropDays = 1
DBDropOnStart = true

I updated heplify-server.toml file but still it not cleaning up.

**Comment by lmangani** [comment]
We can't help you much unless you attach some logs or output.

**Comment by vishalmpai** [comment]
HEPAddr               = "0.0.0.0:9060"
HEPTCPAddr            = ""
HEPTLSAddr            = "0.0.0.0:9060"
ESAddr                = ""
ESDiscovery           = true
LokiURL               = ""
LokiBulk              = 200
LokiTimer             = 4
LokiBuffer            = 100000
LokiHEPFilter         = [1,5,100]
ForceHEPPayload	      = []
PromAddr        = "0.0.0.0:9096"
PromTargetIP          = ""
PromTargetName        = ""
DBShema               = "homer7"
DBDriver              = "postgres"
DBAddr                = "localhost:5432"
DBUser          = "homer_user"
DBPass          = "NDCBh2U68jlo3a0jSSJOG6YiB0"
DBDataTable           = "homer_data"
DBConfTable           = "homer_config"
DBBulk                = 200
DBTimer               = 4
DBBuffer              = 400000
DBWorker              = 8
#DBRotate              = true
#DBPartLog             = "2h"
#DBPartSip             = "1h"
#DBPartQos             = "6h"
#DBDropDays            = 1
DBDropDaysCall        = 0
DBDropDaysRegister    = 0
DBDropDaysDefault     = 0
#DBDropOnStart         = true
DBRotate = true
DBPartLog = "30m"
DBPartSip = "30m"
DBPartQos = "30m"
DBDropDays = 1
DBDropOnStart = true
Dedup                 = false
DiscardMethod         = []
AlegIDs               = []
CustomHeader          = []
SIPHeader             = []
LogDbg                = ""
LogLvl                = "warning"
LogStd                = false
LogSys                = true
Config                = "./heplify-server.toml"
ConfigHTTPAddr        = ""


Also please let me know which sort of log you needed will share here.

Thanks

**Comment by vishalmpai** [comment]
homer01 /usr/local/bin/heplify-server[3132]: logp.go:142: [log] Disable stderr logging
  homer01 /usr/local/bin/heplify-server[3132]: server.go:83: start heplify-server 1.32 with config.HeplifyServer{HEPAddr:"0.0.0.0:9060", HEPTCPAddr:"", HEPTLS
  homer01 /usr/local/bin/heplify-server[3132]: prometheus.go:38: expose metrics without or unbalanced targets
  homer01 /usr/local/bin/heplify-server[3132]: rotator.go:344: start creating tables (2021-02-02 13:44:44.044411746 +0000 UTC m=+0.015226718)
  homer01 /usr/local/bin/heplify-server[3132]: rotator.go:349: dial tcp 127.0.0.1:5432: connect: connection refused
  homer01 /usr/local/bin/heplify-server[3132]: rotator.go:352: dial tcp 127.0.0.1:5432: connect: connection refused
  homer01 /usr/local/bin/heplify-server[3132]: rotator.go:355: dial tcp 127.0.0.1:5432: connect: connection refused
  homer01 /usr/local/bin/heplify-server[3132]: rotator.go:357: end creating tables (2021-02-02 13:44:44.065881179 +0000 UTC m=+0.036696158)
  homer01 /usr/local/bin/heplify-server[3132]: rotator.go:360: dial tcp 127.0.0.1:5432: connect: connection refused
  homer01 /usr/local/bin/heplify-server[3132]: server.go:138: dial tcp 127.0.0.1:5432: connect: connection refused

**Comment by vishalmpai** [comment]
As i debug i found that due to full disk space the postgressql service is getting up. So can anyone help me out.

**Comment by vishalmpai** [comment]
I managed it to fix it at my side by deleting the unwanted logs and make postgresql service up and later on as suggested by @lmangani added the parameter and restarted the service.

Thank you @lmangani
