### ISSUE TITLE
Cannot extend columns in search results

### ISSUE THREAD

**Issue by devBash99** [sipcapture/homer#442]
Hello I have an issue regarding the homer web app UI.

Whenever I try to extend the column in the search results it reverts back to the initial size. This is only false for the **Date** column which works fine. I am using **Homer 7 (Docker) Verion 7.9.10.** I also pulled the latest web app image and tested in a separate environment but it was the same there as well. I have attached a gif below
![homer7_column](https://user-images.githubusercontent.com/58656223/106955716-6f2d7d80-6757-11eb-8652-38f745dc61e0.gif)

**Comment by AlexeyOplachko** [comment]
Addressed in https://github.com/sipcapture/homer-ui/pull/386/commits/3f533a1328946b2a4c59f3a34be138bbc96f4fee, after we do testing and merge in Master, behavior for this will become a setting. 
Default will remain same as right now, but you'll be able to disable "size to fit"(current behavior) or to enable "Auto-sizing" which enlarges columns so their content fits inside without being cut of

**Comment by devBash99** [comment]
Thank you. Let me test this and get back to you.

**Comment by devBash99** [comment]
I tested it and it works. But after refreshing the page the setting go back to default.

**Comment by lmangani** [comment]
Closing as no longer reproducible. Please reopen if this is still an issue.
