### ISSUE TITLE
If I use sngrep to capture and push packets to Heplify Server, how to set the capture ID?

### ISSUE THREAD

**Issue by Dup4** [sipcapture/homer#444]
- <https://github.com/sipcapture/homer/wiki/Examples:-sngrep>
- <https://github.com/irontec/sngrep/wiki#how-to-use>

The two documents listed above did not mention how to set capture ID.

I want to know if sngrep supports setting the capture ID when pushing packets.

**Comment by lmangani** [comment]
Sounds like a question for `sngrep`? ;) any reason not to use `heplify` or one of our agents?
