### ISSUE TITLE
homer installs and receives data but isnt populating DB

### ISSUE THREAD

**Issue by thesipguy** [sipcapture/homer#445]
Hi Lorenzo, I installed Homer on Debian 9 via the script, it installs and I can log in to the portal, I can see it listening to port 9060 and I can see traffic coming from the OpenSips server, but when I try to search in homer it doesnt find any info.

I guess I'm missing a step in the installation but cant figure out what.

thank you
Scott

**Comment by lmangani** [comment]
Please confirm the status of the core services and/or any related events from syslog when restarting them:
- heplify-server
- postgresql-12

**Comment by thesipguy** [comment]
I see this

Feb 10 14:44:44 HomerCapture heplify-server[743]: 2021/02/10 14:44:44.385283 rotator.go:349: ERR dial tcp 127.0.0.1:5432: connect: connection refused
Feb 10 14:44:44 HomerCapture systemd[1]: Starting LSB: Start NTP daemon...
Feb 10 14:44:44 HomerCapture heplify-server[743]: 2021/02/10 14:44:44.409058 rotator.go:352: ERR dial tcp 127.0.0.1:5432: connect: connection refused
Feb 10 14:44:44 HomerCapture homer-app[749]: {"level":"error","msg":"dial tcp 127.0.0.1:5432: connect: connection refused","time":"2021-02-10T14:44:44Z"}
Feb 10 14:44:44 HomerCapture homer-app[749]: panic: failed to connect database

**Comment by lmangani** [comment]
There's the answer - postgres is down. You need to check the status of the service and figure out why its not starting.
```
systemctl restart postgres-12
systemctl status postgres-12
```

**Comment by thesipguy** [comment]
I formated my server and reinstalled from the script, an now I dont get those errors anymore, here is the logs I get now

Feb 10 15:23:55 HomerCapture /usr/local/bin/heplify-server[12379]: server.go:83: start heplify-server 1.32 with config.HeplifyServer{HEPAddr:"0.0.0.0:9060", HEPTCPAddr:"", HEPTLSAddr:"0.0.0.0:9060", ESAddr:"", ESDiscovery:true, ESUser:"", ESPass:"", LokiURL:"", LokiBulk:200, LokiTimer:4, LokiBuffer:100000, LokiHEPFilter:[]int{1, 5, 100}, ForceHEPPayload:[]int{}, PromAddr:"0.0.0.0:9096", PromTargetIP:"", PromTargetName:"", DBShema:"homer7", DBDriver:"postgres", DBAddr:"localhost:5432", DBUser:"homer_user", DBPass:"VVD24HoTYSoOHhpuPaqwxpagoQ", DBDataTable:"homer_data", DBConfTable:"homer_config", DBBulk:200, DBTimer:4, DBBuffer:400000, DBWorker:8, DBRotate:true, DBPartLog:"2h", DBPartIsup:"6h", DBPartSip:"1h", DBPartQos:"6h", DBDropDays:14, DBDropDaysCall:0, DBDropDaysRegister:0, DBDropDaysDefault:0, DBDropOnStart:false, Dedup:false, DiscardMethod:[]string{}, AlegIDs:[]string{}, CustomHeader:[]string{}, SIPHeader:[]string{}, LogDbg:"", LogLvl:"info", LogStd:false, LogSys:true, Config:"/etc/heplify-server.toml", ConfigHTTPAddr:"", ConfigHTTPPW:"", Version:false}
Feb 10 15:23:55 HomerCapture /usr/local/bin/heplify-server[12379]: prometheus.go:38: expose metrics without or unbalanced targets
Feb 10 15:23:55 HomerCapture /usr/local/bin/heplify-server[12379]: rotator.go:344: start creating tables (2021-02-10 15:23:55.219018093 +0000 UTC m=+0.010245735)
Feb 10 15:23:55 HomerCapture /usr/local/bin/heplify-server[12379]: rotator.go:357: end creating tables (2021-02-10 15:23:55.910204411 +0000 UTC m=+0.701432060)
Feb 10 15:23:55 HomerCapture /usr/local/bin/heplify-server[12379]: postgres.go:61: postgres connection established

**Comment by lmangani** [comment]
@thesipguy alright that's great - normally its best to troubleshoot why things happen before a nuke or next time you might loop back here ;)

**Comment by thesipguy** [comment]
NO, its still not working, before I messed around when it didnt work, I guess that broke something else, but now with a fresh installation its still not working

**Comment by thesipguy** [comment]
Maybe my opensips config is wrong, here are the relevant settings, I just changed the ip's for security reasons
listen = hep_udp:188.118.x.xxx:6061
modparam("siptrace", "trace_on", 1)
modparam("proto_hep", "hep_id","[hid]138.197.xxx.xxx:9060;transport=udp; version=3")
modparam("siptrace", "trace_id","[tid1]uri=hep:hid")
modparam("proto_hep", "hep_capture_id", 1)
I tried added the following line but it didnt work either
modparam("proto_hep", "homer5_on", 0)

in my route I set
sip_trace("tid1");

**Comment by thesipguy** [comment]
When I changed homer5_on to 0, it puts this in the log

Feb 10 16:01:22 HomerCapture /usr/local/bin/heplify-server[23415]: decoder.go:130: ParseMsg: err parsing msg no SIP eof found#012"{\n\t\"payload\":\t\"SIP/2.0 200 Server Running\\r\\nVia: SIP/2.0/UDP localhost:5065;received=127.0.0.1;rport=5065;branch=z9hG4bK495819\\r\\nFrom: <sip:keepalived@sip.xxxx.com>;tag=33180\\r\\nTo: <sip:keepalived@sip.xxxx.com>;tag=a49a-40fff2a70edb9d5798a102c3b12aad58\\r\\nCall-ID: 002d46bda104d916b199e07e62882775@localhost\\r\\nCSeq: 20 NOTIFY\\r\\nServer: OpenSIPS (2.4.9 (x86_64/linux))\\r\\nContent-Length: 0\\r\\n\\r\\n\"\n}"#012nodeID: 1, protoType: 1, version: 2, protocol: 17, length: 408, flow: 188.118.xxx.xxx:5060->127.0.0.1:5065

**Comment by lmangani** [comment]
@thesipguy whats the OpenSIPS version?

**Comment by thesipguy** [comment]
2.4.9

**Comment by lmangani** [comment]
That's pretty old, but also a testament to OpenSIPS stability, I have no 2.4 setups to test/replicate with but I'll take a look. Anyway the error you're getting is more about the signaling than HEP and the payload seems to be malformed.

**Comment by thesipguy** [comment]
Its only 3 months old. its a LTS version

**Comment by lmangani** [comment]
@thesipguy that's intended from a #HEP perspective, not overall of course. We're focused on that.

**Comment by lmangani** [comment]
Closing for no updates. Please reopen if this is still an issue.
