### ISSUE TITLE
Failed to create a new dashboard.

### ISSUE THREAD

**Issue by lcalderonboix** [sipcapture/homer#446]
Hi experts,

I've installed homer 7 over Debian. When I access by web Now it appears me the following error "Failed to create a new dashboard" and no data is showed. It worked properly for a few days.

What can I check?.

Thanks.

Regards.

**Comment by lmangani** [comment]
Hi @lcalderonboix 
In order to get assistance please specify:

- status of db service
- the version of the application you are running
- any console log or syslog errors form the system.

**Comment by lmangani** [comment]
AFTER you collect the console.log errors, you can try from the UI `settings > reset > clear local data`  and see if that helps reset the dashboard.

**Comment by lcalderonboix** [comment]
Hi Imangani!

The version is 7.9.10.
I've check all syslog and  I've not seen anything abnormal.
Then I clear local data from the UI but the problem still persists.

These are all the services runnning:

homer
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Fri 2021-02-19 10:47:46 CET; 3 days ago
   CGroup: /
           ├─docker
           │ ├─ed14b73786cd3fbc472a3f883d6ebf190a86ed7ba2e03ca27ffc92970abf8266
           │ │ └─12241 /bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles --storage.tsdb
           │ ├─718e915adc297bd9bf9195caab075cfda2d7ed916ea08e97da84f588a895f173
           │ │ └─12589 /bin/alertmanager --config.file=/etc/alertmanager/config.yml --storage.path=/alertmanager
           │ ├─651df8da72a037c9d866b2ff93eac527f69e44d8640d2ce02e6dd6a5b6a193c6
           │ │ └─12596 /bin/node_exporter --path.procfs=/host/proc --path.sysfs=/host/sys --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)
           │ ├─7c783f84dcd3f01d4e26a744fdab42069d5445b714f0f7001423f2c3a0c594a8
           │ │ ├─12494 postgres
           │ │ ├─12876 postgres: checkpointer
           │ │ ├─12877 postgres: background writer
           │ │ ├─12878 postgres: walwriter
           │ │ ├─12879 postgres: autovacuum launcher
           │ │ ├─12880 postgres: stats collector
           │ │ ├─12883 postgres: logical replication launcher
           │ │ ├─13528 postgres: root homer_data 172.17.0.8(52906) idle
           │ │ ├─13967 postgres: root homer_data 172.17.0.8(52922) idle
           │ │ ├─13968 postgres: root homer_data 172.17.0.8(52924) idle
           │ │ ├─13969 postgres: root homer_data 172.17.0.8(52926) idle
           │ │ ├─20240 postgres: autovacuum worker   homer_data
           │ │ ├─20537 runc init
           │ │ ├─21705 postgres: root homer_data 172.17.0.9(48064) idle
           │ │ ├─23326 postgres: root homer_config 172.17.0.9(37956) idle
           │ │ ├─23327 postgres: root homer_config 172.17.0.9(37958) idle
           │ │ └─23329 postgres: root homer_config 172.17.0.9(37960) idle
           │ ├─ce8192aa376319393e603641621d70037ab683aae0e94b7cfbd19e02d580057f
           │ │ └─12864 ./heplify-server
           │ ├─4f7babc78abbee099b4551fd41d77782d5e4c8d9ddbfd86c435b8b5662f7f953
           │ │ └─13164 /homer-app -webapp-config-path=/usr/local/homer/etc
           │ ├─8583cb2a3e8739e4e2433f95e1211741d2f423d0214ec195f5847c3478a6cac9
           │ │ └─12234 /usr/bin/loki -config.file=/etc/loki/local-config.yaml
           │ └─565ac59bdca817b45c38be7a64f6b25b7f1e2ce461eddb464814554ee129624b
           │   └─12221 grafana-server --homepath=/usr/share/grafana --config=/etc/grafana/grafana.ini --packaging=docker cfg:default.log.mode=console cfg:default.paths.data=/var/lib/grafana cfg:default.paths.logs=/var/log/grafana cfg:def
           ├─user.slice
           │ └─user-1000.slice
           │   ├─session-78.scope
           │   │ ├─20543 systemctl status
           │   │ ├─20544 pager
           │   │ ├─25470 sshd: homer [priv]
           │   │ ├─26439 sshd: homer@pts/0
           │   │ ├─26445 -bash
           │   │ ├─26717 su
           │   │ └─26917 bash
           │   └─user@1000.service
           │     └─init.scope
           │       ├─26417 /lib/systemd/systemd --user
           │       └─26419 (sd-pam)
           ├─init.scope
           │ └─1 /sbin/init
           └─system.slice
             ├─containerd.service
             │ ├─  525 /usr/bin/containerd
             │ ├─12176 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/565ac59bdca817b45c38be7a64f6b25b7f1e2ce461eddb464814554ee129624b -address /run/containerd/containerd.sock -containerd
             │ ├─12193 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/8583cb2a3e8739e4e2433f95e1211741d2f423d0214ec195f5847c3478a6cac9 -address /run/containerd/containerd.sock -containerd
             │ ├─12197 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/ed14b73786cd3fbc472a3f883d6ebf190a86ed7ba2e03ca27ffc92970abf8266 -address /run/containerd/containerd.sock -containerd
             │ ├─12463 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/7c783f84dcd3f01d4e26a744fdab42069d5445b714f0f7001423f2c3a0c594a8 -address /run/containerd/containerd.sock -containerd
             │ ├─12543 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/718e915adc297bd9bf9195caab075cfda2d7ed916ea08e97da84f588a895f173 -address /run/containerd/containerd.sock -containerd
             │ ├─12557 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/651df8da72a037c9d866b2ff93eac527f69e44d8640d2ce02e6dd6a5b6a193c6 -address /run/containerd/containerd.sock -containerd
             │ ├─12845 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/ce8192aa376319393e603641621d70037ab683aae0e94b7cfbd19e02d580057f -address /run/containerd/containerd.sock -containerd
             │ ├─13135 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/4f7babc78abbee099b4551fd41d77782d5e4c8d9ddbfd86c435b8b5662f7f953 -address /run/containerd/containerd.sock -containerd
             │ └─20529 runc --root /var/run/docker/runtime-runc/moby --log /run/containerd/io.containerd.runtime.v1.linux/moby/7c783f84dcd3f01d4e26a744fdab42069d5445b714f0f7001423f2c3a0c594a8/log.json --log-format json exec --process /tm
             ├─systemd-timesyncd.service
             │ └─469 /lib/systemd/systemd-timesyncd
             ├─dbus.service
             │ └─509 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
             ├─docker.service
             │ ├─12143 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 3000 -container-ip 172.17.0.2 -container-port 3000
             │ ├─12168 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 3100 -container-ip 172.17.0.3 -container-port 3100
             │ ├─12823 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 9060 -container-ip 172.17.0.8 -container-port 9060
             │ ├─12838 /usr/bin/docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 9060 -container-ip 172.17.0.8 -container-port 9060
             │ ├─13126 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 9080 -container-ip 172.17.0.9 -container-port 80
             │ └─26468 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
             ├─ssh.service
             │ └─520 /usr/sbin/sshd -D
             ├─system-getty.slice
             │ └─getty@tty1.service
             │   └─517 /sbin/agetty --noclear tty1 linux
             ├─systemd-logind.service
             │ └─512 /lib/systemd/systemd-logind
             ├─cron.service
             │ └─514 /usr/sbin/cron -f
             ├─systemd-udevd.service
             │ └─288 /lib/systemd/systemd-udevd
             ├─rsyslog.service
             │ └─516 /usr/sbin/rsyslogd -n
             └─systemd-journald.service
               └─273 /lib/systemd/systemd-journald

**Comment by lcalderonboix** [comment]
Now I rebooted the machine and now It apperarsme the following error:

loki is up-to-date
prometheus is up-to-date
grafana is up-to-date
nodeexporter is up-to-date
alertmanager is up-to-date
db is up-to-date
heplify-server is up-to-date

ERROR: for homer-webapp  Container "565ac59bdca8" is unhealthy.
ERROR: Encountered errors while bringing up the project.

**Comment by lcalderonboix** [comment]
New Update. It failed because there was not free space on disk.

Is there a way to select the info to save in data base? For instance I dont need to save RTCP messages.

Regards.

**Comment by lmangani** [comment]
@lcalderonboix in this case you should disable RTCP at the HEP senders rather than write and drop the data perhaps?

**Comment by lcalderonboix** [comment]
Done it. Thank you Lorenzo.
