### ISSUE TITLE
 Export Flow as PNG With Aliases and Grouping

### ISSUE THREAD

**Issue by YisroelTech** [sipcapture/homer#450]
When doing an Export Flow as PNG it would be extremely useful to have it display the same way the Flow tab displays it, including the Alias names and the grouping (if set to Group by Alias.)

See compared Flow tab (left) and Exported Flow (right):
![image](https://user-images.githubusercontent.com/7387839/109696012-97dc4380-7b5a-11eb-90b0-c4320b139afc.png)

**Comment by adubovikov** [comment]
It has been implemented. Please test the latest homer-app 1.4.13 package and UI 7.10.3
