### ISSUE TITLE
Feature - Calls grouped by Call-ID

### ISSUE THREAD

**Issue by iliesh** [sipcapture/homer#452]
Hello,

The Display Result widget by default is showing all calls with all messages, is there any way to add an option to group them by callid for ex?
And by pressing on that specific callid to open a new window containing the full call flow for that particular callid.

Thank you.
Regards,

**Comment by lmangani** [comment]
I'm not understanding the point. This is how it already works, if you are talking about search results, they sorted by time but you can also sort them by callid, etc. when they have no parameters they will show everything. Use parameters to limit results.

Also, Inside each session popup, you can filter the sessions-ids and protocols being displayed
![image](https://user-images.githubusercontent.com/1423657/110790771-bf758f00-8271-11eb-8237-f7a052189fde.png)

**Comment by iliesh** [comment]
@lmangani ,

Yes, the search result is what I meant. I know you can sort each column as you wish, which is great - but what I want is to GROUP the result based on some parameters (callid for ex.). This way the result page will be much shorter and we will have a single call per line instead of a transaction, and if want to see the full call flow - just press on that particular call and you will see all transactions. (which is already implemented).

For ex, from the result below:

![image](https://user-images.githubusercontent.com/14953151/110795558-e2eb0a80-826e-11eb-9488-ac9e0a2fa341.png)

will be nice to have just 2 lines (results) - one for callid 03efc95178fef0565a1788d409ea854f and another one: 217321472cbfafc5578c2f8701dd5c13
