### ISSUE TITLE
@lmangani , Calls grouped by Call-ID

### ISSUE THREAD

**Issue by iliesh** [sipcapture/homer#453]
@lmangani ,

Yes, the search result is what I meant. I know you can sort each column as you wish, which is great - but what I want is to GROUP the result based on some parameters (callid for ex.). This way the result page will be much shorter and we will have a single call per line instead of a transaction, and if want to see the full call flow - just press on that particular call and you will see all transactions. (which is already implemented).

For ex, from the result below:

![image](https://user-images.githubusercontent.com/14953151/110795558-e2eb0a80-826e-11eb-9488-ac9e0a2fa341.png)

will be nice to have just 2 lines (results) - one for callid 03efc95178fef0565a1788d409ea854f and another one: 217321472cbfafc5578c2f8701dd5c13

_Originally posted by @iliesh in https://github.com/sipcapture/homer/issues/452#issuecomment-796743463_

**Comment by lmangani** [comment]
Just filter by SIP Method = INVITE and it' ll basically do what you' re saying?

**Comment by iliesh** [comment]
@lmangani, it's a kind of workaround - instead of having 15-20 lines - there will be just 3-4, or more depending on how many re-invites are in that dialog. I think an option to group the result will make more sense (IMHO).

Thank you.

**Comment by lmangani** [comment]
I know exactly what you're talking about, but there' s no transaction tracking in HOMER (only in HEPIC) to act on the grouping, so this would be a UI gimmick/workaround anyhow. This said, the table can support grouping by columns from a technical standpoint, so feel free to send a PR if you' d like to add it anytime! Thanks!
