### ISSUE TITLE
Homer/HEPIC RTP capture question.

### ISSUE THREAD

**Issue by ghost** [sipcapture/homer#455]
Hello,
From what I understand, in order to capture RTP traffic the 'HEPIC" product must be used and this is not a free product.  I have been unable to locate the price for using HEPIC.  When I am on the HEPIC page, the Contact page does not appear to be working so I am unable to ask this question there.  I would appreciate any information anyone has on this topic.

Thank you,

**Comment by lmangani** [comment]
HOMER does not need HEPIC and vice versa, they compete with each other with different features. Contact sales@qxip.net anytime if you would like more details.
