### ISSUE TITLE
Change homer title

### ISSUE THREAD

**Issue by bmgante** [sipcapture/homer#462]
Hi,
Is it possible to change "(prod)" on browser tab?

![image](https://user-images.githubusercontent.com/27358817/115274607-c5944080-a138-11eb-9b21-f3ad3a7b3ba3.png)

Was checking on index.html but didn´t find any reference to "(prod)", only HOMER title.

Thanks

**Comment by adubovikov** [comment]
Done. Please install homer-app-1.4.0

**Comment by bmgante** [comment]
How was this request addressed? Did you remove “(prod)” from title or is it somehow configurable?

Is there any relevant change/update  to be taken in consideration for webapp config file when migrating from 1.3.2?

Thanks

**Comment by adubovikov** [comment]
removed
