### ISSUE TITLE
Heplify server decoder issue

### ISSUE THREAD

**Issue by devBash99** [sipcapture/homer#464]
Looking at heplify server logs. I found this issue . I have an issue of missing data as well. Can someone help me out here.
Note: I am not using the latest version of heplify server.

decoder.go:132: parseStartLine err: received err while parsing start line: parseStartLineRequest err: request line did not split on LWS correctly "ate>\n</dialog>\n</dialog-info>\nNOTIFY sip:6910@<ip>:44779;transport=TCP SIP/2.0\r\nVia: SIP/2.0/TCP <ip>:5060;branch=z9hG4bK2d66.128c7004.0\r\nVia: SIP/2.0/UDP <ip>;received=<ip>;rport=5060;branch=z9hG4bKFpQ6SaKSK8arB\r\nRecord-Route: <sip:<ip>:5060;r2=on;lr;ftag=1865059521>\r\nRecord-Route: <sip:<ip>:5060;transport=tcp;r2=on;lr;ftag=1865059521>\r\nMax-Forwards: 69\r\nFrom: <sip:park+704@:5060>;tag=IuYgUJs12nN3\r\nTo: \"6910\" <sip:6910@:5060>;tag=1865059521\r\nCall-ID: 0_976215689@\r\nCSeq: 509318809 NOTIFY\r\nContact: <sip:park+704@:5060>\r\nUser-Agent: Squond\r\nAllow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, PRACK, NOTIFY, PUBLISH, SUBSCRIBE\r\nSupported: precondition, 100rel, path, replaces\r\nEvent: dialog\r\nAllow-Events: talk, hold, conference, presence, as-feature-event, dialog, line-seize, call-info, sla, include-session-description, presence.winfo, message-summary, refer\r\nSubscription-State: active;expires=1601\r\nContent-Type: application/dialog-info+xml\r\nContent-Length: 240\r\n\r\n<?xml version=\"1.0\"?>\n<dialog-info xmlns=\"urn:ietf:params:xml:ns:dialog-info\" version=\"14930\" state=\"full\" entity=\"sip:park+704@\">\n<dialog id=\"704\" direction=\"init"

**Comment by adubovikov** [comment]
looks like there is no \r\n but \n\n\n - this looks not RFC compliance and need extend decoder.

**Comment by devBash99** [comment]
I am sorry i'm not much familiar with this and i didn't understand what you meant by extend decoder. If you can guide me on what needs to be done than i can try and work on the code for a solution

**Comment by devBash99** [comment]
Also could this also be due to using quite an older version of capt-agent?

**Comment by kYroL01** [comment]
@devBash99 what Alexandr is saying is refers to this part I guess
` "ate>\n\n\nNOTIFY sip:6910`
if you see there is `\n\n\n` instead `\r\n` and this create the problem for the **split**

**Comment by devBash99** [comment]
@kYroL01  Ah yes i saw that sorry. So i just need to modify the decoder to be able split on \n\n\n as well. Or maybe go to the source and see what causing this.

**Comment by lmangani** [comment]
@devBash99 modifying the decoder is not the final solution, rather use this useful information to fix the original client breaking standard

**Comment by devBash99** [comment]
@lmangani  The client we use to send packets to hep server is capt-agent. Could this be a problem happening when capt agent encapsulates the packets (we have very old capt agents running) our infrastructure consists of multiple freeswitch as media server and opensisps and sbc. If capt agent dosen't add anything than media servers etc might be sending non compliant packets.

**Comment by devBash99** [comment]
This the second kind error. 
decoder.go:132: parseStartLine err: received err while parsing start line: parseStartLine err: length of s.Val is less than 3
"e>\n</dialog>\n</dialog-info>\nNOTIFY sip:6901@:43394;transport=TCP SIP/2.0\r\nVia: SIP/2.0/TCP :5060
 nodeID: 1912, protoType: 1, version: 2, protocol: 6, length: 1298, flow: :5060->:43394
  server.go:297: stats since last 5 minutes. PPS: 2972, HEP: 891659, Filtered: 0, Error: 17

**Comment by lmangani** [comment]
@devBash99 we can't support ancient versions, this issue might already be resolved as far as we know in a recent release, so the troubleshooting is void unless you can upgrade the instance. Can you do so?

**Comment by lmangani** [comment]
@devBash99 to be clear, captagent is NOT responsible for the newline errors, it just captures and forwards them including any errors they might have - some servers will handle this better than others in HEP just like SIP realms. In my understanding and opinion the actual fault is one of the SIP client/proxy etc sending it forward.

**Comment by devBash99** [comment]
@lmangani  Yes I had planned on upgrading all the capt agents but i was holding on because i was not sure if capt agent would be the culprit here . Our entire infrastructure is old (except homer) we are upgrading to new versions and servers. Like we are running a lot of freeswitch servers on version 1.4.26 on debian 8 . I was looking for a quick solution for now.

**Comment by lmangani** [comment]
@devBash99 I don't think changing the agent would change the fact those captured messages are malformed and rejected by the parser. If you want to try submit a PR for heplify-server to allow those newline malformations as discussed above and want to live with this feel welcome and we'll assist.

**Comment by devBash99** [comment]
@lmangani yes I agree with you, Trying to solve the issue right now with sip clients or proxy is something we can't tackle right now because we are scrapping our entire current infrastructure moving to a whole new production env soon. So yes for a short time I would like to live with this solution(don't like it very much as well). Any help would be very much appreciated. I will try to submit a PR soon. Do you have any development guideline that I need to strictly follow ? Thank you

**Comment by kYroL01** [comment]
@devBash99  I can address you directly to the code

The error you see in your **first** log 
`parseStartLineRequest err: request line did not split on LWS correctly`
is triggered here https://github.com/sipcapture/heplify-server/blob/a683cb969af2eeae93abc3f112c4dc25b2168dfc/sipparser/startline.go#L97

The error you see in your **second** log 
`parseStartLine err: length of s.Val is less than 3. Invalid start line`
is triggered here https://github.com/sipcapture/heplify-server/blob/a683cb969af2eeae93abc3f112c4dc25b2168dfc/sipparser/startline.go#L61

**Comment by lmangani** [comment]
@devBash99 Feel free to send in a PR anytime if you feel this is still required - we'll assist if you get stuck refer this issue
