### ISSUE TITLE
LDAP authentication not getting users groups

### ISSUE THREAD

**Issue by ciscomonkey** [sipcapture/homer#468]
Setting up LDAP Authentication, and I can authenticate against AD with adminmode and usermode set to true.  When I set these to false (to require group membership) Homer is not seeing the groups on the user.

In my config:
```
  "ldap_config": {
    "base": "DC=DOMAIN,DC=local",
    "host": "server.local",
    "port": 636,
    "usessl": true,
    "skiptls": true,
    "binddn": "bind@domain.local",
    "bindpassword": "**",
    "userfilter": "(sAMAccountName=%s)",
    "groupfilter": "(memberUid=%s)",
    "groupattribute": "cn",
    "admingroup": "HOMER Admin",
    "adminmode": false,
    "usergroup": "HOMER User",
    "usermode": false,
    "attributes": ["givenName", "sn", "memberOf", "mail", "uid"],
    "skipverify": true,
    "anonymous": false
  },
```

And when logging in as this user I get the following logs:
```
{"level":"debug","msg":"Sending response request...map[givenName:FIRSTNAME mail:EMAIL memberOf:CN=HOMER User,OU=Groups,DC=DOMAIN,DC=local sn:LASTNAME uid:]","time":"2021-05-20T16:57:10Z"}
{"level":"debug","msg":"Found groups for user USERNAME: []","time":"2021-05-20T16:57:10Z"}
```

The user is part of the group, i've also tried the recursive search for groupfilter and tried the groups in CN=,OU=,DC=... format with no change.

**Comment by adubovikov** [comment]
do you use full DN for group match ? Do you have an example for ldapsearch ?

**Comment by ciscomonkey** [comment]
I've tried both just name as well as full DN with the same result.  The same settings are working for authenticating users into the grafana instance as well.

What do you want to see for ldapsearch?

When searching the user, I see the groups:
```
ldapsearch -x -H ldap://x.x.x.x -D "bind@domain.local" -b "DC=DOMAIN,DC=LOCAL" -W "(sAMAccountName=userid)" 

...snip...
memberOf: CN=HOMER User,OU=Groups,DC=DOMAIN,DC=local
memberOf: CN=HOMER Admin,OU=Groups,DC=DOMAIN,DC=local
...snip...
```

Searching the group, I see the user as a member:
```
ldapsearch -x -H ldap://x.x.x.x -D "bind@domain.local" -b "DC=DOMAIN,DC=LOCAL" -W "(cn=HOMER User)" 

...snip...
member: CN=usercommonname,OU=Users Team,DC=DOMAIN,DC=local
distinguishedName: CN=HOMER User,OU=Groups,DC=DOMAIN,DC=local
...snip...
```

**Comment by ciscomonkey** [comment]
@adubovikov was there anything you want me to pull for this issue?

**Comment by adubovikov** [comment]
I will take a look on it today!

**Comment by adubovikov** [comment]
here you are

https://github.com/sipcapture/homer-app/commit/d5339e5c6f24a5ebc4bb5addc48067ec3dbf3ef9

please check it and let us know!

**Comment by ciscomonkey** [comment]
Unfortunately doesn't appear to change:

```
{"level":"debug","msg":"Sending response request...map[cn:Ryan Mullins dn:CN=Ryan Mullins,OU=Users Team,OU=SERVICE USERS,DC=DOMAIN,DC=local givenName:Ryan mail:ryan.mullins@DOMAIN.com sn:Mullins uid:]","time":"2021-06-15T14:05:00Z"}
{"level":"debug","msg":"Group search by: CN=Ryan Mullins,OU=Users Team,OU=SERVICE USERS,DC=DOMAIN,DC=local","time":"2021-06-15T14:05:00Z"}
{"level":"debug","msg":"New user: CN=Ryan Mullins,OU=Users Team,OU=SERVICE USERS,DC=DOMAIN,DC=local","time":"2021-06-15T14:05:00Z"}
{"level":"debug","msg":"Searching ldap group for user: CN=Ryan Mullins,OU=Users Team,OU=SERVICE USERS,DC=DOMAIN,DC=local","time":"2021-06-15T14:05:00Z"}
{"level":"debug","msg":"Found ldap groups: []","time":"2021-06-15T14:05:00Z"}
{"level":"debug","msg":"Found groups for user USERNAME: []","time":"2021-06-15T14:05:00Z"}
```

**Comment by adubovikov** [comment]
@ciscomonkey sorry, but can you check if "CN=Ryan Mullins,OU=Users Team,OU=SERVICE USERS,DC=DOMAIN,DC=local" has any memberof attributes ? or maybe CN=rmullins ? Because the ldapsearch like -W "sAMAccountName=userid" doesn't say too much

**Comment by ciscomonkey** [comment]
Sorry @adubovikov for the delay, I seem to have missed the notification.

It does, it's in the first snippet in the notes above.  I just put ```userid``` to scrub the user data in those examples - here's a full snippet of the ```memberOf``` attributes of my user - replacing the domain name with {{DOMAINNAME}} on the output:

```
memberOf: CN=HOMER User,OU=Groups,DC={{DOMAINNAME}},DC=local
memberOf: CN=HOMER Admin,OU=Groups,DC={{DOMAINNAME}},DC=local
memberOf: CN=MCP Users,OU=Groups,DC={{DOMAINNAME}},DC=local
memberOf: CN=MCP Staff,OU=Groups,DC={{DOMAINNAME}},DC=local
memberOf: CN=MCP Administration,OU=Groups,DC={{DOMAINNAME}},DC=local
memberOf: CN=vSphereVCAdmins,CN=Users,DC={{DOMAINNAME}},DC=local
memberOf: CN=Domain Admins,CN=Users,DC={{DOMAINNAME}},DC=local
```

**Comment by ciscomonkey** [comment]
@adubovikov just curious if you needed anything else from me on this one?

**Comment by lmangani** [comment]
Hello @ciscomonkey we will get to this eventually, but unfortunately our agenda is quite loaded at the moment. 
If this is urgent you would consider a sponsoring this fix, we might prioritize it forward.

**Comment by adubovikov** [comment]
@ciscomonkey sorry, i will try to find time on this WE. As @lmangani mentioned before, now we are kindly busy :( Thank you!

**Comment by adubovikov** [comment]
@ciscomonkey sorry for delay, but we found the issue

https://github.com/sipcapture/homer-app/commit/23e959eb48ad8ad320eb35863abde920d71b51e1


please set the correct group_attributes in your webapp_conifg.json and it should work!

```
"group_attributes": [
     "cn",
     "memberOf",
     "GroupAttribute",
     "distinguishedName",
     "dn",
     "member"
   ],
```

**Comment by adubovikov** [comment]
@ciscomonkey any feedback ? I will close the ticket - please reopen if it won't work

**Comment by ciscomonkey** [comment]
Sorry, I missed the notifications.  Unfortunately no change for me here. 

```
homer-webapp    | {"level":"debug","msg":"Found ldap groups: []","time":"2021-10-14T05:34:42Z"}
homer-webapp    | {"level":"debug","msg":"Found groups for user USERNAME: []","time":"2021-10-14T05:34:42Z"}

**Comment by nakchak** [comment]
@ciscomonkey Have you tried setting your group filter to use LDAP_MATCHING_RULE_IN_CHAIN oid?

https://docs.microsoft.com/en-gb/windows/win32/adsi/search-filter-syntax

As soon as i set my group filter to use that it solved all of my group based login issues...
Here is suitably scrubbed of credentials copy of my working LDAP config

```
  "ldap_config": {
    "base":  "dc=domain,dc=local",
    "host":  "dc01.domain.local",
    "port":   636,
    "usessl": true,
    "skiptls": false,
    "binddn": "CN=LDAPLookupUser,CN=Builtin,DC=domain,DC=local",
    "bindpassword": "S3cur3_P4ssW0rd",
    "userfilter": "(sAMAccountName=%s)",
    "groupfilter": "(member:1.2.840.113556.1.4.1941:=%s)",
    "admingroup": "HomerAdmins",
    "adminmode": false,
    "usergroup": "HomerUsers",
    "usermode": false,
    "attributes": ["dn", "givenName", "sn", "mail", "sAMAccountName"],
    "UseDNForGroupSearch":true
  },
```

**Comment by ciscomonkey** [comment]
@nakchak That was the missing part!  

I had to add the fix from @adubovikov above in addition to using OID and that was the magic combo for me.

**Comment by nakchak** [comment]
@ciscomonkey Happy to help, glad that fixed it
