### ISSUE TITLE
Convert project to GIT submodular structure

### ISSUE THREAD

**Issue by kvishnivetsky** [sipcapture/homer#47]
Main meta-project 'homer'.
Subprojects:
+ 'homer-web' - main WUI components
+ 'homer-web-mysql' - 'homer-web' MySQL configs and dependencies  for installation via OS package manager
+ 'homer-kamailio-mysql' - kamailio configs and dependencies for installation via OS package manager
+ 'homer-captagent' - capture agent code with configs and dependencies

The whole build will produce several system packages, which may be installed in apropriate combination.

**Comment by lmangani** [comment]
Hi Konstantin,

For discussion: this is a good proposal, but forthcoming version 5 will change things quite a bit so the topic can be more safely get addressed once we release out in May/June. Only exception would be captagent, this has been for some time a separate project (sipcapture/captagent) with different cycles and should best not be included/packaged with Homer generally speaking.

**Comment by kvishnivetsky** [comment]
No problem, let's wait for v5.

17.04.2015 14:18, Lorenzo Mangani пишет:
>
> Hi Konstantin,
>
> For discussion: this is a good proposal, but forthcoming version 5 
> will change things quite a bit so the topic can be more safely get 
> addressed once we release out in May/June. Only exception would be 
> captagent, this has been for some time a separate project 
> (sipcapture/captagent) with different cycles and should best not be 
> included/packaged with Homer generally speaking.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/sipcapture/homer/issues/47#issuecomment-93941017>.
>


-- 
С уважением,
Константин С. Вишнивецкий
Тел.: +7 913 774-7588
ICQ: 328-468-511
SkyPE: kvishnivetsky
URL: http://www.vishnivetsky.ru

**Comment by lmangani** [comment]
For tracking an initial version of this approach has been implemented for Homer 5 release (homer-ui, homer-api and more will come) while captagent will remain separate and separately tracked.
