### ISSUE TITLE
Homer-UI only display max of 200 records

### ISSUE THREAD

**Issue by ngeksyo** [sipcapture/homer#470]
Hi All,

I am noticing that homer-ui only display 200 records max. Is this the correct behavior or is this a bug?

I am sure that there are more that 200 records because i can search records that are not in the list and HEP traffic to server are just fine.

![image](https://user-images.githubusercontent.com/5231255/120316630-37eb6980-c310-11eb-8457-aa627e3fba8e.png)

![image](https://user-images.githubusercontent.com/5231255/120316722-4d609380-c310-11eb-9fbc-83d250fb6e18.png)

**Comment by lmangani** [comment]
This is a common first day obstacle :) Add the `query limit` field to your forms, and you'll control the limit of each query

welcome to the homer club!
