### ISSUE TITLE
db won't start, docker log file show permission issue

### ISSUE THREAD

**Issue by tp-8426** [sipcapture/homer#472]
When running docker-composer, the db stays in a "Restarting" state:
    **db               docker-entrypoint.sh postgres    Restarting**

Looking at **docker-compose logs --follow db**:

    chmod: /var/lib/postgresql/data: Permission denied
    chown: /var/lib/postgresql/data: Permission denied
    ...
    db exited with code 1

------------------------------------------------------------------
**# docker info**:
Containers: 7
 Running: 6
 Paused: 0
 Stopped: 1
Images: 9
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc docker-runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 66aedde759f33c190954815fb765eedc1d782dd9 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-1160.31.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 2
Total Memory: 7.666 GiB
Name: labhomr-ads-1
ID: POJR:AC4P:VGS5:OY4C:P5OC:X2AW:COMH:KMZL:Y6X2:GUUN:VKQ6:BY6C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)

**Comment by tp-8426** [comment]
I found an post that suggested that the volume mapping should be "- ./postgres-data:/var/lib/postgresql" instead of "- ./postgres-data:/var/lib/postgresql/data".  Ref: https://serverfault.com/questions/857209/postgres-in-a-docker-container-not-working-constantly-restarting

Removing "/data" and then issuing **docker-compose up -d** worked, all containers are up.

**Comment by lmangani** [comment]
Feel free to send in a PR if you think any of the defaults are at fault here
