### ISSUE TITLE
SIP Method Message

### ISSUE THREAD

**Issue by bmgante** [sipcapture/homer#474]
Hi.

Does homer support Sip request method message? If yes, what is the template to be used to query those messages in homer UI?

Thanks

**Comment by lmangani** [comment]
@bmgante HOMER will capture anything its agents can sniff and forward, which in most cases includes any SIP method or its response when agents are properly configured. I'm not at all sure what you mean.

**Comment by bmgante** [comment]
indeed, I am able to get message type through sip_deafult. 
It was good if we could add MESSAGE as a type for SIP Method ddl:
![image](https://user-images.githubusercontent.com/27358817/126151517-1d8eb20e-17bf-438e-9857-7d3021980d15.png)

**Comment by adubovikov** [comment]
you can type as well :-) anyway, the mapping can be easy edit and you can add any type of methods
