### ISSUE TITLE
docker-compose up throws error

### ISSUE THREAD

**Issue by ChicagoJay** [sipcapture/homer#476]
VM running Windows 10 Pro (21H1) and Docker Desktop with Debian WSL2 environment.

After running 
```
git clone https://github.com/sipcapture/homer7-docker
cd homer7-docker/heplify-server/hom7-prom-all
```
The `docker-compose up -d` command fails at `Running 4/6` with: `Error response from daemon: path /home/technician/homer7-docker/heplify-server/hom7-prom-all/prometheus is mounted on / but it is not a shared mount.`

Containers prometheus and grafana never get created.

Please let me know how to pull logs to help troubleshoot.

Thanks!

EDIT:
I deleted everything (containers, images, and volumes) and tried it again, with sudo, and this time I got an error in Creating db:
```
ERROR: for db  Cannot create container for service db: not a directory
ERROR: Encountered errors while bringing up the project.
```
I deleted everything again, and sudo'd the compose command again, and got the same result with db not being able to create a container.

**Comment by lmangani** [comment]
marking as resolved / inactive, feel free to update if still needed.

**Comment by ChicagoJay** [comment]
> marking as resolved / inactive, feel free to update if still needed.

I never got any advice on how to sort this out.  I am using the non-docker version.

**Comment by adubovikov** [comment]
this is local docker problem, we can suggest update it to the actual and retest it
