### ISSUE TITLE
SDP packet indicator in flow view

### ISSUE THREAD

**Issue by solarmon** [sipcapture/homer#477]
Hi,

When I use sngrep, I find it useful when it shows a "(SDP)" text on a packet that has SDP in it.

However, in the Homer 7 web GUI in the flow view of the trace, you have to go in to the packet to see if there is any SDP details in it.

Can the flow view be changed to give an indication of whether SDP is present in a packet or not, without having to open it up. If the same behaviour as sngrep to add "(SDP)" to the packet name (ideally in a different colour) then that would be great!

Thank you!

**Comment by lmangani** [comment]
Thanks for letting us notice! This is indeed a bug as this feature has been in homer for the last 10+ years.
We'll fix and restore the SDP indicator in the Flow and Messages tab.

**Comment by lmangani** [comment]
resolved in latest homer-app (1.3.24)
![image](https://user-images.githubusercontent.com/1423657/128172293-1fb13192-5c04-4531-8975-284cf72ddb33.png)

**Comment by solarmon** [comment]
@lmangani 

Thank you!

What is the process to upgrade an existing install without losing existing data?

**Comment by lmangani** [comment]
It depends - if you installed using packages, upgrade the packages - no data will be lost (its in the DB), if you used docker pull the latest images and restart. 

_Note the packages are being built and pushed so there might be a delay in them showing up on the repository._

**Comment by solarmon** [comment]
@lmangani 
Thank you. I'm using dockers. I used "docker-compose pull" and then "docker-compose up -d", but I did have some errors returned - for example:


```
# docker-compose up -d
Removing grafana
loki is up-to-date
caddy is up-to-date
prometheus is up-to-date
Recreating 976e563740dc_976e563740dc_grafana ...
Recreating 976e563740dc_976e563740dc_grafana ... error

ERROR: for 976e563740dc_976e563740dc_grafana  You cannot remove a running container 976e563740dcb5719527128c0a806a5b807ae4fed7258d5b2de3bfee9793fc3d. Stop the container before attempting removal or use -f

ERROR: for grafana  You cannot remove a running container 976e563740dcb5719527128c0a806a5b807ae4fed7258d5b2de3bfee9793fc3d. Stop the container before attempting removal or use -f
ERROR: Encountered errors while bringing up the project.

```

and


```
Removing db
Starting loki ...
Starting caddy ...
Starting prometheus ...
Starting loki ... done
Recreating 0bde8cfa8bf5_db ...
Starting alertmanager ...
Recreating 0bde8cfa8bf5_db ... error

ERROR: for 0bde8cfa8bf5_db  You cannot remove a running container 0bde8cfa8bf54e60ec489978fbe0df556d89014691fc3911953d1890e4f39965. Stop the container before attempting removal or use -f

ERROR: for db  You cannot remove a running container 0bde8cfa8bf54e60ec489978fbe0df556d89014691fc3911953d1890e4f39965. Stop the container before attempting removal or use -f
ERROR: Encountered errors while bringing up the project.
```

For the last one, I used "docker stop db" and tried it again and it built it OK.

Now I can see the SDP indicator in the flow view! 

I also now realise that it would also be useful to see this SDP indicator in the results and message list for the SIP Method, but the flow view was the main priority.

Thank you once again!

**Comment by lmangani** [comment]
Upgrade again in a couple hours. There's another half of this PR which was not merged at the time of building.

**Comment by adubovikov** [comment]
fixed. UI 7.9.16
