### ISSUE TITLE
Shared link bug: SIP flow not working

### ISSUE THREAD

**Issue by AlexeyLilichenko** [sipcapture/homer#479]
Have problem with shared link.
I prepare **shared link**, in my case example for dev-system:
http://172.27.88.125:9082/search/result?%7B%22timestamp%22:%7B%22from%22:1628056194750,%22to%22:1628056705670%7D,%22param%22:%7B%22search%22:%7B%221_call%22:%7B%22id%22:43126,%22callid%22:%5B%22a2fcaeea-68dd16b6@10.128.150.71%22,%224642b04b27bae6dd597a418a0799ef15@172.27.88.207:5060%22,%226f2dbfe00aa114c328b29d8a1112db35@172.27.88.113:5060%22%5D,%22uuid%22:%5B%5D%7D%7D,%22location%22:%7B%7D,%22transaction%22:%7B%22call%22:true,%22registration%22:false,%22rest%22:false%7D,%22id%22:%7B%7D,%22timezone%22:%7B%22value%22:-180,%22name%22:%22Local%22%7D%7D%7D= 

Some user opens **shared link**, login into Homer (if not logged in already).
Then, if he click on **Session ID** value, he usually see **Flow** and other tab related to call.
But, sometimes it does not work.

**When it not working**:
1) if I remove **localStorage** for Homer web-page
2) user opened **Shared Link** before he did any "**Search**" inside homer

**Why it is not working**:
When **localStorage** do not have "**searchQuery**" element, user can open shared link and see list of SIP-messages, but click on "**Session iD**" value does not open any window, so he cannot see Flow and other tabs.

Workaround to make it work right now:
1) if **localStorage** was deleted, user need to do **Login** into homer, then he need to press "**Search**" one time (parameter does not matter). As a result, "**searchQuery**" will appear in **localStorage**.
2) Now user can open "**Shared Link**" and click "**Session ID**" value and in new window he will see "**Flow**" and other tabs.

Can you fix that, please?

I use https://github.com/sipcapture/homer7-docker
with Homer 7.9.13

**last commit there:**
commit **42796c31ead32735b5a9d97ec492790bf79e8e31**
Author: Lorenzo Mangani <lorenzo.mangani@gmail.com>
Date:   Wed Mar 3 16:47:42 2021 +0100

**Comment by adubovikov** [comment]
The issue has been fixed and we released a new package. Please test it and reopen the issue if needed.
