### ISSUE TITLE
Check exit code for git clone

### ISSUE THREAD

**Issue by nshopik** [sipcapture/homer#48]
`git clone --depth 1 git://git.sip-router.org/sip-router kamailio`

This string currently fail because of some git repo problems. Installer should check exit code before move to next part or give more noticeable error as it currently easily missed in small terminal because of scrollback

**Comment by lmangani** [comment]
For simplicity i added a check if the clone directory before proceeding down the script. 
Let us know if this suffices until the new version brings a new script: https://github.com/sipcapture/homer/commit/b0fb3ff208e189ae02d51ca1e6f440c5660f9dab
