### ISSUE TITLE
Docker install docs

### ISSUE THREAD

**Issue by petekelly** [sipcapture/homer#481]
Minor issue, the docker installation lists port 9060/tcp for sending HEP, it should be 9061

https://github.com/sipcapture/homer/wiki/Quick-Install#-docker-install

**Comment by lmangani** [comment]
Hey @petekelly 
Which compose bundle are you referring to? Generally speaking, the udp/tcp/tls HEP ports can be freely changed via the heplify-server container ENV variables to match the mapping, none is statically assigned so this can be overridden.

**Comment by petekelly** [comment]
Hello @lmangani  :)

The docker install guide says "You should now be able to access your HOMER instance on port 9080 and send HEPv3 traffic to port 9060" - this was in fact 9060/UDP and 9061/TCP when I checked the docker-compose.yml file.

Maybe it just needs clarification, I spent a while trying to send to 9060/TCP (I assumed tcp being the default for hepv3) 

"You should now be able to access your HOMER instance on port 9080 and send HEPv3 traffic to port 9060/UDP or 9061/TCP"

would be clearer, for me anyway!

**Comment by lmangani** [comment]
I see what you mean now - modified to make a little more sense! Thanks Pete!

**Comment by petekelly** [comment]
Thank you :) I checked it and I think you changed the Manual Install section instead of Docker. Any chance you could change that one too?

**Comment by lmangani** [comment]
done and done! ;)
