### ISSUE TITLE
Can I use HEP agent with TCP to send message to HOMER server?

### ISSUE THREAD

**Issue by portsip** [sipcapture/homer#482]
Can I use HEP agent with TCP to send messages to the HOMER server?
The UDP maybe lost the data.

**Comment by adubovikov** [comment]
yes, you can,

**Comment by adubovikov** [comment]
https://github.com/sipcapture/captagent/blob/master/conf/transport_hep.xml#L9

change to tcp and of course be sure that the destination port is also TCP
