### ISSUE TITLE
How to Manual install?

### ISSUE THREAD

**Issue by hb9eue** [sipcapture/homer#485]
Dear Team

Debian Stretch is EOL. CentOS is a NoGo for my employer.
Docker is probably not the way to go, as this will be part of a TSP Core infrastructure.
So I'm looking for information how to do a manually install of Homer 7 on preferably Ubuntu 20.04

Could anyone point me the right direction? Any help appriciated.

-Benoît-

**Comment by lmangani** [comment]
Not sure I understand. Debian 10 is fully supported, as should its derivates - the installer is just as opensource as the code it installs, and can be easily extended in case of issues.

**Comment by adubovikov** [comment]
you can use any OS - the all components are static :-)

**Comment by hb9eue** [comment]
> Not sure I understand. Debian 10 is fully supported, as should its derivates - the installer is just as opensource as the code it installs, and can be easily extended in case of issues.

Yes, I went down that rabbit hole on ubuntu 20.04, but after I 'fixed' one installer check after the other and more and more cam up, I just gave up.
Maybe I should have a go under Debian 11?

**Comment by hb9eue** [comment]
> you can use any OS - the all components are static :-)

Sure, I can clone the repositories, but then? Lots of templates to copy for every part. Lot of try and error and possibilities to go down the wrong trouser leg. So I had hoped for some sort of guideline.

**Comment by adubovikov** [comment]
> Yes, I went down that rabbit hole on ubuntu 20.04, but after I 'fixed' one installer check after the other and more and more cam up, I just gave up.
> Maybe I should have a go under Debian 11?

But again, what's is the problem install homer-app and heplify-server from packages ?

**Comment by hb9eue** [comment]
> But again, what's is the problem install homer-app and heplify-server from packages ?

Ok, I suppose I missed something. There are ready made deb packages? Where?

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer/wiki/Quick-Install#-manual-install

**Comment by adubovikov** [comment]
Heplify-server:
```
wget --content-disposition https://packagecloud.io/qxip/sipcapture/packages/debian/buster/heplify-server_1.56.0_amd64.deb/download.deb
```
Homer-App
```
wget --content-disposition https://packagecloud.io/qxip/sipcapture/packages/debian/buster/homer-app_1.3.28_amd64.deb/download.deb
```

**Comment by hb9eue** [comment]
> https://github.com/sipcapture/homer/wiki/Quick-Install#-manual-install

Thank you, somehow I feel stupid now. I always tough this was for the obsolete Homer 5 version which I tried before.

**Comment by adubovikov** [comment]
sure, you are welcome.

Don't forget start us: https://github.com/sipcapture/homer/stargazers
