### ISSUE TITLE
Procesing SRTP-XR messages

### ISSUE THREAD

**Issue by mcebey1891** [sipcapture/homer#487]
Hello there

I have installed the docker version and two probes with captagent.
In the probes I see RTCP packets arriving with extended reports (RFC 3611) but when I go to the QoS window in the web-app, no related data appears. Also in Grafana, in the QoS XRTP tabs I don't have any data.

This is not related to the recent update because it happened with the previous version.

Do I have to configure something in particular so that the information of the SRTP-XR packets is processed?

Thanks

**Comment by lmangani** [comment]
Hello @mcebey1891 
For cases like this, we can't do much without actual packet examples and without the running config of the agent.
As a starter, are you 100% sure the portrange to capture those is correctly configured the agent?
Please provide a PCAP/TXT Dump with some of the packets in question and we'll check them together

**Comment by mcebey1891** [comment]
Do you need all the captagent configuration or just some files?

The traces I have are from clients, is there a place that can send the information directly to you?

Thanks

**Comment by mcebey1891** [comment]
Hello, sorry for the use of your time.

While making the example traces, I found that although I have the packages with extended report, they do not have the information I was looking for.

I'm going to close the case.

Thanks for all.

**Comment by lmangani** [comment]
@mcebey1891 what information were you looking for and what were those packets exactly?

**Comment by mcebey1891** [comment]
On the Grafana QOS XRTP dashboard I haven't any data

![QoS](https://user-images.githubusercontent.com/54403048/132019986-9e977358-6f6c-46d7-830f-bb973c7e7694.png)

That information is very useful for Me. But if it is not in the RTCP packets, there is not much to do. I leave a trace as an example.

[call_rfc3611.zip](https://github.com/sipcapture/homer/files/7106529/call_rfc3611.zip)

**Comment by lmangani** [comment]
This is just normal RTCP. HEPlify or any other basic agent should be able to produce reports for it just fine.
