### ISSUE TITLE
inverted arrows

### ISSUE THREAD

**Issue by tsabi** [sipcapture/homer#49]
Hi,
i think i use the latest webhomer from git, and the arrows on the call flow shows inverted in my system.
Attached a sample call.
thanks,
Csaba

![1429865217](https://cloud.githubusercontent.com/assets/210099/7315867/da4771f2-ea71-11e4-9d75-ef7d281edb16.png)

**Comment by adubovikov** [comment]
preferences.php:

define('CFLOW_DIRECTION', 0); /* Callflow Direction */
