### ISSUE TITLE
Homer web GUI - Regex Results Filter - not working with regular expressions

### ISSUE THREAD

**Issue by solarmon** [sipcapture/homer#495]
Hi,

As requested in the Gitter chat, this is a ticket to track the issue with the "Regex Results Filter" not working with regular expression, and only seems to behave as a string match.

Thank you.

**Comment by AlexeyOplachko** [comment]
This feature will be pushed to develop branch later today, thanks for bringing our attention to this 😉

**Comment by AlexeyOplachko** [comment]
Fix is live on develop branch

**Comment by adubovikov** [comment]
homer-app-1.4.13
