### ISSUE TITLE
Pressing ESC should close windows one-by-one

### ISSUE THREAD

**Issue by gedia** [sipcapture/homer#499]
In homer5, pressing ESC while viewing (having "in-focus") a floating window would only close that window. In homer7, all windows are closed. I do think the homer5 behaviour is more practical. Scenario:

- Perform a search
- Open a callid and navigate to the "flow" tab
- Click on an "INVITE" message from the flow, new floating window appears
- Click on a "200 OK" message from the flow, another floating window appears
- Press ESC once, "200 OK" message window closes
- Press ESC again, "INVITE" message window closes
- Press ESC again, flow diagram window closes.

If people prefer the current "clear all" behaviour, perhaps it could be configurable in settings?

**Comment by adubovikov** [comment]
@gedia so, the feature has been implemented - I will close the ticket!
