### ISSUE TITLE
Default MySQL Schema: Call-ID field too short

### ISSUE THREAD

**Issue by jawaidbazyar** [sipcapture/homer#5]
The default Call-ID field length in the MySQL schema is too short.

The Schema has Call-ID at 100 characters. However, the SIP RFC specifies no maximum length on the SIP Call-ID field.

**Comment by lmangani** [comment]
The current schema optimization limit for Call-ID is based on real life scenarios. Do you have examples where the 100 chars limit is exceeded consistently for Call-ID header?

**Comment by jawaidbazyar** [comment]
Yes, my softswitch (MetaSwitch, which is the leading softswitch in ILECs and many CLECs) routinely generates long call-IDs. Example:
| 0gQAAC8WAAACBAAALxYAAHFsRPBpW7e07LTBw2tzPpFkUQJ+BzjNhGh9LP+3ligcAygrTHySXhj/gH/ItOwLxQ--@68.64.213.163 |
| 0gQAAC8WAAACBAAALxYAAHFsRPBpW7e07LTBw2tzPpFkUQJ+BzjNhGh9LP+3ligcAygrTHySXhj/gH/ItOwLxQ--@68.64.213.163 |
| 0gQAAC8WAAACBAAALxYAAD6aJkx4RdVn+uZLb5ZgRU4mfhIFiQg6KhyI9RVx2+mOeEurmyay8M2iXyVf/r6sxQ--@68.64.213.163 |
| 0gQAAC8WAAACBAAALxYAAD6aJkx4RdVn+uZLb5ZgRU4mfhIFiQg6KhyI9RVx2+mOeEurmyay8M2iXyVf/r6sxQ--@68.64.213.163 |
| 0gQAAC8WAAACBAAALxYAAFe8E8alPE9f7R2AxvMb4adYf7wNaK0qE8xHrnL2KZsfoOgVw2Lq4Skx0CGLL0eXGA--@68.64.213.163 |
| 0gQAAC8WAAACBAAALxYAAFe8E8alPE9f7R2AxvMb4adYf7wNaK0qE8xHrnL2KZsfoOgVw2Lq4Skx0CGLL0eXGA--@68.64.213.163 |
| 0gQAAC8WAAACBAAALxYAALJWplX6XBW+5+RcXmrQ7aAeTQq36Q2EfOGQctJPM2nkNGWT4FGd0U/Gt3TaUy6jjg--@68.64.213.163 |
| 0gQAAC8WAAACBAAALxYAALJWplX6XBW+5+RcXmrQ7aAeTQq36Q2EfOGQctJPM2nkNGWT4FGd0U/Gt3TaUy6jjg--@68.64.213.163 |

**Comment by lmangani** [comment]
Fields extended to 120 chars in schema for now (which should also account for min. encoding, etc)
https://github.com/sipcapture/homer/commit/d1c026408fe37cc32f17e56c8c2745f5c0ac7d50
