### ISSUE TITLE
Cannot install on Debian11

### ISSUE THREAD

**Issue by antonio-couto** [sipcapture/homer#500]
I cannot install on Debian 11,

Unable to locate package heplify-server
Unable to locate package heplify

homer-app is ok

Any advice please ?

thanks in advance.

**Comment by kYroL01** [comment]
Thanks for sharing this! We will have a look asap

**Comment by adubovikov** [comment]
The package is static, therefore you can install this package wget --content-disposition https://packagecloud.io/qxip/sipcapture/packages/ubuntu/bionic/homer-app_1.4.18_amd64.deb/download.deb

**Comment by adubovikov** [comment]
and heplify-server

wget --content-disposition https://packagecloud.io/qxip/sipcapture/packages/debian/stretch/heplify-server_1.56.0_amd64.deb/download.deb

**Comment by antonio-couto** [comment]
Thanks a lot, I will try to install.

**Comment by yeya** [comment]
Same issue with Ubuntu 20.04.1 LTS.
I don't think it's right to close the issue.

**Comment by adubovikov** [comment]
@yeya same as above - the all app are static binary - you can install debian package on any Ubuntu or Mint systems.
on the next round we will upload it to Ubuntu LTS as well

**Comment by adubovikov** [comment]
@yeya ok. We have uploaded for Bullseye,Focal and Bionic

enjoy!
