### ISSUE TITLE
IPV6 call legs don't show up when we export a PCAP from Homer

### ISSUE THREAD

**Issue by vandenp** [sipcapture/homer#501]
If a call involves IPV6 those call legs don't show up when we export a PCAP from Homer.  They are visible in the "export TEXT" file and also are shown in the PNG file.

**Comment by adubovikov** [comment]
can you please tell the version of homer-app?

**Comment by vandenp** [comment]
The version of homer-app is 7.9.13

We use the latest docker images
echo "  >> Install Homer7 .."
git clone https://github.com/sipcapture/homer7-docker 
echo " >> Pull container images .."
/usr/local/bin/docker-compose -f homer7-docker/heplify-server/hom7-prom-all/docker-compose.yml pull

**Comment by adubovikov** [comment]
@vandenp sorry, can you make a PG dump of your trace and provide us private ? We have checked our IPv6 stream and these are ok.

**Comment by vandenp** [comment]
@adubovikov 
I just need to find out if I'm allowed. Will get it for you tomorrow if I get the thumbs up.

**Comment by vandenp** [comment]
@adubovikov 
Unfortunately I'm not permitted to share the PG dump.
Is there any hints you can give on how we could debug this issue on our end?
Are there Homer app logs that we could share?

**Comment by adubovikov** [comment]
@vandenp ok, please enable full debug in system_settings and send the log to us

**Comment by vandenp** [comment]
@adubovikov 
Attaching the Homer log.
At 10:46am I pressed the "Export PCAP" and a 10:51am
Seeing lots of these:
 {"level":"error","msg":"write error to the pcap buffer Invalid source IPv4 address (address is IPv6)","time":"2021-11-04T14:52:27Z"}
[homer-app.log.2021_11_04_00_00.txt](https://github.com/sipcapture/homer/files/7476545/homer-app.log.2021_11_04_00_00.txt)

**Comment by adubovikov** [comment]
@vandenp can you please confirm that both IP addresses are IPv6 ? and you don't have mix IPv4 and IPv6

**Comment by vandenp** [comment]
@adubovikov 
One of the users was IPv4 and the other was IPv6.

**Comment by adubovikov** [comment]
I think this is impossible, you couldn't generate IP header that has one ipv4 and another ipv6. Maximum you can make encapsulation that includes one IPv4 IP Layer and IPv6, but again, you should have 4 addresses to generate it.

**Comment by vandenp** [comment]
There are four unique call legs involved in this call. The calls are connected together.
The 3 legs have ipv4 IP headers. One has ipv6 IP headers.

**Comment by adubovikov** [comment]
in this case it should works without any problem. Can you download and install the latest package and test one more time ?

I have also added some more debug info

**Comment by vandenp** [comment]
We installed the latest package and we now see the iPV6 call legs. 
Thanks very much @adubovikov.

**Comment by adubovikov** [comment]
superb! :-) Enjoy!
