### ISSUE TITLE
homer-7, 7.10.13 - Failed to load API definition on "preference/api%2520documentation"

### ISSUE THREAD

**Issue by khorsmann** [sipcapture/homer#506]
Hi folks,

i want to report that the homer-webapp 7.10.13 didnt have the swagger-json. After reading a bit around here, its an additonal step needed to generate them. This step seems missing to the docker-images.

```shell
$ git branch
* homer7
$ git log | head -n1
commit d89827595401fad9a670cb1dc84dc801634e8566

$ git clone https://github.com/sipcapture/homer.git
$ cd homer
$ update_subs.sh
$ cd homer-docker/heplify-server/hom7-prom-all
# changed the docker-compose.yml to my needs.
$ docker-compose up -d
```

Failed to load API definition.
```shell
{"data":{},"message":"swagger file couldn't be found"}
```

Best - Karsten

**Comment by adubovikov** [comment]
Hi @khorsmann ,

thanks for report. @AlexeyOplachko can you please check it ?

the file is located in the homer-app https://github.com/sipcapture/homer-app/blob/master/swagger.json

**Comment by AlexeyOplachko** [comment]
Should be fixed with this: https://github.com/sipcapture/homer-app/commit/967cee567fcd4c9eda9f3c06b997a1c3ae548892
