### ISSUE TITLE
Problem with Displayed timezone select

### ISSUE THREAD

**Issue by VladimirMokhov** [sipcapture/homer#508]
Hi, I have a problem with "Displayed timezone select". It does not work: I wanna change the timezone but everytime I have the same result (after changing and pushing the "apply" button). My timezone remains unchanged...

I installed the latest version from https://github.com/sipcapture/homer/wiki/Quick-Install#-quick-install
![new](https://user-images.githubusercontent.com/88138056/144615764-a3bb9a52-4dd5-49c7-8f01-9fcccc18a319.png)

![new2](https://user-images.githubusercontent.com/88138056/144615775-fb92d0bd-b816-4bef-b0ef-283108cac4ff.png)

P.S. I would like to ask how can I know the version of my Homer7?

Thank you.

**Comment by adubovikov** [comment]
@VladimirMokhov how did you install it ?

if you use the package:

rpm -qa | grep homer

or
dpkg -l | grep homer

and also you can see in the title - UI version

**Comment by adubovikov** [comment]
@VladimirMokhov it has been fixed https://github.com/sipcapture/homer-ui/commit/c29cd3337af27ccefdc332dd8fb425940dad3d36

and we have created a new package: 1.4.27 

please update!

Regards,
Alexandr

**Comment by adubovikov** [comment]
@VladimirMokhov don't forget to star us: https://github.com/sipcapture/homer/stargazers :-)

**Comment by VladimirMokhov** [comment]
Thank you!

**Comment by lmangani** [comment]
@VladimirMokhov please confirm if this resolves your issue

**Comment by VladimirMokhov** [comment]
Issue resolved.
