### ISSUE TITLE
Use of Server Header to identify UAS

### ISSUE THREAD

**Issue by xaled1** [sipcapture/homer#511]
When observing a call in "Session Info" Tab a UAS will only be identified if it has provided a "User-Agent" Header. It is often not the case. It would be helpful to have the "Server:" header used as well as a fallback for UAS identification if no User-Agent header is available.

**Comment by adubovikov** [comment]
@jacovinus can you please add it to Homer-UI ? if UAS is empty = force to .Server

**Comment by jacovinus** [comment]
already solved doing if UAS is empty, force to server, please try with last UI version.

**Comment by kYroL01** [comment]
Implemented and fixed - closing it

![ScreenShot_20221012175315](https://user-images.githubusercontent.com/7222956/195390407-8d8e18a9-aeca-413f-a042-7051b3552c27.png)
