### ISSUE TITLE
Make alias names for IP addresses also availabe in "QoS" tab 

### ISSUE THREAD

**Issue by xaled1** [sipcapture/homer#514]
It would be helpful to be able to use alias names for IP addresses also in "QoS" tab for the the call observation.

**Comment by kYroL01** [comment]
Hi @xaled1 thanks for the ticket.
Yes, @naqashsaeed tested and we reproduced it.
@AlexeyOplachko Can you please check about this, as the Alias are not visible on the QOS tab ?
We should add this feature also for that.
![image](https://github.com/sipcapture/homer/assets/7222956/053071c3-62bc-41c4-852c-a904f6c195b0)

**Comment by kYroL01** [comment]
The feature is implemented and tested by @naqashsaeed - we can close the ticket

**Comment by kYroL01** [comment]
![image](https://github.com/sipcapture/homer/assets/7222956/4055e730-7ca8-4257-9908-0a1aa1c63788)
