### ISSUE TITLE
sip flow ui - inability to scroll down after scrolling right

### ISSUE THREAD

**Issue by sudomoke** [sipcapture/homer#518]
When viewing the sip flow of wide captures, i am not able to scroll down when scrolled right. It'll glitch and prevent vertical scrolling until you scroll horizontally left to the original position. 

I've found this to occur in Google Chrome, Edge, and Firefox on Windows 10.

**Comment by lmangani** [comment]
@Moke could you please attach an example image, gif, anything to help understand this visually

**Comment by sudomoke** [comment]
Here's a gif: https://imgur.com/a/BQERTbb

**Comment by adubovikov** [comment]
@Moke we have asked our dev team to check it

**Comment by RFbkak37y3kIY** [comment]
fixed and merged to 'develop' branch

**Comment by adubovikov** [comment]
the issue has been fixed. Please reopen if need it

**Comment by sudomoke** [comment]
I am still able to reproduce this issue as of homer-app --version VERSION: 1.4.29

**Comment by adubovikov** [comment]
sorry, now it should be ok

homer-app-1.4.30-amd64

can you please recheck ?

**Comment by sudomoke** [comment]
So far so good. I'll update if I am able to reproduce.
