### ISSUE TITLE
SentryPeer data integration

### ISSUE THREAD

**Issue by ghenry** [sipcapture/homer#519]
Hi all,

I've started this in Oct 2021 in my evenings:

https://github.com/SentryPeer/SentryPeer

I've just released v1.0.0 as I'm happy now that you can do (p2p replication of data next):

- Process and chose to reply 200 OK to SIP probes (set via cli or env variable)
- List collected IP addresses via the RESTful API
- Query a specific IP address via the RESTful API
- List collected phone numbers via the RESTful API
- Query a specific phone number via the RESTful API

I'm looking to start building a ML training model and exploring how to best match this into data captured via Homer so you could do various things with it like you'd normally do during your day to day VoIPOps.

Or is there something like this already that I've missed?

A bit about me and the project:

- https://www.se-radio.net/team/gavin-henry/
- https://blog.tadsummit.com/2021/11/17/sentrypeer/
- https://2021.commcon.xyz/talks/sentrypeer-a-distributed-peer-to-peer-list-of-bad-ip-addresses-and-phone-numbers-collected-via-a-sip-honeypot

Thanks,
Gavin.

**Comment by adubovikov** [comment]
please follow our swagger

**Comment by ghenry** [comment]
Thanks. I was asked to open a ticket here https://groups.google.com/g/homer-discuss/c/a2sukcLKUwM by @lmangani

Apologies if I misread or misunderstood.

Gavin.

**Comment by lmangani** [comment]
HI @ghenry indeed but we meant related to an integration effort with HOMER on either side - nothing seems to be mentioning how in the post, so whenever you are at that stage, please do let us know!

**Comment by ghenry** [comment]
Ah, cool. No problem. I'll look at various things then that you've both mentioned.

**Comment by lmangani** [comment]
I think a HEPSub client should be the first step in integration, allowing HOMER people to query the SentryPeer API interactively
We already have a caching HEPSub API client for [APIBAN](https://github.com/sipcapture/hepsub-apiban) you could potentially and adapt just to get started

**Comment by ghenry** [comment]
Thanks. Will check it out.

**Comment by ghenry** [comment]
Hi @lmangani,

I've finally released https://sentrypeer.com !!

About SentryPeerHQ -> https://sentrypeer.com/about

https://github.com/SentryPeer/SentryPeerHQ

I'll look to start this integration now.

Thaks.
