### ISSUE TITLE
Add support for automatic redirect to sso idp provider

### ISSUE THREAD

**Issue by sudomoke** [sipcapture/homer#520]
When visiting the homer application, it would be ideal if end-users were automatically redirected (skipping the homer7 login screen) to initiate the oauth2 authentication. I would like to request that a configuration file item be added to support configuring this behavior when enabling sso.

**Comment by adubovikov** [comment]
@AlexeyOplachko can you please check it ?

**Comment by AlexeyOplachko** [comment]
Implemented in dev.
You can bypass redirect if needed if you go through 
yourdomain/direct-login

**Comment by kYroL01** [comment]
@AlexeyOplachko can we close this ticket ?

**Comment by kYroL01** [comment]
Implemented and resolved

**Comment by sudomoke** [comment]
What config value turns this on?
