### ISSUE TITLE
Disable showing RTCP as the default setting

### ISSUE THREAD

**Issue by lmangani** [sipcapture/homer#523]
### Discussed in https://github.com/sipcapture/homer/discussions/522

<div type='discussions-op-text'>

<sup>Originally posted by **Gasmanz** February  1, 2022</sup>
Does anyone know if it's possible to disable showing the RTCP messages in the SIP Flow by default. Having to do this everytime I look at a SIP Flow is very annoying after the 100th time. For me the RTCP details are rarely used in call investigations. In fact it would be good to have the ability to set the defaults for any of the flow display parameters.

Thanks in advance.</div>

**Comment by lmangani** [comment]
@AlexeyOplachko could you take a look and confirm the persistence state of the protocol selectors?

**Comment by AlexeyOplachko** [comment]
Checked on our setup, settings of protocol selection does persist, and also default value for RTCP is off. 
@Gasmanz can you go to Preferences, Reset, and click on Clear User Local Data and try replicating your issue again? Maybe your localstorage got corrupted somehow and isn't being overwritten.
