### ISSUE TITLE
Please publish packages for centos stream 8 and stream 9

### ISSUE THREAD

**Issue by ruben-herold** [sipcapture/homer#526]
hi,

it would be nice if you could publish packages for centos stream 8 and centos stream 9.
Centos8 is dead so you can remove it.

**Comment by lmangani** [comment]
@ruben-herold we have no plans for stream, but we're welcoming any PR to support terrible operating systems :)

**Comment by ruben-herold** [comment]
Where can I find the repo with the spec files an build configurations?

**Comment by adubovikov** [comment]
sorry, just short update - we push the package to el/8 , so you can take that repository
