### ISSUE TITLE
Cannot find CFLOW_HPORT setting for homer 7

### ISSUE THREAD

**Issue by Josh-vxt** [sipcapture/homer#529]
Hi I've been searching all over this repo and I cannot seem to find the CFLOW_HPORT setting for Homer 7, is this something that is specific to [Homer 5](https://github.com/sipcapture/homer-api/blob/10903b08d99a6e02672b4a8c2d0cfe87b800a887/api/preferences_example.php#L8)?

Furthermore is there a similar setting like what is described in this thread of removing duplicate packets.
https://groups.google.com/g/homer-discuss/c/SwbV4fPfVqA

We are quite new to Homer so just trying to get our heads around everything.

Thanks in advance

**Comment by adubovikov** [comment]
@Josh-vxt you have special params on the right corner of your call flow dialog

![Screenshot from 2022-03-17 10-48-11](https://user-images.githubusercontent.com/4513061/158782771-07aa3ab2-f1b2-4b04-abc1-b720f07c8a9e.png)
w

**Comment by Josh-vxt** [comment]
How are those settings able to remove duplicate packets?

> Furthermore is there a similar setting like what is described in this thread of removing duplicate packets.
https://groups.google.com/g/homer-discuss/c/SwbV4fPfVqA

**Comment by adubovikov** [comment]
these are two different cases: CFLOW_HPORT - an option how to display packets on the call flow dialog. About the packet deduplication please check this settings: https://github.com/sipcapture/homer-app/blob/master/etc/webapp_config.json#L76-L79
