### ISSUE TITLE
Webhomer "Capture node" search not working

### ISSUE THREAD

**Issue by trideeindhoven** [sipcapture/homer#53]
When i go to "Search" and search for packets, i see many packets (which is expected and good). But when i fill out a "Capture node" (as seen in the column "node"), no results are visible. I confirmed this issue with at least one other user of webhomer. As i am using webhomer for multiple SIP-servers with medium traffic, selecting a single capture node immensely reduces the results.
I am using the latest git version of webhomer.

![webhomer1](https://cloud.githubusercontent.com/assets/9008122/7472279/342f5122-f331-11e4-87d6-b9a356399527.png)

**Comment by adubovikov** [comment]
normaly it should be concat of name of capture node (mysql table) + captagent ID,
but ok, I have changed to full format. Please check

https://github.com/sipcapture/homer/commit/f7ce7506e51a45a0dc006098588456c034b97211

**Comment by trideeindhoven** [comment]
I have checked the functionality and it is working now! Before capt12001 or capt1:2001 did not work. Now capt1:2001 DOES work! Thank you very much for the very fast response!
