### ISSUE TITLE
Homer UI not showing logs

### ISSUE THREAD

**Issue by getrahulchauhan** [sipcapture/homer#533]
Hello,

I have new in homer , and i installed homer 7.10.18, homer-app service and heplify-server services is working fine but i can't see any logs on web.

My server have : -
Asterisk 13.17.2
Homer App UI : - 7.10.18
Homer-app version: - homer-app 1.4.35.
postgresql -12

homer_data=# select * from hep_proto_1_call;
id | sid | create_date | protocol_header | data_header | raw
----+-----+-------------+-----------------+-------------+-----
(0 rows)

/etc/asterisk/hep.conf

[general]
enabled = yes ; Enable/disable forwarding of packets to a
; HEP server. Default is "yes".
;capture_address = 192.168.1.1:9061 ; The address of the HEP capture server.
capture_address = 10.10.0.17:9060
capture_password = foo ; If specified, the authorization passsword
; for the HEP server. If not specified, no
; authorization password will be sent.
capture_id = 1234 ; A unique integer identifier for this
; server. This ID will be embedded sent
; with each packet from this server.
uuid_type = call-id

Please help, also i wanted to know whether homer will works with asterisk chan_sip module?

**Comment by husam212** [comment]
You must load `res_hep_pjsip` or `res_hep_rtcp` for HEP to work in Asterisk, currently there's no support for `chan_sip` module.

**Comment by kYroL01** [comment]
@getrahulchauhan follow the suggestion that @husam212 wrote here. 
Thanks
