### ISSUE TITLE
packages for arm64

### ISSUE THREAD

**Issue by davehorton** [sipcapture/homer#534]
I've been installing the homer webapp and heplify-server from the binary packages, and this has worked fine on amd64 architecture.  I'm bringing up some systems on AWS Graviton processors now, and realized there are no packages published for arm64.  Would this be possible?

**Comment by kYroL01** [comment]
Hello @davehorton we need first to validate this on ARM system before publish.
Thank you and sorry for the late answer

**Comment by marcocajon** [comment]
Hey guys, were these published?

**Comment by lmangani** [comment]
We have some [beta multi-arch images](https://github.com/sipcapture/heplify-server/pkgs/container/heplify-server/213658839?tag=1.59.7-multiarch) you can try looking for feedback: 

```
ghcr.io/sipcapture/heplify-server:1.59.7-multiarch
```
