### ISSUE TITLE
Blank QoS tab and UA Report in Flow tab

### ISSUE THREAD

**Issue by solarmon** [sipcapture/homer#536]
Hi,

Homer 7.10.18
rtrpproxy 2.2.alpha.d5b7b4c4

I have set up rtpproxy to sent RTCP captures to Homer. This is working in that the packets do get to Homer.

However, for some calls (not all calls) I have this situation. In the QoS tab, it is empty/blank:

![image](https://user-images.githubusercontent.com/46369787/163202327-67ac727d-c000-4ebd-a04a-36e5c325e0ed.png)

In the Flow tab, I see a "UA Report". The IP are that of each media endpoint. Note the timestamp of this UA Report:

![image](https://user-images.githubusercontent.com/46369787/163202432-cdf8177f-26c3-4b9b-915e-18c8baab5703.png)

In the Log tab, there are RTCP packets, but they start after the timestamp of the UA Report:

![image](https://user-images.githubusercontent.com/46369787/163202711-035c14e8-e57c-42ef-8cfc-de07164d6554.png)

Please can you advise what this UA Report is, and when it does appear it causes the QoS tab to be blank.

Thank you.

**Comment by lmangani** [comment]
We need a dataset to reproduce this in order to find the potential issue

**Comment by solarmon** [comment]
@lmangani,

Just tell me what you require, but I cannot expose any sensitive data on a public forum - we we need to agree on how the dataset gets to you.

**Comment by lmangani** [comment]
I'm afraid we cannot work on this privately but should be able to remove the sensitive data very easily in exchange for free support :) We're solving a technical problem and we need technical details. None of the PII apply here (ips, numbers, etc) just session identifiers and details.

**Comment by solarmon** [comment]
OK, I will try to sanitise the data - please can you let me know exactly what you need and how/where to get it from.

**Comment by lmangani** [comment]
If timing in the RTCP reports is the issue, you can try boost your mapping lookup range to catch them:
```
    {
        "source_field": "data_header.callid",
        "lookup_id": 5,
        "lookup_profile": "default",
        "lookup_field": "sid",
        "lookup_range": [
            -300,
            2000
        ]
    },
```

**Comment by solarmon** [comment]
Do you mean time/date stamp on the rtpproxy and homer servers? I've just checked and the clocks are within a second of each other.

Or do you mean the timing difference between the RTCP endpoints themselves?

Anyways, I did change the range to beteen -600 and 400:
```
 {
        "source_field": "data_header.callid",
        "lookup_id": 100,
        "lookup_profile": "default",
        "lookup_field": "sid",
        "lookup_range": [
            -600,
            400
        ]
    },
    {
        "source_field": "data_header.callid",
        "lookup_id": 5,
        "lookup_profile": "call",
        "lookup_field": "sid",
        "lookup_range": [
            -600,
            400
        ]
    },
```

I've made 10 test calls so far and none of them has show the issue that was seen before and I see both QoS stats for both legs of the call.

I mention both legs of a call because the issue seems to be occurring on the inbound leg of the call. So do you think there is a timing difference between our RTCP endpoint and the SIP provider RTCP endpoint that would cause such an issue?

**Comment by solarmon** [comment]
And just typical...as soon as I posted the last comment and made another test call, the same issue has occurred. Again, on the inbound SIP leg of the call coming from the SIP provider.

**Comment by lmangani** [comment]
Let us know if you spot the difference between the good and bad scenario

**Comment by solarmon** [comment]
I'm doing the exact same test call every time. At the moment It just seems intermittent/random as to whether it has this display issue or not.

What would help me troubleshoot further is understanding what this "UA Report" is why/when does it appear in the flow view. It is not a SIP method, and the flow view is showing it with the IP of the media endpoints. So it must be to do with how it analyse the RTCP packets?

**Comment by lmangani** [comment]
Check if your BYE or 200 OK contain a User-Agent report (X-RTP-Stats, P-RTP-Stat) or sends RTCP-XR or whatnot

**Comment by solarmon** [comment]
I don't see anything in the SIP packets.

Doing a capture on the rtpproxy, I see that the first RTCP packet received is a "Receiver Report" (with Source Description), the rest of the RTCP packets are "Sender Report".

The Receiver Report packet matches exactly the timestamp of the "UA Report" that appears in Homer.

![image](https://user-images.githubusercontent.com/46369787/163271985-0f81aefa-7e25-4872-8ba5-6905af0b78e3.png)

Could this Receiver Report be messing up the RTCP stats in the QoS tab?

**Comment by solarmon** [comment]
On Homer, in the Message tab of the call, this UA Report packet seems to appear as:

![image](https://user-images.githubusercontent.com/46369787/163272632-e745e3b1-b08d-4483-85fc-37a07e25933e.png)

Which matches the timestamp of the Sender Report in the rtpproxy capture:

![image](https://user-images.githubusercontent.com/46369787/163272829-00ababf7-7a1b-4a59-beff-4ff8929353d1.png)

**Comment by solarmon** [comment]
This is the rtpproxy capture, filtered for just RTCP:

![image](https://user-images.githubusercontent.com/46369787/163273933-a266388e-9e7a-4870-9c39-ae00a7eb7deb.png)

**Comment by lmangani** [comment]
I'm sorry but we can't work with screenshots. It's hard to even guess what the issue might be based on the provided info.

**Comment by solarmon** [comment]
I found that you can filter by SIP and RTCP in the Message tab:

![image](https://user-images.githubusercontent.com/46369787/163274700-3c9ec11c-07b5-45b9-9c28-45e7ec23384c.png)

So this first packet doesn't seem to be classed as Method or Type of RTCP?

**Comment by solarmon** [comment]
Looking back at the captures in Homer of the calls (and filtering the call view just to show RTCP payload type) that do and don't have this issue, the common thing is that when there a UA Report (RTCP packet type of Receiver Report), the QoS tab is empty; and when there is no UA Report then the QoS tab is working as expected.

Something about the UA Report (RTCP packet type of Receiver Report) seems to be breaking the QoS tab and RTCP stats analysis.

**Comment by lmangani** [comment]
As mentioned, you need to share the actual data for us to debug, there's nothing we can do with the theory - I'm sorry.

**Comment by solarmon** [comment]
What data do you require?

**Comment by lmangani** [comment]
Up to your judgement, we need to see everything that's needed in order to replicate the same issue.

**Comment by solarmon** [comment]
Maybe the RTCP HEP capture packets itself? And just the one for the Receiver Report?

**Comment by lmangani** [comment]
But how would be then able to correlate them with a session we do not have? those all cross-reference.
If you're not willing to share the full traces to reproduce it (privately or censored) we won't be able to debug this

**Comment by solarmon** [comment]
@lmangani 

Please find attached a sanitised version of the RTCP HEP captures coming from rtpproxy. The first packet is of type 201 (Receiver Report) which seems to cause the display issue in the QoS tab.
(attachment removed)

**Comment by solarmon** [comment]
@lmangani 

Looking at the HEP capture and using the HEP decoder from https://github.com/sipcapture/hep-wireshark/tree/master/lua

The only issue I can see (although, the decoder doesn't say anything about) is that the Encapsulated Payload content for the Receiver Report packet isn't quite JSON format valid - the last item (report_count) ends with a comma character:

![image](https://user-images.githubusercontent.com/46369787/163391264-ebbdc91d-08b7-4f12-9f88-f3b5af1dd95a.png)

Could this be the reason for the issue?

**Comment by solarmon** [comment]
I think I have found the bug in the rttproxy rtcp hep module:

Line 193 doesn't have the comma character:

https://github.com/sippy/rtpproxy/blob/b9d7b4ced2e9797f7d5d3f033af288fbc1aaecd8/modules/acct_rtcp_hep/rtcp2json.c#L193

But line 217 seems to have this comma character:

https://github.com/sippy/rtpproxy/blob/b9d7b4ced2e9797f7d5d3f033af288fbc1aaecd8/modules/acct_rtcp_hep/rtcp2json.c#L217

**Comment by lmangani** [comment]
@solarmon sounds like a very plausible cause! nice finding!

**Comment by solarmon** [comment]
@lmangani 

I fixed the source code, recompiled rtpproxy and the modules, and that seems to have fixed the issue:

Homer now processed the packet correctly and the QoS tab shows RTCP stats:

![image](https://user-images.githubusercontent.com/46369787/163409828-f136526a-5ce2-41f8-bdcb-bed5c84c857a.png)

You might want to look at making Homer handle such malformed packets more gracefully. Or at least give a clear indication that the packet is malformed.

Thank you for you support, it is very much appreciated.

I suppose I should now raise a bug report on the rtpproxy Github!
