### ISSUE TITLE
Feature Request: Grafana QoS RTCP dashboard - heplify_rtcp_jitter and target_name label combination?

### ISSUE THREAD

**Issue by solarmon** [sipcapture/homer#539]
Hi,

I have RTCP HEP packets sent from rtpproxy in to Homer, which feeds in to Grafana.

I would like to customise the QoS RTCP dashboards so that I can get those stats on an individual or group of target hosts (as defined  by PROMTARGETIP and PROMTARGETNAME for Homer)

In other dashboards that have queries that use the `heplify_method_response ` label, I am able to use a `target_name ` label combination to specify what targets to scope the query for. For example:

```
(sum(increase(heplify_method_response{target_name=~"(HOST1|HOST2|HOST3)", method="INVITE", response="200"}[5m])))
```

However, for the QoS RTCP dashboard query, it uses the `heplify_rtcp_jitter` label, but there is no `target_name ` label combination allowed for it. So it cannot be scoped for certain targets.

Is it possible to have a `heplify_rtcp_jitter` and `target_name ` label combination to be able to create specific QoS RTCP stats for certain individual or groups of target hosts?

**Comment by gudge25** [comment]
same here
heplify_rtcp_packets_lost{instance="heplify-server:9096", job="heplify-server", node_id="1234", target_name="unknown"}

target_name="unknown" always

**Comment by lmangani** [comment]
Hard to tell without knowing what your signaling looks like and without knowing how you configured aliases.

**Comment by gudge25** [comment]
sorted by usign 
`      - "HEPLIFYSERVER_PROMTARGETIP=X.X.X.X"
       - "HEPLIFYSERVER_PROMTARGETNAME=Label"`
       and restarted  
       how i can see directions for  rtcp and  _response

**Comment by lmangani** [comment]
So you did NOT have any PROMTARGETIP or PROMTARGETNAME defined to begin with? I assumed you did. Nice!
