### ISSUE TITLE
Correlating two incoming legs in Freeswitch

### ISSUE THREAD

**Issue by uppuluriaditya** [sipcapture/homer#541]
Hi,
Is there a way to correlate two incoming legs to freeswitch via ESL? We have a setup where, Freeswitch receives INVITE from two users. I want to correlate both the legs before bridging. May i know how to do that?

Thanks in advance

**Comment by adubovikov** [comment]
You can insert the X-Cid to the second leg and after correlate it in UI using correlation script. The example is in our wiki

**Comment by lmangani** [comment]
And here's the link: https://github.com/sipcapture/homer/wiki/Examples%3A-FreeSwitch#b2bua-correlation
Just emulate the same logic with your ESL commands and it should work fine.

**Comment by uppuluriaditya** [comment]
> using correlation scrip

Thank you for the example. But in my setup, i have two incoming calls. So setting it like above example, will set two different correlation IDs to two incoming calls (As Call-IDs are different for both the legs). isn't it?

**Comment by lmangani** [comment]
@uppuluriaditya that's totally up to you, we have nothing to do with your call logic - each call should point at the other.
