### ISSUE TITLE
Unable to configure Alarm widget inside Homer7-UI

### ISSUE THREAD

**Issue by akhatkz** [sipcapture/homer#544]
Hello, on previous Homer5 -UI, there was and still there, examples on alarm route configuration inside sipcapture.kamailio configuration. 
However, I can't find example how to configure "alarm widget" on Homer7-UI.

Is there any examples how to configure "alarm widget" inside Homer7-UI? Thank you.

![image](https://user-images.githubusercontent.com/108856713/177714572-7ee887dc-fec2-4ee3-85b3-015c78859947.png)

Regards,

**Comment by lmangani** [comment]
Hello @akhatkz alerting in HOMER 7 has been moved to Grafana which is much more capable and flexible. 
The old widget is on the way to being decommissioned.

**Comment by lmangani** [comment]
Please star the project and if possible, avoid double posting the same issue on the mailing-list.

**Comment by akhatkz** [comment]
Thank you [lmangani](https://github.com/lmangani) for your answer. I appologies for double posting.

regards,
a .kz
