### ISSUE TITLE
Homer7 user data location

### ISSUE THREAD

**Issue by BaldingVoIP-engineer** [sipcapture/homer#545]
Hi All, 

More a question than anything. 

I am using SaltStack to install and config Homer7 but I am having trouble finding the location where to drop a file with a list user details for the web-app login. 

Everything works and I am installing via the bootstrap method (Quick Install) but I want to drop a file to overwrite the default log in with a list of users. 

Does anyone know where this lives? I need to view it and construct a file that matches it so I can drop it onto the estate of Homer boxes I have. 

Many thanks.

**Comment by lmangani** [comment]
The data is in the database and provisioned by [homer-app](https://github.com/sipcapture/homer-app#initialization)
This step is not mandatory with the exception of the admin user which is managed/reset using this method.

Your users should be provisioned through the Admin APIs or by replicating the method above.

**Comment by BaldingVoIP-engineer** [comment]
Thanks @lmangani 

I will look at the Admin API as that would be easier for me to hit.
