### ISSUE TITLE
FreeSWITCH Capture Agent over TCP?

### ISSUE THREAD

**Issue by hnimminh** [sipcapture/homer#548]
Does [FreeSWITCH Capture Agent](https://github.com/sipcapture/homer/wiki/Examples%3A-FreeSwitch) support send package over to **TCP**?

From  https://github.com/freeswitch/sofia-sip/blob/060e3a294a6e51276e806adf4547cd69e7186fe9/libsofia-sip-ua/tport/tport_logging.c#L159 only **UDP** is support.

Do we have plan to support **TCP**?

**Comment by lmangani** [comment]
Hello @hnimminh unfortunately it does not (feel free to open a request on their repository) but you can use our agents or an advance HEP proxy such as OpenSIPS as a HEP relay between UDP and TCP protocols. Hope this helps!

**Comment by hnimminh** [comment]
Thanks @lmangani , I thought that code belong to sipcapture.

**Comment by khorsmann** [comment]
@hnimminh you can also send captures via Kamailio to Homer. And if you want you can use the golang hfp proxy to send it to Homer https://github.com/ivlovric/HFP
