### ISSUE TITLE
log not showing

### ISSUE THREAD

**Issue by 9-4-6** [sipcapture/homer#553]
config.js content:

var config = {
  hep_config: {
    debug: true,
    HEP_SERVER: '192.168.16.133',
    HEP_PORT: 9060
  },
  esl_config: {
    debug: true,
    ESL_SERVER: '192.168.16.133',
    ESL_PORT: 8021,
    ESL_PASS: 'ClueCon',
    HEP_PASS: 'multipass',
    HEP_ID: 2222,
    report_call_events: true,
    report_rtcp_events: true,
    report_qos_events: true
  },
  logs_config: {
    debug: true,
    HEP_PASS: 'multipass',
    HEP_ID: 2222,
    logs: [
     {
       tag : 'opus_decoder',
       host : '192.168.16.133',
       pattern: ['^([^ ]*) .*Opus decoder stats',
                 '^([^ ]*) .*[DEBUG]'],
       path : '/usr/local/freeswitch/log/freeswitch.log'
     }
   ]

  }

};

**Comment by lmangani** [comment]
@CollectBugs please do not double-post. Update either of your issues with the requested details to get help

_you did not even bother specifying you're using hepgen here, so I doubt this will be the correct place_

Please use the original issue you opened.

**Comment by CollectBugs** [comment]
ok

**Comment by 9-4-6** [comment]
> @CollectBugs please do not double-post. Update either of your issues with the requested details to get help
> 
> _you did not even bother specifying you're using hepgen here, so I doubt this will be the correct place_
> 
> Please use the original issue you opened.

ok, link https://github.com/sipcapture/hepipe.js/issues/30
