### ISSUE TITLE
homer  postgres defualt passward and username？

### ISSUE THREAD

**Issue by 9-4-6** [sipcapture/homer#554]
homer  postgres defualt passward？

**Comment by lmangani** [comment]
starring the project?

**Comment by 9-4-6** [comment]
> starring the project?

yes，I want to connect to the database，I checked the configuration
Enter the user, the password is wrong
![image](https://user-images.githubusercontent.com/32507511/189067021-9ec76d41-79ae-41e3-a438-16faeeb379d8.png)

![image](https://user-images.githubusercontent.com/32507511/189067177-3c420fbe-4307-4e87-be3d-db8124b08fde.png)

**Comment by lmangani** [comment]
1) star the project - give support to get support
2) no default. the postgres DB password is randomly generated by the bash installer. check your install log.

**Comment by 9-4-6** [comment]
> 1. star the project - give support to get support
> 2. no default. the postgres DB password is randomly generated by the bash installer. check your install log.
1.ok
2.I know, the password and username are not checked in this file (/etc/heplify-server.toml)? I can't connect to the database with the username and password inside

**Comment by lmangani** [comment]
> Please star this repository to motivate the developers and to get higher priority! ⭐

**Comment by 9-4-6** [comment]
> > Please star this repository to motivate the developers and to get higher priority! ⭐

I've already done it, right?
![image](https://user-images.githubusercontent.com/32507511/189080322-4f40332c-3fc2-4e66-8653-cfeb7691b72a.png)

**Comment by 9-4-6** [comment]
> > Please star this repository to motivate the developers and to get higher priority! ⭐



> > Please star this repository to motivate the developers and to get higher priority! ⭐

why did you close this question for me

**Comment by lmangani** [comment]
The question was answered. The passwords are generated during setup. The other settings are open for editing.
The actual configuration is accessible to you only, so we do not know what could have been misconfigured.

**Comment by CollectBugs** [comment]
> The question was answered. The passwords are generated during setup. The other settings are open for editing. The actual configuration is accessible to you only, so we do not know what could have been misconfigured.

**Installation method：**
wget https://github.com/sipcapture/homer-installer/raw/master/homer_installer.sh
chmod +x homer_installer.sh
./homer_installer.sh

1.I did not set a password when installing homer, and did not initialize the database。
2.Regarding the configuration of the password, there is no change

**Comment by 9-4-6** [comment]
> The question was answered. The passwords are generated during setup. The other settings are open for editing. The actual configuration is accessible to you only, so we do not know what could have been misconfigured.

 1.I understand your idea
 2.However, the password of the configuration file is the password that was initialized during installation. If there is no change, you cannot log in
3.The configuration file has not changed

**Comment by lmangani** [comment]
Log in.... are you perhaps trying to use the DB auth to login to the UI instead of `admin/sipcapture`?

**Comment by 9-4-6** [comment]
> Log in.... are you perhaps trying to use the DB auth to login to the UI instead of `admin/sipcapture`?

1.Use the DB auth to login to the UI and report an incorrect password （homer_user/ay8zFGx6ZZM00ErOj78hOhXPQ）
2.Install the homer initialization password in this configuration（/etc/heplify-server.toml）

![image](https://user-images.githubusercontent.com/32507511/189095991-915047f4-b3e3-459c-9f5b-9bdd20f69c29.png)
![image](https://user-images.githubusercontent.com/32507511/189096073-399d1ab4-ba35-4716-afdb-1b881e7e9c83.png)
![image](https://user-images.githubusercontent.com/32507511/189097099-4c4d884c-ed72-465e-af2f-db1e025ce40f.png)

**Comment by 9-4-6** [comment]
> Log in.... are you perhaps trying to use the DB auth to login to the UI instead of `admin/sipcapture`?

hello，thank for your reply
the issue has been resolved
correct command connection：
psql -h 127.0.0.1 -p 5432 -d homer_data -U homer_user
