### ISSUE TITLE
About the homer configuration problem

### ISSUE THREAD

**Issue by 9-4-6** [sipcapture/homer#555]
### **1.Please explain the field descriptions in heplify-server.tom**
 SIPHeader
 DBPartLog  
 DBPartSip    
 DBPartQos             = "6h"
 DBDropDays            = 14
 DBDropDaysCall        = 0
 DBDropDaysRegister    = 0
 DBDropDaysDefault     = 0
 DBDropOnStart         = false
 DBUsageProtection     = true
 DBUsageScheme         = "percentage"
 DBPercentageUsage     = "80%"
 DBMaxSize             = "30MB"
 Dedup                 = false
 DiscardMethod         = []
 AlegIDs               = []
 CustomHeader

**Comment by kYroL01** [comment]
Hi @CollectBugs 
This is a short description of these variables https://github.com/sipcapture/homer/wiki/HEPLIFY-SERVER-Settings
Thank you
