### ISSUE TITLE
Failed to add dashboard to homer UI

### ISSUE THREAD

**Issue by 9-4-6** [sipcapture/homer#556]
Homer UI adds dashboard, upload json file and drag and drop are unsuccessful
step1
![image](https://user-images.githubusercontent.com/32507511/189264398-c8971102-4a01-423c-9607-27af4c2573b7.png)

step2：
![image](https://user-images.githubusercontent.com/32507511/189264429-7cc4feba-a832-475f-a7ce-d52e20f83ff7.png)

**Comment by AlexeyOplachko** [comment]
Thanks for reporting this, we'll look into it 👍

**Comment by kYroL01** [comment]
This was implemented. I will close the ticket.
Reopen if you still think the bug is not resolved correctly.
Thank you
