### ISSUE TITLE
Missing Details tab from message window when opened from Flow ro Messages view

### ISSUE THREAD

**Issue by solarmon** [sipcapture/homer#568]
Hi,

I have come across a display issue/bug. This issue occurs on latest version 7.10.23 of homer-webapp.

The issue is that the Details tab/view for a message only appears when you open the message from within the query results window - for example:

![image](https://user-images.githubusercontent.com/46369787/205071190-cb04c223-1d6e-4c27-a1ae-ea1b8b145e06.png)

The same message (same message ID) when opened up from the Flow or Messages view, does not have the Details tab/view (I've highlighted in yellow where it should be):

![image](https://user-images.githubusercontent.com/46369787/205071240-c91c8fea-0459-4a4e-b4bd-ca3b805fe497.png)

I assume this is a display bug and the Details tab should be available for any message view, regardless of how/where it is opened on?

Thank you.

**Comment by lmangani** [comment]
Moved issue to sipcapture/homer repo

**Comment by adubovikov** [comment]
fixed in this commit https://github.com/sipcapture/homer-ui/commit/7456e7e166130594b4f48b6ea64a6592addad73c
