### ISSUE TITLE
ERROR: do_action: bad from dropping packet

### ISSUE THREAD

**Issue by jvb187** [sipcapture/homer#57]
I am receiving the following errors after Kamailio has been running for about 30 seconds:

Jun 10 09:32:56 homer104 ./kamailio[13827]: ERROR: sipcapture [sipcapture.c:1571]: sip_capture(): ERROR: do_action: bad from dropping packet
Jun 10 09:32:56 homer104 ./kamailio[13827]: ERROR: db_mysql [km_dbase.c:121]: db_mysql_submit_query(): driver error on query: Table 'homer_db.sip_capt' doesn't exist
Jun 10 09:32:56 homer104 ./kamailio[13827]: ERROR: <core> [db_query.c:235]: db_do_insert_cmd(): error while submitting query

These errors repeat until I stop the Kamailio service, and no calls are captured once this occurs. It appears this happens because there is a SIP message with something that Kamailio does not like in the FROM header. Is there any way to identify what it does not like, or to ignore what it considers bad headers and insert them anyway?

**Comment by adubovikov** [comment]
please iupgrade kamailio's sipcapture to this one:

https://github.com/adubovikov/kamailio
https://github.com/adubovikov/kamailio/tree/master/modules/sipcapture

or as workaround, please replace all sip_capture() function in your kamailio.cfg to sip_capture("sip_capture");

Wbr,
Alexandr

**Comment by adubovikov** [comment]
this is valid only for H 3.x

for H5 you should use this config:

https://github.com/sipcapture/homer-api/blob/master/examples/sipcapture/kamailio.cfg

**Comment by jvb187** [comment]
The upgraded sipcapture worked great.

Thank you!
