### ISSUE TITLE
API Auth Error Homer 7 

### ISSUE THREAD

**Issue by PJ111288** [sipcapture/homer#570]
Hello Sir,

Need help to login through API. I am trying to use api but unable to authenticate and getting following response or error.

curl -v --cookie "HOMERSESSID=tcuass65ejl2lifoopuuurpmq7; path=/" -X POST -H "Content-Type: application/json" -d '{"username":"admin","password":"password123"}' http://localhost:9080/api/v3/session

Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying ::1:9080...
* Connected to localhost (::1) port 9080 (#0)
> POST /api/v3/session HTTP/1.1
> Host: localhost:9080
> User-Agent: curl/7.74.0
> Accept: */*
> Cookie: HOMERSESSID=tcuass65ejl2lifoopuuurpmq7; path=/
> Content-Type: application/json
> Content-Length: 48
>
* upload completely sent off: 48 out of 48 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Content-Type: application/json; charset=UTF-8
< Vary: Origin
< Date: Wed, 07 Dec 2022 12:36:46 GMT
< Content-Length: 29
<
{"message":"Login required"}
* Connection #0 to host localhost left intact

**Comment by idanam-del** [comment]
hey @PJ111288 i have the same isse. Have you found a solution?

**Comment by lmangani** [comment]
The API needs an authentication token and not a user:password. You can generate tokens and explore the API authentication directly from the HOMER 7 UI in the Admin section.
