### ISSUE TITLE
SIP messages out of order

### ISSUE THREAD

**Issue by jrozhon** [sipcapture/homer#572]
Hi, on a fresh-installed Homer 7 (via apt repository), I get some of the SIP messages out of the expected order. I checked that there was a similar issue already reported about 3 years ago, but in my case the timestamps are already wrong (see figure).

I have heplify-server 1.59.3 and Asterisk 18.14 with hep module loaded and configured.

I have also checked the system time on both servers.

Any idea would be appreciated. Thanks.

![homer](https://user-images.githubusercontent.com/12800857/210066037-ec0e56a1-ba5a-43fe-9df6-4bcec9f82a55.png)

**Comment by lmangani** [comment]
> I have heplify-server 1.59.3 and Asterisk 18.14 with hep module loaded and configured.

This could have multiple causes, and a single message doesn't tell much.
In HEPv3 timestamps are marked by the sender. Is the time syncronized between your hosts?

**Comment by jrozhon** [comment]
Thanks for such a quick response. Yes, both have NTP up and running and I checked it manually as well. Moreover, all messages are from the same Asterisk server so in case of misaligned time I would expect for all messages to be slightly off but in correct order.

**Comment by lmangani** [comment]
Accurate timestamping is only available in HEPv2/3 and its designed to avoid exactly this scenario. If you're not doing any TLS on your instance, just replace the internal res_hep with hepfliy to confirm if that's the case.

**Comment by adubovikov** [comment]
just to be sure, do you have HEP only from your asterisk or do you have on one box asterisk and another has heplify client ? (not server)

**Comment by adubovikov** [comment]
because the 401 has rounded milliseconds timestamp: 621000 - the last 000 should be bigger than 339. Also, please check the capture_id and the capture IP on 401 and INVITE

**Comment by jrozhon** [comment]
As a "client" I have Asterisk with res_hep/res_hep_pjsip. No heplify there or anywhere else yet, but will try it after business hours as per Lorenzo's advice.

Yes, I can also see the rounding, but can't really figure where it happens as it seems that it is done for incoming messages and not for the outgoing ones.

I am inclined to think that it has something to do with res_hep in Asterisk, though.

**Comment by jrozhon** [comment]
Capture IDs are ok, both are 1.

**Comment by jrozhon** [comment]
So, heplify (client) sends the timestamps without rounding, so I guess it is clear now. Thank you both for support.

**Comment by lmangani** [comment]
Thanks for confirming @jrozhon we'll see if's even possible to patch the native HEP driver but we always suggest the passive approach when encryption is not at play. Welcome to the club!
