### ISSUE TITLE
Homer 7 - SIP NOTIFY not populated in PostgreSQL database.

### ISSUE THREAD

**Issue by jonhvoxbox** [sipcapture/homer#576]
Hi Guys,

We are running heplify-server ver 1.59.3 and homer 7 and have an issue with SIP NOTIFY not being added to the database.

I can see they are presented from openSIPS on the correct port to the heplify-server as HEPv3, and the NOTIFY's can be seen incrementing in the metrics, however not seeing any in the postgres DB and therefore the UI.

Is this a known issue?

Thanks

Jon

**Comment by kYroL01** [comment]
Hi @jonhvoxbox 
Are you using the `hep_module` for OpenSIPS to send HEP traffic, if I understood correctly, right ?
Did you see if `heplify-server` is then sending traffic to Postgres DB ?

Thank you

**Comment by jonhvoxbox** [comment]
Hi @kYroL01  thank you for the reply.

Yes using the hep_module, and heplify-server is sending other methods to Postgres DB (INVITE/REFER/INFO) it just wont send the NOTIFY into db. 
Any ideas how to debug? It was included in the DiscardMethod parameter but I removed it and restarted but still dont see it in DB but see it in metrics.

Didnt know if I need to check anywhere else or best approach to debug?

Thanks!

**Comment by lmangani** [comment]
@jonhvoxbox are you searching in the "SIP - default" partition? Notify, Pubish, Options (and in general any out-of-band method) will not be stored alongside calls, for obvious reasons. Give it a try with a smart search widget:

![image](https://user-images.githubusercontent.com/1423657/219654552-79031790-de22-4455-9c6f-01c5b6949844.png)

**Comment by jonhvoxbox** [comment]
Hi @lmangani  unfortunately when I try the SIP -default partition it isnt returning anything. Also for context this is an in-dialog NOTIFY in response to a REFER I am trying to grab. I am just perplexed as to why I cant find in Database.  And unfortunately the smarch search widget is not returning anything.

**Comment by lmangani** [comment]
I can't reproduce this. Feel free to provide a PCAP (or HEPGen.js script) to produce the same outcome for testing.

**Comment by jonhvoxbox** [comment]
Hi @lmangani fair enough, can you please confirm the current recommended versions we should be running and will make sure they are also aligned.

Thanks for reply!

**Comment by lmangani** [comment]
Latest release for everything is the recommended setup (since that's what we'll be able to patch and test) for our own components. The rest is less relevant.

**Comment by jonhvoxbox** [comment]
ok thanks @lmangani will do that and reopen if still have issues. Thanks for looking.

**Comment by lmangani** [comment]
Thanks! Let us know what you discover and feel free to reopen anytime.
