### ISSUE TITLE
SIP/2.0 100 Trying displaying before the actual invite

### ISSUE THREAD

**Issue by nbhatti** [sipcapture/homer#58]
On latest git master with FreeSWITCH Version 1.5.15b. `100 Trying` time stamp is actually seen before the original `INVITE`. Could this be Network related or something to do with capture agent? 

    U 2015/06/11 12:40:21.809395 5.9.50.x:5060 -> 144.76.149.x:1255
    SIP/2.0 100 Trying

    U 2015/06/11 12:40:21.809524 144.76.149.x:1255 -> 5.9.50.x:5060
    INVITE sip:441698300860@5.9.50.x SIP/2.0

It shows `12:40:21.809395` for `100 Trying` and `12:40:21.809524` for `INVITE`

**Comment by nbhatti** [comment]
Or could this be because when I get the first INVITE on the switch, it then selects another INVITE to the gateway to establish the call and that's why I don't see the who call legs? Customer, Our Switch and the gateway?

**Comment by adubovikov** [comment]
this was fixed already in the last version of sipcapture module.

https://github.com/kamailio/kamailio/blob/master/modules/sipcapture/
