### ISSUE TITLE
Trying to implement loki search with custom headers

### ISSUE THREAD

**Issue by thomas414** [sipcapture/homer#580]
Hi,

can somebody maybe explain to me how the mapping and correlation in general for homer works? I still don't really understand.

Just to show what i want to achieve:
I have a setup like this:

SOME PROVIDER <-> KAMAILIO <-> FREESWITCH <-> KAMAILIO <-> CLIENTS

The kamailios and freeswitch are already pushing HEP data into homer and that works perfectly.

I have now implemented loki into my setup in order to also view kamailio and freeswitch log. For kamailio this works fine as the SIP Call Ids of the two legs are also in the logs and are automatically in the search string in the UI.

Problem is with Freeswitch, as the key for the logs is the internal uuid. 
My idea was to include X-aleg-uuid and X-bleg-uuid header at freeswitch.

If this is possible and the correct way to do so, please tell me how can i automatically include the aleg-uuid and bleg-uuid in the loki search string?
If not, what would be the correct way?

Thank you in advance!

P.S.: homer-app is version 1.4.47, homer-ui is version 7.10.24 and heplify-server is version 1.59.3

Best regards

**Comment by lmangani** [comment]
Hello @thomas414 it seems you might be possibly mixing up homer's internal session correlation w/ the extranal logs correlation. If this is about logs, then it's really more of a freeswitch preference question. 
It seems you already figured how this works with the Kamailio logs.  For Freeswitch you either have to extract the callid to the logs or use a two step approach (callid to uuid, uuid to logs) but there's no magical way to populate anything in the loki search (aleg-uuid and bleg-uuid, etc) unless HOMER knows about it from the session itself or through extractions. Injecting a X-Log- Header with it might help but it's completely up to your preferences and skills.

**Comment by lmangani** [comment]
Issue closed as this is just a discussion, but feel free to extend if needed.
