### ISSUE TITLE
Can i change default Shema Name

### ISSUE THREAD

**Issue by GokhanAksoynet** [sipcapture/homer#582]
Hello,

Can i change homer5 or homer7 shema name. When i try to send data to another named shema it gives error.

Do i have to use homer5 or homer7?

Thank you.

**Comment by lmangani** [comment]
Happy to answer. Those are presets selectors, not free fields. Only `homer7` is supported, anything else is deprecated. 
Please star this repository if you plan on opening issues and requests ⭐
