### ISSUE TITLE
1.4.47 packages and up on https://packagecloud.io/qxip/sipcapture are broken

### ISSUE THREAD

**Issue by gcecasmithc** [sipcapture/homer#583]
Few issues with 1.4.47 and up packages.

No binary is placed under /usr/local/bin/. "homer-app.service: Failed at step EXEC spawning /usr/local/bin/homer-app: No such file or directory" is thrown when it attempts to start. Creating a symlink between /usr/local/homer/bin/homer-app and /usr/local/bin/homer-app allows it to launch.

webapp_config.json is now named webapp_config.json.example which breaks the homer-installer(https://github.com/sipcapture/homer-installer).

The web UI is unreachable and "remote http://127.0.0.1:3000 unreachable, could not forward: dial tcp 127.0.0.1:3000: connect: connection refused" is thrown. If Grafana is running it simply redirects to the Grafana UI if a valid token is set, if not, "Invalid Basic Auth Header" is thrown. This occurs even if Grafana is disabled in webapp_config.json.

Nothing is shown in the log file or console.

1.4.37 appears to be fine.

**Comment by gcecasmithc** [comment]
Similar issues from the Google group.

https://groups.google.com/g/homer-discuss/c/iF7gjz0at9A - homer-installer not finding webapp_config.json because it is named webapp_config.json.example.

https://groups.google.com/g/homer-discuss/c/6-6C9PI39U8 - Other issues with 1.4.47 and up.

**Comment by gcecasmithc** [comment]
Same issues with 1.4.51.

**Comment by gcecasmithc** [comment]
Crap, please transfer this issue to homer-app. Sorry :(

**Comment by kYroL01** [comment]
Hi @gcecasmithc this could be related to this https://github.com/sipcapture/homer-app/discussions/512

**Comment by kYroL01** [comment]
@gcecasmithc good news - we fixed that here https://github.com/sipcapture/homer-app/commit/2de546f9b6205897a2e5305af3fb163059cea90e
The next release should be ok.

**Comment by adubovikov** [comment]
the release homer-app_1.4.52_amd64 has been published

**Comment by adubovikov** [comment]
Please use homer-app_1.4.53_amd64.deb 

Should be ok now!
