### ISSUE TITLE
Using HOMER to aggregate existing CDRs

### ISSUE THREAD

**Issue by idanam-del** [sipcapture/homer#586]
Hello, i would like to ask if its possible to aggregate multiple CDR sources in DBs using HOMER?

Maybe a better question would be at what cases can i use HOMER to aggregate existing data CDRs or LOGs? If at all.

thank you

**Comment by adubovikov** [comment]
for LOG - you can send right away with HEPID 100 , it will add to the hep_proto_100_default.

For CDR, there is also a way to do this by usin HEPID: 50, but the format should be a JSON
