### ISSUE TITLE
Time Filter doesn't seem to apply correctly

### ISSUE THREAD

**Issue by katurru** [sipcapture/homer#591]
Hello,

We have a new Homer 7 installation capturing with Heplify and we have an strange issue when we are filtering for the last minutes or hours. 
When we filter for the last 5 minutes, it seems to be ok.

![5minutessearch](https://github.com/sipcapture/homer/assets/93181747/97b12de5-afce-44e0-b751-a6a19b280f56)

But when we filter for the last 3 hours, it doesn't matter how we order the results, the interface doesn't show the most recent results. 

![3hourssearch](https://github.com/sipcapture/homer/assets/93181747/6c078156-e9c1-4782-91a4-844866916dee)

We've got the filter timezone set the same as the OS. 

![imagen](https://github.com/sipcapture/homer/assets/93181747/464e488c-8fad-44fc-8393-c1dcf6d59b25)

Homer-app Version: 

Package: homer-app
Version: 1.4.53
Priority: extra
Section: default
Maintainer: QXIP SIPCapture <support@sipcapture.org>
Installed-Size: 38,4 MB
Provides: homer-app
Replaces: homer-app
Homepage: http://qxip.net
Download-Size: 22,2 MB
APT-Manual-Installed: yes
APT-Sources: https://packagecloud.io/qxip/sipcapture/debian bullseye/main amd64 Packages
Description: HOMER 7 WebAPP + API

Heplify version:

Package: heplify
Version: 1.65.2
Priority: extra
Section: default
Maintainer: QXIP Sipcapture <support@sipcapture.org>
Installed-Size: 8.093 kB
Provides: heplify
Replaces: heplify
Homepage: http://qxip.net
Download-Size: 3.337 kB
APT-Manual-Installed: yes
APT-Sources: https://packagecloud.io/qxip/sipcapture/debian bullseye/main amd64 Packages
Description: HEP Capture Agent for HOMER/SIPCAPTURE

Could you please help us?

Thanks!

**Comment by katurru** [comment]
Sorry, my mistake. I didn't set query limit. 

Thanks

**Comment by lmangani** [comment]
Well done figuring this was limit induced & welcome to our community @katurru
