### ISSUE TITLE
FreeSWITCH Capture Agent - RTCP

### ISSUE THREAD

**Issue by idanam-del** [sipcapture/homer#595]
hey is it possible to capture RTCP packets and not just SIP?

what needs to be configured on Freeswitch?

**Comment by kYroL01** [comment]
This is more of a FreeSWITCH question.

Anyway, you need to check the FreeSWITCH documentation on how to activate RTCP on FS side
https://developer.signalwire.com/freeswitch/FreeSWITCH-Explained/Signalling/RTCP_13173472/#about

Then you can follow our guide
https://github.com/sipcapture/homer/wiki/Examples%3A-FreeSwitch

Thanks for the star :)
