### ISSUE TITLE
How to capture media in homer-7?

### ISSUE THREAD

**Issue by PJ111288** [sipcapture/homer#598]
Hi Friends,

My goal is to capture media/voice of calls as well in homer?

Thanks,
PJ

**Comment by lmangani** [comment]
Hello @PJ111288 I'm sorry this is not possible in HOMER! We're against call interception and do not want our opensource to be weaponized against user privacy. Our approach is to do everything with numbers and statistics, without privacy invasion.

There are other tools doing this HOMER can interact with, but mind most of them are not legal. Thanks for understanding!
