### ISSUE TITLE
Sip call + Logs ?

### ISSUE THREAD

**Issue by aakuzmsk** [sipcapture/homer#599]
good morning,  here I have a log in which the data is not related to the call in any way, but I would like to see it in the call flow as log .. I tried hepipe.js but I see the data only when adding a separate tab in the widget and then as hep-log , as shown in your examples in video meetups, it doesn’t work (- what’s wrong? how to output if there is nothing to correlate the call with the log?

**Comment by lmangani** [comment]
If you'd like to us to help you need to provide full context to your request. What data? How are you reading it? How are you parsing it? How are you sending it? Describe the full circuit and we'll try to provide a suggestion. Mind the logs MUST have a correlation field to the session (callid, some header value, etc) or you won't be able to do much with it.

**Comment by aakuzmsk** [comment]
another question about mappings..
I have logs that I'm parsing and have chosen a correlation parameter for it - id_session .
there are also calls with an added header "xcid" which contains the same id_session. those. this is their common correlation field.
what should be written in the mappings so that I can see these logs in the call flow?

**Comment by lmangani** [comment]
Not sure what's the goal with adding another question before answering any clarifications on the previous?

**Comment by aakuzmsk** [comment]
> Not sure what's the goal with adding another question before answering any clarifications on the previous?

I'm sorry, the previous question can be closed. you completely answered - that without a correlation parameter, nothing will work out.

**Comment by aakuzmsk** [comment]
the second question, in principle, also falls into the sip + logs topic, so I decided to write here  0:-)

**Comment by lmangani** [comment]
> what should be written in the mappings so that I can see these logs in the call flow?

Here's a full [example](https://github.com/sipcapture/homer/wiki/Custom-Header-Searching-and-Correlation#full-example-for-2-way-correlation)

**Comment by aakuzmsk** [comment]
конечно я уже видел данный документ , но там имеется в виду поиск звонки ,  и мне непонятно как это реализовать для  отображения логов, поиск не нужен

**Comment by aakuzmsk** [comment]
of course, I have already seen this document, but it means search for calls, and it is not clear to me how to implement it to display logs, search is not needed

**Comment by lmangani** [comment]
Just change the `lookup_profile` and `lookup_id` to the desired type you want to search into.  

For example, the following correlates a callid with a log with type `100` using partition `default` 

``` 
{
    "source_field": "data_header.callid",
    "lookup_id": 100,
    "lookup_profile": "default",
    "lookup_field": "sid",
    "lookup_range": [
      -300,
      200
    ]
  }
```
