### ISSUE TITLE
installer use old kamailio.cfg

### ISSUE THREAD

**Issue by nshopik** [sipcapture/homer#60]
homer_installer.sh using old varian of kamailio.cfg, which produce errors on duplicate entries.

Should be used this one - https://github.com/sipcapture/homer/blob/master/configs/kamailio.cfg

**Comment by lmangani** [comment]
Thanks Nikolay,

The old installer will be shortly decommissioned and/or dropped to community as we switch to Homer 5 branch with its own installer attached.

**Comment by nshopik** [comment]
What so special about Homer5? I just unable find any info, what you trying to achieve with it. 

Current homer probably perfect tool for sip debug but still poor in term of stats monitoring. Only global graph/stats, but we'd like to see more per IP/destination specific stats generation.

**Comment by lmangani** [comment]
A lot is special about Homer 5 and it addresses exactly the direction you mentioned in several ways on the stats front. Maybe you should take a look at our presentations to get an idea, or just give it a go: https://github.com/sipcapture/homer/tree/homer5
