### ISSUE TITLE
User restrictions?

### ISSUE THREAD

**Issue by aakuzmsk** [sipcapture/homer#600]
whether there is a manual how restrictions to users are set? I didn’t find a description anywhere (for example, how to prevent a user / group from deleting / changing already created widget tabs?

**Comment by lmangani** [comment]
Users and user settings are provisioned and managed by [homer-app](https://github.com/sipcapture/homer-app/tree/31e9e57a5c618745d64e4bdfba778f452f5fa17b#create-user) and you can see all the insights in the code.

In general terms, widget access should be restricted to the user creating or sharing the resource.
You can experiment and report back if you find any inconsistencies. 

Thanks!
