### ISSUE TITLE
Template for loki

### ISSUE THREAD

**Issue by iamhalje** [sipcapture/homer#602]
Please help me with my questions in this situation:

1) if loki does not use authorization, is it correct to keep the pass and user settings in the config (example from webapp_config.json)

  "loki_config": {
    "api": "loki/api/v1",
    "enable": true,
    "help": "Settings for LOKI Database (optional)",
    "host": "http://localhost:3100",
    "param_query": "query_range",
    "user": "admin",
    "pass": "admin"

    
2) after viewing the damp to automatically view the log without touching anything manual, how to replace the standard job and parse in logql? (configure logql automatic query for yourself)

![loki](https://github.com/sipcapture/homer/assets/81181610/f2cffc5b-5cf6-4c11-91c8-7e4c10ae1f69)

3) from which version of the homer can you send requests to loki? (that is, when he was release version)

Thank you all in advance!

**Comment by iamhalje** [comment]
the main question of course is number 2, is there a variable to replace job heplify-server?

**Comment by iamhalje** [comment]
this will be enough if you answer question number 2, accidentally closed the ticket*

**Comment by lmangani** [comment]
> after viewing the damp to automatically view the log without touching anything manual, how to replace the standard job and parse in logql? (configure logql automatic query for yourself)

Not sure I understand. You will have to push the log search button at least once for the query to start, making this automatic would cause lots of unecessary connections for an on-demand action. You can customize the logql query selector pattern. 

@AlexeyOplachko will provide the configuration options for the logql query template.

**Comment by iamhalje** [comment]
yes, need to configure the template, for a start, at least change the standard job heplify-server, then I'm waiting for a template with parameters for logql

for example on {service=~"opensips|rtpengine"} and callid like now

**Comment by AlexeyOplachko** [comment]
We've addressed this in latest PR, new version should be released pretty soon. 
To add template you want to add property `template` in `loki_config` part of homer config.
I.e. 
```json
"loki_config": {
        "help": "Settings for LOKI Database (optional)",
        "user": "admin",
        "password": "admin",
        "param_query": "query_range",
        "regexp": false,
        "host": "http://127.0.0.1:3100",
        "template": "{job=\"heplify-server\"}",
        "external_url": "",
        "api": "loki/api/v1",
        "enable": true
    },
 ```
 Edit: We with the team thought up of an upgrade for this, will implement later today

**Comment by iamhalje** [comment]
okay, looking forward to, thanks

**Comment by AlexeyOplachko** [comment]
Update: You now are able to provide full template. I.e. if you change config to
`"{job=\"test-server\" |~ \"%callid%\"}"` it'll replace %callid% with callids from the correlated call

**Comment by iamhalje** [comment]
thanks for adding this feature.
