### ISSUE TITLE
homer-webapp inclusion

### ISSUE THREAD

**Issue by izaacmenezes** [sipcapture/homer#608]
Hello, first of all, the project was excellent!

I would like to know if it is possible to integrate the homer-webapp in the "hep-prom-graf" version, install everything correctly, but I miss the more analytical web part;

I tried in some ways but without success, could you help me please?

**Comment by lmangani** [comment]
Hello @izaacmenezes not sure I understand the question but it seems you're referring to a compose example?

In any case, I would suggest using the latest [HOMER 10 example](https://github.com/sipcapture/homer-docker) which contains the latest settings and includes everything.

**Comment by izaacmenezes** [comment]
actually it would just be a support to integrate homer-webapp into what I already have today which is "hep-prom-graf"

@lmangani
