### ISSUE TITLE
Problem installing Homer 10

### ISSUE THREAD

**Issue by inatelso** [sipcapture/homer#610]
I am trying to install the new Homer 10, through Docker, which has the following version Docker version 1.13.1, build 7d71120/1.13.1. I verify that the script is trying to download the packages and the following messages appear.

[root@localhost all-in-one]# docker-compose pull
[+] Pulling 1/9
 ✔ hepgen-bad Skipped - Image is already being pulled by hepgen                                          0.0s
 ⠸ clickhouse-server Pulling                                                                                                           1.4s
 ⠸ heplify-server Pulling                                                                                                                 1.4s
 ⠸ mailhog 7 layers [⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                    1.4s
   ⠋ df20fa9351a1 Pulling fs layer                                                                                                  0.0s
   ⠋ ed8968b2872e Pulling fs layer                                                                                                0.0s
   ⠋ a92cc7c5fd73 Pulling fs layer                                                                                                  0.0s
   ⠋ f17c8f1adafb Waiting                                                                                                              0.0s
   ⠋ 03954754c53a Waiting                                                                                                            0.0s
   ⠋ 60493946972a Waiting                                                                                                            0.0s
   ⠋ 368ee3bc1dbb Waiting                                                                                                           0.0s
 ⠸ hepgen Pulling                                                                                                                          1.4s
 ⠸ grafana Pulling                                                                                                                          1.4s
 ⠸ vector Pulling                                                                                                                            1.4s
 ⠸ qryn Pulling                                                                                                                               1.4s
 ⠸ alertman Pulling                                                                                                                        1.4s
missing signature key

Please give your support to be able to install homer 10, I am trying to install it on Centos 7.

**Comment by lmangani** [comment]
The best way to tell is to try and run the bundle. Do you have any issues when running `docker-compose up -d`?

**Comment by inatelso** [comment]
Yes, I share with you the message that I get when executing the command docker-compose up -d

[root@localhost all-in-one]# docker-compose up -d
[+] Running 0/23
 ⠼ hepgen-bad 7 layers [⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                                                                                                                          1.3s
   ⠋ 7264a8db6415 Waiting                                                                                                                                                                                                         0.0s
   ⠋ eee371b9ce3f Waiting                                                                                                                                                                                                         0.0s
   ⠋ 93b3025fe103 Waiting                                                                                                                                                                                                         0.0s
   ⠋ d9059661ce70 Waiting                                                                                                                                                                                                         0.0s
   ⠋ 8a30dc432d8d Waiting                                                                                                                                                                                                         0.0s
   ⠋ 6379ec47a6a0 Waiting                                                                                                                                                                                                         0.0s
   ⠋ 4f4fb700ef54 Waiting                                                                                                                                                                                                         0.0s
 ⠼ alertman Pulling                                                                                                                                                                                                               1.3s
 ⠼ hepgen Pulling                                                                                                                                                                                                                 1.3s
 ⠼ heplify-server Pulling                                                                                                                                                                                                         1.3s
 ⠼ grafana Pulling                                                                                                                                                                                                                1.3s
 ⠼ qryn Pulling                                                                                                                                                                                                                   1.3s
 ⠼ mailhog 7 layers [⠀⠀⠀⠀⠀⠀⠀]      0B/0B      Pulling                                                                                                                                                                             1.3s
   ⠋ df20fa9351a1 Pulling fs layer                                                                                                                                                                                                0.0s
   ⠋ ed8968b2872e Pulling fs layer                                                                                                                                                                                                0.0s
   ⠋ a92cc7c5fd73 Pulling fs layer                                                                                                                                                                                                0.0s
   ⠋ f17c8f1adafb Waiting                                                                                                                                                                                                         0.0s
   ⠋ 03954754c53a Waiting                                                                                                                                                                                                         0.0s
   ⠋ 60493946972a Waiting                                                                                                                                                                                                         0.0s
   ⠋ 368ee3bc1dbb Waiting                                                                                                                                                                                                         0.0s
 ⠼ vector Pulling                                                                                                                                                                                                                 1.3s
 ⠼ clickhouse-server Pulling                                                                                                                                                                                                      1.3s
missing signature key

**Comment by lmangani** [comment]
@inatelso i'm sorry but the information you're pasting doesn't help understand the issue

**Comment by lmangani** [comment]
@inatelso did you resolve this problem?

**Comment by SerhiiZahuba** [comment]
I had the same problem, after updating the docker version - everything worked out for me.

**Comment by andrekis** [comment]
hi all
just to report error to install homer10 all-in-one , under corporate netwok
(homer7 docker-compose.yml installs just fine)

unable to install from docker-compose up (from homer10     (path)/homer-docker/all-in-one/)

i think it pulls containers from github without problems, but not from ghcr.io

last lines show:

.....
Pulling hepgen (qxip/docker-hepgen:)...
latest: Pulling from qxip/docker-hepgen
7264a8db6415: Already exists
eee371b9ce3f: Pull complete
93b3025fe103: Pull complete
d9059661ce70: Pull complete
8a30dc432d8d: Pull complete
6379ec47a6a0: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:9b099854c276ecdbfbbc0d1eccb95e0f2c08785ed9f5321403dd557c23e7cde4
Status: Downloaded newer image for qxip/docker-hepgen:latest
Pulling heplify-server (ghcr.io/sipcapture/heplify-server:latest)...
ERROR: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n<html lang=\"en\" xml:lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\">\r\n  <head>\r\n    <title>Response denied by WatchGuard HTTP Proxy</title> \r\n    <style type=\"text/css\">\r\n      body {\r\n        font-family: Arial, Helvetica, Verdana, Sans-Serif;\r\n        font-size: small;            \r\n        font-weight: normal;            \r\n        color: #000000;\r\n      }\r\n      div {            \r\n        margin-left: auto;            \r\n        margin-right: auto;            \r\n        text-align: center;\r\n      }\r\n      .box {          \r\n        width: 600px;\r\n        background-color: #F2F2F2;            \r\n        border-left: solid 1px #C2C2C2;            \r\n        border-right: solid 1px #C2C2C2;            \r\n        vertical-align: middle;\r\n        padding: 20px 10px 20px 10px;\r\n      }\r\n      p {\r\n        text-align: left;\r\n      }\r\n      .red {\r\n        font-weight: bold;\r\n        color: Red;\r\n        text-align: center;\r\n      }\r\n      .band {            \r\n        height: 20px;\r\n        color: White;\r\n        background: #333333;\r\n        width: 600px;\r\n        border-left: solid 1px #333333;\r\n        border-right: solid 1px #333333;\r\n        padding: 3px 10px 0px 10px;\r\n      }\r\n      div#wrap {\r\n        margin-top: 50px;\r\n      }\r\n    </style>\r\n  </head>\r\n  <body> \r\n    <div id=\"wrap\">\r\n      <div class=\"band\"></div>\r\n      <div class=\"box\">\r\n        <p class=\"red\">Response denied by WatchGuard HTTP Proxy.</p>\r\n        <p><b> Reason: </b> all proposed authentication schemes denied </p>\r\n        <p>Please contact your administrator for assistance.</p>\r\n        <p>More Details:</p>\r\n        <p><b>Method:</b> GET</p>\r\n        <p><b>Host:</b> ghcr.io</p>\r\n        <p><b>Path:</b> /v2/sipcapture/heplify-server/manifests/latest</p> \r\n      </div>\r\n      <div class=\"band\">WatchGuard Technologies, Inc.</div>\r\n    </div>\r\n  \r\n</body>\r\n</html>"


thanks

**Comment by naqashsaeed** [comment]
Yes, I also face the same issue with the docker version` 1.13.1`, as this docker version is bugged Then I update docker to
 version` 25.0.1` and its all working fine.

**Comment by kYroL01** [comment]
Thanks @naqashsaeed for the test!

@andrekis can you please open a dedicated issue for that, just to don't mix subject so we can focus directly on your problem? thank you!
