### ISSUE TITLE
homer UI only displaying 200 records

### ISSUE THREAD

**Issue by behram-x** [sipcapture/homer#617]
Hi ALL,

i have a problem with homer UI as it only displays 200 records for all dates, i'm unable to figure out whether the issue is with DB settings or UI setting, i'm unable to find the setting through which i can get all the saved packets on homer UI.

**Comment by lmangani** [comment]
It's not a bug its a feature. There's a LIMIT field with a default value of 200.

**Comment by behram-x** [comment]
> It's not a bug its a feature. There's a LIMIT field with a default value of 200.

i'm unable to find it can you please help in this regard ?

**Comment by lmangani** [comment]
- Edit the search form
- Drop the `limit` parameter to the active column
- Fill the limit field with any new desired value

**Comment by behram-x** [comment]
> * Edit the search form
> 
>     * Drop the `limit` parameter to the active column
> 
>     * Fill the limit field with any new desired value

found it, many thanks :)
