### ISSUE TITLE
Heplify-server doesn't insert HEP packets from Kamailio siptrace

### ISSUE THREAD

**Issue by hopefulGiupplo** [sipcapture/homer#622]
Hello, I have set up an environment with Kamailio 5.6.0, and wanted to use Homer7 via the siptrace module. The problem is that the heplify server seems to receive the packets sent by Kamailio, but doesn't insert them in the postgres database.

Some more information:

- Kamailio sends HEP3/SIP packet to the right socket of heplify-server, and those packets are recognized by wireshark. However, heplify-server logs a WARN saying it receives malformed packets. I'll include my kamailio setup below, but let me know if this should be an issue for the Kamailio mailing list, rather than here.
- A tcpdump on the homer machine shows that packets arrive, and wireshark can decode the pcap capture without problems
- the Heplify-server doesn't even try to insert the packets it receives into the postgres database, seems like it ditches them.
- Using heplify on kamailio machine, instead of siptrace, everything works.

My kamailio setup:
```
# ----- siptrace params -----
#!ifdef WITH_HOMER
modparam("siptrace", "duplicate_uri", "sip:MY_HOMER_MACHINE:9060")
modparam("siptrace", "send_sock_address", "sip:MY_KAMAILIO_MACHINE:5060")
modparam("siptrace", "hep_mode_on", 1)
modparam("siptrace", "hep_version", 3)
modparam("siptrace", "trace_to_database", 0)
modparam("siptrace", "trace_mode", 5)
modparam("siptrace", "trace_on", 1)
#!endif
```
Routing logic:

```
request_route {
    #!ifdef WITH_HOMER
    sip_trace_mode("t");
    hlog("Logging info to Homer.");
    #!endif
...
}

```

I'm uploading homer.pcap (github doesn't support pcap extension, so it will be linked from google drive), that is the result of a tcpdump listening to port 9060 on Homer's VM, and the logs from the Heplify-server.
Thank you for your assistance.
[heplify-server.log](https://github.com/sipcapture/homer/files/13487622/heplify-server.log)
[homer.pcap](https://drive.google.com/file/d/1E10g5J57cKkDiSTzSDaTvi2e0sACsufV/view?usp=sharing)

**Comment by lmangani** [comment]
My first bet is on `trace_mode` being the issue. Why is it set to 5?

https://www.kamailio.org/docs/modules/5.6.x/modules/siptrace.html#siptrace.p.trace_mode

**Comment by hopefulGiupplo** [comment]
It was set to 5 because we wanted to activate options 1 and 4, and documentation led us to believe it was a bit-based choice. Anyways, now I set it to 1 and the tables are still empty. I'm attaching the new pcap traces and the heplify-server logs.
[heplify-server.log](https://github.com/sipcapture/homer/files/13488947/heplify-server.log)
[Homer tcpdump listening on port 9060](https://drive.google.com/file/d/1cM9EXNCC5wKuM2MxfjG_expljZBNI8k3/view?usp=sharing)
[Kamailio tcpdump listening on port 5060](https://drive.google.com/file/d/1uPLUMM3XlBT1yKZxPsokA5FrvD0-5YeA/view?usp=sharing)

**Comment by hopefulGiupplo** [comment]
I managed to fix it, thank you for your help
