### ISSUE TITLE
Web UI possiility to reset password on first sign-in  and maybe delete support user

### ISSUE THREAD

**Issue by os11k** [sipcapture/homer#628]
Hi,

Homer7 web UI has a bit of outdated for username/password setup, which is basically hardcoded to be admin/sipcapture. Would be very nice to have possibility to set it up from variable in docker-compose as for Grafana or DB and maybe force to change on first sign in. Additionally would be nice to have such option for a user, when you create user, add checkbox to force user to reset. 

I'm not sure why support user is there, but I think it must be disabled by default, I think sometimes it maybe overlooked and left there with default password on...

**Comment by lmangani** [comment]
There's no real hardcoded parameters, but rather a script with defaults you can change and customize in your own build. 
homer-app is the process creating and managing users and user authentication as per [readme](https://github.com/sipcapture/homer-app?tab=readme-ov-file#create-user)

You can essentially create a setup without any default users, and then create them with your own logic/values/

This being said, internal user management is very basic indeed. Any contributions are welcome or you can use external auth.

Edit: if you need suggestions let us know or join up the matrix channel to discuss it
