### ISSUE TITLE
Question on RTPProxy HEP module

### ISSUE THREAD

**Issue by jagnetta** [sipcapture/homer#635]
Good day,

Regarding the configuration parameters shown here:
https://github.com/sipcapture/homer/wiki/Examples-RTPPROXY

We're running rtpproxy 3.0.  I've been searching to see if the parameters have changed at all since the example provided.

I am not seeing HEP leave the RTPEngine server, only the opensips HEP. 

If you have any guidance on this, please advise.

Thanks,
Jim

**Comment by lmangani** [comment]
Hi Jim! The best way is to refer to the relevant project documentation as of the current settings required. The RTPProxy instructions in the Wiki are based on the [RTPProxy integration test code](https://github.com/sippy/rtpproxy/blob/master/tests/acct_rtcp_hep/basic.conf) which still looks as follows: 

```
modules {
    acct_rtcp_hep {
        load = ../modules/acct_rtcp_hep/.libs/rtpp_acct_rtcp_hep_debug.so
        capt_host  = 127.0.0.1
        capt_port  = %%HEP_PORT%%
        capt_ptype = %%HEP_PROTO%%
        capt_id = 101
    }
}
```

Perhaps the .so module does not exist in your setup?

**Comment by jagnetta** [comment]
Hi Lorenzo,

Thanks for the reply, we have the module, it's in a different path, but maybe it's not loaded, I'll investigate.  To confirm, the setting "capt_host" should be the address of the homer server that will receive the HEP, yes?

Thanks,
Jim

**Comment by lmangani** [comment]
That's correct!

**Comment by jagnetta** [comment]
Thanks,  you can close the ticket....  I appreciate it!

**Comment by lmangani** [comment]
No problem! Please ACK the bot and remember to give us a github star to support the project ⭐
