### ISSUE TITLE
Cutting SIP and SDP header in HEP ​​message

### ISSUE THREAD

**Issue by matuskaacc** [sipcapture/homer#639]
I'm noticing that when the SIP message collected for the captagent is a little larger, is cutting out part of the header and the entire SDP body in the HEP message sent to the heplify-server. Does anyone know if there is any configuration in the captagent that could cause this behavior?

**Comment by matuskaacc** [comment]
The Frame  size of  Invite SIP Message is 1352 Bytes and i'am noticing that the size of hep package is limited to a maximum of 1624 bytes. i don't see packer bigger than this size sent from captagent to heplify-server

**Comment by kYroL01** [comment]
Hi @matuskaacc this is an issue for **captagent**, please open it here https://github.com/sipcapture/captagent/issues

Anyway, try to enable reassembling in the agent config 
[reasm](https://github.com/sipcapture/captagent/blob/master/conf/socket_pcap.xml#L8) 
and
[tcpdefrag](https://github.com/sipcapture/captagent/blob/master/conf/socket_pcap.xml#L10)
