### ISSUE TITLE
Homer empty with asterisk 17

### ISSUE THREAD

**Issue by roni-segal-tc** [sipcapture/homer#645]
Installed homer and this it what im seeing
Hep doesn't seem to be sent from Asterisk.
Homer version 7.10.34
![image](https://github.com/sipcapture/homer/assets/155433941/b1fefd44-b6da-4577-957a-f1d1fbff6f3a)

**Comment by lmangani** [comment]
@roni-segal-tc sorry but you're providing nothing we can help with. I guess you have no data.
Start by making sure you configured your hep agent correctly and make sure you see hep packets going into homer. 
If you see it coming and nothing shows, remember to open firewall ports etc
