### ISSUE TITLE
Debian packages missing in the official repository

### ISSUE THREAD

**Issue by xaled1** [sipcapture/homer#649]
Hi 

In debian-repository of homer:
https://packagecloud.io/qxip/sipcapture/

There is no "heplify-server" for debian bullseye and no packets at all for debian bookworm.

Is this planned or a mistake?

**Comment by lmangani** [comment]
You should use the [any/any](https://packagecloud.io/qxip/sipcapture/packages/any/any/heplify-server_1.59.7_amd64.deb?distro_version_id=35) repository. Heplify-Server is statically compiled and has no other requirements, so all deb packages are essentially the same package. Everything else you see with a specific OS distribution is legacy stuff.

**Comment by xaled1** [comment]
Got it, thank you.
