### ISSUE TITLE
Homer5 roadmap

### ISSUE THREAD

**Issue by vasyl-shumskyi** [sipcapture/homer#65]
Hey guys,

What's the roadmap for homer5? I see its in beta2 now and actively developed.  When do you approximately plan to have stable release out?

Thanks!

**Comment by vasyl-shumskyi** [comment]
Found some info, but that's very likely beta related.. If not stable should be out pretty soon..

// Andrew, we will release a new H5 and Captagent6 in less than 2 weeks. There is a lot changes including table performance. If you can wait, it will be awesome.

**Comment by linuxmaniac** [comment]
Use the mailing list please, this is _NOT_ an issue
https://groups.google.com/forum/#!forum/homer-discuss
