### ISSUE TITLE
Homer 7 at Docker - Rotate logs

### ISSUE THREAD

**Issue by pablohssilva** [sipcapture/homer#654]
Hi.
How can I do to clean a postgresql database without crash the aplication?

Is there a less invasive way?

I saw that there is an option in the homer WEB page "Admin Settings > Reset > Local Storage" Would this button be used to clean the logs sent by HEPlify?

I need a way to rotate these logs.

My scenario:
I installed homer 7 from the link:
https://github.com/sipcapture/homer/wiki/Quick-Install#-docker-install

Then I downloaded "HEPlify: https://github.com/sipcapture/heplify/releases" on another host to send the packages to homer

**Comment by bilalrao12** [comment]
@pablohssilva Below ENVs in heplify-server container can be used to rotate the homer data in postgresql.

- "HEPLIFYSERVER_DBROTATE=true"
- "HEPLIFYSERVER_DBDROPDAYS=5"
- "HEPLIFYSERVER_DBDROPONSTART=true"
