### ISSUE TITLE
Call Flow is flow of SIPs overtime not flow of sips of a call (HOMER10)

### ISSUE THREAD

**Issue by bazrafshanmh** [sipcapture/homer#657]
As described in the title, the call flow dashboard in homer10 is the flow of multiple SIPs over a limited time, (and it has the log messages too!) not a a great thing like the homer7 and Wireshark's call flow.

**Comment by lmangani** [comment]
This is still very much a WIP so all feedback is useful, but like most users transitioning and in absence of docs I think most are missing the point. The flow-view acts on a filter (like any other widget) returning and by restricting what the filter shows you get the same effect. The example offers a mixed view but by all means it can display only SIP messages and/or sessions, etc by query. 

The view in Grafana is like a "looking glass" we can use to display a single session, live traffic, relations between different types, CDRs and so on. Regular homer-only things will carry on in the homer-interface once we reach API stability.

**Comment by bazrafshanmh** [comment]
thanks, Solved
