### ISSUE TITLE
A way to clear the data in homer10 (grafana)

### ISSUE THREAD

**Issue by bazrafshanmh** [sipcapture/homer#658]
Is there a way to clear the data in Grafana dashboards from now on?

**Comment by lmangani** [comment]
I do not understand your question. Could you articulate more or provide an example?

**Comment by bazrafshanmh** [comment]
Think about when your dashboard is messy and you want to make it clean and don't want to set an end date for the time.

**Comment by lmangani** [comment]
I still don't uderstand. Dashboards use variables (such as timerange, filters) and those can be set to defaults when saving, if that's what you mean? Unless you save the dashboard in Grafana and/or provide URL parameters it will go back to the saved defaults.

**Comment by bazrafshanmh** [comment]
In Wireshark, you can "restart current capture" to clean the view. Is there any alternative way to do this in Grafana/Home10?

**Comment by lmangani** [comment]
Yes, by resettings the time filters and enabling autorefresh you would get a similar effect. But since we're working with stored data there's no such thing as restarting a capture, you can only modify the filters and time range. hope this helps.

**Comment by bazrafshanmh** [comment]
Thanks! 
Isn't there any way to work with the databases and clear one table's contents?
