### ISSUE TITLE
Multi-value selection in destination and source of calls in call flow dashboard

### ISSUE THREAD

**Issue by bazrafshanmh** [sipcapture/homer#659]
Is there a restriction that restricts you from enabling multi-value parameter in src-ip and dst-ip?

**Comment by lmangani** [comment]
HOMER 10 uses qryn, which itself implements the LogQL query language, used in this context. Please refer to the [LogQL syntax](https://qryn.metrico.in/#/guide/logql) documentation to understand what can and cannot be done. It is equally important to understand the "tags" data inserts. For label selection you can use regex to match multiple patterns, or use the pipe separator.

**Comment by bazrafshanmh** [comment]
I meant [this](https://github.com/user-attachments/assets/729f4ab0-6746-4ba7-b570-22f3bf549707)

**Comment by bazrafshanmh** [comment]
You said right but what I said is I think a good way to give users the ability to use Homer more easily

**Comment by lmangani** [comment]
I appreciate the input! This is still a technical preview so there are no bells and whistles but in general, we're more about making users into experts rather than making things easy ;)

**Comment by bazrafshanmh** [comment]
A nice philosophy 😄
