### ISSUE TITLE
Setting Up Homer 10 with Kamailio and SipCapture for SIP Monitoring

### ISSUE THREAD

**Issue by bazrafshanmh** [sipcapture/homer#663]
Hello, and sorry for taking up your time
Since I did not find complete and correct sources and documents for my question, I am now raising it here

Can you provide a way to use the XRTP dashboard in Homer 10 using Kamailio? In that dashboard, no panel has data, and also in Prometheus, there are no metrics with the names mentioned in the query.

The best way I've found is to use sipcapture instead of siptrace, which I needed help finding proper documentation on how to use it.

**Comment by lmangani** [comment]
Hello @bazrafshanmh and thanks for the question. the answer is simple - the XRTP dashboard requires the clients to send `X-RTP-Stat` data in the SIP signaling. If this is the case, statistics will display. Note this is not connected to any other RTCP/RTP feature.

Hope this helps!

**Comment by bazrafshanmh** [comment]
Do you mean that my softphone should support this sip header? 
Do you know any softphone (or sip-stack) that supports this?

**Comment by lmangani** [comment]
@bazrafshanmh baresip comes to mind, but its not that common. Yes the phone has to send the stats in a header and/or RTCP-XR SIP packets, etc.
