### ISSUE TITLE
Grafana监控homer数据教程

### ISSUE THREAD

**Issue by baipengbo** [sipcapture/homer#664]
我现在homer部署好了，我想通过Grafana监控分析一些数据，现在没找到相关两个怎么打通得教程，我用Prometheus不知道怎么采集homer数据，homer这边需要部署什么来给Prometheus采集数据，整个教程那位能给指导分享下，感谢

**Comment by lmangani** [comment]
您可以按照这个完整的示例进行操作: https://github.com/sipcapture/homer-docker/tree/main/all-in-one

**Comment by baipengbo** [comment]
> 您可以按照此完整示例进行操作：https://github.com/sipcapture/homer-docker/tree/main/all-in-one

非常感谢回复，但是这个教程教了咋部署，还是没说怎么把数据跟grana监控采集，谢谢

**Comment by lmangani** [comment]
是的。它包含数据源、示例、将 HOMER 连接到 Prometheus/qryn 和 Grafana 的查询。抱歉，我们不会说中文，请用英文发帖，谢谢！

**Comment by baipengbo** [comment]
Hello,

I am currently facing some issues while setting up Homer and Heplify, and I hope you could provide some assistance.

Current Environment Description
Homer and Heplify are installed on the same server.
Prometheus and Grafana are installed on a separate server.
My objective is to use Prometheus to scrape data from Heplify's port 9060 and then visualize this data in Grafana.
Current Issues

Prometheus Unable to Scrape Data:

When attempting to scrape data from Heplify's port 9060 using Prometheus, the request fails, and the port seems unreachable.
I have verified that the Heplify service is running, and the configuration file sets listen_address to 0.0.0.0:9060 within the metrics section. However, when testing with curl http://localhost:9060/metrics, I receive a Connection refused error.
Checking the port listening state with netstat shows no record of port 9060 being bound.
The system firewall is disabled, and SELinux is not blocking the port binding.

Missing RTCP Data Capture:

Currently, Homer does not capture RTCP data.
I am looking for documentation or guidelines on how to configure Homer to capture RTCP data.
Request for Assistance

Could you please assist with the following:

How can I ensure that Heplify correctly exposes its metrics endpoint so that Prometheus can collect data?
Is there any documentation or guidance available for configuring Homer to capture RTCP data?

Thank you very much for your help! I look forward to your response.

Best regards,










在 2024-09-27 17:40:44，"Lorenzo Mangani" ***@***.***> 写道：

是的。它包含数据源、示例、将 HOMER 连接到 Prometheus/qryn 和 Grafana 的查询。抱歉，我们不会说中文，请用英文发帖，谢谢！

**Comment by baipengbo** [comment]
Hello,

I am currently facing some issues while setting up Homer and Heplify, and I hope you could provide some assistance.

Current Environment Description
Homer and Heplify are installed on the same server.
Prometheus and Grafana are installed on a separate server.
My objective is to use Prometheus to scrape data from Heplify's port 9060 and then visualize this data in Grafana.
Current Issues

Prometheus Unable to Scrape Data:

When attempting to scrape data from Heplify's port 9060 using Prometheus, the request fails, and the port seems unreachable.
I have verified that the Heplify service is running, and the configuration file sets listen_address to 0.0.0.0:9102 within the metrics section. However, when testing with curl http://localhost:9102/metrics, I receive a Connection refused error.
Checking the port listening state with netstat shows no record of port 9102 being bound.
The system firewall is disabled, and SELinux is not blocking the port binding.

Missing RTCP Data Capture:

Currently, Homer does not capture RTCP data.
I am looking for documentation or guidelines on how to configure Homer to capture RTCP data.
Request for Assistance

Could you please assist with the following:

How can I ensure that Heplify correctly exposes its metrics endpoint so that Prometheus can collect data?
Is there any documentation or guidance available for configuring Homer to capture RTCP data?

Thank you very much for your help! I look forward to your response.

Best regards,







在 2024-09-27 17:40:44，"Lorenzo Mangani" ***@***.***> 写道：

是的。它包含数据源、示例、将 HOMER 连接到 Prometheus/qryn 和 Grafana 的查询。抱歉，我们不会说中文，请用英文发帖，谢谢！

**Comment by lmangani** [comment]
> My objective is to use Prometheus to scrape data from Heplify's port 9060 and then visualize this data in Grafana.

There is some confusion. Only `heplify-server` offers a metrics endpoint to scrape. Our [example](https://github.com/sipcapture/homer-docker/blob/main/all-in-one/docker-compose.yml#L181) clearly shows this part of the configuration as well as every other element. You must follow the compose example to achieve your purpose.

Please follow the docker example as it answers all of your configuration and logic questions 👍

**Comment by baipengbo** [comment]
Hello, I have installed the relevant services using Docker, and now I want to monitor SIP mouse through Grafana, using ClickHouse as the data source. Do I need to write SQL queries for this? I saw some SIP metric templates related to Homer on the Grafana website; can I use them directly? Below are the services I have deployed. Please provide relevant guidance. Thank you!

![模板](https://github.com/user-attachments/assets/cb43e31a-fab9-4c15-8db8-f6c1f51e5670)


![docker部署](https://github.com/user-attachments/assets/503659f5-3897-4628-a133-e74687cc7a5f)
![clickhouse](https://github.com/user-attachments/assets/f8eec1f3-cb23-489d-b918-ca7f945488f3)
