### ISSUE TITLE
NEED HELP ABOU CALL RECORDINGS

### ISSUE THREAD

**Issue by solusaas-git** [sipcapture/homer#670]
I have configured the RTPproxy server as described in the manual, but still can't have recording on the FTP server. 

please assist me with a correct config

here is a sample of pcap trace :

| No.  | Time     | Source IP      | Destination IP | Protocol  | Length | Message                                                                                                                               |
|------|----------|----------------|----------------|-----------|------|---------------------------------------------------------------------------------------------------------------------------------------|
| 446  | 0.546720 | 176.9.26.121   | 88.99.195.187  | RTPproxy  | 200  | Request: Delete an active session (Bye/Cancel/Error), Call-ID: 624fb6eb5f931eff4a17b67f56c5d7f4@176.9.26.114-b2b_2-1-0, Tag: d907bb3a1a419f491794ad539b616a75, Tag: e9cdcfae9ac930997854267b79b9d5d7 |
| 447  | 0.546912 | 88.99.195.187  | 176.9.26.121   | RTPproxy  | 79   | Reply: 0                                                                                                                             |
| 662  | 0.813382 | 167.235.12.121 | 88.99.195.187  | RTPproxy  | 79   | Request: Information b                                                                                                               |
| 663  | 0.813426 | 88.99.195.187  | 167.235.12.121 | RTPproxy  | 195  | Reply: sessions created: 10146 active sessions: 16 active streams: 32 packets received: 1926924 packets transmitted: 1926924        |
| 748  | 0.919836 | 176.9.26.121   | 88.99.195.187  | RTPproxy  | 79   | Request: Information b                                                                                                               |
| 749  | 0.919939 | 88.99.195.187  | 176.9.26.121   | RTPproxy  | 195  | Reply: sessions created: 10146 active sessions: 16 active streams: 32 packets received: 1927008 packets transmitted: 1927008        |
| 790  | 0.968132 | 176.9.26.121   | 88.99.195.187  | RTPproxy  | 79   | Request: Information b                                                                                                               |
| 791  | 0.968238 | 88.99.195.187  | 176.9.26.121   | RTPproxy  | 195  | Reply: sessions created: 10146 active sessions: 16 active streams: 32 packets received: 1927048 packets transmitted: 1927048        |
| 1153 | 1.419286 | 176.9.26.121   | 88.99.195.187  | RTPproxy  | 79   | Request: Information b                                                                                                               |
| 1154 | 1.419383 | 88.99.195.187  | 176.9.26.121   | RTPproxy  | 195  | Reply: sessions created: 10147 active sessions: 17 active streams: 34 packets received: 1927408 packets transmitted: 1927408        |
| 1212 | 1.488047 | 176.9.26.121   | 88.99.195.187  | RTPproxy  | 219  | Request: Offer/Update, Call-ID: 224b20e92b600a2e199686e07144ff02@176.9.26.114-b2b_1-1-0, IP: 185.76.20.69:46122, Tag: 6e8a047a0709c445d06f49cfe3506ab1, Tag: cd7cfd6d9462c7538bfb123b32e6e29f |
| 1213 | 1.488140 | 88.99.195.187  | 176.9.26.121   | RTPproxy  | 83   | Reply: 47220[Malformed Packet]                                                                                                       |
| 1404 | 1.723831 | 167.235.12.121 | 88.99.195.187  | RTPproxy  | 79   | Request: Information b                                                                                                               |
| 1405 | 1.723939 | 88.99.195.187  | 167.235.12.121 | RTPproxy  | 195  | Reply: sessions created: 10147 active sessions: 17 active streams: 34 packets received: 1927655 packets transmitted: 1927655        |
| 1621 | 1.986756 | 176.9.26.121   | 88.99.195.187  | RTPproxy  | 79   | Request: Information b                                                                                                               |
| 1622 | 1.986871 | 88.99.195.187  | 176.9.26.121   | RTPproxy  | 195  | Reply: sessions created: 10147 active sessions: 16 active streams: 32 packets received: 1927870 packets transmitted: 1927870        |
| 1623 | 1.990228 | 176.9.26.121   | 88.99.195.187  | RTPproxy  | 79   | Request: Information b                                                                                                               |
| 1624 | 1.990326 | 88.99.195.187  | 176.9.26.121   | RTPproxy  | 195  | Reply: sessions created: 10147 active sessions: 16 active streams: 32 packets received: 1927870 packets transmitted: 1927870        |
| 1968 | 2.417300 | 176.9.26.121   | 88.99.195.187  | RTPproxy  | 193  | Request: Offer/Update, Call-ID: 5eb08334597b7daa6e0dabe02b52ee24@194.32.76.119:5060-b2b_1-1-0, IP: 194.32.76.119:19418, Tag: 7d0d63d838e188b1a2d1124b4988fdcf |
| 1969 | 2.417470 | 88.99.195.187  | 176.9.26.121   | RTPproxy  | 83   | Reply: 46686[Malformed Packet]                                                                                                       |
| 1975 | 2.423244 | 176.9.26.121   | 88.99.195.187  | RTPproxy  | 79   | Request: Information b                                                                                                               |
| 1976 | 2.423364 | 88.99.195.187  | 176.9.26.121   | RTPproxy  | 195  | Reply: sessions created: 10148 active sessions: 16 active streams: 32 packets received: 1928218 packets transmitted: 1928218        |
| 2273 | 2.793834 | 167.235.12.121 | 88.99.195.187  | RTPproxy  | 79   | Request: Information b                                                                                                               |
| 2274 | 2.793955 | 88.99.195.187  | 167.235.12.121 | RTPproxy  | 195  | Reply: sessions created: 10151 active sessions: 19 active streams: 38 packets received: 1928514 packets transmitted: 1928514        |
| 2451 | 3.009614 | 176.9.26.121   | 88.99.195.187  | RTPproxy  | 79   | Request: Information b                                                                                                               |
<img width="1677" alt="Capture d’écran 2024-10-31 à 22 23 58" src="https://github.com/user-attachments/assets/a0b1a225-d12d-4878-b931-be45717a782e">

**Comment by lmangani** [comment]
I'm sorry HOMER doesn't do any RTP recording or FTP uploading. Perhaps the question was for another project?

**Comment by solusaas-git** [comment]
oh sorry i posted in wrong repo it was about RTPproxy, can you help me with it please, i'm stucked and neet it

**Comment by lmangani** [comment]
I'm sorry we can't help you with this problem, but I'm sure the RTPProxy community will
