### ISSUE TITLE
Suggestion - homer-app module be removed from homer10 branch

### ISSUE THREAD

**Issue by jaikishanwadhawa** [sipcapture/homer#674]
Since homer-app git repository mentions,
HOMER 7.x Front-End and API Server
can we remove it from homer-10 branch to avoid confusion ?

Please correct me if my understanding is wrong.

https://github.com/sipcapture/homer/pull/673

**Comment by lmangani** [comment]
Thanks @jaikishanwadhawa but not sure why this was proposed. Could you elaborate? HOMER 10 is just a public demo note a release
