### ISSUE TITLE
rotate.sh on Homer5 reference wrong script names

### ISSUE THREAD

**Issue by albersag** [sipcapture/homer#71]
Its references 

new_table="$bin_dir/homer_mysql_new_table.pl"
programm="$bin_dir/homer_mysql_partrotate_unixtimestamp.pl"

But on /script directory its names are 

new_table.pl

partrotate_unixtimestamp.pl

i had to rename to :

-rwxr-xr-x  1 root root 6564 jul 28 08:29 homer_mysql_new_table.pl
-rwxr-xr-x  1 root root 5105 jul 28 08:30 homer_mysql_partrotate_unixtimestamp.pl

**Comment by adubovikov** [comment]
Thanks!

fixed .

https://github.com/sipcapture/homer-api/commit/07af05081a9b0dcf6f393c8463b782d2834d32e0
