### ISSUE TITLE
Some search requests got from date '1970-01-01 07:00:00'

### ISSUE THREAD

**Issue by smith51** [sipcapture/homer#73]
I found that some search search requests got from date '1970-01-01 07:00:00'/ For example, I searched alerts. And this URL

`https://homer.internal.site/index.php?method=500&location[]=1&node=&from_date=2015-07-30&from_time=16:-1:30&to_date=2015-07-30&to_time=16:0:30&limit=100&task=result&component=search`

was transformed to this select:

`SELECT id
FROM sip_capture
WHERE (
`date`
BETWEEN '1970-01-01 07:00:00'
AND '2015-07-30 16:00:30'`

**Comment by adubovikov** [comment]
Your from_time is wrong, it could not be negative value

**Comment by smith51** [comment]
This URL was generated by HOMER, I didn't make requests bu hands. So please look at code requests that generating from Alerts.

**Comment by adubovikov** [comment]
please provide name and version of your browser.

**Comment by smith51** [comment]
I am using Seamonkey version 2.30. I'll try to use Google Chrome latest version.

**Comment by smith51** [comment]
OK, I got another "bad" calls. The difference is 9 hours. It's very strange - why this difference. I am living in Siberia, Russia, UTC+7, not +9.

This URL was generated by Seamonkey and it's contains "negative" time:
`https://homer.internal.site/index.php?method=500&location[]=1&node=&from_date=2015-08-04&from_time=-1:59:02&to_date=2015-08-04&to_time=0:59:02&limit=100&task=result&component=search`

This URL was generated by Google Chrome and it's contains right time:
`https://homer.internal.site/index.php?method=500&location[]=1&node=&from_date=2015-08-04&from_time=8:59:02&to_date=2015-08-04&to_time=9:59:02&limit=100&task=result&component=search`

**Comment by adubovikov** [comment]
probably this is js issue of Seamonkey ?

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer/blob/master/configs/kamailio.cfg#L430

you
