### ISSUE TITLE
Too Many 400 - No data available in table

### ISSUE THREAD

**Issue by smith51** [sipcapture/homer#75]
I have some Alarms about "Too Many 400" but I can't see this records because SIP messages of status "400" not recording to sip_capture table. I am using latest git version of Homer 3.6 and default config.

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer/blob/master/configs/kamailio.cfg#L244

https://github.com/sipcapture/homer/blob/master/configs/kamailio.cfg#L413

as u see you check real status and increase counter base on this condition. Please check your sip_capture table.

**Comment by smith51** [comment]
Thanks, I fixed my config and can see 'status 400' records. It's very strange but my config was missed some sections from default config. Maybe it's because I am used old config.
