### ISSUE TITLE
WARNING: sl [../../modules/tm/tm_load.h:148]: load_tm_api(): Cannot import load_tm function from tm module

### ISSUE THREAD

**Issue by smith51** [sipcapture/homer#83]
Found this warnings and errors in log file:

Aug  5 11:08:44 homerserver /usr/local/kamailio/sbin/kamailio[28429]: ERROR: sipcapture [sipcapture.c:812]: mod_init(): insert_retry_timeout has no meaning when insert_retries is not set
Aug  5 11:08:44 homerserver /usr/local/kamailio/sbin/kamailio[28429]: WARNING: sl [../../modules/tm/tm_load.h:148]: load_tm_api(): Cannot import load_tm function from tm module
Aug  5 11:08:44 homerserver /usr/local/kamailio/sbin/kamailio[28429]: WARNING: sl [../../modules/tm/tm_load.h:148]: load_tm_api(): Cannot import load_tm function from tm module
Aug  5 11:10:44 homerserver /usr/local/kamailio/sbin/kamailio[28441]: ERROR: <script>: TIME : 0
Aug  5 11:15:44 homerserver /usr/local/kamailio/sbin/kamailio[28441]: ERROR: <script>: TIME : 5
Aug  5 11:20:44 homerserver /usr/local/kamailio/sbin/kamailio[28441]: ERROR: <script>: TIME : 0
Aug  5 11:25:44 homerserver /usr/local/kamailio/sbin/kamailio[28441]: ERROR: <script>: TIME : 5

a lot of `ERROR string` made by 5 minutes interval.

What does it mean? I am using git version of Homer 3.6 made at Jul 30.

**Comment by adubovikov** [comment]
this is not homer's issue, please check your configs...

**Comment by smith51** [comment]
Found this warnings and errors in log file:

`
Aug  5 11:10:44 homerserver /usr/local/kamailio/sbin/kamailio[28441]: ERROR: <script>: TIME : 0
Aug  5 11:15:44 homerserver /usr/local/kamailio/sbin/kamailio[28441]: ERROR: <script>: TIME : 5
Aug  5 11:20:44 homerserver /usr/local/kamailio/sbin/kamailio[28441]: ERROR: <script>: TIME : 0
Aug  5 11:25:44 homerserver /usr/local/kamailio/sbin/kamailio[28441]: ERROR: <script>: TIME : 5`

a lot of `: ERROR: <script>: TIME : ` string made by 5 minutes interval.

What does it mean? I am using git version of Homer 3.6 made at Jul 30.

**Comment by smith51** [comment]
Module tm presented in modules directory:

> ll /usr/local/kamailio/lib64/kamailio/modules/tm.so
-rwxr-xr-x 1 root root 1736179 Июл 30 20:00 /usr/local/kamailio/lib64/kamailio/modules/tm.so

**Comment by adubovikov** [comment]
https://github.com/sipcapture/homer/blob/master/configs/kamailio.cfg#L430

you can disable this log output

**Comment by smith51** [comment]
Please answer about load_tm function from tm module. I am using config from https://github.com/sipcapture/homer/blob/master/configs/kamailio.cfg , tm.so presented in modules directory. I found a lot of "Cannot import load_tm" substring in kamailio binaries. I used install script to compile and install Homer.

**Comment by adubovikov** [comment]
you can ignore this.
