### ISSUE TITLE
RTCP Statistics aren't showed in call flow when using multiple nodes

### ISSUE THREAD

**Issue by kemathy** [sipcapture/homer#9]
We're using two capture nodes, separated with Homer webUI, and when we try to look at the RTCP Stats for a call, we've got a popup with "No Data".

We found in the file api/class/search.php, that the line 129 "$rows = $mydb->loadObjectList($query.$order);" of showRtcpAll function doesn't return any result, even if the database are well filled with rtcp captures.
We activated some debug to get the SQL request Homer generates before, and tried to execute this request manually ; it returns results. The problem doesn't seem to be on the SQL side.
Also, we found that Homer is trying to execute the SQL request on localhost, and not on the node where it found the call flow.

**Comment by adubovikov** [comment]
can you please check the last git ?

**Comment by kemathy** [comment]
It works only if the node on which the call has been captured is defined in the configuration.php file. 
If the call has been captured on another node, it doesn't work (got an access denied SQL error).
It's in the right way :-)

**Comment by adubovikov** [comment]
ok, rtcp and sip are on the different nodes ? This means, you don't know which node you should query... need do foreach over all.  For performance is not good :-(

**Comment by kemathy** [comment]
No, Rtcp and SIP are one the same node...

--
Kevin MATHY

**Comment by kemathy** [comment]
I think it's related, but I'm facing another problem : 
I've got in configuration.php HOMER_HOST configured with one of my capture node's IP (eg. 10.84.9.45)
I search for a call captured by this node, having rtcp data (checked manually in rtcp_capture table), and when I click on "RTCP info" in his call-flow, I just get a blank page. No alert this time, just blank... I took a look at the GET's response received by my brother, and it seems that there is data (cf. screenshot attached).
First, I thought of a browser fail, but I tried with both Firefox and Safari, and it's all the same.
If you need me to do more tests, feel free to ask ;-) 
Thanks, 
Kevin
![capture1](https://cloud.githubusercontent.com/assets/7022659/5798260/1525ef52-9fc6-11e4-82b0-2a7b18706e76.jpg)

**Comment by adubovikov** [comment]
done.
