### ISSUE TITLE
not able to make HEP working via tcp 

### ISSUE THREAD

**Issue by gmaruzz** [sipcapture/homer#94]
Hello,

I'm trying to enable transmission of hep via tcp.

Homer side, from default config (instaled by instalkler) I commented out disable_tcp=yes and added a line listen=tcp:192.168.1.131:5060 (eg: same line as per udp).

Restarted, and it reports to listen on both tcp and udp, correct ports.

On captagent I changed the line in core_hep.conf section of config to read:
            <param name="capture-proto" value="tcp"/>
(only changed from udp to tcp), but it does not work.

It all works in udp.

What am I doing wrong?

thanks in advance,

-giovanni

**Comment by gmaruzz** [comment]
xml line was eaten by markup support.
On captagent I changed the line in core_hep.conf section of config to read (bracket deleted):

            param name="capture-proto" value="tcp"/

**Comment by adubovikov** [comment]
currently sipcapture module in kamailio/opensips has only HEP UDP support.

**Comment by gmaruzz** [comment]
ok, thanks a lot!
:)
